### ISSUE TITLE
Checkbox name prop added to the label, not the input

### ISSUE THREAD

**Issue by rogerso** [react-toolbox/react-toolbox#1001]
The name prop is being added to the label component instead of the actual input component inside Checkbox.

This is probably caused by 091a1fa38a0c4c684ec4f371b62a572f304a4f08. Therefore this probably affects RadioButton too.

**Comment by javivelasco** [comment]
Thanks! I've changed it again to spread props on input but keeping onMouse enter and leave into the label, this way the tooltip will still work :)
