### ISSUE TITLE
Browser Compatibility

### ISSUE THREAD

**Issue by esdu** [react-toolbox/react-toolbox#1002]
Hey folks, I'm planning to use react-toolbox for a new project. Is there a Browser Compatibility chart anywhere? I can't seem to find one. Thanks!

**Comment by samsch** [comment]
There is #260, which says IE11 and Edge on the MS side.

**Comment by javivelasco** [comment]
Closed on favor of #260 We should integrate something like BrowserStack. I've already wrote them but I need to integrate it
