### ISSUE TITLE
Number input invalid value display

### ISSUE THREAD

**Issue by samsch** [react-toolbox/react-toolbox#1003]
In Firefox, if you use an input with `type="number"`, and enter a non-number, the value property of the input is reported as "" (string of length 0).

In react-toolbox Input, this leads to the component thinking it's empty, so the label is slid back down behind the invalid text.

**Comment by javivelasco** [comment]
What would you suggest to fix this? Looks like a shitty workaround in FF

**Comment by samsch** [comment]
I'm honestly not sure. For my original case, I switched to a text input. I just wanted to bring some attention to this issue.

A similar problem/case is noted with Angular in this [StackOverflow question](http://stackoverflow.com/questions/32649779/firefox-cant-clear-invalid-number-field-with-angular), and some more general description and work arounds are here [How to get the raw value an \<input type=“number”\> field?](http://stackoverflow.com/questions/18852244/how-to-get-the-raw-value-an-input-type-number-field)

I haven't dived into the Input code to know if a css-based workaround is helpful.

**Comment by javivelasco** [comment]
I've been trying it out and it looks very difficult to fix from the library. You can initially leave the value undefined but then, after typing a bit, you'll see that the empty input leads to an empty string. There is no way to distinguish then an empty input from a wrong typed input.

My piece of advice: react toolbox does not handle the state for you. In the onChange callback you can figure out if it's a number and then parse it appropriately. For example, if it is an input and you get something different, just don't set the value and the input won't get shown. 

I'm closing, honestly I think there is nothing we can do better than this :)
