### ISSUE TITLE
timepicker - cannot change hours

### ISSUE THREAD

**Issue by drummerhu** [react-toolbox/react-toolbox#1007]
I can't change the hours, it changes back to the original value.
I can change the minutes, but only every 2nd click works.
I tried to debug it, componentWillUpdate changes back the state, but I can't fix it.
(Can be reproduced on the demo site - http://react-toolbox.com/#/components/time_picker )
(last known working version: 1.2.1)

**Comment by javivelasco** [comment]
A typo writing the lifecycle method. I'm releasing a patch asap
