### ISSUE TITLE
1st of January is absent in the date picker calendar

### ISSUE THREAD

**Issue by Anna-Pogribnyak** [react-toolbox/react-toolbox#1008]
![screenshot 2016-11-30 15 30 45](https://cloud.githubusercontent.com/assets/9572273/20754102/03154528-b712-11e6-8d96-cea8ea9d042e.png)

**Comment by javivelasco** [comment]
@Anna-Pogribnyak I can't reproduce with the latest release. Please update because I think this is solved! I've tried at http://react-toolbox.com/#/components/date_picker and it works
