### ISSUE TITLE
Open to eslint config improvements?

### ISSUE THREAD

**Issue by nathanmarks** [react-toolbox/react-toolbox#101]
Just curious if you're open to an `.eslintrc` related pull request. I'd like to add some rules to help with consistency in syntax and better practices (in my opinion at least).

I totally get that a lot of this is personal preference and you may not want any changes made, if you want I can create a PR with some added rules and you can check them out and see what you think.

For example:

#### Current config:
![image](https://cloud.githubusercontent.com/assets/4420103/11108640/91064692-88b6-11e5-9e43-8cff8bf45ec6.png)

#### With some additional rules:
![image](https://cloud.githubusercontent.com/assets/4420103/11108706/306047c4-88b7-11e5-8395-a51c1b0104ad.png)

**Comment by javivelasco** [comment]
ESlint configuration is really personal but what you've detected is a problem of consistency anyway. I'm going to add the rule. IYO better with or without spaces for JSX curly braces?

**Comment by nathanmarks** [comment]
@javivelasco All official react examples and popular libs are without spaces in JSX curly braces, I'd stick with that convention.

If I suggested specific eslint rules 1 by 1 with examples, would that help you consider them?

Some of them will actually just enforce styling that **you already follow** but contributors may not.

**Comment by javivelasco** [comment]
Great, sounds perfect!

**Comment by soyjavi** [comment]
@nathanmarks sounds good +1

**Comment by NogsMPLS** [comment]
perhaps this might be of use?

https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb

**Comment by javivelasco** [comment]
It's interesting, we can take a look on it and grab rules I think

**Comment by javivelasco** [comment]
@nathanmarks Suggestions to improve the eslint config?

**Comment by javivelasco** [comment]
@nathanmarks I'm closing the issue. Feel free to PR some changes to the eslint configuration but I think we have more or less the config you suggested in the first place. I'm closing to reduce noise
