### ISSUE TITLE
Tree view

### ISSUE THREAD

**Issue by AntonyBaasan** [react-toolbox/react-toolbox#1010]
We need at our project an advanced tree view. Something similar to this one:
https://angular-ui-tree.github.io/angular-ui-tree/#/basic-example

Do you have the plan to do this component in a roadmap?

**Comment by javivelasco** [comment]
I didn't saw it in the spec. If it isn't, we are not implementing it officially. There is a similar component which is the `List` with nesting though. That will be implemented as soon as we release the postcss version

**Comment by razakj** [comment]
Hi, i use react-toolbox for one of our projects (thanks for the great library) where we found ourselves in need of a tree-view component for handling larger data sets and keep the feel of material design at the same time. If someone's interested have a look here https://github.com/razakj/rt-treeview

(Again the component isn't as per material design specs but rather to handle our own use case - Larger data sets and performance)
