### ISSUE TITLE
Menu docs value property

### ISSUE THREAD

**Issue by samsch** [react-toolbox/react-toolbox#1015]
The [menu docs](http://react-toolbox.com/#/components/menu) example has a `value` property on each MenuItem, which doesn't appear to exist either in the component code or docs.

I'm guessing this is a left-over from an older version or a copy-paste mistake?

**Comment by samsch** [comment]
Ok, I found it. Menu uses the value prop of the child directly via cloneElement.

I would be great if this system was explained in the docs. There is a mention of the selection system working similar to List, however the List docs also do not explain the value property (which appears in the List example as well).

**Comment by javivelasco** [comment]
Actually I'm not very happy wit this behavior. If you know outside the component which value is selected you can also add the styles yourself in the item that is currently selected. This logic would not be needed inside the component any longer. For this reason I think it's better to keep it uncovered and drop it in the future.
