### ISSUE TITLE
Passing integer value to autocomplete doesn't work

### ISSUE THREAD

**Issue by azimgd** [react-toolbox/react-toolbox#1016]
Following code will fail with an error
```
const countriesObject = {3: 'asd', 'ES-es': 'Spain', 'TH-th': 'Thailand', 'EN-gb': 'England', 'EN-en': 'USA'};

<Autocomplete
    source={countriesObject}
    multiple={false}
    value={3}
/>
```

uncaught at eventName TypeError: (rawQuery || "").toLowerCase is not a function

basically here -> https://github.com/react-toolbox/react-toolbox/blob/5c248720b773881fa221ef6c9ad5737e40a11c30/components/autocomplete/Autocomplete.js#L184

**Comment by javivelasco** [comment]
For the record: I'm sick of this component. It's getting so damn complex. It's going to be refactored very soon
