### ISSUE TITLE
Switch is not compatible with fastclick

### ISSUE THREAD

**Issue by landabaso** [react-toolbox/react-toolbox#1018]
This is not a bug within react-toolbox.

The Switch element in react-toobox is basically: `<label><input></label>`.
There are issues in FastClick under this situation: https://github.com/ftlabs/fastclick/issues/60

FastClick is still pretty popular so it's worth it to take a look.

Even though this is not an bug in react-toolbox there's an easy fix that react-toolbox could apply:
Right now this is how I fix it:

```
@import 'node_modules/react-toolbox/lib/switch/theme';
//FastClick does not work well with react-toolbox Switch since a switch has a label + input inside
//https://github.com/ftlabs/fastclick/issues/60
.field {
  & > * { pointer-events: none; }
}
```
As you can see Switch works well with fastClick when adding that: ` & > * { pointer-events: none; }` on the field class.

@javivelasco close this issue if you think it's not worth it adding that style just for the sake of some compatibility. At least the issue will be here for anyone that searches and finds the problem in the future.

**EDIT: The Ripple fx stops working when applying that fix. So I definitely think it's not idea to fix it as is unless you come with a better idea.**

**Comment by javivelasco** [comment]
Thanks for reporting @landabaso, I think it's going to be useful for people digging into this.

I didn't know fastclick but if the solution can come with CSS you can always pass a theme down to apply the patch so thanks for your comment. I also think that applying the patch in react-toolbox would be a little out of scope. This shouldn't be rt responsibility :)

Thanks!
