### ISSUE TITLE
Compilation Fail

### ISSUE THREAD

**Issue by Hello-Zeze** [react-toolbox/react-toolbox#1019]
After adding react-toolbox to a react project created using react-cli "create-react-app", I get the following error message:

Failed to compile.                                                                                                               
                                           
Error in ./~/react-toolbox/lib/app_bar/theme.scss                                                                                
Module parse failed: c:\_Development\Tuts\React-Toolkit\rtk\node_modules\react-toolbox\lib\app_bar\theme.scss Unexpected character '@' (1:0)                                                                                                                      
You may need an appropriate loader to handle this file type.                                                                     
SyntaxError: Unexpected character '@' (1:0)                                                                                      
 @ ./~/react-toolbox/lib/app_bar/index.js 16:13-36 

This is my webpack.config.js file:

const path = require('path');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
    context: __dirname,
    entry:{
        app:'./src/index.js'
    },
    output:{
        path: path.join(___dirname, 'dist'),
        filename:'bundle.js'
    },
    resolve:{
        extensions:['','.scss','.js','.json']
    },
    module:{
        loaders:[
            {
                test:/\.(scss|css)$/,
                loader: ExtractTextPlugin.extract("style-loader", "css-loader")
            }
        ]
    }
};

**Comment by wtgtybhertgeghgtwtg** [comment]
See #707.
