### ISSUE TITLE
cpx does not copy .css to .lib on build

### ISSUE THREAD

**Issue by pekkah** [react-toolbox/react-toolbox#1021]
#666 the build task does not work on Windows command prompt as the cpx command does not copy the .css files to .lib. Running it using Bash command prompt works.

**Comment by pekkah** [comment]
Channging the css script in package.json to `"css": "cpx \"./components/**/*.css\" ./lib"` fixes the problem (also gives you output of files copied with -v).

**Comment by javivelasco** [comment]
May you PR this fix?
