### ISSUE TITLE
Allow proptype object for ListItem caption

### ISSUE THREAD

**Issue by nicklee1990** [react-toolbox/react-toolbox#1025]
I believe the caption prop on the ListItem should accept an object (e.g. JSX) rather than only a string as only accepting a string prevents formatting this string through CSS. I'm sure there's other use cases as well. I can look at a doing a PR if this is considered worthwhile?

**Comment by javivelasco** [comment]
For me it's ok, PR! :)

**Comment by javivelasco** [comment]
Done!

**Comment by nicklee1990** [comment]
great stuff!
