### ISSUE TITLE
Samsung default browser not displaying material icons

### ISSUE THREAD

**Issue by k0r8i** [react-toolbox/react-toolbox#1026]
Anyone ever experienced issues regarding google's Icons in combination with Samsung default Browser? Just got the Screenshots from a friend's phone, trying to get hold of a Samsung phone/browser myself.
![img-20161204-wa0001](https://cloud.githubusercontent.com/assets/17675159/20866625/b356be9a-ba31-11e6-8cc0-eb506432cc61.jpg)
![img-20161204-wa0002](https://cloud.githubusercontent.com/assets/17675159/20866626/b95d04e8-ba31-11e6-8feb-e3912be8f59e.jpg)

**Comment by javivelasco** [comment]
This is very very specific. It would be great if we find a fix though.

**Comment by k0r8i** [comment]
I got hold of a Samsung phone and experimented a bit with material-icons css class selector.
When adding
```
.material-icons{
        -webkit-font-feature-settings: 'liga';
        -moz-font-feature-settings: 'liga';
        font-feature-settings: 'liga';
      }
```
all buttons work as expected.

**Comment by javivelasco** [comment]
I'm sure this is going to be helpful for a lot of people, thanks!! :)
