### ISSUE TITLE
Time picker not working. Moving hour hand is not changing hour value.  Reference: http://react-toolbox.com/#/components/time_picker

### ISSUE THREAD

**Issue by himanshu0511** [react-toolbox/react-toolbox#1028]
Reproduction steps:
1- Go on link http://react-toolbox.com/#/components/time_picker
2- start Playground.
3- try to change hours by moving hour hand in time picker.
4- change is not reflected in hours section of time, it is reverted back to its original value.

Cause of problem: Depencency chain is causing time picker to not work properly. i.e. one of depencency is still in previous version.

How I solve it:
Solution 1: remove directory node_modules and reinstall dependencies
Solution 2: use yarn instead of npm

**Comment by javivelasco** [comment]
Fixed!
