### ISSUE TITLE
Scrollable Dropdowns have no visual indication of additional hidden content

### ISSUE THREAD

**Issue by q3452** [react-toolbox/react-toolbox#1029]
....unless a row of text is partially clipped by the border which offers a hint.

Scrollbars would be ideal and according to #589, compliant with spec.  However they're non-trivial to include and naive attempts seem to cause all sorts of weirdness in the control.

I'm at a bit of a loss as to how to easily offer the user some indication that they can scroll to additional content.

Any suggestions?

**Comment by javivelasco** [comment]
I guess you can always modify the overflow property to show a scroll when the list of options is scrollable. I was wondering if maybe it is worthy to create an HOC for scrollable content. It may generate issues but visually components would look prettier. Opinions?

**Comment by javivelasco** [comment]
Also, following #1020, scrollable content should allow to navigate using keyboard. I have an implementation of an HOC that allows to move through a list with the keyboard handling scrolling and all. The scroll can be just an indicator in the side of the affected wrapper. There is stuff that needs to be done before getting into this but yes, it should be solved

**Comment by q3452** [comment]
Modifying the overlow is problematic (or was for me anyway) because the list is itself an overflow of the Dropdown div which isn't resized for content.  The <ul> has a max-height of 45vh but once we give it scroll bars, it conforms to the parent height which is much smaller.  Also, there's some width issue that causes horizontal scroll bars as soon as the vertical scrollbar is consuming any space in the ul's element.

Admittedly, I'm not particularly strong with CSS so these might be solvable issues but certainly, it was starting to look like an extensive fork of the code to implement rather than a few lines of CSS.

**Comment by javivelasco** [comment]
Closed in favor of #1169

**Comment by paddotk** [comment]
@javivelasco I'm not sure what you mean by your last comment. Is the scrollbar going to be there at some point? Is there a way to manually override this myself? (Setting overflow:auto on any of the divs or ul doesn't work).

**Comment by paddotk** [comment]
I made a PR to fix this issue. The issue has been around for some time and has pretty harsh effects, since users do not know the dropdown lists contain more items.
See https://github.com/react-toolbox/react-toolbox/pull/1885
