### ISSUE TITLE
Breaking Changes to the Tabs Components in v1.3.0

### ISSUE THREAD

**Issue by jasonleibowitz** [react-toolbox/react-toolbox#1031]
I was previously using [v1.2.5](https://github.com/react-toolbox/react-toolbox/releases/tag/1.2.5) and recently upgraded to [v1.3.0](https://github.com/react-toolbox/react-toolbox/releases/tag/1.3.0). In my project I'm using the tabs component with theme overrides for styling. 1.3.0 introduced some breaking changes due to a change in DOM structure for this component. 

The release notes for v1.3.0 don't mention this and I wanted to ensure that anyone that ran into this problem like I did would find something about this. 

The specific commit that caused the change is #975. For anyone else having this issue please note that the DOM structure for the Tabs component is slightly different now.  

I would also suggest adding an example of the new Tabs Navigation into [the documentation](http://react-toolbox.com/#/components/tabs). 

cc: @therealparmesh

**Comment by javivelasco** [comment]
Sorry about the breaking change @jasonleibowitz. I'm committing this new year to publish a Roadmap and to be more careful about the Changelogs. The documentation is going to change soon with new examples and an awesome design. That will be the perfect moment :)
