### ISSUE TITLE
Is it possible to add a custom component in a Table ?

### ISSUE THREAD

**Issue by thomasthiebaud** [react-toolbox/react-toolbox#1037]
Is it possible to add a custom component in a Table ? So it will be possible to add Buttons, Checkbox or more complex react component ? 

- Is it possible to add then in the model, so it will be available for a full column ?
- Is it possible to add it as a value for a single row (in this case the model can contains something like `{ type: Component }` ?

**Comment by vmsoftware** [comment]
I think yes, 

By the way, the best option is to use the new table implementation. See [https://github.com/react-toolbox/react-toolbox/tree/css-next/components/table](https://github.com/react-toolbox/react-toolbox/tree/css-next/components/table)

You can add any component inside `TableCell` component, something like this:

`<TableCell><ANY_COMPONENT/></TableCell>`

I hope it works!

**Comment by thomasthiebaud** [comment]
I can not make it work with the current version. Does `css-next` correspond to the `version 2.0` ? I can not use the beta because I'm working on production code, but I will switch when it is release.
