### ISSUE TITLE
css files missing in version 2.0.0-beta.1

### ISSUE THREAD

**Issue by sea129** [react-toolbox/react-toolbox#1038]
version: 2.0.0-beta.1
Windows 10

I just installed the very new release. The css files in /lib/animations/ and the variables.css are missing. webpack can't find them. It may be related to #1021

**Comment by javivelasco** [comment]
Yeah sorry, this version adds a transform step to reduce boilerplate on your side. I missed copying those css that don't belong to any component. I'm fixing it tomorrow, thanks for reporting!

**Comment by legomind** [comment]
just a polite bump :-)

**Comment by kjg531** [comment]
+1

**Comment by x4080** [comment]
Is this already solved? Theres log somewhere about the version 2? Using purecomponent now?

**Comment by javivelasco** [comment]
I'm publishing a new release with this just now

**Comment by x4080** [comment]
What is the new version ? I use npm show react-toolbox@* version and the latest is still 1.3.2

**Comment by sea129** [comment]
@x4080 new version should be 2.0.0-beta.2
try npm view react-toolbox versions

**Comment by x4080** [comment]
@sea129 thanks I'll try

**Comment by x4080** [comment]
Hi, I install react toolbox example and update the react toolbox to 2.0.0-beta.2, but after updating it wont run, there's a breaking change ? the $palette-xxx variable is not exists now

**Comment by javivelasco** [comment]
@x4080 Update to 2.0.0-beta.4

**Comment by x4080** [comment]
Thanks I'll check it out
