### ISSUE TITLE
Worrying lack of changelogs for updates.

### ISSUE THREAD

**Issue by Klathmon** [react-toolbox/react-toolbox#1043]
I hate to make this issue, but it's starting to become a problem that we are seeing a significant amount of updates but never any explanation on what is in them, what changed, or what was fixed.

It looks like the last update that had a real explanation was 1.1.0 and 1.1.1 After that they are just released without any info and we are forced to look through commit logs and issues to figure out what changed. And in a few of them we have had issues, and are struggling to find out if/when they are fixed.

This is an annoyance for a normal library, but for something like react-toolbox which is so ingrained in the applications you build with it that it's not easily replaced, it becomes very worrying.

Is there somewhere that you are recording changelogs and fixed bugs that we are missing? Can we expect them to return?

And is there anywhere that you are documenting your future plans for the library? So we can understand what might be getting removed/changed and act accordingly?

Finally, I know maintaining an open-source library isn't easy. You have been doing a wonderful job on this library, and it's been a massive help to us developing applications. So if there is anything that we can do to help out in this area, please let me know! I'm more than willing to help sort through commits, manage changelogs, or whatever else you need to help. This library is extremely useful, and I want to help it stay that way for others.

**Comment by x4080** [comment]
Ahh its not just me then :)

**Comment by javivelasco** [comment]
I gave an answer to this at [HN](https://news.ycombinator.com/item?id=13192088). Don't worry, from now on I will be writing detailed Changelogs and I will try to be more transparent on development and plans. Recall, there is a ROADMAP now that you can check to see the direction in which we are moving. I also opened an [Open Collective site](https://opencollective.com/react-toolbox) for anybody that wants to back the project.

**Comment by Klathmon** [comment]
I sincerely appreciate the work done in this area. The new roadmap is fantastic and so much more than what I was looking for, so thank you!
