### ISSUE TITLE
Null error and blank page with IE10

### ISSUE THREAD

**Issue by tumetus** [react-toolbox/react-toolbox#1047]
I am getting the following error in my app when using IE 10: "Unable to get property 'composeTheme' of undefined or null reference" and the browser just renders a blank page. 

![pic1](https://cloud.githubusercontent.com/assets/3472062/21155326/6bd5f932-c17a-11e6-8687-0831e90b9d8d.PNG)

I guess this is kind of specific case and without more info might be hard to solve. So I tested the react-toolbox homepage with IE10 and when I tried to open the components page (http://react-toolbox.com/#/components) it also rendered a blank page with same kind of error: "Unable to get property 'bold' of undefined or null reference".

![pic2](https://cloud.githubusercontent.com/assets/3472062/21155327/6bda979e-c17a-11e6-8e35-bd9aefb5e79e.PNG)

Tested with react-toolbox 1.2.3 and 1.3.2.

**Comment by tuckerconnelly** [comment]
This is because of https://github.com/javivelasco/react-css-themr/issues/37 I think

**Comment by javivelasco** [comment]
Fixed, thanks @tuckerconnelly

**Comment by tumetus** [comment]
Thank you!
