### ISSUE TITLE
Table Documentation does not match Implementation

### ISSUE THREAD

**Issue by DragosRotaru** [react-toolbox/react-toolbox#1049]
The Documentation  needs to be fixed for the table component!!! its not up to speed with how the implementation is currently. I just spent 30 minutes trying to figure out why the Table wont accept `model` and `source` props and I looked in the code to find out those are gone and now there is TableHead and TableCell and TableRow. 

The Documentation in question: http://react-toolbox.com/#/components/table

**Comment by sea129** [comment]
@DragosRotaru I think the doc on react-toolbox.com is still for version 1.x.x, new doc is here https://github.com/react-toolbox/react-toolbox/blob/2.0.0-beta.2/components/table/readme.md.

However, another problem is that all table components are not exported, I have to import them from 'react-toolbox/lib/table'

**Comment by DragosRotaru** [comment]
Thanks alot! what a dufus I am..  In regards to the need to import the subcomponents, that is a standard pattern across most if not all react UI libraries. It makes sense to import things as you need them.
