### ISSUE TITLE
Adding a global button click delay?

### ISSUE THREAD

**Issue by alltom** [react-toolbox/react-toolbox#105]
Most of the Buttons in my app perform actions that cause the Button to disappear (dismiss some information, change modes, etc). So when I tap a Button with my touch pad, the mouseDown and click events happen so close together that I never get to see any of the Ripple animation. It's actually a little disconcerting.

Any tips on how I might add a global delay for click events on Buttons?

I thought I'd sub-class or fork Button, but react-toolbox uses Button a lot internally as well (in Navigation, in particular), so that wouldn't get all the buttons.

I thought of patching Button, but I don't know how I'd make that configurable, because I'm sure most people want buttons that react immediately.

**Comment by lycon2014** [comment]
This sounds great mterestmgw

**Comment by soyjavi** [comment]
Hi @alltom In my opinion **the best option** is handle the delay in the callback of `onClick`, but if you think is better create a property like `delay` we are open to any proposal. 

best,

javi

**Comment by alltom** [comment]
Thanks, good suggestions. It looks like I'll have to manually decorate every affected button no matter which strategy I choose, so I may as well go the non-invasive route and wrap my onClick callbacks with a delay.

**Comment by javivelasco** [comment]
I think it's ok to add a `delay` prop to delay the `onClick` callback if you need it.
Wouldn't that be a solution @alltom ?
