### ISSUE TITLE
Tool-tip is not working with RadioButton

### ISSUE THREAD

**Issue by Raathigesh** [react-toolbox/react-toolbox#1050]
When a `RadioButton` component is decorated with a `Tooltip`, the RadioButtons are no longer clickable and `onChange` on `RadioGroup` is no longer firing. 

Any pointers would be helpful!

**Comment by SleeplessByte** [comment]
Decorate a Tooltip with a Radio Button instead (i.e. nest the tooltip inside the Radiobutton).

**Comment by Raathigesh** [comment]
@SleeplessByte Tooltip allows you to decorate other components. But can the tooltip be used as a standalone component? If you could provide a snippet, it would be helpful.

**Comment by SleeplessByte** [comment]
@Raathigesh I think this was changed in 1.3+

```JSX
<RadioButton label='SomeLabel' value='some-value'>
  <TooltipLink label='?' tooltip='Some extra information about this button' />
</RadioButton>
```

Before 1.3 (like 1.2.5.) you'll get:
```
input is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`. Check the render method of RadioButton.
```

**Comment by Raathigesh** [comment]
@SleeplessByte  Thank you. But unfortunately this solution is not working. The tooltip is not properly aligned.

**Comment by SleeplessByte** [comment]
Screenshot or it didn't happen. Works fine here.

**Comment by Raathigesh** [comment]
Here you go! My expectation is to have the tooltip on top of the radio button instead of an additional `?`.

![image](https://cloud.githubusercontent.com/assets/3108160/21388047/8d59a0e6-c7a0-11e6-8d4c-e1aca3d619f0.png)

**Comment by SleeplessByte** [comment]
Right. That's not what we do for the simple reason that mobile users won't see it until they click the button.

**Comment by javivelasco** [comment]
@Raathigesh If you want to add the tooltip to the RadioButton it is possible indeed but tweaking a bit with CSS. The Tooltip is just an HOC that adds some properties to a component so it appears when you mouse enter. I understand you want to add it to the Radio element but it is hidden for encapsulation purposes. You can do multiple things to get it working as you want:

- Pass a custom theme to the tooltip to align it on the left but it will still work on mouse enter over the label.
- Add an element just with the purpose of aligning it over the Radio. Try this in the playground:

```jsx
const TooltipDiv = Tooltip('div')

const style = {
	position: 'absolute',
  height: 20,
  width: 20,
  top: 0
}

class RadioTest extends React.Component {
  state = {
    value: 'vvendetta'
  };

  handleChange = (value) => {
    this.setState({value});
  };

  render () {
    return (
      <RadioGroup name='comic' value={this.state.value} onChange={this.handleChange}>
        <RadioButton label='The Walking Dead' value='thewalkingdead'>
        	<TooltipDiv style={style} tooltip="This is Walking Dead" />
        </RadioButton>
        <RadioButton label='From Hell' value='fromhell' disabled/>
        <RadioButton label='V for a Vendetta' value='vvendetta'/>
        <RadioButton label='Watchmen' value='watchmen'/>
      </RadioGroup>
    );
  }
}

return <RadioTest />;
```
