### ISSUE TITLE
Web page not opening

### ISSUE THREAD

**Issue by asifalikhokhar** [react-toolbox/react-toolbox#1052]
The web page http://react-toolbox.com is not opening, it is only loading a blank page.
![react-toolbox](https://cloud.githubusercontent.com/assets/11837568/21199433/563491d8-c265-11e6-9952-a554c7d5216e.png)

**Comment by javivelasco** [comment]
It was a problem with react-css-themr. It should work now :)

**Comment by asifalikhokhar** [comment]
Thanks (Y)
