### ISSUE TITLE
Understanding the code base

### ISSUE THREAD

**Issue by sagar12861** [react-toolbox/react-toolbox#1053]
Hey I'm very new to react-toolbox. The code base of this project inspired me a lot. I'm trying to understand the code base much better. May know the reason behind using react propTypes instead other tools like flow or other language like type script ? I just want to know the philosophy behind that.

**Comment by javivelasco** [comment]
I'd love to adopt Flow but I have no experience and need to get started with it. Contributions on this are very welcome but here no particular reason behind not using it more than lack of experience :)
