### ISSUE TITLE
css could not work with webpack.

### ISSUE THREAD

**Issue by BrickXu** [react-toolbox/react-toolbox#1054]
Hi all,

I meet a problem when I use webpack to build my react app:
```
  [279] ./~/react-toolbox/lib/button/theme.css 879 bytes {0} [built] [1 error]

ERROR in ./~/css-loader!./~/react-toolbox/lib/button/theme.css
Module build failed: Error: composition is only allowed when selector is single :local class name not in ".raised", ".raised" is weird
    at /home/xulei/MyWorkSpaces/react_toolbox/node_modules/css-loader/node_modules/postcss-modules-scope/lib/index.js:26:13
    at Array.map (native)
    at getSingleLocalNamesForComposes (/home/xulei/MyWorkSpaces/react_toolbox/node_modules/css-loader/node_modules/postcss-modules-scope/lib/index.js:20:26)
    at /home/xulei/MyWorkSpaces/react_toolbox/node_modules/css-loader/node_modules/postcss-modules-scope/lib/index.js:106:26
    at /home/xulei/MyWorkSpaces/react_toolbox/node_modules/css-loader/node_modules/postcss/lib/container.js:198:28
    at /home/xulei/MyWorkSpaces/react_toolbox/node_modules/css-loader/node_modules/postcss/lib/container.js:148:26
    at Rule.each (/home/xulei/MyWorkSpaces/react_toolbox/node_modules/css-loader/node_modules/postcss/lib/container.js:114:22)
    at Rule.walk (/home/xulei/MyWorkSpaces/react_toolbox/node_modules/css-loader/node_modules/postcss/lib/container.js:147:21)
    at Rule.walkDecls (/home/xulei/MyWorkSpaces/react_toolbox/node_modules/css-loader/node_modules/postcss/lib/container.js:196:25)
    at /home/xulei/MyWorkSpaces/react_toolbox/node_modules/css-loader/node_modules/postcss-modules-scope/lib/index.js:105:12
    at /home/xulei/MyWorkSpaces/react_toolbox/node_modules/css-loader/node_modules/postcss/lib/container.js:241:28
    at /home/xulei/MyWorkSpaces/react_toolbox/node_modules/css-loader/node_modules/postcss/lib/container.js:148:26
    at Root.each (/home/xulei/MyWorkSpaces/react_toolbox/node_modules/css-loader/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/home/xulei/MyWorkSpaces/react_toolbox/node_modules/css-loader/node_modules/postcss/lib/container.js:147:21)
    at Root.walkRules (/home/xulei/MyWorkSpaces/react_toolbox/node_modules/css-loader/node_modules/postcss/lib/container.js:239:25)
    at /home/xulei/MyWorkSpaces/react_toolbox/node_modules/css-loader/node_modules/postcss-modules-scope/lib/index.js:101:9
 @ ./~/react-toolbox/lib/button/theme.css 4:14-69
```

here is my `webpack.config.js`:
```
const HtmlWebpackPlugin = require('html-webpack-plugin');

const HTMLWebpackPluginConfig = new HtmlWebpackPlugin({
  template: `${__dirname}/public/index.html`,
  filename: 'index.html',
  inject: 'body',
});

module.exports = {
  entry: './src/Main.js',
  output: {
    path: './dist',
    filename: 'bundle.js'
  },
  module: {
    loaders: [{
      test: /\.less$/,
      loader: 'style-loader!css-loader!less-loader'
    }, {
      test: /\.css$/,
      loader: 'style-loader!css-loader'
    }, {
      test: /\.js$/,
      loader: 'babel-loader',
      exclude: /node_modules/,
      query: {
        "presets": ["es2015", "react", "stage-1"]
      }
    },{
        test: /\.scss$/,
        include: [
          /node_modules\/react-toolbox/,
        ],
        loader: 'style-loader!css-loader!sass-loader'
      }]
  },
  devServer: {
    inline: true,
    port: 8000,
  },
  plugins: [HTMLWebpackPluginConfig],
};
```

I'm not very good at front-end stack, and I googled this error message but nothing works for me, could anyone told me how to fix this problem ?

Thanks.

**Comment by willianribeiro** [comment]
I'm having the same problem

**Comment by Rajiv-Kulkarni** [comment]
I am having the same problem too. I added react-toolbox to the react-slingshot starter and just tried to add  a button from their demo components page.

**Comment by kurtharriger** [comment]
You need to change your css-loader configuration in webpack to enable modules.  For example:

        loader: 'style!css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass'

**Comment by Rajiv-Kulkarni** [comment]
The icons are not coming through on the buttons. I am using the same buttons example from the react-toolbox.com button components page: http://react-toolbox.com/#/components/button

![image](https://cloud.githubusercontent.com/assets/12962858/21286379/b8bd23ac-c417-11e6-936f-26b9b552c2e5.png)

**Comment by Rajiv-Kulkarni** [comment]
How do I get this icon to show up:
<Button icon='bookmark' label='Bookmark' accent />

**Comment by BrickXu** [comment]
@kurtharriger thanks, I will try it later.

**Comment by javivelasco** [comment]
This is a classic. You need to add configuration parameters for css modules. Please check the [example repository](http://github.com/react-toolbox/react-toolbox-example). Also, I encourage you all to migrate to the PostCSS version. It's still labeled as a beta and there are some breaking changes like `Table` and `Layout` but it's going to be merged soon. Recall you don't need webpack anymore if you don't want it or you find it troublesome:

![react-toolbox-themr](https://cloud.githubusercontent.com/assets/1634922/21305836/285a092a-c5ce-11e6-8ad4-7b170dc97d1b.gif)

Check [react-toolbox-themr](https://github.com/react-toolbox/react-toolbox-themr). I'm publishing a migration guide soon

**Comment by BrickXu** [comment]
@javivelasco  coooool example !!!!!

**Comment by willianribeiro** [comment]
Thank You guys! It's working for me!

For reference, I follow this steps:

1. Install react-toolbox from npm: 
```npm install react-toolbox@2.0.0-beta.4```

2. Update the loader on my webpack config responsible for css files:

```
/* from this: */

module: {
    loaders: [
        {
            test: /\.css$/,
            loader: 'style!css?importLoaders=1!postcss'
        }
    ]
}
```

```
/* to this: */

module: {
    loaders: [
        {
            test: /\.css$/,
            loader: 'style!css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass'
        }
    ]
}
```

3. After that two steps React Toolbox is already working (You can use as showed [here](https://github.com/react-toolbox/react-toolbox#basic-usage) ), but They assume You have [Material Design Icons](https://material.io/icons) configured in your project. 
There are two ways to configure it, the simplest way is add a <link> tag in your `index.html`:

```
<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
```

**Comment by willianribeiro** [comment]
@Rajiv-Kulkarni, Your icons are not working probably because You didn't do step 3.

**Comment by devdlabs** [comment]
@willianribeiro is that webpack-2 ?

**Comment by willianribeiro** [comment]
@devdlabs, no, it's webpack 1.13.2

**Comment by Rajiv-Kulkarni** [comment]
Thanks. The icons are now showing up. The tooltip example didn't work for me though. Maybe I am not doing it right. Thanks.

**Comment by Rajiv-Kulkarni** [comment]
Can React-Toolbox live with React-Bootstrap? Thanks.

**Comment by Rajiv-Kulkarni** [comment]
Never mind about the tooltip. It sees to be working fine. Thanks.

**Comment by Rajiv-Kulkarni** [comment]
So far, React-Toolbox and React-Bootstrap seem to be working ok together:
![image](https://cloud.githubusercontent.com/assets/12962858/21325974/56dc2998-c5ee-11e6-94ba-b18353e384c2.png)

![image](https://cloud.githubusercontent.com/assets/12962858/21325988/654c026e-c5ee-11e6-81ca-fbe2810caa9a.png)

What could be the possible collisions? Thanks.

**Comment by javivelasco** [comment]
Not at all, everything should work fine. React Toolbox uses CSS Modules so there is no chance of collisions at all
