### ISSUE TITLE
Not getting the IconButton to display icon

### ISSUE THREAD

**Issue by Rajiv-Kulkarni** [react-toolbox/react-toolbox#1057]
I am trying to use react-toolbox in the react-slingshot starter kit. I am trying to display an IconButton similar to the one on the react-toolbox site examples. 
1.I installed react-toolbox
2.I made a change to the webpack config to say:
      {test: /(\.css|\.scss)$/, loaders: ['style', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]', 'sass?sourceMap']},

3.I installed toolbox-loader (not sure if it is needed)
4.In the HomePage component I added:
import {IconButton} from 'react-toolbox/lib/button';
and then:
<IconButton icon="favorite" accent />

This is what displays for the button:
![image](https://cloud.githubusercontent.com/assets/12962858/21233876/7768a1e0-c2b6-11e6-83d7-29f113842758.png)

I just see the word FAVORITE instead of the icon. What am I doing wrong? Let me know if I need to provide more info. But basically I did not make any other changes. Thanks.

**Comment by lucasljj** [comment]
You need the material icons font, see the docs: http://react-toolbox.com/#/components/font_icon

**Comment by javivelasco** [comment]
+1 @lucasljj

**Comment by ankurarora** [comment]
I am facing the same problem, couldn't find any example to explain how to correctly import build.

**Comment by ionelaluncanu** [comment]
http://google.github.io/material-design-icons/#getting-icons

**Comment by mgutz** [comment]
Why aren't there simple steps for this kind of stuff?

```sh
yarn add material-design-icons
```

Add this to `.js` file which imports your css

```js
import 'material-design-icons/iconfont/material-icons.css'
```

**Comment by ankurarora** [comment]
Thanks, but I am not using create-react-app and that didn't work with my custom setup.

**Comment by charleslaw** [comment]
I am using a custom setup and added the following to my index.html:

     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
