### ISSUE TITLE
Add readme how to start docs site locally

### ISSUE THREAD

**Issue by liesislukas** [react-toolbox/react-toolbox#106]
Hi, i get this view after clone, npm install, npm start: 

Some basic documentation how to start locally would help. How do you develop docs site?

![1](https://cloud.githubusercontent.com/assets/2733862/11168545/82a64f38-8b9b-11e5-9fa1-6bdb98eb0aca.png)

**Comment by javivelasco** [comment]
To lift the docs site you have to go to `docs` folder and then `npm install && npm start`.
We are going to add the explanation in the contribution section of the README, keeping this open meanwhile.

Thanks! :)

**Comment by liesislukas** [comment]
i've done your steps: npm install && npm start, but i got that view from screenshot, looking for same like  http://react-toolbox.com/#/components

**Comment by javivelasco** [comment]
If you do it from `docs` folder it should start the webpack config in this same folder. The server should be listening on `localhost:8081`.
