### ISSUE TITLE
[2.0.0-beta.2] Server side rendering of Layout component leads to "ReferenceError: window is not defined" error

### ISSUE THREAD

**Issue by romppra** [react-toolbox/react-toolbox#1061]
There seems to be an issue with Layout component which will prevent its rendering at server side. The root cause of the problem seems to be in how initial state is handled in combination of utils.getViewPort function. This leads to an situation where window-object is called at server side (where it is not available), causing "ReferenceError: window is not defined" error.

I made a "quick and dirty" test bench for SSR case where you can, if you wish, to test this: https://github.com/romppra/react-toolbox-ssr-testbench

It's basically the spec section of toolbox-project wrapped in webpack driven SSR configuration. Swapping the Layout-component to eg. simple div in Root-component should make the application, and rest of the components, render.

**Comment by carlitux** [comment]
@javivelasco I installed the beta.4 and there is not this fix on it, could you release another beta with this?

**Comment by javivelasco** [comment]
Of course!

**Comment by daviscabral** [comment]
I am having this same error with `2.0.0-beta.12`. 

@carlitux what have you done to fix it?

**Comment by daviscabral** [comment]
@javivelasco do you know anything about it that might help me? I am still trying to make it work.
