### ISSUE TITLE
webpack 2 example

### ISSUE THREAD

**Issue by acambas** [react-toolbox/react-toolbox#1063]
Could you please provide an example with webpack 2 in a different repo so that it pick up the package from npm. 
I've managed to load the component and styling but i have an issue with styles not being properly scoped( for example: icon styles are shared so i have weird margins with icons in buttons).
 
here is the image of the issue
<img width="1374" alt="screen shot 2016-12-17 at 15 33 43" src="https://cloud.githubusercontent.com/assets/5221188/21287946/8e731424-c46e-11e6-87fe-3d401876850c.png">

As you can see the icons in the buttons have a margin which is picked up from the icon class

**Comment by sai-prasanna** [comment]
@acambas  please share your webpack 2 conf, for me css loader doesn't load styles in css modules

**Comment by javivelasco** [comment]
Webpack 2 is configured more or less the same. Nonetheless, I'll add an example with the new version example repository.
