### ISSUE TITLE
Incorrect value of --tab-text-inactive-color in css-next branch

### ISSUE THREAD

**Issue by dhaundy** [react-toolbox/react-toolbox#1064]
In file https://github.com/react-toolbox/react-toolbox/blob/css-next/components/tabs/config.css from branch css-next, there should be no comma after var(--tab-text)

  --tab-text-inactive-color: color(var(--tab-text), a(70%));
should be
  --tab-text-inactive-color: color(var(--tab-text) a(70%));

To reproduce, use postcss-custom-properties & postcss-color-function in webpack config.

**Comment by javivelasco** [comment]
Thanks!
