### ISSUE TITLE
Feature Request: Form component

### ISSUE THREAD

**Issue by chiester** [react-toolbox/react-toolbox#1068]
I would love to see a <Form /> component that could be rendered from a json schema, such as https://github.com/mozilla-services/react-jsonschema-form or https://github.com/networknt/react-schema-form

I tried to use the latter with react-toolbox, but I've had a lot of issues with MUI.

**Comment by javivelasco** [comment]
There was a try to make a `Form` component but I honestly think it's out of the scope of the library. We are suppose to provide visual components while this can be generated using another module. Also, it's not exactly easy to manage this kind of component and there are other helpful libraries like redux-form that can be easily used with react-toolbox. I'm pointing to #626 anyway!

**Comment by drager** [comment]
@chiester: We have built our own [react-form-helper](https://github.com/beanloop/react-form-helper) to handle forms in react with toolbox (works not only for toolbox though). So if you are open to something other than JSON schemas you could check it out.

**Comment by javivelasco** [comment]
I will! Thanks @drager

**Comment by chiester** [comment]
Thanks @drager and @javivelasco
