### ISSUE TITLE
Discord invitation link is broken ?

### ISSUE THREAD

**Issue by shidhincr** [react-toolbox/react-toolbox#107]
I tried to join the discord group and got the error message that "the invitation code is invalid"

**Comment by javivelasco** [comment]
Sorry, we forgot to make the invitation permanent, now it's fixed.
Thanks for reporting! :)

**Comment by shidhincr** [comment]
@javivelasco Thanks

**Comment by hawkins** [comment]
Looks like this channel was either deleted or merged according to reactiflux moderators, since the `react-toolbox` channel no longer exists.

Should the discord link be removed or is there a new home for non-issue discussion?
