### ISSUE TITLE
Date with time picker

### ISSUE THREAD

**Issue by alkhoo** [react-toolbox/react-toolbox#1073]
Feature request: (ie: not an Issue)

Any thoughts of merging Date and Time picker line, similar to: http://jquense.github.io/react-widgets/docs/#/datetime-picker

Currently, it requires math to merge both input fields to produce a single timestamp.

**Comment by kuka-radovan** [comment]
I am missing this component too...

**Comment by Pajn** [comment]
Maybe not exactly what you seek, but we have a datetime picker that is based on the date and time picker in toolbox
https://github.com/beanloop/react-toolbox-components/blob/master/docs/datetime-picker.md
https://github.com/beanloop/react-toolbox-components/blob/master/src/datetime-picker.tsx

Hopefully it's helpfull

**Comment by javivelasco** [comment]
I think this is [out of the spec](https://material.io/guidelines/components/pickers.html#). Note that the implementation is flexible and it's done in multiple separated files. You can create your own by importing small components from react-toolbox :)
