### ISSUE TITLE
Warn: "ThemedLayout should have a Panel for a child, optionally preceded by a NavDrawer and/or followed by a Sidebar."

### ISSUE THREAD

**Issue by alexandru-tomescu** [react-toolbox/react-toolbox#1075]
Hi @javivelasco !
You should modify components/layout/Layout.js:41 from
` if (!(~ALLOWED_THEMED.indexOf(names))) { `
to
` if (!(ALLOWED_THEMED.indexOf(names))) { ` 

I had the right children, but i was warned.

Thank you !

**Comment by javivelasco** [comment]
I think the warning is already removed for recent versions! Thanks :)
