### ISSUE TITLE
Warning: Unknown props `model`, `source` on <table> tag.

### ISSUE THREAD

**Issue by heymartinadams** [react-toolbox/react-toolbox#1079]
Using `@2.0.0.beta-4`, receiving the following error:

`Warning: Unknown props model, source on <table> tag.`

When using the table according to [these instructions](http://react-toolbox.com/#/components/table).
`<Table
				model={UserModel}
				onChange={this.handleChange}
				onSelect={this.handleSelect}
				selectable
				multiSelectable
				selected={this.state.selected}
				source={this.state.source}
			/>`

**Comment by sea129** [comment]
those instructions are for version 1.3.x.

**Comment by heymartinadams** [comment]
Any chance you might have instructions for version 2.0.0? Was unable to use < 2.0.0 due to SASS configuration errors that were driving me insane (I use Browserify, not Webpack, and couldn’t find sufficient documentation).

**Comment by sea129** [comment]
#666 this is a good reference if you want to use version 2. and checkout the branch [V2 branch](https://github.com/react-toolbox/react-toolbox/tree/2.0.0-beta.4). The doc folder is an example, but using webpack

**Comment by heymartinadams** [comment]
Thanks, @sea129!
