### ISSUE TITLE
Button onClick

### ISSUE THREAD

**Issue by retorquere** [react-toolbox/react-toolbox#1083]
How do I implement a botton onClick handler? When I do this

```
<Button {...props} theme={theme} onClick={alert('success')}/>
```

in [react-toolbox-example](https://github.com/react-toolbox/react-toolbox-example) I get the alert when I refresh the page but not when I click the button.

**Comment by javivelasco** [comment]
You're assigning the vale returned by alert call to onClick. Instead you have to provide a function like () => alert("foo").

But this is not even react toolbox stuff, it's basic react!

**Comment by retorquere** [comment]
My apologies... I thought I did try that, this was just my latest experiment, but you're right.
