### ISSUE TITLE
Non-unique Tab element ids

### ISSUE THREAD

**Issue by colin-umn** [react-toolbox/react-toolbox#1085]
From what I can tell, Tab label elements have id values of "0", "1", "2" and so on for each set of Tabs, which means that the HTML element ids are not unique on the page if there are multiple sets of tabs or if any other elements use the small integers as ids.  I have been in web development for a long time and maybe I missed something, but isn't this an obvious violation of the HTML specification and accepted practice?

**Comment by javivelasco** [comment]
That was so true! Thank you!
