### ISSUE TITLE
Support for clipped and floating permanent navigation drawers

### ISSUE THREAD

**Issue by mpiroc** [react-toolbox/react-toolbox#1093]
The [material guidelines](https://material.io/guidelines/patterns/navigation-drawer.html#navigation-drawer-behavior) describe three types on permanent navigation drawers (scroll down to 'Types of permanent navigation drawers'):

> * Full-height navigation drawer: Apps focused on information consumption that use a left-to-right hierarchy
> * Navigation drawer clipped under the app bar: Apps focused on productivity that require balance across the screen
> * Floating navigation drawer: Apps that require less hierarchy

I can implement the first type by using the `pinned` property on `NavDrawer` or `Drawer`. But I would like to use the second type (clipped under app bar), and I don't see an obvious way to do that using `react-toolbox`.

**Comment by javivelasco** [comment]
It is possible indeed but you need to use the new implementation under 2.0 beta. Here is how it would look:

<img width="1440" alt="screenshot 2017-01-16 10 26 57" src="https://cloud.githubusercontent.com/assets/1634922/21977415/5b88d902-dbd6-11e6-9260-6c1ab5a028ad.png">

And the code could like like:

```jsx
import React from 'react';
import AppBar from '../components/app_bar';
import { Layout, Panel, NavDrawer } from '../components/layout';

const Root = () => (
  <Layout>
    <AppBar title="React Toolbox" fixed flat />

    <NavDrawer active pinned clipped>
      This is the content for the drawer
    </NavDrawer>

    <Panel>
      This is the content for panel
    </Panel>
  </Layout>
);

export default Root;
```

**Comment by mpiroc** [comment]
I was able to work around this in 1.x by using a nested layout:

```
<Layout>
  <Panel>
    <MyAppBarComponent />
    <Layout>
      <NavDrawer pinned={true}>
        {'Nav content'}
      </NavDrawer>
      <Panel>
        {'Main content'}
      </Panel>
    </Layout>
  </Panel>
</Layout>
```

**Comment by logicalor** [comment]
I am trying to get a fixed navbar layout using the technique described in [#2](#issuecomment-272811567).

I have built the project using create-react-app.

- react@15.4.2
- react-toolbox@2.0.0-beta.6

I'm also using [react-toolbox-themr@1.0.2](https://github.com/react-toolbox/react-toolbox-themr) to integrate the react-toolbox modules into my project without needing to eject from create-react-app.

It mosly works, but the Panel containing my content doesn't seem to be aware of the fixed AppBar and NavDrawer, so they both overlay the Panel.

![screenshot-bbw local 3000-2017-02-17-09-22-53](https://cloud.githubusercontent.com/assets/5744173/23046000/e9eb2378-f4f2-11e6-9dfc-7ff3d181b659.png)

Is this normal behaviour, or could it be a side effect of my project implementation (eg. react-toolbox-themr not porting over correct behaviour for the panel)?  If it's normal, then I guess I can shoehorn some behaviour when the component app loads or screen dimensions change, to nudge the margins of the Panel accordingly.

Here are my components:

```
export default class App extends Component {
	
  ...

  render() {

    const { children } = this.props;
    const { loggedIn, user, app, drawerActive, drawerPinned, 
      drawerClipped, appBarIconVisible, permanentAt } = this.state;

    return (
      <ThemeProvider theme={theme}>
        <Layout>
          <TopNav 
            loggedIn={ loggedIn } 
            user={ user } 
            title={app.title}
            drawerClick={this.toggleDrawerActive}
            appBarIconVisible={appBarIconVisible}
          />
          <SideNav 
            active={ drawerActive} 
            pinned={ drawerPinned } 
            clipped={ drawerClipped }
            loggedIn={ loggedIn } 
            user={ user } 
            title={app.title}
            onOverlayClick={this.toggleDrawerActive}
            permanentAt={permanentAt}
          />
          <Panel>
            {children}
          </Panel>
          <NotificationSystem ref="notificationSystem" />
        </Layout>
      </ThemeProvider>
    )
  }
}

export default class TopNav extends Component {

  ...

  render() {
    
    const { loggedIn, title, drawerClick, appBarIconVisible } = this.props;

    if (loggedIn) {
      return (
        <AppBar 
          className="AppBar" 
          title={title} 
          leftIcon={appBarIconVisible ? 'menu' : null} 
          onLeftIconClick={drawerClick} 
          fixed 
          flat
        >
          <Navigation type='horizontal'>
            <Link href='#/account/dashboard' label="Dashboard" />
            <Link href='#/account/profile' label="Profile" />
            <Link href='#/account/settings' label="Settings" />
            <Link href='#/logout' label="Sign Out" />
          </Navigation>
        </AppBar>
      )
    }
    
    else {
      return (
        <AppBar 
          className="AppBar" 
          title={title} 
          leftIcon={appBarIconVisible ? 'menu' : null} 
          onLeftIconClick={drawerClick} 
          fixed 
          flat
        >
          <Navigation type='horizontal'>
            <Link href='#/login' label="Sign In" />
            <Link href='#/register' label="Register" />
          </Navigation>
        </AppBar>
      )
    }
  }
}

export default class SideNav extends Component {

  render() {
    
    const { active, pinned, clipped, onOverlayClick, permanentAt } = this.props;

    return (
      <NavDrawer active={active}
        pinned={pinned} 
        permanentAt={permanentAt}
        clipped={clipped}
        onOverlayClick={ onOverlayClick }
      >
        <p>
           Test Content
        </p>
      </NavDrawer>
    )
  }
}
```
