### ISSUE TITLE
make overlay width and height 100%

### ISSUE THREAD

**Issue by patilparesh** [react-toolbox/react-toolbox#1104]
i want to make `class="theme__overlay___xxx theme__active___xxx"` width and height 100%...i didnt want `width: 100vw; height: 100vh;` this.
i am added external sass in page and in dialog tag i added `theme={MyTheme} className={MyTheme.overlay}` but this class not work on overlay div.. how to change width and height overlay div

**Comment by javivelasco** [comment]
This is fixed right [here](https://github.com/react-toolbox/react-toolbox/issues/1055). Previously we had no way of specifying a className for the `Overlay` rendered in the `Dialog`. From that commit it is possible!
