### ISSUE TITLE
Ripple doesn't center on mouse cursor if window is scrolled

### ISSUE THREAD

**Issue by alltom** [react-toolbox/react-toolbox#111]
Unless scrollTop is 0, Ripples don't appear in the right place. If you scroll the page, the Ripple is centered on where your cursor would have been if you hadn't scrolled. So if you've scrolled enough, you don't see the Ripple at all. :(

I guess the cursor's position is relative to the viewport, but used as if it's relative to the document?

**Comment by javivelasco** [comment]
Can you give me specific steps to reproduce it on local and try to figure out what's going on??

**Comment by javivelasco** [comment]
Oh! I see, are you wrapping your app with the `App` component?

**Comment by alltom** [comment]
Thanks!
