### ISSUE TITLE
Minimal example fails

### ISSUE THREAD

**Issue by stripTM** [react-toolbox/react-toolbox#1111]
Trying to test react-toolbox "version": "1.3.3" I started with the basic example, but I do not run, this is the code and the error.

```
import React from 'react';
import ReactDOM from 'react-dom';
import { Button } from 'react-toolbox/lib/button';
```

> Failed to compile.
> 
> Error in ./~/react-toolbox/lib/ripple/Ripple.js
> Module not found: 'immutability-helper' in /media/creaciones/www/react-form-components/node_modules/react-toolbox/lib/ripple
> 
>  @ ./~/react-toolbox/lib/ripple/Ripple.js 23:26-56

**Comment by oxyno-zeta** [comment]
Hello,

You need to install 'immutability-helper' : `npm install --save immutability-helper`.
This dependency is in 'peerDependencies', so it is not installed when you run the `npm install` command. You need to install all 'peerDependencies' by yourself.

You can see here : #695 

Oxyno-zeta

**Comment by stripTM** [comment]
Thanks, 

This is already fixed, but now I have another problem related to the Prerequisites -> http://react-toolbox.com/#/install
I am new using webpack, npm, etc and I do not understand how to install it

> module.js:472
>     throw err;
>     ^
> 
> Error: Cannot find module 'autoprefixer'
>     at Function.Module._resolveFilename (module.js:470:15)
>     at Function.Module._load (module.js:418:25)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/media/creaciones/www/react-form-components_2/webpack.config.js:5:22)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>

**Comment by oxyno-zeta** [comment]
Same thing : `npm install --save-dev autoprefixer`

**Comment by stripTM** [comment]
Hello,

I now understand how it works, thanks :)
Iit would be nice if these dependencies were already included in the package, if it was possible.

Now the following error I think is due to my webpack.config.js configuration, I do not know what I have to add for it to process theme.scss

> ERROR in ./~/react-toolbox/lib/button/theme.scss
> Module parse failed: /media/creaciones/www/react-form-components_2/node_modules/react-toolbox/lib/button/theme.scss Unexpected character '@' (1:0)
> You may need an appropriate loader to handle this file type.
> SyntaxError: Unexpected character '@' (1:0)
>     at Parser.pp$4.raise (/media/creaciones/www/react-form-components_2/node_modules/acorn/dist/acorn.js:2221:15)
>     at Parser.pp$7.getTokenFromCode (/media/creaciones/www/react-form-components_2/node_modules/acorn/dist/acorn.js:2756:10)
>     at Parser.pp$7.readToken (/media/creaciones/www/react-form-components_2/node_modules/acorn/dist/acorn.js:2477:17)
>     at Parser.pp$7.nextToken (/media/creaciones/www/react-form-components_2/node_modules/acorn/dist/acorn.js:2468:15)
>     at Parser.parse (/media/creaciones/www/react-form-components_2/node_modules/acorn/dist/acorn.js:515:10)
>     at Object.parse (/media/creaciones/www/react-form-components_2/node_modules/acorn/dist/acorn.js:3098:39)
>     at Parser.parse (/media/creaciones/www/react-form-components_2/node_modules/webpack/lib/Parser.js:902:15)
>     at NormalModule.<anonymous> (/media/creaciones/www/react-form-components_2/node_modules/webpack/lib/NormalModule.js:104:16)
>     at NormalModule.onModuleBuild (/media/creaciones/www/react-form-components_2/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
>     at nextLoader (/media/creaciones/www/react-form-components_2/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
>  @ ./~/react-toolbox/lib/button/index.js 26:13-36
>

**Comment by oxyno-zeta** [comment]
That's because you doesn't support 'scss' files in your webpack configuration.

That's my webpack configuration for loaders : 
```
loaders: [
            {
                test: /\.js(x|)?/,
                exclude: /node_modules/,
                loader: 'babel',
            },
            {
                test: /\.html$/,
                loader: 'html',
                exclude: /node_modules/,
            },
            {
                test: /\.css$/,
                loader: webpackCombineLoaders([
                    {
                        loader: 'css',
                        query: {
                            modules: true,
                            camelCase: true,
                            localIdentName: '[path][name]---[local]---[hash:base64:5]',
                        },
                    },
                    {
                        loader: 'postcss',
                    },
                ]),
            },
            {
                test: /\.s[ac]ss$/,
                loader: webpackCombineLoaders([
                    {
                        loader: 'style',
                    },
                    {
                        loader: 'css',
                        query: {
                            modules: true,
                            camelCase: true,
                            localIdentName: '[local]',
                        },
                    },
                    {
                        loader: 'postcss',
                    },
                    {
                        loader: 'sass',
                        query: {
                            sourceMaps: 'true',
                        },
                    },
                ]),
            },
            {
                test: /\.(png|jpe?g|gif|svg|woff2?|eot|ttf|otf|wav)(\?.*)?$/,
                exclude: /node_modules/,
                loader: 'url',
                query: {
                    limit: 10,
                    name: '[name].[hash:7].[ext]',
                },
            },
        ],
```

My dependencies : 
```
const webpackCombineLoaders = require('webpack-combine-loaders');
```
And also : 
```
css-loader
autoprefixer
file-loader
html-loader
node-sass
postcss-loader
sass-loader
style-loader
url-loader
```

**Comment by stripTM** [comment]
After adding and 

> npm install --save-dev webpack-combine-loaders extract-text-webpack-plugin
> npm install --save [your modules...]

compiling, yeah!

I still do not have the part to generate the bundle.css, but I'm going to rely on https://github.com/react-toolbox/react-toolbox-example , which I'm seeing are many things that I do not know.

**Comment by sotream** [comment]
@oxyno-zeta Can you share your postcss config, please. I have an error while I try to add NavDrawer to my project. 
I'm using: `"react-toolbox": "^2.0.0-beta.4"`

[Screenshot](http://prntscr.com/dtoz8b)

**Comment by javivelasco** [comment]
@stripTM Actually this is fixed in the latest version! I'm closing
