### ISSUE TITLE
Tooltip is not visible in Dialog

### ISSUE THREAD

**Issue by alwinn1977** [react-toolbox/react-toolbox#1116]
```
import { Button, IconButton } from 'react-toolbox/lib/button';
import Dialog from 'react-toolbox/lib/dialog';
import Tooltip from 'react-toolbox/lib/tooltip';

const TooltipIconButton = Tooltip(IconButton);
....
<Dialog>
...
<TooltipIconButton
          tooltip="Merge"
          icon="merge_type"
          onClick={() => this.handleCodeVersionDialog()}
        />
</Dialog>

```

Tooltip does not appear inside dialog at all. Rather, it appears behind the dialog and not visible. Why? What can I do to fix it?

**Comment by rubenmoya** [comment]
Which version are you using?

This is a picture from the `/spec` using the `2.0.0-beta.4`:

![screen shot 2017-01-15 at 19 17 37](https://cloud.githubusercontent.com/assets/905225/21965019/65c2635e-db57-11e6-8f09-a2af24052f05.png)

**Comment by alwinn1977** [comment]
Now I'm using react-toolbox 1.3.3. I tried using version 2.0.0-beta but got problems with webpack.

**Comment by javivelasco** [comment]
In case it's fixed in the new version we rather close this. I encourage you @alwinn1977 to move to the latest version. You don't need to use webpack, [react-toolbox-themr](github.com/react-toolbox/react-toolbox-themr) can help you

**Comment by lucaas** [comment]
I also encountered this issue. Since I don't have want to move to a prerelease version (or have the time to move dependent styling over from sass), I solved it in my application by adding a theme to the tooltip'ed component, forcing it's z-index higher.

theme.scss
```
.tooltip {
    z-index: 300;
}
```

component.js
```
import theme from './theme.scss';
...
<TooltipFontIcon theme={theme} ... />
```
