### ISSUE TITLE
Redux theme switcher

### ISSUE THREAD

**Issue by alexandru-tomescu** [react-toolbox/react-toolbox#1117]
I have written ConnectedThemeProvider:

`class ConnectedThemeProvider extends Component {
	render() {
		return (
			<ThemeProvider 
				theme={ themes[this.props.theme] } 
				children={ this.props.children}  /> )
	}
}`

and it's all good.

I have 3 themes:
`
import theme1 from './theme1';
import theme2 from './theme2';
import theme3 from './theme3';

export const themes = {
	theme1,
	theme2,
	theme3
}; 

export const availableThemes = Object.keys(themes);
`

And it's all good

Every theme has only a key for the AppBar (RTAppBar) and a style for the background color like this:
`.appBar {
  background-color: yellow !important;
}`
(!important because the AppBar loads his main color, but this is not a big problem)

**My problem is: The theme for ThemeProvider switches correctly (through redux store), but the style for appbar doesn't change, remains always the same. all the styles appears correctly in bundle.css**

this is my index:
`<Provider store={store}>
		<ConnectedThemeProvider>
			<ConnectedIntlProvider>
	  		<Router 
	  			history={history} 
	  			routes={getRoutes(store)} />
    	</ConnectedIntlProvider>
		</ConnectedThemeProvider>
  </Provider>,`

and getRoutes contains the App: 
`export default function getRoutes() {
  return (
    	<App>
            (Routes with their components)
    	</App>
  );
}`

Could you help me please ?
Thank you !

**Comment by javivelasco** [comment]
I think this is not an issue of react-toolbox but more related to [react-css-themr](https://github.com/javivelasco/react-css-themr/issues/34). Anyway, re-rendering on context change it's a recurrent issue, you may need to re-render manually.

**Comment by alexandru-tomescu** [comment]
Thank you @javivelasco ! I solved by inserting in runtime custom css with selectors data-react-toolbox :)

**Comment by javivelasco** [comment]
Amazing!
