### ISSUE TITLE
Create a test / spec for typescript definition

### ISSUE THREAD

**Issue by panjiesw** [react-toolbox/react-toolbox#1118]
As the lib is not originally authored in typescript, the definition is written manually by hand, thus may introduce an incomplete definition, or typo, error, etc for the ts users.

Should we make some kind of type checking for the definition into the build/test step? We can do it like the type registration in [DefinetlyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), where there is a spec only typescript file importing all the components, which purpose is only for type checking. 

For example we can define the `spec` directory as a typescript project (put a `tsconfig.json` into this), then we write a ts file importing all the component, then run the `tsc` compiler against it. This way any contribution to typescript definition of `react-toolbox` will be either type checked by IDE/editor or the `tsc` compiler.

**Comment by javivelasco** [comment]
This would be perfect. Would you create a PR for this? It would be very helpful specially for me since I bever used Typescript

**Comment by panjiesw** [comment]
Sure, I'll get into this soon. Should I include this in #1114 ?

**Comment by javivelasco** [comment]
I'd make itnin a separate PR, I'm merging that one now
