### ISSUE TITLE
Disable warnings on labels

### ISSUE THREAD

**Issue by maxmantz** [react-toolbox/react-toolbox#1123]
Hi,

I'm using react-intl's `<FormattedMessage />` to display labels in menus and buttons. When I'm using this, react gives me a warning like this: 

``` 
warning.js:36 Warning: Failed prop type: Invalid prop `caption` of type `object` supplied to `MenuItem`, expected `string`.
```

Since `<FormattedMessage />` displays a string everything works fine. Would it be OK to extend the prop types on these items (Dropdown, MenuItem, Button etc...) to allow for React elements to be passed in?

**Comment by MorrisGallego** [comment]
Hi, 

If it's possible, you can use the imperative API from react-intl. That way you avoid the warning and everything works perfectly (at least in my case).

**Comment by maxmantz** [comment]
I tried that and the warning disappeared. Thank you!
