### ISSUE TITLE
Fix for input padding

### ISSUE THREAD

**Issue by waldnercharles** [react-toolbox/react-toolbox#1124]
I'm a little new to scss, so I'm not actually sure how to contribute to the scss bundled with this, but I found a slight bug with `input-padding`.

When changing `input-padding`, it adversely effects the `input-icon-offset`. It can be fixed by doing `$input-icon-offset: $input-padding - ($input-field-padding * 0.5);`

Again, I'm fairly new to scss so am still unfamiliar with how to contribute when I don't see any scss files.

Hope this helps someone.

**Comment by javivelasco** [comment]
Thanks for reporting, I think this may be useful for people that want to change the value as you did. Truth is I don't consider this a bug mostly because if you change some configuration variables for spacing it may break some other styles and you should adjust manually to get the expected results.

**Comment by waldnercharles** [comment]
Great point. Thanks for the explanation!
