### ISSUE TITLE
Wrong typescript definition for Ripple

### ISSUE THREAD

**Issue by stefanhong** [react-toolbox/react-toolbox#1125]
TypeScript definition file `react-toolbox/lib/ripple/index.d.ts` exports `rippleFactory`, but it should be named `Ripple` to match that in the `react-toolbox/index.d.ts` file.  I have no idea how the ripple definition file is generated because I can't find it in this repo but it is in the installed package.  Right now TypeScript compiler throws out this error message when importing any component from the toolbox:

`error TS2305: Module '...../node_modules/react-toolbox/lib/ripple/index"' has no exported member 'Ripple'.`

**Comment by DmitryDorofeev** [comment]
I have to use v1.3.3 to avoid this problem.

**Comment by panjiesw** [comment]
It's covered in #1114 along with other type restructure.
