### ISSUE TITLE
Missing -webkit-tap-highlight-color after PostCSS refactor

### ISSUE THREAD

**Issue by sciyoshi** [react-toolbox/react-toolbox#1128]
With the removal of `commons.css` the tap highlights are now showing on mobile devices. `-webkit-touch-callout` should also be added back.

https://github.com/react-toolbox/react-toolbox/commit/81acda716228c3b5110730b145226222eac6ef12#diff-dac3b2697166accce529dceebadc024aL18

@javivelasco

**Comment by javivelasco** [comment]
I've just added it to the reset and it's used in most components. Please if you find it missing in any place you can add it a send a PR or open an issue with the specific component to fix it.
