### ISSUE TITLE
Uncaught Error: Cannot find module './style'

### ISSUE THREAD

**Issue by varghesethomase** [react-toolbox/react-toolbox#113]
Uncaught Error: Cannot find module './style'
=================================
I get this error when including react-toolbox  component via npm to my project. 
`import DatePicker from 'react-toolbox';`
this is how i imported. but i found ./style.scss is not getting loaded.
I also figured out that its because i'm not using     "toolbox-loader": "0.0.3" plugin properly. 

Can you help out how i can configure this? 
I also read about including a theme.scss file and has it in the root of project. 
so i need help with configuring the plugin so that i can get it working. 

Attaching my webpack config file
[make-webpack-config.txt](https://github.com/react-toolbox/react-toolbox/files/35165/make-webpack-config.txt)

**Comment by javivelasco** [comment]
Hi @varghesethomase!

The import should be done from the proper lib directory if you want to import just what you need. For the `DatePicker` it's `import DatePicker from 'react-toolbox/lib/date_picker'`. Another option is to use destructuring to import from the main package entry like `import {DatePicker} from 'react-toolbox'` but in that case you are requiring the whole library.

If it's still not working reopen the issue.
Thanks!

**Comment by varghesethomase** [comment]
Hi @javivelasco, 
sorry to say but still the issue persists. And its the same old error that comes up. I guess there has to be a bit of configuring to be done int he webpack. I havent used the toolbox-loader properly if i'm right. So can you please check my webpack config file attached with the previous message so that i can fix it asap? TIA

**Comment by javivelasco** [comment]
I'm finding difficult to find out what's the error in your config. Can you try to compare it with the [example setup](https://github.com/react-toolbox/react-toolbox-example)? Both the configuration and imports so we can make sure that's about the config and not a package issue?

**Comment by nathanmarks** [comment]
@varghesethomase If you setup a demo repo I will try to fix it for you

**Comment by brandonhamilton** [comment]
@varghesethomase , it looks like you need to add '.scss' to the webpack resolve config by adding it to your extensions array in your web pack config file, e.g:
```javascript
var extensions = [ '', '.js', '.jsx', '.scss', '.json', '.node' ]
```

**Comment by malte-wessel** [comment]
@brandonhamilton thx, worked for me!

**Comment by keiranvv** [comment]
Hey, I'm having the same issue but I'm not using webpack. I'm using browserify from the command line. Is there any way I can somehow include the scss extension? It seems that no matter what I try I get this exception.

This is the command I'm using:
`browserify -t [ babelify --presets [ react ] ] app.jsx -o bundle.js`

**Comment by milesburton** [comment]
@keiranvv You've got a couple of options with browserify. You can install one of the sass plugins which will interpret the import in react-toolbox and produce the styles as needed. Alternatively you can configure browserify to physically ignore the import, and manage styles manually, for example using your existing sass build pipeline.

Neither approaches are ideal. 1# most/all the browserify plugins are outdated 2# Hacky/error prone.

It would be useful to have a precompiled version of react-toolbox, should resolve the differences in build pipelines

**Comment by wtgtybhertgeghgtwtg** [comment]
@milesburton I agree.  Especially when you don't use SASS anywhere else in your project, it's a little odd setting it up for a package.
