### ISSUE TITLE
2.0.0-beta.4 menu theme.css syntax error.

### ISSUE THREAD

**Issue by sotream** [react-toolbox/react-toolbox#1130]
Hi, 
i found an error in menu/theme.css line 374:
in file:
`--menu-divider-height: calc((4.8 / 4) * var(--unit)));`
should be:
`--menu-divider-height: calc((4.8 / 4) * var(--unit));`

**Comment by mike-midnight** [comment]
Hello!

It happened for me as well! 
+1 on this
