### ISSUE TITLE
Enable import { AppBar, Button } from 'react-toolbox'

### ISSUE THREAD

**Issue by davidfloegel** [react-toolbox/react-toolbox#1132]
Great library!!

It would be amazing if I could just import components like this though:
`import { AppBar, Button } from 'react-toolbox'`

Would save a lot of lines of code :)

**Comment by thesbros** [comment]
You should be able to; unless they've changed something recently. I do it like that in my code.

**Comment by thj-dk** [comment]
> import { AppBar, Button } from 'react-toolbox'

The downside to that approach is that the whole library is bundled by webpack.

**Comment by Pajn** [comment]
The extend on what @thj-dk said. If you import from the sub-modules your bundle will only include components that you actually use, where as importing form 'react-toolbox' will include all components. That will increase bundle size and parse time unnecessarily.

**Comment by UchihaVeha** [comment]
> The downside to that approach is that the whole library is bundled by webpack.

Webpack 2 with Tree-shaking can resolve this problem

**Comment by thj-dk** [comment]
@UchihaVeha Did you get it working? I haven't been able to with the latest version.

**Comment by javivelasco** [comment]
Actually this is possible :/ But I don't recommend it at all
