### ISSUE TITLE
Slider should accept style prop

### ISSUE THREAD

**Issue by Coderah** [react-toolbox/react-toolbox#1133]
Either type definition files (for TypeScript) are incorrect or Slider should be using a style prop (like most other components), I would expect this style to be put on the highest level component (container) rather than having to use the theme prop anytime you want to adjust styles for a Slider.

**Comment by panjiesw** [comment]
from what I see [here](https://github.com/react-toolbox/react-toolbox/blob/dev/components/slider/Slider.js#L268) (both master & dev branch), it doesn't pass `style` prop down the top `div` component nor its children. So it shouldn't be in the type definition file of `Slider`

But as the definition files are written by hand, it's a bit difficult to change it, with how the way it's currently written. You can participate in #1114 as I'm attempting to restructure the type definitions.
