### ISSUE TITLE
How to override variables in custom theme?

### ISSUE THREAD

**Issue by thj-dk** [react-toolbox/react-toolbox#1138]
I can't figure out how to override variables in my custom theme. Could you provide me with an example or guide me in the right direction, please?

I want to change the width of the NavDrawer and from my understanding of `components/layout/theme.css`, the NavDrawer gets its width from `--drawer-desktop-width` located in `components/drawer/config.css`.

I tried implementing `RTDrawer` in my theme with the following CSS:

```
:root {
  --drawer-desktop-width: 100px;
  --drawer-mobile-width: 80px;
}
```

But without luck. Whats the correct way of achieving this?

**Comment by thj-dk** [comment]
I think it would be great with some guidance on how this is supposed to work. I'd be happy to write some documentation, when I figure out how?

**Comment by thj-dk** [comment]
Is the only option to provide a JS object to css-next features.customProperties.variables? Can't this be done using CSS?

**Comment by rubenmoya** [comment]
As far as I know, that's the only option

**Comment by javivelasco** [comment]
@thj-dk Overriding variables can be done without preprocessing only if your browser supports it so it's not recommended at all. For this you just have to redefine variables *after* the originals. Of course they shouldn't be processed. To override variables with your customs you need to process with css next and provide your overrides. If you are using react toolbox configured with css modules in webpack it's pretty easy to define a module with all of your overrides and pass it to the customProperties option from css-next. 

If you use react-toolbox-themr you can add your overrides in the package configuration or in a custom file as specified in the README. 

Another option could be to override them as you were doing in your example but in that case you also need to import the original CSS file. Take into account that the variable scope is only applied per file!

At the end you need to either rely on the browser or process with css next. In the later you must use react toolbox themr or css next directly consuming their api to provide overrides. 

@thj-dk Overriding variables can be done without preprocessing only if your browser supports it so it's not recommended at all. For this you just have to redefine variables *after* the originals. Of course they shouldn't be processed. To override variables with your customs you need to process with css next and provide your overrides. If you are using react toolbox configured with css modules in webpack it's pretty easy to define a module with all of your overrides and pass it to the customProperties option from css-next. 

If you use react-toolbox-themr you can add your overrides in the package configuration or in a custom file as specified in the README. 

Another option could be to override them as you were doing but in that case you also need to import the CSS file

If you have further questions please ask! I'll be happy to help.
