### ISSUE TITLE
Some thoughts about the button component

### ISSUE THREAD

**Issue by nathanmarks** [react-toolbox/react-toolbox#114]
A few thoughts I had while reviewing the `<Button />` component:

##### 1. Why is my text inside an `<abbr>` tag?

This tag is for abbreviations, it is totally out of place here. The `<abbr>` tag is for this:

```html
<abbr title="Hypertext Markup Language">HTML</abbr>
```

##### 2. I'd like to be able to use children for my button content

This feels much more natural to me... hopefully I'm not crazy ;) :

```jsx
<Button>Hello World</Button>

// or perhaps with an icon

<Button>
  <FontIcon ... />
  Hello World
</Button>

// and a ripple!

<Button ripple>
  <FontIcon ... />
  Hello World
</Button>
```

##### 3. Where did you find the loading animation? 

Not sure the ripple is a good loading animation for UX, where have you seen it in google's apps or spec? From my understanding, the ripples are supposed to be an event that is ink spreading outwards from the point of input from your mouse/finger -- not loading animations.

##### 4. Would be useful to be able to use as an anchor link too

This can be done by checking for a `href=.....` prop and using `React.createElement()` to conditionally create an `<a>` tag instead of a `<button>`.

**Comment by soyjavi** [comment]
Hi @nathanmarks 

I will try to answer all your questions ;)

**1. Why is my text inside an <abbr> tag?**
Our wrong is better use `<span>` element

**2. I'd like to be able to use children for my button content**
My question for you is... *why?* now you can use the attribute `icon` for that purpouse. `<button>` its a simple component (not a composition one) we think is better keep simple.

**3. Where did you find the loading animation?**
Totally agree, any porpoise?

**4. Would be useful to be able to use as an anchor link too**
Like `<button>` we have `<link>` (now I think anchor is better name). If we respect the HTML Spec is better separate both, and keep them in separate files.

best,

javi

**Comment by nathanmarks** [comment]
@soyjavi Hey Soyjavi

Thanks for the response!

It is very easy to support `label=` AND `<Button>Label</Button>`. This is still a simple component except it is much closer to how you use the `<button>` HTML element which feels more natural to me.

```
const { label, children } = this.props

render (
  <button>{label ? label : children}</button>
);
```

I will take a look through some google apps and see what they tend to do for loading on buttons.

**Comment by nathanmarks** [comment]
@soyjavi Also, even though the `<a>` tag is called anchor, I think most people just use the term "anchor link" to refer to in-page links -- `<Link>` is just fine :)

However, the problem with the link right now is that it does not let you style `<a href......` as buttons. This is what I was referring to when I mentioned making the button smart enough to allow it to be implemented as either a `<button>` or `<a>` tag.

**Comment by javivelasco** [comment]
I think to resolve the anchor problem, we can provide a `button` boolean property to the `Link` so in case it's true we can apply button styles imported from the `Button` component. That would keep semantics.  About the children I think it's worthy to support both `label` and children. Makes sense in case you want to provide a custom icon, I mean an icon not provided in Material Design icon font. Both are very easy changes that can be done and included in a few minutes!!

**Comment by nathanmarks** [comment]
@javivelasco Great! I think that's an awesome idea.

It would be nice not to have to duplicate any code to use all the same features (accent, ripple, etc etc) that buttons have. How will you achieve that with the link?

**Comment by javivelasco** [comment]
Yes, I've just realized as I was reading :sweat_smile: 
To keep it separated I think we should add those properties to links as well but that's actually meaning a look of duplication because we are not only importing the button style but also the modifiers. Maybe instead of importing just the style, the `Link` can hold a dependency with the `Button` component.

Then, in the button component we can have a static method that gets the properties and returns `className` string which are actually from buttons but are dumped into the anchor. The ripple can work independently I guess. BUT... it would be a lot easier to accept an `href` in the button and make the `Link` just a wrapper.

**Comment by nathanmarks** [comment]
Accepting href in the button and conditionally making it a `<a>` element is much easier.

Also, technically, visually it is still a "button", which is why we're using the `<Button>` components.

Here's a contrived example of how it would work:

```jsx
const { children, className, href, ...otherProps } = this.props;
const element = href ? 'button' : 'a';

return React.createElement(element, {
  className,
  href,
  ...otherProps
}, children);
```

**Comment by javivelasco** [comment]
Yes, I agree with you. It's way easier at implementation level and it makes sense. Let's see @soyjavi opinion!

**Comment by soyjavi** [comment]
@nathanmarks I'm thinking in the perfomance if we create a composite component I think the render gets more time (because each component has a render function). In my opinion I prefer keep simple, I understand perfectly that `card` component needs subcomponents... but `button` why? We need respect the spec of Material Design and button spec is quite simple.

what do you think about perfomance?

best,

**Comment by nathanmarks** [comment]
@soyjavi It doesn't even need to accept subcomponents other than a string if you'd prefer to keep it tightly controlled:

```
static propTypes = {
  children: PropTypes.string
}
```

This is purely so we can use the `<Button>` component like a regular HTML element:
```
<Button>Click Here!</Button>
```

In terms of the `<a>` vs `<button>` issue, the reasoning behind that is because at the moment it is impossible with this library to create a link that is a button visually.

You cannot do `<a href=".......">Action</a>` with a button as `href` is not a valid attribute for `<button>`.

**Comment by nathanmarks** [comment]
@soyjavi just to add RE the performance, I will do some tests later

**Comment by EnzoMartin** [comment]
Regarding the button `icon` property, right now you can't use other Icon Fonts like Font-Awesome, which supports stacked icons, and thus requires additional markup than a single `<i>` tag

**Comment by nathanmarks** [comment]
@soyjavi @javivelasco 

One more thing, about the props... `kind=` seems like a poor english translation.

Even though you hear people say, "Oh, I like this kind of X", in technical documentation `type=` would be a much more appropriate prop name.

To take it another step further -- since things like `accent` and `primary` are props instead of `color=xx`, maybe `raised` should just be a prop for consistency? Also means less writing :)

**Comment by javivelasco** [comment]
Yeah I know. Actually it was the best I've found to replace `type` since it should be used to be transferred to the `button` tag. Do you think we can use a better one? We can change the props definition for buttons if we can find something that makes more sense of course, but always respecting transferring properties to the `button` tag :)

**Comment by nathanmarks** [comment]
@javivelasco I would just do a `raised` boolean prop, and have flat as default. This makes it consistent with the other button options such as color (accent/primary)

**Comment by javivelasco** [comment]
Ok I think it's fine. Tomorrow I'm adding it [here](https://github.com/react-toolbox/react-toolbox/tree/button-enhancements). Gotta go now!
