### ISSUE TITLE
v1 typescript typings bug - index.js export Ripple

### ISSUE THREAD

**Issue by beckend** [react-toolbox/react-toolbox#1140]
Module '"node_modules/react-toolbox/lib/ripple/index"'
 has no exported member 'Ripple'.

And it truth, it does not.
Reading the src this is the only export of [default](https://github.com/react-toolbox/react-toolbox/blob/master/components/ripple/index.js#L4);

**Comment by panjiesw** [comment]
How do you import it?

```javascript
// It's supposed to be used like this
import Ripple from 'react-toolbox/lib/ripple'
// not this one
import {Ripple} from 'react-toolbox/lib/ripple'
```

But yeah, it wouldn't hurt to also provide the named export `Ripple`

**Comment by beckend** [comment]
Related to https://github.com/react-toolbox/react-toolbox/issues/1125 if he meant v1.
