### ISSUE TITLE
Dependency injection doesn't work with React-hot-loader

### ISSUE THREAD

**Issue by valerybugakov** [react-toolbox/react-toolbox#1148]
Hey, first of all thanks for a great library! Love it.
I'm using `2.0.0-beta.4` version and there's a utility function that helps filter out children of certain types:
```js
function isComponentOfType(classType, reactElement) {
  return reactElement && reactElement.type === classType;
}
```
Approach described here https://github.com/react-toolbox/react-toolbox/issues/957 with `CustomRow` injection doesn't work for me in development environment, because all components are proxied by `React-hot-loader` and strict equality check fails. Is there another way to do it or is it possible to expose an API to change the behavior of `isComponentOfType`? `React-hot-loader` is really popular, it would be great to have `react-toolbox` compatible with it.

**Comment by valerybugakov** [comment]
I've hacked it in a forked repo for now:  https://github.com/valerybugakov/react-toolbox/commit/fc7983a619b451a1a4019d3e6fcf93e8382f7292
It solved my problem for now. Is it worth creating a pull request maybe with some fixes?

**Comment by javivelasco** [comment]
Please do! I can review it today and if it has no downsides I will merge it!!

**Comment by valerybugakov** [comment]
@javivelasco done here https://github.com/react-toolbox/react-toolbox/pull/1164
