### ISSUE TITLE
Tabs are not rendered [2.0.0-beta4]

### ISSUE THREAD

**Issue by olegstepura** [react-toolbox/react-toolbox#1155]
Fully copying the full Tabs example component from here: http://react-toolbox.com/#/components/tabs with latest beta release

I see this (no tabs at all):
![tabs](https://cloud.githubusercontent.com/assets/534510/22099644/dd83ff9e-de34-11e6-9b6c-52ad8d8a1b67.png)

Didn't you change the props? Or is it a bug?

**Comment by javivelasco** [comment]
Maybe there is a bug in that specific version. Probably there were missing exports. I've tried the latest released beta and it works for me. Please try it out and reopen if it doesn't work! Thanks for reporting :)

**Comment by olegstepura** [comment]
Hi! It's the same in `react-toolbox@2.0.0-beta.4`. Please reopen.

**Comment by javivelasco** [comment]
Can anybody else confirm this issue? I've tried and it works for me :/

**Comment by olegstepura** [comment]
I'll try to create a test repo

**Comment by javivelasco** [comment]
Ok! Thanks :)

**Comment by olegstepura** [comment]
Here is my test case for Tabs (`tabs-test` branch):
https://github.com/olegstepura/react-toolbox-example/tree/tabs-test

For me the resulting picture is still the same (tested in Firefox and Chrome on Windows)

**Comment by javivelasco** [comment]
That wasn't easy. The issue is that React Hot Loader proxies components so the `type` of the component is no longer recognized. This happens because `Tabs` needs to recognize its children to figure out how should they be rendered. We [added recently](https://github.com/react-toolbox/react-toolbox/pull/1164) the ability to override `isComponentOfType` to keep using Hot Loader with react-toolbox. There are instructions in the same PR. What this fix does is to use `isComponentOfType` implementation to allow overriding it.

**Comment by olegstepura** [comment]
So I just need to wait for #1165, correct?

**Comment by javivelasco** [comment]
I've just released 😵 It's going to work for the `Layout` but not for `Tabs` because the fix is not included in the bundle. It will be for the next release!

**Comment by SleeplessByte** [comment]
@javivelasco please update Tabs.d.ts in `react-toolbox@2.0.0-beta.5`

It refers to `TabTheme` but doesn't import it (from `Tab.d.ts`)

**Comment by javivelasco** [comment]
Done @SleeplessByte, coming with the next beta

**Comment by olegstepura** [comment]
When do you think the next beta will be released?

**Comment by javivelasco** [comment]
Released!

**Comment by olegstepura** [comment]
Works with `react-hot-loader` now with `2.0.0-beta.6`, thank you!

**Comment by dimun** [comment]
I have cloned the repo and I'm trying with '2.0.0-beta.8' and I have the same issue, the tabs are not displaying.

![image](https://cloud.githubusercontent.com/assets/18353499/25536859/e131e9e2-2c01-11e7-83f0-48a4f728ad05.png)

**Comment by Rosenblad** [comment]
Same issue in beta 2.0.12

**Comment by nxstack** [comment]
I am also facing same issue with beta 2.0.12. Any idea, when this issue will be fixed? Is someone even looking into this?

**Comment by javivelasco** [comment]
It could be because you're requiring components w/o styles?

**Comment by dreadheadsic** [comment]
@ankurarora solution is to use `overrideComponentTypeChecker` like shown in [this comment](https://github.com/react-toolbox/react-toolbox/pull/1164#issuecomment-274853442)
Works with react-hot-loader@4.0.0
