### ISSUE TITLE
Table prop onRowClick is not documented

### ISSUE THREAD

**Issue by gustavohenke** [react-toolbox/react-toolbox#1160]
I had to debug the `Table`'s source to discover it actually had a `onRowClick` prop.

Seems like #827 missed it.

**Comment by javivelasco** [comment]
Thanks for reporting @gustavohenke but this implementation of `Table` is deprecated in favor of the future version available in the latest beta and this same `dev` branch. Feel free to open a PR to `master` we are only accepting fixes and releasing patches until 2.0 is stable. Recall you can use 2.0 beta now!

**Comment by gustavohenke** [comment]
And can I rely on the current docs to use the 2.0 beta?

**Comment by javivelasco** [comment]
Not yet, but each component has its own documentation file. If you browse each component folder in the current `dev` branch you will find the same docs as they appear in the site but updated with the current state and implementation. Take [this](https://github.com/react-toolbox/react-toolbox/tree/dev/components/table) as an example.
