### ISSUE TITLE
Ability to add HTML in values of source property of Autocomplete

### ISSUE THREAD

**Issue by grrseguin** [react-toolbox/react-toolbox#1161]
WDYT about add some HTML in values of `source` property of `Autocomplete`component ?

**Comment by javivelasco** [comment]
Sorry, no more work on the `Autocomplete` because it is going to be rewritten. The current implementation is very limited and we need something more flexible. Anyway I'm curious about why do you find it useful?

**Comment by grrseguin** [comment]
I want to show component like in `Dropdown` component.

**Comment by javivelasco** [comment]
@grrseguin It's going to be possible. The content of the suggestion will be completely given by users by nesting
