### ISSUE TITLE
Menu with selectable property doesn't display the selected value

### ISSUE THREAD

**Issue by mvanlonden** [react-toolbox/react-toolbox#1166]
I'm using menu as a dropdown component because I'd like to use a `<MenuDivider />`, but the setting the selectable property to true doesn't keep the selected value

**Comment by javivelasco** [comment]
Hi @mvanlonden! You can use it like that but the component doesn't keep the state, like other components, the `Input` for example, this component is stateless. You can pass the `selectable` property with the value you want to select but when it changes you have to capture the new value with a wrapper component and pass the new one.

Recall a reimplementation of the Dropdown is coming and with that you will be able to customize the appearance by adding separators and custom rendering items to do so. Patience!

**Comment by mvanlonden** [comment]
:) ok thanks! Wasn't aware of the reimplementation of dropdown. No problem,
worked around by using button in combination with menu. Awesome library,
thanks so much for putting it together
