### ISSUE TITLE
TextArea Component

### ISSUE THREAD

**Issue by dbrrt** [react-toolbox/react-toolbox#1167]
It'd be nice there could be a TextArea component in React-Toolbox

**Comment by javivelasco** [comment]
`Input` component with `multiline` enabled is a `TextArea` :)

**Comment by dbrrt** [comment]
Thanks for having highlighted it ;) Exactly what I was looking for.

**Comment by jimmywarting** [comment]
man... have too google it to figure it out, 

nonconventional,
