### ISSUE TITLE
theme property doesn't work on button with raised property

### ISSUE THREAD

**Issue by acambas** [react-toolbox/react-toolbox#1184]
If i add a theme object to a button component the styles are applied properly but when i add the raised property the styles are overridden

**Comment by rubenmoya** [comment]
Probably is because of these rules which override the color and background: https://github.com/react-toolbox/react-toolbox/blob/dev/components/button/theme.css#L172

You'll have to override them or use !important

**Comment by javivelasco** [comment]
That's right. Selector priority is an issue now but it will be progressively fixed. First one fixed will be the button but this is a common an well known issue across the library at the moment. Thanks for your response @rubenmoya. @acambas what you can do is to check in the Devtools the priority of the button selector and use the same or boosted in 1 point by namespacing your custom button
