### ISSUE TITLE
React-toolbox and Meteor with latest version 2.0.0-beta.5

### ISSUE THREAD

**Issue by Furqankhanzada** [react-toolbox/react-toolbox#1185]
Here is a demo how we where using it before https://github.com/nathantreid/meteor-react-toolbox-example
But now you changed all scss files to css and using css modules variables so how i can access these variables to my scss files ?

First i was doing like this :

```
@import "~react-toolbox/lib/globals";
@import "~react-toolbox/lib/list/config";

.card{
  border-radius: 0;
  margin-top: $unit * 1.5;
  .graphHeader{
    background: $color-primary;
    padding: 0 $unit * 3 0 $unit * 5;
    h3{
      padding: $unit * 2.2 0 $unit * 1.8 0;
      color: $color-primary-dark;
      letter-spacing: $unit - 0.9;
      font-size: $font-size-small * 1.8;
      width: 85%;
      float: left;
    }
``` 

Now i tried to change ```$unit``` to ```var(--unit)```  :

```
@import "~react-toolbox/lib/variables.css";
@import "~react-toolbox/lib/list/config.css";

.card{
  border-radius: 0;
  margin-top: var(--unit) * 1.5;
  .graphHeader{
    background: $color-primary;
    padding: 0 var(--unit) * 3 0 var(--unit) * 5;
    h3{
      padding: $unit * 2.2 0 $unit * 1.8 0;
      color: $color-primary-dark;
      letter-spacing: var(--unit)- 0.9;
      font-size: $font-size-small * 1.8;
      width: 85%;
      float: left;
    }
```

But its giving me error.

Any suggestion ?

**Comment by lucasljj** [comment]
You mixed the syntax of the postcss with that of the sass, try substituting all variables started with $ (sass variables) per var (--example)

**Comment by Furqankhanzada** [comment]
i did and getting ``` Error: Undefined operation: "var(--unit) times 1.5".
```

**Comment by rubenmoya** [comment]
You need to use `calc`, for example: `calc(var(--unit) * 1.5)`

**Comment by javivelasco** [comment]
The beta doesn't work with SCSS. It's only postcss. Also the builds will only keep *to-transform* custom variables that are included in postcss next. I'd change the example to either use [react-toolbox-themr](https://github.com/react-toolbox/react-toolbox-themr) with beta version or to go with a different configuration to remove sass completely replacing it with postcss.

Recall that for modern browsers you don't even need to transform the CSS!
