### ISSUE TITLE
Tabs in app bar like in the playground

### ISSUE THREAD

**Issue by stereokai** [react-toolbox/react-toolbox#1193]
I want to have tabs with an underline in the app bar.

How can I achieve this kind of layout, as used in the React Toolbox playground? I really couldn't find any documented example for it. Thank you very much!

![tabs2](https://cloud.githubusercontent.com/assets/2685357/22440175/b106cecc-e732-11e6-90fb-b3f3ffc0b1b7.PNG)

**Comment by javivelasco** [comment]
Here is an example https://github.com/react-toolbox/react-toolbox/issues/1144

:)

**Comment by stereokai** [comment]
Huh! I can't believe it was asked only 2 weeks ago! :)

I'm sorry for bothering you with it haha...

**Comment by javivelasco** [comment]
No bother at all! :)
