### ISSUE TITLE
Chip's avatar inside card displayed as block

### ISSUE THREAD

**Issue by wiikka** [react-toolbox/react-toolbox#1195]
Used themr, but I assume problem is in react-toolbox. Inside card avatars have style display: block, but if I want to use chip with avatar inside card it should inline-block. Seems like a bug or is there restriction in Google Material that chip shouldn't be used inside card? Beta 6.

**Comment by javivelasco** [comment]
That rule was assuming `Avatar` is known inside `Card` so it was wrong, thanks! :)
