### ISSUE TITLE
Default button colour should be neutral

### ISSUE THREAD

**Issue by nathanmarks** [react-toolbox/react-toolbox#120]
There doesn't seem to be a way to create a neutral coloured button as shown in the google material design documentation.

In material design web UI libraries that are official google projects, the default buttons are all neutral coloured:

https://material.angularjs.org/latest/demo/button
https://elements.polymer-project.org/elements/paper-button?view=demo:demo/index.html&active=paper-button
http://www.getmdl.io/components/index.html#buttons-section

Since there is a `primary` and `accent` prop, shouldn't the omission of both props result in a neutral button?

**Comment by javivelasco** [comment]
You are right. Working on it for the next buttons iteration

**Comment by nathanmarks** [comment]
@javivelasco Still got some work to do on the cards here... but it also made me realize we are missing another type of button.

We should be able to make buttons like this:
![image](https://cloud.githubusercontent.com/assets/4420103/11211620/bae7593c-8cfe-11e5-9b96-7c60ef0a73ae.png)

In other implementations you see them used widely, even material design lite which is very incomplete feature-wise has them.

The reason I noticed is because I was trying to put together a card with icon buttons:
![image](https://cloud.githubusercontent.com/assets/4420103/11211659/0a486e62-8cff-11e5-8767-ba724e07b809.png)

**Comment by javivelasco** [comment]
Ok, I'm adding them too in the `button-enhancements` branch!

**Comment by nathanmarks** [comment]
@javivelasco awesome!

PS, how can we setup the docs to allow for more examples to be shown easily?

The reason I am asking, is because I imagine I could probably show at least 7-8 examples of different possible cards that would be useful for users to see.

**Comment by javivelasco** [comment]
I think we can add more examples in the documentation. The loader is able to parse multiple examples in the documentation so you can structure it. One of the reasons why you should click to load each example is because that allows to have a proper parsed README file in github component folder.

Adding more should be just a matter of copying more code. The bad news about it is that probably there are people who want to see all examples at once instead of loading them one by one.

**Comment by nathanmarks** [comment]
That's the problem, loading 1 by 1 is not great UX.

Is it possible to have examples that are not part of the playground? I think that the playground is great for users to try things out, but not good for multiple examples.

**Comment by javivelasco** [comment]
Maybe we can try to figure out something. The main goal was to be able to see the readme in the Github repository too. Maybe with special comments as placeholders we would be able to display the rendering in the documentation and also load them in the playground

**Comment by nathanmarks** [comment]
I kind of like the playground just being minimal with the examples -- it makes it more friendly for the user to open it and try things.

I almost feel like the playground is a great complimentary tool to try out things from the more detailed examples.

**Comment by javivelasco** [comment]
Yes, we can try something to parse the README file and replace it rendering examples. I'm going to play a bit with it after the `Button` changes

**Comment by javivelasco** [comment]
Fixed in master but not released yet

**Comment by nathanmarks** [comment]
@javivelasco Love button flexibility now!

I'm wondering if it is worth turning buttons into a mixin so users can create their own colors easily:

```scss
.my-button {
  @include button($color: $brand-color, $type: 'raised');
}
```

**Comment by javivelasco** [comment]
Maybe we can consider it for future but actually I don't see an scenario where a user would use the mixin instead of using a toolbox button directly. Also, consider composition by importing from react toolbox with `composes` keyword from css modules!

**Comment by nathanmarks** [comment]
@javivelasco was just referring to the button colouring output for the various states, not the entire structure -- for custom buttons colors (for example a brand colour that has to follow certain guidelines for usage)

**Comment by javivelasco** [comment]
Isn't it possible to do it with `composes`??

**Comment by nathanmarks** [comment]
You're probably right, i'm not knowledgable about CSS modules
