### ISSUE TITLE
IE 11 style issues - Editable table

### ISSUE THREAD

**Issue by kartikraja** [react-toolbox/react-toolbox#1200]
Editable table has some style issues in IE 11. Cell texts are not visible and header text is center aligned even though it is set to "left". I guess cell text issue is due to the line-height property. It works fine if I remove the css property.

![cell_text](https://cloud.githubusercontent.com/assets/5374983/22475373/65d5fb22-e7a4-11e6-8737-51bdab61373c.PNG)
![table_header](https://cloud.githubusercontent.com/assets/5374983/22475372/65cd4220-e7a4-11e6-8ad3-1e21f5d5f8d8.PNG)

**Comment by javivelasco** [comment]
Hi! This is not going to be fixed since the `Table` component present in 1.x is deprecated in favor of a more flexible one shipped with 2.x. There is no official release yet so if you want to use it you can check the README files in the `dev` branch.
