### ISSUE TITLE
Styling improvements to Button component

### ISSUE THREAD

**Issue by matthewberkompas** [react-toolbox/react-toolbox#1202]
Hey guys. I've been using a custom `theme` prop to color the `Button` component in my project by  which has worked pretty well except for one issue. Here's a use case: 

I have a page with multiple buttons in various places on it. One button is a "Purchase Button" which I would like to be colored green so I make a theme and pass it to the button. Great! I have my green button. The other buttons on the page also need various styling. One of them is a "Delete" button which I want to be red. So, as before, I go into my theme file and add the necessary styles and pass the theme into the "Delete" button. Refresh and...the "Delete" button is green along with the "Purchase" button. 

Obviously, this is because you can't style multiple buttons with the same theme file. A work-around for this is to create separate theme files for each unique button but that gets really messy really fast. 

What I'm proposing as a solution to this problem is enabling more preset color options that could be set in the global `config.scss` file. Right now react-toolbox has only two (`primary` and `accent`) but it would be nice if it had 4 or 5. That way, developers could simply define what those colors were in `config.scss` and and pass them in as props like so: 
```javascript
<Button
  label={this.props.label}
  icon={this.props.icon}
  onClick={this.handleClick}
  className={`${className}`}
  success // << other options might be 'info', 'warning' and 'danger'
/>
```

This is similar to the twitter bootstrap approach, just not using classes. Thoughts?

**Comment by javivelasco** [comment]
Hi @matthewberkompas! Thanks for the feedback.

I think this shouldn't be done in the library. The reason is that, as far as I know, MD defines two levels of buttons for the primary and secondary colors. It is perfectly ok the need to have more buttons with different colors but as long as it can be achieved using theming, I think we should push down the responsibility.

For example, you can create a custom button over react-toolbox button:

```jsx
import RTButton from 'react-toolbox/lib/button';
import customTheme from './Button.css';

const Button = ({ className, success, delete, theme, ...others }) => {
  const _className = cn(className, {
    [style.success]: success,
    [style.delete]: delete,
  });
  <Button className={_className} theme={theme} {...others}/>
);

export default Button;
```

Then use if with the same API as react-toolbox but adding your custom props. I think this makes more sense than messing with more levels. I have to admit that the `Button` looks very simple but its css is not easy at all.

As I always say: if anybody else think we should add more props for different button levels please feel free to comment and we can reopen the issue if needed :) Thanks again for the feedback @matthewberkompas

**Comment by matthewberkompas** [comment]
That makes perfect sense. The solution you posted above should work fine for my needs. Just to confirm though, did you mean to use `<RTButton .../>` instead of `Button` in the example? I want to make sure I understand how it works. Thanks!

**Comment by javivelasco** [comment]
Yeah! Sorry, I meant RTButton :) glad it makes sense 😁

**Comment by matthewberkompas** [comment]
A couple other things: Where do `cn` and `style` come from in your example above?

**Comment by kwelch** [comment]
`cn` is common to name to use when importing `classnames` and binding it with CssModules. `style` is the import for the CssModules.

**Comment by kwelch** [comment]
I cannot esit on mobile but after reviewing the snippet, `cn` is not bound just `classnames` default export aliased as `cn`

**Comment by javivelasco** [comment]
Thanks @kwelch that's right.

Sorry @matthewberkompas, I've just updated the example :(

**Comment by matthewberkompas** [comment]
No problem. Thanks for taking the time to help!

**Comment by matthewberkompas** [comment]
<img width="382" alt="screen shot 2017-02-03 at 11 08 09 am" src="https://cloud.githubusercontent.com/assets/7084294/22604575/1737d47c-ea01-11e6-9757-2f980d845079.png">
This will be a huge help. Thanks again!

**Comment by matthewberkompas** [comment]
I really don't want to bug anyone but I have one more question. Is it possible to have _one_ theme file containing all the styles for success, warning, etc... instead of passing in a another theme file everywhere I use the button, thus having to include the styles I want to use in _that_ theme file? Basically, I want to just be able to add `success` as a prop and have by `CustomButton` component and it's `theme.scss` take care of styling it.

**Comment by prabhaav** [comment]
@matthewberkompas can you share the css you used to get the buttons working
