### ISSUE TITLE
List ListItem Ripple effect Issue

### ISSUE THREAD

**Issue by devarsh** [react-toolbox/react-toolbox#1205]
The ripple effect moves outside the bounds of the element, I've copied the example straight from docs, this occurs only with List.

| Library            | Version        | 
|:-----|:-----|
| `react`      | `15.4.2`   | 
|`react-toolbox` |`^2.0.0-beta.6` |

![Image](https://cloud.githubusercontent.com/assets/644099/22505666/b2ed38ae-e8a2-11e6-8ed6-e5a0990ca855.gif)

**Comment by tomahawkzx** [comment]
Same issue here,  2.0.0-beta.6.

**Comment by devarsh** [comment]
There is a typo error, which accidently passes ripple boolean to theme, which causes the classname to be set undefined.

I don't have the setup else i would post a PR is a very simple change.

https://github.com/react-toolbox/react-toolbox/blob/dev/components/list/ListItem.js#L75

**Comment by gustavohenke** [comment]
#1215
