### ISSUE TITLE
Tooltip type definitions prevent wrapping JSX Element

### ISSUE THREAD

**Issue by odenney** [react-toolbox/react-toolbox#1206]
Hey guys, I've been looking into using the Tooltip component but it seems when using it with typescript there is a restriction on what it can actually wrap. The type defs specify a React.ComponentClass is required meaning it won't wrap standard JSX Elements or a a stateless component. From what I can see in the actual js code of the Tooltip component there doesn't seem to be a need for this restriction. Is there anything I'm missing or is this a bug in the type defs?

Cheers

**Comment by javivelasco** [comment]
cc @panjiesw

**Comment by panjiesw** [comment]
Yup it should use `React.ReactType` instead I guess. Will send a PR for this soon.

**Comment by panjiesw** [comment]
Apparently I already discovered this issue and include a fix in PR #1163 :sweat_smile: 
You can see it [here](https://github.com/panjiesw/react-toolbox/blob/ts-validation/components/tooltip/index.d.ts), and the commit panjiesw/react-toolbox@bcd861c50a0edeac1966de0e97b0eeb277ab0684

**Comment by javivelasco** [comment]
Cool!
