### ISSUE TITLE
Enable avatar for List Checkbox Item

### ISSUE THREAD

**Issue by tomahawkzx** [react-toolbox/react-toolbox#1207]
Hi. 

Is it possible to combine the "avatar" feature of ListItem in the ListCheckbox? (like shown in the sample mockup below)

![image](https://cloud.githubusercontent.com/assets/18285859/22513327/0efc0e60-e883-11e6-80a5-52e53465b081.png)

I've checked the ListCheckbox's options and didn't found anything related to do so.  What could be the proper way to a accomplish this? 

Some of my considerations:

1) Use ListItem with a checkbox added to rightActions, and handle the checkbox state using ListItems's onClick event (to ensure that the user could click anywhere in the item to check it, not only by selecting the action)

2) Implement the rightIcon option in ListCheckbox. By doing so, it could be solved by using `rightIcon={<Avatar><img src={url}/></Avatar>}`. 

Thanks :)

**Comment by tomahawkzx** [comment]
I successfully implemented this as described in item **1.**, but I still wondering if this is the best practice.

### 

### List Items generated using .map()
Generates the array of `<ListItem />` components, adding a rightAction `<Checkbox />` and binding the event to handle the state both on _Checkbox.onChange_ and _ListItem.onClick_
```
  return this.state.checkData.map((item) => {
            return (
                <ListItem key={item.ContentSubscriber.userId}
                    avatar={item.ContentSubscriber.User.profilePic}
                    caption={item.ContentSubscriber.User.name}
                    legend={item.ContentSubscriber.User.email}
                    // selectable={true}
                    rightActions={
                        [<Checkbox 
                        checked={item.Checked} 
                        disabled={item.blockChange}
                        onChange={this.onItemClick.bind(this,item.ContentSubscriber.userId)} />]
                    }
                    onClick={this.onItemClick.bind(this,item.ContentSubscriber.userId)}
                    disabled={item.blockChange}
                    
                    >

                </ListItem>
      )
});
```


### onItemClick event
```
onItemClick(id) {
          var new_state = this.state.checkData.map(function (item) {
            if (item.blockChange){
                return item;
            }            
            var n_data = {
                ContentSubscriber: item.ContentSubscriber,
                Checked: (item.ContentSubscriber.userId == id? !item.Checked: item.Checked)
            };
            return n_data;

        });        

        this.setState({ checkData: new_state
            });
}
```

**Comment by javivelasco** [comment]
I think this can be closed then. You should be able to pass anything via composition :)
