### ISSUE TITLE
Have form validate like "formsy-material-ui"?

### ISSUE THREAD

**Issue by thearabbit** [react-toolbox/react-toolbox#1210]
I am a newbie for `React-Tollbox`.
Have form validate like "formsy-material-ui"?
Please help me.

**Comment by gustavohenke** [comment]
Form validations don't belong to an UI library like React Toolbox.

As a maintainer of the Redux Form library, I can say it's pretty easy to integrate it with React Toolbox:

```js
import Input from "react-toolbox/lib/input";
import { reduxForm, Field } from "redux-form";

const renderInputField = ({ input, meta: { touched, error }, ...props }) => (
  <Input
    { ...input }
    { ...props }
    error={ touched && error } />
);

const MyForm = ({ handleSubmit }) => (
  <form onSubmit={ handleSubmit }>
    <Field
      name="username"
      label="Username"
      type="email"
      required
      component={renderInputField} />

    <Field
      name="password"
      type="password"
      label="Password"
      required
      component={renderInputField} />

    <button type="submit">Submit</button>
  </form>
);

export default reduxForm({
  form: "login",
  validate ( values ) {
    const errors = {};
    if ( !values.username ) {
      errors.username = "Username is required";
    }

    // TODO add more validations
    return errors;
  }
})( Form );
```

Head over to https://redux-form.com if you want more examples and docs :)

**Comment by thearabbit** [comment]
Thanks for your reply, I think that `React Toolbox` have owner form validate like `formsy of MUI`.
I will check soon.

**Comment by javivelasco** [comment]
I agree. Validations, form handling, etc doesn't belong to react toolbox as we just provide UI components and this is more behavior. There are tons of libs that should be compatible with RT!

**Comment by thearabbit** [comment]
Could you extends [Uniform](https://github.com/vazco/uniforms).
It look great!

**Comment by javivelasco** [comment]
I still think it can be done outside react-toolbox :)
