### ISSUE TITLE
Date Picker/Time Picker and dropdown clear and set to null

### ISSUE THREAD

**Issue by Doff3n** [react-toolbox/react-toolbox#1213]
Hi thanks for creating such a good React framework.

IMO it should be possible to clear the Date Picker/Time Picker value so that the value is set to null.

That also goes for the Dropdown, the dropdown should have a Select none value that defaults to the value being set to null.

**Comment by javivelasco** [comment]
Thanks @Doff3n ! I think it makes sense too but I didn't see anything related to a reset in the material design guidelines. Good news is that both component are stateless and you can pass the state being stored somewhere else. 

This means you can easily change the value provided to the picker without actually touching the ripple, same as usually you find a "reset" button in forms. For this I think this shouldn't be included in the pickers... at the end it's a behavior achievable without modifying the library and there is no point on this in the spec either.

Thanks for your kind words and your feedback, I hope it helps!
