### ISSUE TITLE
Autocomplete showAllSuggestions: false on handleQueryChange is too aggressive when multiple: false

### ISSUE THREAD

**Issue by roerdinkholder** [react-toolbox/react-toolbox#1216]
According to the API documentation on `showSuggestionsWhenValueIsSet`:

> If true, the list of suggestions will not be filtered when a value is selected, until the query is modified.

With the following configuration of props:
```
<Autocomplete
  label='Country'
  multiple={false}
  onChange={this.handleChange.bind(this, 'country')}
  showSelectedWhenNotInSource
  showSuggestionsWhenValueIsSet
  source={countries}
  value={this.state.country} />
```

This shows the unfiltered source list whenever the query is empty, except when I take the following steps:

1. Select an item from the suggestions
2. Clear the suggestion (by back-spacing)
3. Start typing a query
4. Back-space until the query is gone

Now, the suggestion list is not shown anymore, and neither will it show if I set focus away from the component, and refocus. This seems very inconsistent and not intended to me.

The responsible code:
```
   handleQueryChange = (value) => {
     if (this.props.onQueryChange) this.props.onQueryChange(value);
     this.setState({query: value, showAllSuggestions: false, active: null}); // <-- showAllSuggestions: false
   };
```

It seems to me this change would result in the expected (at least, by me :)) behavior:

```
   handleQueryChange = (value) => {
     if (this.props.onQueryChange) this.props.onQueryChange(value);
     const showAllSuggestions = this.props.showSuggestionsWhenValueIsSet && !value.length;
     this.setState({query: value, showAllSuggestions, active: null});
   };
```
This would re-set showAllSuggestions to true if the query is emptied and showSuggestionsWhenValueIsSet was true to begin with.

**Comment by javivelasco** [comment]
Thanks for detailing this issue but it is one more of the reasons why #1169 exists. If you want to PR this change meanwhile and it doesn't break anything I'd be happy to merge :)
