### ISSUE TITLE
Running Docs locally only show blank page

### ISSUE THREAD

**Issue by supirman** [react-toolbox/react-toolbox#1218]
Trying run Documenation as written in https://github.com/react-toolbox/react-toolbox#authors-and-contributors

But it only show blank page. It may simillar with #1052.

Edit : It seem it can not find ```'react-toolbox/commons.css'```. When I remove it, it is working but the font is different with http://react-toolbox.com/.

**Comment by javivelasco** [comment]
Yes, we have to update the docs but since they are going to change a lot it's still broken. Anyway this is issued at #1151 so I'm closing in favor of that one
