### ISSUE TITLE
htmlFor on label breaks Checkbox, Radio and Switch

### ISSUE THREAD

**Issue by alexhisen** [react-toolbox/react-toolbox#1219]
https://github.com/react-toolbox/react-toolbox/pull/1180 introduced htmlFor attribute on labels that wrap input tags in Chekbox, Radio and Switch.

However, per HTML spec, the for attribute refers to the ID of the input element, not the name. If you in fact pass a name prop to them, these components stop working because input tags lack ids and the click event is not carried over to the htmlFor element because there is no such element.

In addition, the name of radio controls is not unique (all radios in a group are supposed to share the same name), so it cannot be used as an id and htmlFor, so htmlFor should just be removed from all three components.

**Comment by javivelasco** [comment]
Thanks for reporting!
