### ISSUE TITLE
Input propType on value and defaultValue should probably allow numbers

### ISSUE THREAD

**Issue by alexhisen** [react-toolbox/react-toolbox#1220]
https://github.com/react-toolbox/react-toolbox/pull/1180 changed the value prop type from any to object or string.

Input type=number should probably also support values that are numbers

**Comment by javivelasco** [comment]
Done!

**Comment by alexhisen** [comment]
Just discovered that Dropdown supports either string or number but RadioButton only string. The two should be consistent.
