### ISSUE TITLE
Updating beta-4 to beta-6 -> Module build failed: Error: Expected pseudo-class or pseudo-element

### ISSUE THREAD

**Issue by landabaso** [react-toolbox/react-toolbox#1223]
I just updated from beta-4 to beta-6 (beta-4 was already using css -not sass-).

I could build my project just fine with beta-4.

However, I'm getting 2 different types of message errors with beta-6:

1) 

```
Module not found: Error: Cannot resolve module 'react-style-proptype' in /Users/lbo/Sites/rwd/node_modules/react-toolbox/lib/checkbox
Module not found: Error: Cannot resolve module 'react-style-proptype' in /Users/lbo/Sites/rwd/node_modules/react-toolbox/lib/checkbox
Module not found: Error: Cannot resolve module 'react-style-proptype' in /Users/lbo/Sites/rwd/node_modules/react-toolbox/lib/slider
```

This can be solved by ` npm install react-style-proptype`. However I think react-toolbox package.json should add this dependency by itself.

EDIT: I checked and it looks like react-style-proptype is already in react-toolbox package...
Strange...
Should it be maybe in dependencies (not devDependencies)?

2) And also this one (repeated many times):

```
Module build failed: Error: Expected pseudo-class or pseudo-element
    at new error (/Users/lbo/Sites/rwd/node_modules/postcss-selector-parser/dist/processor.js:29:23)
    at Parser.error (/Users/lbo/Sites/rwd/node_modules/postcss-selector-parser/dist/parser.js:234:15)
    at Parser.pseudo (/Users/lbo/Sites/rwd/node_modules/postcss-selector-parser/dist/parser.js:336:25)
    at Parser.parse (/Users/lbo/Sites/rwd/node_modules/postcss-selector-parser/dist/parser.js:553:22)
    at Parser.loop (/Users/lbo/Sites/rwd/node_modules/postcss-selector-parser/dist/parser.js:521:18)
    at new Parser (/Users/lbo/Sites/rwd/node_modules/postcss-selector-parser/dist/parser.js:104:21)
    at Processor.process (/Users/lbo/Sites/rwd/node_modules/postcss-selector-parser/dist/processor.js:26:21)
    at /Users/lbo/Sites/rwd/node_modules/postcss-attribute-case-insensitive/dist/index.js:107:68
    at /Users/lbo/Sites/rwd/node_modules/postcss-loader/node_modules/postcss/lib/container.js:241:28
    at /Users/lbo/Sites/rwd/node_modules/postcss-loader/node_modules/postcss/lib/container.js:148:26
    at Root.each (/Users/lbo/Sites/rwd/node_modules/postcss-loader/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/Users/lbo/Sites/rwd/node_modules/postcss-loader/node_modules/postcss/lib/container.js:147:21)
    at Root.walkRules (/Users/lbo/Sites/rwd/node_modules/postcss-loader/node_modules/postcss/lib/container.js:239:25)
    at /Users/lbo/Sites/rwd/node_modules/postcss-attribute-case-insensitive/dist/index.js:106:7
    at LazyResult.run (/Users/lbo/Sites/rwd/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:276:20)
    at /Users/lbo/Sites/rwd/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:190:37
```

**EDIT:**
I should have mentioned that I am using themr like this:
```
const contextTheme = { 
  RTRipple: require('react-toolbox/lib/ripple/theme'),
  RTButton: require('./button'),
  RTDialog: require('./dialog'),
  RTOverlay: require('react-toolbox/lib/overlay/theme'),
  RTSwitch: require('./switch'),
  RTSlider: require('./slider'),
  RTProgressBar: require('./progress_bar'),
  RTInput: require('./input')
};
export default contextTheme;
```
And, then, for example  './tabs.css' looks like this:

```
@import 'react-toolbox/lib/tabs/theme';
@import './theme';

.label {
  font-size: 14px;
  padding: 0;
  padding-bottom: 14px;
  padding-top: 14px;
}
```
(where in ./theme.css I have some further colors and sized overrides, for example).

The message itself is not very descriptive. And from the Changelog I don't have any idea what may be going on.

@javivelasco any idea?

**Comment by landabaso** [comment]
Configuring postcss with postcss-apply reduces the number of times the message error (`Expected pseudo-class or pseudo-element`) from 30 to 7.

So anyone with this problem, just remind to add "`require('postcss-apply')(),`" to the array for postcss in webpack.

I'm still missing something new that was added from beta-4 to beta-6... (something used 7 times).

**Comment by olegstepura** [comment]
this should have been fixed by #1190

**Comment by landabaso** [comment]
It's not (at least in npm)...

This was a problem I could easily solve.

I'm still fighting with the other problem. Any idea?

**Comment by landabaso** [comment]
Wow... I finally found how to fix the problem!
`require('postcss-apply')(),`
has to be after
 `require('postcss-import')(),`

I hope this issue helps others...

I'm not closing it yet because npm is not including #1190 (so that @javivelasco can take a look to the issue and then close it).

**Comment by javivelasco** [comment]
Thanks @landabaso it's not in npm yet but I'm deploying a new version in the following days. Thank everybody who helped! :)

**Comment by phamcharles** [comment]
Has the fix 'Expected pseudo-class or pseudo-element' been released?

**Comment by javivelasco** [comment]
Nope, sorry. I'm releasing tomorrow!

**Comment by landabaso** [comment]
@phamcharles in order to solve the pseudo-* problem, the postcss section of webpack should look like this (in this exact order):
```
[
    require('postcss-import')(), 
    require('postcss-apply')(),
    require('postcss-extend')(),
    require('postcss-nested')(),
    require('postcss-cssnext')({
      features: {
        customProperties: {
          //variables: { //use them or not (up to you)
          //  mainColor: "red",
          //  altColor: "blue"
          //},
          //browsers: ['last 100 versions'] //depending on your project needs
        }   
      }   
    })  
    ,require('postcss-reporter')({ clearMessages: true })
  ]
```
