### ISSUE TITLE
Typescript: Input onKeyDown does not exist

### ISSUE THREAD

**Issue by junibrosas** [react-toolbox/react-toolbox#1225]
Seems like the typings for the Input component lacks onKeyDown.

I have this error:

Property 'onKeyDown' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Input> & { children?: ReactNode; } & InputProps

**Comment by junibrosas** [comment]
I avoided this typescript error via import the Input component using require.

var Input = require('react-toolbox/lib/input');

<Input.Input />

**Comment by javivelasco** [comment]
May you send a PR to fix this?

**Comment by codeaid** [comment]
It's the same with `onKeyUp`:

> error TS2339: Property 'onKeyDown' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Input> & Readonly<{ children?: ReactNode; }> & Rea...'
