### ISSUE TITLE
When the state for an autocomplete is null, it doesn't work

### ISSUE THREAD

**Issue by pupeno** [react-toolbox/react-toolbox#1226]
If you set null instead of "" as the starting stating of an non-multi autocomplete, it doesn't work. It doesn't show all the options and it doesn't let you select any option.

**Comment by rubenmoya** [comment]
I opened a PR to fix it, although I couldn't reproduce the error with the list not showing, are you using the `showSuggestionsWhenValueIsSet` prop?

**Comment by pupeno** [comment]
@rubenmoya no, I wasn't setting that property.
