### ISSUE TITLE
Differencing id and value in autocomplete

### ISSUE THREAD

**Issue by DaVinciLord** [react-toolbox/react-toolbox#1227]
I have an Autocomplete element set to allow the creation of new elements and one of my use case is that a user types what he wants (suggestionMatch is set to filter the results) and he presses the "Enter" key to choose the value entered without focusing one of the suggested values.
The problem comes when the value entered match a certain key in the source object, causing conflicts in the returned value. 

Example: 
```
sourceObject = {
 1: '2',
 2: '3'
};

valueFromAutoComplete = '2';
```

In this case I want the value '2' from sourceObject (which key is 1).
I can find my way to get the wanted key with lodash, but I cannot differenciate whether the value was focused before hitting 'Enter' or not.

**Comment by javivelasco** [comment]
@DaVinciLord sorry for taking this long to answer. Autocomplete is going to be refactored so I don't want to spend too much time working on it. It's proven that the data source is not a good approach so we are rather embracing nesting.

Did you get it working? I will try to work on it anyway but I can't dedicate too much, sorry :(

**Comment by DaVinciLord** [comment]
@javivelasco I decided to go for a text input instead, as this is my only use case (and I check for the entered value in database afterwards to get an ID if it exists)

**Comment by javivelasco** [comment]
Thanks!
