### ISSUE TITLE
How to apply theme to HOCs

### ISSUE THREAD

**Issue by gamliela** [react-toolbox/react-toolbox#1235]
I recently started using React Toolbox and I found it really cool and polished. Well done!

React Toolbox doesn't support RTL languages naturally, so I decided to create HOCs (high-order-components) that will wrap the original Toolbox components and add the missing functionality. For example, I created an element InputRTL that wraps the original Input element, and adds to it RTL support by injecting a theme property with customized CSS rules. Here is an example:

**InputRTL.jsx**
```
import theme from './theme.scss';
export class InputRTL extends React.Component {
    render() {
        let mergedTheme = Object.assign({}, theme, this.props.theme);
        return <Input {...this.props} theme={mergedTheme} />
    }
}
```
**theme.scss**
```
.input {
  &.withIcon {
    margin-left: 0;
    margin-right: 4.8rem;
  }
  .label {
    left: auto;
    right: 0;
  }
  .icon {
    left: auto;
    right: -4.8rem;
  }
}
```

This works perfectly, but the problem starts when I want to customize InputRTL itself. I can expose "theme" property from InputRTL, like I did in the example above, but how I can merge this property with the already existing theme? the simple Object.assign approach doesn't work because theme is a simple map, so keys are overridden and css selectors of InputRTL are lost.

Looking at the big picture, it seems that by design the "theme" property, in the context of React Toolbox, can be used only once in a chain of HOC components. To solve this problem, I think it would be great to have a property like "themes" (plural), that will accept array of themes and apply them in order. This way, each HOC will simply add it's customized theme to the array so nothing gets overridden and lost.

Thanks again and keep up the good work!

**Comment by javivelasco** [comment]
Hi @gamliela! That's the exact purpose of react-css-themr. You can compose your hoc with it to provide a theme that gets merged with the one you pass by props. Also, you can import a themeable function that expose this funcionality concatenating strings while it avoids duplication. 

Take a look, it should solve your issue! Otherwise, let me know! :)

**Comment by gamliela** [comment]
Hi @javivelasco, Thanks for answering!
I read about react-css-themr but: 

> First you need to use raw components to get this styles properly applied. Second, you have to add dependency themes by yourself. For example, the Button requires Ripple so you have to provide styles for both of them

I prefer using themed components and customize them when necessary, instead of overriding the whole theme, since it takes less time and knowledge. Also, you must use global ThemeProvider. I was looking for a simpler solution, and I thought that providing ability to merge themes from multiple sources can be helpful.

Anyway, I will try different approaches now and see how it goes. Thanks!

**Comment by javivelasco** [comment]
Maybe I didn't explained myself. That's the exact purpose of `react-css-themr`, there is a function `themr` that you can import. It merges two className objects:

```jsx
const a = { foo: 'foo-xyz', bar: 'bar-xyz' };
const b = { bar: 'baz' };
themr(a, b); // outputs { foo: 'foo-xyz', bar: 'bar-xyz baz' };
```

The HOC is to provide a default theme object and merge with this strategy any theme prop passed. You don't need to use the ThemeProvider. That's convenient to pass theme objects from context to any component of a particular type which is not your use case.

You either decorate your components or use the themr function straight, but it covers what you are exposing

**Comment by gamliela** [comment]
Thanks. I managed to have a working solution, using context and ThemeProvider.
But your solution is better because it is local to HOC and doesn't rely on global context.
Still, it is not clear to me, how do you theme the dependencies?
For example, if I want to theme CHECKBOX, I must also provide theme for RIPPLE, right?
How can I do that with themr function that accepts only one identifier?
Thanks!

**Comment by gamliela** [comment]
Got it. I simply apply themr twice. It works perfectly, and now I don't need ThemeProvider. Great!
