### ISSUE TITLE
#offtopic Interesting character

### ISSUE THREAD

**Issue by ShavidzeT** [react-toolbox/react-toolbox#1236]
Hey guys,
I have question out of this project.
Do you know what the character "ღ" is on your website's footer <img src="http://i.imgur.com/d7A4yiI.png">

**Comment by devarsh** [comment]
This might help http://heartsymbol.love/symbols/heart-sketch

**Comment by ShavidzeT** [comment]
@devarsh Yeah, right :+1:

**Comment by javivelasco** [comment]
😄
