### ISSUE TITLE
Error on importing ANYTHING from this lib

### ISSUE THREAD

**Issue by ShashankaNataraj** [react-toolbox/react-toolbox#1238]
I just did 

`$ npm install --save react-toolbox`

and 

`import { Button } from 'react-toolbox';`

Now I keep getting the below error from my webpack! What gives?!

```
Failed to compile.

Error in ./~/react-toolbox/lib/button/theme.css
Module build failed: Error: composition is only allowed when selector is single :local class name not in ".raised", ".raised" is weird
    at Array.map (native)
 @ ./~/react-toolbox/lib/button/theme.css 4:14-120 13:2-17:4 14:20-126
```

Im trying to include this in the app generated by `create-react-app` if that makes a difference...

**Comment by liangchunn** [comment]
If you'd be a little more patient, you should have already found the answer [https://github.com/react-toolbox/react-toolbox/issues/1054#issuecomment-267910222](here)

**Comment by ShashankaNataraj** [comment]
@liangchunn Sorry if I came off as impatient and aggressive, not sleeping for 36 hours will do that to a person.

Will go through the link you posted in my free time. Thanks a bunch!

**Comment by javivelasco** [comment]
Thank you @liangchunn 😊
