### ISSUE TITLE
Table example is not working

### ISSUE THREAD

**Issue by TheDeveloperXYZ** [react-toolbox/react-toolbox#124]
The table example is not working in all browsers (IE, FF, Chrome - Win 8.1).

Throws error in console.

http://react-toolbox.com/#/components/table

**Comment by javivelasco** [comment]
Wow, we forgot to upload the new example. Thanks for reporting, fixing!

**Comment by ipsips** [comment]
it's still broken

`TypeError: unknown: Property id of VariableDeclarator expected node to be of a type ["LVal"] but instead got null`

**Comment by javivelasco** [comment]
<img width="1280" alt="screenshot 2016-02-01 00 29 06" src="https://cloud.githubusercontent.com/assets/1634922/12705958/e0caa426-c87a-11e5-9b9a-b88119a40016.png">

It is for me 😕Which browser are you using?

**Comment by ipsips** [comment]
Safari 9

![screen shot 2016-02-01 at 10 55 58](https://cloud.githubusercontent.com/assets/1770542/12712655/989e72f6-c8d2-11e5-8466-37462a6cbb4b.png)

**Comment by javivelasco** [comment]
Ok, worth investigate it. I'm quite sure it should be a playground thing. Help here appreciated!

**Comment by ipsips** [comment]
cloned the repo and it seems to work just fine locally here

**Comment by javivelasco** [comment]
Ok, thanks! Issue to investigate :)

**Comment by MIGUELWAXX** [comment]
need support.. thanks

**Comment by goodbeysr** [comment]
i copied the code given in the exemple but it doesnt render . i checked the DOM and i found that the tbody is empty even if the source object is full of data

**Comment by Rabsztok** [comment]
@goodbeysr turns out that example on the website is outdated. For example how to use `Table` in `2.0.0-beta`, look at https://github.com/react-toolbox/react-toolbox/tree/dev/components/table#data-table

@javivelasco I think it would be very helpful to mention on top of README, that you should use docs from github source code and not from the website when using 2.0.0.
