### ISSUE TITLE
Layout:When NavDrawer or SideNav Pinned, Panel Height overflows beyond content

### ISSUE THREAD

**Issue by devarsh** [react-toolbox/react-toolbox#1242]
I'm not sure if this is the default behavior, but when Navdrawer is pinned, the height of the panel component increases resulting in a Vertical scrollbar even when content is not overflowing.

**Desired bhevior: ** 
Panel vertial scrollbar should not appear when content is not overflowing the screen.

![out](https://cloud.githubusercontent.com/assets/644099/22918535/c473f014-f2b0-11e6-8f6f-32d8d06b61af.gif)

**Comment by javivelasco** [comment]
It's definitely a bug. The space shouldn't affect the main panel, maybe it was broken at some moment. Do you have a repository with this example to debug it from there?

**Comment by devarsh** [comment]
Seems to be due to a min-height of 100% set on  'data-reactroot', when removing it, the problem goes away, but not sure what other parts get affected when I remove that.

And it happens with the example in layout Readme.md file

I'm using react-toolbox 2.0.0 beta-6

**Comment by olegstepura** [comment]
I tried here to override styling using `flex` model, but faced an issue when `NavDrawer` is always visible (theme wrapper was `flex: 1`, and it overlapped my content making it not usable). 

Also `Drawer` is removed from DOM when not visible, this leads to issues. For example if I use `react-router v4` and my `Switch` tag is a root one, and each `Route` is wrapped with `Layout` incl. `NavDrawer` , after I change route `NavDrawer` just disappears without animation.

Maybe it could be a good idea to restyle layout with flex taking all this into account.

**Comment by javivelasco** [comment]
It should work now! @olegstepura maybe it's a better idea to use flex indeed, but I need to dig deeper and remember the organization. This is going to be a target to be moved to styled components and that will be a good moment to check it out.

What I don't get is the problem with `Switch`. I've tried it out in a different project and it was working nicely using routes for the content. Maybe you can open a different issue to try to reproduce it?

**Comment by olegstepura** [comment]
Well, I need to create a test repo I think. Will open separate issue then.

**Comment by olegstepura** [comment]
@javivelasco was this fix included in the release of `2.0.0.beta.7` ? If yes, seems like it's not fixed (scrollbar appears when `NavDrawer` is opening or is closing (only during animation phase).

**Comment by javivelasco** [comment]
Nope sorry, I released before fixing but we can release again :)

**Comment by olegstepura** [comment]
@javivelasco let's release again ;)
