### ISSUE TITLE
Repeated class names

### ISSUE THREAD

**Issue by timurgarif** [react-toolbox/react-toolbox#1245]
Hi! Thanks for the project! 

I noticed some components render with class names repeated in the `class` attribute (twice or even more times). 
I'm playing with **ListItem**. It outputs html with class names 4 (!) times repeated. 
See http://react-toolbox.com/#/components/list
theme__itemText___1yEJl, theme__primary___3I6dC
![repeated-class-name](https://cloud.githubusercontent.com/assets/12256600/22930695/9ca2e53c-f2d2-11e6-989a-1264271f5e74.png)

Not a big deal but still a bug.

**Comment by devarsh** [comment]
@timurgarif  Yes it seems like a bug with the website, but have been using the component in my demo project and are not repeating.

![screen shot 2017-02-15 at 5 41 08 pm](https://cloud.githubusercontent.com/assets/644099/22973963/0f36c95a-f3a6-11e6-9696-fa29140f8573.png)

**Comment by timurgarif** [comment]
@devarsh, How did you get that?
In my project both server side and client rendering do repeat class names like in http://react-toolbox.com/#/components/list demo.

If your demo is public, a link to sources might be helpful.

BTW, I use "^1.2.1" version.

**Comment by devarsh** [comment]
@timurgarif, this could be the issue with version 1
I'm using react-toolbox": "^2.0.0-beta.6 for my project and it is not suffering from this issue, I've not yet installed and verified the same with version 1

**Comment by timurgarif** [comment]
@devarsh, I see. After a stable version release, I'll migrate to 2.x to check it. Thank you.

**Comment by javivelasco** [comment]
@timurgarif This is a behavior generated by react-css-themr. We recently added a patch to skip duplicated classnames so in the deployed docs (that corresponds to the stable version) it's still the old dependency and the issue is happening. Updating to 2.x as you guys said should work since the themr dependency is updated!
