### ISSUE TITLE
Each child in an array or iterator should have a unique key prop

### ISSUE THREAD

**Issue by sudhirbitsgoa** [react-toolbox/react-toolbox#1250]
```javascript
{this.state.complaints.map(comp =>
              <ListItem
                avatar={comp.avatar}
                caption={comp.caption}
                legend={comp.legend}
                key={comp.key}
                comp={comp}
              />
          )}
```
giving this warning
Warning: Each child in an array or iterator should have a unique "key" prop

**Comment by devarsh** [comment]
You need to provide unique key to each react elements, refer react docs,
this is not a react-toolbox issue

**Comment by sudhirbitsgoa** [comment]
Yes i understand. ListItem should be taking care of that some how. Might be by taking unique param.

**Comment by devarsh** [comment]
Well passing the `key` props to your` ListItem` component is the proper way to go, frameworks should not be taking care of that.

If you want to eliminate passing `key` altogether, perhaps you could create a wrapper Fn will take care of passing unique `key` to your components.

Something like this
```js
const renderList = (counter = 0) => (obj) => (
<ListItem
  caption={obj['caption']}
  to={obj['to']}
  activeClassName={GactiveClassName}
  className={GclassName}
  key={`ListItem_${counter++}`}
/>
)
export default renderList()
```

**Usage**
```js
const DemoComponent = () => (
<List>
{ array.map((item) => renderList(item)) }
</List>
)
``` 

Caution: Generate component in `compoentWillMount` and not in the `render`, else on every render call new elements will be created, becuase a new key will be allocated each time.

**Comment by sudhirbitsgoa** [comment]
well i'm passing the key to <ListItem> which is unique. Please look at top code. Still i observe the error.

**Comment by devarsh** [comment]
Well can you tell me the version of react-toolbox you're using

I'm using `"react-toolbox": "^2.0.0-beta.6"` and have not faced this issue like you one you're mentioning.
Are you sure this is the only component you're rendering as a list, if yes can you send me the link to your code.

**Comment by javivelasco** [comment]
Looks like it was a local issue. Thanks @devarsh !
