### ISSUE TITLE
Panel Not Aware of Fixed NavDrawer and AppBar?

### ISSUE THREAD

**Issue by logicalor** [react-toolbox/react-toolbox#1252]
I am trying to build a fixed NavDrawer / AppBar layout using the technique described in [Issue #1093, Comment #2](https://github.com/react-toolbox/react-toolbox/issues/1093#issuecomment-272811567).

I have built the project using create-react-app.

- react@15.4.2
- react-toolbox@2.0.0-beta.6

I'm also using [react-toolbox-themr@1.0.2](https://github.com/react-toolbox/react-toolbox-themr) to integrate the react-toolbox modules into my project without needing to eject from create-react-app.

It mosly works, but the Panel containing my content doesn't seem to be aware of the fixed AppBar and NavDrawer, so they both overlay the Panel.

![screenshot-bbw local 3000-2017-02-17-09-22-53](https://cloud.githubusercontent.com/assets/5744173/23046000/e9eb2378-f4f2-11e6-9dfc-7ff3d181b659.png)

Is this normal behaviour, or could it be a side effect of my project implementation (eg. react-toolbox-themr not porting over correct behaviour for the panel)?  If it's normal, then I guess I can shoehorn some behaviour when the component app loads or screen dimensions change, to nudge the margins of the Panel accordingly.

Here are my components:

```
export default class App extends Component {
	
  ...

  render() {

    const { children } = this.props;
    const { loggedIn, user, app, drawerActive, drawerPinned, 
      drawerClipped, appBarIconVisible, permanentAt } = this.state;

    return (
      <ThemeProvider theme={theme}>
        <Layout>
          <TopNav 
            loggedIn={ loggedIn } 
            user={ user } 
            title={app.title}
            drawerClick={this.toggleDrawerActive}
            appBarIconVisible={appBarIconVisible}
          />
          <SideNav 
            active={ drawerActive} 
            pinned={ drawerPinned } 
            clipped={ drawerClipped }
            loggedIn={ loggedIn } 
            user={ user } 
            title={app.title}
            onOverlayClick={this.toggleDrawerActive}
            permanentAt={permanentAt}
          />
          <Panel>
            {children}
          </Panel>
          <NotificationSystem ref="notificationSystem" />
        </Layout>
      </ThemeProvider>
    )
  }
}

export default class TopNav extends Component {

  ...

  render() {
    
    const { loggedIn, title, drawerClick, appBarIconVisible } = this.props;

    if (loggedIn) {
      return (
        <AppBar 
          className="AppBar" 
          title={title} 
          leftIcon={appBarIconVisible ? 'menu' : null} 
          onLeftIconClick={drawerClick} 
          fixed 
          flat
        >
          <Navigation type='horizontal'>
            <Link href='#/account/dashboard' label="Dashboard" />
            <Link href='#/account/profile' label="Profile" />
            <Link href='#/account/settings' label="Settings" />
            <Link href='#/logout' label="Sign Out" />
          </Navigation>
        </AppBar>
      )
    }
    
    else {
      return (
        <AppBar 
          className="AppBar" 
          title={title} 
          leftIcon={appBarIconVisible ? 'menu' : null} 
          onLeftIconClick={drawerClick} 
          fixed 
          flat
        >
          <Navigation type='horizontal'>
            <Link href='#/login' label="Sign In" />
            <Link href='#/register' label="Register" />
          </Navigation>
        </AppBar>
      )
    }
  }
}

export default class SideNav extends Component {

  render() {
    
    const { active, pinned, clipped, onOverlayClick, permanentAt } = this.props;

    return (
      <NavDrawer active={active}
        pinned={pinned} 
        permanentAt={permanentAt}
        clipped={clipped}
        onOverlayClick={ onOverlayClick }
      >
        <p>
           Test Content
        </p>
      </NavDrawer>
    )
  }
}
```

**Comment by devarsh** [comment]
Works for me
I'm not using any custom CSS theme, perhaps something could have gone wrong when you extended the `rect-toolbox` theme using `themr`.

version
-  react-toolbox@2.0.0-beta.6

![screen shot 2017-02-17 at 12 50 30 pm](https://cloud.githubusercontent.com/assets/644099/23056142/da41d53a-f50f-11e6-8e63-6400b69dbd77.png)

**App.js**
```js
import React, { Component } from 'react';
import { Layout, NavDrawer, Sidebar, Panel } from 'react-toolbox/lib/layout';
import { AppBar } from 'react-toolbox';
import Checkbox from 'react-toolbox/lib/checkbox';

class LayoutExample extends Component {
  state = {
    bodyScrolled: true,
    sideNavActive: false,
    sideNavPinned: true,
    sideNavClipped: true
  };

  handleToggle = param => {
    this.setState({ [param]: !this.state[param] });
  }

  render () {
    const { sideNavActive, sideNavPinned, sideNavClipped } = this.state;
    return (
      <Layout>
        <AppBar
          fixed
          leftIcon='menu'
          onLeftIconClick={this.handleToggle.bind(this,'sideNavActive')}
          title="Demo App"
        />
         <NavDrawer
          active={sideNavActive}
          clipped={sideNavClipped}
          onOverlayClick={this.handleToggle.bind(this,'sideNavActive')}
          pinned={sideNavPinned}
        >
        </NavDrawer>
        <Panel bodyScroll={this.state.bodyScrolled}>
          <h1> Hey there </h1>
        </Panel>
      </Layout>
    );
  }
}
export default LayoutExample
```

**Comment by logicalor** [comment]
Huh, thanks for that.  I'm getting the vertical scrollbar issue as well.  Seems to be due to a min-height of 100% set on my 'data-reactroot' div (ie, the immediate child of the app root).  Adding this to my index.css got rid of the scrollbars, but not sure if it affects anything else:

```
#root > div {
  min-height: none;
}
```

To address my other issue, for now I have added an onresize handler to nudge the panel, which is working for me. 

```
handleResize = () => {
  var appBarRect = document.getElementsByClassName('TopNav')[0].getBoundingClientRect();
  var navDrawerRect = document.getElementsByClassName('SideNav')[0].getBoundingClientRect();
  var topLevelPanel = document.getElementsByClassName('PanelTopLevel')[0]
  topLevelPanel.style.marginLeft = navDrawerRect.right + 'px'
  topLevelPanel.style.marginTop = appBarRect.bottom + 'px'
}
```

**Comment by javivelasco** [comment]
@logicalor the `AppBar` should be a direct descendant of the `Layout` component because it needs to be recognized in order to clone it injecting some props. If you need to write a wrapper for the component you can create a custom `Layout` by checking its definition in the source code and injecting your wrapped AppBar. If should be possible to customize just the `AppBar` content though.

This is a pattern that can appear in more places so I'm considering to add a property to specify a different component type each time a component needs to identify its children.

**Comment by davidharting** [comment]
@javivelasco So `<AppBar />` and `<NavDrawer />` both need to be a direct descendent of `<Layout />` in order for everything to work correctly?

That's what I'm seeing, but I wonder if it's because of error on my part rather than the toolbox.
