### ISSUE TITLE
Add required object to date and time pickers

### ISSUE THREAD

**Issue by bmulcahy** [react-toolbox/react-toolbox#1253]
So i am using react-toolbox components in some of my forms and let me say I like it a lot. The one thing I am missing though is the ability to add a required prop to the date and time pickers to match the other input components in my forms. 

Could I get some help on how I would do this manually or can I put in a feature request to have this added to the default component?

**Comment by javivelasco** [comment]
Thanks! There is an [spread] of additional properties over the `Input` component so you should be able to pass a `required` field and any other one not listed in the `DatePicker` properties but present for the `Input` component. It should work, if it doesn't please let me know to reopen the issue and check it out again :)

**Comment by JulianJorgensen** [comment]
Hi @javivelasco, I tried above and it doesn't seem to work. The component source code looks right to me, so I'm not sure where the bug is coming from. Will let you know if I find a fix.

**Comment by JulianJorgensen** [comment]
Ok so I've verified that DatePicker input does get added "required" prop correctly, but does not go through validation fully. See attached screenshot.
![developer_tools_-_http___localhost_3000_schedule_and_rise](https://user-images.githubusercontent.com/46347/27943039-85eac0d8-630e-11e7-8efc-7f062123f803.jpg)

**Comment by JulianJorgensen** [comment]
![rise](https://user-images.githubusercontent.com/46347/27943069-c7886f36-630e-11e7-9bd4-e14ccaab61e0.jpg)
