### ISSUE TITLE
Where'd the Sass go?

### ISSUE THREAD

**Issue by ballPointPenguin** [react-toolbox/react-toolbox#1254]
After following the setup instructions in the README, and spending time to configure node-sass and sass-loader, things just were not looking good.
Finally I drilled down in the library only to find that there are no .scss files, only css.
What even is going on?
It seems that the version you get with `npm install react-toolbox` is very different than that which is documented in the README and fancy website.
At the very least, a word of warning in the README would save newcomers like me a few hours of confusion.

**Comment by kwelch** [comment]
There is a line item in the `ReadMe.md` at line 8. 

https://github.com/react-toolbox/react-toolbox/blame/dev/README.md#L8

**Comment by javivelasco** [comment]
Thanks @kwelch !

**Comment by ballPointPenguin** [comment]
Thanks. Somehow I was only reading the #master README which has no such warning in it.
Not sure how I missed the #dev branch, since it is the default.

**Comment by ballPointPenguin** [comment]
I'd like to nag on this a little bit more. The reason I wasn't reading #dev README is because I was just reading http://react-toolbox.com/#/install
It makes sense that the website would document the stable version and not the dev release,
however since npm by default installs the dev release you are going to have people like me who keep getting confused. Steps to reproduce:
```
1. visit http://react-toolbox.com/#/install and follow instructions
2. :sad_panda:
```

**Comment by javivelasco** [comment]
Oh yes, sorry about that @ballPointPenguin. We are going to release 2.0 as stable without making too much noise and then deploy an updated version of the docs site. It's still on the sass version...

**Comment by ballPointPenguin** [comment]
I completely understand.
But until that release happens, anyone who follows http://react-toolbox.com/#/install will be confused when the styles don't load.

**Comment by javivelasco** [comment]
I know but while it's not stable I'm not sure about publishing the new docs either. A default install will get you 1.x which corresponds to the deployed docs. Anyway we are releasing 2.0 as stable very soon :)

**Comment by ballPointPenguin** [comment]
Thanks for all your work! I'm looking forward to it.
