### ISSUE TITLE
Cannot run docs

### ISSUE THREAD

**Issue by pupeno** [react-toolbox/react-toolbox#1267]
When trying to run the docs app from master, I got this error:

```
ERROR in ./app/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' C:\Users\pupeno\Documents\Dashman\react-toolbox\components/commons.css in C:\Users\pupeno\Documents\Dashman\react-toolbox\docs\app
 @ ./app/index.js 3:0-36
```

**Comment by elazzabi** [comment]
Got a similar error but worked fine after re-running npm install on both / and /docs directories

**Comment by javivelasco** [comment]
Right now the docs are broken as reported at #1151 In closing in favor of that one because I guess it's the same source of error.
