### ISSUE TITLE
Custom theme not working for NavDrawer [2.0.0-beta.6]

### ISSUE THREAD

**Issue by josemigg** [react-toolbox/react-toolbox#1279]
Hi!

I'm new using react-toolbox so maybe I made some mistakes.

I'm trying tu customize NavDrawer and it looks like the custom theme only is aware of .pinned theme property.

I tried this solution [https://github.com/react-toolbox/react-toolbox/issues/914](#914)

The code is the example one:
```
import React, { PropTypes, } from 'react';
import { AppBar, } from 'react-toolbox/lib/app_bar';
import { Layout, NavDrawer, Panel, } from 'react-toolbox/lib/layout';
import FontIcon from 'react-toolbox/lib/font_icon';
import theme from './layout.css';

class LayoutTest extends React.Component {
  state = {
    drawerActive: true,
    drawerPinned: true,
    sidebarPinned: true,
  };
  
  toggleDrawerActive = () => {
    this.setState({ drawerActive: !this.state.drawerActive, });
  };
  
  render() {
    return (
      <Layout theme={theme}>
        <NavDrawer active={this.state.drawerActive}
                   pinned={this.state.drawerPinned} permanentAt='xxxl'
                   onOverlayClick={ this.toggleDrawerActive }>
          <p>
            Navigation, account switcher, etc. go here.
          </p>
        </NavDrawer>
        <Panel>
          <AppBar leftIcon='menu' onLeftIconClick={ this.toggleDrawerActive } />
          <div>
            <h1>Main Content</h1>
            <FontIcon value='add' /> <FontIcon value='add' /> <FontIcon value='add' /> <FontIcon value='add' />
          </div>
        </Panel>
      </Layout>
    );
  }
}

LayoutTest.propTypes = {
  children: PropTypes.node,
};

export default LayoutTest;
```

and layout.css

```
.layout {
  .navDrawer {
    .drawerContent {
      background-color: blue;
    }
  }
}
```

I tried different approachs using the api defined in the docs page. I can only use these two properties to customize the navDrawer content: 
![image](https://cloud.githubusercontent.com/assets/8917610/23449928/cfdc434e-fe58-11e6-856d-c6dcf1e96071.png)

So for example this code is changing the NavDrawer background to blue when it's pinned:
```
     <NavDrawer theme={theme}
                   active={this.state.drawerActive}
                   pinned={this.state.drawerPinned} permanentAt='xxxl'
                   onOverlayClick={ this.toggleDrawerActive }>
          <p>
            Navigation, account switcher, etc. go here.
          </p>
        </NavDrawer>
```
```
.pinned {
  background: blue;
}
```

Note that in this last code I assigned the theme to the NavDrawer instead of Layout.

BTW, when are you releasing a new version? 

Thanks

**Comment by josemigg** [comment]
I've just realised that I'm using the 2.0.0-beta.6 version. I though I was using the last stable version

**Comment by rubenmoya** [comment]
Yep, you have to pass the theme to the NavDrawer, and then change it in the css without nesting it in the layout:

```
.navDrawerDrawer {
  background-color: red;

  &.pinned {
    background-color: green;
  }
}
```

**Comment by josemigg** [comment]
Thanks @rubenmoya it worked! 

Looks like the classes have changed from the documentation and I made some mistakes.
