### ISSUE TITLE
Ripple spans don't get removed in 2.0.0-beta.6

### ISSUE THREAD

**Issue by Qard** [react-toolbox/react-toolbox#1283]
Just trying out the react-toolbox-example repo with a quick upgrade from its current beta.4 to the latest beta.6 and noticed that somewhere between then and now the span elements created by ripples stopped getting removed from the button elements.

**Comment by javivelasco** [comment]
I've tried in multiple examples and it works well. Maybe the issue is that the ripple in your configuration doesn't have a transition defined for the expansion. In this case the remove listener may have never been called, but if you include default styles it should work well

**Comment by Qard** [comment]
I'm using whatever the configuration is in the react-toolbox-example project. I changed literally nothing other than installing the slightly newer beta.6. Either react-toolbox itself is broken or the example project is broken. 😕

**Comment by javivelasco** [comment]
Let me try it out too

**Comment by javivelasco** [comment]
It works for me 😕 

![screenflow](https://cloud.githubusercontent.com/assets/1634922/23868685/a2817fd2-0820-11e7-8c58-1656e9469e08.gif)

**Comment by Qard** [comment]
Hmm...I just did a fresh checkout in another directory and did the `npm install react-toolbox@2.0.0-beta.6` again and this time it works fine. I guess something went wrong with the npm install before? 😕

**Comment by javivelasco** [comment]
Maybe, it was broken in a previous release. Glad it works! :)
