### ISSUE TITLE
Docs should be clearer on how to import components when using react-css-themr / react-toolbox-themr and create-react-app

### ISSUE THREAD

**Issue by gmeans** [react-toolbox/react-toolbox#1288]
I just ran into the issue mentioned here: #1278 

The README mentions importing Raw Components, but this results in theme functionality being excluded.

https://github.com/react-toolbox/react-toolbox#raw-component

I think the Importing Components section would benefit from an additional sub-section describing how to import components when using the theming utilities and create-react-app.

**Comment by izakfilmalter** [comment]
Docs need to be updated for 2.0 still. It's something that will be worked on. 2.0 is still a beta release. If you need something more stable with good docs, I would drop down to 1.3.

**Comment by gmeans** [comment]
fair enough. thanks!

**Comment by javivelasco** [comment]
Thank for the answer @izakfilmalter !
