### ISSUE TITLE
FAB circular loading Indicator

### ISSUE THREAD

**Issue by nathanmarks** [react-toolbox/react-toolbox#129]
This is more of a future enhancement than anything -- just think it looks nice and would be fun to implement:

https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B0NGgBg38lWWbTlSaHdQZEMtalk/components-progressactivity-typesofindicators-061101_Circular_Aspirational_xhdpi_002.webm

**Comment by javivelasco** [comment]
Very nice, let's keep it for future!

**Comment by soyjavi** [comment]
I want implement it ... now

**Comment by javivelasco** [comment]
Closing in favor of #626
