### ISSUE TITLE
Unable to set initial values for react-toolbox dropdown

### ISSUE THREAD

**Issue by jsushankprdxn** [react-toolbox/react-toolbox#1292]
Hey,

I'm using redux-form with react-toolbox and I'm facing a scenario wherein I need to prepopulate the values in dropdown. Redux is providing me the initial values but it seems like react-toolbox Dropdown is not setting the values and hence I'm getting blank dropdown.

It would be great if someone could help me with this.

Thanks in advance!

**Comment by izakfilmalter** [comment]
In your constructor, are you setting the state for the value from your props?

**Comment by jsushankprdxn** [comment]
@izakfilmalter Really appreciate your help. But i got the problem solved as it was a fault from my end.

I had seperate data both in reducers file and Edit component which did not allowed the Dropdown to have pre-populated data. As i changed the data that is to be edited its working as expected now.

Anyways thanks for showing up.

**Comment by NarasimhaReddyY** [comment]
Getting same issue, can please post  a example to solve this issue?
