### ISSUE TITLE
Integrate redux-form

### ISSUE THREAD

**Issue by alexandru-tomescu** [react-toolbox/react-toolbox#1293]
Hi, 

Have you thought to integrate into form and input elements redux-form ?

https://github.com/erikras/redux-form

Thank you

**Comment by gustavohenke** [comment]
Hi @alexandru-tomescu!
I'm one of the maintainers of Redux Form, and I'm using it with React Toolbox for company products and for side projects.

The integration between both is very easy to achieve:

```js
import Input from "react-toolbox/lib/input";
import { reduxForm, Field } from "redux-form";

const renderField = ({ input, meta, ...props }) => (
  <Input
    { ...input }
    { ...props }
    error={ meta.touched && meta.error } />
);

export const Form = ({ handleSubmit }) => (
  <form onSubmit={ handleSubmit }>
    <Field
      name="name"
      component={ renderField }
      type="text"
      label="Name"
      required
    />
  </form>
);

// ..apply reduxForm HOC, maybe more
```

Finally, I must say that React Toolbox is an UI library.
It should never care about form submission and validation, just like Redux Form doesn't care about your UI details.
You can, however, create a 3rd party integration lib and request us to list it as a friendly lib.

**Comment by alexandru-tomescu** [comment]
@gustavohenke I agree with you. Everything you said is correct and true, but there could be an option also for this. Or... duplicated inputs components with redux-form integrated.

**Comment by gustavohenke** [comment]
Some reasons why this is a bad idea IMO:
- Even though Redux Form is quite popular, it's not a *defacto* lib to deal with forms in React land (compare it to React Router, for example)
- It could end up creating a maintenance burden for @javivelasco
- It could end up falling under a rock and released with low quality

So, really, I'm all for a 3rd party library.

**Comment by izakfilmalter** [comment]
Ya thirdparty lib is the way to go.

**Comment by alexandru-tomescu** [comment]
Ok, thank you guys. Now things are more clear.

**Comment by euanmillar** [comment]
It seems straightforward to add in DatePicker and DropDown like this:

```
const renderDropdown = ({ input: { onBlur, ...inputForm }, source }) => (
      <Dropdown {...inputForm} source={source}  />
    );
const renderDatePicker = ({ input: { onBlur, ...inputForm }, label, source }) => (
      <DatePicker {...inputForm} label={label} sundayFirstDayOfWeek />
   );
```
NOTE: onBlur is removed due to dispatches that are not needed on this component.

But what about a RadioGroup that consists of nested RadioButtons?

**Comment by michal-novacek** [comment]
@euanmillar thanks for suggesting to overload the onBlur, no idea why it messes with redux form but it sure does

**Comment by kushagraThapar** [comment]
Hello, I am trying to integrate react-toolbox's `RadioGroup` with `redux form` and I am having issues separating out the radio group component from the form itself as the radioGroup has nested RadioButtons. 
Is there a way to provide the radioButtons array into the radioGroup component from the form itself like we do in `select dropdown` component ?
