### ISSUE TITLE
How to change the primary color

### ISSUE THREAD

**Issue by Cleanshooter** [react-toolbox/react-toolbox#1295]
I've been reading the documentation (which still looks like it's for v1) and looking at the example project and I'm ready to admit that I give up.  All I want to do is change the default primary color from Blue500 to well anything else... and I can't find clear instructions on how to do it... the current Theming documentation doesn't make any sense and provides incomplete examples like it assumes we know how to use this tool... Sorry frustrated...

Can any one give it to me step by step how to do this one thing?

**Comment by izakfilmalter** [comment]
Are you using 1.3 or 2.0?

**Comment by Cleanshooter** [comment]
I just did `npm install --save react-toolbox` which as of now defaults to ^2.0.0-beta.6

**Comment by izakfilmalter** [comment]
Cool. Are you using https://github.com/react-toolbox/react-toolbox-themr or did you set up a css-modules step in your gulp file?

**Comment by Cleanshooter** [comment]
That's the part I'm struggling with... I did install the themr but I'm still not understanding how it can help me change the default primary color for all the components... when I read through the documentation  it sounds like I have to create a scss file for each component...

I'm not using gulp.

**Comment by izakfilmalter** [comment]
If you are using themr, you add it into you package.json file. Here is an example from one of my projects: 

```
  "reactToolbox": {
    "include": [
      "BUTTON",
      "INPUT",
      "SLIDER"
    ],
    "customProperties": {
      "preferred-font": "-apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'",
      "animation-duration": "0.3s",
      "color-primary": "var(--palette-amber-500)",
      "color-accent": "var(--palette-pink-a200)",
      "color-accent-dark": "var(--palette-pink-700)",
      "color-primary-contrast": "var(--color-dark-contrast)",
      "color-accent-contrast": "var(--color-dark-contrast)",
      "slider-snap-color": "var(--palette-amber-500)"
    },
    "output": "public/react-toolbox"
  },
```

**Comment by Cleanshooter** [comment]
correction I had react-css-themr installed... based on this part of the documentation https://github.com/react-toolbox/react-toolbox#customizing-all-instances-of-a-component-type

So if I'm understanding you correctly I should/could probably remove react-css-themr.  

Then install the one you mention, read it's documentation and rely on a snipit like the one you provide to do what I'm trying to do. (Thanks for the example btw...)

**Comment by Cleanshooter** [comment]
ok... so I guess I made some assumption here that I shouldn't have.  I assumed the App Bar component would use the primary color... it does not.  

So what is best way to just change the app bar color?  tried doing 
`"appbar-color":"var(--palette-grey-900)"`
in the custom properties of the package.json and it didn't have any effect...

Current documentation site says todo:

```
import React from 'react';
import { AppBar } from 'react-toolbox/lib/app_bar';
import theme from './PurpleAppBar.scss';

const PurpleAppBar = (props) => (
  <AppBar {...props} theme={theme} />
);

export default PurpleAppBar;
.appBar {
  background-color: #800080;
}
```

But that's doesn't seem to work either...

**Comment by Cleanshooter** [comment]
Current code (that does work):

App.js:

```
import React, { PropTypes } from 'react';

import Message from '../containers/Message';

//React-Toolbox implimentation
import { ThemeProvider } from 'react-css-themr';
import theme from '../css/react-toolbox/theme';
import AppBar from 'react-toolbox/lib/app_bar';
import AppBarTheme from '../css/react-toolbox/appBar.css'

const App = ({children}) => {
  return (
    <ThemeProvider theme={theme}>
    <div>
    	<AppBar title='Test' theme="AppBarTheme">
		  </AppBar>
			<Message />
  		{children}
    </div>
    </ThemeProvider>
  );
};

App.propTypes = {
  children: PropTypes.object
};

export default App;
```

appBar.css
```
.appBar {
  background-color: black;
}
```

This seems a bit less than ideal though since now I can't access anything from the color palette.  Any ideas on how I could do this a bit better?
