### ISSUE TITLE
Tab component always uppercase.

### ISSUE THREAD

**Issue by AntonioRecaldeRusso** [react-toolbox/react-toolbox#1296]
I read the documentation, and there is no option for making the tab labels not uppercase.
In a project we're working on, we decided to use React-Toolbox, but in one of our Tabs, the case of the Tab labels is relevant.
Is there a way to make the letter case not all uppercase?

**Comment by gustavohenke** [comment]
Use CSS.

```css
.label {
  text-transform: none;
}
```

```js
import theme from "./your.css";

<Tab label="foo bar" theme={{ label: theme.label }}>content</Tab>
```

**Comment by javivelasco** [comment]
Thanks @gustavohenke !

**Comment by danskal** [comment]
For anyone looking for a quicker and easier fix, something like: 

```
<Tab label="foo bar" sx={{ textTransform: "none" }}>content</Tab>
```
... will also do the trick

**Comment by Rhema7776** [comment]
How do i align the label  to the start
