### ISSUE TITLE
Multiline Label in input component not aligned

### ISSUE THREAD

**Issue by ShenAdrada** [react-toolbox/react-toolbox#1297]
![screenshot_2](https://cloud.githubusercontent.com/assets/26157352/23640441/b515b6ce-0328-11e7-960c-1b99730f04d8.png)

**Comment by ShenAdrada** [comment]
![screenshot_3](https://cloud.githubusercontent.com/assets/26157352/23640548/78562286-0329-11e7-9bf9-9be7f118b53b.png)

**Comment by rubenmoya** [comment]
It's related to this method https://github.com/react-toolbox/react-toolbox/blob/dev/components/input/Input.js#L119. Not sure how to fix it though.

**Comment by projoneftw** [comment]
temporary fix: in the component set `rows={1}`

**Comment by ShenAdrada** [comment]
thanks @rubenmoya . yes @projoneftw , that's what I did also to temporarily fix it. thanks!

**Comment by HandsomeMedia** [comment]
I think this is still an issue!  For us, the temp fix will not work if user enters more than 1 row of text - the component will not auto-resize.  Instead, we get an scrollbar controlling a 1-row viewport - yuck!
