### ISSUE TITLE
Buttons not visible clearly inside AppBar

### ISSUE THREAD

**Issue by vanthiyathevan** [react-toolbox/react-toolbox#130]
When a `Button` is inside `AppBar`, the default colour still remains dark. When button set as primary it's same colour as the AppBar bg. hard to see. And I noticed the `floating` buttons are squished

You can see this in the playground.
```jsx
  <AppBar>
    <Button href='http://github.com/javivelasco' target='_blank' raised>
      <GithubIcon /> Github
    </Button>
    <Button icon='bookmark' label='Bookmark' accent />
    <Button icon='bookmark' label='Bookmark' raised primary />
    <Button icon='inbox' label='Inbox' flat />
    <Button icon='add' floating />
    <Button icon='add' floating primary />
    <Button icon='add' floating primary disabled />
    <Button icon='add' floating accent mini />
    <Button icon='mood' toggle />
    <Button toggle primary>
      <GithubIcon />
    </Button>
    <Button icon='add' label='Add this' flat primary />
    <Button icon='add' label='Add this' flat disabled />
    <Button icon='bookmark' label='Bookmark' raised primary loading />
  </AppBar>
```

**Comment by javivelasco** [comment]
Hi @vanthiyathevan! 

I'd considerer a bug how the floating buttons are looking inside the `AppBar`, the should still look rounded. About the colors, I think there is no bug with them. A primary color has the same background color independently where it's positioned and it should be developer's responsibility to use proper colors for buttons over the AppBar.

I'm adding the bug label to investigate the problem with floating buttons but I think they shouldn't change it's default behavior depending on the context. That would be hard to determinate and maintain.

Thanks for reporting!

**Comment by javivelasco** [comment]
This is actually happening because the `AppBar` has a display `flex` attribute in the CSS. Since the collection of buttons are wider than the app bar the layout stretches the buttons. In a layout where the container does not exceed the `AppBar` size it wouldn't be happing.

Closing, thanks!
