### ISSUE TITLE
Menu/IconMenu "selected" prop is not working

### ISSUE THREAD

**Issue by felipeAndrade0918** [react-toolbox/react-toolbox#1300]
I am able to get it working in the Playground but not in my application.
My version is 2.0.0-beta.6.

Here's the code that I'm using for tests:

```
<IconMenu icon='more_vert' position='topLeft' menuRipple selectable={true} selected='help'>
 <MenuItem value='download' icon='get_app' caption='Download' />
 <MenuItem value='help' icon='favorite' caption='Favorite' />
 <MenuItem value='settings' icon='open_in_browser' caption='Open in app' />
 <MenuItem value='signout' icon='delete' caption='Delete' disabled />
</IconMenu>
```

**Comment by rubenmoya** [comment]
It is working for me with a newly created react app, the "highlight" is the text in bold and a transparent background, I don't know if that's right.

<img width="900" alt="screen shot 2017-03-08 at 21 14 41" src="https://cloud.githubusercontent.com/assets/905225/23722097/59b1dffc-0444-11e7-9423-0db87a584fc9.png">

**Comment by felipeAndrade0918** [comment]
I'll take a look again, thanks for the feedback.

**Comment by felipeAndrade0918** [comment]
The problem was at our end. Our font wasn't ready for font-weight 500.
Thanks everyone! =)
