### ISSUE TITLE
Dismiss button for Tab component

### ISSUE THREAD

**Issue by AntonioRecaldeRusso** [react-toolbox/react-toolbox#1310]
How could I add an "x" (close) clickable button to the Tab component? E.g.:

![screen shot 2017-03-08 at 11 39 48 am](https://cloud.githubusercontent.com/assets/5383318/23720986/3281d422-03f5-11e7-8227-a1988e938cda.png)

In future versions, I hope letting the developer add any html element to the tab label is allowed (same as RTButton). Based on the documentation, it seems that the label can only be a string.

I tried wrapping each tab with a Button, but the children of "Tab" can only be "Tabs" :(

**Comment by javivelasco** [comment]
Actually it is possible to pass an element as label so you can put any JSX you want. Combining this with style theme customization allows you to get the behavior you want:

<img width="636" alt="screenshot 2017-05-26 11 17 35" src="https://cloud.githubusercontent.com/assets/1634922/26488755/fd484c48-4204-11e7-96a6-ec2bd73e8258.png">

<img width="563" alt="screenshot 2017-05-26 11 18 18" src="https://cloud.githubusercontent.com/assets/1634922/26488774/09a0d046-4205-11e7-8493-9276441ad099.png">
