### ISSUE TITLE
Can you use a href in card title, and using _dangerouslySetInnerHtml in CardText

### ISSUE THREAD

**Issue by itsaphel** [react-toolbox/react-toolbox#1311]
Two questions, kinda...

`                    <CardTitle
                        title={this.props.post.title}
                        subtitle={this.formatDate(this.props.post.created_at)}
                    />`

1. Can I href just the title to a certain link?

2. For <CardText>, I use a BB code viewer for formatting. I transfer it to HTML during rendering (saved in DB as BB code). Can I use _dangerouslySetInnerHtml or something to show this HTML in the card text?

**Comment by rubenmoya** [comment]
For the first one, you can do something like this (with a `Link` from react router for example):

```
const Link = () => <a href="https://github.com/react-toolbox/react-toolbox/">React Toolbox</a>;
```

```
<Card className={style.card}>
        <CardTitle
          title={<Link />}
          subtitle="Subtitle here"
        />
        <CardText>Some text</CardText>
        <CardActions>
          <Button label="Action 1" />
          <Button label="Action 2" />
        </CardActions>
      </Card>
```

**Comment by LordRobust** [comment]
@rubenmoya Thank you for the response!

What I mean for 2 is... I have a <CardText> and inside it I have the body of my post:

`<CardText>{this.truncateString(this.props.post.body, 600)}</CardText>`

This body is in HTML. Like <strong>Hello</strong> world. I want to parse the HTML inside the CardText.

dangerouslySetInnerHtml won't work here. Anything else I can do?

**Comment by stern-shawn** [comment]
Have you tried applying dangerouslySetInnerHTML to an element inside of CardText?

Partial example of code that works in one of my projects. In this case post.content.extended.html is a string of html pulled from my DB, similar to what you described:
```
const summary = truncate(post.content.extended.html, 250);
...
<CardText>
    <p dangerouslySetInnerHTML={{ __html: summary }} />
</CardText>
```
