### ISSUE TITLE
Customize Dialog "close" nav button?

### ISSUE THREAD

**Issue by mjvalade** [react-toolbox/react-toolbox#1314]
When the Dialog is generated the "close" button is rendered in a `<nav>` at the bottom. Is it possible to move it to the top and render my content under it? Sometimes the scroll pushes the "close" off the screen and I would like to make it an "X" at the upper right corner.

**Comment by kylanhurt** [comment]
I am also wondering about this. As well as adding a permanent navbar header to the dialog box.

**Comment by mjvalade** [comment]
@kylanhurt did you ever figure out how to customize it?

**Comment by alaindresse** [comment]
Add a classname on the button in the actions, and add the appropriate styling in your css. I use:
```javascript
let actions = [{
   icon: "close",
   className: "snm-close-dialog",
   onClick: () => this.props.onCloseDialog(),
   neutral: false
}];
```
with the style
``` css
.snm-close-dialog {
    position: absolute;
    top: 0;
    right: 0;
}
```
