### ISSUE TITLE
Module parse failed button\theme.css

### ISSUE THREAD

**Issue by Bryze** [react-toolbox/react-toolbox#1315]
I copied the basic button implementation from the react-toolbox website and it seems to give an error in the react-toolbox theme. Please see the screenshot for the error.

My index.js file

`import React from 'react';`
`import ReactDOM from 'react-dom';`
`import { Button } from 'react-toolbox/lib/button';`

`ReactDOM.render(`
        `<Button label="Hello World!" />,`
   `     document.getElementById('app')
);`

My webpack.config.js file

`var HTMLWebpackPlugin = require('html-webpack-plugin');`
`var HTMLWebpackPluginConfig = new HTMLWebpackPlugin({`
`	template: __dirname + '/app/index.html',	`
`	filename: 'index.html',`
	`inject: 'body'
});`

`module.exports = {`

	entry: __dirname + '/app/index.js',
	module: {
		loaders: [
			{
				test: /\.js$/,
				exclude: /node_modules/,
				loader: 'babel-loader'
			}
		]
	},
	output: {
		filename: 'transformed.js',
		path: __dirname+'/build'
	},
	plugins: [HTMLWebpackPluginConfig]
};

and the package.json file
`   {
  "name": "react2",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "webpack",
    "start": "webpack-dev-server"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-toolbox": "^2.0.0-beta.7"
  },
  "devDependencies": {
    "babel-core": "^6.23.1",
    "babel-loader": "^6.3.2",
    "babel-preset-react": "^6.23.0",
    "html-webpack-plugin": "^2.28.0",
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.4.1"
  }
}`

This is the error
![error](https://cloud.githubusercontent.com/assets/10598701/23745767/7fe90aec-04df-11e7-92b1-ff610c71b4f3.PNG)

Am i missing something? Because all the website says is `npm install --save react-toolbox`, nothing more.
Note - `npm build` runs fine. `npm start` gives the error.
Please guide :)

**Comment by rubenmoya** [comment]
In your webpack config you need to handle the css, you only have the loader for the `.js` files. You have an example here: https://github.com/react-toolbox/react-toolbox-example
