### ISSUE TITLE
Dropdown styling

### ISSUE THREAD

**Issue by shankjn** [react-toolbox/react-toolbox#1329]
I'm unable to style the dropdown's border bottom when the component is disabled. By default, it considers dotted border from .disabled > .inputElement. I did not understand how exactly dropdown takes styling from the input element. Does anyone have a solution so that I can replace the default dotted border when disabled with the border I want.

**Comment by rubenmoya** [comment]
I'll check it this afternoon at home, but maybe overriding this one? https://github.com/react-toolbox/react-toolbox/blob/dev/components/dropdown/theme.css#L67

**Comment by shankjn** [comment]
Tried that already. Does not work.

**Comment by shankjn** [comment]
![image](https://cloud.githubusercontent.com/assets/22961090/23949086/3248fa64-095c-11e7-9aa2-3d23d8126761.png)

It takes the disabled property from inputElement of input, which makes it difficult to make any changes to the dropdown.

**Comment by rubenmoya** [comment]
Have you tried with this?

```
.test {
  & input {
    border-bottom: 1px solid red !important;
  }
}
```

![screen shot 2017-03-15 at 22 29 57](https://cloud.githubusercontent.com/assets/905225/23971618/f2c543ac-09ce-11e7-85df-9e8b89424514.png)

**Comment by shankjn** [comment]
I'm able to change the dropdown border when enabled. I was looking for a solution where I can change my border color when dropdown is disabled.

**Comment by shankjn** [comment]
.dropdown input {
    border-bottom: 1px solid black;
}
This works for me, but &.disabled for the same condition does not.

**Comment by shankjn** [comment]
Does anyone have a solution for styling the dropdown border-bottom when it is disabled?

**Comment by vinogradov** [comment]
From the [documentation](https://github.com/react-toolbox/react-toolbox/tree/dev/components/dropdown):
> "This component uses an `Input` under the covers. The theme object is passed down namespaced under `input` keyword. This means you can use the same theme classNames from `Input` component but namespaced with `input`. For example, to style the label you have to use `inputLabel` className."

So the answer is:

```sass
.inputDisabled > .inputInputElement
  border-bottom-style: solid
  color: inherit
```
