### ISSUE TITLE
Doesn't install on ubuntu 14.04

### ISSUE THREAD

**Issue by kreneskyp** [react-toolbox/react-toolbox#133]
I've been trying to install react-toolbox as dependency for a project.   `npm install` works when run locally on os/x 10.11.1, but not in an ubuntu 14.04 docker container.  Both the host and client are using `node v4.1.1` and `npm v2.14.4`

Webpack gives an error when importing react-toolbox components. 

```
Module not found: Error: Cannot resolve 'file' or 'directory' /var/project/node_modules/react-toolbox/lib/button in /var/project/wet_arms/static/jsx/dashboard
```

The source for react-toolbox is in `./node_modules/react-toolbox` but there is no `lib` directory.  `npm install react-toolbox --verbose` doesn't show any errors.

The dev dependencies for my project were copied from the example project:
```
  "devDependencies": {
    "core-js": "^1.2.6",
    "es6-promise": "^3.0.2",
    "autoprefixer": "^6.0.3",
    "babel-core": "^6.1.4",
    "babel-eslint": "^4.1.5",
    "babel-loader": "^6.0.1",
    "babel-plugin-react-transform": "^1.1.1",
    "babel-preset-es2015": "^6.1.4",
    "babel-preset-react": "^6.1.4",
    "css-loader": "^0.21.0",
    "extract-text-webpack-plugin": "^0.9.0",
    "normalize.css": "^3.0.3",
    "node-sass": "^3.4.1",
    "postcss-loader": "^0.7.0",
    "react": "^0.14",
    "react-addons-css-transition-group": "^0.14.2",
    "react-addons-test-utils": "^0.14.2",
    "react-dom": "^0.14.2",
    "react-toolbox": "0.12.9",
    "react-transform-catch-errors": "^1.0.0",
    "react-transform-hmr": "^1.0.1",
    "sass-loader": "^3.0.0",
    "style-loader": "^0.13.0",
    "toolbox-loader": "0.0.3",
    "webpack": "^1.12.0",
    "cross-env": "^1.0.1",
    "express": "^4.13.3",
    "redbox-react": "^1.1.1",
    "webpack-dev-middleware": "^1.2.0",
    "webpack-hot-middleware": "^2.4.1"
  }
```

**Comment by soyjavi** [comment]
Have you tried use the official React-Toolbox-Example https://github.com/react-toolbox/react-toolbox-example??

**Comment by kreneskyp** [comment]
Yes, same result when using the example.

```
$:/srv/react-toolbox-example# ls node_modules/react-toolbox/
LICENSE    components  karma.conf.js  server.js  tests.webpack.js               webpack.config.test.js
README.md  docs        package.json   spec       webpack.config.development.js
```

**Comment by javivelasco** [comment]
So weird. I've just updated the example yesterday with the last version. Can you try with it? It works for me.

**Comment by kreneskyp** [comment]
Was an issue with the version of node/npm.  I had older versions already installed.  Manually installing newer versions of node/npm caused some sort of conflict.  I started with a fresh ubuntu container and followed [these instructions](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions).  Everything works now.

**Comment by javivelasco** [comment]
Awesome, thanks for the update @kreneskyp !!
