### ISSUE TITLE
React-toolbox uses version of react-css-themr that breaks with isomorphic-style-loader

### ISSUE THREAD

**Issue by fredantell** [react-toolbox/react-toolbox#1335]
First off, thank you for this library :)

RT uses react-css-themr 1.7.2 as of this writing which has a bug with Isomorphic style loader. I was just editing my yarn.lock file to force it to use react-css-themr@2.0.0 which has a fix for the issue:
https://github.com/javivelasco/react-css-themr/issues/44
(TL;DR Isomorphic Style Loader injects functions into the CSS Module and when themr reflects over the style object it was previously only expecting strings and threw an error when it got to the functions that ISL injected. The fix just added a ```typeof function``` check)

My workaround was to force themr to 2.0 despite its breaking changes. Unfortunately I noticed that for some reason with 2.0 the ```<Dropdown />``` RT component's blur function is firing and closing the dropdown before the onClick function to select a value can fire. If I just swap in 1.7.2 and manually edit in the typeof check, this same code works fine. Unfortunately, I couldn't figure out what it was about 1.7.2 vs 2.0.0 that meant that the blur function fired first with 2.0 but the handleSelect function fired first in 1.7.2.

Is it ok to ask for a hotfix to react-css-themr to bump to 1.7.3 (i.e. add the 2 or so lines of code that makes it compatible with ISL) and an update of react-toolbox's dependency?

If you'd like me to help in any way let me know what I can do.

**Comment by fredantell** [comment]
I developed a pretty elaborate workaround that involves stripping the functions injected by isomorphic-style-loader off of the CSS Modules before I hand them to anything that may invoke themr() from react-css-themr.

I'm then still using withStyles to actually inject the CSS into the DOM. To that function I need to pass the original CSS Modules with the functions still injected.

In order to get the ordering of all the stylesheets correct I'm doing this all on a wrapper that has access to the RT component's base style sheet, all of its dependencies' base styles, and the overrides I'm passing in via props.

If this pattern actually turns out to work I can share it since it was definitely not easy arriving at it. I tried a lot of different approaches all which had subtle or not so subtle issues.

**Comment by javivelasco** [comment]
Please share! Closing then :)

**Comment by hardchor** [comment]
@fredantell Could you please share your solution?

**Comment by landabaso** [comment]
The ugly workaround is to manually edit `yarn.lock` (if using yarn) and force react-toolbox to use `react-css-themr "^2.0.0"`.

react-css-themr 2.0.0 with react-toolbox beta works fine for me. However, I guess there are some incompatibilities depending how you use it.

Also, it is not recommended to manually edit `yarn.lock`. In addition, after upgrading packages, sometimes yarn.lock is reseted and you have to edit it again.

**Comment by javivelasco** [comment]
Already updated :)
