### ISSUE TITLE
Not able to integrate with react-redux-starter-kit

### ISSUE THREAD

**Issue by techhysahil** [react-toolbox/react-toolbox#1337]
I was trying to integrate react-toolbax with [React redux starter kit](https://github.com/davezuko/react-redux-starter-kit) but issue is coming in style compilation. I tried various solution but nothing is working for me. 

I really wanna go ahead with both of these. Can someone please help me out, i am getting stuck on this.

**Comment by tobiasandersen** [comment]
I haven't used that project, but if you don't have control over the webpack config, you'd have to do something like this: https://github.com/react-toolbox/react-toolbox#usage-in-create-react-app-projects.
