### ISSUE TITLE
Is it possible to use your toolbox with create-react-app ?

### ISSUE THREAD

**Issue by francoisgeorgy** [react-toolbox/react-toolbox#1342]
Hi,
I'm a beginner with react. 
I would like to use your toolbox with the https://github.com/facebookincubator/create-react-app project. I get the following "classic" error:

Error in ./ /react-toolbox/lib/button/theme.css
Module build failed: Error: composition is only allowed when selector is single :local class name not in ".raised", ".raised" is weird
    at Array.map (native)
 @ ./ /react-toolbox/lib/button/theme.css 4:14-116 13:2-17:4 14:20-122

Altough I have found a lot of info regarding this error I'm still unable to solve it. All the solutions talk about a webpack config file, but your project hides webpack. So, how can I solve this?

Thanks for your help.

**Comment by priecint** [comment]
Hey,

I don't think that's possible without [ejecting](https://github.com/facebookincubator/create-react-app/#converting-to-a-custom-setup). The thing is CRA hides webpack config from you, not react-toolbox.

**Comment by francoisgeorgy** [comment]
Thanks for your answer. That's exactly what I feared :-( This makes create-react-app useless.

**Comment by gustavohenke** [comment]
How curious, I started trying CRA yesterday, and I searched instead of asking. I found this: #707

**Comment by francoisgeorgy** [comment]
Very interesting. I did find a lot of threads talking about this problem, but not that one. Than you.

**Comment by francoisgeorgy** [comment]
I just tried react-toolbox with a vanilla react project and it works fine. So, I just will not use create-react-app. That's ok for me.

**Comment by gustavohenke** [comment]
There are ways to workaround this issue, for example one could fork react-scripts (like [custom-react-scripts](https://github.com/kitze/custom-react-scripts) did) and make it work with React Toolbox.

But chances are that the maintenance burden probably outweighs the advantage of using CRA... so you end up ejecting it anyway :D

**Comment by vmsoftware** [comment]
https://cloud.githubusercontent.com/assets/1634922/21305836/285a092a-c5ce-11e6-8ad4-7b170dc97d1b.gif

**Comment by francoisgeorgy** [comment]
Thanks all of you for your help.
