### ISSUE TITLE
TypeError: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by FDiskas** [react-toolbox/react-toolbox#1345]
Version: 2.0.0-beta.7
https://github.com/react-toolbox/react-toolbox/blob/2.0.0-beta.7/components/app_bar/AppBar.js#L71
```
TypeError: Cannot read property 'getBoundingClientRect' of null
      
      at AppBar._this.initializeScroll (node_modules/react-toolbox/lib/app_bar/AppBar.js:54:51)
      at AppBar.componentDidMount (node_modules/react-toolbox/lib/app_bar/AppBar.js:73:16)
      ...
```
This problem happening then I trying to write a tests using `react-test-renderer`
I think that this is because of headless browser.

**Comment by FDiskas** [comment]
The same error you can get then there is no element try running in console:
```js
document.querySelector("missing element").getBoundingClientRect();
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
```
:snail:

**Comment by samybob1** [comment]
https://github.com/facebook/react/issues/9244
