### ISSUE TITLE
Change theme realtime?

### ISSUE THREAD

**Issue by eduardoinnorway** [react-toolbox/react-toolbox#1347]
Hi,

Is there any way now or future plans to add support to add a theme on realtime?

I have done of ton of apps where they want theming based on target group. For example if I get some queryparam with ?theme=foo, then I would like to set a global theme from the corresponding foo theme.

Feedback?

**Comment by supirman** [comment]
I would like to know this too. As far as I know you will need to compile different theme into different css then you need logic to change loaded css.

**Comment by kwelch** [comment]
For v1.x I assume this is not possible at all since everything is in css. 

I am very interested if the changes in v2 have allowed for this possibility.

**Comment by gustavohenke** [comment]
@kwelch, AFAIK, v2 moves to PostCSS from SCSS, and refactors/rewrites/adds some components. That's all.

**Comment by eduardoinnorway** [comment]
Well, with some playing around we made it work, you can use the ThemeProvider as a wrapper around the changing content/pages.

Create a library for the "themes", we want to handle more than just styling of react-toolbox.

> /themes
>    /theme1
>        /styles
>            button.css, appBar.css ...
>        /img
>            logo.svg, ....
>         theme.js  //Returns an object with all theming resources.
>     /theme2 ....
> index.js //Exports all themes

`
//index.js
import theme1 from './theme1/theme';
import theme2 from './theme2/theme';

export default {
  theme1,
  theme2
};`

Now you can import the theme bundle anywhere, and set the theme you desire. Note that if you want to change the theme on the fly you need to force render the ThemeProvider, we want to change with param set before, so we don't have need for on the fly theming.

Import theme, set the right them and add it to the ThemeProvider:

<ThemeProvider theme={theme.styles}>
