### ISSUE TITLE
Additional Info/Icon in Card Header?

### ISSUE THREAD

**Issue by sammy-tam** [react-toolbox/react-toolbox#1348]
I'm new to this but react toolbox has been working great so thanks everybody around here.

I have a question as I'm using the Card component, most particularly with the Card Title component.  What is the proper way, if possible, to implement icon / status text on the top right corner of the card, similar to these examples from the spec?

![Image of 1](https://storage.googleapis.com/material-design/publish/material_v_10/assets/0Bzhp5Z4wHba3cXJ0OTI1MXJUV0U/components_cards_action5.png)

![Image of 2](https://storage.googleapis.com/material-design/publish/material_v_10/assets/0Bzhp5Z4wHba3UWdmRm15cGR2TGM/components_cards_action4.png)

Any thoughts?

**Comment by realart** [comment]
I have exact same request!

**Comment by MichaelGregory** [comment]
The`title` prop on `CardTitle` component accepts markup which will be rendered inside the H5 element. Specify something along the lines of
```
<div>
  <div class="align-left">
    Google
  </div>
  <div class="align-left">
    <IconMenu>...</IconMenu>
  </div>
</div>
```

You'll need to use CSS to get the alignment right, including specifying a width on the DIV containing the H5.
