### ISSUE TITLE
Possible to import css classes or variables?

### ISSUE THREAD

**Issue by brian-gates** [react-toolbox/react-toolbox#1349]
I'd like to reference variables and classes within my own css.  Is this possible?

e.g. can I reference the shadow variables?

```
.myclass {
  box-shadow: var(--shadow-3p);
}
```

Or compose classes?

```
.mybutton {
  composes: button
}
```

**Comment by k0r8i** [comment]
Use
`@import 'react-toolbox/lib/variables.css';`
in your own css files and use whatever variable is defined in variables.css :)

**Comment by brian-gates** [comment]
This works perfectly, thank you!
