### ISSUE TITLE
Fixed label?

### ISSUE THREAD

**Issue by eduardoinnorway** [react-toolbox/react-toolbox#1352]
I see in code there are som references to .fixed regarding Label in input compontent. I would like to set the label fixed on top of Input when wanted. Is there a way today?

For example:

<Input fixedLabel=boolean

Anyways, awesome job so far, I think we will contribute with some components in future. We really like the setup.

/Eduardo

**Comment by drager** [comment]
@eduardoinnorway: Using `<Input floating />`, will indicate if the label is floating in the input field or not. Floating is set to `true` by default. So what do you want, could you elaborate?

**Comment by m-maksyutin** [comment]
@eduardoinnorway: Override css like it's described in Customizing components part on http://react-toolbox.com/#/install

Use something like this:

```
@import "react-toolbox/lib/input/theme.css";

:root {
    --input-label-font-size_custom: var(--font-size);
}

.inputElement {
    &:focus:not([disabled]):not([readonly]),
    &.filled,
    &[type='date'],
    &[type='time'] {
        & ~ .label:not(.fixed) {
            font-size: var(--input-label-font-size_custom);
            top: var(--input-focus-label-top);
        }
    }

    & {
        & ~ .label:not(.fixed) {
            font-size: var(--input-label-font-size_custom);
            top: var(--input-focus-label-top);
        }
    }
}

.counter {
    font-size: var(--input-label-font-size_custom);
}
```

**Comment by LachlanStuart** [comment]
@drager I think they may mean like the "Fixed Floating Label Text" example from here: http://www.material-ui.com/#/components/text-field where the label is permanently above the input, allowing the `placeholder` attribute to be used without the label overlapping the placeholder text. 

IMO it would be worth adding `.inputElement[placeholder]` to the list of rules that triggers the label to be raised, as currently specifying a `placeholder` causes unsightly overlapping text. Unfortunately I don't have time at the moment to make a PR.
