### ISSUE TITLE
beta-7: Dropdown onBlur called on focus

### ISSUE THREAD

**Issue by ben-freenome** [react-toolbox/react-toolbox#1354]
Dropdown's onBlur function is called on focus, not blur. This seems to be what is leading to the problem where tabbing through multiple dropdowns does not close the previous dropdown, so that all previous dropdowns remain open.

**Comment by flushentitypacket** [comment]
Just ran into this as well. Seems like it'd be as simple as removing this line:
https://github.com/react-toolbox/react-toolbox/blob/3d8cd6689b61760c7b5a39d45c2ed0af3c968403/components/dropdown/Dropdown.js#L102

**Comment by burtontanner** [comment]
I also cannot get the onBlur prop to fire correctly.

**Comment by Schw2iizer** [comment]
I am also having the same issue.
