### ISSUE TITLE
Button Ripple effect strange behaviour

### ISSUE THREAD

**Issue by raza2022** [react-toolbox/react-toolbox#1357]
**Edit: here is my repo link https://github.com/raza2022/final-react**
@mjurincic @drhayes @okonet @owais @Rendez Thanks for the great work.
I tried the tool box with a already scofoled project with https://github.com/stylesuxx/generator-react-webpack-redux
after hours i successfully solved all errors link to` loaders` `webpack ` `config `and bla bla.
now the issue is that it's misbehavior some styles for example ripple effect ( when click on button ) it creates a big black circle instead of ripple effect.
![image](https://cloud.githubusercontent.com/assets/5462788/24320527/ddebfb88-1158-11e7-9495-8f6c1d279925.png)
and after click on button it looks like :(
![image](https://cloud.githubusercontent.com/assets/5462788/24320548/198973dc-1159-11e7-89d1-ee715eef0c57.png)

here is my updated webpackconfig dev file
```
'use strict';
const fs = require('fs');
const path = require('path');
const npmBase = path.join(__dirname, '../../node_modules');
class WebpackBaseConfig {
  constructor() {
    this._config = {};
  }
  get includedPackages() {
    return [].map(pkg => fs.realpathSync(path.join(npmBase, pkg)));
  }
  set config(data) {
    this._config = Object.assign({}, this.defaultSettings, data);
    return this._config;
  }
  get config() {
    return this._config;
  }
  get env() {
    return 'dev';
  }
  get srcPathAbsolute() {
    return path.resolve('./src');
  }
  get testPathAbsolute() {
    return path.resolve('./test');
  }
  get defaultSettings() {
    const cssModulesQuery = {
      modules: true,
      importLoaders: 1,
      localIdentName: '[name]-[local]-[hash:base64:5]'
    };
    return {
      context: this.srcPathAbsolute,
      devtool: 'eval',
      devServer: {
        contentBase: './src/',
        publicPath: '/assets/',
        historyApiFallback: true,
        hot: true,
        inline: true,
        port: 8000
      },
      entry: './index.js',
      module: {
        rules: [
          {
            enforce: 'pre',
            test: /\.js?$/,
            include: this.srcPathAbsolute,
            loader: 'babel-loader',
            query: { presets: ['es2015'] }
          },
          {
            test: /^.((?!cssmodule).)*\.css$/,
            use: [
              "style-loader",
              {
                loader: "css-loader",
                options: {
                  modules: true,
                  sourceMap: true,
                  importLoaders: 1,
                  localIdentName: "[name]--[local]--[hash:base64:5]"
                }
              },
              "postcss-loader" // has separate config, see postcss.config.js nearby
            ]
          },
          //{
          //  test: /^.((?!cssmodule).)*\.css$/,
          //  loaders: [
          //    { loader: 'style-loader'},
          //    { loader: 'css-loader', options: cssModulesQuery},
          //  ]
          //},
          {
            test: /\.(png|jpg|gif|mp4|ogg|svg|woff|woff2)$/,
            loader: 'file-loader'
          },
          {
            test: /^.((?!cssmodule).)*\.(sass|scss)$/,
            loaders: [
              { loader: 'style-loader' },
              { loader: 'css-loader' },
              { loader: 'postcss-loader' },
              { loader: 'sass-loader' }
            ]
          },
          {
            test: /^.((?!cssmodule).)*\.less$/,
            loaders: [
              { loader: 'style-loader' },
              { loader: 'css-loader' },
              { loader: 'postcss-loader' },
              { loader: 'less-loader' }
            ]
          },
        //  {
        //    test: /^.((?!cssmodule).)*\.styl$/,
        //    loaders: [
        //      { loader: 'style-loader' },
        //      { loader: 'css-loader' },
        //      { loader: 'postcss-loader' },
        //      { loader: 'stylus-loader' }
        //    ]
        //  },
          {
            test: /\.json$/,
            loader: 'json-loader'
          },
          {
            test: /\.(js|jsx)$/,
            include: [].concat(this.includedPackages, [this.srcPathAbsolute]),
            loaders: [{ loader: 'babel-loader' }]
          },
          {
            test: /\.cssmodule\.(sass|scss)$/,
            loaders: [
              { loader: 'style-loader' },
              {
                loader: 'css-loader',
                query: cssModulesQuery
              },
              { loader: 'postcss-loader' },
              { loader: 'sass-loader' }
            ]
          },
          {
            test: /\.cssmodule\.css$/,
            loaders: [
              { loader: 'style-loader' },
              {
                loader: 'css-loader',
                query: cssModulesQuery
              },
              { loader: 'postcss-loader' }
            ]
          },
          {
            test: /\.cssmodule\.less$/,
            loaders: [
              { loader: 'style-loader' },
              {
                loader: 'css-loader',
                query: cssModulesQuery
              },
              { loader: 'postcss-loader' },
              { loader: 'less-loader' }
            ]
          },
          {
            test: /\.cssmodule\.styl$/,
            loaders: [
              { loader: 'style-loader' },
              {
                loader: 'css-loader',
                query: cssModulesQuery
              },
              { loader: 'postcss-loader' },
              { loader: 'stylus-loader' }
            ]
          }
        ]
      },
      output: {
        path: path.resolve('./dist/assets'),
        filename: 'app.js',
        publicPath: './assets/'
      },
      plugins: [],
      resolve: {
        alias: {
          actions: `${ this.srcPathAbsolute }/actions/`,
          components: `${ this.srcPathAbsolute }/components/`,
          config: `${ this.srcPathAbsolute }/config/${ this.env }.js`,
          images: `${ this.srcPathAbsolute }/images/`,
          sources: `${ this.srcPathAbsolute }/sources/`,
          stores: `${ this.srcPathAbsolute }/stores/`,
          styles: `${ this.srcPathAbsolute }/styles/`
        },
        extensions: [
          '.js',
          '.jsx'
        ],
        modules: [
          this.srcPathAbsolute,
          'node_modules'
        ]
      }
      //postcss: function () {
      //  return [];
      //}
    };
  }
}
module.exports = WebpackBaseConfig;
```
am working from 24 hours (-6 slepping :( ) just bumping my head on wall any help will be greatly appreciated

**Comment by raza2022** [comment]
I am closing for now as i switched to material-ui instead of react-toolbox to complete my project on time.

**Comment by javivelasco** [comment]
You just needed to add the CSS for the ripple! Sorry I didn't answer before!

**Comment by raza2022** [comment]
@javivelasco I already switched to Material ui because it's urgent project, But Thanks :thumbsup:

**Comment by davidtsai130** [comment]
@javivelasco I'm running into this issue now, what do you mean by "You just needed to add the CSS for the ripple"?

**Comment by javivelasco** [comment]
When the effect shown in the GIF happens it's because the CSS of the ripple is missing. Depending on the config you are using you might need to either import the component in a different way of to add the `RIPPLE` component to your `react-toolbox-themr` configuration. In any case the issue happens for that reason and I guess it's not an issue with the lib itself but with configuration

**Comment by davidtsai130** [comment]
@javivelasco I am importing the Button like so:
`import { Button } from 'react-toolbox/lib/button';` which would mean the theme should already be applied, no? Should I instead do this: `import Button from 'react-toolbox/lib/button/Button';` and add `BUTTON` and `RIPPLE` to the `react-toolbox-themr` configuration?

Here is my webpack config: 
`const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const ExtractTextPlugin = require('extract-text-webpack-plugin')

module.exports = {
	entry: [
		'whatwg-fetch',
		path.resolve(__dirname, 'src/index.js'),
	],
	// entry: './src/index.js',
	output: {
		path: path.resolve(__dirname, 'build'),
		filename: 'bundle.js',
	},
	module: {
		rules: [
			{
				test: /(\.scss|\.css)$/,
				use: ExtractTextPlugin.extract({
					fallback: 'style-loader',
					use: [
						{
							loader: 'css-loader',
							options: {
								modules: true,
								sourceMap: true,
								importLoaders: 1,
								localIdentName: '[name]__[local]___[hash:base64:5]',
							},
						},
						{
							loader: 'postcss-loader!'
						},
					],
					publicPath: '/build',
				})
			},
			{
				test: /\.js$/,
				exclude: /node_modules/,
				use: 'babel-loader'
			}
		]
	},
	devServer: {
		contentBase: path.join(__dirname, 'build'),
		compress: true,
		open: true,
		stats: 'errors-only',
	},
	plugins: [
		new HtmlWebpackPlugin({
			template: './src/index.html',
			title: 'React App Setup',
			minify: {
				collapseWhitespace: true,
			},
			hash: true,
			inject: 'body',
		}),
		new ExtractTextPlugin({
			filename: 'app.css',
			disable: false,
			allChunks: true,
		}),
	]
}
`

and part of my package.json looks like this: 
`
  "license": "MIT",
  "scripts": {
    "dev": "webpack-dev-server",
    "prod": "npm run clean && webpack -p",
    "clean": "rimraf ./build/*",
    "toolbox": "react-toolbox-themr"
  },
  "reactToolbox": {
    "include": [
      "BUTTON",
      "RIPPLE"
    ],
    "customProperties": {
      "animation-duration": "0.3s",
      "color-accent": "var(--palette-pink-a200)",
      "color-accent-dark": "var(--palette-pink-700)",
      "color-primary-contrast": "var(--color-dark-contrast)",
      "color-accent-contrast": "var(--color-dark-contrast)"
    },
    "output": "assets/react-toolbox"
  },
  "dependencies": {
    "babel-preset-es2015": "^6.24.0",
`

**Comment by tiagomapmarques** [comment]
@raza2022 You need to add the PostCSS dependencies listed on the `react-toolbox` package. The only optional one is `postcss-reporter`. Be sure to add them in the **exact** version they are listed, otherwise the CSS will still misbehave.
Since you already have a `postcss-loader` on css files you should be fine with only those changes.

PS: Double-check your PostCSS file. It should look similar to (or exactly like) this:
```
module.exports = {
  plugins: {
    'postcss-import': {
      root: __dirname,
    },
    'postcss-mixins': {},
    'postcss-each': {},
    'postcss-cssnext': {},
  },
};
```
