### ISSUE TITLE
webpack postcss loader issue  -Module build failed: Error: Unexpected "space" found.

### ISSUE THREAD

**Issue by Springbach** [react-toolbox/react-toolbox#1358]
in lib directory of all components in files theme.css
Where is the mistake???, I haven't resolve it yet.
Please help if you can

**Comment by gustavohenke** [comment]
It's very likely that no one will be able to help you without further details.

**Comment by Springbach** [comment]
Thank you Gustavo for reply!

this is me webpack config

var path = require('path');
var webpack = require('webpack');
var autoprefixer = require('autoprefixer');
var precss = require('precss');
var functions = require('postcss-functions');
var ExtractTextPlugin = require("extract-text-webpack-plugin");

var postCssLoader = [
  'css-loader?module',
  '&localIdentName=[name]__[local]___[hash:base64:5]',
  '&disableStructuralMinification',
  '!postcss-loader'
];

var plugins = [
    new webpack.NoErrorsPlugin(),
    new webpack.optimize.DedupePlugin(),
    new ExtractTextPlugin('bundle.css'),
];

if (process.env.NODE_ENV === 'production') {
  plugins = plugins.concat([
    new webpack.optimize.UglifyJsPlugin({
      output: {comments: false},
      test: /bundle\.js?$/
    }),
    new webpack.DefinePlugin({
      'process.env': {NODE_ENV: JSON.stringify('production')}
    })
  ]);

  //postCssLoader.splice(1, 1) // drop human readable names
};

var config  = {
  entry: {
    bundle: path.join(__dirname, 'client/index.js')
  },
  output: {
    path: path.join(__dirname, 'server/data/static/build'),
    publicPath: "/static/build/",
    filename: '[name].js'
  },
  plugins: plugins,
  module: {
    loaders: [
      {test: /\.css/, loader: ExtractTextPlugin.extract('style-loader',
postCssLoader.join(''))},
      {test: /\.(png|gif)$/, loader:
'url-loader?name=[name]@[hash].[ext]&limit=5000'},
      {test: /\.svg$/, loader:
'url-loader?name=[name]@[hash].[ext]&limit=5000!svgo-loader?useConfig=svgo1'},
      {test: /\.(pdf|ico|jpg|eot|otf|woff|ttf|mp4|webm)$/, loader:
'file-loader?name=[name]@[hash].[ext]'},
      {test: /\.json$/, loader: 'json-loader'},
      {
        test: /\.jsx?$/,
        include: path.join(__dirname, 'client'),
        loaders: ['babel']
      }
    ]
  },
  resolve: {
    extensions: ['', '.js', '.jsx', '.css'],
    alias: {
      '#app': path.join(__dirname, 'client'),
      '#c': path.join(__dirname, 'client/components'),
      '#css': path.join(__dirname, 'client/css')
    }
  },
  svgo1: {
    multipass: true,
    plugins: [
      // by default enabled
      {mergePaths: false},
      {convertTransform: false},
      {convertShapeToPath: false},
      {cleanupIDs: false},
      {collapseGroups: false},
      {transformsWithOnePath: false},
      {cleanupNumericValues: false},
      {convertPathData: false},
      {moveGroupAttrsToElems: false},
      // by default disabled
      {removeTitle: true},
      {removeDesc: true}
    ]
  },
  postcss: function() {
    return [autoprefixer, precss({
      variables: {
        variables: require('./client/css/vars')
      }
    }), functions({
      functions: require('./client/css/funcs')
    })]
  }
};

module.exports = config;
/////////////////////////////////////////////////////////////////////

--in console
$ NODE_ENV=production webpack

this is compilation errors in all lib components:

ERROR in
./~/css-loader?module&localIdentName=[name]__[local]___[hash:base64:5]&disableStructuralMinification!./~/postcss-loader!./~/react-toolbox/lib/tooltip/theme.css
    Module build failed: Error: Unexpected "space" found.
        at new error (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss-selector-parser/dist/processor.js:29:23
)
        at Parser.error (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss-selector-parser/dist/parser.js:234:15
)
        at Parser.pseudo (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss-selector-parser/dist/parser.js:362:18
)
        at Parser.parse (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss-selector-parser/dist/parser.js:551:22
)
        at Parser.loop (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss-selector-parser/dist/parser.js:519:18
)
        at new Parser (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss-selector-parser/dist/parser.js:104:21
)
        at Processor.process (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss-selector-parser/dist/processor.js:26:21
)
        at getParsed (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss-minify-selectors/dist/index.js:32:59
)
        at optimise (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss-minify-selectors/dist/index.js:139:21
)
        at /home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss/lib/container.js:241:28
        at /home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss/lib/container.js:148:26
        at Root.each (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss/lib/container.js:114:22
)
        at Root.walk (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss/lib/container.js:147:21
)
        at Root.walkRules (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss/lib/container.js:239:25
)
        at /home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss-minify-selectors/dist/index.js:165:20
        at LazyResult.run (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss/lib/lazy-result.js:274:20
)
        at LazyResult.asyncTick (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss/lib/lazy-result.js:189:32
)
        at LazyResult.asyncTick (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss/lib/lazy-result.js:201:22
)
        at LazyResult.asyncTick (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss/lib/lazy-result.js:201:22
)
        at LazyResult.asyncTick (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss/lib/lazy-result.js:201:22
)
        at LazyResult.asyncTick (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss/lib/lazy-result.js:201:22
)
        at LazyResult.asyncTick (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss/lib/lazy-result.js:201:22
)
        at LazyResult.asyncTick (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss/lib/lazy-result.js:201:22
)
        at LazyResult.asyncTick (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss/lib/lazy-result.js:201:22
)
        at LazyResult.asyncTick (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss/lib/lazy-result.js:201:22
)
        at /home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/postcss/lib/lazy-result.js:194:27
        at tryCatch (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/es6-promise/dist/es6-promise.js:410:12
)
        at invokeCallback (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/es6-promise/dist/es6-promise.js:425:13
)
        at publish (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/es6-promise/dist/es6-promise.js:393:7
)
        at flush (/home/george/myprogs/src/
github.com/springbach/leon_desktop/node_modules/es6-promise/dist/es6-promise.js:121:5
)



Thanks for help Gustavo!

George


2017-03-26 5:07 GMT+07:00 Gustavo Henke <notifications@github.com>:

**Comment by miguel-orange** [comment]
I also had the same issue and was able to fix it by adding the following to webpack 2 loader options.
```javascript
new webpack.LoaderOptionsPlugin({
    options: {
        postcss: () => {
            return [
                /* eslint-disable global-require */
                require('postcss-cssnext'),
                // ({
                //     features: {
                //         customProperties: {
                //             variables: reactToolboxVariables,
                //         },
                //     },
                // }),
                require('postcss-modules-values'),
                /* eslint-enable global-require */
            ];
        }
    }
})
```

**Comment by Springbach** [comment]
Yes, It works. Thanks!

2017-04-06 12:48 GMT+07:00 Miguel Amaro <notifications@github.com>:

**Comment by codeaimh** [comment]
Hello guys I have the same problem :( Can somebody please help me to fix it? I tried to add what Miguel-orange said, but I don't know where to put it :(

**Comment by miguel-orange** [comment]
@codeaimh,
You'll want to add that in webpack.config.js 's plugins array. But more importantly I was starting with this [migration guide](https://github.com/react-toolbox/react-toolbox/wiki/Migrating-from-version-1.3-to-2.0). I hope it's still relevant.
