### ISSUE TITLE
Error: composition is only allowed when selector is single :local

### ISSUE THREAD

**Issue by eldyvoon** [react-toolbox/react-toolbox#1359]
ERROR in ./~/css-loader!./~/postcss-loader!./~/react-toolbox/lib/button/theme.css
Module build failed: Error: composition is only allowed when selector is single :local class name not in ".raised", ".raised" is weird

If you need my webpack.config.js it's here : http://pastebin.com/33C1quLS

**Comment by gvillenave** [comment]
I'm seeing the same issue when trying to import { Layout, NavDrawer, Panel } from 'react-toolbox/lib/layout'

**Comment by sanfilippopablo** [comment]
I'm having this issue while using react-toolbox through react-toolbox-themr.

**Comment by sanfilippopablo** [comment]
@eldyvoon In your webpack.config.js you're not enabling CSS modules  for css-loader. Check here: https://github.com/react-toolbox/react-toolbox#setting-up-postcsscssnext-in-webpack
