### ISSUE TITLE
Remove "List" prefix

### ISSUE THREAD

**Issue by adaojunior** [react-toolbox/react-toolbox#136]
Since ListSubHeader, ListItem, ListCheckbox,Divider are List's children I think we could remove "List" prefix.
```js
import { List, Item, SubHeader, Divider, Checkbox } from 'react-toobox/list';
```

It's a personal opinion, but if we take a look to html (I know JSX and Html are diferrent) we gonna see stuff like:

```html
<datalist id="languages">
  <option value="PHP" />
  <option value="C++" />
  <option value="Java" />
</datalist>

<fieldset>
    <legend>Personalia:</legend>
</fieldset>

<video width="320" height="240" controls>
  <source src="movie.mp4" type="video/mp4">
</video>
```

I think it makes more sense to not prefix

**Comment by javivelasco** [comment]
I understand what you mean but imagine the case you need both a `Menu` and a `List`. Both components have `Item`. Don't you think it's more semantic to have the prefix in that particular case? We are open to change naming conventions and we are going to do it indeed.

It's a good point to discuss

**Comment by EnzoMartin** [comment]
If you need both though, you'd probably end up doing `{ Item as MenuItem } from 'list';`

**Comment by javivelasco** [comment]
Yeah, but the pattern is actually to prefix a subcomponent, isn't it??

**Comment by adaojunior** [comment]
Well, if we look how React Native does it, it's gonna be like:
```jsx

let { TabBarIOS} = React;

<TabBarIOS>
    <TabBarIOS.Item title="React Native" selected={true}>
         /// something here
    </TabBarIOS.Item>
</TabBarIOS>
```

**Comment by javivelasco** [comment]
Ok, I would like to get more feedback about this. @nathanmarks proposed to change naming conventions to be closer to standards. What do you think about removing prefixes for nested components?

**Comment by nathanmarks** [comment]
@adaojunior @javivelasco 

In react native, from the module itself they are actually exporting `TabBarItemIOS`. See here: https://github.com/facebook/react-native/blob/dd09c88571f5397346903e0e8c73224cbf40c862/Libraries/Components/TabBarIOS/TabBarItemIOS.ios.js#L141

The folder structure is: `react-native/Libraries/Components/TabBarIOS/TabBarItemIOS.ios.js`

If you look in the `TabBarIOS` component, they have the `TabBarItemIOS` component set as a static property:

```
var TabBarIOS = React.createClass({
  statics: {
    Item: TabBarItemIOS,
  },
...
```

This is why you can access the `TabBarItemIOS` via `TabBarIOS.Item`.

The general idea is to find a balance with 'namespacing' child components and keeping component names short and easy. 

And most importantly, like in React Native, the general accepted convention is to export a module matching the file name of the component.

**Comment by javivelasco** [comment]
Great, I'm closing here then. As soon as you have cards ready we can start moving all the components in order to release 0.14. I'm going to try moving the `classNames` with [https://github.com/JedWatson/classnames](https://github.com/JedWatson/classnames).

**Comment by nathanmarks** [comment]
@javivelasco I'm going to finish the cards this weekend, had a busy week but finally have some time! :)

**Comment by javivelasco** [comment]
No problem, take your time. I've just opened a new `classnames` branch to move the components to classnames package. It should be easy a fast!
