### ISSUE TITLE
Unexpected token : running node app.js

### ISSUE THREAD

**Issue by eldyvoon** [react-toolbox/react-toolbox#1360]
```
/Users/James/Documents/app/node_modules/react-toolbox/lib/ripple/theme.css:1
(function (exports, require, module, __filename, __dirname) { :root {
                                                              ^
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/James/Documents/app/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/James/Documents/writers/node_modules/react-toolbox/lib/ripple/index.js:13:14)
```

I don't know why I got above error msg when I try to run my express server. My webpack.config.js is here http://pastebin.com/raw/k5RyXuZP

**Comment by rubenmoya** [comment]
I think it's because you need the cssnext plugin for postcss. Check it here: https://github.com/MoOx/postcss-cssnext

**Comment by i3ringit** [comment]
I believe I'm having the same issue.

I use postcss-cssnext, so that's not the problem.

In my case (I believe it's the same with @eldyvoon), webpack compiles just fine, the error happens when the server is started.

**Comment by markchkhotua** [comment]
I have the same problem. 
@i3ringit , @eldyvoon did you find the solution of this issue?
Help, please

**Comment by i3ringit** [comment]
@markchkhotua I was not able to solve this, I chose to move on and implement the material components I needed myself. I probably won't try react-toolbox again, I'm afraid. Good luck.

**Comment by eldyvoon** [comment]
@markchkhotua I moved on too. :(

**Comment by danieljodeci** [comment]
Same issue :/ anybody ever figure this out? 

my current webpack config:
```javascript
import path from 'path';
import webpack from 'webpack';
import reporter from 'postcss-reporter';
import cssNext from 'postcss-cssnext';

const rootFolder = path.resolve(__dirname, '..');
const config = {
  context: rootFolder,

  entry: {
    main: './src/client'
  },

  output: {
    path: path.resolve(rootFolder, 'static/assets'),
    publicPath: '/assets/',
    filename: '[name].[hash].js'
  },

  module: {
    rules: [
      {
        enforce: 'pre',
        test: /\.js?$/,
        exclude: /node_modules/,
        use: 'eslint-loader'
      },
      {
        test: /\.js?$/,
        exclude: /node_modules/,
        loader: 'babel-loader'
      },
      {
        test: /\.(png|jpg|jpeg|gif|svg|woff|woff2)$/,
        use: 'url-loader?limit=10000'
      },
      {
        test: /\.(eot|ttf|wav|mp3)$/,
        use: 'file-loader'
      },
      {
        test: /\.css$/,
        use: [
          "style-loader",
          {
            loader: "css-loader",
            options: {
              modules: true,
              sourceMap: true,
              importLoaders: 1,
              localIdentName: "[name]--[local]--[hash:base64:8]"
            }
          },
          "postcss-loader" // has separate config, see postcss.config.js nearby
        ]
      },
    ]
  },

  plugins: [
    new webpack.optimize.OccurrenceOrderPlugin(true),
    new webpack.NoEmitOnErrorsPlugin(),
    // new webpack.NamedModulesPlugin(),
    new webpack.LoaderOptionsPlugin({
      options: {
        context: __dirname,
        postcss: [
          cssNext({
            browsers: ['last 1 version']
          }),
          reporter
        ],
      }
    })
  ],

  resolve: {
    extensions: ['*', '.js', '.css', '.html', '.scss', '.json'],
    modules: ['src', 'node_modules'],
    alias: {
      app: path.resolve(rootFolder, 'src/app')
    }
  }
};

export default config;
```

**Comment by javivelasco** [comment]
Remember you can extract the css using react-toolbox-themr and skip this whole config!

**Comment by Nemsae** [comment]
I have this same exact error, however only after hours of building with Toolbox and successfully compiling webpack. Now all of a sudden I get this error even though there were absolutely no changes made to my webpack config.

If someone can enlighten me as to which direction to debug. I have diffed my files with a working version of react-toolbox app but there is literally nothing to look at.

**Comment by unleashit** [comment]
@Nemsae same here! Everything was working perfectly, made no changes to wepack then all of a sudden boom, Unexpected Token : 

In my case, the components are loading fine (although at one point they weren't). Now, it's just the error in the console which is still unnerving. I've spent at the last 5 hours reverting commits, setting up a clean sandbox, etc. to no avail. I'm pretty sure the problem comes down to the project being isomorphic, but it's super weird that even after reverting to a commit where it was previously working with no errors, now I can't get rid of them no matter what I do.

It's a shame, because from a design and many other angles, this project is awesome. There are a lot of people having this issue. Many of them seem to just not be setting Webpack to properly intercept the RT imports and add CSS modules, etc. That's not my issue, nor it seems a good portion of other peoples'. I wish I could use RT, but I'm also going to have to give up at this point as either I'm something in my setup won't play nice with it and/or there's a pretty major bug that the maintainers don't care much about.

**Comment by tobiasandersen** [comment]
What version of postcss-loader have you installed?

**Comment by Nemsae** [comment]
@unleashit Unfortunate to hear that. I was able to finish up the project by using the react-toolbox-themr. It was a bit tricky to implement the theme provider but beyond that it worked. But as you mentioned I am moving on. Just going to work straight with material.

**Comment by unleashit** [comment]
@tobiasandersen  the latest stable, 2.0.6

@Nemsae I tried that awhile back and it was working in a different project, but it's more manual work than I'd like. Plus I prefer it with CSS modules as I'm already using them anyway.

**Comment by tobiasandersen** [comment]
@unleashit I believe there're still [problems with that version](https://github.com/react-toolbox/react-toolbox/issues/1461), try downgrading to v1.3.3.

**Comment by unleashit** [comment]
Just tried downgrading, but it didn't solve my problems. Here's my webpack config in case it helps.

```
       // React toolbox needs CSS modules
        ifElse(isClient || isServer)(
          mergeDeep(  // helper method that merges this piece into the overall config
            {
              test: /\.css$/,
              include: path.join(appRootDir.get(), 'node_modules', 'react-toolbox'),
            },

            ifDevClient({      // if development mode and client side
              use: [
                'style-loader',
                {
                  loader: 'css-loader',
                  options: {
                    modules: true,
                    sourceMap: true,
                    importLoaders: 1,
                    localIdentName,  // [name]_[local]_[hash:base64:5]
                  },
                },
                'postcss-loader',
              ],
            }),

           // removed production configs for the example

            ifNode({    // when run on the server
              use: [
                `css-loader/locals?modules=1&sourceMap&importLoaders=1&localIdentName=${localIdentName}`,   // using css-loader/locals here, but have tried with and without
                'postcss-loader',
              ],
            }),
          ),
        ),
```

I'm working with the React Universally boilerplate which has a more complex server side workflow than I'm used to. I can't say that I fully understand everything it's doing yet, although I'm not having issues anywhere else. I'm processing css modules + sass with an almost identical WP config outside of RT without issue. The weird thing is everything from React Toolbox renders just fine. CSS module transformations are there. and I don't have the formatting problems as issue #1461. But nonetheless, the error appears in the console as soon as I add an import from RT.

**Comment by jonbronson** [comment]
I'm encountering a very similar issue:

`/Users/jon/workspace/prototype/node_modules/react-toolbox/lib/avatar/theme.css:1
(function (exports, require, module, __filename, __dirname) { :root {
                                                              ^
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jon/workspace/prototype/node_modules/react-toolbox/lib/avatar/index.js:16:14)
    at Module._compile (module.js:570:32)`

I modeled my webpack config after the react-toolbox-example. The first Button I added renders perfectly. But when I added <Card> I get this error during build. Has anyone figured out a solution?

**Comment by unleashit** [comment]
In my case, the issue turned out due to how the React boiler plate I was using (React Universally) is optimized. I actually had the correct Webpack setup the whole time, but needed to whitelist React Toolbox using the boilerplate's API to let Webpack process it for the server bundle. It's now working fine for me on a server rendered app. 

I'd suggest trying to make a specific loader for css and React Toolbox only with include (and make sure to exclude it in any other css rules if its in the path).

**Comment by fchengpc** [comment]
@unleashit i think im facing the same issue as everybody else here. How did you get it working on your SSR app? do you mind share the sample setup code?
I'm trying to do this with `next.js`

**Comment by unleashit** [comment]
Yeah I eventually did although in my case it turned out that my starter repo has a whitelist only policy for csp and nunning node scripts (the latter was the surprise). This was related to React Universally but my guess is next.js might have something similar?
