### ISSUE TITLE
Using this with sass-loader

### ISSUE THREAD

**Issue by sampeka** [react-toolbox/react-toolbox#1365]
I'm trying to integrate react-toolbox with our frontend for the first time, but we're having some issues with the build process for the stylesheets.

Experiencing the same issue as in: https://github.com/react-toolbox/react-toolbox/issues/1186 but the solution there didn't solve it for me. Most of our styles are written in sass, so we need to keep sass loader. Unfortunately I don't seem to be able to get this to work because of the traceback below:

```
ERROR in ./~/css-loader!./~/postcss-loader?{"parser":{}}!./~/sass-loader/lib/loader.js!./~/react-toolbox/lib/avatar/theme.css
Module build failed:
    & *,
   ^
      Illegal nesting: Only properties may be nested beneath properties.
      in /Users/sampeka/dev/plum/app-web/node_modules/react-toolbox/lib/avatar/theme.css (line 367, column 5)
 @ ./~/react-toolbox/lib/avatar/theme.css 4:14-151 13:2-17:4 14:20-157
 @ ./~/react-toolbox/lib/avatar/index.js
 @ ./~/react-toolbox/lib/chip/index.js
 @ ./~/react-toolbox/lib/autocomplete/index.js
.....
```

Here's some excerpts from my webpack config:

```
const scss = require('postcss-scss');

const postcssPlugins = [
  require('postcss-cssnext')(),
  require('postcss-modules-values')
];

// ...
module: {
  rules: [
      test: /\.(css|scss|sass)$/,
      loader: [
        'style-loader',
        'css-loader',
        { loader: 'postcss-loader',  options: { plugins: () => [...postcssPlugins], parser: scss } },
        'sass-loader'
      ],
      include: [__dirname]
    }
  ]
}
// ...
```

Is it possible to use react-toolbox whilst keeping `sass-loader`? If I'm understanding the issue correctly, it seems to be that `sass-loader` is throwing because the styles in `react-toolbox` are not valid sass but I'm not sure if there is a way round it. I tried creating a different loader for `sass` and `css`, but the css ended up not being included for some reason (despite it building). Thanks a lot for the help :)

**Comment by sampeka** [comment]
I think this is potentially an issue with `style-loader`, with `ExtractTextPlugin` enabled this works. Will close after I confirm it.

**Comment by dhaundy** [comment]
Hi @sampeka, could you please share your final config? I could not get sass-loader to work. I removed it, and now my bundled css is missing @imported files. Thanks!

**Comment by sampeka** [comment]
Sure @dhaundy, there's a lot of crud in my config so I'll just show the relevant bits:

```
const postcssPlugins = [
  require('postcss-cssnext')(),
  require('postcss-modules-values')
];

const scssLoader = [
  { loader: 'style-loader' },
  { loader: 'css-loader' },
  { loader: 'sass-loader' }
];

const postcssLoader = [
  { loader: 'style-loader' },
  { loader: 'css-loader', options: { modules: true } },
  { loader: 'postcss-loader', options: { plugins: () => [...postcssPlugins] } }
];

module.exports = {
  resolve: {
    extensions: ['.js', '.jsx', '.css', '.scss', '.sass'],
    modules: [
      path.resolve(__dirname, 'node_modules'),
      path.resolve(__dirname, './src')
    ]
  },
  module: {
    rules: [
      {
        test: /\.(scss|sass)$/,
        loader: scssLoader,
        include: [__dirname]
      },
      { test: /\.css$/,
        loader: postcssLoader,
        include: [__dirname]
      }
    ]
  }
};
```

**Comment by vikramjit575** [comment]
@sampeka thanks a lot!my issue is resolved finally

**Comment by vikramjit575** [comment]
This is also working for me



`var path = require('path');
var config = {
   entry: './main.js',
	
   output: {
    path: path.join(__dirname, "dist/js"),
    filename: "index.js"
},
	
	
   devServer: {
      inline: true,
      port: 9191
   },
	
   module: {
      loaders: [
         {
            test: /\.jsx?$/,
            exclude: /node_modules/,
            loader: 'babel-loader',
				
            query: {
               presets: ['es2015', 'react']
            }
         },
		  {
                 test: /(\.css|\.scss)$/,
                loader: 'style-loader!css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!sass-loader?sourceMap'
            }
      ]
	  
   }
}`
