### ISSUE TITLE
Radio Button is broken with RHL

### ISSUE THREAD

**Issue by olegstepura** [react-toolbox/react-toolbox#1368]
I'm experiencing an issue with `RadioGroup` and `react-hot-loader` together.

![ezgif-1-4805f840af](https://cloud.githubusercontent.com/assets/534510/24401008/e4e69d24-13b2-11e7-849b-c6062cb11e2b.gif)

isComponentOfType is overwritten in my case. If I remove RHL, it works.

this is caused by the fact, that `isComponentOfType` in `RadioGroup` is loaded from `utils/react` instead of `utils/is-component-of-type` and is not overwritable.

**Comment by holzfelix** [comment]
Hi, 
I added the actual beta.8 from repo to my app ... but the problem is stell actual ...

**Comment by olegstepura** [comment]
I updated to `beta.8` and for me it looks ok with `RHL 3`

**Comment by holzfelix** [comment]
you are able to check the radios?

**Comment by holzfelix** [comment]
code cools like this: 

`import { RadioGroup, RadioButton } from 'react-toolbox/lib/radio';`

```
 <RadioGroup name='steptype' value={this.state.value} onChange={this.handleChange}>
     <RadioButton label={I18n.t('processes.new.processStepTypeDuty')} value='duty'/>
      <RadioButton label={I18n.t('processes.new.processStepTypeVariable')} value='variable'/>
      <RadioButton label={I18n.t('processes.new.processStepTypeOptioanal')} value='optional'/>
 </RadioGroup>
```

**Comment by acthp** [comment]
Having this issue with beta.12 and rhl 4.0.0. Is there any solution?
