### ISSUE TITLE
Add FloatingLabel option to Datepicker

### ISSUE THREAD

**Issue by jgoux** [react-toolbox/react-toolbox#137]
Hello,
as the DatePicker element is composed of a TextField, it would make sense to add the FloatingLabel option to harmonize the UI. :+1:

**Comment by javivelasco** [comment]
Oh! I see what you mean. When the `DatePicker` is filled up there is no label to show. Is that right?
I see this as a great improvement and easy to implement.
Thanks!

**Comment by jgoux** [comment]
Yes this is exactly what I meant. :)

**Comment by javivelasco** [comment]
Great, we can plan it as an enhancenment!

**Comment by javivelasco** [comment]
It will be available in `0.12.14`
