### ISSUE TITLE
Input type file not matching material ui 

### ISSUE THREAD

**Issue by exexzian** [react-toolbox/react-toolbox#1370]
input type file shows plain HTML type input Choose File
[input type file](http://i66.tinypic.com/w86xj6.png)

Can we have bit of customization to make it look more clean and close to material ui.

**Comment by kozakluke** [comment]
Link doesn't work

**Comment by olegstepura** [comment]
Link has this image

![w86xj6](https://cloud.githubusercontent.com/assets/534510/24430827/e26f35b8-1418-11e7-8157-e81d0159db92.jpg)

**Comment by tengis** [comment]
Hi Guys, 

I think there are no clear guideline about input(type=file) would look like in [material design.](https://material.io/guidelines/components/text-fields.html) 

I guess [this is](https://codepen.io/alexandergaziev/pen/JdVQQm) the closest possible option for it.

Cheers!

**Comment by sanfilippopablo** [comment]
react-toolbox already has this, although it is an undocumented feature (should be documented because it's great).
It's called `BrowseButton` and you can use it like this:
```es6
import React from "react";
import { BrowseButton } from "react-toolbox/lib/button";

class Upload extends React.Component {
  handleChange = e => {
    console.log(e.target.files[0]);
  };
  render() {
    return (
      <div>
        <BrowseButton
          icon="file_upload"
          label="Upload"
          onChange={this.handleChange}
        />
      </div>
    );
  }
}
```

It looks like a regular `Button` and accept most —I think— of the props `Button` accepts.

**Comment by exexzian** [comment]
@sanfilippopablo thanks for finding out _the_ *undocumented feature*, that's working fine, seems I will have to decide whether to use _more expressive traditional input file ui_ or the `BrowseButton``

**Comment by nidhigadhavi** [comment]
i want to change button css with icon here.  plz guide.

**Comment by nathandunn** [comment]
+1 to document!   That is a nice feature.
