### ISSUE TITLE
Cursor too big in Table input

### ISSUE THREAD

**Issue by pmirandaarias** [react-toolbox/react-toolbox#1373]
The cursor is too big in the input of Table:
![rt](https://cloud.githubusercontent.com/assets/20463330/24410786/56758b70-13aa-11e7-8577-5d9f38552efb.PNG)

.theme__table__vJMNl tr {
    height: 48px;
    line-height: 48px;
}

**Comment by rubenmoya** [comment]
Unable to reproduce in playground
