### ISSUE TITLE
Esc key listener leakage in Overlay

### ISSUE THREAD

**Issue by JanuszP** [react-toolbox/react-toolbox#1377]
Esc key event listener is never removed, See:

https://github.com/react-toolbox/react-toolbox/blob/dev/components/overlay/Overlay.js#L27 

bind(this) creates new function that is never removed, handleEscKey doesn't need to use bind(this) as it's arrow function, 

Also in here:

https://github.com/react-toolbox/react-toolbox/blob/dev/components/overlay/Overlay.js#L48

Issue issue is simmilar to line 27 but also has another bug by not removing event listner when dialog state changes to inactive.

Pull request with fixes is here:
https://github.com/react-toolbox/react-toolbox/pull/1376

**Comment by codrin-iftimie** [comment]
Same problem fixed with https://github.com/react-toolbox/react-toolbox/pull/1319

**Comment by JanuszP** [comment]
#1319 doesn't handle deregistration of event listener when dialog switches into inactive state.

**Comment by rubenmoya** [comment]
Fixed in https://github.com/react-toolbox/react-toolbox/pull/1376
