### ISSUE TITLE
tabs not switching on click event 

### ISSUE THREAD

**Issue by vikramjit575** [react-toolbox/react-toolbox#1381]
tabs not switching on click event but index is being maintained on click

**Comment by sanfilippopablo** [comment]
If you share some code maybe I can help you. Are you setting `setIndex`?

**Comment by josemigg** [comment]
did you set up onChange event?

I think you have to do something like this

`class Tabs extends React.Component {
  state = {
    index: 0,
  };
  
  handleTabChange = (index) => {
    this.setState({ index, });
  };
  
  render() {
    return (
      <RTTabs {...this.props}
              index={this.state.index}
              theme={theme}
              onChange={this.handleTabChange}
              />
    );
  }
}`

**Comment by vikramjit575** [comment]
here is my code
import React from 'react';
import Header from "./Header.jsx";
import Featured from "./Featured.jsx";
import Archives from "./Archives.jsx";
import {Tab, Tabs} from 'react-toolbox';
import AppBar from 'react-toolbox/lib/app_bar';
import Navigation from 'react-toolbox/lib/navigation';
import {IconMenu, MenuItem, MenuDivider } from 'react-toolbox/lib/menu';
import Footer from "./Footer.jsx";
import { Link } from "react-router";
import { Checkbox, IconButton } from 'react-toolbox';
import { Layout, NavDrawer, Panel, Sidebar } from 'react-toolbox';

class LayoutTest extends React.Component {
constructor()
{
super();

		this.statetab = {
    index: 1,
    fixedIndex: 1,
    inverseIndex: 0
  };

	


			}

	
	 handleTabChange(index){
    this.setState({index});
  };

  handleFixedTabChange(index){
  alert(index)
    this.setState({fixedIndex: index});
  };

  handleInverseTabChange(index){
    this.setState({inverseIndex: index});
  };

  handleActive(){
    console.log('Special one activated');
  };

	
   render() {

const Tabb = () =>
(
 <section>
        <Tabs {...this.props} index={this.statetab.index} onChange={this.handleTabChange.bind(this)}>
          <Tab label='Primary'><small>Primary content</small></Tab>
          <Tab label='Secondary' onActive={this.handleActive.bind(this)}><small>Secondary content</small></Tab>
          <Tab label='Third' disabled><small>Disabled content</small></Tab>
          <Tab label='Fourth' hidden><small>Fourth content hidden</small></Tab>
          <Tab label='Fifth'><small>Fifth content</small></Tab>
        </Tabs>
        <h5>Fixed Tabs</h5>
        <Tabs index={this.statetab.fixedIndex} onChange={this.handleFixedTabChange.bind(this)} fixed>
          <Tab label='First'><small>First Content</small></Tab>
          <Tab label='Second'><small>Second Content</small></Tab>
          <Tab label='Third'><small>Third Content</small></Tab>
        </Tabs>
        <h5>Inverse Tabs</h5>
        <Tabs index={this.statetab.inverseIndex} onChange={this.handleInverseTabChange.bind(this)} inverse>
          <Tab label='First'><small>First Content</small></Tab>
          <Tab label='Second'><small>Second Content</small></Tab>
          <Tab label='Third'><small>Third Content</small></Tab>
          <Tab label='Disabled' disabled><small>Disabled Content</small></Tab>
        </Tabs>
      </section>

);
	   
	   return (  
	
		 
    
  </AppBar>
		 <div id="container">

	
	<div>
	<Tabb/>
	
	</div>
		 
           </div>
            </body>
         
      );
   }
}

export default LayoutTest;

**Comment by sanfilippopablo** [comment]
There seems to be a couple of typos (`this.statetab`, `<Tabb/>`) but your code isn't exactly readable. Please post it again inside the markdown code block, like this:
<pre>
```es6
your code
```
</pre>
