### ISSUE TITLE
Add delay to tooltip

### ISSUE THREAD

**Issue by elliotatRetireup** [react-toolbox/react-toolbox#139]
I think that adding a delay prop to the tooltip could allow people to build it into apps without worrying about spamming tooltips.

**Comment by javivelasco** [comment]
Makes sense!

**Comment by soyjavi** [comment]
Totally agree... we will implement it in the next release.

**Comment by soyjavi** [comment]
Fixed https://github.com/react-toolbox/react-toolbox/commit/ef6bd0899d43d3a76bee96e6c25b23bdf55ff459
