### ISSUE TITLE
Color Theme

### ISSUE THREAD

**Issue by tobias-f** [react-toolbox/react-toolbox#1392]
I am struggeling a bit with the theming in react-toolbox (2.0.0-beta.7):

I want to change e.g. the primary color. According to the docs, I can provide a _theme.sass and include it with the webpack sass-loader. So far so good. But: how do I set the primary color there? Although the documentation says that the lib/colors file is a SASS file, it is in reality a CSS file. So how do I change e.g. the primary color? Could someone give me a short example?

Thanks a lot....

**Comment by darklilium** [comment]
I did this on my main file when i want to change the color on an APPBAR.

1.- `import theme from '../css/RedAppBar.scss';`

2 .- ```
const AppBarTest = () => (
  <AppBar title='Hello' theme={theme}></AppBar>
);
```

3.- In the RedAppBar.scss
`.appBar { background-color: #da291c; }`

**Comment by tobias-f** [comment]
Hi...

Nope, not what I was going after :-)

I don't want to change the color of a specific component, but I want to change the primaryColor variable globally, so that all components that use this variable adapt accordingly..

**Comment by MorrisGallego** [comment]
React Toolbox v2 doesn't uses SCSS anymore. The docs in the web are for previous versions (branch 1.x).
You can find the docs for v2 in https://github.com/react-toolbox/react-toolbox#theming-configuration-variables

**Comment by darklilium** [comment]
But still having the issue. Im using webpack 2 too.

**Comment by hansena** [comment]
check out the "Settings configuration variables in JavaScript" in the read me...   it explains exactly what you are trying to do

**Comment by alexeyMohnatkin** [comment]
@hansena it's not clear how to redefine color variables globally.
`@value color-primary: var(--palette-deep-purple-500);`
How this will redefine `--color-primary`?
Also I wanted to look how it's realized in docs, but it's not working  (#1151).

**Comment by hansena** [comment]
Comment

**Comment by mogadanez** [comment]
probably need to maintain collection of such variables sets like https://bootswatch.com/
