### ISSUE TITLE
Cannot import date_picker without error

### ISSUE THREAD

**Issue by elliotatRetireup** [react-toolbox/react-toolbox#140]
Running line:
import DatePicker from 'react-toolbox/lib/date_picker';

I get an error only with importing the date picker: 
ERROR in ./~/react-toolbox/lib/utils/testing.js
Module not found: Error: Cannot resolve module 'react-addons-test-utils' in /Users/elliot/react_working/node_modules/react-toolbox/lib/utils

@EnzoMartin  Also confirmed this is an issue.

**Comment by drhayes** [comment]
I get this when I import Table as well.

**Comment by soyjavi** [comment]
did you upgraded your `npm packages`?
