### ISSUE TITLE
CSS is not rendered correctly

### ISSUE THREAD

**Issue by holzfelix** [react-toolbox/react-toolbox#1400]
I've just run the install
and copied the code from this example:

http://react-toolbox.com/#/components/input

result is this: 

![ashampoo_snap_2017 04 06_13h27m21s_003_](https://cloud.githubusercontent.com/assets/6866699/24752393/f64b647e-1acd-11e7-8655-80e6e51c7969.png)

**Comment by drager** [comment]
@holzfelix: Have you followed the steps described [here](http://react-toolbox.com/#/install)?

**Comment by holzfelix** [comment]
i've done this: npm install --save react-toolbox

**Comment by drager** [comment]
Have you read the [prerequisites](http://react-toolbox.com/#/install#prerequisites)?

**Comment by holzfelix** [comment]
Yes just now read. But when I Install webpack my app isn't compiled anymore ... is there an alternative to webpack?

**Comment by drager** [comment]
Yeah, there's Browserify as well. Have you checked out https://github.com/facebookincubator/create-react-app though?

**Comment by holzfelix** [comment]
whats the better choice

**Comment by drager** [comment]
What do you mean? Maybe you could check out `create-react-app` which is a great choice.

**Comment by holzfelix** [comment]
thats what I use at the moment. Don't understand why the css is not rendered correctly ... no errors notheing ...

**Comment by drager** [comment]
You could checkout this [example](https://github.com/react-toolbox/react-toolbox-example). And go from there.

**Comment by tobiasandersen** [comment]
Have you tried this: https://github.com/react-toolbox/react-toolbox#usage-in-create-react-app-projects?
