### ISSUE TITLE
Card theme color can not be overwritten

### ISSUE THREAD

**Issue by yueduz** [react-toolbox/react-toolbox#1404]
import React from 'react';
import style from './theme.scss'
import {Card} from 'react-toolbox/lib/card';

const Banner = () => (
  <Card theme={style}>
    <p>哥只是个传说别相信哥</p>
    <p>---好辛苦</p>
    <p>开发中,不能购买。不搞活动，没有优惠。我们是正经的网络商贩。让你用更短的时间完成购物。</p>
  </Card>
);
export default Banner;

//--------------------------- './theme.scss'
.card {
    background-color: #800080;
    padding-top: 70px;
}

//He always returns to the default color

**Comment by yueduz** [comment]
![2017-04-09 01-03-21](https://cloud.githubusercontent.com/assets/1448159/24830853/6748b218-1c53-11e7-851b-fe7e414e4093.png)

**Comment by tobiasandersen** [comment]
Give your css rule higher specificity (e.g. by typing `div.card` instead).
