### ISSUE TITLE
changing some styles

### ISSUE THREAD

**Issue by holzfelix** [react-toolbox/react-toolbox#1408]
Hi together,

 I want to change some of the default styles like padding and so on. 

what would be the best way to do this?

**Comment by holzfelix** [comment]
Noone with Idea?

**Comment by holzfelix** [comment]
poor ... any help would be amazing

**Comment by rubenmoya** [comment]
You just have to pass a `theme` prop with the custom styles to the component:

```
import theme from './myCustomStyles.css';

<Input theme={theme} />
```
