### ISSUE TITLE
Date Picker Month/Year Prop to select the 'level' of the picker.

### ISSUE THREAD

**Issue by elliotatRetireup** [react-toolbox/react-toolbox#141]
Would like to be able to designate the 'level' of the date picker.

That is, I would like to be able to control whether the date picker opens to the month view or the year view. 

Use case is for entering credit card expiration. Its likely a person's credit card expiration date is not in the current month, so it makes sense to let them select the year/month first in most cases.

**Comment by soyjavi** [comment]
Hi @elliotatRetireup our approach it is build the same Material Design experience. Take a look to official documentation https://www.google.com/design/spec/components/pickers.html#pickers-date-pickers

Maybe in future releases we will extend these *basic* components.
best

**Comment by javivelasco** [comment]
I think we should speak about it. @elliotatRetireup it's just about extracting the current view to a property? Or are you thinking about something else? I guess to select just the year, maybe the component is just not appropriated but in makes sense to choose which view should be displayed first. Two options here:

- Allow a default `defaultView` property to decide where should be the picker opened.
- Extract `view` which gives responsibility to the consumer about where to store the view state.

Feedback?

**Comment by javivelasco** [comment]
Another option would to to allow **locking** the datepicker via a prop. In that scenario you should provide day and month anyway because to follow the official spec we have to display a header with the current selected date.

**Comment by soyjavi** [comment]
@javivelasco @elliotatRetireup In my honest opinion for that situation is better use a `<Input type='date' />` with `disabled` property.

**Comment by elliotatRetireup** [comment]
There might be a workaround, but I guess what I'd like, is a date picker that goes Year-Month. I think the current one opens to the current date, then you have to click to go up to year or month selectors.

However, credit card expirations are just Month and Year, so selecting a specific date doesn't make sense. Currently I'm just using 2 comboboxes instead of the date picker for this.

If the goal is to strictly follow the material design, maybe this change doesn't make sense?

**Comment by javivelasco** [comment]
I think following the spec means also making this "sacrifice". Closing for now.
If more people want to do something on this we can review PRs of plan it.

**Comment by danieljodeci** [comment]
I am also very interested in a way to change the default display to "years" then to "months" once the year is selected. Is this possible yet? Would appreciate a PR for this!

**Comment by amirmol** [comment]
Definitely a good practice to allow which view to show up. Especifically when users are to specify their birthdate. I cannot tell you how much trouble this is causing for  people who don'tknow  how to change to a  year (e.g by clicking on Month's Back button) 

Imo, 
Defining a defaultView could be ideal but not the next best solution is to change the flow to  Select Year > select month/date.
