### ISSUE TITLE
Latest version of react gives PropTypes warning

### ISSUE THREAD

**Issue by BrockWills** [react-toolbox/react-toolbox#1410]
With React 15.5, importing PropTypes from React is deprecated in favour of importing from the new 'prop-types' package.

See this link: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

Thus, using react-toolbox with the latest version of react gives a deprecation warning in the console.

Will look into a PR for this.

**Comment by vldmr1986** [comment]
The same warnings: 
- in my local console:
warning "react-toolbox@2.0.0-beta.6" has incorrect peer dependency "react@^0.14 || ~15.4.0".
warning "react-toolbox@2.0.0-beta.6" has incorrect peer dependency "react-dom@^0.14.0 || ~15.4.0".
- browser console:
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by flexzero** [comment]
+1

**Comment by BrockWills** [comment]
#1413 Should hopefully solve this

**Comment by four-eyes-04-04** [comment]
I solved this by installing the `prop-types` from npm

```
npm install --save prop-types
```

then replacing all lines that looks like this:

```
MyComponent.propTypes = {
  prop: React.PropTypes.string.isRequired
}
```

to this:

```
import React, { Component } from 'react';
import PropTypes from 'prop-types';

class MyComponent extends Component {
  // .. the class itself
}

// now using the prop-types package
MyComponent.propTypes = {
  prop: PropTypes.string.isRequired
}
```

[prop-types from npm](https://www.npmjs.com/package/prop-types)

I hope this helps.

**Comment by kevinmthomasse** [comment]
Utilizing the **FlipMove** package still causes the **ProtoTypes** deprecated warning even after following the best practice illustrated here: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by sjain-mi9** [comment]
Even after importing PropTypes from prop-types, I'm receiving the same Warning. 
"react-toolbox": "^2.0.0-beta.8"
"prop-types": "15.5.8"
"react": "^15.5.4"

![2c434891b10ce64db58122a38b93bbbd4bbc1db44a1a767704 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/27962193/25341746/de98d9ca-28d7-11e7-872e-dc9daf4e7161.png)

**Comment by DORRITO** [comment]
Same here!  Importing react-flip-move gives me the error, despite having the correct and updated proptypes import.

**Comment by mandelaloko** [comment]
Also with me:
![captura de tela 2017-05-02 as 15 52 42](https://cloud.githubusercontent.com/assets/13973499/25634027/8a762fae-2f4f-11e7-9916-03b4ff9e1201.png)


```
"dependencies": {
    "classnames": "^2.2.5",
    "firebase": "^3.7.5",
    "firebaseui": "^1.0.1",
    "immutability-helper": "^2.1.2",
    "lodash": "^4.17.4",
    "re-base": "^2.7.0",
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "react-router-dom": "^4.1.1",
    "react-tag-input": "^4.7.1",
    "reactfire": "^1.0.0",
    "slugify": "^1.1.0"
  },

```

**Comment by BrunoQuaresma** [comment]
+1

**Comment by Kliton** [comment]
+1

**Comment by raunofreiberg** [comment]
Getting the same error here.

**Comment by Omortis** [comment]
Same here. Note that I'm not using PropTypes directly anywhere in my code though it seems to be called out many times by imported modules.

react@15.5.4
prop-types@15.5.10

**Comment by oshalygin** [comment]
Same issue, not using PropTypes from the `react` package anywhere in my code but its still throwing this warning.

**Comment by nivek91** [comment]
+1

**Comment by JuliusPopoola** [comment]
+1

**Comment by steve-goodwin** [comment]
+1

**Comment by devjaw** [comment]
+1

**Comment by SH-Stark** [comment]
+1

**Comment by BHouwens** [comment]
+1

**Comment by tobiasandersen** [comment]
Seriously, please stop writing +1 comments. I'm sure the maintainers will fix this when they have the time and energy to do so. If you still feel like you have to +1, use the reaction feature provided by GitHub for that exact purpose. 

Each time you write a new comment, a lot of people will get notifications about it (yes, I know that I'm doing the same here, sorry about that). And also, consider that the people maintaining this library is probably doing it on their free time, and that they might already be stressed/feel guilty about open issues and PRs (**which they really shouldn't!**).

**Comment by timtawan** [comment]
+1

**Comment by javivelasco** [comment]
@tobiasandersen, your comment at the top of the README. You totally nailed it and indeed I'm working on this on my spare time. It is generating a lot of personal issues that I can't take anymore, and I feel like I can't deal with all. I can still work on the project but probably not as much as the community might require. This is open source, please contribute everybody and I promise I'll be checking on PRs and releasing new versions when I have time for it.

BTW, a new version was already released with support for React 15.5 so I'm closing.
Thank you

**Comment by kalm42** [comment]
+1

**Comment by gouzaa** [comment]
+1

**Comment by hongduclam** [comment]
+1

**Comment by javivelasco** [comment]
Such a pity you three can't be banned from using the project

**Comment by srajiv-xpio** [comment]
+1

**Comment by dbsimeone** [comment]
+1

**Comment by zzwar2009** [comment]
+1

**Comment by jaydevonline** [comment]
And above three also.

**Comment by ericswenson15** [comment]
+1

**Comment by ericswenson15** [comment]
@tobiasandersen plus 1 add information about how recently ppl have been having the issue

**Comment by tobiasandersen** [comment]
@ericswenson15 What are you talking about? This issue is fixed in the latest release.

**Comment by javivelasco** [comment]
@ericswenson15 this is solved. If you are getting this warning with the latest react-toolbox it is some other lib

**Comment by thekhenzie** [comment]
+1

**Comment by rubenmoya** [comment]
Not sure about that last +1, but if you're having the same problem, please open a new issue, since this one was closed months ago, thank you! :)

**Comment by chenop** [comment]
I was getting this error for a whlie , until I figure out that the following line also produce this error:
`import * as React from "react";`
Fixing to the following in all my files:
`import React from "react";`
Did the trick for me.
