### ISSUE TITLE
Move to using react-transition-group instead

### ISSUE THREAD

**Issue by zxlin** [react-toolbox/react-toolbox#1414]
The [old repo](https://www.npmjs.com/package/react-addons-css-transition-group) says that we should use the new repo https://www.npmjs.com/package/react-transition-group instead and simply change the imports in the following manner:

```
// Old 
import CSSTransitionGroup from 'react-addons-css-transition-group';
 
// New 
import CSSTransitionGroup from 'react-transition-group/CSSTransitionGroup';
```

Can someone take this on? Thanks in advance!

**Comment by randycoulman** [comment]
See #1448, which makes this change.
