### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by luisnomad** [react-toolbox/react-toolbox#1418]
I have found an error here:
http://react-toolbox.com/#/components/app_bar

The example contains a reference to Link:
`import Link from 'react-toolbox/lib/Link';`

The correct path seems to be:
`import Link from 'react-toolbox/lib/link';`

https://github.com/react-toolbox/react-toolbox/tree/master/components/link

**Comment by rubenmoya** [comment]
Seems like it was fixed months ago in the `dev` branch, we just need to merge it to `master`

https://github.com/react-toolbox/react-toolbox/blob/dev/components/app_bar/readme.md
