### ISSUE TITLE
Timepicker: null value

### ISSUE THREAD

**Issue by wesleyody** [react-toolbox/react-toolbox#1421]
Using a Timepicker, is impossible to use an empty value (null or whatever). It should be possible

```
TypeError: Cannot read property 'getTime' of null
```
*DatePickerDialog*

**Comment by codeaid** [comment]
Have you tried using `undefined`? I think I had a similar issue and using that fixed the issue.

**Comment by wesleyody** [comment]
@codeaid it worked. What I had to do:

`value={ value ? new Date( value ) : undefined }`
