### ISSUE TITLE
Helper Text missing in Input

### ISSUE THREAD

**Issue by harsimranb** [react-toolbox/react-toolbox#1424]
In the Material Spec for text fields, there is an option for helper text to show under the text field. https://material.io/guidelines/components/text-fields.html#text-fields-layout.  React-Toolbox input does not support this yet.

The only dilemma I see here is how you would resolve the conflict between validation error message and helperText, as both are placed in the same location.

**Comment by rubenmoya** [comment]
We could change the `error` prop to be only boolean, and extract the string to another prop like `message`, `text` or something like that, so you have message, and message + error.

**Comment by rubenmoya** [comment]
Closing in favor of https://github.com/react-toolbox/react-toolbox/issues/1636
