### ISSUE TITLE
Clicking a Button with ripple enabled shows large circle

### ISSUE THREAD

**Issue by tfuqua** [react-toolbox/react-toolbox#1425]
I'm sure the issue is on my end. When I click on a button from react-toobox similar to the example http://react-toolbox.com/#/install, the ripple causes large black circle to appear.

![image](https://cloud.githubusercontent.com/assets/6877570/25297014/43d17296-26b9-11e7-8750-56e9d7a8abb3.png)

**Comment by harsimranb** [comment]
@tfuqua Looks like you're missing `postcss` in your webpack.  Refer to this: https://github.com/react-toolbox/react-toolbox#prerequisites.

**Comment by tfuqua** [comment]
That was it. thank you for the help
