### ISSUE TITLE
Change default font from "Roboto" in v-1.3.4

### ISSUE THREAD

**Issue by matthewberkompas** [react-toolbox/react-toolbox#1428]
@javivelasco Is there a way (specifically in version 1.3.4) to change the default font from "Roboto" to something else? I'm implementing Material Design on a redesign of a live web app which is currently using the Bootstrap framework and I'd like to use "Helvetica Neue" as the typeface on the new design so that it matches the old design until it's completely done away with. That way the old and new UI won't look drastically different. Any ideas?

**Comment by rubenmoya** [comment]
You can do it overriding [this css variable](https://github.com/react-toolbox/react-toolbox/blob/dev/components/variables.css#L16), this issue tells you how: https://github.com/react-toolbox/react-toolbox/issues/865
