### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by nikolayg** [react-toolbox/react-toolbox#1434]
First of all, it's a great library - thanks for your work!

Does `react-toolbox` support file upload components? If not, how would you go about file upload in an app that uses `react-toolbox`?

**Comment by k0r8i** [comment]
#1370 might help :)

**Comment by nikolayg** [comment]
Thanks, I found that as well! However, I couldn't make it work with [redux-api-middleware](https://github.com/agraboso/redux-api-middleware/issues) :(

I ended up using [react-file-upload](https://github.com/captivationsoftware/react-file-input) instead. This module has a few bugs, which I had to patch, but otherwise works fine.
