### ISSUE TITLE
How to add scrollbar in a dialog box?

### ISSUE THREAD

**Issue by raka9256** [react-toolbox/react-toolbox#1436]
My data is very large for dialog box and I want to add scroolbar for that

**Comment by pbflanagan** [comment]
This is a CSS problem, overflow-wrapper has all the styles you'll need: 

https://codepen.io/patrickflanagan/pen/RVgJZM

**Comment by pvsousalima** [comment]
How do I add this into my react code? I am also facing the same issue

**Comment by VinodLouis** [comment]
For a workaround I did via css

div[data-react-toolbox=dialog] > section{
  overflow: auto;
}
