### ISSUE TITLE
Old peerDependencies

### ISSUE THREAD

**Issue by ToniIltanen** [react-toolbox/react-toolbox#1441]
peerDependencies are set to old version of React.

  "peerDependencies": {
    "classnames": "^2.2.0",
    "prop-types": "^15.5.7",
    "react": "^0.14 || ~15.4.0",
    "react-addons-css-transition-group": "^0.14.0 || ~15.4.0",
    "react-dom": "^0.14.0 || ~15.4.0"
  }

current version for react is 15.5.4.
Also, the strict version could be changed to ^, there's no need for using stricts.

**Comment by gvillenave** [comment]
Just submitted #1448
