### ISSUE TITLE
AppBar 'leftIcon' not working

### ISSUE THREAD

**Issue by burakuluu** [react-toolbox/react-toolbox#1445]
I have successfully implement AppBar to my existing project but when I write 'menu' to 'leftIcon', it doesn't show the icon of 'leftIcon'. Also there is another weird icon showing on the right side and I don't know why.

![image](https://cloud.githubusercontent.com/assets/25999821/25709004/c028d4c4-30f0-11e7-825d-25f938136125.png)

This my code implementing 'leftIcon';
```
        <AppBar title='DASHBOARD' leftIcon='menu'>
          <Navigation type='horizontal'>
```

What did I go wrong?

**Comment by gustavohenke** [comment]
You must add the Material Icons font for this to work. This is described in the Installation instructions.

**Comment by burakuluu** [comment]
Thanks for reply @gustavohenke 
How can I actually import Material Design Icons to my project? Can you give clue about it?

**Comment by rubenmoya** [comment]
You have an example in the react-toolbox-example: https://github.com/react-toolbox/react-toolbox-example/blob/master/src/www/index.html#L16

You just have to add `<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">` to your `index.html`

**Comment by burakuluu** [comment]
Thanks @rubenmoya my leftIcon has shown up but the weird item on the right that I circled around with red still keeps showing up. Do you have any guess that what it would be? I didn't add, it just appeared when I add **AppBar** and **Navigation** to my code.

**Comment by burakuluu** [comment]
I found out. In the _theme.css_ class under the _AppBar_ folder of _react-toolbox_, there is a css identifier, which is '  `overflow-x: hidden;` ' and I removed it and that weird icon has disappeared. Closing the case.
