### ISSUE TITLE
Provide option to remove selection checkboxes from Table

### ISSUE THREAD

**Issue by drhayes** [react-toolbox/react-toolbox#145]
If it doesn't make sense to select rows... maybe by not providing `onSelect` callback? Or passing `selectable={false}` attribute at top-level?

**Comment by soyjavi** [comment]
Hi @drhayes all our components are *stateless*, in `Table` component if you want select all the rows you should provide all indexes in `selected` property.

**Comment by javivelasco** [comment]
@drhayes You have now a `selected` prop to pass to the component. Makes sense to be able to disable checkboxes from a prop, it's more expressive.

Thanks! :)

**Comment by alxaln** [comment]
legal
