### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by UX-Unicorn** [react-toolbox/react-toolbox#1464]
The current peer dependency react-css-themr 1.7.2 is still throwing the React.Proptype warning.  Any plans to update that dependency so the warning goes away?

**Comment by plougsgaard** [comment]
This has been fixed here https://github.com/react-toolbox/react-toolbox/commit/ae09770cd4aab861e95a070b975d7fdef1ace082

**Comment by samsch** [comment]
As an FYI, this is not fixed in 1.x, and since 1.x is no longer actively developed, probably won't be unless someone externally takes it on and makes a PR.
