### ISSUE TITLE
Problem: Unable to run docs with default instructions

### ISSUE THREAD

**Issue by trevorbernard** [react-toolbox/react-toolbox#147]
Following the default instructions leads to a litany of errors in the form of:

```
cd docs/
npm install 
npm start
...
ERROR in ../components/index.js
Module not found: Error: Cannot resolve module 'babel' in /Users/tbernard/code/react-toolbox/components
 @ ../components/index.js 9:0-28
```

**Comment by javivelasco** [comment]
You'd need to `npm install` from the root too since webpack config is simulating react toolbox package as an alias for the upper directory. That means we are also consuming packages from there so you need to `npm install` there too.

Reopen if it's still not working, thanks!! :)

**Comment by trevorbernard** [comment]
Awesome, it worked.

But the problem still persists and the default instructions are incorrect. I'd happily submit a pull request but I'm unable to reopen the issue.

**Comment by javivelasco** [comment]
I've just updated the commands listed in `README` file to make clear you'd need to install dependencies from the main package too.

Thanks @trevorbernard!! :)
