### ISSUE TITLE
Dropdown issue with Overflow Hidden

### ISSUE THREAD

**Issue by MadebyAe** [react-toolbox/react-toolbox#1471]
The issue happen when the parent container has overflow: hidden style
The dropdown list is affected by the parent style, I can suggest use Portal HoC for this.
```
<div style={{ overflow: 'hidden' }}>
        <Dropdown
          source={this.countries}
          onChange={this.handleCountryChange}
          value={this.state.countrySelected}
        />
</div>
```

Result:

<img width="719" alt="overflow hidden" src="https://cloud.githubusercontent.com/assets/1707438/26129090/b8550acc-3a43-11e7-8119-8905b9bdd9fc.png">

**Comment by LarsMontanaro** [comment]
+1
