### ISSUE TITLE
Error - Argument `$color` of `rgba($color, $alpha)` must be a color

### ISSUE THREAD

**Issue by niba** [react-toolbox/react-toolbox#148]
I upgraded my react-toolbox to the newest version and now I have this error:

```
Argument `$color` of `rgba($color, $alpha)` must be a color
Backtrace:
        node_modules/react-toolbox/components/button/_config.scss:8, in function `rgba`
        node_modules/react-toolbox/components/button/_config.scss:8
      in D:\Projects\DrivingLicense\node_modules\react-toolbox\components\button\_config.scss (line 8, column 29)
```
Sass fails on the first use of syntax `rgb($color-variable, alpha)`
Probably it's connected with #132

**Comment by javivelasco** [comment]
Probably there is a typo in the new color set. Have you added customization?

**Comment by niba** [comment]
My project has the same setup as your docs page. It works with 0.12.10 (version before merging color changes)

**Comment by javivelasco** [comment]
I need more information to debug this. I've just ran the example project with the theme configuration from `docs` subproject:

```scss
$color-primary: $palette-indigo-500;
$color-primary-dark: $palette-indigo-700;
$color-primary-light: $palette-indigo-500;
$color-accent: $palette-pink-a200;
$color-accent-dark: $palette-pink-700;
$color-primary-contrast: $color-dark-contrast;
$color-accent-contrast: $color-dark-contrast;
```

And it's working. I've also tried disabling `toolbox-loader` to use default configuration and it's working properly too. It may be connected to #132 indeed but I need to reproduce it to debug it. Try to remove your custom configuration to have default variables and check if it works.

**Comment by niba** [comment]
@javivelasco  I found error in one of my scss files. I had reassigned #color-accent with the old way (unquote and string color). Sorry for making troubles.

**Comment by javivelasco** [comment]
No problem!  Happy to see it works :)

**Comment by ranouf** [comment]
I have the same error after a npm upgrade -g.

this is my package.json
{
  "name": "WikikiBackend.Ng4",
  "version": "0.0.0",
  "dependencies": {
    "@angular/animations": "^4.1.3",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.1.3",
    "@angular/core": "^4.1.3",
    "@angular/flex-layout": "2.0.0-beta.8",
    "@angular/forms": "^4.1.3",
    "@angular/http": "^4.1.3",
    "@angular/material": "^2.0.0-beta.5",
    "@angular/platform-browser": "^4.1.3",
    "@angular/platform-browser-dynamic": "^4.1.3",
    "@angular/platform-server": "^4.0.0",
    "@angular/router": "^4.1.3",
    "@covalent/core": "^1.0.0-beta.4",
    "@types/node": "7.0.18",
    "angular2-jwt": "^0.2.3",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "^2.0.5",
    "aspnet-webpack": "^1.0.29",
    "auth0-js": "^8.7.0",
    "auth0-lock": "^10.16.0",
    "awesome-typescript-loader": "3.1.3",
    "css": "2.2.1",
    "css-loader": "0.28.1",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.9",
    "expose-loader": "0.7.3",
    "extract-text-webpack-plugin": "2.1.0",
    "file-loader": "0.11.1",
    "hammerjs": "^2.0.8",
    "html-loader": "0.4.5",
    "isomorphic-fetch": "2.2.1",
    "jquery": "3.2.1",
    "json-loader": "0.5.4",
    "preboot": "4.5.2",
    "raw-loader": "^0.5.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "^5.0.1",
    "sass-loader": "^6.0.5",
    "style-loader": "0.17.0",
    "to-string-loader": "1.1.5",
    "typescript": "2.3.2",
    "url-loader": "0.5.8",
    "webpack": "2.5.1",
    "webpack-hot-middleware": "2.18.0",
    "webpack-merge": "4.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@types/chai": "3.5.2",
    "@types/jasmine": "2.5.47",
    "@types/hammerjs": "^2.0.34",
    "chai": "3.5.0",
    "jasmine-core": "2.6.1",
    "karma": "1.7.0",
    "karma-chai": "0.1.0",
    "karma-chrome-launcher": "2.1.1",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.0",
    "karma-webpack": "2.0.3",
    "node-sass": "^4.5.3"
  }
}


I think it s because of an incompatibility between two packages, I didnt have this pb before.

How did you fix the pb?
