### ISSUE TITLE
Missing class on wrapper div in CardTitle component hinders styling

### ISSUE THREAD

**Issue by thomaseizinger** [react-toolbox/react-toolbox#1480]
The CardTitle component wraps the title and subtitle element in a div. (https://github.com/react-toolbox/react-toolbox/blob/dev/components/card/CardTitle.js#L18)

Unfortunately this div is not directly styleable because it does not have a classname. However, adding styles to this div is necessary for example to control text-overflow.

What is your take on problems like these?
Currently, I address this by directly selecting the div:
```
.cardTitle {
  > div {
    overflow: auto;
    margin-right: 3rem;
  }
}
````
However, this feels wrong. I would much rather select the div directly with a classname.

**Comment by rubenmoya** [comment]
Since the whole style customisation will change a lot in the next version of react-toolbox with the agnostic components, and this is working I think we could keep it the way it is.
