### ISSUE TITLE
Disable ripple of MenuItem does not work

### ISSUE THREAD

**Issue by kuka-radovan** [react-toolbox/react-toolbox#1489]
I set `menuRipple` property to false of `IconMenu`, but `MenuItems` still have ripple effect.  I expected that ripple effect will disappear according to appropriate documentation.

**Comment by rubenmoya** [comment]
You can see here in [Menu.js#L204](https://github.com/react-toolbox/react-toolbox/blob/dev/components/menu/Menu.js#L204) when the menu renders the items it chooses first the item `ripple` value, and then the menu `ripple` value which seems to be `true`.

Not sure if we should choose the menu configuration over the item one... but you can disable the ripple effect with `ripple={false}` in the menu items.

**Comment by kuka-radovan** [comment]
@rubenmoya Thank you for your help. BTW: it is missing in documentation.
