### ISSUE TITLE
Toggle button hover state is incorrect

### ISSUE THREAD

**Issue by nathanmarks** [react-toolbox/react-toolbox#149]
Not supposed to have a background on hover:

![image](https://cloud.githubusercontent.com/assets/4420103/11321481/47e48ef2-908f-11e5-9a4c-fd905d4f1000.png)

In other material design UI web libraries they use the icon button as the type of button you see here too:

![image](https://cloud.githubusercontent.com/assets/4420103/11321496/cb961518-908f-11e5-8bcb-cc51c296cbfa.png)

from: https://www.google.com/design/spec/layout/structure.html#structure-app-bar

You've probably seen it in tons of google apps too. These icon buttons are handy to use in other areas such as cards.

**Comment by nathanmarks** [comment]
On the note of the other types of icon buttons. I bring it up because I realize now the toggle buttons look quite small in the cards... for example:

![image](https://cloud.githubusercontent.com/assets/4420103/11321919/004fc14a-90a0-11e5-83e0-4999c6ac982e.png)


Now compare that to:

![image](https://cloud.githubusercontent.com/assets/4420103/11321920/0a653afc-90a0-11e5-8aa2-da6100fc6228.png)


Would be good to be able to achieve the latter in terms of sizing, it looks a lot better. 

Do you think the button is suitable for this or do you think there is a 2nd component needed? From what I see in other implementations, the hover and active (ripple) states are different from regular buttons. 

Look here for a demo implementation of an icon button:

https://elements.polymer-project.org/elements/paper-icon-button?view=demo:demo/index.html&active=paper-icon-button

**Comment by nathanmarks** [comment]
@javivelasco  Check out the spec page on my cards branch and play with the icon buttons, you'll see what I mean in how they compare to icon buttons in other material design user interfaces. They also seem a few pixels too small.

**Comment by javivelasco** [comment]
Agree. Let's split it into another component a review styling!
