### ISSUE TITLE
Usage of focus and blur on input

### ISSUE THREAD

**Issue by sjain-mi9** [react-toolbox/react-toolbox#1493]
Does the usage of focus and blur methods still exist for input component?? If yes, how can I make use of those methods.

**Comment by sjain-mi9** [comment]
In the latest update of react-toolbox, "react-toolbox": "2.0.0-beta.11", It did not have focus and blur as functions. Are you planning to have that back or permanently remove it?

**Comment by gonnarule** [comment]
Same here, just updated from beta8 to beta12 to get rid of PropTypes warnings, and my focus/blur calls won't work anymore.

**Comment by rubenmoya** [comment]
Not sure what could be happening, I tested it in `2.0.0-beta.11`, and passing `onBlur` and `onFocus` props to the `<Input />` component it seems to work:

```
<Input
  // Other props
  onBlur={() => console.log('onBlur event')}
  onFocus={() => console.log('onFocus event') }
/>
```
![input_events](https://cloud.githubusercontent.com/assets/905225/26560097/1b5fa008-44b4-11e7-82a4-c1d1297b63fa.gif)

**Comment by sjain-mi9** [comment]
@rubenmoya onBlur and onFocus are working totally fine. I'm looking for focus and blur methods for input. 
![image](https://cloud.githubusercontent.com/assets/27962193/26560192/969fd634-4482-11e7-87ec-49a300f54e63.png)

**Comment by rubenmoya** [comment]
Are you getting a **Uncaught TypeError: Cannot read property 'focus' of undefined** error?

This is in that method: `'DEPRECATED: To access the wrapped instance, you have to pass ' + '{ innerRef: fn } and retrieve with a callback ref style.'`

I made it work using `innerRef={(node) => { this.inputNode = node; }}` and then a method with `this.inputNode.focus();`, but I don't know if that's the problem.

**Comment by sjain-mi9** [comment]
Thank you for the help. I tried this method, but I'm getting a warning like:  Unknown prop `innerRef` on <input> tag. Not sure how would I define that?

**Comment by tobiasandersen** [comment]
Hm, that should work. Can you show how you're using it?

**Comment by sjain-mi9** [comment]
If I have understood it right, within my input I have 
<Input 
......
innerRef={(node) => { this.myInput = node; }} 
......
/>
and under componentDidMount have defined this.myInput.focus(). It does work right, but throws a warning saying Unknown prop innerRef

**Comment by tobiasandersen** [comment]
I believe [react-css-themr](https://github.com/javivelasco/react-css-themr) should use (and remove) that prop before it's passed down to the RT Input component. You aren't using an outdated version of that package?

**Comment by subhamagr** [comment]
Hi. I am facing the same problem. here's my code:

```js

render() {
   return (
     <Input
        type={type}
        {...input}
        disabled={disabled || !editable}
        icon={icon}
        theme={registrationTheme}
        className={registrationTheme.input}
        placeholder={placeholder}
        ref={(r) => { this.ref = r; }}
     />
   )  
}

```

and I am trying to make the input field focus using:
```js
makeFocus() {
  this.ref.getWrappedInstance().focus();
}

```

I'm using react-toolbox@1.3.4

**Comment by solics** [comment]
> Not sure what could be happening, I tested it in `2.0.0-beta.11`, and passing `onBlur` and `onFocus` props to the `<Input />` component it seems to work:
> 
> ```
> <Input
>   // Other props
>   onBlur={() => console.log('onBlur event')}
>   onFocus={() => console.log('onFocus event') }
> />
> ```
> ![input_events](https://cloud.githubusercontent.com/assets/905225/26560097/1b5fa008-44b4-11e7-82a4-c1d1297b63fa.gif)

That resolver my problem.
