### ISSUE TITLE
Don't treat warnings as errors

### ISSUE THREAD

**Issue by nZeus** [react-toolbox/react-toolbox#1505]
Latest release of React (15.5) introduces some new warnings, but they are shown as errors in the console:

![image](https://cloud.githubusercontent.com/assets/2727326/26527923/5f7f0d9e-439e-11e7-8c95-fcffa9c46775.png)

Please change them to **warnings**. They should be displayed as errors in the next version of React (16.0).

**Comment by rubenmoya** [comment]
Not sure this is a react-toolbox issue, as far as I know it's react itself who uses `console.error` instead of `console.warn`.
