### ISSUE TITLE
Typings for v2.0?

### ISSUE THREAD

**Issue by Kitanotori** [react-toolbox/react-toolbox#1507]
Installed 2.0.0-beta.11, but there doesn't seem to be usable typings around. Any info on the status of typings for 2.0.0 (when, where, who)? I understand it's still beta, but I am starting a new project using TypeScript, and having at least some kind of typings around is a huge factor in deciding the framework.

**Comment by Kitanotori** [comment]
Related to https://github.com/react-toolbox/react-toolbox/issues/1506

**Comment by javivelasco** [comment]
I've just released `beta.12` that fixes the issue
