### ISSUE TITLE
Place handleTabChange method to <Tabs> component

### ISSUE THREAD

**Issue by sanzhardanybayev** [react-toolbox/react-toolbox#1516]
Giving `<Tabs>` component's parent responsibility to handle tabs changing makes work clumsy in cases when you need to have mulptiple `<Tabs>` on your page. This entails having as much handler events and indexes as many` <Tabs>` tags are used. Very inconvenient.  

If you pass handleTabChange to `<Tabs> `component itself, then work becomes much easier and elegant. By the way that is Single Responsibility Principle from S.O.L.I.D.

I'll be thankful you make that change! Thanks in advance!

**Comment by Sanzhar-Danybayev-Excelsior** [comment]
@javivelasco hello! What do you think of it?

**Comment by tobiasandersen** [comment]
If you remove that, you wouldn't be able to control the tabs. But I guess having the option of using the tabs as either controlled or uncontrolled could be useful. 

If it's a pain for you, you could just create your own version of an uncontrolled tabs component by wrapping the Tabs component from react-toolbox.

**Comment by Sanzhar-Danybayev-Excelsior** [comment]
@tobiasandersen did you read by question from top to bottom? There's no need to control the tabs in his parent. This function by itself must be inside `<Tabs>` , as the only thing that `Tabs` component must do apart from containing tabs  is changing them.  More than that `<Tabs>`'s parent has nothing in common with it,  as his only purpose is to contain other stuff and provide with specific functions if needed. 
I've been making website for 5 years, believe me there're many cases when you need to have multiple `Tabs` on the same page. Writing event handler for each of then is **insane!**.

**Comment by Sanzhar-Danybayev-Excelsior** [comment]
@tobiasandersen by the way, why do you think that `Tabs` component  can't conrol tabs inside it?

**Comment by tobiasandersen** [comment]
Yes, I've read your post, but I'm not sure I understand what you're proposing. I thought you meant that we should remove the `index` and `onChange` prop from the `Tabs` component, and instead just let it control itself (i.e. and _uncontrolled_ component). Is this not what you meant?

**Comment by Sanzhar-Danybayev-Excelsior** [comment]
@tobiasandersen you misunderstood me) Look at `Tabs` [documenation ](http://react-toolbox.com/#/components/tabs), there you'll see that to handle tabs changing you need to create handler for each `Tabs` component, which is very inconvenient. Especially in the cases when you need to have multiple Tabs.  Did I manage to explain you what is the issue?

**Comment by tobiasandersen** [comment]
Yes, the `Tabs` component currently takes an `index` and an `onChange` prop. How would you like it to work instead?

**Comment by Sanzhar-Danybayev-Excelsior** [comment]
@tobiasandersen currently 'change tab' logic is in `<Tabs>`'s parent. What I suggest is to assign this responsibility to `<Tabs>` component itself. Because otherwise this logic is implemented in `<Tabs>`'s parent, which implies code duplication.

**Comment by Pajn** [comment]
That sounds like what @tobiasandersen describes, if you mean something else please show a code example demonstrating what you mean.
Not having this logic in <Tabs> is much more powerful and is inline with good practices in React as you are free to manage this state as you please (in Redux for example) and also allows you to change the current tab from the parent component.
