### ISSUE TITLE
There should be no loading ripples on components.

### ISSUE THREAD

**Issue by nathanmarks** [react-toolbox/react-toolbox#152]
Ripples have a specific purpose defined in the spec as a response to user input (touching, clicking, etc). They shouldn't be included as a loading indicator.

**Comment by javivelasco** [comment]
I agree. @soyjavi ?

**Comment by nathanmarks** [comment]
@javivelasco I mentioned it in another issue -- he agrees after I raised the point that it doesn't conform to spec. See #3 here: https://github.com/react-toolbox/react-toolbox/issues/114#issuecomment-156947912

**Comment by soyjavi** [comment]
Totally agry
