### ISSUE TITLE
Tabs Component 

### ISSUE THREAD

**Issue by gesseekur** [react-toolbox/react-toolbox#1522]
I am trying to create a raw tabs component and for some reason, tab is not getting recognized by the browser. 

![screen shot 2017-06-02 at 4 34 47 pm](https://cloud.githubusercontent.com/assets/13419784/26748314/6ba3f956-47b1-11e7-9f3d-74190cffb888.png)

In my stylesheets, I copied over the same exact styles as what is on react-toolbox's tab component source code just so I can see it working before adding my own. 

In my inspect element: 
![screen shot 2017-06-02 at 4 32 35 pm](https://cloud.githubusercontent.com/assets/13419784/26748276/2061b94c-47b1-11e7-83c4-3ce37d7d7f69.png)

I have no idea why Tab is not running and why my screen is blank!

Any suggestions will help :D thanks in advance.

BTW I am new to React so I'm sorry if there is an obvious solution.

**Comment by mirandamon** [comment]
I don't think you need two 'Tabs' components. It should be more like:
```
<Tabs ...>
    <Tab>
        {'Tab 1'}
    </Tab>
    <Tab>
        {'Tab  2'}
    </Tab>
</Tabs>
```
