### ISSUE TITLE
Invalid prop `children` supplied to `TableCell`

### ISSUE THREAD

**Issue by protzi** [react-toolbox/react-toolbox#1523]
https://github.com/react-toolbox/react-toolbox/blob/dev/components/table/readme.md#tablecell
Why this warning appears ?
> children	Any		Any content you want to render inside the cell.

And my test components look like this
```
{products.map(product =>
              <TableRow key={product.id}>
                <TableCell>{product.id}</TableCell>
                <TableCell>{product.title}</TableCell>
                <TableCell>{product.category}</TableCell>
                <TableCell>{product.price}</TableCell>
                <TableCell>{product.isAvailable}</TableCell>
                <TableCell>
                  <IconMenu icon='more_vert' position='topLeft' menuRipple>
                    <MenuItem value='download' icon='get_app' caption='Download' />
                    <MenuItem value='help' icon='favorite' caption='Favorite' />
                    <MenuItem value='settings' icon='open_in_browser' caption='Open in app' />
                    <MenuDivider />
                    <MenuItem value='signout' icon='delete' caption='Delete' disabled />
                  </IconMenu>
                </TableCell>
              </TableRow>
            )}
```
`Warning: Failed prop type: Invalid prop `children` supplied to `ThemedTableCell`, expected a ReactNode.
    in ThemedTableCell (created by ProductsIndex)`

`warning.js:36 Warning: Failed prop type: Invalid prop `children` supplied to `TableCell`, expected a ReactNode.
    in TableCell (created by ThemedTableCell)`

**Comment by sophiemachin** [comment]
I had the same problem. I made the problem go away by doing what the warning suggested and putting the cell content inside a `<div>`, like this:

    {products.map(product =>
      <TableRow key={product.id}>
        <TableCell><div>{product.id}</div></TableCell>
        <TableCell><div>{product.title}</div></TableCell>
        <TableCell><div>{product.category}</div></TableCell>
        <TableCell><div>{product.price}</div></TableCell>
        <TableCell><div>{product.isAvailable}</div></TableCell>
        <TableCell>
          <IconMenu icon='more_vert' position='topLeft' menuRipple>
            <MenuItem value='download' icon='get_app' caption='Download' />
            <MenuItem value='help' icon='favorite' caption='Favorite' />
            <MenuItem value='settings' icon='open_in_browser' caption='Open in app' />
            <MenuDivider />
            <MenuItem value='signout' icon='delete' caption='Delete' disabled />
          </IconMenu>
        </TableCell>
      </TableRow>
    )}

I'm not sure why the warning was being thrown.

**Comment by qapquiz** [comment]
DO NOT push boolean in JSX expression. It will fix this issue.

**Comment by gdamota** [comment]
<img width="180" alt="screen shot 2018-12-18 at 9 49 31 am" src="https://user-images.githubusercontent.com/35322499/50172587-42cdf300-02aa-11e9-8546-ccc4f64dd896.png">
is this acceptable. The popover tag was throwing a bunch of random react errors.

**Comment by damtea** [comment]
> DO NOT push boolean in JSX expression. It will fix this issue.

This solves my problem

**Comment by YoannBuzenet** [comment]
How do you handle Mui checkboxs if there must be no boolean ?

**Comment by jitension** [comment]
You can do something like this if it's relevant:

`<TableRow>
	<TableCell size="small">
		{this.state.checkbox ? (
			<Checkbox />
		) : (
			<>
				{'Some Label'}
				{this.state.tooltip && (
					<Tooltip title="Edit">
						<IconButton color="inherit" >
							<EditIcon fontSize="small" />
						</IconButton>
					</Tooltip>
				)}
			</>
		)}
	</TableCell>
<TableRow>`

**Comment by dcfw6l** [comment]
You missed the return after the map:

{products.map(product =>
  return  <TableRow key={product.id}>
    <TableCell><div>{product.id}</div></TableCell>
    <TableCell><div>{product.title}</div></TableCell>
    <TableCell><div>{product.category}</div></TableCell>
    <TableCell><div>{product.price}</div></TableCell>
    <TableCell><div>{product.isAvailable}</div></TableCell>
    <TableCell>
      <IconMenu icon='more_vert' position='topLeft' menuRipple>
        <MenuItem value='download' icon='get_app' caption='Download' />
        <MenuItem value='help' icon='favorite' caption='Favorite' />
        <MenuItem value='settings' icon='open_in_browser' caption='Open in app' />
        <MenuDivider />
        <MenuItem value='signout' icon='delete' caption='Delete' disabled />
      </IconMenu>
    </TableCell>
  </TableRow>
)}

**Comment by dcfw6l** [comment]
You missed the return key after mapping the array:

`{products.map(product =>
  return <TableRow key={product.id}> 
    <TableCell><div>{product.id}</div></TableCell>
    <TableCell><div>{product.title}</div></TableCell>
    <TableCell><div>{product.category}</div></TableCell>
    <TableCell><div>{product.price}</div></TableCell>
    <TableCell><div>{product.isAvailable}</div></TableCell>
    <TableCell>
      <IconMenu icon='more_vert' position='topLeft' menuRipple>
        <MenuItem value='download' icon='get_app' caption='Download' />
        <MenuItem value='help' icon='favorite' caption='Favorite' />
        <MenuItem value='settings' icon='open_in_browser' caption='Open in app' />
        <MenuDivider />
        <MenuItem value='signout' icon='delete' caption='Delete' disabled />
      </IconMenu>
    </TableCell>
  </TableRow>
)}`
