### ISSUE TITLE
Dropdown problem

### ISSUE THREAD

**Issue by hooligans993** [react-toolbox/react-toolbox#1525]
Hello. I have a problem with dropdown. It does not display correctly. My code on the screns
![capture](https://user-images.githubusercontent.com/22562763/26837363-90719cd2-4add-11e7-9a21-eb98e6742804.JPG)

And browser devTools:

![capture2](https://user-images.githubusercontent.com/22562763/26837364-908ca310-4add-11e7-84ca-6f5ca7ac6fbb.JPG)
`
import {Dropdown} from 'react-toolbox/lib/dropdown';

let countries = [
        { value: 'EN-gb', label: <span style={{color:"red"}}>asd</span> },
        { value: 'ES-es', label: 'Spain'},
        { value: 'TH-th', label: 'Thailand', disabled: true },
        { value: 'EN-en', label: 'USA'}
    ];

<Dropdown
                            source={countries}
                            onChange={(e)=>console.log(e)}
                        />`

**Comment by aislanmaia** [comment]
In this line:  `value: 'EN-gb', label: <span style={{color:"red"}}>asd` Have you tried to close the `span` element?
Example:
` value: 'EN-gb', label: <span style={{color:"red"}}>asd</span>`

**Comment by OmeGaCinoS** [comment]
Hello, I have the same problem don't understand why, if you can help me!

**Comment by rubenmoya** [comment]
Your elements doesn't have any css class added, check your Webpack configuration, you have an example here in [react-toolbox-example](https://github.com/react-toolbox/react-toolbox-example)
