### ISSUE TITLE
Misleading documentation regarding TypeScript

### ISSUE THREAD

**Issue by cprieto** [react-toolbox/react-toolbox#1526]
The documentation states:

> A TypeScript definition file react-toolbox.d.ts is available. It is referenced in package.json and should be picked up by the TypeScript compiler when importing from the npm package.

I am currently using react-toolbox 2 beta 12, and no reference to react-toolbox.d.ts, in fact, that file doesn't exist in the library.

I am having the common 'react-toolbox is not a module' from the TypeScript compiler:

> TS2307: Cannot find module 'react-toolbox'

It will be great if the documentation reflect the current status of the project instead.

I can't make my current sample to work, so sadly I cannot make a pull request stating what is the correct behaviour.

**Comment by Ramzeus** [comment]
I have the same version as you, and for me it's working ok (so far at least...).
Are you trying to include the whole library at once? Because I don't think that is how you are supposed to use it. I include thinks like this:
`import { Input } from 'react-toolbox/lib/input';`
