### ISSUE TITLE
Radio Buttons don't change their active state with setState

### ISSUE THREAD

**Issue by holzfelix** [react-toolbox/react-toolbox#1527]
Hi all,

I'm currently facing an issue regarding the react-toolbox-radioButtons. 

The idea is to add html-components (divs) with a click on a button, which will also be added into an array "myArray" within the state. This html component has it own radio buttons. This is the function that gets triggered whenever you click the "add" button:

```
addComponentToArray = () => {
const foo = {
            ...
            attr: 1,
            ...
        };
        return new Promise(resolve => {
            this.setState({
                myArray: this.state.myArray.concat(foo)
            }, resolve)
        });
}
```
This is my html for the radio buttons:

```
 <RadioGroup name='foo' className={css.myStyle} value={this.state.myArray[index].attr}
                                onChange={(value, event) => {
                                    this.changeInputOptionHandler(value, "attr", index)
                                }}>
                        <RadioButton label="Option1" value={1} />
                        <RadioButton label="Option2" value={2}/>
                        <RadioButton label="Option3" value={3}/>
                    </RadioGroup>
```
This is my handler:

```
function changeInputOptionHandler(value, field, index) {
this.setState((prevState) => ({
    myArray: prevState.myArray.map((currentIndex, i) => {
        if (i === index) {
            return {
                ...currentIndex,
                [field]: value
            }
        }
        return currentIndex
    })
}), () => {
    console.log("New state in ASYNC callback:", this.state.myArray);
} );
}
```
The state is set properly, e.g. if I'd click on the second option it writes "2" (as integer) into myArray at the right index. However, the radio buttons don't follow the change. They don't change their active-state.
If I would change the logic to a single object instead of an array (of html-components containing radio buttons), the radio buttons work. Are they not suited for that? Any ideas on how to solve this? Is this a problem regarding the radio buttons or am I simply missing something? Thanks!

**Comment by amy-butz** [comment]
This is very similar to an issue I am having, would love to know if you found a solution.

**Comment by holzfelix** [comment]
Yes I have found a solution. Its a bit big deal ;) I can extract the relevant code later and post it here.
