### ISSUE TITLE
What's smt for? 

### ISSUE THREAD

**Issue by ShirleyYoung0926** [react-toolbox/react-toolbox#1530]
I am reading the source code, and in Input component, if the Input is multiple line, there is a handleKeyPress function will prevent input more characters. What's the smt and why do we need this function?  Thanks.

    handleKeyPress = (event) => {
      // prevent insertion of more characters if we're a multiline input
      // and maxLength exists
      const { multiline, maxLength, onKeyPress } = this.props;
      if (multiline && maxLength) {
        // check if smt is selected, in which case the newly added charcter would
        // replace the selected characters, so the length of value doesn't actually
        // increase.
        const isReplacing = event.target.selectionEnd - event.target.selectionStart;
        const value = event.target.value;

        if (!isReplacing && value.length === maxLength) {
          event.preventDefault();
          event.stopPropagation();
          return undefined;
        }
      }

      if (onKeyPress) onKeyPress(event);
      return undefined;
    };

**Comment by antipin** [comment]
*smt* stands for *something* i guess
And we need this function for the reason clearly described in the comment above – prevent user from put in too many characters (if maxLength option is set)
