### ISSUE TITLE
Problems with Avatar styling

### ISSUE THREAD

**Issue by tristan-shelton** [react-toolbox/react-toolbox#1532]
Through regular usage of the library I've discovered a couple of issues with the default styling of Avatars that I feel should be fixed. Paste the following code into the playground to see what I mean:

```javascript
const Bugs = () => (
  <div>
    <List>
      <ListItem
        avatar={<Avatar icon="person" />}
        caption="This icon is misplaced"
      />
    </List>
    <Card style={{ width: 400 }}>
      <CardTitle
      	avatar={<Avatar icon="person" />}
        title="This longer card title squeezes the avatar for some reason"
      />
    </Card>
  </div>
);

return <Bugs />
```

In the first example, all icons inside of avatars attached to list items are not center aligned.

In the second example, a CardTitle's title will "squish" any avatar when the width of the card is not sufficient (e.g. on mobile).

**Comment by hawkins** [comment]
I also see the squished avatar issue frequently with medium-length titles or subtitles. Even shorter content such as the typical Twitch username, i.e., `adventurousdrake` causes the icon to be squished when the card is ~250px wide, which is typically how large my cards are.

Have you found any improvements to styling that alleviate this issue for you?

**Comment by tristan-shelton** [comment]
@hawkins I solved the problem today after finally implementing component overrides. See the documentation here first: https://github.com/react-toolbox/react-toolbox#customizing-all-instances-of-a-component-type

Once react-css-themr is set up and you can successfully override styles for components, you can add one for RTAvatar with the following contents:

```
@import '~react-toolbox/lib/variables';
@import '~react-toolbox/lib/avatar/config';

.avatar {
  min-width: var(--avatar-size);
}
```

This change should probably be backported into the base style for the avatar component.

As for the other unrelated issue of icon alignment, I found that it was due to an incorrect value for icon size in the ListItem theme. I was able to solve it by setting `list-item-icon-size` to `40`. To set variable values see the documentation here: https://github.com/react-toolbox/react-toolbox#theming-configuration-variables
