### ISSUE TITLE
Using Input inside Drawer shows the label when writing

### ISSUE THREAD

**Issue by jacargentina** [react-toolbox/react-toolbox#1537]
On the playground for the Drawer, simply put this:

```
          <Input type='text' label='Name' name='name' maxLength={16} floating={false}/>
```
And you get this when starts typing the letter "a"

<img width="391" alt="captura de pantalla 2017-06-12 a la s 22 30 32" src="https://user-images.githubusercontent.com/517228/27062051-c76cd392-4fbe-11e7-9b7a-d696d901282c.png">

**Comment by bwobst** [comment]
Looks like you're missing a couple props for `<Input />`.

Try adding these two things: `value={this.state.name} onChange={this.handleChange.bind(this, 'name')}`

It should now look like this: `<Input type='text' label='Name' name='name' value={this.state.name} onChange={this.handleChange.bind(this, 'name')} maxLength={16} floating={false} />`

Also make sure you include the `handleChange` function as well as an initial value for `name` in state (e.g. an empty string).

**Comment by jacargentina** [comment]
Solved! Can i suggest better docs?

**Comment by Rosenblad** [comment]
I thought this was a bug as well. Could easily be solved with some prop validation.
