### ISSUE TITLE
Any plans to support HTML5 input autofocus?

### ISSUE THREAD

**Issue by gavriguy** [react-toolbox/react-toolbox#1547]
I love using react toolbox & especially using the form and input components.
I was wandering if there is any plan to use the HTML5 input autofocus input attribute?

Thanks

**Comment by kajm** [comment]
+1

**Comment by hardchor** [comment]
That's already perfectly possible:

```jsx
          <Input
            type="text"
            label="Notes"
            multiline
            maxLength={200}
            value={value}
            onChange={setNotes}
            autoFocus
          />
```

**Comment by gavriguy** [comment]
10x I tried `autofocus` and not `autoFocus`

**Comment by charleslaw** [comment]
The docs should get updated, does anyone know where the text for the docs is located?

**Comment by charleslaw** [comment]
Ah, it's not in the doc folder where, just after submitting the comment I found it: https://github.com/react-toolbox/react-toolbox/blob/dev/components/input/readme.md I will update at some point unless someone beats me to it
