### ISSUE TITLE
Type for label should be React.ReactNode instead of string

### ISSUE THREAD

**Issue by PatrLind** [react-toolbox/react-toolbox#1552]
I am adding translation to a web application I am working on.
I have made a custom component (called Tr) that loads translation data  from the server and looks up the right translation from the users selected language.
But when I try to use it with for example the Link component I get type errors saying that `Types of property 'label' are incompatible. Type 'Element' is not assignable to type 'string | undefined'`.

I can get around the error by casting my <Tr> object to `any`, but that feels not so good to me.
So, therefore I propose that you make properties like label on all components to be of type `React.ReactNode` instead.
The reason I don't want to use a raw string is because I want to be able to color the text in a different color if the translation is missing. There are also data-tags on the translated text (in a `<span>` tag) that identify the text ID so I can relate to it at a later stage when it is rendered in the browser and also to allow for inline translation updates.

By the way, the AppBar title have some special case handling for when the title is of type string. If it is, it renders the title correctly, if it is not, it skips the h1-tag, and the AppBar theming breaks.

Some sample code:
```
            <AppBar title="{<Tr topic="Generic" field="AppTitle"/> as any}" leftIcon="menu">
              <Navigation type="horizontal">
                <Link label={<Tr topic="User" field="InboxLink"/> as any} icon="inbox" style={{color: 'white'}}/>
                <Link active label={<Tr topic="User" field="ProfileLink"/> as any} icon="person" style={{color: 'white'}}/>
              </Navigation>
            </AppBar>

```

**Comment by rubenmoya** [comment]
This has been answered already I think, check this out: https://github.com/react-toolbox/react-toolbox/issues/1306
