### ISSUE TITLE
Autocomplete item templating

### ISSUE THREAD

**Issue by justnick21** [react-toolbox/react-toolbox#1559]
Any suggestions on how I can achieve this?

Would you accept a PR adding this functionality?

**Comment by rubenmoya** [comment]
As far as I know, the Autocomplete component will have a major refactor, but a PR is always welcomed!

**Comment by justnick21** [comment]
OK, thanks. I will leave this for now. Related to this issue: https://github.com/react-toolbox/react-toolbox/issues/1169
