### ISSUE TITLE
Changing Hint and label Coloer

### ISSUE THREAD

**Issue by holzfelix** [react-toolbox/react-toolbox#1562]
Hi all,

how can I change the color of the label and the hints? 

![screenshot_2017 07 01_16h27m24s_006_](https://user-images.githubusercontent.com/6866699/27762895-50654c0a-5e7a-11e7-8a33-ac65d7a93561.png)

tried this in theme: 

```
.input label{
    color: #fff;
}
```

But nothing changes

**Comment by Pajn** [comment]
Please see the documentation about [Customizing Components](https://github.com/react-toolbox/react-toolbox#customizing-components).
