### ISSUE TITLE
Dropdown blur method

### ISSUE THREAD

**Issue by elliotatRetireup** [react-toolbox/react-toolbox#157]
Dropdowns should have a prop to set an event onBlur.

I thought maybe we could have it so that its true/false or an optional function.

So, if its true, it closes the dropdown on deBlur. If false, it doesn't close the dropdown (how it acts now)

Then, if they give a  function, it can run that function, too.

Might be useful to also give a Open/Closed prop to manually set the state of the dropdown

**Comment by soyjavi** [comment]
@elliotatRetireup Totally agree... we will fix it.
