### ISSUE TITLE
innerRef/withRef/other for Input node access?

### ISSUE THREAD

**Issue by jasonvasquez** [react-toolbox/react-toolbox#1570]
I have an Input component on which I need to perform cursor operations, etc. which are not react-toolbox specific, so I just need access to the DOM node.   I'm a little confused by the interplay between react-toolbox and react-css-themr here (this particular node sits under a ThemeProvider hierarchy.

In any case, as of 2.0.0-beta12, the innerRef prop is available and works on the Input component, but the typescript typings do not expose it as a prop, leading to compilation errors.  I'm happy to submit a PR to update the typing, but I wanted to make sure this was the correct or expected route going forward.

**Comment by rubenmoya** [comment]
Probably it's the best idea to submit a PR, any contribution is always welcomed! :D

**Comment by jasonvasquez** [comment]
@rubenmoya thanks - what is the correct branch to work against?  I've submitted PR's against the dev branch previously, but it appears that agnostic-typescript might be the correct target these days? (dev still indicates a 2.0.0-beta8 in it's package.json version)

**Comment by rubenmoya** [comment]
I think the best option is `dev`, since `agostic-typescript` as far as I know still in early stages.
