### ISSUE TITLE
Warning: Unknown prop `raised` on <a> tag. Remove this prop from the element.

### ISSUE THREAD

**Issue by holzfelix** [react-toolbox/react-toolbox#1579]
Hi 

I got this error:

`Warning: Unknown prop `raised` on <a> tag. Remove this prop from the element.`

I'm using raised like this:

` <Button icon='save' type="submit" label={<T value='processes.new.save'/>} raised primary/>
`
thats similar like the one on docs: http://react-toolbox.com/#/components/button

Any Idea how to fix this?

**Comment by bwobst** [comment]
The problem is likely coming from `<T />`. I did something like this which worked fine:

```
function T() {
  return <div>test</div>;
}
```

What does your `<T />` component look like?
