### ISSUE TITLE
All components for inputting data should have error props

### ISSUE THREAD

**Issue by elliotatRetireup** [react-toolbox/react-toolbox#158]
Specifically noticed that dropdowns were missing this.

I think it would be useful to have the text turn red and display an error like with the input boxes. This would make sense for the date/time pickers and anything else that takes user input, no?

**Comment by soyjavi** [comment]
Hi @elliotatRetireup , we are thinking in that... in the next release (0.14) we will be focus in improve `<Form>` component.

**Comment by nathanmarks** [comment]
@soyjavi I think that the focus should be more specifically on the individual components that make up a form, making them easy to use and layout for a unified experience **without** a helper component to tie them together. The `<Form>` component is not compatible with a lot of applications.

**Comment by javivelasco** [comment]
Now all input components are using `Input` component and displaying errors the same way. Reopen in case I'm missing something. They are:

- `Autocomplete`
- `Dropdown`
- `Input`
- `TimePicker`
- `DatePicker`

Coming during next release today!

**Comment by tomasztomys** [comment]
How can I put error message to DatePicker?

**Comment by javivelasco** [comment]
You have an `error` prop in the `DatePicker` to do so
