### ISSUE TITLE
Compatibility with preact-cli?

### ISSUE THREAD

**Issue by Pablo-Merino** [react-toolbox/react-toolbox#1583]
Hello! Great work with the library, I love it! It's beautiful.

However, I'm trying to use it with [preact-cli](https://github.com/developit/preact-cli), but it's giving me this error:

`Module build failed: Error: composition is only allowed when selector is single :local class name not in ".raised", ".raised" is weird`

After some research, I've realized that this error has something to do with webpack, but I'm not able to fix it. I tried hacking together some of the solutions in #1278 and #1359, but none work.

The steps to reproduce are:

- `preact create example-app`
- `yarn add react-toolbox`
- Add `import { Button } from 'react-toolbox/lib/button';` to the file, and try to use the component in `render()`.

I'd appreciate if someone gave me some directions to fix this, as I'm interested in using the library. Let me know if you need more info!

**Comment by SonDaniel** [comment]
Hey @Pablo-Merino,
I am also using Preact on top of my React.
If you look here: https://github.com/developit/preact-compat
Preact actually gives you an option to use react based libraries for preact. I dont know if this helps you but check it out. If it does, then great!

**Comment by Pajn** [comment]
See this note for using it with Create React App https://github.com/react-toolbox/react-toolbox#basic-usage

**Comment by rkostrzewski** [comment]
Hi @Pablo-Merino,
to use Preact CLI with `react-toolbox` you'd have to create `preact.config.js` and configure it as follows:
```
import path from 'path'

const reactToolboxPath = path.resolve('./node_modules', 'react-toolbox')

export default (config, env, helpers) => {
  const rules = helpers.getLoadersByName(config, 'postcss-loader')
  const cssModulesRule = rules[0].rule
  cssModulesRule.include.push(reactToolboxPath) // this enables css modules for react-toolbox
  const globalCssRule = rules[1].rule
  globalCssRule.exclude.push(reactToolboxPath) // exclude react-toolbox from global css
}
```

See readme for further [info](https://github.com/developit/preact-cli#webpack). If you encounter any problem feel free to open an issue at [Preact CLI](https://github.com/developit/preact-cli/issues)

**Comment by louisremi** [comment]
@rkostrzewski This seems to work!
Maybe you should add this example to the [Config Recipes](https://github.com/developit/preact-cli/wiki/Config-Recipes).
Thanks a lot anyway :-)

**Comment by Pablo-Merino** [comment]
Yep! @rkostrzewski's snippet works just fine! Thanks! I'm closing this issue.

**Comment by louisremi** [comment]
I'm unable to get color functions (`color(#000 a(25%))`) to work using the base config, which leaves the components half-styled :-/
Has anyone solved that last problem? @Pablo-Merino could you re-open the issue?

**Comment by louisremi** [comment]
Ok, my bad, I didn't follow the latest install instructions from react-toolbox. I needed to
`npm install --save-dev postcss-loader postcss-cssnext`
and add a `postcss.config.css` file at the root of my project:
```js
module.exports = {
	plugins: {
		'postcss-cssnext': {},
	},
};
```
Now it seems everything works fine :-)
