### ISSUE TITLE
Allow PropType.node for ListItem legend

### ISSUE THREAD

**Issue by ericbiewener** [react-toolbox/react-toolbox#1585]
It works given the current code, just needs proptype updates [here](https://github.com/react-toolbox/react-toolbox/blob/dev/components/list/ListItemContent.js#L18) and [here](https://github.com/react-toolbox/react-toolbox/blob/dev/components/list/ListItemLayout.js#L55).

**Comment by olegstepura** [comment]
Fixed with #1496. Also please take a look at #1611

this one should be fixed, but not released yet!

@javivelasco you definitely need to release more often!

**Comment by javivelasco** [comment]
I know :(
