### ISSUE TITLE
dropdown showing [object object]

### ISSUE THREAD

**Issue by holzfelix** [react-toolbox/react-toolbox#1589]
Hi the dropdown Input shows Object Object because value is `value=""`
value should be `value={}`

how can I change this?

![screenshot_2017 07 18_15h47m49s_004_](https://user-images.githubusercontent.com/6866699/28320296-7c5e06a4-6bd0-11e7-9cd3-9c1a4b6ab501.png)

**Comment by tobiasandersen** [comment]
Could you provide a small example?

**Comment by Pajn** [comment]
The dropdown labels should be strings, it looks like you are passing an object instead
