### ISSUE TITLE
Needs maintainers?

### ISSUE THREAD

**Issue by Pajn** [react-toolbox/react-toolbox#1596]
This is an awesome library on a great course but lately the activity has dropped. This is very understandable and unavoidable in these kinds of projects. However, one way to mitigate this a bit is to add more maintainers that can help review and merge PRs.

**Comment by oliviertassinari** [comment]
@javivelasco Adding new maintainers is a great way to scale up OSS projects. Go for it 🚀

**Comment by javivelasco** [comment]
I'm going through a hard time as you may notice from the inactivity. I need volunteers willing to keep compromised with the project! Of course I will try to get back to it ASAP but help is definitively needed, please anybody interested ping me through Slack or Twitter

**Comment by oliviertassinari** [comment]
@javivelasco Take care of yourself 👐

**Comment by kuka-radovan** [comment]
This project haven't moved anywhere for 4 months. Despite being really good. @javivelasco please, can you express yourself, whether you still have future plans with this project? Are there maintainers that expressed interest to maintain it?
