### ISSUE TITLE
Accessing Input value and .focus method

### ISSUE THREAD

**Issue by Mbarak-Mbigo** [react-toolbox/react-toolbox#1597]
Am using _react-toolbox version 2.0.0-beta.12_  with _typescript version 2.4.1_  and I can't seem to be able to access the value from this Input component instance as well as access its `focus` method.
This is my code `<Input label="add item" ref={(Input) => { this.state.itemInput = Input; }} />
` , am triggering the function using this button `<Button label="Add" onClick={this.add}/>` and this is the function am using to access its value 

```public add() {
    this.setState({
      addedItem: this.state.itemInput.value,
    });
    this.state.itemInput.focus();
``` 

What could I be doing wrong?

**Comment by binhqx** [comment]
react-css-themr is used to style the components. You will need to use the `innerRef={...}` to get access the the DOM node through the wrapper.  
`<Input label="add item" innerRef={(Input) => { this.state.itemInput = Input; }} />`

**Comment by Mbarak-Mbigo** [comment]
I tried that, and am getting `innerRef` does not exist `error TS2339: Property 'innerRef' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Input> & Readonly<{ children?: ReactNode; }> & Rea...'.`

**Comment by eldyvoon** [comment]
I had the same issue, why can't I simply focus an input upon componentDidMount?

`Unknown prop `innerRef` on <input> tag. Remove this prop from the element`

**Comment by eldyvoon** [comment]
Found a solution

`<Input autoFocus />`

**Comment by subhamagr** [comment]
Hi. I am facing the same problem. here's my code:

```js

render() {
   return (
     <Input
        type={type}
        {...input}
        disabled={disabled || !editable}
        icon={icon}
        theme={registrationTheme}
        className={registrationTheme.input}
        placeholder={placeholder}
        ref={(r) => { this.ref = r; }}
     />
   )  
}

```

and I am trying to make the input field focus using:
```js
makeFocus() {
  this.ref.getWrappedInstance().focus();
}

```

**Comment by dmeehan1968** [comment]
@eldyvoon Agree, ```autoFocus``` works, it is an HTML5 attribute for ```input``` elements.  ```Input``` props are passed down to the underlying DOM node which is what allows this to work.  

You can only have one node with autoFocus on a page (for hopefully obvious reasons!)

**Comment by literal-sushi** [comment]
I have two inputs that need to be focused dynamically. Is there a way?
