### ISSUE TITLE
Autocomplete: allow to track the query

### ISSUE THREAD

**Issue by mping** [react-toolbox/react-toolbox#161]
Right now there's no way to hook in autocomplete component and fetch more options that match the user query, because the input that's used is already hooking on key events.

Would be great if the component allowed for some sort of onKeyUp, onQuery or whatever, so remote options could be fetched and dataSource updated.

As a hack, you can listen to `onKeyDown` since `onKeyUp` is already being handled.

**Comment by javivelasco** [comment]
Makes a lot of sense. This makes me think about the `query` being extracted from the autocomplete. I think for most cases nobody would care about about it so probably it would be enough with a callback getting the value as first parameter. What's your opinion about it? Would you like to keep the value where you want or enough with a callback?

Thanks!

**Comment by nathanmarks** [comment]
@javivelasco I am currently using autocomplete inputs in a react app and have a good grasp of what's needed, I will review this component if you want.

**Comment by javivelasco** [comment]
Sure! :D

**Comment by mping** [comment]
A callback would fix all needs I guess. Maybe @nathanmarks has better input on this.
But I'd say the best is to match other component's specs so the api of react-toolbox is somewhat predictable. 

Don't really know if other components support/will support this though.

**Comment by javivelasco** [comment]
Well, the rest of components are taking as much data as possible out of the component but that makes the consumer responsible from storing the data in a higher order component or a store or something. The think is, how much does care the consumer about the query? Enough to delegate storing it? Just enough for a callback? IMO a callback is fine.

**Comment by nathanmarks** [comment]
@javivelasco  @mping I will take a look soon -- I have a need to hook up custom autocompletes to existing prediction APIs via redux so will have a good perspective on it

**Comment by javivelasco** [comment]
Great @nathanmarks !!

**Comment by nathanmarks** [comment]
@javivelasco Ok, i've tried using the autocomplete and found some issues. 

1. Doesn't implement the most prominent spec examples. Should focus on providing the user with the tools needed to implement common use cases. 
2. Cannot be used easily in complex applications (compatible with a small number of basic use cases).
3. Does too much

At the moment, this component is not suitable for a lot of use cases. I suggest making the API much more flexible, allowing it to work with any type of data source. The focus should be on providing the UI components in the spec in a way that they can work with any data source. To give users an easy option, you can still include the basic string matching query as an option to use in the library.

I have an idea for this, which would achieve the following:
1. Allow you to connect any type of data source or custom query
2. Also enable the use `<select>`, `<Input/>`, and `<input>` elements with full access to their element (or component API in the case of `<Input/>`). This means that all input related styling/settings props can be passed to that component as described in the documentation. That way the autocomplete implementation is also more portable and focuses on providing the elements unique to autocomplete.

I'm going to try something out, i'll let you know how it goes.

**Comment by javivelasco** [comment]
Great, we can put it on the upcoming roadmap.
I specially love the idea of implement some *async super-custom* example

**Comment by nathanmarks** [comment]
@javivelasco As part of my process i'm building a simple select replacement (single, regular input style), alongside an asynchronous autocomplete with external API communication.

I'm also making sure that this will play nice with any type of input -- you see autocompletes everywhere in material design. Lots of full width form fields on android, a few input fields, but mostly -- raised search inputs like this:

![image](https://cloud.githubusercontent.com/assets/4420103/11453506/c868fc20-95da-11e5-95db-e1166e00fb52.png)

**Comment by nathanmarks** [comment]
@javivelasco we should either create a new issue or use a single issue to combine #161 (this), #170 and #138

**Comment by nathanmarks** [comment]
@javivelasco please close this in favour of https://github.com/react-toolbox/react-toolbox/issues/174
