### ISSUE TITLE
why react-toolbox components don't accept and render props.style?

### ISSUE THREAD

**Issue by the1900** [react-toolbox/react-toolbox#1610]
For instance I need to set inline style for positioning. 
``` jsx
<Navigation type='vertical' style={this.props.style} theme={theme} className={this.state.active ? theme.fm__active :""} >
          <Button floating mini theme={theme} style={{backgroundColor: BrandColor.linkedin}}>         
            { <LinkedinIcon /> }
          </Button>
          <Button floating mini theme={theme} style={{backgroundColor: BrandColor.facebook}}>         
            { <FacebookIcon /> }
          </Button>        
        </Navigation>
```

But It doesn't work and I think because of there is no `style={props.style}` in return method of all of the components.

**Comment by paultannenbaum** [comment]
Because the implementation and styling is abstracted away from the components you are calling. So everything you want to style must be used through the theme api. I do not necessarily agree with this approach, but this is how react-toolbox has decided to approach this problem.

**Comment by rubenmoya** [comment]
This will completely change in the `v3`, stay tuned :)
