### ISSUE TITLE
Autocomplete: doesn't allow for '0' values

### ISSUE THREAD

**Issue by mping** [react-toolbox/react-toolbox#162]
Dunno if its a bug, but autocomplete currenty verifies if the source prop has `length`: https://github.com/react-toolbox/react-toolbox/blob/master/components/autocomplete/index.jsx#L115

```
if (source.hasOwnProperty(length)) {
        return new Map(source.map(function (item) {
```

Note that `length` is not a string, and currently has value '0' (maybe it's an artifact from babel? I couldn't find any var declaration. 

Maybe it should check for `'length'` instead?
Anyway I did a PR: https://github.com/react-toolbox/react-toolbox/pull/163

**Comment by nathanmarks** [comment]
Fixed by #163 (#12e9e4bf4f11a9ca9b6290063f1fc5ab182a88b7)
