### ISSUE TITLE
Importing tabs gives error

### ISSUE THREAD

**Issue by elliotatRetireup** [react-toolbox/react-toolbox#164]
Can't import tabs and tab without getting several errors:

ERROR in ./~/react-toolbox/lib/utils/polyfills.js
Module not found: Error: Cannot resolve module 'core-js/fn/array/from' in /Users/elliot/react_working/node_modules/react-toolbox/lib/utils
 @ ./~/react-toolbox/lib/utils/polyfills.js 3:0-32

ERROR in ./~/react-toolbox/lib/utils/polyfills.js
Module not found: Error: Cannot resolve module 'core-js/fn/array/iterator' in /Users/elliot/react_working/node_modules/react-toolbox/lib/utils
 @ ./~/react-toolbox/lib/utils/polyfills.js 5:0-36

ERROR in ./~/react-toolbox/lib/utils/polyfills.js
Module not found: Error: Cannot resolve module 'core-js/fn/map' in /Users/elliot/react_working/node_modules/react-toolbox/lib/utils
 @ ./~/react-toolbox/lib/utils/polyfills.js 7:0-25

ERROR in ./~/react-toolbox/lib/utils/polyfills.js
Module not found: Error: Cannot resolve module 'core-js/fn/string/starts-with' in /Users/elliot/react_working/node_modules/react-toolbox/lib/utils
 @ ./~/react-toolbox/lib/utils/polyfills.js 9:0-40

ERROR in ./~/react-toolbox/lib/utils/polyfills.js
Module not found: Error: Cannot resolve module 'core-js/fn/symbol' in /Users/elliot/react_working/node_modules/react-toolbox/lib/utils
 @ ./~/react-toolbox/lib/utils/polyfills.js 11:0-28

**Comment by soyjavi** [comment]
Hi @elliotatRetireup did you upgrade your NPM package? Seems like you didn't update the last packages.

**Comment by elliotatRetireup** [comment]
Do you mean the react-toolbox or npm itself?

React-toolbox is on v0.12.13

**Comment by javivelasco** [comment]
He means if you npm installed after the update to make sure you´re not missing any new additions to toolbox! :)

**Comment by elliotatRetireup** [comment]
Okay I will update later today then let you guys know. Since I'm the only one with this issue, its probably what you're saying. Thanks!

**Comment by javivelasco** [comment]
Nice, I'm closing and if it's still happening let us know to reopen and investigate it further!
