### ISSUE TITLE
Accessing component nodes for styling

### ISSUE THREAD

**Issue by paultannenbaum** [react-toolbox/react-toolbox#1640]
Maybe I am missing something, but I can not how to figure out how to style individual component nodes that are not exposed through the components theme api. 

For example, on a `Dialog` component, how would I target the dialog background overlay (the dark area the dialog sits on top of)? I have been using the library for only a couple days but I have run into several cases where I can not target certain pieces of a component and feel like I may be missing something.

Why not just put a classname or data attribute on each generated node of the component?

**Comment by cklab** [comment]
The overlay theme.css uses a variable `--overlay-color` for this [(see here)](https://github.com/react-toolbox/react-toolbox/blob/dev/components/overlay/theme.css#L6). If you use webpack, you can override it in postcss.config.js:

```
module.exports = {
    plugins: {
        ...
        'postcss-cssnext': {
            features: {
                customProperties: {
                    variables: {
                        "overlay-color": "red"
                    }
                }
            }
        }
    }
};
```

**Comment by paultannenbaum** [comment]
Thank you @cklab this is very helpful. I still do not understand why all nodes aren't exposed via some kind of class or data attribute for custom styling as it seems like something that a lot of people would want from a library, versus having to do this sort of reverse engineering style fix, but at least it works. Thanks for responding and the great library!
