### ISSUE TITLE
ListItem action does not prevent default

### ISSUE THREAD

**Issue by TraceyK14** [react-toolbox/react-toolbox#1641]
I have a ListItem that has an onClick event. I also have an IconMenu being passed down to rightActions prop. 

When I click the IconMenu it also triggers the ListItem onClick action.

Maybe I am doing something wrong?

**Comment by Pajn** [comment]
Event bubble up to parent elements. You can prevent this by capturing the event and calling `stopPropagation()`

**Comment by TraceyK14** [comment]
@Pajn Thank you for responding! I figured this out and forgot to comment and close, Sorry about that!

Below is an example of how to do this if anyone finds this issue and needs help as well. 

```
<IconMenu icon="more_vert"  onClick={ e => e.stopPropagation() }>
    <MenuItem icon="delete" caption="Delete" />
</IconMenu>
```

**Comment by TraceyK14** [comment]
@Pajn Thank you for responding! I figured this out and forgot to comment and close, Sorry about that!

Below is an example of how to do this if anyone finds this issue and needs help as well. 

```
<IconMenu icon="more_vert"  onClick={ e => e.stopPropagation() }>
    <MenuItem icon="delete" caption="Delete" />
</IconMenu>
```
