### ISSUE TITLE
React tool box on React native

### ISSUE THREAD

**Issue by NawazKhanMd** [react-toolbox/react-toolbox#1644]
Is it still not possible to use React tool box on React native Pls Reply....

**Comment by Pajn** [comment]
No, this is currently not possible and I have a hard time seeing that become a possibility in the near future.

**Comment by rubenmoya** [comment]
The next version of React Toolbox will work on React Native, you can check some examples on javi's twitter, but for now we have to wait!

**Comment by eduardoinnorway** [comment]
Can you please provide any more info?

**Comment by rubenmoya** [comment]
The `v3` will be agnostic, so you can use it wherever you want, but that's the only thing I know, there are some examples in Javi's twitter with a date picker working in react native, but we won't know anything else until `v3` is out, which I hope is in the next months :)

Sorry for not having any more info!
