### ISSUE TITLE
Disable default behavior of open/close for menu

### ISSUE THREAD

**Issue by sjain-mi9** [react-toolbox/react-toolbox#1647]
Menu has default behavior for open and close, is there a way to disable that and have out own open/close control?
I'm mainly looking to disable close when someone clicks on the screen (outside menu) and not sure how to achieve that.

**Comment by Pajn** [comment]
You should be able to do this by capturing clicks and touchstart before it bubbles up to the document.
For example:
```
<div onClick={e => e.stopPropagation()} onTouchStart={e => e.stopPropagation()}>
 You should be able to click here withou the menu closing
</div>
```
