### ISSUE TITLE
data-* props

### ISSUE THREAD

**Issue by mikeplus64** [react-toolbox/react-toolbox#1648]
It'd be nice to support data-* props; probably just by passing any "extra" props found to the root elements for each component.

In case anyone is interested or wants let me know this is crazy (I don't know), specifically I'm using a data attribute to avoid having to allocate a new function for every element of a list for an onClick handler, or having to fudge around with memoisation. I suspect this is a lighter-weight approach though I haven't done any measurements to show which is best. Then again, this needs DOM access, which JS folklore has lead me to believe is slow...

The code looks like

```
...
onClickItem(ev) {
  foo(ev.target.dataset.thing);
}
render() {
  return this.props.something.map(a => <ListItem key={a.key} onClick={this.onClickItem} data-thing={a.thing} caption={a.caption} />)
}

**Comment by Pajn** [comment]
Support for passing unknown props might be worth considering, there are both up and downsides with that. For your specific use case though I would recommend allocating a new function every time though. I have very rarely and only in extreme special cases had that give any noticeable performance effect. The simpler code wins here and the time is probably better spent optimizing something else :smiley:
