### ISSUE TITLE
<Button> component  hover effects  doesn't work !!! HELP！！

### ISSUE THREAD

**Issue by zdJOJO** [react-toolbox/react-toolbox#1666]
hi, everybody ! Plz help me !

i use `Button` component  .

when my mouse passes through the `Button` ,  `Button` hover effects  doesn't work !! 

what's wrong with it ??  I've spent two hours looking for reason.....

there is my code: 

```
import React from 'react';
import ReactDOM from 'react-dom';
import Button from 'react-toolbox/lib/button';

ReactDOM.render(
  <Button flat primary label="Hello World!" />,
  document.getElementById("app")
); 
```

**this is my result , but it's wrong:** 

![20170830162156](https://user-images.githubusercontent.com/25069798/29862880-733a6116-8da0-11e7-9edc-76c66036fbe2.jpg)

**An example of the official website：**

![2017-08-30-162123-169](https://user-images.githubusercontent.com/25069798/29862867-64ae7d80-8da0-11e7-9d2f-388c4a3068c1.jpg)

**Comment by Pajn** [comment]
It's impossible to tell exactly what's wrong without more information.
I would guess there's a problem with your build configuration though. Please check again your configuration against the steps outlined in the README. If you are not fully confident about configuring webpack I would personally recommend using themr by following the steps for create-react-app and in that way completely avoid any webpack configuration.

**Comment by TimoRuetten** [comment]
Its a bit strange - I have the same issue. Click Ripple effects and all other effects of most of the components are working perfectly - but the Button hover effect is not available.

**Comment by TimoRuetten** [comment]
@zdJOJO I had the same issue. After taking a look into https://github.com/react-toolbox/react-toolbox-example and modify my webpack bundle its works.

My webpack bundle looks now like this:


```javascript
// ...
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract({
          loader: [
            {
              loader: 'css-loader',
              query: {
                localIdentName: '[hash:8]',
                modules: true,
                sourceMap: true,
                importLoaders: 1,
              },
            },
            {
              loader: 'postcss-loader',
            },
          ],
        }),
      },
      {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract({
          loader: [
            'style-loader',
            {
              loader: 'css-loader',
              query: {
                localIdentName: '[hash:8]',
                modules: true,
                sourceMap: true,
                importLoaders: 1,
              },
            },
            {
              loader: 'postcss-loader',
            },
            {
              loader: 'sass-loader',
              query: {
              },
            },
          ],
        }),
      },
```


I hope it will help you.
