### ISSUE TITLE
Add title attribute back to image in Avatar

### ISSUE THREAD

**Issue by ericbiewener** [react-toolbox/react-toolbox#1673]
The image title attribute was removed in [this commit](https://github.com/react-toolbox/react-toolbox/commit/3859c464ff0bc792b65f362167c4294c75a393ef). How would you feel about adding it back in? The mouseover tooltip it provides can be helpful.

It also looks like only the image, icon, or title span element should be getting rendered rather than all 3.

**Comment by rubenmoya** [comment]
That's a good catch! I'm not sure why it was removed, we should've kept it along with the `alt` attribute since they're used for different things. I'll tackle this one as soon as I can (probably on Monday).

Thank you for the feedback!
