### ISSUE TITLE
Autocomplete can't get name attribute

### ISSUE THREAD

**Issue by eldyvoon** [react-toolbox/react-toolbox#1674]
I use Autocomplete like this with Input, but Autocomplete has a problem using `name`

```
<Autocomplete
                direction="down"
                selectedPosition="above"
                label="Events"
                name="events" //failed
                multiple
                onChange={this.onChange}
                source={events}
                value={user.events}
              />

onChange(value, event) {
    const field = event.target.name; // undefined
 
  }
```

**Comment by rubenmoya** [comment]
What is happening is that the event that you're receiving there is the click on the `<li />` generated by the autocomplete, you can check it here: https://github.com/react-toolbox/react-toolbox/blob/dev/components/autocomplete/Autocomplete.js#L367
