### ISSUE TITLE
Dropdown doesn't close if clicking immediately on a different Dropdown

### ISSUE THREAD

**Issue by GutzC** [react-toolbox/react-toolbox#1678]
When one Dropdown component is open and you then click directly onto a different Dropdown component, the original is not being closed. Can view an example of the behavior in the [Dropdown playground](http://react-toolbox.com/#/components/dropdown):

![image](https://user-images.githubusercontent.com/2251011/30441456-b93cc50e-9936-11e7-8855-3fb531cda9e6.png)

Looks like there have been a couple issues in the past that are showing as closed ([#1246](https://github.com/react-toolbox/react-toolbox/issues/1246), [#314](https://github.com/react-toolbox/react-toolbox/issues/314)), so possibly a regression?

**Comment by rubenmoya** [comment]
I've not been able to reproduce it in the playground, closing for now
