### ISSUE TITLE
Trying to use react-starter with react-toolbox

### ISSUE THREAD

**Issue by Sicria** [react-toolbox/react-toolbox#169]
Hello,

I'm trying to use https://github.com/webpack/react-starter with React-toolbox and am getting an error when building.

I've looked at the example and tried to get it to work using the webpack that comes with react-starter but just can't seem to figure it out.

Getting this error

```
Module not found: Error: Cannot resolve module 'react-toolbox/lib/button'
```

Any help would be greatly appreciated.

**Comment by javivelasco** [comment]
Hi @Sicria ! If you don't get it working I can try to create a project with react-starter during the weekend. Anyway it looks like `react-toolbox` is not included in the webpack configuration. Make sure it is in your `node_modules` and also that it is included in your build. Also remember you have to add `sass-loader` to process toolbox styles.

**Comment by Sicria** [comment]
Hey @javivelasco that would be great, I've tried multiple things but can't seem to get it working. I'm sure it's a 5 min thing that I'm missing to do with Webpack.

**Comment by Sicria** [comment]
Hi @javivelasco did you get a working version of react-starter and react-toolbox? Still can't seem to figure out a way to get them to work together.

**Comment by javivelasco** [comment]
Hi @Sicria! I'm sorry but I didn't have try enough to try :( We are releasing a new version today, I'll try to do it today but I can't guarantee. Anyway, I'll do it as soon as possible. Sorry!

**Comment by javivelasco** [comment]
Everything should work with 1.0.2!
