### ISSUE TITLE
React 16

### ISSUE THREAD

**Issue by et1975** [react-toolbox/react-toolbox#1694]
I haven't seen any mention of it, will this upgrade happen before 2.0 release?

**Comment by rubenmoya** [comment]
Yes, we will upgrade to React 16 before the release :)

**Comment by landabaso** [comment]
Will you create a beta13 exactly the same as beta12 but with React 16 support (for easier upgrade path)?
Or will you add also new feats / maybe some breaking changes too?

**Comment by rubenmoya** [comment]
We're planning to merge the `agnostic-typescript` branch, which already has React 16, it will be exactly the same, but the project organization will be quite better since we're using lerna to be able to have different packages, one of them being the current version of react-toolbox (packages/react-toolbox).

**Comment by landabaso** [comment]
Would you please also consider a beta13 exactly as beta12 with React16?
In fact I'm using React 16 with beta12 just fine but yarn complains all the time:

```
warning "react-css-themr@2.1.2" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0".
warning "react-toolbox@2.0.0-beta.12" has unmet peer dependency "prop-types@^15.5.7".
warning "react-toolbox@2.0.0-beta.12" has incorrect peer dependency "react@^15.5.0".
warning "react-toolbox@2.0.0-beta.12" has incorrect peer dependency "react-dom@^15.5.0".
warning "react-transition-group@1.2.0" has incorrect peer dependency "react@^15.0.0".
warning "react-transition-group@1.2.0" has incorrect peer dependency "react-dom@^15.0.0".
```

react-css-themr has the same issue.

Maybe we should wait until [react-transition-group v1 updates also to React 16](https://github.com/reactjs/react-transition-group/issues/207).

**Comment by tfuqua** [comment]
react-transition-group just released their update to work with React 16

**Comment by mgcrea** [comment]
Also, would be great to backport the support for React 16 to the `v1.x` as it should be quite easy.

**Comment by mlcohen** [comment]
Any status update on this? We use react-toolbox v1 extensively with React v15. We'd really love to upgrade to v2 but won't do so until react toolbox is compatible with React v16. What is the road map for react-toolbox?

**Comment by jmar777** [comment]
I have a little bandwidth I could lend to the effort as well (unless @rubenmoya's PR is good to go as is, of course). Would love to contribute however I can to get this compatible with React 16... just need a little guidance on where that energy is best spent. :)

**Comment by wimpog** [comment]
Anything new here? Will there be a **react-toolbox** release for **React 16**?
