### ISSUE TITLE
Glitches on modal backdrop opacity after Chrome 61 Update

### ISSUE THREAD

**Issue by leonardobaggio** [react-toolbox/react-toolbox#1695]
Hey folks,

Just noticed that my modal's/dialogs backdrop became kinda weird after I've installed the new version of Google Chrome. At first I thought there are something going wrong with my graphics driver since I've coincidentally restored my computer yesterday (and then installed the latest Chrome version available), but the same issue was occurring in different computers (all with Chrome 61.0.3163.100 ).

## The Issue

When a dialog is shown, the backdrop div display some random glitches
![glitch](https://user-images.githubusercontent.com/18285859/30973246-0f56d986-a443-11e7-840a-48da51d1e77d.gif)

![image](https://user-images.githubusercontent.com/18285859/30973029-7e05223a-a442-11e7-9e1b-39060efea812.png)

## Workarround
After some further investigation I've found out that changing the `background-color: #fff;` from hexadecimal to RGBA `background-color: rgba(0,0,0,0.9);` solves the problem.

Removing the opacity property also solves the glitch, but the point here is to keep the backdrop's transparency.

![glitch_solved](https://user-images.githubusercontent.com/18285859/30973537-bdede890-a443-11e7-8401-1313f8198676.gif)

## Possible root Cause

I've checked the Chromium Changelog for version 61 and this was in the new features list:
`- CSS color values can now be 8- and 4-digit hex colors of the format #RRGGBBAA and #RGBA.`
https://blog.chromium.org/2017/08/chrome-61-beta-javascript-modules.html

Maybe I should file a bug report in Chromium project...

**Comment by rubenmoya** [comment]
Yes, it seems like a problem with chrome/chromium more than react-toolbox itself.

**Comment by edbernal** [comment]
This guy is a rock star! You hit on the exact problem we found with our agent facing application after we got the Chrome update. Thanks for the info because it helped us quickly fix the problem.

**Comment by leonardobaggio** [comment]
> This guy is a rock star! You hit on the exact problem we found with our agent facing application after we got the Chrome update. Thanks for the info because it helped us quickly fix the problem.

Thank you! I'm really glad to help!

Could you please provide an endorsement in the acknowledgment of this bug in my submission to the Project V8's Issue tracker? (images and any extra info is always appreciated)

Here follows the link:
https://bugs.chromium.org/p/v8/issues/detail?id=6866&can=1&q=opacity&colspec=ID%20Type%20Status%20Priority%20Owner%20Summary%20HW%20OS%20Component%20Stars

**Comment by LiranCohen** [comment]
+1 Thank you for this! Marketing department was going crazy over this as it started happening the day after a new release was deployed.
