### ISSUE TITLE
Table integration with react-virtualized?

### ISSUE THREAD

**Issue by lolJS** [react-toolbox/react-toolbox#1696]
I would like to use [react-virtualized](https://github.com/bvaughn/react-virtualized/) with the components in this library. Although it doesn't seem like there's any documentation around the individual Table components. Is this even possible?

**Comment by rubenmoya** [comment]
By reading their docs it doesn't seem they let you use custom components, they only let you change the styling through their `.css` file.

**Comment by hansena** [comment]
react-table was quite easy to integrate with react-toolbox if you are open to an alternative table library...
