### ISSUE TITLE
autocomplete

### ISSUE THREAD

**Issue by janusch** [react-toolbox/react-toolbox#170]
Hey,
great work on the component toolbox, i'd love to start using it!

When playing around with the autocomplete in the playground there is an error, when multiple is set to false `multiple={false}` 

Also in the documentation it could be useful to mention if the autocomplete works well with async data sources. 

Keep up the great work!

**Comment by javivelasco** [comment]
Thanks for reporting and for your words! 
We are gonna take a look on that :)

**Comment by nathanmarks** [comment]
@javivelasco please close this in favour of #174

**Comment by oscar-g** [comment]
I know this is closed, but I got the demo working by editing the state, before adding `multiple={false}`:
```
state = {
  countries: ''
}
```
