### ISSUE TITLE
styling components in react-toolbox using scss

### ISSUE THREAD

**Issue by aayushis12** [react-toolbox/react-toolbox#1702]
I have a component like this

	<Card style={{width:'350px'}} theme={theme}>
		<CardMedia aspectRatio="wide" image=""/>
		<CardTitle title="Avatar here" className={theme.card-title}/>
	</Card>
I have imported my scss and react-toolbox components like this-
```

import theme from './assets/theme/theme';
import './assets/theme/theme.css';
import './App.scss';
import ThemeProvider from 'react-toolbox/lib/ThemeProvider';
import {Card,CardTitle,CardMedia} from 'react-toolbox/lib/card';
```
In my App.scss file, I have-

```
.card-title.cardTitle{
  .title{
    color: red
  }
}
```
But by doing this, I get this error that

> 'title' is not defined no-undef

Am I supposed to import something in my scss file?
Please suggest what should be done here!Thanks.

**Comment by mihiramin89** [comment]
@aayushis12 title is an attribute on your CardTitle element. If you want to use the .title css selector you need to add className='title' to the cardTitle element.

**Comment by aayushis12** [comment]
you mean I should remove className=card-title and replace it with title? @mihiramin89

**Comment by mihiramin89** [comment]
yes your component should look like this. 

````
<Card style={{width:'350px'}} theme={theme}>
	<CardMedia aspectRatio="wide" image=""/>
	<CardTitle title="Avatar here" className="title"/>
</Card>
````

Not sure if your css will work. I would just try it out and check. Also the inspector tool is a good tool to use to debug styling issues. However, the below code is what i have done in the past. 

````
[data-react-toolbox='card'] {
    .title {
       color: red;
    }
}
````

**Comment by peterdivvito** [comment]
The problem is that javascript doesn't allow - in a variable name. `theme.card-title` is not valid javascript. The interpreter thinks you are trying to do `theme.card - title` and `title` doesn't exist.

I believe CssModules might change classes that have dashes in them to camel case. Look into that, or just change your SCSS classname to implicitly be  camel case.

**Comment by rubenmoya** [comment]
Your card:
```
<Card theme={theme}>
  <CardMedia aspectRatio="wide" image="" />
  <CardTitle title="Avatar here" />
</Card>
```

Imports needed:
```
import { Card, CardTitle, CardMedia } from 'react-toolbox/lib/card';
import theme from './assets/theme/theme';
```

theme.css (i could be wrong here, did it from the top of my head)
```
.cardTitle {
  .title{
    color: red
  }
}
```

**Comment by ankibalyan** [comment]
@rubenmoya I'm not getting `.tittle` class under the `.cardTitle` element, instead getting some randomly generated classes like below.

    <div data-react-toolbox="card" class="_8pay8" style="width: 350px;">
      <div class="_1dU3o _1RHxe cardTitle">
        <div data-react-toolbox="avatar" class="_3OjJz"><img alt="" class="_2Ueo9" src="https://placeimg.com/80/80/animals"></div>
        <div>
          <h5 class="_3qCP3">Avatar style title</h5>
          <p class="_3p3mO">Subtitle here</p>
        </div>
      </div>
    </div>

**Comment by ankibalyan** [comment]
@mihiramin89 do you have any idea, why I'm not getting the actual class names in the compiled component?

**Comment by rubenmoya** [comment]
The randomly generated classes are because of css modules, that's hoy it's supposed to work

**Comment by ankibalyan** [comment]
ok! Then should I target the subtitle field with `_3p3mO` class name, or it justs works with scss theme only. I've integrated scss with  CRA and `node-sass-chokidar`.

**Comment by mihiramin89** [comment]
@ankibalyan can I see the code that you have? I would try your code in the playground for react-toolbox.. when i added a className to the CartTitle it showed up when i inspected the element. http://react-toolbox.com/#/components/card

**Comment by ankibalyan** [comment]
@mihiramin89 This is what I'm trying here, It seems It doesn't work without including `scss`. 

    import React, { Component } from 'react';
    import ThemeProvider from 'react-toolbox/lib/ThemeProvider';

    import theme from './assets/react-toolbox/theme'
    import Card from 'react-toolbox/lib/card/Card';
    import CardTitle from 'react-toolbox/lib/card/CardTitle';

    import './assets/react-toolbox/theme.css'
    import styles from './App.css';

    const App = ({ children }) => (
      <ThemeProvider theme={theme}>
        <div>
        <Card style={{width: '350px'}} theme={styles}>
          <CardTitle
            avatar="https://placeimg.com/80/80/animals"
            title="Avatar style title"
            subtitle="Subtitle here"
            className="cardTitle"
          />
        </Card>
        </div>
      </ThemeProvider>
    );

    export default App;


then `App.scss` which compiles to `App.css` with `node-sass-chokidar`

    .cardTitle {
      align-items: center;
      display: flex;

      & .title {
        font-size: calc(2 * var(--unit));
        font-weight: 500;
        letter-spacing: 0.02em;
        line-height: 1;
        margin: 0;
        padding: 0;
      }
      & .subtitle {
        color: blue;
    }
    }

    [data-react-toolbox='card'] {
      .title {
        color: red;
      }
    }

**Comment by ankibalyan** [comment]
@mihiramin89 It shows the main class `cardTitle` which I added but not the nested classes for `title` and `subtitle`.

**Comment by mihiramin89** [comment]
try the below selectors instead of .title & .subtitle

[class*='theme__title']
[class*='theme__subtitle']

**Comment by mihiramin89** [comment]
or you could just use the `h5` selector and the `p` selector inside your .cardTitle selector.

**Comment by ankibalyan** [comment]
yep, I can use h5 and p tags, but those selectors has least priority.

**Comment by ankibalyan** [comment]
@mihiramin89 @rubenmoya thank you for all your support. I was able to dig further and resolves the problem.

While defining the stying, I'd have to provide the class names in theme param, and define those classes separately. I was doing this as combined stuff. lame :/

    <CardTitle
        avatar="https://placeimg.com/80/80/animals"
        title="Avatar style title"
        subtitle="Subtitle here"
        theme={{cardTitle: 'cardTitle', subtitle: 'subtitle'}}
      />
    </Card>

This works like a charm :)
