### ISSUE TITLE
react-toolbox v1 continued support, react 16 ?

### ISSUE THREAD

**Issue by bionikspoon** [react-toolbox/react-toolbox#1703]
Has v1 been abandoned?  

Has there been any conversation about continuing to support v1 while v2 is in beta ?   V1 is falling behind on those essential peerDependencies -- specifically the current version of react.

**Comment by rubenmoya** [comment]
Right now we're focusing on finishing the `v3` (agnostic-typescript branch), PRs solving issues in `v1` and `v2` are much appreciated, but there is no 'official' work in `v1` and `v2` anymore.

**Comment by landabaso** [comment]
So, can we already jump to agnostic-typescript? If so, could you publish it to npm?
Any consideration to be taken to port our stuff from beta2?
Thanks!

**Comment by tech4him1** [comment]
@rubenmoya Is there any status update that we can follow for v3?

**Comment by bionikspoon** [comment]
Updated v1 to be react16 compatible.

https://github.com/react-toolbox/react-toolbox/compare/1.3.4...bionikspoon:mp_react_16

I don't know your release process.  It has green tests.  And I'm going to test it in a private app at work.

Note:  Had to update `react-css-themr`.  Should probably wait until they merge my changes.  Can follow that conversation here: https://github.com/javivelasco/react-css-themr/issues/75

**Comment by bionikspoon** [comment]
Updates:

I published a built version of this here: https://github.com/bionikspoon/react-toolbox/tree/react_16_build

In the short term, my team will be using this.  The app is on a private repo, but I'll keep this thread posted on it's journey to be used in production:

- [x] open pr
- [x] review app open, properly builds, tests pass, and passes a basic click test
- [x] team signoff
- [ ] qa signs off
- [ ] production release 🥇 

```json
//package.json
{
  "dependencies": {
    "react-toolbox": "git://github.com/bionikspoon/react-toolbox.git#react_16_build"
  }
}
```

List of components we use:

- Button
- Checkbox
- Dialog
- Dropdown
- Input
- ProgressBar
- Radio
- Tabs
- TimePicker
- Tooltip
- also, we use a ton of `themr` features.

**Comment by theskillwithin** [comment]
@bionikspoon 
```
ERROR in ./node_modules/react-toolbox/lib/date_picker/Calendar.js
Module not found: Error: Can't resolve 'react-transition-group/CSSTransitionGroup' in '/Users/aupeterson/Projects/ansible-playbooks/marketplace/git-repos/marketplace/Apps/v2/node_modules/react-toolbox/lib/date_picker'
 @ ./node_modules/react-toolbox/lib/date_picker/Calendar.js 17:26-78
 @ ./node_modules/react-toolbox/lib/date_picker/index.js
 @ ./node_modules/react-toolbox/lib/form/index.js
 @ ./node_modules/react-toolbox/lib/index.js
 @ ./app/components/WpLive/view.js
 @ ./app/components/WpLive/index.js
 @ ./app/builds/ssr/Wplive.js

ERROR in ./node_modules/react-toolbox/lib/time_picker/Clock.js
Module not found: Error: Can't resolve 'react-transition-group/CSSTransitionGroup' in '/Users/aupeterson/Projects/ansible-playbooks/marketplace/git-repos/marketplace/Apps/v2/node_modules/react-toolbox/lib/time_picker'
 @ ./node_modules/react-toolbox/lib/time_picker/Clock.js 17:26-78
 @ ./node_modules/react-toolbox/lib/time_picker/TimePickerDialog.js
 @ ./node_modules/react-toolbox/lib/time_picker/TimePicker.js
 @ ./node_modules/react-toolbox/lib/form/Form.js
 @ ./node_modules/react-toolbox/lib/form/index.js
 @ ./node_modules/react-toolbox/lib/index.js
 @ ./app/components/WpLive/view.js
 @ ./app/components/WpLive/index.js
 @ ./app/builds/ssr/Wplive.js
```

**Comment by theskillwithin** [comment]
@bionikspoon 
https://github.com/reactjs/react-transition-group/blob/master/Migration.md
could you update to add this?

**Comment by Ulyanich-v** [comment]
guys, any activity here? Does anyone know, is react toolbox team going to make v1 branch compatible with  react 16? Or may be release v2 version with react 16?
@bionikspoon @rubenmoya

**Comment by jackjwilliams** [comment]
@bionikspoon Thank you for that! I've forked your v16 branch, could you give any insight into how you setup your webpack or do style imports? 

I tried to just render a basic AppBar, but it's always completely unstyled. It's inlining some styles, but react-toolbox has undefined styles

```
<header class="" data-react-toolbox="app-bar">
  <button class=" undefined" type="button" data-react-toolbox="button">
    <span data-react-toolbox="font-icon" class="material-icons">menu</span>
  </button>
  <h1 class="">Test Application</h1>
</header>
```

![image](https://user-images.githubusercontent.com/1746015/33001740-6ab36cee-cd75-11e7-80e0-8c3f72fdce3e.png)

**Comment by rubenmoya** [comment]
There is a PR open for React 16 in `v1` https://github.com/react-toolbox/react-toolbox/pull/1719 just waiting for the merge. Also, keep in mind that `v3` with agnostic components is around the corner.

**Comment by Ulyanich-v** [comment]
v3 with agnostic components how close to release?

**Comment by rubenmoya** [comment]
Closing in favor of #1715
