### ISSUE TITLE
Upgrade to v2 guide

### ISSUE THREAD

**Issue by theskillwithin** [react-toolbox/react-toolbox#1705]
Could you create an upgrade guide from RT v1 to RT v2?

I have quite a large project and want to keep everything else in place and working and be able to upgrade to RT v2 so I can update to react 16.

**Comment by theskillwithin** [comment]
https://gist.github.com/theskillwithin/a211ec040605986c24407cd609ae5583#file-webpack-config-babel-js-L122

**Comment by theskillwithin** [comment]
attempting to fork the 1.3.4 version and run proptypes update script
https://github.com/theskillwithin/mojo-rt

https://blog.discordapp.com/lessons-from-migrating-a-large-codebase-to-react-16-e60e49102aa6

**Comment by that1matt** [comment]
There is an upgrade guide in the README.md.

Direct Link: https://github.com/react-toolbox/react-toolbox/wiki/Migrating-from-version-1.3-to-2.0
