### ISSUE TITLE
TimePicker component size is too big on Desktop

### ISSUE THREAD

**Issue by Altiano** [react-toolbox/react-toolbox#1710]
![screenshot from 2017-10-10 18-19-34](https://user-images.githubusercontent.com/8316282/31381674-cc8a5520-ade7-11e7-9274-72690d72e134.png)

it will get even worse if the width of viewport smaller, say : 1360x500

**Comment by rubenmoya** [comment]
Are there any steps to reproduce it? It's not happening on the playground so my guess is that some styles are being overwritten... but without more information, it's hard to know what's going on.
