### ISSUE TITLE
Dropdown source item set as disabled throws warning

### ISSUE THREAD

**Issue by mateoKaradza** [react-toolbox/react-toolbox#1714]
Dropdown component throws warning when one of the source items has property disables as true.
When item is set as disabled, it works properly, but because of the PropTypes it throws a warning in console.

https://github.com/react-toolbox/react-toolbox/blob/dev/components/dropdown/Dropdown.js#L183

```
 Expected `onClick` listener to be a function, instead got a value of `boolean` type.
    in li (created by Dropdown)
    in ul (created by Dropdown)
    in div (created by Dropdown)
    in Dropdown (created by ThemedDropdown)
    in ThemedDropdown (created by Select)
```

**Comment by pnachum** [comment]
Is there any update on this issue?
