### ISSUE TITLE
common.scss overrides

### ISSUE THREAD

**Issue by wrench7** [react-toolbox/react-toolbox#172]
Using react-toolbox with the common.scss file removes the webkit scrollbar.

There's  a lot of other stuff going on in the commons.scss file that changes the styling of the pages that I'm trying to use react-toolbox on (primarily around font-size). Is there anyway to namespace the changes that are in commons.scss file so it just affects react-toolbox components?

**Comment by javivelasco** [comment]
Hi @wrench7 !!

React Toolbox includes this `commons` to do a reset in the document but if you don't want it, you can avoid including it. There are a couple of things to take into account:

- Toolbox uses `1rem` as sizing unit and we set in commons the `font-size` to `10px` which allows to use rems as they were pixels. For example, `1.6rem` would be `16px`. This allows you to scale the content either setting a different base font size or changing the `$unit` to something else in your stylesheet. You are free to avoid commons but you'd need set the `$unit` accordingly. A good example would be to set in your customization sass file `$unit` to `10px`. 
- There are some general resets that are included in commons but not in components stylesheets. To keep DRY we are not setting a reset for lists in dropdowns for example. If you avoid commons you have to do it yourself. We took this decision for now but we are open to change, for example using composes with some common resets would be a solution.

We are having a lot of people who want to avoid commons inclusion so probably we will work on a version or option that skips resets. That's for the second point, the first one should be kept to be flexible about sizing.

**Comment by wrench7** [comment]
Thanks for the incredibly swift reply!

Ideally react-toolbox should be able to be dropped into an existing app and it should just work, without affecting the styles in the app. I'm very interested in using the framework, but at the moment it seems to be styling other elements on the page which I wouldn't expect to be happening.

I've been fiddling around with the font-size and $unit properties but can't seem to get it working so that both my styles and the ones in Toolbox sit side by side.

I'll continue to play with things and report back here if I fix my problem.

**Comment by wrench7** [comment]
I can see a font-size 62.5% in the html element and that's being overriden straight away by font-size: 1.6em in the body element. I'm a bit confused as you mentioned that you use font-size 10px in commons but I can't see that anywhere?

I'm not sure how to apply the $unit variable you're suggesting. If I set it in a file that I import, there's no way to override the unit settings that the Toolbox components get (from their _base.scss and then _globals.scss imports).

Is anyone else using this on projects that have other CSS libraries being used (for instance flexboxgrid) ?

**Comment by wrench7** [comment]
I'm also noticing that without the CSS styles from the Toolbox app component, the ripple effects on buttons don't work

**Comment by javivelasco** [comment]
Did you wrap the app with `App` component?

**Comment by wrench7** [comment]
I did in the end - it might be an idea to update the docs if that's required to get things like ripple effects working properly.

**Comment by wrench7** [comment]
I've distilled my issue down to the fact that the common.scss file sets the html font-size to 62.5% and the flexboxgrid library I'm using bases it's measurements on the root font-size being 100%.

I can't get the $unit value to have any effect (due to the previously mentioned issue above) so am at a lose as to who to integrate this framework in with other's that rely on a different root font-size setting being set.

Any suggestions/help would be appreciated.

**Comment by javivelasco** [comment]
Sorry, did not have too much time to answer. Browsers has a 16px size by default so 62.5% makes 10px default to use as base for rems. You can provide at the top of your `theme.scss` a `$unit: 10px;` and this should work.

I'll do some tests during the weekend and migrate the globals to locals with `composes` keyword from CSS Modules.

**Comment by wrench7** [comment]
Yep, I'm across the rem side of things now (haven't used that too much in the past) but believe the issue now lies around passing the $unit variable to the global.scss file and it being reliably passed down to all of the Toolbox components.

For starters, the _globals.scss file doesn't have ```!default``` after the $unit declaration so I can't override it.

Doing a simple test (setting the font-size of 100% in the Toolbox spec site) and then simply editing $unit: 0.625 doesn't actually uniformly scale things.

**Comment by javivelasco** [comment]
Ok that's the problem then. You can't override the unit.
It will be fixed asap, I'm labeling this as bug!

**Comment by ro-savage** [comment]
Hey guys,

Any update on this? 

I get the same issue with html `{ font-size: 62.5% }` reset overwriting all my other font styling, and removing it / changing back to 100% breaks all the react-toolbox components.

It feels like it should be possible to just set all react-toolbox component to be based on 10px (62.5%) fonts rather than overriding the entire site to start using 10px base fonts.

**Comment by javivelasco** [comment]
Yeah, you can always add a PR to set a default flag in the default so it can be overriden.
Only you guys using the components all able to figure out all these improvements :)

**Comment by javivelasco** [comment]
Please check #498

**Comment by javivelasco** [comment]
Since this changed a lot I think issues listed here should be solved!
