### ISSUE TITLE
Styled-Components migration

### ISSUE THREAD

**Issue by Secretmapper** [react-toolbox/react-toolbox#1722]
@javivelasco wrote updates on twitter and on some issues in this repo about switching the postcss to styled-components. Have there been any updates on this? There doesn't seem to be any issues that is tracking this here.

I'd love to know if this is something that's still in the roadmap, and/or if there's anything contributors can help with on the styled-components migration.

This is a big dependency on our project and I'd be happy to pitch in on the styled-components migration.

**Comment by oliviertassinari** [comment]
@Secretmapper As far as I know, you can find the effort on the [agnostic-typescript](https://github.com/react-toolbox/react-toolbox/commits/agnostic-typescript) branch.

**Comment by dziamid** [comment]
@oliviertassinari there does not seem to be any progress on `agnostic-typescript` branch. Has the migration been abandoned?

**Comment by oliviertassinari** [comment]
@dziamid I don't know.

**Comment by rubenmoya** [comment]
The migration is still ongoing, Javi is pretty busy lately but we'll keep working on it!
