### ISSUE TITLE
Input field label misbehaves when field is in error state.

### ISSUE THREAD

**Issue by MrJoy** [react-toolbox/react-toolbox#1727]
http://react-toolbox.com/#/components/input

1. Go to the last input field in the playground.
1. Enter a value.
1. Move focus out of the field.

Note that the label sweeps down over the input area.

**Comment by mogadanez** [comment]
its same even with empty value
  <Input type='text' placeholder="test" label='error' error="Some errror" />

=>


![image](https://user-images.githubusercontent.com/790307/33762036-694ed74a-dc0b-11e7-90b8-906a6f6c1de0.png)

**Comment by rubenmoya** [comment]
That's just a problem with the playground, we're not passing a value to the `Input` component so [this check](https://github.com/react-toolbox/react-toolbox/blob/dev/components/input/Input.js#L183) fails and the necessary css class is not applied, handling the input change and adding a value fixes it:

```
<Input
  type='text'
  value={this.state.withError}
  name="withError"
  onChange={this.handleChange.bind(this, 'withError')}
  label='error'
  error={<span>Error!! <a href="#!"
  onClick={e => { e.preventDefault(); console.log('some help'); }}>?</a></span>}
/>
```

We need to fix the documentation [here](https://github.com/react-toolbox/react-toolbox/blob/dev/docs/app/components/layout/main/modules/examples/input_example_1.txt).
