### ISSUE TITLE
What's wrong with the react-toolbox home page?

### ISSUE THREAD

**Issue by AOHUA** [react-toolbox/react-toolbox#1731]
I'm was planning to use react-toolbox on a new project. But I cannot see any examples and usages on the home page anymore. Where else can I find it? Thank you!

**Comment by weizlini** [comment]
looks like the domain expired ?

**Comment by chadfawcett** [comment]
For anyone needed access, I've deployed the gh-pages branch to Netlify https://peddler-jam-26368.netlify.com

**Comment by mgcrea** [comment]
@rubenmoya Any reason you did not setup a fallback on http://react-toolbox.github.io/react-toolbox? Would seem to be the most quick and easy fix to address this, update the README while the .com issue is settled.

**Comment by chadfawcett** [comment]
@mgcrea I can't answer why it hasn't been yet, but there is a PR fixing this if you wanted to give it a :+1: https://github.com/react-toolbox/react-toolbox/pull/1732

**Comment by tconroy** [comment]
Seems odd maintainers haven't set the domain to auto-renew? 🤔

**Comment by javivelasco** [comment]
@tconroy Turns out that @soyjavi has ownership of the original www.react-toolbox.com and I couldn't make him renew/transfer the domain so we'd rather migrate to a new one I can be responsible of. Now you can access react-toolbox.io

**Comment by javivelasco** [comment]
@chadfawcett Thank you for publishing meanwhile :)

**Comment by tconroy** [comment]
@javivelasco thank you for resolving this! 👍
