### ISSUE TITLE
Cannot build docs

### ISSUE THREAD

**Issue by chadfawcett** [react-toolbox/react-toolbox#1733]
Since the website is down (#1731) I decided to setup a copy locally. I ran through the steps under [Authors and Contributors](https://github.com/react-toolbox/react-toolbox#authors-and-contributors). I receive various errors:

I first ran it with `node v8.4.0` and received errors when attempting to run `npm start`.

I then tried using `node v4.8.5` and then `node v4.2.1` and both result in an error when attempting to `npm install` from the root directory.

**Comment by chadfawcett** [comment]
For anyone needed access, I've deployed the `gh-pages` branch to Netlify https://peddler-jam-26368.netlify.com

**Comment by rubenmoya** [comment]
Thank you! :)
