### ISSUE TITLE
react-toolbox domain is down (http://react-toolbox.com/)

### ISSUE THREAD

**Issue by deSargeSoftware** [react-toolbox/react-toolbox#1734]
http://react-toolbox.com/ is down: This Domain Name Has Expired. Could you please renew it :)? Thanks

**Comment by vampxlr** [comment]
Eagerly waiting for it to come up live again.

**Comment by roadev** [comment]
It will be awesome if you move to Github Pages.

**Comment by deSargeSoftware** [comment]
Until is up, you can use this one: https://peddler-jam-26368.netlify.com/#/ (I received as well).

**Comment by neoromantic** [comment]
Funny that how that is happening every year :)

**Comment by drunkengranite** [comment]
bump

**Comment by mgcrea** [comment]
Duplicate of #1731

**Comment by javivelasco** [comment]
react-toolbox.io is up now!

**Comment by CASandmann** [comment]
Why did you guys switch to a .io domain?  Not that it really matters in the long run, but all old links to the docs are now broken and the new location doesn't show up on a Google search while the old (broken) one still does.

**Comment by javivelasco** [comment]
Because @soyjavi has ownership of the `.com` and it was impossible to reach him or to make him renew the domain so I had to switch to keep ownership of the whole thing. The docs and everything will be updated during the next days, sorry about it
