### ISSUE TITLE
Issue in using nested object in usermodel

### ISSUE THREAD

**Issue by vikaskyadav** [react-toolbox/react-toolbox#1735]
I have been trying to use table component and now I have to use nested object inside the usermodel. Can anybody help me with that?

**Comment by 3af** [comment]
Hey,

you'd improve chance of someone helping you if you provided more details. Code example that is easily runnable is good start. Try to provide as much as possible helpful details.

Same applies for #1736.

**Comment by amy-butz** [comment]
I also need to solve this issue. The object that is my source for the table looks like this:

`{
"id": "5a3814f79b0b017748d4136b",
"name": "Example Building",
"address": {
       "streetNumber": "123",
       "streetName": "Anywhere Dr.",
       "suite": "101",
       "city": "Anytown",
       "state": "US",
      "zip": "12345"
                 },
"isActive": true
}`

So how do I access, for example, the city field, which is nested inside the address object, to make them part of the model? The following code does NOT work:

`const BuildingModel = {
            name: {type: String, title: "Name"},
            city: {type: String, title: "City"},
            isActive: {type: Boolean, title: "Active"}`

**Comment by 3af** [comment]
One simple solution that just came to my mind is to change (flatten) the source.

@amy-butz in your case
```
{
  "id": "5a3814f79b0b017748d4136b",
  "name": "Example Building",
  "city": "Anytown",
  "isActive": true
}
```
should work for the model you used above.

I think this is general solution for this problem - just change the data in your selectors.
