### ISSUE TITLE
Inside head tag, <style> tags including --palette variables.

### ISSUE THREAD

**Issue by arikanmstf** [react-toolbox/react-toolbox#1739]
Hello, when I use RT 2 Beta, There are so many <style> tags inside the <head> . I assume somehow webpack imports theme.css files. Is that really necessary to include them. How to avoid ? Because it slows the app.

Version info:

react-toolbox-themr: 1.0.2
react-toolbox: 2.0.0-beta.12
webpack: 3.3.0
react: 15.6.1

Project available at: https://github.com/arikanmstf/mylibrary

Screenshot:

<img width="357" alt="screen shot 2017-11-03 at 20 16 27" src="https://user-images.githubusercontent.com/13220774/32386931-876c32b4-c0cb-11e7-800c-b74d4140e2f4.png">

<img width="361" alt="screen shot 2017-11-03 at 20 16 17" src="https://user-images.githubusercontent.com/13220774/32386932-8b22c954-c0cb-11e7-8118-1d07f0b0e9e3.png">

**Comment by arikanmstf** [comment]
I tracked the commits, and I can say that the bug comes from
`<Link>` component.
Whenever I import the `<Link>` component like `import Link from 'react-toolbox/lib/Link'` includes style tags.

**Comment by arikanmstf** [comment]
When I change the `import Link from 'react-toolbox/lib/link ` to `import Link from 'react-toolbox/lib/link/Link` the error gone.
Problem is, that error happens at all of the components imported without theme.
Like `import { Card, CardMedia, CardTitle, CardActions } from 'react-toolbox/lib/card';`
or
`import { Table, TableHead, TableRow, TableCell } from 'react-toolbox/lib/table';`

There is definetly a bug

**Comment by 3af** [comment]
Hey,

I cannot reproduce this in my project. When I import Link like you described I don't see any additional style element in my head.

![obrazek](https://user-images.githubusercontent.com/33279089/32495456-ff00ca36-c3c5-11e7-92ec-1114b62d357a.png)

From quickly looking into your webpack config it seems like this is because you use [style-loader](https://webpack.js.org/loaders/style-loader/).

If you don't want to see so many style elements take a look at https://github.com/webpack-contrib/extract-text-webpack-plugin. From the picture above you can see I have only one main CSS included.

**Comment by arikanmstf** [comment]
Yes because I've fixed my bug already.
Did you try include Links like 
`import Link from 'react-toolbox/lib/link `
And check my webpack config carefully, I already use Extract text plugin:
https://github.com/arikanmstf/mylibrary/blob/master/webpack.config.js
For output of the project see: http://mustafaarikan.net/mylibrary/
@3af

**Comment by jamesmarrs** [comment]
hey @arikanmstf I had similar issues with a lot of css being injected I didnt use (developer tools ran so slow, etc). Its highly dependent on how your webpack is configured. In addition to extract text plugin, I had to use the  postcss-cssnext library. This cleaned up most of the style issues for me. Unfortunately I dont use the themr to theme my project, so i cant say much about that.

**Comment by 3af** [comment]
So you fixed the problem? How? Maybe someone else will find it useful.

Yes, I included the Link like that and I don't see any additional `style`s.

**Comment by arikanmstf** [comment]
As I mentioned on previos comment,

> When I change the `import Link from 'react-toolbox/lib/link ` to `import Link from 'react-toolbox/lib/link/Link` the error gone.
