### ISSUE TITLE
Autocomplete Enhancements

### ISSUE THREAD

**Issue by nathanmarks** [react-toolbox/react-toolbox#174]
This issue is to track enhancements for autocomplete I am currently working on. This includes solving #161, #170  and #138 

I've tried using the autocomplete and found some issues.
1. Doesn't implement the most prominent spec examples. Should focus on providing the user with the tools needed to implement common use cases.
2. Cannot be used easily in complex applications (compatible with a small number of basic use cases).
3. Does too much internally in a single component with little flexibility to show for it

Goals:
- [ ] Solve #161, #170 and #138
- [x] Allow you to connect any type of data source or custom query
- [x] Enable the direct use of `<Input/>` and `<input>` with full access to their component API.
- [x] Can be easily used for everything in the spec such as the raised boxes, search bars, appbar search fields, full width searches on mobile when responsive styling is implemented.
- [x] Support for autocomplete item templating.
- [ ] Still have the option to use chips, but with greater control.

This means that all input related styling/settings props can be passed to that component as described in the documentation. That way the autocomplete implementation is also more portable and focuses on providing the elements unique to autocomplete.

**Comment by javivelasco** [comment]
Awesome @nathanmarks

**Comment by soyjavi** [comment]
Great!!

**Comment by kagux** [comment]
I've came across multiple situations where I need to customize selection list. In fact, because we use Flux, it would be much easier to have autocomplete input separated from selection. We ended up rendering custom selections using data from stores, not from autocomplete component. 

I wish there were 3 components: Autocomplete, Chip and maybe MultiSelect to combine them. That way I could take Autocomplete, connect it to store and use a List to render selection.

Anyways, @nathanmarks do you still have time to work on this issue? Is there any way I could help?

**Comment by nathanmarks** [comment]
@kagux Yeah I already started on this and actually just built a react autocomplete out the other day for work that uses redux that I intend to port some of the functionality from.

**Comment by acornejo** [comment]
@nathanmarks do you have a branch that you would like to share? I've run into some problems with autocomplete myself, and I would rather reuse someone elses' work instead of reimplementing it.

**Comment by javivelasco** [comment]
I'm probably working on this too in a week or so. It would be cool to open a branch here so more people can contribute

**Comment by nathanmarks** [comment]
@javivelasco @acornejo I will definitely try to push a branch then this week! I just want to clean some things up first before passing the baton.

**Comment by javivelasco** [comment]
:+1: !

**Comment by nathanmarks** [comment]
@javivelasco @acornejo 

Hey guys, I rebased my branch and assessed my current progress. I have a few things I want to finish up with it. If you can wait -- give me until Monday to wrap up the component.

**Comment by javivelasco** [comment]
Sure, take the time you need :)

**Comment by nathanmarks** [comment]
I got sidetracked this weekend and ended up spending my free time digging into jsdoc es6 functionality. So gonna need a few more days to wrap this up :dancers:

**Comment by javivelasco** [comment]
No problem! :)

**Comment by felipeleusin** [comment]
Hi folks, would love to help with this. Is there a roadmap for the autocomplete or a PR that needs help?

**Comment by javivelasco** [comment]
@nathanmarks should have a branch with it!

**Comment by nathanmarks** [comment]
@javivelasco Haven't had time to work on this at all since the last time -- I've had to shift my attention for now over to something that I can use for a project I'm working on. There wasn't enough activity over here to get some things done in time, day job work has been crazy. (and also for the other reason I mentioned to you on discord)

**Comment by javivelasco** [comment]
Ok, np nathan :)

**Comment by felipeleusin** [comment]
Ah ok. I actually used a lot of https://github.com/JedWatson/react-select/ and I think it has a great API for this the only issue is applying the material design guidelines to it but integrating one of those two options might be better than rolling a self made autocomplete

**Comment by javivelasco** [comment]
@felipeleusin we should open a PR and work on this enhancements from there. There are a lot of issues related to the Autocomplete and react select has the perfect API to take.

**Comment by renato** [comment]
Anyone working on this? The checked items in OP, like templating and custom querying, are finished somewhere?

**Comment by felipeleusin** [comment]
I never got to this... did some digging around and got stuck trying to customize react-select to the material design guidelines. I think maybe porting some (all?) of the code might be easier... the most glaring needs I have with autocomplete is:

* Custom sources, value key and label key
* Async loading (passing a function to loadOptions)
* Custom option renderer, custom value renderer

**Comment by danpoz** [comment]
Just being able to get the value of the text field if an item not in the data source is entered would be huge.

Right now if I have a list of ["Apples", "Oranges", "Pears"], and select "Apples" then enter "Bananas", I can only get "Apples" back.

**Comment by oscar-g** [comment]
I have a quick suggestion...I've been using [react-autosuggest](https://github.com/moroshko/react-autosuggest) for a while and I really like the API for the component.  A lot of the things I like about that module have already been mentioned on this thread.

However, it would be nice if Autocomplete could accept custom values...right now it is kind of 'strict' in the sense that only the values in `props.source` are allowed.  @danpoz mentioned a case where you have Apples, Oranges, and Pears in the list, but the user may want to input Bannanas.  It would be useful to have a prop that enables these custom values...kind of like 'tagging' a blog post, for example.

**Comment by duhseekoh** [comment]
Really, all we need is:
1. to have this act just like an input, any value can be entered
2. a function `onKeyPress(value)`. Then I could make an ajax call with that value to update the `source` array.
3. clicking on an item in the array also updates the value (as it currently does, no changes here)

**Comment by javivelasco** [comment]
I'm currently working with React in my main work and probably I'll have to write an autocomplete soon. If nobody can provide PRs improving this, I guess I'll get real feedback about usage inside a real world redux app and bring it here

**Comment by duhseekoh** [comment]
I went through several react auto complete components today. I've been looking for a non obtrusive implementation. One that simply suggests values, but allows the user to enter anything they want. Also, I'm using redux-form and storing all of my state in redux.

Just one mans opinion, but thought it would be good to get my thoughts down while they're fresh.

**react-toolbox autocomplete**
- Pro: Fits with the rest of the toolbox (styling, api, etc...)
- Con: Limits the 'value' property to 
- Pro: I can decide how my options get populated and the component just keeps rendering that array
- Con: Stores an internal query value for its input state. This isn't redux friendly.

**react-select**
- Pro: Seems to do everything
- Con: Tries to do everything
- Pro: There are a lot of people using it
- Con: Doesn't do everything. Again, suffers from the toolbox con where the value must be one of the suggested options
- Con: Has a bunch of preconceived styling notions built in, so going outside that is a mess. What's with the auto expanding input when typing? Also seems to mix inline styles with regular css

**react-autosuggest**
- Pro: Doesn't limit the input value to one of the suggested options. Bingo!
- Pro: Flexibile. Not all the bells and whistles of react-select, but those were just getting in my way
- Pro: No assumption how how your data comes in. Not on the shape or on where it's coming from.
- Con: A lot of required fields
- Con: Lot's of churn, the latest version seems to be stable though

**Comment by oscar-g** [comment]
@duhseekoh that's a very informative comparison. Do you think it would be
wise to depend on one of these in react-toolbox?

**Comment by javivelasco** [comment]
Yeah, maybe we can just add style or something but in the best case we should reuse the `Input` as well

**Comment by duhseekoh** [comment]
I think it makes sense to integrate with something like react-autosuggest, or at least be heavily inspired by its api. 

I imported the CSS modules from the Input component and applied them to the relevant elements on the react-autosuggest component (you can pass the input of react-autosuggest all of its properties) and had it pretty much looking like a toolbox Input element (sans the bar animation when focusing).

**Comment by oscar-g** [comment]
@duhseekoh: I tried that as well and got pretty OK results. On a slightly-undelated note, regarding react-redux form, I was able to make a custom `Field` class that correctly mapped the value on `react-toolbox` Input.

@javivelasco: I think we can make a few changes, drawing from some of the other autosuggest components, that should improve toolbox Autocomplete.  One of my requests is to allow custom values, like I stated earlier.  Another good improvement should be to make Input have the same api as the native input.

**Comment by duhseekoh** [comment]
That's fair. Some modifications to the current toolbox autocomplete impl is probably a good path forward.

**Comment by oscar-g** [comment]
I can dig into the code this weekend and we come up with a more specific plan.

**Comment by gregegan** [comment]
Any progress on a `onKeyPress` callback for retrieving a new source? Looks like a callback should be added to `handleQueryKeyDown` in Autocomplete.js

**Comment by javivelasco** [comment]
That should be easy to do. I'm writing a new autocomplete during next week probably and I have a way better approach. This should come soon

**Comment by kanzelm3** [comment]
@javivelasco Would love to get a status update seeing as it has been a few months since the last post.

**Comment by javivelasco** [comment]
Of course. I'm currently planning a lot of changes for most of the components. Some of them: `Dropdown`, `Table`, `List`, `Menu` and `Autocomplete`. But there is a blocking issue right now:  PostCSS migration.

React Toolbox 2.0 is going to get rid of SASS so every style has been rewritten. We still need to update the documentation but there is already a beta release so you can start trying it out. Once that's done we can start adding new components and making this better.

Summarizing: still in mind but blocked until an official 2.0

**Comment by Doff3n** [comment]
Autocomplete should IMO follow the same scheme as the Dropdown with label and values, it is currently inconsistent using a map?

**Comment by wpanas** [comment]
It's nearly a year since this issue was reported and we still has no solution. I want to know what can we do to help you guys with `Autocomplete`. I see many suggestion on how this should be handled, but no conclusions. Maybe for starters, you can merge #991

**Comment by javivelasco** [comment]
The real blocking @wpanas now is #666. The only thing remaining to merge this branch is the build system. I have some drafts on my local and I'm going to work on this during the week so we can move on with new components and better implementations. Still if you want to work directly on the PostCSS branch it would be cool. I would change a lot and also I have things in mind like:

- Separating selection rendering from the component
- Allow to pass a predicate to match suggestions
- Get rid of maps in the internal implementation
- Allow to pass options using children instead of passing a source
- .... 

I have an implementation in another project indeed and I plan to work on both this and the Dropdown after the PostCSS branch is fully merged
