### ISSUE TITLE
What is happening with react-toolbox

### ISSUE THREAD

**Issue by TimoRuetten** [react-toolbox/react-toolbox#1748]
Hey!

I am wondering whats happening with react-toolbox. The domain is unreachable, there are 47 pull requests, last commits are long time ago etc. ...

Maybe the owner isnt interested anymore to maintain this project ? Any infos ?

**Comment by miguel-orange** [comment]
https://github.com/react-toolbox/react-toolbox/issues/1742#issuecomment-342095270

**Comment by tech4him1** [comment]
Latest commit was October 6th: https://github.com/react-toolbox/react-toolbox/tree/agnostic-typescript

**Comment by javivelasco** [comment]
https://github.com/react-toolbox/react-toolbox/issues/1742#issuecomment-344006400
