### ISSUE TITLE
So huge

### ISSUE THREAD

**Issue by markolofsen** [react-toolbox/react-toolbox#1752]
The size of my bundle is 6 mb. It's normal? How to fix it?

**Comment by hansena** [comment]
6mb from react-toolbox?? Take a look at the “Importing components“ section of the readme, should help you sort it out

**Comment by markolofsen** [comment]
I have few pages and in each page I use:
```
import React, {Component} from 'react';
import {withRouter} from 'react-router';
import {connect} from 'react-redux';
import {Layout, Panel, NavDrawer, Sidebar} from '../components/layout';
```
It's normal practice or I have to include this once?

**Comment by markolofsen** [comment]
Also, by default bundle with "react-toolbox" — 6.3 Mb.

**Comment by javivelasco** [comment]
Try to require components directly separated. Probably you are requiring from indexes making the bundle huge since the whole library is going to be included instead of just what you actually use.

**Comment by hansena** [comment]
@markolofsen here is an example:
import { List, ListItem, ListDivider } from "react-toolbox/lib/list";

**Comment by markolofsen** [comment]
`import { List, ListItem, ListDivider } from "react-toolbox/lib/list";`
A'll check it. Thanks.
