### ISSUE TITLE
Your site does not work

### ISSUE THREAD

**Issue by markolofsen** [react-toolbox/react-toolbox#1753]
Your site does not work — [react-toolbox.com](http://react-toolbox.com)

**Comment by cinic** [comment]
Really? #1742 #1746 #1748

**Comment by javivelasco** [comment]
www.react-toolbox.io

**Comment by markolofsen** [comment]
Ok, understood )

**Comment by cinic** [comment]
@javivelasco hi, website in repo description needed to be edit (http://react-toolbox.io).

**Comment by javivelasco** [comment]
Yeah!! So many places. Currently I've just changed the CNAME, I'm finishing fixes in the current repository to redeploy. Thanks for telling I'm doing it just now
