### ISSUE TITLE
Difficult to make a responsive App Bar

### ISSUE THREAD

**Issue by alltom** [react-toolbox/react-toolbox#177]
I have an App Bar with several items: site title, search box, two buttons, and a Menu. On mobile, there's no space for the buttons, so I want to show those items in the Menu instead when the window width is small. I tried two ways of doing this, neither of which worked well:

**Two Menus: one for narrow screens and one for wide.**

I used CSS media queries to show and hide the Menus. But if a Menu is hidden when it is created, the click handlers don't register, so you can only click the one that was visible when the page first loaded.

**One Menu: use CSS media query to show and hide menu items.**

I used media queries on the Menu items themselves to show and hide them. Unfortunately, the menu doesn't recalculate its height when items are shown and hidden this way, so it keeps whatever dimensions it calculated when the page first loaded. Sometimes that leaves whitespace at the bottom of the menu, and sometimes it means the bottom two items are cut off.

**Comment by soyjavi** [comment]
Hi @alltom in future releases we will focus in the redesign of all components with a perfect fit in any kind of screen.

stay tunned ;)

**Comment by alltom** [comment]
![giphy-16](https://cloud.githubusercontent.com/assets/1678/11501760/8e43ec22-97eb-11e5-88d6-45fef7c6d8c0.gif)

**Comment by javivelasco** [comment]
:D

**Comment by javivelasco** [comment]
Closed in favour of #224
