### ISSUE TITLE
2.0 beta 13

### ISSUE THREAD

**Issue by lolJS** [react-toolbox/react-toolbox#1771]
@javivelasco When can we expect this? There's a bunch of fixes in Dev that I'm waiting for.

**Comment by kozakluke** [comment]
this library is probably dead

**Comment by havesomeleeway** [comment]
In that case, which material ui based library are you using at the moment @kozakluke ? I'm using material-ui but I havent switched to v1 beta yet.

**Comment by L-u-k-e** [comment]
@kozakluke @havesomeleeway see: https://github.com/react-toolbox/react-toolbox/issues/1787


if you really want another library though, it might be worth having a look at the official material component implementations provided by Google. https://material.io/components/

There's a set of react rappers for them being maintained also. https://github.com/jamesmfriedman/rmwc

**Comment by rubenmoya** [comment]
Hi! The library is not dead, Javi is pretty busy right now, and he'll be focusing on the next version of react toolbox, you can expect a new beta version next week probably, as soon as I catch up with him.
