### ISSUE TITLE
Autocomplete Key Event Handlers

### ISSUE THREAD

**Issue by clurdish** [react-toolbox/react-toolbox#1777]
Currently, the Autocomplete component does not allow additional handlers for `onKeyUp` and `onKeyDown`. Adding support for these callbacks would allow for more customizable behavior, especially where navigation is involved.

I'm proposing that this be implemented in a similar manner to the `onFocus` prop in conjunction with `handleQueryFocus`. For example:

**onKeyUp**
```
handleQueryKeyUp = (event) => {
  ...
  if (this.props.onKeyUp) this.props.onKeyUp(event);
}
```

I intend to issue a pull request, and this issue will complement that request.

**Comment by paulociecomp** [comment]
may you give a context where this events would be useful?

**Comment by clurdish** [comment]
A useful context would be if you want to bind keys to actions on the page outside of the autocomplete component. For example, on `Enter`, an ajax call might return full search results from the resulting autocomplete query. While the `input` child of `Autocomplete` is focused, an `onKeyUp` event listener would be the ideal place to listen for keys that cannot be captured by `onKeyPress`.

**Comment by b-hayes** [comment]
I need this feature as well to ensure a valid place is selected. Wanted onkeyp to clear the stored place that might have been stored from a previous selection.

**Comment by b-hayes** [comment]
Actually I found you can bind keyup event the way you would normally without using places event listeners.
autocomplete = new google.maps.places.Autocomplete(... etc etc

and then use:

$(document).on('keyup',autocomplete,function () {
            alert('keyup');
        });

This worked for me I hope you find it helpful.
