### ISSUE TITLE
Can't interact with page while Snackbar is visible

### ISSUE THREAD

**Issue by alltom** [react-toolbox/react-toolbox#178]
While a Snackbar is visible, the rest of the page doesn't get mouse events.

I was going to add a persistent bar reminding the user to reload the page if I detect that there's a newer version of the site, but that prevented people from using the site until they dismissed the bar.

**Comment by javivelasco** [comment]
I think I know why is happening. I'm going to fix it tonight, thanks for reporting @alltom !!

**Comment by javivelasco** [comment]
Not yet, I've been quite busy last week. I'll try to move it later today!

**Comment by wrench7** [comment]
Thanks for adding that fix :-)

Worth noting that the pointer-events prop that you added won't work in IE < 11, which made me wonder what baseline browser config react-toolbox supports?

**Comment by javivelasco** [comment]
Truth is I'm not worrying too much about cross-browser issues. I'd like to support lower versions than IE11 in a new iteration soon. For now I can guarantee react-toolbox works in all latest Chrome, Safari and Firefox since they are the ones I can test physically.
