### ISSUE TITLE
This project is dead

### ISSUE THREAD

**Issue by callmetwan** [react-toolbox/react-toolbox#1787]
Intentionally contentious title. I haven't seen any updates or comments from the creators in about 6 months. Are you intending to resume this project @javivelasco and @soyjavi? My team wanted something that we could become familiar with and contribute to. We understand if you two are busy (being a project maintainer is hard!!) but the sudden stop in communication makes us think this project is dead.

We're close to making the decision to abandon React Toolbox. We'd prefer not to though!

**Comment by javivelasco** [comment]
It's not! Just too busy. The current version works pretty nicely but the restructure I'm working on needs time. Sorry, I'll try to get back to it ASAP

**Comment by provmark** [comment]
Thanks for the quick response  @javivelasco as our team has been wondering the same thing.  What version do you recommend using for projects that are moving to React 16?
Thanks.

**Comment by sjain-mi9** [comment]
@javivelasco Thank you for the update. Is there any ETA for the new version?

**Comment by timurgarif** [comment]
I'm quite happy with current stable version (1.3.4, the master branch).
Though It would be great if @javivelasco continued to periodically merge important PR's to the master branch. Like React 16 compatibility upgrade (if any) or bug fixes.
#1596

**Comment by javivelasco** [comment]
Yeah, I know there are super important PRs to get merged and issues to answer. I'm looking forward having some more time to attend to all of this. Will try to get something done during the weekend and to get use to dedicate at least a couple of commits per day. I can't commit to an specific ETA though. Anyway, as @timurgarif not only the master branch is stable but also the 2.x beta. What I plan to do is basically a way more flexible customization API and better practices for some components.

**Comment by 3af** [comment]
@provmark I use 2.0.0-beta.12 (the latest) with react 16.2.0 without any problems.

**Comment by hansena** [comment]
@javivelasco anything we can do to help you out or do you just need us to have patience?

**Comment by rubenmoya** [comment]
Hi @hansena! Any help is welcome, for example, answering questions in the issues, or opening PRs fixing bugs.

Every issue we solve is something less Javi has to worry about, so he can focus more in the next version :)

**Comment by deedoc** [comment]
Hi @3af! Could you help to install 2.0.0-beta.12 correctly? I tried to but no luck. My webpack.config is very similar with yours one (https://github.com/react-toolbox/react-toolbox/issues/1801#issuecomment-362721276)

I think libraries's versions are matter. I tried different versions of postcss-loader but again... no luck.

Here is my package.json
```
{
  "name": "cc-client",
  "version": "1.0.0",
  "description": "",
  "main": "client.js",
  "scripts": {
    "start-dev": "./node_modules/.bin/webpack --watch --progress",
    "build-prod": "./node_modules/.bin/webpack --mode=production"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "css-loader": "^0.28.11",
    "postcss-cssnext": "^2.8.0",
    "postcss-loader": "^0.10.1",
    "postcss-modules-values": "^1.3.0",
    "style-loader": "^0.20.3",
    "webpack": "^2.6.0"
  },
  "dependencies": {
    "babel-polyfill": "^6.26.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-toolbox": "^2.0.0-beta.12"
  }
}
```

Here is my webpack.config.js:
```
const path = require("path"),
  webpack = require("webpack")
;

module.exports = {
  entry: "./client.js",
  output: {
    path: path.join(__dirname, "dist"),
    filename: "client.js"
  },
  module: {
    rules: [
      { test: /\.js?$/, exclude: /node_modules/, use: [
        { loader: "babel-loader", options: { presets: ["react", "es2015"], plugins: ["transform-class-properties"], retainLines: true }}
      ]},
      { test: /\.css$/, include: [/react-toolbox/], use: [
            "style-loader",
            { loader: "css-loader", options: {
                importLoaders: 1,
                modules: true,
                sourceMap: true,
                localIdentName: "[name]--[local]--[hash:base64:8]",
            }},
            { loader: "postcss-loader", options: {
              plugins: function (loader) {
                return [
                    require("postcss-import")({ root: __dirname }),
                    require("postcss-mixins")(),
                    require("postcss-each")(),
                    require("postcss-cssnext")({
                      features: {
                        customProperties: {
                          variables: {
                            "color-text": "#444548",
                            "color-primary": "var(--palette-blue-500)",
                            "button-height": "30px"
                          },
                        },
                      },
                      browsers: [
                        ">1%",
                        "last 4 versions",
                        "Firefox ESR",
                        "not ie < 9"
                      ]
                    }),
                ];
              }
          }}
      ]}
    ]
  },
  plugins: [
    new webpack.ProvidePlugin({
      React: "react", R: "react"
    })
  ]
}
```

Here is my client.js:
```
import "babel-polyfill";

import AppBar from 'react-toolbox/lib/app_bar';
import Navigation from 'react-toolbox/lib/navigation';
import Link from 'react-toolbox/lib/Link';

const GithubIcon = () => (
  <svg viewBox="0 0 284 277">
    <g><path d="M141.888675,0.0234927555 C63.5359948,0.0234927555 0,63.5477395 0,141.912168 C0,204.6023 40.6554239,257.788232 97.0321356,276.549924 C104.12328,277.86336 106.726656,273.471926 106.726656,269.724287 C106.726656,266.340838 106.595077,255.16371 106.533987,243.307542 C67.0604204,251.890693 58.7310279,226.56652 58.7310279,226.56652 C52.2766299,210.166193 42.9768456,205.805304 42.9768456,205.805304 C30.1032937,196.998939 43.9472374,197.17986 43.9472374,197.17986 C58.1953153,198.180797 65.6976425,211.801527 65.6976425,211.801527 C78.35268,233.493192 98.8906827,227.222064 106.987463,223.596605 C108.260955,214.426049 111.938106,208.166669 115.995895,204.623447 C84.4804813,201.035582 51.3508808,188.869264 51.3508808,134.501475 C51.3508808,119.01045 56.8936274,106.353063 65.9701981,96.4165325 C64.4969882,92.842765 59.6403297,78.411417 67.3447241,58.8673023 C67.3447241,58.8673023 79.2596322,55.0538738 106.374213,73.4114319 C117.692318,70.2676443 129.83044,68.6910512 141.888675,68.63701 C153.94691,68.6910512 166.09443,70.2676443 177.433682,73.4114319 C204.515368,55.0538738 216.413829,58.8673023 216.413829,58.8673023 C224.13702,78.411417 219.278012,92.842765 217.804802,96.4165325 C226.902519,106.353063 232.407672,119.01045 232.407672,134.501475 C232.407672,188.998493 199.214632,200.997988 167.619331,204.510665 C172.708602,208.913848 177.243363,217.54869 177.243363,230.786433 C177.243363,249.771339 177.078889,265.050898 177.078889,269.724287 C177.078889,273.500121 179.632923,277.92445 186.825101,276.531127 C243.171268,257.748288 283.775,204.581154 283.775,141.912168 C283.775,63.5477395 220.248404,0.0234927555 141.888675,0.0234927555" /></g>
  </svg>
);

require("react-dom").render(
  <AppBar title='React Toolbox' leftIcon='menu' rightIcon={<GithubIcon />}>
    <Navigation type='horizontal'>
      <Link href='http://' label='Inbox' icon='inbox' />
      <Link href='http://' active label='Profile' icon='person' />
    </Navigation>
  </AppBar>,
  (function initRootContainer() {
    var body = document.body;

    var rootContainer = document.createElement("div");
    rootContainer.style.width = "100%"; rootContainer.style.height = "100%";
    body.appendChild(rootContainer);
    return rootContainer;
  })()
);
```

Here is my client.html
```
<!doctype html>
<html>
  <head>
    <title></title>
  </head>
  <body>
    <script src="dist/client.js"></script>
  </body>
</html>
```

Here is whole solution as zip-archive: ![client.zip](https://github.com/react-toolbox/react-toolbox/files/1837140/client.zip)

Here is result screenshot: ![client html - google chrome 2018-03-22 13 55 16](https://user-images.githubusercontent.com/1650866/37766756-ef499276-2dd8-11e8-8046-9383480f64e9.png)

**Comment by 3af** [comment]
Hi @deedoc,

sorry for late response. I'll try to look at it this week if you haven't solved it yourself by now.

**Comment by deedoc** [comment]
@3af, I'm using another ui-kit right now, but i really love react-toolbox and hope you help me (and not just me I think)
Will be waiting, thank you!

**Comment by luchillo17** [comment]
Seems React Toolbox is receiving updates, but React Toolbox Themr is indeed dead since **Feb 11 2017**, seems i cannot use this with CRA, do i have to eject?

**Comment by oliviertassinari** [comment]
👋 from Material-UI.

I'm coming back to this project [3 years later](https://github.com/react-toolbox/react-toolbox/issues/39). I have been following what you guys are doing closely since the first release of the project. It had a great influence on the direction Material-UI took. At some point, I was even benchmarking your component's implementations (now, I tend to benchmark with Bootstrap, Vuetify, MCW and Ant design). I really want to thank you for all the effort!

Now, I can't help myself thinking, what's your ambition going forward? I have been looking at the following data:
- Code activity:
![capture d ecran 2018-12-26 a 11 58 38](https://user-images.githubusercontent.com/3165635/50443964-fe73d000-0905-11e9-973b-b4fb52143750.png)
- Documentation trafic:
![capture d ecran 2018-12-26 a 12 02 47](https://user-images.githubusercontent.com/3165635/50444009-3b3fc700-0906-11e9-9953-bbc5385e7509.png)
- npm downloads:
![capture d ecran 2018-12-26 a 11 57 43](https://user-images.githubusercontent.com/3165635/50443954-f451d180-0905-11e9-902d-0908cea5b5da.png)
- GitHub stars:
![capture d ecran 2018-12-26 a 11 59 19](https://user-images.githubusercontent.com/3165635/50443946-ed2ac380-0905-11e9-979a-c41470517586.png)

They all makes be believe the project isn't moving as fast as the React community is.
How do you guys want to move forward? Have you considered the option to deprecate the library?
We could potentially build a stronger community on Material-UI side.

**Comment by luchillo17** [comment]
@oliviertassinari I agree with you, i had to move to Material-UI to be able to use themes, which in an enterprise level app is not that uncommon, if the base project in React-Toolbox depends on React-Toolbox-Themr, but the package itself is abandoned, it's the same as saying we can't create more than 1 theme in React-Toolbox.

Deprecating React-Toolbox and uniting the community around Material-UI isn't that crazy, i think it's a good idea.
