### ISSUE TITLE
Browser autocomplete off

### ISSUE THREAD

**Issue by 1aGh** [react-toolbox/react-toolbox#1795]
Hi,

a came across this issue few days ago. Do you anyone knew how to disable browser autocomplete on Input element??

Thank you for your answer

**Comment by 3af** [comment]
Hi,

[autoComplete="off"](https://stackoverflow.com/questions/37503656/react-doesnt-render-autocomplete-off) works for me.

TypeScript complains though...

**Comment by guacamoli** [comment]
I recently had to deal with this in Chrome and quickly realized that autoComplete=“off” does not work anymore (at the form or input level), at least for me. Chrome ends up showing its autocomplete by analyzing a few other things — label of the input, the name attribute of the input. Let me know if autoComplete=“off” ends up working for you, otherwise I can share my workaround.

**Comment by 1aGh** [comment]
Hi,

this isn't work. I have this two inputs:

<Input
	key='phoneNumber'
	disabled={!editMode}
	theme={theme}
	type='text'
	label='Phone number'
	name='phoneNumber'
	value={phone}
	onChange={this.handleDefaultParamChange.bind(this, 'phone')}
	autoComplete="off"
/>
<Input
	key='davtoken'
	theme={theme}
	disabled={!editMode}
	type='password'
	label='WebDav token'
	name='davtoken'
	value={davtoken}
	onChange={this.handleDefaultParamChange.bind(this,'davtoken')}
	autoComplete="off"
/>

The strange think is that both of them has different key and name that the inputs where I usually fill the user name and password for login. And still Chrome fill this two inputs with this values.

**Comment by rubenmoya** [comment]
Have you tried using the `autocomplete="off"` in the `form` instead of the `input`?

**Comment by 1aGh** [comment]
No, but I don't want to have this Inputs in the form because I'm submiting this via another component. I just save this values to the redux and then send it to the server.

**Comment by shudson250** [comment]
`autocomplete="new-password"` should work for you.

**Comment by 1aGh** [comment]
Yes that is perfect. It's finally works. But you must type autoComplete="new-password"

**Comment by jzaburunov** [comment]
@guacamoli Hey
> few other things — label of the input, the name attribute of the input. Let me know if autoComplete=“off” ends

Could tell more about how chrome works with label and input name in this point please

**Comment by MiH0N** [comment]
> `autocomplete="new-password"` should work for you.

Surprisingly, my problem was solved, but I did not understand why
Put 
`autocomplete="new-password"`
 to work correctly
Can you explain why?

**Comment by ankushweb** [comment]
for me autocomplete="new-password" is not working
