### ISSUE TITLE
Disabled Input Components can get focus, display animations, trigger onChange - 0.13.1 

### ISSUE THREAD

**Issue by elliotatRetireup** [react-toolbox/react-toolbox#180]
As of the newest update I have noticed this issue on some of my input forms.

**Comment by javivelasco** [comment]
Ok, thanks for reporting!

**Comment by smazurov** [comment]
seems like password type isn't password anymore. Additionally, the Inputs don't respect values entered in (even with passed in state). All reported behaviors are visible on main docs.

**Comment by linzerui** [comment]
the label of Input with value can also display animation.It seems like a bug.

**Comment by javivelasco** [comment]
Ok, I did not have too much time yesterday, I'll try to fix it asap.
Thanks guys

**Comment by ai10** [comment]
I still have issue with type="password" not being passed in.
