### ISSUE TITLE
composition is only allowed when selector is single :local class name not in ".raised", ".raised" is weird

### ISSUE THREAD

**Issue by prakhargloify** [react-toolbox/react-toolbox#1803]
./node_modules/react-toolbox/lib/button/theme.css
Module build failed: Error: composition is only allowed when selector is single :local class name not in ".raised", ".raised" is weird
    at Array.map (<anonymous>)

**Comment by AlesMenzel** [comment]
Are  u using it with CRA (create react app)? If thats the case then you need to include the "raw" component without styles and include the styles from react-toolbox-themr.

Example:
```
import React from 'react';
import Button from 'react-toolbox/lib/button/Button'; // NOT: import { Button } from 'react-toolbox/lib/button';
import './sample.css';

const Sample = ({ a, b }) => (
  <span className="sample">
    Sample Component, a: {a}, b: {b}
    <Button raised primary>A button</Button>
  </span>
);

export default Sample;
```

**Comment by rubenmoya** [comment]
If you're using create-react-app check https://github.com/react-toolbox/react-toolbox#usage-in-create-react-app-projects otherwise check https://github.com/react-toolbox/react-toolbox#usage-in-webpack-projects-not-create-react-app
