### ISSUE TITLE
TimePicker initial onClick does not occur

### ISSUE THREAD

**Issue by LixarBowyay** [react-toolbox/react-toolbox#1812]
When using the TimePicker component with a custom button to trigger it opened/closed, the initial click event (using no drag of the mouse) on the hours portion of the clock will not use the selected value. If you reload the page and attempt to reproduce, but this time instead click and drag even slightly, the hours field updates without trouble.

Steps to reproduce:
_Chrome/FF/Safari_

1. Load view with TimePicker in it's hidden state
2. Press custom input button and update active state of TimePicker to trigger open modal dialog
3. *!SINGLE!* Click on any of the hours numbers (do not drag at all) and the modal advances to not selecting the minutes
4. Hour on top of modal has not changed from default

**Comment by rubenmoya** [comment]
Hi! What version of react toolbox are you using? I haven't been able to reproduce it with `v2`:

![time_picker](https://user-images.githubusercontent.com/905225/36468056-162ba04a-16e2-11e8-9b8e-65fc46f5c48d.gif)

**Comment by LixarBowyay** [comment]
I believe this can be closed, the problem was something else other than this library taking over the initial click event.
