### ISSUE TITLE
ListItem documentation missing "to" and "onClick" properties

### ISSUE THREAD

**Issue by wrench7** [react-toolbox/react-toolbox#182]

**Comment by wrench7** [comment]
I forked react-toolbox last night to try and fix this issue I've raised, but realised that the [documentation](http://react-toolbox.com/#/components/list) isn't stored in this repo. Would be great if it was so that the community can chip in with documentation fixes as well :-)

**Comment by wrench7** [comment]
Scratch that, just found it! Had to follow the docs folder's structure to realise it was indeed pointing into the components folder, my bad.

**Comment by javivelasco** [comment]
Np, thanks for contributing!
