### ISSUE TITLE
Drawer opacity

### ISSUE THREAD

**Issue by tgwozdzik** [react-toolbox/react-toolbox#183]
Hi, 
i would like to ask about the Drawer component and opacity attribute that is added when component has active state. I don't want this effect in my application, so i started to look for a way to remove it.

I tried to use toolbox-loader to define my own theme. I found a global variable $color-overlay-opacity in _global.scss file. This is my theme file: 

```
$color-overlay-opacity: 0 !default;
```

Unfortunately this way doesn't work, so I started to look around why, and I found that this variable is never used in any component.

What is more, I found that Overlay component that is used in Drawer has a default prop opacity set to 0.5. I think that it would be nice to be able to set this value by prop in Drawer or variable in my own theme. 

Please tell me what do you think about it, or let me know if there is some other way to set this value :)

**Comment by javivelasco** [comment]
Yeah, we missed this. Initially the drawer has its own overlay so it was able to set the opacity. Then we put an opacity attribute directly in the Overlay component. I'm moving it to a CSS attribute so you can override it by SCSS which so easy.

Labeled as bug and resolving asap.
Thanks! :)

**Comment by tgwozdzik** [comment]
Thank you! :)
