### ISSUE TITLE
cssnext variables not showing up

### ISSUE THREAD

**Issue by UX-Unicorn** [react-toolbox/react-toolbox#1839]
I am not getting any errors in the console but none of the cssnext variables are being conpiled.  In the dev tools it just shows up as the variable name?

**Comment by hansena** [comment]
can you provide some more information?  can you recreate this in a codesandbox?

**Comment by UX-Unicorn** [comment]
I had an older version of postcss loader installed and it was breaking it.  I fixed it by updating the loader.  THanks
