### ISSUE TITLE
Problem initializing Clock from TimePickerDialog on react 16

### ISSUE THREAD

**Issue by rogeliotg** [react-toolbox/react-toolbox#1846]
Hi:
After migrating to react 16 the TimePicker is failing. It sees that the Clock inside TimePickerDialog is not correctly initialized.

TimePickerDialog.js:90 Uncaught TypeError: Cannot read property 'handleCalculateShape' of undefined
    at TimePickerDialog.componentDidUpdate (TimePickerDialog.js:90)
    at commitLifeCycles (react-dom.development.js:9706)
    at commitAllLifeCycles (react-dom.development.js:11349)
    at HTMLUnknownElement.callCallback (react-dom.development.js:104)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:142)
    at invokeGuardedCallback (react-dom.development.js:191)
    at commitRoot (react-dom.development.js:11488)
    at completeRoot (react-dom.development.js:12371)
    at performWorkOnRoot (react-dom.development.js:12321)
    at performWork (react-dom.development.js:12239)
componentDidUpdate @ TimePickerDialog.js:90
commitLifeCycles @ react-dom.development.js:9706
commitAllLifeCycles @ react-dom.development.js:11349
callCallback @ react-dom.development.js:104
invokeGuardedCallbackDev @ react-dom.development.js:142
invokeGuardedCallback @ react-dom.development.js:191
commitRoot @ react-dom.development.js:11488
completeRoot @ react-dom.development.js:12371
performWorkOnRoot @ react-dom.development.js:12321
performWork @ react-dom.development.js:12239
performSyncWork @ react-dom.development.js:12216
interactiveUpdates @ react-dom.development.js:12466
interactiveUpdates @ react-dom.development.js:1962
dispatchInteractiveEvent @ react-dom.development.js:4256
react-dom.development.js:9557 The above error occurred in the <TimePickerDialog> component:
    in TimePickerDialog (created by TimePicker)
    in div (created by TimePicker)
    in TimePicker (created by ThemedTimePicker)
    in ThemedTimePicker (created by FORMITEM)
    in ErrorBoundary (created by FORMITEM)
    in FORMITEM (created by FORM)
    in form (created by FORM)
    in FORM (created by DIALOGO)
    in section (created by Dialog)
    in div (created by Dialog)
    in div

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-dom.development.js:9557
logError @ react-dom.development.js:9596
commitErrorLogging @ react-dom.development.js:9794
commitAllLifeCycles @ react-dom.development.js:11353
callCallback @ react-dom.development.js:104
invokeGuardedCallbackDev @ react-dom.development.js:142
invokeGuardedCallback @ react-dom.development.js:191
commitRoot @ react-dom.development.js:11488
completeRoot @ react-dom.development.js:12371
performWorkOnRoot @ react-dom.development.js:12321
performWork @ react-dom.development.js:12239
performSyncWork @ react-dom.development.js:12216
interactiveUpdates @ react-dom.development.js:12466
interactiveUpdates @ react-dom.development.js:1962
dispatchInteractiveEvent @ react-dom.development.js:4256

**Comment by masakij** [comment]
The latest published version does not support React v16.
React v16 support version will be published in the near future.
https://github.com/react-toolbox/react-toolbox/pull/1814

Which version of react-toolbox was used?

**Comment by rubenmoya** [comment]
Let's wait until we publish the new version with React 16, marking it as bug in the meantime

**Comment by rubenmoya** [comment]
Closed via https://github.com/react-toolbox/react-toolbox/pull/1869
