### ISSUE TITLE
Input Component onChange receiving value instead of event

### ISSUE THREAD

**Issue by mauron85** [react-toolbox/react-toolbox#186]
According to http://react-toolbox.com/#/components/input

handleChange method should be receiving event as one of parameters, however in react-toolbox v0.13.3 I'm getting value instead

**Comment by javivelasco** [comment]
Yes, we forgot to change the documentation but it's advised in the [release notes](https://github.com/react-toolbox/react-toolbox/releases/tag/0.13.1). Changing the docs asap, thanks for reporting it!
