### ISSUE TITLE
How to re-use lib/colors.css on js components

### ISSUE THREAD

**Issue by jacargentina** [react-toolbox/react-toolbox#1868]
I want to have all my app with react-toolbox "standard colors". I some react libraries, like [Victory](https://github.com/FormidableLabs/victory) in my case, they accept colors directly, not styles.

So in this case, i would love to have centralized colors (lib/colors.css) and use them by their name on my components. Is that possible right now?

I'm thinking for a ugly hack: by simply copy/paste the lib/colors.css file to my own rt-colors.js and replace all `--palette-xxx-yyy: COLOR_VALUE;` with a JSON object with keys `palette-xxx-yyy: COLOR_VALUE` and export default that object.

**Comment by hansena** [comment]
@jacargentina 
1. Define the variables you want to override in a javascript file somewhere in your project:
```javascript
const styleVariables = {
		'color-primary': "#405c8a",
		'color-primary-dark': "#405c8a",
		'preferred-font': "'Roboto', sans-serif",
		"drawer-background-color": "var(--palette-grey-300)",
		"autocomplete-color-primary-contrast": "var(--palette-grey-100)",
		"autocomplete-color-primary": "var(--palette-grey-900)",
		"input-hint-opacity": "100",
};
export default styleVariables;
```
2. Update the postcss node of the LoaderOptionsPlugin in your webpack config:
```javascript
...
import styleVariables from './src/styles/variables.js';
...
plugins: [
...
    new webpack.LoaderOptionsPlugin({
...
        postcss: () => {
            return [
                require('postcss-cssnext')({
                    features: {
                        customProperties: {
                            variables: styleVariables,
                        },
                    },
                }),
            ];
        }
...
    })
...
]
```

**Comment by jacargentina** [comment]
I don't want/need to define any variable because they are already there ... In file lib/colors.css

For example, --palette-blue-grey-400

Redefining what is already there is what I want to avoid, ie code  duplication

Hope you get it?

**Comment by jairmilanes** [comment]
You can just import the colors.css into your own scss files and use it: 
```@import '~react-toolbox/lib/colors';

.my-element {
    color: var(--palette-blue-grey-400);
}
```

Just remember to import the `color.css` into every scss file you want to use it, I personaly put do this inside a `defaults.scss`:
```
@import url('https://fonts.googleapis.com/css?family=Roboto');
@import '~react-toolbox/lib/colors';
@import '~react-toolbox/lib/variables';
```

and then I import the defaults into other scss files.

Hope it helps!

**Comment by jacargentina** [comment]
@layoutzweb I'm not using sass here, nor want to!
