### ISSUE TITLE
Dropdown's lines, font look different than other input's lines, font.

### ISSUE THREAD

**Issue by elliotatRetireup** [react-toolbox/react-toolbox#188]
Take a look at the picture and you see that dropdowns are white while other inputs are grayish. Also the text is different even though there is no styling difference applied to the components.

![example](https://cloud.githubusercontent.com/assets/14080426/11564438/dce6e1b8-999e-11e5-8b9c-f6fd2f090c39.png)

**Comment by javivelasco** [comment]
Can you please make sure this is not messing with custom styles you may set for your app? I mean for the `font-size`. It looks like we should use the same sass variables to style dropdown borders as for inputs. Labeling as bug and doing it soon.

Thanks!

**Comment by elliotatRetireup** [comment]
In this picture, my font-size for the whole page was 65%. Removing this line from style sheet, the fonts on the dropdowns don't match those on the input boxes.

Also, I have no custom sizing for the dropdowns' templates.

**Comment by javivelasco** [comment]
I'll check it during the weekend!

**Comment by javivelasco** [comment]
@elliotatRetireup If you can't fix the problem with font sizes, please open another issue with a more detailed description. I think I've explained this in other issue, but here it is again just in case:

React Toolbox uses by default a `1rem` size as base unit which is supposed to be equivalent to `10px`. To get `10px` as root size you'd need to provide `font-size: 62.5%` to your `body` element which can be done automatically importing `react-toolbox/lib/commons`. An alternative is to use `toolbox-loader` to set a different `$unit`. This allows to scale components sizes as you want.
