### ISSUE TITLE
Parcel Bundler configuration

### ISSUE THREAD

**Issue by dusty** [react-toolbox/react-toolbox#1897]
I am trying to use react-toolbox with parcel bundler and it looks like I'm missing something.  I was hoping someone had some insights.

I put together a codesandbox of a simple react app using css modules here:

https://codesandbox.io/s/31qko09356

Below is a screenshot, you can see that the Button does have a data-react-toolbox attribute, but it isn't styled.

Any ideas?

<img width="1439" alt="screen shot 2018-11-27 at 8 49 50 am" src="https://user-images.githubusercontent.com/792/49093508-7674aa80-f221-11e8-8cef-35dab40e6792.png">

**Comment by bskimball** [comment]
I think you should check out react-toolbox-themr https://github.com/react-toolbox/react-toolbox-themr. They have an example for create-react-app which is similar to what you would need to do with parcel

**Comment by dusty** [comment]
Thanks I'll take a look at themr.
