### ISSUE TITLE
[BUG] When Input has Icon, label will float to default position on unfocus regardless whether value is there or not

### ISSUE THREAD

**Issue by TheDeveloperXYZ** [react-toolbox/react-toolbox#190]
http://react-toolbox.com/#/components/input

Load in playground.

For example, type in *email address input* some random letters.

Unfocus input by clicking anywhere out of input.

The label will go back to original position regardless wheter value is there or not.

##### This however does not occur on inputs with no icon.

Tested on both FF and Chrome - all on latest version.

**Comment by javivelasco** [comment]
Already fixed. The problem was a typo in the example, we had:

```jsx
<Input type='email' label='Email address' icon='email' />
```

but you need to give a value for the `Input` and also handle changes since it does not have state. It is fixed by doing:

```jsx
<Input type='email' label='Email address' icon='email' value={this.state.email} onChange={this.handleChange.bind(this, 'email')} />
```

and handling changes properly with `handleChange`.

Thanks for reporting!
