### ISSUE TITLE
can not open page

### ISSUE THREAD

**Issue by seungyeub** [react-toolbox/react-toolbox#1915]
https://www.react-toolbox.io/

I tried to visit the site to use the react-toolbox.
However, the page does not open.
Please check.

**Comment by JoshK2** [comment]
I see it's because www in the URL, they did not do a redirect from www.

**Comment by JoshK2** [comment]
You can still access the website from this URL http://react-toolbox.io .

**Comment by seungyeub** [comment]
thank you.
