### ISSUE TITLE
Fixed, always open Drawer not possible?

### ISSUE THREAD

**Issue by saidimu** [react-toolbox/react-toolbox#192]
It seems it isn't (easily) possible to have a fixed Drawer which always stays open because the opacity gets in the way. Turning off the opacity also disappears the Drawer.

This layout is extremely useful for larger screens where screen space isn't an issue and the navigation drawer should always be visible/open. I should add that this is also a very common pattern in Google apps. Google's official Material Design for web apps suggests such layouts in their [docs](http://www.getmdl.io/components/index.html#layout-section/layout).

![screenshot from 2015-12-04 01-22-53](https://cloud.githubusercontent.com/assets/468077/11583275/dc6cd742-9a25-11e5-9c19-1edfd7af7740.png)

**Comment by javivelasco** [comment]
You are totally right. It makes a lot of sense to have a way to create a permanent Drawer. For now, it's not possible but we'll try to have it ready for the next iteration.

Thanks!

**Comment by saidimu** [comment]
Awesome! Look forwarding to using it.

**Comment by nathanmarks** [comment]
@javivelasco this would work well as part of responsivizing everything

**Comment by nathanmarks** [comment]
All of the app-bar + drawer combos and their optional UX patterns (such as auto opening + locked above X width) should be possible ideally after everything is made to meet the adaptive UI requirements of the spec.

**Comment by javivelasco** [comment]
Yep

**Comment by javivelasco** [comment]
Closing in favour of #224
