### ISSUE TITLE
Using with este

### ISSUE THREAD

**Issue by AlesJiranek** [react-toolbox/react-toolbox#194]
Hi, 
I'm trying to use reac-toolbox with https://github.com/este/este but I can't get it working, because styles are not loading. 
It shows me error ` Cannot resolve 'file' or 'directory' ./style in @ ./~/react-toolbox/lib/input/Input.js 35:13-31`

Could you point me, what should I change in webpack config please? 
It looks like this 
https://github.com/este/este/blob/master/webpack/makeConfig.js

**Comment by AlesJiranek** [comment]
ok, i figgured out, that I have to add .scss to resolve extensions. But it is still not working, becuse you are using class names like `style.input`. I think, i have to change something more in config, do you know what is it please?

**Comment by AlesJiranek** [comment]
It is `modules` option on css-loader

**Comment by javivelasco** [comment]
Great, thanks for the info!

**Comment by AlesJiranek** [comment]
But there is a problem with server side rendering, because css modules are not available on server
