### ISSUE TITLE
Add breakpoint mixins to prepare for responsive styling?

### ISSUE THREAD

**Issue by nathanmarks** [react-toolbox/react-toolbox#197]
I would like, where applicable, to start adding responsive styles for things I'm contributing to.

Google have given a great outline on the responsive breakpoints in the spec:
https://www.google.com/design/spec/layout/adaptive-ui.html

Would it be possible for you to setup the initial stages of making this responsive and get things setup how you would like them in terms of breakpoints? (such as making mixins available for use in components).

Looking at the google spec page, it would also appear that a grid system should be part of this library as it is a core part of the adaptive layout philosophy.

**Comment by javivelasco** [comment]
For me it would be perfect to have some breakpoints well defined in `globals.scss` and then create some mixins to use in each component. It also makes sense to have a grid of course! We can use this issue to track the progress

**Comment by nathanmarks** [comment]
Here's what they use at [angular/material](https://github.com/angular/material): 
https://github.com/angular/material/blob/v1.0.0-rc6/src/core/style/variables.scss#L30-L33

It seems to fall in line with the 5 high level breakpoints google [define in the spec](https://dl.dropboxusercontent.com/s/btz7d8ntmtsxdbj/2015-12-06%20at%209.42%20PM.png)

In contrast, with material design lite they only provide 3 breakpoints:
https://github.com/google/material-design-lite/blob/master/src/_variables.scss#L514-L534

These 3 breakpoints don't fall in line with the high level xs->xl breakpoints, but rather seem to be following phone(portrait) -> tablet(portrait) -> "desktop": http://www.getmdl.io/components/index.html#layout-section/grid

**Comment by javivelasco** [comment]
I prefer angular material approach, we can go with it

**Comment by nathanmarks** [comment]
@javivelasco Me too, it's more flexible and I don't like naming "phone" as just anything below `480px`. It is not a good representation of modern devices given all the different types of resolutions, pixel density and not to mention portrait/landscape.

**Comment by nathanmarks** [comment]
BTW, do you want to add the variables + breakpoint mixins? 

Something like `@include media-breakpoint-up('sm') { }` would be nice along with other variations like `media-breakpoint-only` and `media-breakpoint-down`

**Comment by javivelasco** [comment]
Yes, it sounds nice. My next goal is to solve the issue with global styles so if you want to create and PR a first approach to `dev` I'll be happy to include it and iterate over it :)

**Comment by javivelasco** [comment]
Closing in favour of #224
