### ISSUE TITLE
Class names "undefined" on generated HTML.

### ISSUE THREAD

**Issue by phyllisstein** [react-toolbox/react-toolbox#207]
Hi there! I'm seeing an odd issue whereby the styles are being loaded fine but the elements are rendered with `class="undefined"`. So this...

```jsx
import { App, AppBar } from 'react-toolbox/lib';

class Application extends React.Component {
  displayName = 'Application';

  render() {
    return (
      <App>
        <AppBar fixed>
          <a href='#'>Application</a>
        </AppBar>
      </App>
    );
  }
}
```

...renders like this:

```html
<div data-react-toolbox="app" class="undefined " data-reactid=".1" style="box-sizing: border-box;">
  <header class="" data-react-toolbox="app-bar" data-reactid=".1.0">
    <a href="#" data-reactid=".1.0.0">Application</a>
  </header>
</div>
```

I checked Webpack's `css-loader` and `style-loader` READMEs against the source, and I can't figure out how to `import` a stylesheet in the way the source seems to expect, such that raw class names are exported as an object. I'd be grateful for any pointers, though. Thanks in advance for your help!

**Comment by Rillus** [comment]
How is your webpack.config.js set up? That's normally the key to CSS module issues.
You'll be after a line that looks something like:
````
{test: /\.(scss|css)$/, loader: 'style-loader!css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]-[local]___[hash:base64:5]!sass-loader?sourceMap!toolbox-loader'},
````

**Comment by javivelasco** [comment]
Yeah, as @Rillus says, this is probably an issue related to your config and CSS modules. Please, check the [example repository](https://github.com/react-toolbox/react-toolbox-example) to get a boilerplate configuration.

I'm closing the issue if it's not happening with anybody else.
Thanks for your response @Rillus !

**Comment by phyllisstein** [comment]
That worked beautifully! I was missing the CSS loader's `modules` flag. Thanks so much for the pointer!

**Comment by javivelasco** [comment]
Great, thanks for the update! :)

**Comment by ArtemZag** [comment]
I have similar problem. But I did added toolbox-loader. And I get it only on windows (on MacOS it works fine). Do you know what it might be? https://github.com/react-toolbox/react-toolbox/issues/528
