### ISSUE TITLE
column placement (multiple items per row)

### ISSUE THREAD

**Issue by acornejo** [react-toolbox/react-toolbox#216]
often you want to place two or more components in the same line.

for instance, you may want to have two input boxes, one for firstname the other for lastname, or perhaps one input box for phone number and next to it a dropdown for type (i.e. mobile, home, work).

there are plenty of such examples in google's material design website, see here:

https://www.google.com/design/spec/components/text-fields.html#text-fields-labels

what solution does react-toolbox recommend to do this? I tried nesting components using flexbox placement (https://github.com/tcoopman/react-flexbox) however that doesn't work well (components break down).

Similarly, it seems that the input box for datepicker has different margin alignments than a regular input box (or a dropdown menu), which prevents placing it in the same line without having some pretty visible alignment issues.

**Comment by javivelasco** [comment]
Hi @acornejo! 

Input in the picker should have the same margin. In case they don't it should be considered a bug and fixed. To place your inputs in the same row it should be possible to provide a `className` prop that is placed in the top node of the component. It should be enough to set some flex css properties. As soon as I have some time I'll try to check your example to see what's happening.

Thanks! :)

**Comment by acornejo** [comment]
@javivelasco thanks for the quick reply.

I am using react-flexbox, but the issues are easily reproducible without it.

For instance, wherever I place an input it takes 100% width of its parent container. This is great, since it suffices to make the parent container smaller (say 33% or 50%) to place multiple inputs in the same row.

Unfortunately, the dropdown behaves differently, and hence it looks ugly if I try to place two of them side by side. This is because they inherit the width of the parent container, so if the parent has width of 50% then the dropdown will only occupy 50% of that (i.e. 25%).

More serious style errors are as follows:

datepicker input has different height and aligntment than dropdown, so if you place them side-by-side they do NOT align.

the same is true of datepicker and autocomplete, or autocomplete and dropdown, etc.

**Comment by javivelasco** [comment]
Ok. I'm working today to get homogeneous inputs and making some fixes to make it possible to align inputs per columns. Releasing it today

**Comment by javivelasco** [comment]
I made an example setting the layout wrapping components in `divs` and it works. For some components you may need to provide the wrapper because the use margins at the top level. In other cases it would be enough providing a `className` property. Here is how the example looks for me:

<img width="742" alt="screenshot 2015-12-20 17 52 19" src="https://cloud.githubusercontent.com/assets/1634922/11918943/4fe9935c-a743-11e5-983a-cfd10f15b352.png">

All input components looks the same size except for the `Autocomplete` with `multiple` selection obviously, since it's placing the selected results at the top of the same element. There is a rewrite on progress for it so soon it will be available. For the simple selection autocomplete it looks nice. Coming during next release today.

**Comment by acornejo** [comment]
Thank you Javi!

This looks fantastic. May I suggest you add this example to the react-toolbox-example or some other public repo with examples? I am sure plenty of folks (including myself) will find it useful.

I was going to open up a separate ticket about the autocomplete, but it seems you guys are aware of that too (the google material design guidelines show a single line, plus the "pills" have an x for removal).

**Comment by javivelasco** [comment]
Yeah, here #174 you can see a proposal to use chip component for the selected items and to split selected area from the actual autocomplete. Hopefully it will be ready for next release.
