### ISSUE TITLE
`overflow-y: scroll` vs `overflow-y: auto`

### ISSUE THREAD

**Issue by pdf** [react-toolbox/react-toolbox#218]
A number of components use `overflow-y: scroll`, which forces scrollbars to be always visible. I presume to work around this, `commons.scss` hides webkit scrollbars globally.  There are two problems with this: on non-webkit browsers, scrollbars are visible even when they are unnecessary; and scrollbars are hidden in webkit browsers, even on elements where they may be desirable.

I propose using `overflow-y: auto; -webkit-overflow-scrolling: touch;` in all components currently using `overflow-y: scroll;`, and if maintainers feel strongly about hiding scrollbars on specific components, those can individually specify the relevant webkit properties.

Happy to send a PR for the former if this is acceptable, of for both if maints can specify the components that require scrollbars hidden (though I'm not convinced this is a great idea).

**Comment by javivelasco** [comment]
I'll be happy to accept a PR with your proposal!
Thanks!
