### ISSUE TITLE
How to extend CSS of the componets?

### ISSUE THREAD

**Issue by varya** [react-toolbox/react-toolbox#219]
I would like to use react-toolbox components but with my own design changes. How should I extend the CSS?

This is how I had to do it for the button to overwrite the given:
<img width="1138" alt="screen shot 2015-12-17 at 14 36 34" src="https://cloud.githubusercontent.com/assets/27215/11870126/95b90548-a4cd-11e5-8147-29b810b5ff37.png">

Not what I would prefer to use. Is there any normal way?

This is my repo. You can see the button at http://localhost:3000/components

**Comment by javivelasco** [comment]
In case you want a custom button you can provide a class and inside this class extend from the `button` class from react toolbox using `composes` keyword from css modules. The problem is that react toolbox css is in your build included *after* your custom style and that would ensure the composed style is included *before* your custom.

Another option is to provide a wrapper so you can boost priority to 2. With that it should be enough!

**Comment by javivelasco** [comment]
@varya by default you have in Material Design three types for buttons: `raised`, `floating` and `flat`. These modifiers should be always present and they are included in the default styles. Apart from that, you have multiple leves that are defining colors:  `primary`, `accent` and `neutral`.

To style `primary` and `accent` React Toolbox uses a SASS mixin that you can use in your project to generate custom buttons. For example, to create a success button you can write something like this:

```scss
// CustomButton.scss
@import "~react-toolbox/lib/mixins";
@include btn-colors('success', white, green, lighten(green, 40%));
```

```jsx
const SuccessButton = (props) => {
  const className = `${style.success} ${style.raised}`;
  return <Button {...props} raised className={className} />;
};
```

You only have to take into consideration that the `mixin` includes styles for the `flat`, `raised` and `floating` modifiers and they are local so they should be included in the `className` prop. I'm going to add this example to the example repository. The mixin is not included yet in the `mixins` file, it will be available *tomorrow* in the *next release*.
