### ISSUE TITLE
Stop adding several copies of the same styles?

### ISSUE THREAD

**Issue by alltom** [react-toolbox/react-toolbox#220]
When you use react-toolbox, for some reason you get many copies of the same styles. For example, if you open the Web Inspector on react-toolbox.com, you can see 10 copies of the `::-webkit-scrollbar` rule set:

![image](https://cloud.githubusercontent.com/assets/1678/11889842/44bb37b2-a502-11e5-8644-c5987d01551a.png)

Is this preventable?

**Comment by javivelasco** [comment]
Wow that's weird. The style is defined as a global in commons. I'll check in it during the week and see what happens. Thanks for reporting @alltom

**Comment by javivelasco** [comment]
This was happening because we were importing `commons.scss` in `globals.scss` inside the docs subproject. After that, `globals` was required in multiple files in order to import some general variables. Now it's fixed by moving commons scss import to the main `App` component.

**Comment by alltom** [comment]
Sweet, thanks. :)
