### ISSUE TITLE
Missing className property in datepicker component

### ISSUE THREAD

**Issue by nkaczor** [react-toolbox/react-toolbox#222]
How to apply custom style on datepicker component? There is no className property :(

**Comment by javivelasco** [comment]
Hi! I did not include `className` because I didn't think it would be needed any customization if you use the standard. Apart from that, is a quite complex component. What would you exactly want to personalize in order to provide an option or something?

**Comment by nkaczor** [comment]
I would like to personalize background color of header and active date style. Can I accomplish it with toolbox-loader?

**Comment by javivelasco** [comment]
With toolbox loader you can personalize almost everything but it mostly focused on color changing. To do so you can check the configuration variables used for each component in the source code. Then you can override those variables in your theme using toolbox loader.

Another option, would be to browse the HTML focusing on `data-react-toolbox` attributes to apply styles from an upper className.

**Comment by javivelasco** [comment]
I've added className property to pickers so you can use it to target more specific elements and give a custom look to your picker. If you just want to modify colors (which is the most likely case) you can use the `toolbox-loader`.

Thanks!
