### ISSUE TITLE
Add link to github source code for components

### ISSUE THREAD

**Issue by itsNikolay** [react-toolbox/react-toolbox#227]
I offer to add a link to github source code for a each component

**Comment by javivelasco** [comment]
I think it makes sense as long as it's transparently configured just like the urls of components. Happy to accept a PR! Thanks for your offer @itsNikolay !

**Comment by itsNikolay** [comment]
Well, I'll send PR as soon as possible :+1:

**Comment by javivelasco** [comment]
Awesome! Thanks! :)
