### ISSUE TITLE
Replace transition-property to transition, because Autoprefixer could not support any cases of transition-property and other transition-*

### ISSUE THREAD

**Issue by itsNikolay** [react-toolbox/react-toolbox#230]
`$ webpack -p`

/node_modules/react-toolbox/lib/animations/zoom-in.scss:1:141: Replace transition-property to transition, because Autoprefixer could not support any cases of transition-property and other transition-*

Nodejs 4.3.2
"react-toolbox": "^0.14.0"
"autoprefixer": "^6.1.2",
"autoprefixer-core": "^5.1.0",

**Comment by Bartekus** [comment]
I've submitted a new pull request which will take care of all these errors as well as bring the entire development up to date, dependencies wise.

**Comment by javivelasco** [comment]
Great, I'll check the PR! Thanks!

**Comment by neverfox** [comment]
Would love to get rid of these warnings. When is the next release planned?

**Comment by javivelasco** [comment]
Today!

**Comment by shidhincr** [comment]
Yay!

**Comment by javivelasco** [comment]
Alredy done guys. Probably another patch will come soon since people are contributing with small fixes constantly. And I love it

**Comment by carlokid** [comment]
Is this fixed?
