### ISSUE TITLE
Support for React Tap Event Plugin

### ISSUE THREAD

**Issue by karlmacklin** [react-toolbox/react-toolbox#232]
Feature request:

The React Tap Event Plugin, https://github.com/zilverline/react-tap-event-plugin (or similar!), can be used to speed up the mobile responsiveness when tapping elements.

From my limited testing and knowledge of this framework I can't get them to work together, so maybe that is something that requires support by modifying the actual components.

ReactJS itself supposedly will handle this in the future so it may or may not be worth considering waiting for that instead.

**Comment by EnzoMartin** [comment]
Just FYI, the 300ms delay is basically just an iOS issue at this point: http://developer.telerik.com/featured/300-ms-click-delay-ios-8/

Chrome, Firefox, and IE all have easy ways to disable the behavior on the browser level, and iOS is making some changes to it already. Wouldn't be surprised if they adopt a similar solution to Chrome/Firefox in a future iOS update.

The delay is barely noticeable though IMO

**Comment by javivelasco** [comment]
Nice response @EnzoMartin and @karlmacklin thanks for your suggestion! As you said, React supposedly it's handling tap events nicely soon. For now, IMO it's better to avoid too much vendor libs specially if it's going to be fixed soon and the delay is not very noticeable. Anyway, that's just my opinion. If more people is likely to add more support for tap events we should add it.

Also, be aware the responsive version is coming soon. We are still planning next steps about it so it would have too much sense to focus on supporting tap events without making sure all components look nice in phones and small tablets.

Thanks for your comment!

**Comment by karlmacklin** [comment]
Yep, totally agree with your thoughts on this!
