### ISSUE TITLE
Colors when using inverse, disabled in combination

### ISSUE THREAD

**Issue by langri-sha** [react-toolbox/react-toolbox#236]
Using the `inverse` attribute on components allows me to place content on dark backgrounds. It seems, though, that using `disabled` will enforce a color which doesn't respect `inverse`.

**Comment by javivelasco** [comment]
Ok. Let's add some styling to make it transparent but making the text look disabled for those cases. Maybe opacity can do the trick when inverse + disabled?

**Comment by langri-sha** [comment]
Sounds like it would do the trick. Do you have any suggestions on how we could add inverse color examples into the documentation playgrounds and maybe I can start a PR with something that works?

**Comment by javivelasco** [comment]
The code loaded in the documentation is [right here](https://github.com/react-toolbox/react-toolbox/tree/dev/docs/app/components/layout/main/modules/examples). You can add an icon with the inverse and disabled prop and change the style definition. I'll try to do it during the week, just came back from holidays! I'll be happy to accept PRs about it!

**Comment by langri-sha** [comment]
Happy new year :fireworks:! If I beat you to it, I'll try to look at the SASS sources and find a suitable way to introduce RGBA for the existing inverse RGB colors.

**Comment by javivelasco** [comment]
Awesome! Happy new year for you too! :)
