### ISSUE TITLE
Datepicker minDate prop should override the default date if minDate > default date

### ISSUE THREAD

**Issue by anthony-nardi** [react-toolbox/react-toolbox#238]
Currently, the minDate prop can be set to a day in the future. Unfortunately, the user can still select the current day by clicking OK.  In my opinion, expressed in pseudo code, `defaultDate = Math.max(minDate, new Date())`

Below are 2 screenshots.  The code is the same for each.  You can see that the user can just click "OK" to select the current day.  If the user clicks another date, they cannot choose the current day anymore.  At the very least, the user should not be able to pick a day that is before the minDate.  

![datepicker2](https://cloud.githubusercontent.com/assets/932450/12045258/f422bf3a-ae6d-11e5-8f18-ab9326c67249.PNG)
![datepicker1](https://cloud.githubusercontent.com/assets/932450/12045257/f4230b48-ae6d-11e5-8221-97cc43c172a1.PNG)

**Comment by javivelasco** [comment]
Labeled as a bug, it will be resolved for the next release.
Thanks @anthony-nardi

**Comment by rrott** [comment]
Looks like it was fixed in https://github.com/react-toolbox/react-toolbox/commit/f31dde202b75656566348a5c75e72ff7b7934952

**Comment by javivelasco** [comment]
Thanks @rrott
