### ISSUE TITLE
Table component always render an input in row even though onChange props wasn't set

### ISSUE THREAD

**Issue by thangngoc89** [react-toolbox/react-toolbox#240]
This condition always true

```js
    if (this.props.onChange) {
      return this.renderInput(key, value);
    } else if (value) {
      return value.toString();
    }
```
https://github.com/react-toolbox/react-toolbox/blob/dev/components/table/TableRow.jsx#L40-L44

Because you always pass onChange props into `TableRow` component at this line 
https://github.com/react-toolbox/react-toolbox/blob/dev/components/table/Table.jsx#L72

**Comment by javivelasco** [comment]
You are right! The intent was to avoid having an editable field if you don't care about changes. Maybe a good solution would be to change here https://github.com/react-toolbox/react-toolbox/blob/dev/components/table/Table.jsx#L72 the function call to a function generator that returns a function in case `onChange` has a value. In case it would have a handler the generator would return null so no input would be rendered.

What do you think?

**Comment by thangngoc89** [comment]
Yup. I think it would be the best :+1: . Anyway, awesome work with react-toolbox

**Comment by javivelasco** [comment]
Thanks! :D

**Comment by newswim** [comment]
I noticed that just using the example table throws this error (React v15 and Meteor 1.3.2.4)

```console
warning.js:44 - Warning: `value` prop on `input` should not be null. Consider using
the empty string to clear the component or `undefined` for uncontrolled components.
```

**Comment by javivelasco** [comment]
Yeah, gonna fix it for the next release

**Comment by javivelasco** [comment]
Shall be fixed
