### ISSUE TITLE
Tooltip doesn't work with Link component

### ISSUE THREAD

**Issue by karlmacklin** [react-toolbox/react-toolbox#241]
I can get the tooltip from examples working fine, but not when trying to decorate a Link component.

Perhaps it's similar to this previous issue:
https://github.com/react-toolbox/react-toolbox/issues/214

?

**Comment by javivelasco** [comment]
Yep, that's the same problem. Easy to fix. Would you want to open a PR? :)

**Comment by karlmacklin** [comment]
I opened one, please check:
https://github.com/react-toolbox/react-toolbox/pull/245

**Comment by javivelasco** [comment]
Merged! Thanks @karlmacklin
