### ISSUE TITLE
Icons cannot get svg

### ISSUE THREAD

**Issue by tomasztomys** [react-toolbox/react-toolbox#243]
I want to use ListItem, but avatar's props must be a string. I want to pass it a SVG component from svg-inline-react.

**Comment by javivelasco** [comment]
We have a pending PR to add flexibility to Lists. It's still not reading but coming soon. For now you can use a material design icon or an image but in the next version you'd be able to provide arbitrary content.

**Comment by epilgrim** [comment]
is this issue solved by #274 ?

**Comment by javivelasco** [comment]
I think so!
