### ISSUE TITLE
Expand / collapse capability for List Items

### ISSUE THREAD

**Issue by jasonkylefrank** [react-toolbox/react-toolbox#249]
Hello,

Do you have plans to add the **expand/collapse** capability (and thus **nested content**) for List Items that the Material Design spec outlines?

![image](https://cloud.githubusercontent.com/assets/7502365/12150385/7eb0eb40-b477-11e5-9e32-b5bb7849ecdf.png)

<br />
This would be a huge benefit.  Material UI has this capability - they call it "nested list items":
<br />

![image](https://cloud.githubusercontent.com/assets/7502365/12150572/86cb43ec-b478-11e5-9fe1-c1c09eb392f6.png)

This capability could help fill the void that other control suites provide with controls like accordions, or "panel boxes" (a la Kendo UI).  I realize that the Material Design spec does not currently show "accordions" or "panel boxes", but the nested list feature is shown by the spec.  

Thanks and best wishes.

**Comment by jasonkylefrank** [comment]
Anybody home?

**Comment by javivelasco** [comment]
Hey @jasonkylefrank I forgot about this. We are thinking about a new more flexible way to display lists. Since it is not originally specified in the List spec, we didn't do it yet. It should be considered for the next list iteration, it's a very useful feature

**Comment by jasonkylefrank** [comment]
Great!  Any idea when that might be released?

**Comment by javivelasco** [comment]
I can´t tell exactly when, there are other tasks with more priority like making the components mobile friendly and a more flexible autocomplete, sorry :(

**Comment by renato** [comment]
I'd like this too.

If you are thinking about a new more flexible way to display lists, is there anything we can do right now to help?

**Comment by pureux** [comment]
Agreed, this would be really useful (though understanding there are also higher priorities).  Thanks!

**Comment by mismith** [comment]
+1

**Comment by javivelasco** [comment]
Any PR regarding this is very welcome in the PostCSS branch! Sorry for my delayed response, I'm lacking spare time lately

**Comment by thj-dk** [comment]
Any progress on this? It would be truly awesome 👍

**Comment by javivelasco** [comment]
It's going to be done in a refactor of the `List` component. For me it's a bit overcomplicated now and I'd like to make it simpler. No progress yet though

**Comment by thj-dk** [comment]
Thanks for the update. Looking foward to it. If you want to share your thoughts on how you imagine this to be implemented, maybe we can help.

**Comment by javivelasco** [comment]
No problem!! Sure I will :)

**Comment by hansena** [comment]
I had a need to implement this functionality now and found the [react-collapsible](https://www.npmjs.com/package/react-collapsible) library to play very nicely with the react-toolbox list controls using a pattern like:
```javascript
<List selectable ripple>
  <ListItem caption="USCM Overview" leftIcon="equalizer" onClick={this.navListOverviewClick} />
  <ListDivider />
  <Collapsible
	trigger={<ListItem rightIcon="keyboard_arrow_down" caption="Reliability" />}
	triggerWhenOpen={<ListItem rightIcon="keyboard_arrow_up" caption="Reliability" />}
	easing="ease-in-out" >
    <ListItem selectable caption="Overview" onClick={this.navListReliabilityOverviewClick} />
    <ListItem selectable caption="Availability" onClick={this.navListAvailabilityClick} />
  </Collapsible>
  <ListDivider />
</List>
```

![temp](https://user-images.githubusercontent.com/15346521/30783067-56e5b06e-a10b-11e7-8702-a36729b4bd18.png)

**Comment by javivelasco** [comment]
Cool! I wanted to say that the next version will be incredibly composable! This component has been completely re-written
