### ISSUE TITLE
Checkbox's input acts like a block in Firefox thus leaving unwanted space

### ISSUE THREAD

**Issue by Genert** [react-toolbox/react-toolbox#250]
In firefox the input will not be hidden and acts like a hidden block.

![12313123](https://cloud.githubusercontent.com/assets/1218788/12155491/075b718a-b4ce-11e5-9de7-034fe8e4a261.png)

**Comment by TheDeveloperXYZ** [comment]
Suggested solution: use **display: none** on input.
