### ISSUE TITLE
weird issue around IconMenu

### ISSUE THREAD

**Issue by jackielii** [react-toolbox/react-toolbox#251]
Used in combination with AppBar etc the width and height of the IconMenu is wrong, in my application with width is simply the width of the viewport.

Test code here: https://github.com/react-toolbox/react-toolbox/compare/dev...jackielii:issue-251

![menuiconerror](https://cloud.githubusercontent.com/assets/360983/12175658/602035fc-b55b-11e5-8e47-aeb577d8370a.png)

It should look like this (copied from official doc)
![image](https://cloud.githubusercontent.com/assets/360983/12175803/13a03fd2-b55c-11e5-99f4-31bd84d164c2.png)

**Comment by javivelasco** [comment]
Yes, probably is related to the fixed position of the container element. Maybe the best would be to position the menu on a top node like we do with other components like the `Drawer` or the `Dialog`. Anyway, it's a bug and case to study, thanks for reporting it!

**Comment by jackielii** [comment]
I think we could achieve a Menu with a `Diaglog` and `List`, `LstItem` etc. right?

**Comment by javivelasco** [comment]
Yep

**Comment by erdysson** [comment]
No I think it is not related to the fixed position of the app-bar, because I have the  same issue in both appbar and inside the body

**Comment by sars** [comment]
Position is defined on componentDidMount
it seems like getBoundingClientRect returns wrong info in that time
If you wrap calculations in componentDidMount with setTimeout - it works good. Otherwise - not

**Comment by quarryman** [comment]
Got the same behaviour. SetTimeout with zero delay solves the issue.
