### ISSUE TITLE
Autocomplete component with multiple=false

### ISSUE THREAD

**Issue by dariuszpaluch** [react-toolbox/react-toolbox#252]
When I use autocomplete with multiple=false (User can choose only one option), I found some mistakes.
1. When we have some selected option, Then user want to change this. Now he need to remove all text from input, then choose onother option from list. I think the best option is: 
   -Remove text from input, and show all options when user click on input (like a simple select)
2. When I select some option from autocomplete, then i remove all from input to choose new option. Then I can't choose this option, which I select before, because it doesn't show in list.

**Comment by javivelasco** [comment]
Yes, I agree with you. It's not a bug but it could work better avoiding the points you've said. More feedback about a desirable behavior would be very nice.

**Comment by dariuszpaluch** [comment]
I think the best option, is add one props to component which describe that clean input on click or not,
and show all options in list when multiple = false.
