### ISSUE TITLE
Event Propagation

### ISSUE THREAD

**Issue by trbngr** [react-toolbox/react-toolbox#257]
I'm looking specifically at Tooltip (I haven't looked at the other components yet)...

all the event handlers just swallow the event.

example: 

```
  handleClick = () => {
    if (this.timeout) clearTimeout(this.timeout);
    if (this.props.tooltipHideOnClick) this.setState({active: false});
    if (this.props.onClick) this.props.onClick();
  }
```

should be
```
  handleClick = (e) => {
    if (this.timeout) clearTimeout(this.timeout);
    if (this.props.tooltipHideOnClick) this.setState({active: false});
    if (this.props.onClick) this.props.onClick(e);
  }
```

**Comment by javivelasco** [comment]
This is done on other components as well. Costs nothing to pass the event through, feel free to submit a PR!

**Comment by soyjavi** [comment]
Is not bad idea pass the `event`, I mean maybe you wanna get some attributes in the `callback` (like cursor axys or whatever...)
