### ISSUE TITLE
jsx extension vs js 

### ISSUE THREAD

**Issue by giltig** [react-toolbox/react-toolbox#258]
Hi,
Your components are with jsx extensions.
I would recommend to change it to normal js extensions due to the fact that jsx is now another transpiled feature of the new js (such as many more of es2015, es 2016 etc.).

**Comment by EnzoMartin** [comment]
Why?

**Comment by giltig** [comment]
It's a matter of convention. jsx today is just part of js and Facebook also recommended that js extension will be the convention also for jsx files.

**Comment by javivelasco** [comment]
Yes, truth is I'm writing no jsx extension anymore. Doing it tonight!

**Comment by nathanmarks** [comment]
Ah, the ever changing practices :)

**Comment by EnzoMartin** [comment]
It's Facebook, so that's gonna happen quite often sadly

**Comment by KerenChandran** [comment]
@javivelasco I think we can close this issue since its implemented in 0cb8d8bdb2f7587f2d4a4770c10346a9d2ef43ad

**Comment by javivelasco** [comment]
Yep, thanks!
