### ISSUE TITLE
cannot npm install?

### ISSUE THREAD

**Issue by pixiez** [react-toolbox/react-toolbox#259]
I am getting the following error while trying to do npm install --save react-toolbox, am I missing anything? thanks 

test@1.0.0 /home/nitrous/code/test
├── UNMET PEER DEPENDENCY classnames@^2.2.0
├── UNMET PEER DEPENDENCY normalize.css@^3.0.3
├── UNMET PEER DEPENDENCY react@^0.14
├── UNMET PEER DEPENDENCY react-addons-css-transition-group@^0.14.0
├── UNMET PEER DEPENDENCY react-dom@^0.14.0
└── react-toolbox@0.14.0
npm WARN EPEERINVALID react-toolbox@0.14.0 requires a peer of classnames@^2.2.0 but none was installed.
npm WARN EPEERINVALID react-toolbox@0.14.0 requires a peer of react@^0.14 but none was installed.
npm WARN EPEERINVALID react-toolbox@0.14.0 requires a peer of react-dom@^0.14.0 but none was installed.
npm WARN EPEERINVALID react-toolbox@0.14.0 requires a peer of react-addons-css-transition-group@^0.14.0 but none was installed.
npm WARN EPEERINVALID react-toolbox@0.14.0 requires a peer of normalize.css@^3.0.3 but none was installed.
npm WARN EPACKAGEJSON test@1.0.0 No description
npm WARN EPACKAGEJSON test@1.0.0 No repository field.

**Comment by getapp** [comment]
@pixiez, you need to install peer dependencies.
try this 

`npm install --save classnames normalize.css react react-addons-css-transition-group react-dom react-toolbox`

**Comment by kagux** [comment]
@pixiez, you need to install peer dependencies.
try this 

`npm install --save classnames normalize.css react react-addons-css-transition-group react-dom react-toolbox`

**Comment by pixiez** [comment]
@kagux thats works, thanks :)
