### ISSUE TITLE
How do I use the default styles?

### ISSUE THREAD

**Issue by calvinrachuy** [react-toolbox/react-toolbox#263]
Please see my SO:
http://stackoverflow.com/questions/34779926/react-toolbox-use-default-css-style

Ref:
https://github.com/react-toolbox/react-toolbox/issues/231
https://github.com/react-toolbox/react-toolbox/issues/198

**Comment by calvinrachuy** [comment]
I opened a new local branch and copied most of the example repo into my project. It seems to be working. I don't know what I missed, as I had copied over almost all of the configs by the time I posted this issue, but anyway I can move forward.

**Comment by javivelasco** [comment]
That's weird, it's happing to a lot of people. Actually the configuration is tricky, that's why we provide an example. Thanks for keeping updated the issue!
