### ISSUE TITLE
Dialog content is rendered on componentDidMount

### ISSUE THREAD

**Issue by sars** [react-toolbox/react-toolbox#264]
Hi there!
I noticed, that dialog content is rendered immediately after the initial rendering occurs.
https://github.com/react-toolbox/react-toolbox/blob/dev/components/overlay/Overlay.jsx#L24

Isn't it nicer to render it of first active=true prop is received?

**Comment by javivelasco** [comment]
Sure, makes a lot of sense. Do you want to PR it?

**Comment by ro-savage** [comment]
This should be fixed in v1.0.0. If its fixed, maybe close the issue? @sars

**Comment by javivelasco** [comment]
Gonna close, I think it should!
