### ISSUE TITLE
standarize component naming conventions

### ISSUE THREAD

**Issue by acornejo** [react-toolbox/react-toolbox#266]
Why is it Dropdown and not DropDown, and DatePicker instead of Datepicker or Autocomplete instead of AutoComplete? There are plenty of other examples AppBar is capitalized but Snackbar isn't, etc. 

It would be nice to have a standard with respect to component naming and capitalization. I have no opinion on the matter, anything which is consistent is good. Pick one and stick to it, FWIW I have a slight preference for not typing underscores in the components, which I guess it means I favor Camelcase over CamelCase (since that is the only thing which seems to follow a convention at the moment).

Btw, in case I haven't said it already, thank you for all the hard work that has gone into these components!!!

PS: I am also happy to contribute a PR to enforce a convention if you guys want to go ahead with this suggested change.

**Comment by nathanmarks** [comment]
> The app bar, formerly known as the action bar in Android, is a special kind of toolbar that’s used for branding, navigation, search, and actions.


"App bar" is two words, hence the capitalization on "bar". ((https://www.google.com/design/spec/layout/structure.html#structure-toolbars))


Google refers to "Snackbar" as one word:
https://www.google.com/design/spec/components/snackbars-toasts.html

**Comment by javivelasco** [comment]
I see this ok actually
