### ISSUE TITLE
Sliders don't have a disabled state

### ISSUE THREAD

**Issue by delaneyj** [react-toolbox/react-toolbox#269]
`<Slider disabled/>` should allow the component to be seem but _grayed out_ or other form of visual cue that an input can not be changed.  Currently editable is used to display a number input but is probably misnamed as its more akin to `detailed` than `editable` as the component is editable where true or false.

**Comment by javivelasco** [comment]
Yes, it's a pending to do. We should do it as soon as possible.

**Comment by delaneyj** [comment]
Great, Seeing other issues such as z-index on the circle overlapping AppBar,etc but will wait for the proper release and retest.
