### ISSUE TITLE
Slider using text input dont send proper onChange value.

### ISSUE THREAD

**Issue by delaneyj** [react-toolbox/react-toolbox#276]
If you have a `<Slider editable/>`, click on text input and keyboard up/down the `onChange` deliver the correct value but if you input a number (such as changing the 5 to 51 and tab out or press enter) the `onChange` gives the previous value.

**Comment by javivelasco** [comment]
I've just tried to reproduce in `dev` branch and it is working properly. The last release is a little outdated and maybe it's an already fixed bug. Please, try in the `dev` branch or wait until tomorrow. We are releasing a new patch, just fixes.

If you get the error again reopen here, thanks!

Thanks for reporting!
