### ISSUE TITLE
Multiline input doesn't resize according to the number of lines

### ISSUE THREAD

**Issue by SimonSelg** [react-toolbox/react-toolbox#278]
Hey,

according to the docs, the multiline inputs textarea will
> grows and shrink according to the number of lines.

I assume this means something like [this](http://www.jacklmoore.com/autosize/).

However, this isn't implemented in the current version of react-toolbox. Is this just an mistake in the docs, or is it just not implemented yet? If that's the case, I'd create an PR for it.

Cheers,
Simon

**Comment by mrogelja** [comment]
+1 for a PR

**Comment by javivelasco** [comment]
Not implemented yet but it would be very nice!

**Comment by madisvain** [comment]
this would be a nice feature to add

**Comment by zhaoyao91** [comment]
+1
