### ISSUE TITLE
CSS Customization Documentation wrong

### ISSUE THREAD

**Issue by gabrielenosso** [react-toolbox/react-toolbox#281]
First, in the example of the customization through CSS in the doc there is the following code:
```
.customized > [data-role="label"] {
  color: green;
  font-weight: bold;
}
```

But there is no "data-role" attribute at all, so it should be:
```
.customized > [data-react-toolbox="button"] { ... }
```

Second, the one nesting level customization for the button is not working: it is overwritten by some rules which have more "specification".

In my case, this is the CSS I get:
```
._1-QXNe2aJslDButq44WVYz:not([disabled])._3-PWAxo248XvhVWntqnzB2, ._1-QXNe2aJslDButq44WVYz:not([disabled])._3hjH1ouNBK0tIZ4CNh0Ea3 {
    color: #212121;
    background-color: white;
}

.customized > [data-react-toolbox="button"] {
    background-color: #3f51b5;
}
```

As you can see, the 'customized' rule is overwritten by the first one.

**Comment by javivelasco** [comment]
Yes, we mentioned this here #270. Some data attributes are missing but the best way to discover them is to add and PR as they are needed. The specificity problem is present too but sometimes I couldn't find a way to get the styles working with a different rule.

You *should* be able to override styles out of theming but it shouldn't be very common
