### ISSUE TITLE
ProgressBar circular is quiet big

### ISSUE THREAD

**Issue by gabrielenosso** [react-toolbox/react-toolbox#284]
The ProgressBar circular version, which is used a lot in Material Design apps, is really big.
As you can see from the Material Design web page (https://www.google.com/design/spec/components/progress-activity.html#progress-activity-types-of-indicators), it should be about 38px.

The one in React Toolbox is about 52px.

The fact is that it's quite hard to change the size of the component (if you use transform: scale() it doesn't look good).

A simple solution could be to have some props like "small" and "big".
So you could have 3 sizes: default (38px), small (24px), big(52px).

And maybe it could also change the stroke-width...

**Comment by gabrielenosso** [comment]
The problem about customizing the scaling is given to the fact that the "circle" element in the React Toolbox version is not rotating on its center.

In the following code, the "circle" elements rotates on itself: http://codepen.io/jczimm/pen/vEBpoL
Indeed you can easily change the width of the container and the stroke-width to customize it.

While in the React Toolbox version, if you change the width, it doesn't work well anymore.

**Comment by javivelasco** [comment]
We'll take a look on it. Thanks for the feedback!

**Comment by neverfox** [comment]
> it should be about 38px

I don't think the spec makes any claims about any one standard size. However, given the recommendation to encircle FABs, that would mean at least two sizes are spec: 56px and 40px (actually slightly large to be outside the button). In any case, I think your recommendation for how it should be implemented is right, but the size should be completely customizable.

**Comment by gabrielenosso** [comment]
Customizable Size and Width would be the best thing to have of course :)

**Comment by javivelasco** [comment]
I think we can provide a property to have a straightforward way to create the component with custom size. The only problem I see is that in that case the component should be spliced into two different components since the width property makes no sense at all for the linear `ProgressBar` and creates confusion

**Comment by mattkauffman23** [comment]
Being able to set the size would be helpful for me too. I'm trying to use a smaller version of the circular `ProgressBar`. I'm in favor of splicing into two components. In addition to the props the component takes being different for the two cases, `ProgressBar`, at least to me, means something long and rectangular (like a bar graph) so its not a great name for the circular indicator. In the material style guide it looks like they prefer the term "Progress Indicator". So maybe `CircularProgressIndicator` and `LinearProgressIndicator`. Or if those are too long just `CircularProgress` and `LinearProgress`.

**Comment by javivelasco** [comment]
Yes, we definitively have to split the component if a sizing prop should be available. More opinions?

**Comment by djdawson3** [comment]
Is there any workaround for this in the meantime? We would like to use a circular progress indicator in our app, but we can't right now because it's too large.

**Comment by javivelasco** [comment]
I think there is nothing done for now. The right thing could be to add a prop to override sizing. A classname is not valid since sizing is related to svg props... I'm very busy lately so I cannot do it...

**Comment by cdroulers** [comment]
I was able to resize it decently using CSS, since the SVG is inline, using the following: 

```sass
  [data-react-toolbox="progress-bar"] {
    width: 1em;
    height: 1em;
    
    svg > circle {
      cx: 10;
      cy: 10;
      r: 8;
    }
  }
```
I had to play around with `cx`, `cy` and `r` to get it to be mostly centered, but it wasn't too bad.

**Comment by sanfilippopablo** [comment]
Wouldn't this be easy to implement using SVG's viewBox property?

**Comment by javivelasco** [comment]
Yeah probably. In any case if it's possible to resize using CSS I'd rather close the issue... Please reopen if you think we should do something about this.

**Comment by sanfilippopablo** [comment]
It's posible, but not easy. The ideal would be the ability to resize it using width and height on the top element. viewBox makes this possible. Leave it closed if you want. If a make some time later, I can send a PR.
