### ISSUE TITLE
AutoComplete can't customize suggestions .active state

### ISSUE THREAD

**Issue by rgranger** [react-toolbox/react-toolbox#286]
Here is my code to override the AutoComplete component :

```
.autocomplete {
    & > [data-react-toolbox="input"] > label {
        color: $color-text-secondary;
    }

    & > [data-react-toolbox="input"] + ul {
        background-color: $color-black;
        color: $color-white;
        li:hover, li:active {
            background-color: #7f7f7f; //!NOT WORKING for active !
        }
    }
}
```

I have only tried with the AutoComplete component, but I guess it is the same for every component with a list. Since I want to make a dark themed application, It is very painful to overwrite every component with selectors like the ones above (since i can't overwrite the CSS modules classes because of their hash).

Moreover, I couldn't find a way to overwrite the .active class which is set when you select a different suggestion with the keyboard (and the default color is too close to $color-white, making the component unreadable).

My suggestion is, instead of using classes with CSS modules (which can't be overriden), would it be possible to define every rules with data-react-toolbox-role, so we can override every nodes inside a component ?

So my code would look this way :

```
.autocomplete {
    & > [data-react-toolbox="input"] > [data-react-toolbox="label"] {
        color: $color-text-secondary;
    }

     [data-react-toolbox="suggestions"] {
        background-color: $color-black;
        color: $color-white;
        & > [data-react-toolbox-suggestions="li"]:hover, 
        & > [data-react-toolbox-suggestions-li-hover="true"], 
        & > [data-react-toolbox-suggestion-li-active="true"] {
            background-color: #7f7f7f;
        }
    }
}
```

Another solution would be to make every _config.scss files overridables.

The config file for the AutoComplete component is like this :

```
$autocomplete-color-primary-contrast: $color-primary-contrast;
$autocomplete-color-primary: $color-primary;
$autocomplete-overflow-max-height: 45vh;
$autocomplete-suggestion-active-background: $palette-grey-200;
$autocomplete-suggestion-padding: $unit;
$autocomplete-suggestions-background: $color-white;
$autocomplete-value-border-radius: .2 * $unit;
$autocomplete-value-margin: $unit * .25 $unit * .5 $unit * .25 0;
$autocomplete-value-padding: $unit * .5 $unit * .75;
```

But i couldn't find a way to overwrite $autocomplete-suggestion-active-background in my code.
Using toolbox-loader I was able to override the _colors.scss and _globals.scss, but that's all. Is there any way to override the variables defined inside the _config.scss files for every component ?

**Comment by rgranger** [comment]
Could anyone answer me, before i move on to https://github.com/jscissr/react-polymer https://elements.polymer-project.org/browse?package=paper-elements ?

**Comment by javivelasco** [comment]
Hi @rgranger sorry for the late response.

The proper way to handle theming is overriding sass variables as it's explained in the documentation. You can use the react toolbox example repository to guide yourself in the configuration. About the data-react-toolbox attributes, you are right. The best would be to add attributes for every node that is likely to be customized. We just accepted a PR about it so it will come next weekend with a new release

**Comment by jasonkylefrank** [comment]
Hi @javivelasco. You mentioned above that

> The best would be to add [`data-*`] attributes for every node that is likely to be customized. We just accepted a PR about it so it will come next weekend with a new release

Can you elaborate on this?  Which PR was this?  Are the changes in the dev branch right now?  I was looking over the first few components (dev branch and others) and mostly I just see `data-react-toolbox` attributes on _wrapper_ `div` elements (not _sub-elements_ of the component).

**Comment by javivelasco** [comment]
Now you should with the new approach!
