### ISSUE TITLE
Using with Meteor

### ISSUE THREAD

**Issue by dagatsoin** [react-toolbox/react-toolbox#287]
Coming from Material-ui where I am not confortable with the complexity of custimization. I heard react-toolbox uses CSS Module.

I am actually facing an issue with Meteor `Error: Cannot find module './style'`.
I don't know if there is a way to use it with Meteor without Webpack. I have never used Webpack and as far as I know it does a lot of grunt work that Meteor already does with babel, building, modules etc.

So is it possible (and how) to use React Toolbox with Meteor?

**Comment by kagux** [comment]
It looks like you're missing css modules loader.  Quick googling gave me this [article](http://nathantreid.com/css-modules-for-meteor/) on css modules with meteor. That should solve styles loading.

**Comment by dagatsoin** [comment]
Thx I will try this. 
About the customisation. Is there a particular workflow to know?
Have I access to all components tree css properties or only customization pount like material-ui?

**Comment by dagatsoin** [comment]
Good news for this issue. @nathantreid is working of a new version of meteor-css-modules https://github.com/nathantreid/meteor-css-modules/issues/1#issuecomment-179084462

**Comment by dagatsoin** [comment]
According to @nathantreid advice I will try to male a compile plugin for meteor to mimic webpack.

I wonder how are handle the scss. Could someone validate those steps?
 1- babel opens the .jsx file and read 'import styles from "./styles"'
 2- babel opens .scss file
 3- postcss-scss import mixins, variables, etc. 
 3- babel compiles the .jsx file (taking account an ./style as an object)
 4- sass is compiled and added to a unique css file

Is that correct?

One thing I don't understand is what is imported by the transpiled code of `import "./style"`

**Comment by javivelasco** [comment]
I didn't check the internals actually, we should check the code for scss loader. I don't think it's babel responsibility.

**Comment by DonHansDampf** [comment]
Anything new on this? I want to use react-toolbox with meteor (1.2 would be fine). Seems like i cant use the meteor-css-modules since react-toolbox doesnt use mss files. Any workaround?

Greetings

**Comment by nathantreid** [comment]
I'm working (when time permits) on enabling sass support in https://github.com/nathantreid/meteor-css-modules. One of the blockers for react-toolbox support right now is that Meteor 1.3-beta.12 doesn't allow me to change the output filenames (which means the style imports that react-toolbox uses (``` import style from './style'; ```) don't work as Meteor writes out the file name as style.scss.js instead of just style.js.
It looks like this is fixed in the latest betas, but they don't currently run on Windows so I haven't been able to use them.
Anyways, support should be coming "soon".

**Comment by javivelasco** [comment]
That sounds awesome @nathantreid ! 🤗

**Comment by iovative** [comment]
Hey @nathantreid so your package will work with the newest 1.3-rc.2 running on OSX correct?  I am having this exact issue running 1.3-rc.2/mantra/react.

**Comment by gadicc** [comment]
@nathantreid forgot to mention here that he [succeeded](https://forums.meteor.com/t/css-modules-for-meteor-without-webpack/19682/11?u=gadicc) :)

**Comment by javivelasco** [comment]
Amazing. Do you guys think this should be documented? Can anybody do it?

**Comment by iovative** [comment]
hey @javivelasco, any plans for a grid system?

**Comment by javivelasco** [comment]
Well, I'm experimenting with grids and CSS modules and I don't think it should be included in the project. What I'm doing with other projects is to create a `scss` stylesheet with some grid classes. Then, when I'm composing a `Layout` component I import the scss from the Layout scss file. That allows to `import style from './Layout.scss'` and then just use it `className={style.column2of6}` for example.

Do you guys think it's useful? Maybe we can open an issue to talk about it

**Comment by javivelasco** [comment]
Please check #498, maybe it's useful to use in meteor
