### ISSUE TITLE
problem with Typescript

### ISSUE THREAD

**Issue by davidmoshal** [react-toolbox/react-toolbox#288]
wasn't able to get React-Toolbox working with Typescript:
- `import ToolboxApp from 'react-toolbox/lib/app';`

received this error:
- `error TS2307: Cannot find module 'react-toolbox/lib/app'.`

I subsequently found this similar project:
http://www.material-ui.com/#/
- it seems to work out of the box without any additional css config

**Comment by wrench7** [comment]
I'm also having issues getting react-toolbox and Typescript to play nicely.

I'm using ```import {Button} from 'react-toolbox';``` which is throwing an "error TS2307: Cannot find module 'react-toolbox'."

Perhaps the guys that were on this issue thread (https://github.com/react-toolbox/react-toolbox/issues/199) can chime in with some assistance :-)

**Comment by javivelasco** [comment]
Yeah, I'm sorry I can't help too much with Typescript issues since I have no experience with it at all. All I can say @davidmoshal is that Material UI doesn't need any CSS configuration because they use inline styles. If you want to use React Toolbox, since it uses CSS modules, you have to include some configuration. Anyway, you have an example project to guide you.

**Comment by wrench7** [comment]
I believe the issue I'm having is to do with having the typedefs included from react-toolbox's package.json file. If I move them into the typings folder that tsd manages and remove the typings property in the react-toolbox package.json then things work.

Will wait to see if one of the TS gurus from that other thread know anything about why that might be.

**Comment by wrench7** [comment]
Ok, after a bit more digging (and reading the docs!) I think I know have a handle on what's going on.

My tsconfig.json file has ``` "exclude": ["node_modules", "config", "dev_server.js"]``` in it, which is obviously going to not pickup the react-toolbox.d.ts file buried deep in the node_modules folder.

I'm adding it back in with:
```
"files": [
    "node_modules/react-toolbox/react-toolbox.d.ts"
  ]

This Stackoverflow article helped shed some light on what was going on - http://stackoverflow.com/questions/28989399/do-i-have-to-reference-typescript-definition-in-every-file
```

**Comment by javivelasco** [comment]
Great!

**Comment by wrench7** [comment]
I didn't open this issue, so am not sure whether my findings will help @davidmoshal or not...

**Comment by wrench7** [comment]
I've also now discovered that having exclude and files properties isn't allowed at the same time in the tsconfig.json file. Read here for more insight https://github.com/Microsoft/TypeScript/wiki/tsconfig.json#details
