### ISSUE TITLE
Ripple can try to set state after unmounting

### ISSUE THREAD

**Issue by neverfox** [react-toolbox/react-toolbox#289]
If your click handler on a Ripple-wrapped component does a transition that unmounts the component, you end up with a warning because of [this line](https://github.com/react-toolbox/react-toolbox/blob/dev/components/ripple/Ripple.jsx#L50):

```
Warning: setState(...): Can only update a mounted or mounting component. This usually
means you called setState() on an unmounted component. This is a no-op. Please check
the code for the undefined component.
```

**Comment by javivelasco** [comment]
This is very interesting. I think it may be one of those cases where it would be nice to use a `setTimeout`. Since the ripple has an animation, probably you'd want to watch it for some milliseconds before unmounting. In that scenario I think is perfectly justified, what do you think?

**Comment by neverfox** [comment]
Yeah, I just noticed that the animation is essentially wasted because the transition happens so quickly, so I'll try the setTimeout.

**Comment by neverfox** [comment]
It might be more elegant, and adaptable to changed animation times, if there was a prop for a rippleEnd callback (which could say, fire an action that lets the transition proceed).

**Comment by javivelasco** [comment]
Yeah, let's do that

**Comment by dlebedynskyi** [comment]
any news on this fix guys?

**Comment by javivelasco** [comment]
I've added a callback `onRippleEnded`. It should be enough to use it if you are getting these errors. Coming in next release!
