### ISSUE TITLE
Reference to app theme in docs

### ISSUE THREAD

**Issue by janesconference** [react-toolbox/react-toolbox#29]
Hi there!

The Button doc page states:
> "A button  clearly communicates what action will occur when the user touches it. It consists of text, an image, or both, designed in accordance with your *app’s color theme*".

It's also evident in the example that the `accent` buttons get the accent color in what seems to be a "standard" indigo-pink Material Design theme.

Is there any way to define themes? If there's not, how do we set the primary and accented colors? Via style sheets? Or is there a different mechanism to it?

**Comment by javivelasco** [comment]
Hi!

Of course, I've written in the [installation page](http://react-toolbox.com/#/install) how themes are going to be defined. As you can see, if you want to take the most of React Toolbox you should be using CSS Modules with webpack workflow. Being that the case, you will be able to include SASS Loader and a little loader we are writing to inject a custom SASS variables file with your custom settings prepending the builds of the modules included in your project.

That means that defining a new theme will be as easy as setting the color variables of the project a SASS configuration. By default we have (taken from MDL):

```scss
$color-primary: $palette-indigo-500 !default;
$color-primary-dark: $palette-indigo-700 !default;
$color-accent: $palette-pink-a200 !default;
$color-accent-dark: $palette-pink-700 !default;
$color-primary-contrast: $color-dark-contrast !default;
$color-accent-contrast: $color-dark-contrast !default;
```

You'll just need to write a file defining your custom colors. We just went live today and the loader is not ready yet, but it will be soon with a configuration section explaining the setup. 😁

**Comment by janesconference** [comment]
Cool, thank you!
