### ISSUE TITLE
material-icons is not minification safe?

### ISSUE THREAD

**Issue by BerndWessels** [react-toolbox/react-toolbox#291]
Hello
I use webpack and the following SASS loader

    var sassLoader = {
    test: /(\.scss|\.css)$/,
    loader: (!BUILD || TEST) ? 'style!css?sourceMap&modules&importLoaders=2!postcss!resolve-url!sass?sourceMap!toolbox' :
      ExtractTextPlugin.extract('css?sourceMap&modules&importLoaders=2!postcss!resolve-url!sass?sourceMap!toolbox')
    };

This will result in minified css - which works fine apart from the `material-icons` class.

It seems the way `react-toolbox` applies the `material-icons` class is not taking part in the css minification process.

Can you confirm this? Can you fix this?

Thanks
Bernd

**Comment by lamuertepeluda** [comment]
I confirm I have the same problem! In my Google MDL (non-react) project I was able to use SCSS within my projects in order to import Material Icons. 

Only way I found to make it work is:
```javascript
require('material-design-icons-iconfont/dist/material-design-icons.css'); //SCSS would work fine but conflicts with ExtractTextPlugin as mentioned in this issue.
require('roboto-fontface/css/roboto/roboto-fontface.css'); //roboto fontface SCSS appears to be screwed up because of font path so I was using CSS also with MDL
require('scss/style.scss'); //where I import all react-toolbox stuff and I add my stuff
```

This is my webpack.config.js loaders config:
```javascript
{
    test: /\.scss$/,
    loader: ExtractTextPlugin.extract('style', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass')
},
// {
//     test: /\.scss$/, - works fine with other frameworks e.g. Google MDL but screws everything up with react-toolbox
//     loaders: ['style', 'css', 'postcss', 'sass']
// },
{
     test: /\.css$/, //only way to import material icons so far
     loaders: ['style', 'css', 'postcss']
 },
```

**Comment by javivelasco** [comment]
As it's said in the documentation, we assume you are including yourself material icons. The only requirement for this to work is that classnames should be global. You would have to leave them out of the build importing them from a CDN or include them with a different loader.

**Comment by lamuertepeluda** [comment]
@javivelasco Indeed. This library is awesome.

Anyway what you suggested is exactly how I got things working in the end:

```javascript
//Use extract text plugin only for react toolbox
{
    test: /\.scss$/,
    include: [path.resolve(__dirname, 'node_modules', 'react-toolbox')],
    loader: ExtractTextPlugin.extract('style', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass')
},
{
    test: /\.scss$/,
    exclude: [path.resolve(__dirname, 'node_modules', 'react-toolbox')],
    loaders: ['style', 'css', 'postcss', 'sass']
},
```

In case this could be helpful for somebody else. I included [Material Icons from this npm package](https://www.npmjs.com/package/material-design-icons-iconfont) and [Roboto font from this package](https://www.npmjs.com/package/roboto-fontface). Of course you may rely on CDN but I feel more comfortable having everything bundled in my dist folder. I'm using url loader for fonts and other stuff and webpack html plugin for generating html files.

As a small caveat, material icons css from the aforementioned (Google Official) package sets 1em height for .material-icons class, which conflicts with react-toolbox rules resulting in misaligned icons. Therefore setting:
```scss
.material-icons {
     height: auto;
}
```
resolves the problem.
