### ISSUE TITLE
Overriding 'active' styles in Tab component with CSS Modules

### ISSUE THREAD

**Issue by joevbruno** [react-toolbox/react-toolbox#294]
Although this is somewhat of a CSS-Modules question, it pertains directly to React-Toolbox's Tab component. I want to override some of the styles (not just color) of a Tab component when it is active. I am also using CSS Modules. How can I target the active class using CSS Modules? I have documented the question on [stack-overflow]( http://stackoverflow.com/questions/35209924/css-modules-react-and-overriding-css-classes), but so far the answer is basically 'you cannot do it'. Am I missing something? 

If I am not missing anything and it cannot cleanly be done with CSS Modules, could we look at adding an activeClassName prop to the Tab component's API?  Although I have thought of some other ways to solve the problem, such as using the `onActive` prop to fire a callback that would use findDOMNode to manually apply inline styles or using a css selector that was looking for a className that contains 'active' in it, these are not particularly clean solutions. Thoughts? Thanks for your time, and your hard work maintaining this lib!

**Comment by javivelasco** [comment]
Thank for your kind words @joevbruno 

Truth is you can't override the class as you guessed. For sure, adding an `activeClassName` prop can be an option. Another one is to make the `active` class `global` so you can target it directly. Theming is being an important issue in case you want a very specific modification. Anyway, I think all of this issues pop up as the lib is used and providing better customization ways is always good.

I'll be happy to accept a PR about this :)

**Comment by savkaoleg** [comment]
I had the same problem. My solution: label[class*="style__disabled___"] { opacity: 0.5; }

**Comment by sosaucily** [comment]
addressing this in https://github.com/react-toolbox/react-toolbox/pull/386
