### ISSUE TITLE
Input component with Hint and Errors following Material Design Errors Patterns

### ISSUE THREAD

**Issue by gabrielenosso** [react-toolbox/react-toolbox#295]
It would be great to implement the Hint and Error features following the guidelines in this link:
https://www.google.com/design/spec/patterns/errors.html#errors-user-input-errors

**Comment by gabrielenosso** [comment]
I found out that the error feature is there, it is just not documented.

**Comment by javivelasco** [comment]
Hi @gabrielenosso ! Where are you missing documentation? The input has a documented `error` prop in the docs.
