### ISSUE TITLE
Add the ability to change the table head titles

### ISSUE THREAD

**Issue by derekstavis** [react-toolbox/react-toolbox#296]
Currently, `<TableHead>` uses model keys as the title of table headings. Adding the ability to change the title in the model would be nice. My proposal is that a new key `title` is added to the model, and is used when available. When not available, fallback to using object key. I can work on such PR, if you do find this interesting upstream.

**Comment by javivelasco** [comment]
I think its a good enhancement with no breaking changes. I'd be happy to accept a PR about it!
