### ISSUE TITLE
Dropdown stops working if rendered in form and tab is used.

### ISSUE THREAD

**Issue by YoYuUm** [react-toolbox/react-toolbox#297]
I'm using some dropdown components in a form, without using a custom template. I have realized that if I change from input to input using tab, the dropdown components break throwing the following error:
`Uncaught TypeError: Cannot read property 'label' of undefined.`
I have notice that this.getSelectedItem() in the dropdown component is returning undefined, and I guess it's related with the code happening onMouseDown not getting executed because the input doesn't get the focus by clicking on it.

**Comment by javivelasco** [comment]
This is very interesting, looking at it! Thanks @YoYuUm

**Comment by javivelasco** [comment]
This should be fixed already!

**Comment by felipeleusin** [comment]
Hi,

The problem with this was the change to only render the active tab. If you have a component with it's own state, it gets unmounted and destroyed.

My solution is to pass a prop to the Tab component onlyRenderActive that defaults to false (to keep with the same way as 0.14) that controls if it will render all the tabs or only the active.

What do you guys think? I can send this PR

**Comment by jeffreywescott** [comment]
Yeah ... I misunderstood this bug report, perhaps. I interpreted "and tab is used" to mean "tabbing through the form fields with the keyboard". There _is_ a bug, as I described above, but it might be a different / new issue. LMK if you'd like me to file it as a new issue.

**Comment by felipeleusin** [comment]
Maybe it was me. I read the issue and immediately thought of my case... I'll send a repro in a new issue and fix it.

**Comment by javivelasco** [comment]
Thanks @felipeleusin ! It makes a lot of sense to have that prop. In fact, for this kind of component, probably even it should default to `false`

**Comment by ktaras** [comment]
I also reproduced the bug described by @jeffreywescott 
When you have a form with dropdown and you're tabbing through it the value of dropdown gets changed and returns a label-attribute, but not a value-attribute of source item.

**Comment by javivelasco** [comment]
Yes please!

**Comment by javivelasco** [comment]
I think the issue was that we were spreading the `onChange` callback to the `Input` element. Then it was called with the current value. As we want to display the `label` as selected value, that's the passed value to the input. This way, `Dropdown` onChange was called with the `Input` value which was actually the `label`. It has been solved by adding it's own tab level, removing the tabIndex from `Input` and finally, extracting the `onChange` prop instead of passing it down to the `Input`.
