### ISSUE TITLE
Sidebar is blocking the content

### ISSUE THREAD

**Issue by alvinsj** [react-toolbox/react-toolbox#30]
is it an expected behaviour? 

![image](https://cloud.githubusercontent.com/assets/243186/10885807/b0d76be2-81b1-11e5-8d30-cb65988e7c5f.jpeg)

**Comment by javivelasco** [comment]
Yes, I'm working now on a responsive version. Since the playground doesn't make too much sense in a mobile platform it's not done yet. Coming really soon!

**Comment by alvinsj** [comment]
:+1:
