### ISSUE TITLE
UNMET PEER DEPENDENCY normalize.css@^3.0.3, UNMET PEER DEPENDENCY react-addons-css-transition-group@^0.14.0

### ISSUE THREAD

**Issue by wzup** [react-toolbox/react-toolbox#300]
I have issues installing `react-toolbox` and eventually making bundles with `browserify`. Here is what I get during installation:

```
$ npm install --save react-toolbox
npm WARN install Couldn't install optional dependency: Unsupported
app@0.0.0 c:\Users\user\node\app
├── UNMET PEER DEPENDENCY normalize.css@^3.0.3
├── UNMET PEER DEPENDENCY react-addons-css-transition-group@^0.14.0
└── react-toolbox@0.14.1

npm WARN EPEERINVALID mongodb-core@1.2.26 requires a peer of kerberos@~0.0 but none was installed.
npm WARN EPEERINVALID react-toolbox@0.14.1 requires a peer of react-addons-css-transition-group@^0.14.0 but none was installed.
npm WARN EPEERINVALID react-toolbox@0.14.1 requires a peer of normalize.css@^3.0.3 but none was installed.
```

And when I try to make a bundle I get this error:
```
[ERROR][vendorsd task]:  Cannot find module './style' from 'c:\Users\user\node\app\node_modules\react-toolbox\lib\dropdown'
[ERROR][vendorsd task]:  Cannot find module './style' from 'c:\Users\user\node\app\node_modules\react-toolbox\lib\input'
```

What do all those errors and warnings mean? How to solve them?
I neither have those packages in my `package.json` nor have them in `/node_modules`. So how can it be `UNMET PEER DEPENDENCY` if there is no even such a package installed.

They are listed as `devDependencies` of `react-toolbox`. Why doesn't `react-toolbox` install them?

**Comment by javivelasco** [comment]
If I'm not wrong, this is an npm 3 issue that it's not directly related to React Toolbox. Also, if you are trying to get a build using browserify, be aware that we give no support. For now, if you want to use react toolbox, you should use webpack (which I think is not a problem though). It would be great if somebody create a test with browserify, sadly right now I don't have the time to do so :(

**Comment by javivelasco** [comment]
I'm closing since this kind of issue is not related to toolbox but npm!

**Comment by wzup** [comment]
> _if you are trying to get a build using browserify, be aware that we give no support. For now, if you want to use react toolbox, you should use webpack_

This is pretty disappointing for those who already have working apps with configured browserify build system. It means if we want to utilize `react-toolbox` in the app, we must switch everything to `webpack` environment. Don't even know what might be faster, find ways to use `react-toolbox` with `browserify` or learn webpack and recreate build system.

**Comment by javivelasco** [comment]
Sorry about that. I have no experience with browserify so I think that the best way to provide support is if anybody with experience can get a configuration working with css modules. The only reasons why we are supporting webpack is because to prepend custom configuration variables we need a loader and because of css modules. But as far as I know there is a demo of css modules with browserify so I think it's perfectly possible

**Comment by jasan-s** [comment]
I'm getting the same errors & I'm using Webpack: 
```
+-- UNMET PEER DEPENDENCY immutability-helper@~2.0.0
+-- UNMET PEER DEPENDENCY normalize.css@~4.2.0
+-- UNMET PEER DEPENDENCY react-addons-css-transition-group@~0.14.0 || ~15.3.0
```

**Comment by Deilv** [comment]
react-toolbox includes those packages in its "peer dependencies". However, peer dependencies are no longer supported in npm 3.x that comes with nodejs 6.x. You either need to install those packages manually or use nodejs 4.x instead, until this is fixed.

**Comment by stereobooster** [comment]
```
UNMET PEER DEPENDENCY react-addons-css-transition-group@~0.14.0 || ~15.3.0
```

```
{
  "name": "test-custom-react-scripts",
  "version": "0.0.1",
  "private": true,
  "devDependencies": {
    "custom-react-scripts": "0.0.13"
  },
  "dependencies": {
    "google-map-react": "^0.20.0",
    "immutability-helper": "^2.0.0",
    "react": "^15.3.2",
    "react-dom": "^15.3.2",
    "react-toolbox": "^1.2.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

node -v: v6.1.0
npm -v: 3.8.6

**Comment by javivelasco** [comment]
Peers should be installed manually guys. They are peers because you may need that dependency installed just once as it happens with react. Am I right?
