### ISSUE TITLE
Menu throws Exception if `{null}` is rendered

### ISSUE THREAD

**Issue by emirotin** [react-toolbox/react-toolbox#302]
Example:

```
const leaveRoom = this.hasPermission('ROOM_LEAVE')
      ? <MenuItem onClick={this.leave} icon="exit_to_app" caption="Leave" />
      : null

    return <IconMenu icon="more_vert">
      {leaveRoom}
      <MenuItem onClick={this.close} icon="close" caption="Close" />
    </IconMenu>
```

Here I want to only show the "Leave" menu item if the user has permissions to click it. The error thrown is
`TypeError: Cannot read property 'type' of null`.

I know I can set `disabled` for the item, but we don't want to tease the users with the actions they don't have permissions to run.

**Comment by javivelasco** [comment]
I see. It should be an easy fix, just checking in the `IconMenu` should be enough. Thanks for reporting this!
