### ISSUE TITLE
More components

### ISSUE THREAD

**Issue by equinusocio** [react-toolbox/react-toolbox#306]
I love react toolbox but It would be beautiful if there were more MD components (MUI have a lot of components). I can suggest this:
- Badge [MUI Example](http://www.material-ui.com/#/components/badge)
- Divider [MUI Example](http://www.material-ui.com/#/components/divider)
- Select Field [MUI Example](http://www.material-ui.com/#/components/select-field)
- Paper [MUI Example](http://www.material-ui.com/#/components/paper)
- Refresh Indicator [MUI Example](http://www.material-ui.com/#/components/refresh-indicator)

**Comment by javivelasco** [comment]
I think some components like `Paper` can be substituted or extracted from `Card`. I'm closing here in favor of #626

**Comment by equinusocio** [comment]
And other changes?
