### ISSUE TITLE
How can i change primary and accent colors?

### ISSUE THREAD

**Issue by LestaD** [react-toolbox/react-toolbox#308]

**Comment by LestaD** [comment]
@javivelasco @soyjavi @ustccjw?

**Comment by joevbruno** [comment]
@LestaD If you are using Webpack, checkout the [toolbox-loader](https://github.com/react-toolbox/toolbox-loader). That should get you started.

**Comment by LestaD** [comment]
@joevbruno what if i use Stylus instead of Sass?

**Comment by joevbruno** [comment]
@LestaD I think you would still utilize the Webpack toolbox-loader to change the default scss variables that React-Toolbox uses for CSS-Modules. Are you using Webpack? I assume you have a style loader that is handling the css-modules that React-Toolbox is using or are you using a built, complied version of React-Toolbox that is only css and ES5 JS?

**Comment by LestaD** [comment]
I use webpack, stylus loader. Can i use scss only for `theme.scss`?

**Comment by joevbruno** [comment]
I have only casually played around with Stylus, so I am somewhat ignorant in that respect; however, you can use whatever method you desire to handle styles in your project with React-Toolbox, but as far as what React-Toolbox uses internally, its SCSS / CSS-Modules all the way through. If you look at the _config.scss in any of the components, most of the color variables are being imported from another file. The theme.scss override that file. Thus, if you give react-toolbox a theme.scss, all of the scss in React-Toolbox needs to compile. So you cannot really use scss for _only_ theme.scss, but you could definitely use scss for only React-Toolbox. All of the classes that you pass as props to React-Toolbox and all of the scss in your project outside of React-Toolbox can use whatever method you desire to handle styles.  To sum it up, I think you will need either to add another loader to your Webpack config that handles scss or perhaps (possibly??) modify your existing stylus loader to also parse scss.

**Comment by LestaD** [comment]
@joevbruno thank you!
