### ISSUE TITLE
Two Dropdowns act independently. One never closes when the other is being opened

### ISSUE THREAD

**Issue by wzup** [react-toolbox/react-toolbox#314]
If you use two Dropdowns and open options of the first Dropdown, and then open options of the second Dropdown, the first Dropdown doesn't close. I stays open. It is against browser original `<select>` behavior. If you use two `<select>`s, one will always close when you try to open the other one. How to enable a behavior of original `<select>`s?

**Comment by javivelasco** [comment]
I think we are just missing a function call. There is a helper implemented to handle clicks outside components.

**Comment by wzup** [comment]
Don't understand what helper you mean. Is it a helper of `react-toolbox` itself or a helper of React library (https://facebook.github.io/react/tips/dom-event-listeners.html)? Could you please elaborate a bit more on that?

**Comment by wzup** [comment]
`Esc` key also doesn't close Dropdown.

**Comment by epilgrim** [comment]
I think the helper is https://github.com/react-toolbox/react-toolbox/blob/dev/components/utils/events.js#L35

**Comment by wzup** [comment]
Also this css creates wrong behavior:
```
// react-toolbox\lib\dropdown\style.scss

  &:not(.up) > .values {
    top: 0;  <-- with "top: 0" list of options appears over currently selected option
    bottom: auto;
  }
```

In genuine `<select>` element (and jQuery plugins too) if you click on `<select>`, the list of options appears ***bellow*** currently selected option. Not ***over*** it:
![jquery selectric - google chrome 2016-02-15 15 44 09](https://cloud.githubusercontent.com/assets/3880497/13042463/59d47bae-d3fb-11e5-9129-e00e2821b37a.png)
(http://lcdsantos.github.io/jQuery-Selectric/demo.html)

`react-toolbox` Dropdown options appears ***over*** currently selected option. It creates unexpected visual effect - you haven't chosen the option yet but suddenly it looks like it is already chosen for you. Looks not nice:
![react toolbox - google chrome 2016-02-15 15 57 47](https://cloud.githubusercontent.com/assets/3880497/13042685/18965f16-d3fd-11e5-9cb1-8067d205da18.png)


It can be fixed by setting `top: [some value]px;` but you experience unexpected behavior again: when you click currently selected option, Dropdows doesn't close. But has to. Try with that demo. Try to click on currently selected option. The list of options will appear and disappear:

![react toolbox - google chrome 2016-02-15 16 02 24](https://cloud.githubusercontent.com/assets/3880497/13042792/017c86ba-d3fe-11e5-930f-d18b713a2a85.png)

**Comment by epilgrim** [comment]
about the select not being closed when you click another select, I cannot reproduce that. If you try
```
class DropdownTest extends React.Component {
  state = {
    selected: 3
  };

  albums = [
    { value: 1, artist: 'Radiohead', album: 'In Rainbows', img: 'http://www.clasesdeperiodismo.com/wp-content/uploads/2012/02/radiohead-in-rainbows.png' },
    { value: 2, artist: 'QOTSA', album: 'Sons for the Deaf', img: 'http://static.musictoday.com/store/bands/93/product_large/MUDD6669.JPG' },
    { value: 3, artist: 'Kendrick Lamar', album: 'Good Kid Maad City', img: 'https://cdn.shopify.com/s/files/1/0131/9332/products/0bd4b1846ba3890f574810dbeddddf8c.500x500x1_grande.png?v=1425070323' },
    { value: 4, artist: 'Pixies', album: 'Doolittle', img: 'http://www.resident-music.com/image/cache/data/Emilys_Packshots/Pixies/Pixies_Doolittlke-500x500.jpg' }
  ];

  handleChange = (value) => {
    this.setState({selected: value});
  };

  customItem (item) {
    const containerStyle = {
      display: 'flex',
      flexDirection: 'row'
    };

    const imageStyle = {
      display: 'flex',
      width: '32px',
      height: '32px',
      flexGrow: 0,
      marginRight: '8px',
      backgroundColor: '#ccc'
    };

    const contentStyle = {
      display: 'flex',
      flexDirection: 'column',
      flexGrow: 2
    };

    return (
      <div style={containerStyle}>
        <img src={item.img} style={imageStyle}/>
        <div style={contentStyle}>
          <strong>{item.artist}</strong>
          <small>{item.album}</small>
        </div>
      </div>
    );
  }

  render () {
    return (
      <span>
      <Dropdown
        auto={false}
        source={this.albums}
        onChange={this.handleChange}
        label='Select your favorite album'
        template={this.customItem}
        value={this.state.selected}
      />
      <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
      <Dropdown
        auto={false}
        source={this.albums}
        onChange={this.handleChange}
        label='Select your favorite album'
        template={this.customItem}
        value={this.state.selected}
      />
      </span>
    );
  }
}

return <DropdownTest />;
```
in the sandbox here: http://react-toolbox.com/#/components/dropdown
it does close the previous select

**Comment by wzup** [comment]
About my comment here https://github.com/react-toolbox/react-toolbox/issues/314#issuecomment-184105880. 
I found an explanation in Google Material Design [specs for menus](https://www.google.com/design/spec/components/menus.html#menus-behavior):
> Menus are positioned over their emitting elements **such that the *currently selected* menu item appears on top of the emitting element**.

And where I was wrong:
> Do not display a duplicate of the selected menu item.

And:
> Positioning the menu below the emitting element separates it from its context.

So your menu appears correctly - over the emitting element. But it doesn't appear *such that the currently selected menu item appears on top of the emitting element*. It appears on top but below the emitting element.

**Comment by javivelasco** [comment]
Thanks for the update!
