### ISSUE TITLE
Autocomplete/Dropdown - multi select

### ISSUE THREAD

**Issue by tomasztomys** [react-toolbox/react-toolbox#319]
I have a problem, because I have to use multi select in my application, but in dropdown I can't make multi-select and make box (tags) of selected elements above input, because dropdown can't be multiple. Autocomplete can be multiple, but after each click, the select is hiding... User has to click to open select for each click (open select and find value - it's problem when it's more than a few elements).
Can you help me?

**Comment by javivelasco** [comment]
Exactly, this should be solved with #174
