### ISSUE TITLE
DatePicker other language

### ISSUE THREAD

**Issue by kodermax** [react-toolbox/react-toolbox#320]
How can i change language for DatePicker?

**Comment by javivelasco** [comment]
Not for now. But it can be a good improvement to provide a custom array months as a prop

**Comment by felipeleusin** [comment]
Would you guys be interested in using moment or Intl support? If not, I think just providing a format method that defines how to display the date would already help.

**Comment by javivelasco** [comment]
As few dependencies needed the best IMO. Also I think the format to display the date in a picker is specified in Material Design isn´t it?

**Comment by felipeleusin** [comment]
I couldn't find anything in the spec regarding the format. Imho, it should be localizable. Regarding the dependency Intl has less dependencies but needs polyfill for some browserd
