### ISSUE TITLE
Pagination for  Table

### ISSUE THREAD

**Issue by kodermax** [react-toolbox/react-toolbox#321]
Could you please add pagination for Table.

**Comment by javivelasco** [comment]
Pagination can be implemented as a higher order component. I think it's not table reponsibility

**Comment by mistre83** [comment]
Hi @javivelasco , how you will build an HOC for pagination ?

For example, you will merge the existing source with a new one ? In this way, the Table component will re-render the entire dataset... no ?

The visua effect is a full re-load of the table, right ?

**Comment by javivelasco** [comment]
Well, I did not wrote an example but I think that if you're willing to use a table providing a source, mutating that source should be enough to get a pagination. You can create a component that renders the `Table` and gets some props to render also buttons with prev and next. Tracking the current segment of the source you want to render would be the hoc responsibility. The visual effect depends on how you implement the source too.

If you use something like immutablejs each I think each row would compare the ref and would not get re-rendered. It all depends on what do you pass down to the `Table`. Maybe the terms I used were not correct, I was referring to a wrapper component that renders the table along with some controls, not exactly an hoc.

**Comment by junibrosas** [comment]
I found this cool react library which basically paginate your data.

https://github.com/AdeleD/react-paginate
