### ISSUE TITLE
TimePicker view problem

### ISSUE THREAD

**Issue by sars** [react-toolbox/react-toolbox#328]
Hi there,

Thanks guys for this library.

I have one problem with TimePicker that I don't know hot to fix
On the first dialog open, clock looks like 

<img width="226" alt="screen shot 2016-02-18 at 5 30 50 pm" src="https://cloud.githubusercontent.com/assets/226194/13148480/3b4899a0-d666-11e5-9558-35d1810c1ae3.png">

and then immediately changes to 

<img width="316" alt="screen shot 2016-02-18 at 5 29 54 pm" src="https://cloud.githubusercontent.com/assets/226194/13148481/3b4a41ec-d666-11e5-910b-38e80536f368.png">

Could you suggest me how to fix this?

**Comment by javivelasco** [comment]
Wow. Can you provide more information about the environment? Browser and version, if you customized the dialog with a new animation or something similar to reproduce it?

BTW, thanks for your kind words :)

**Comment by sars** [comment]
Chrome, last version,
I didn't customise dialog or picker component...
I didn't find the reason so far...

**Comment by sars** [comment]
hmmmm... may be this is related to SSR...
when i go from another page to target page with timePicker - if works fine
when i go directly to the target page (SSR rendering happens) - it works bad
