### ISSUE TITLE
Time Picker UI breaks when on 26 minutes in Chrome

### ISSUE THREAD

**Issue by MarcBalaban** [react-toolbox/react-toolbox#33]
![image](https://cloud.githubusercontent.com/assets/2932405/10898555/6ff24812-8180-11e5-9b7d-ef73b58a03cf.png)

**Comment by ustccjw** [comment]
In newest chrome, it's ok.

**Comment by MarcBalaban** [comment]
hmmm, odd.
![image](https://cloud.githubusercontent.com/assets/2932405/10899254/e30cb6c8-8187-11e5-94f4-bddf3d6e8366.png)

**Comment by ustccjw** [comment]
maybe you should debug yourself, i do not have this problem...

**Comment by danmartinez101** [comment]
@ustccjw I was able to reproduce it fairly quickly. I'll try debugging a bit when I have a free moment or two.
 <img width="473" alt="screen shot 2015-11-02 at 10 10 08 pm" src="https://cloud.githubusercontent.com/assets/2669819/10900500/9839d9c4-81ae-11e5-9d01-134165be52c2.png">

**Comment by javivelasco** [comment]
Maybe it can be related to Codemirror? Or it's possible to reproduce it from the specs page in the main project?

**Comment by soyjavi** [comment]
I think so.. maybe Codemirror is trolling us ;)

**Comment by rwfeather** [comment]
I can reproduce it as well, not just for 26, but also 4. 
![image](https://cloud.githubusercontent.com/assets/6589528/10922588/94fc080c-8241-11e5-841a-0f923859bdfa.png)

So it seems to be symmetrical.

**Comment by soyjavi** [comment]
I have tried without the playground and its working. Maybe codemirror is trolling us ;)

**Comment by adaojunior** [comment]
Timer Picker's UI looks different for me
![time-picker](https://cloud.githubusercontent.com/assets/4921294/10928018/147605fc-828c-11e5-98c9-fc22af9a4328.PNG)

**Comment by danmartinez101** [comment]
@adaojunior click on the 28 at the top to switch to the minutes selector and you should see the same thing.

**Comment by adaojunior** [comment]
@danmartinez101 Yeah, aparently it does not follow the specification https://www.google.com/design/spec/components/pickers.html#pickers-time-pickers

**Comment by javivelasco** [comment]
@adaojunior why is not ok with the spec??

**Comment by javivelasco** [comment]
@adaojunior just saw your previous comment. You have two flavors for Time Picker component. `format="24hr"` will render the 24 hours clock. If you want to stick to the spec (although you can find 24hr clock in Android), just change the format prop to `ampm`.

**Comment by adaojunior** [comment]
@javivelasco thanks

**Comment by TheDeveloperXYZ** [comment]
I cannot reproduce this error on Windows environment.

Guessing from Safari browser #49 and MarcBalaban picture (MacBook), I guess this glitch is exclusive to Apple software.

**Comment by rwfeather** [comment]
@TheDeveloperXYZ I'm able to reproduce a similar glitch on Windows 7 + Chrome.
