### ISSUE TITLE
This project is died?

### ISSUE THREAD

**Issue by kodermax** [react-toolbox/react-toolbox#331]

**Comment by javivelasco** [comment]
No. Just need contributors and people willing to help maintaining. I'm just one person and don't have time to spend on it every single day. I'm answering issues and reviewing PRs during the weekends, help is appreciated.

**Comment by kodermax** [comment]
Sadness, your project is better material-ui.

**Comment by javivelasco** [comment]
Thank you @kodermax ! Just need some community around it... I don't have too much spare time. Hopefully I will release a new version during the weekend and fix some bugs. :)

**Comment by kodermax** [comment]
Are you the one this project is done?

**Comment by javivelasco** [comment]
What do you mean?

**Comment by kodermax** [comment]
Project author is one?

**Comment by javivelasco** [comment]
[Mostly](https://github.com/react-toolbox/react-toolbox/graphs/contributors)
