### ISSUE TITLE
Color icon for FontIcon

### ISSUE THREAD

**Issue by kodermax** [react-toolbox/react-toolbox#335]
I can't set my color for material-icons.

**Comment by javivelasco** [comment]
You can change the color with CSS. The property in font icons is set to `currentColor` which means the color property. It is inherited so you can set a color for the parent element and the icon will get it

**Comment by jasan-s** [comment]
I can't seem to be able to change it either. Did you ever solve this @kodermax ? I'm setting the color in parent element and the iconMenu element, yet the color value is coming from theme.scss
