### ISSUE TITLE
Failed at the react-toolbox@0.14.0 start script

### ISSUE THREAD

**Issue by SMahil** [react-toolbox/react-toolbox#340]
I was trying installing react-toolbox. Got this error:

`> cross-env NODE_ENV=development UV_THREADPOOL_SIZE=100 node ./server

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8080
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1227:14)
    at listen (net.js:1263:10)
    at net.js:1372:9
    at nextTickCallbackWith3Args (node.js:486:9)
    at process._tickCallback (node.js:392:17)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:140:18)
    at node.js:1001:3

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! react-toolbox@0.14.0 start: `cross-env NODE_ENV=development UV_THREADPOOL_SIZE=100 node ./server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-toolbox@0.14.0 start script 'cross-env NODE_ENV=development UV_THREADPOOL_SIZE=100 node ./server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-toolbox package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development UV_THREADPOOL_SIZE=100 node ./server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-toolbox
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-toolbox
npm ERR! There is likely additional logging output above.`

**Comment by Kosta-Github** [comment]
> Error: listen EADDRINUSE 0.0.0.0:8080

Your port `8080` is already in use (by another service)...

**Comment by javivelasco** [comment]
Thanks @Kosta-Github !
