### ISSUE TITLE
typescript typings upgrade to typescript 1.8 

### ISSUE THREAD

**Issue by afaayerhan** [react-toolbox/react-toolbox#341]
with typecript 1.8.0 we would get this error anytime we reference react-toolbox.d.ts
Error:(1064, 5) TS2661: Cannot re-export name that is not defined in the module. I would like to send a pull request with fix. new to open source how can i do this?

**Comment by javivelasco** [comment]
Help with this?

**Comment by wrench7** [comment]
@afaayerhan => https://guides.github.com/activities/contributing-to-open-source/ :-)
