### ISSUE TITLE
[DatePicker] Select a date by clicking a number?

### ISSUE THREAD

**Issue by wzup** [react-toolbox/react-toolbox#342]
Is there a possibility to select a date by clicking a number, and not `OK` button? Like in Material-UI `autoOk={true}` property. So no need `OK` button for this behavior.

And how to close DP dialog by clicking outside of it? Now it closes only if you click `Close` button inside DP dialog.

**Comment by javivelasco** [comment]
For now we haven't this option but It should be not difficult to implement.
