### ISSUE TITLE
clean install breaks 

### ISSUE THREAD

**Issue by swarajd** [react-toolbox/react-toolbox#343]
require('./style') and import style from './style' breaks every time, when I cleanly install react hot boilerplate and react toolbox and try to use it

**Comment by stovmascript** [comment]
Make sure you have the right [`resolve.extensions`](https://webpack.github.io/docs/configuration.html#resolve-extensions) set in your webpack config - add `'.scss'` in addition to the defaults.

Example: https://github.com/react-toolbox/react-toolbox/blob/dev/webpack.config.development.js#L20

**Comment by javivelasco** [comment]
Thanks @stovmascript, I think the description for this issue is wrong. You just have a configuration issue, please check the examples to get it working, you shouldn't have a problem
