### ISSUE TITLE
Label not working properly with precompiled Input with type=Password

### ISSUE THREAD

**Issue by gabrielenosso** [react-toolbox/react-toolbox#346]
Hi all.
I found a strange problem: when the browser precompile the fields o a form (for example when you save your username and your password), the Password label remain in the placeholder place (it doesn't move up). So the dots of the password overlap the label.

But if I click anywhere in the page (not only in the form), then the label moves up.

See the image attached to understand the overlapping problem.
![iwas control center 4 0](https://cloud.githubusercontent.com/assets/4018887/13319646/694615fa-dbc3-11e5-9bae-82613ca28cd5.png)

**Comment by javivelasco** [comment]
Is it sure the password is getting the updated value via props?

**Comment by gabrielenosso** [comment]
Yes, of course it is.
The value is passed by props to both Input components

**Comment by gabrielenosso** [comment]
Strange thing is that it works perfectly in Firefox (the error happens in Chrome).

**Comment by gabrielenosso** [comment]
Update: it seems to be a Chrome issue (still open after some years):
https://bugs.chromium.org/p/chromium/issues/detail?id=352527

**Comment by javivelasco** [comment]
Wow, that's interesting, thanks @gabrielenosso 
Do you think we can do something to fix it?

**Comment by gabrielenosso** [comment]
Well honestly I don't know if there is a way to "emulate" it.

A solution that seems to be used is something like that: https://github.com/iamjoetaylor/vanilla-autofill-event (this is the vanilla version).

But of course it doesn't seem "clean".

**Comment by javivelasco** [comment]
Being a documented Chrome issue, maybe we can just wait for the next update. In case somebody wants to provide support, I think the component can be tweaked with the solution you provided. What do you think?

**Comment by boxcee** [comment]
@gabrielenosso did you get it to work with the solution you posted?

I didn't try the solution but when I check for the value of my input field it is empty, even though I can see the browser rendered something. Eventually clicking the input field will give me the autofilled value.

**Comment by gabrielenosso** [comment]
@boxcee, there is no clean way to do that.
It's a Chrome bug.

**Comment by mienaikoe** [comment]
webkit browsers now have the `-webkit-autofill` pseudo class when an input as autofilled. You still can't get the value from it, but you can know that a value exists. Perhaps react toolbox can move the label out of the way if it detects that the input element has this psuedo class?
