### ISSUE TITLE
Components are scaled up

### ISSUE THREAD

**Issue by brodeuralexis** [react-toolbox/react-toolbox#347]
I seem to be having problem setting up `react-toolbox`.  While the styles are loaded in a bundle, components are bigger than what they look like in the docs.

The window on the left is the docs and the window on the right is my application.

![sc2](https://cloud.githubusercontent.com/assets/11179144/13370963/43c18d76-dcce-11e5-8d5e-14842cceb198.PNG)

Here is a link to my application's code https://github.com/brodeuralexis/react-toolbox-test

| Program | Version |
|-------------|-----------|
| Node       | 5.5.0     |
| NPM       | 3.3.12   |
| Google Chrome | 48.0.2564.116 m |
| Windows | 8.1 |

For library versions, see `package.json`

**Comment by javivelasco** [comment]
You have to include the `commons.scss`. Check the [example repository](https://github.com/react-toolbox/react-toolbox-example). Styles are considering your root size is 10px but if you don't do it yourself or include the commons, it would be 16px which scales up the components

**Comment by brodeuralexis** [comment]
Thank you.

With this, it is now possible to rid myself of material-ui :smile:

**Comment by javivelasco** [comment]
👏

**Comment by MIGUELWAXX** [comment]
low pro...

**Comment by javivelasco** [comment]
@MIGUELWAXX ?

**Comment by MIGUELWAXX** [comment]
Peercoin, Namecoin Test Support Levels https://shar.es/1etah4 via @sharethis

https://shar.es/1etah4

The general consolidation in the crypto-market is still ongoing. But while BTC is making tentative gains, both Peercoin and Namecoin are drifting lower and testing important support levels. Let’s start with PPC and we’ll get back to Namecoin later on.


Read more...


This message was sent using ShareThis [http://www.sharethis.com]
