### ISSUE TITLE
[Dropdown] Permanent icon and a placeholder as an initial value

### ISSUE THREAD

**Issue by wzup** [react-toolbox/react-toolbox#348]
Is it possible now with Dropdown?

Initial state of Dropdown. An icon and a placeholder text. It's not `<option>`s' label text as a placeholder, it is exactly a placeholder text that will disappear on selection:

![expedia travel_ vacations cheap flights airline tickets airfares - google chrome 2016-02-28 16 40 26](https://cloud.githubusercontent.com/assets/3880497/13378292/b4beec02-de3c-11e5-8881-5bf5408a88b1.png)

And when an `<option>` is selected. Placeholder text disappeared but the icon left:

![expedia travel_ vacations cheap flights airline tickets airfares - google chrome 2016-02-28 16 50 22](https://cloud.githubusercontent.com/assets/3880497/13378296/e1ef7f8e-de3c-11e5-8201-41e4e9bce171.png)

Current `label` property has a little different behavior. And it doesn't disappear after selecting an option:
![react toolbox - google chrome 2016-02-28 17 09 08](https://cloud.githubusercontent.com/assets/3880497/13378318/0b447186-de3e-11e5-963a-47e9c4f59348.png)

**Comment by javivelasco** [comment]
Already done. If no value is selected, it will display the placeholder :)
