### ISSUE TITLE
Cannot resolve ./style in react-toolbox lib/components

### ISSUE THREAD

**Issue by FakhruddinAbdi** [react-toolbox/react-toolbox#349]
After installing react-toolbox over react-starter-kit i came across an error below:
` ERROR in ./~/react-toolbox/lib/list/ListCheckbox.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ./style in /Users/Username/WebstormProjects/projectName/node_modules/react-toolbox/lib/list
     @ ./~/react-toolbox/lib/list/ListCheckbox.js 23:13-31
`

And this error iterate for all react-toolBox components used in my codes
I have tried to change webpack config but wasn't helpful

**Comment by joevbruno** [comment]
This is probably happening because the starter kit does not have the correct css-loaders for webpack. Look at React Toolbox's webpack file and under the loaders you will see one for css/scss. Copy that line into your webpack file and NPM install css-loader, sass-loader, and auto prefixer. Then run webpack and all should be well. You may need to also npm install the extract text plugin for webpack too if you want to output a css file.

**Comment by egbertp** [comment]
I had the same issue. See what I've changed in my PR here: https://github.com/coryhouse/react-slingshot/pull/55/files

**Comment by javivelasco** [comment]
You have to add node_modules/react-toolbox to be processed by webpack too

**Comment by FakhruddinAbdi** [comment]
Thank you for your replies. @javivelasco Could you please provide a quick tuts for your solution.
How to add node/modules/react-toolbox to webpack?

**Comment by FakhruddinAbdi** [comment]
I have tried all suggested solution, but still its not working 
You can check my webpack.config.js in the link below 
https://github.com/kriasoft/react-starter-kit/blob/master/tools/webpack.config.js

**Comment by javivelasco** [comment]
You are not telling webpack to resolve css extension nor explicitly including node_modules!

**Comment by jesselve** [comment]
I have wasted my entire day on this issue.  More specific help would be greatly appreciated!
Things I have already tried:

- I have npm installed css-loader, sass-loader and auto-prefixer as well as the extract-text-webpack-plugin.

- I have added '.css' to the list of "resolve extensions" (even though this is not present in the webpack.config.development.js file)

- I have explicitly included "node_modules"

- I have explicitly included "node_modules/react-toolbox/lib/button" (as a test)

If anyone is able to resolve this, please provide a comment with the steps!

**Comment by kagux** [comment]
Share your webpack config

**Comment by jesselve** [comment]
var path = require('path');
var webpack = require('webpack');
const autoprefixer = require('autoprefixer');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  devtool: 'eval',
  entry: [
    'webpack-dev-server/client?http://localhost:3000',
    'webpack/hot/only-dev-server',
    './src/index'
  ],
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/static/'
  },
  resolve: {
    extensions: ['', '.jsx', '.css', '.scss', '.js', '.json']
  },
  module: {
    loaders: [
      {
        test: /\.(js|jsx)$/,
        loader: 'babel',
        exclude: /(node_modules)/
      }, {
        // "include" is commonly used to match the directories
        include: [
          path.resolve(__dirname, "node_modules"),
          path.resolve(__dirname, "node_modules/react-toolbox/lib/button")
        ],
        test: /\.(scss|css)$/,
        loader: ExtractTextPlugin.extract('style', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass?sourceMap')
      }
    ]
  },
  postcss: [autoprefixer],
  plugins: [
    new ExtractTextPlugin('spec.css', { allChunks: true }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin()
  ]
};

**Comment by kagux** [comment]
Here's an extract of my working config
```
  module: {
    loaders: [
      {test: /\.js$/, exclude: /node_modules/, loaders: ['react-hot']},
      {test: /\.json$/, loader: 'json'},
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel',
        query: {
          presets: ['es2015', 'react'],
          plugins: [
            'transform-class-properties',
            'transform-object-rest-spread',
            'transform-decorators-legacy',
            'transform-runtime',
            'jsx-control-statements/babel'
          ]
        }
      },
      {
        test: /(\.scss|\.css)$/,
        loader: ExtractTextPlugin.extract('style', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass?sourceMap!toolbox')
      }
    ]
  },
```

**Comment by carlitux** [comment]
I was with same issue and as there is not much on traceback... I compared with another project's package.json and webpack config... I got that I **just** forgot.

```bash
npm install --save-dev css-loader toolbox-loader sass-loader style-loader
```

**Comment by vldmr1986** [comment]
Just install 'react-style-proptype' into your node_modules
