### ISSUE TITLE
Project scope

### ISSUE THREAD

**Issue by gchudnov** [react-toolbox/react-toolbox#35]
Slightly confused...
Any advantages over callemall/material-ui that looks more mature and battle-tested?

**Comment by soyjavi** [comment]
Hi,

Maybe is good idea read (https://github.com/react-toolbox/react-toolbox/blob/master/README.md). React-toolbox is a completely different approach, we believe in decoupled components (is not necessary get all the bundle), we believe in SaSS and CSS-Modules (we hate css inline styles)... 

Our idea is create the best (pixel perfect) components using Material Design spec.

best,

javi

**Comment by gchudnov** [comment]
got it,
thank you!
