### ISSUE TITLE
Menu is always open

### ISSUE THREAD

**Issue by stovmascript** [react-toolbox/react-toolbox#350]
The [`Menu`](https://github.com/react-toolbox/react-toolbox/tree/dev/components/menu) component has an `active` prop, which "If true, the menu will be displayed as opened by default". But even thought it's set to false by default, the menu always renders opened. I even tried playing around with the [spec component](https://github.com/react-toolbox/react-toolbox/blob/dev/spec/components/menu.jsx), but still couldn't get it to work.

I expected it to work like the `IconMenu`, which works fine, but I need a dropdown/select-like menu.

I started with the example code for the IconMenu and changed it like this:

```jsx
<Menu>
    <MenuItem caption='Download' />
    <MenuItem caption='Favorite' />
</Menu>
```

Is it a bug or am I using it wrong?

**Comment by javivelasco** [comment]
By default, the `Menu` component has a prop `position: POSITION.STATIC`. This means the menu can be used as a static block which means it will be displayed. If you don't want it be static you can set it to `AUTO`. This is something the `IconMenu` does already. Maybe the default option should be `AUTO` to avoid confussion
