### ISSUE TITLE
[Error: The style-loader cannot be used in a non-browser environment] Is there a some probe-tested way to use RT with server-side rendering?

### ISSUE THREAD

**Issue by wzup** [react-toolbox/react-toolbox#355]
In my app I use server side rendering. When I require webpack-generated bundle in server module, I get this error:

```
const components = require('./../assets/js/react/server.webpack');

Error: The style-loader cannot be used in a non-browser environment
```

Is there some best-practices way to use RT with server side rendering?

**Comment by javivelasco** [comment]
Sure, I've tested it using [require hook](https://github.com/css-modules/css-modules-require-hook) for CSS Modules. Just like any other app. Make sure your config includes `node_modules` so it can find react toolbox imports
