### ISSUE TITLE
Empty dropdown values creates errors

### ISSUE THREAD

**Issue by halkeye** [react-toolbox/react-toolbox#356]
Simple use case

```
  export default class MainWindow extends React.Component {
    render () {
      return <Dropdown source={[]} />;
   }
  }
```

Produces:
```
Uncaught TypeError: Cannot read property 'label' of undefined
```

Expanded in the console leads to learning that dropdown's value is derived from `this.getSelectedItem()` which returns source[0] which is undefined.

I can work around this by pre-filling with a dummy value, but I encountered it when a page first rendered while still waiting for data to be available.

**Comment by LetoGear** [comment]
May I ask why would you need an empty dropdown?
If the source is not always ready, maybe you could approach in this way?
`return {source && <Dropdown source={source} />`

**Comment by javivelasco** [comment]
Agree. If your dropdown is empty I think you should just render something else

**Comment by halkeye** [comment]
Yea, as I said, there's work arounds.

Empty dropdowns are valid in html and other things, so it didn't occur to me that its considered invalid so I recorded it as a bug.

**Comment by javivelasco** [comment]
Alright, it makes sense to take a look though! Thanks for the feedback @halkeye :)

**Comment by javivelasco** [comment]
Now instead of returning the first element in the source (which caused the error), it's returning nothing. This was needed in order to show a template as a default placeholder, but I removed it in favor of a typical placeholder with no template.

After selecting a value it will behave the way it did before.
