### ISSUE TITLE
[Menu] Doesn't highlight selected child item

### ISSUE THREAD

**Issue by wzup** [react-toolbox/react-toolbox#357]
1. 
It is not clear what is the role for `value` key in Menu. What `Boolean` value should be and how does it work?

![react toolbox - google chrome 2016-03-05 23 40 12](https://cloud.githubusercontent.com/assets/3880497/13548560/1b5305c0-e32e-11e5-8b70-4b1363b28ddd.png)

2.
It seems that Menu neither:
1) highlight selected child item, nor
2) allow to set initial value.

I set `selectable=true` and `value=eng`. But dedicated `MenuItem` is not highlighted.
```
        return (
            <IconMenu icon='language'
                    position='auto'
                    menuRipple
                    className="costomMenu"
                    selectable={true} // How does it work?
                    value="eng" // How does it work? In docs this prop is Boolean
                outline={false}>
                <MenuItem value='eng' caption='English' selected={true} className="customItem" ripple={true} />
                <MenuItem value='de' caption='German' className="customItem" />
            </IconMenu>
        );
```

**Comment by javivelasco** [comment]
This was a typo. The `prop` accepted by both `IconMenu` and `Menu` is `selected`. It can be any value used in a `MenuItem` and it represents the select item. You can try this in the playground:

```jsx
const MenuTest = () => (
  <IconMenu selected='download' selectable icon='more_vert' position='top-left' menuRipple>
    <MenuItem value='download' icon='get_app' caption='Download' />
    <MenuItem value='help' selected icon='favorite' caption='Favorite' />
    <MenuItem value='settings' icon='open_in_browser' caption='Open in app' />
    <MenuDivider />
    <MenuItem value='signout' icon='delete' caption='Delete' disabled />
  </IconMenu>
);

return <MenuTest />;
```

So you will see the first option highlighted. I've just updated the docs
