### ISSUE TITLE
Tooltip on RadioButton?

### ISSUE THREAD

**Issue by LetoGear** [react-toolbox/react-toolbox#359]
```
<RadioGroup>
  ...
  <TooltipRadioButton
    label={ROLE.title}
    value={ROLE.value}
    tooltip={ROLE.desc}
    tooltipDelay={500}
  />
  ...
</RadioGroup>
```

`desc` is a one-line brief description about the ROLE and is meant to be only necessary to occasional users, thus I really feel like using tooltip on this occasion.
Would it be possible?

**Comment by javivelasco** [comment]
Now it's supported!
