### ISSUE TITLE
Tabs: "Cannot read property 'getBoundingClientRect' of undefined"

### ISSUE THREAD

**Issue by emirotin** [react-toolbox/react-toolbox#361]
Seems to happen when the component starts unmounting (or when it's not fully mounted yet?)
Repro: have 2 pages with tabs, cross-linked. Switch between them.

**Comment by mattkauffman23** [comment]
Having a similar issue but with IconMenus, where I'm getting Cannot read 'getBoundingClientRect' of undefined .

I have IconMenus that are in a grid component that removes rows from the DOM when they're no longer visible. I found this issue: https://github.com/react-toolbox/react-toolbox/issues/251 and I suspect the fix there introduced race conditions when components unmount.

In this particular case it looks like a guard on this.refs here: https://github.com/react-toolbox/react-toolbox/blob/5184e872daf1f5820455a16b5bef17d2c9a8abe3/components/menu/Menu.jsx#L47 would fix the problem I'm seeing. Feels like a band aid though.

**Comment by emirotin** [comment]
@mattkauffman23 may be related: https://github.com/react-toolbox/react-toolbox/issues/303

**Comment by mattkauffman23** [comment]
👍 @emirotin thanks will look into whether that's related.

**Comment by albert-tse** [comment]
The same bugfix should also be applied here: https://github.com/react-toolbox/react-toolbox/blob/dev/components/menu/Menu.js#L47
