### ISSUE TITLE
Default value for dropdown (undefined)

### ISSUE THREAD

**Issue by sars** [react-toolbox/react-toolbox#367]
Hi there.
After last update I encounter a issue: I used sources like:

``` js
[
  { label: 'Time' },
  { value: '10:30Z', label: '12:30 - 13:00' }, 
  { value: '11:30Z', label: '13:30 - 14:00' }
]
```

so, if my value is undefined, the first option would be selected.

https://github.com/react-toolbox/react-toolbox/commit/993afbce39438ef6dce37d40f20de3d1ff7c3ec7#diff-c00f8d97c0aa29d06cc6ae0914dff58fL84

this commit kills this behaviour :)

Is there any other way to define such default value that would work the same?

**Comment by javivelasco** [comment]
Close in favor of #1169
