### ISSUE TITLE
Does RT utilize any add-on of react-addons?

### ISSUE THREAD

**Issue by wzup** [react-toolbox/react-toolbox#375]
Just curious, if RT components (which ones if any?) use any add-on of `react-addons`.

I have these add-ons in my `node_modules`:

`react` `"version": "0.14.7"`
`react-addons-create-fragment` `"0.14.7"`
`react-addons-css-transition-group` `"0.14.7"`
`react-addons-pure-render-mixin` `"0.14.7"`
`react-addons-transition-group` `"0.14.7"`
`react-addons-update` `"0.14.7"`

And in my `webpack` config I make vendors bundle providing both `react` and `react-addons`:
```
[
                'react', <===<
                'react-dom',
                'moment',
                'jquery',
                'react/addons', <===<
                'react-toolbox/lib/dropdown',
                'react-toolbox/lib/button',
            ]
```

And I get warning thrown in a browser console if I provide 'react/addons':
`Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.`

And if I remove  'react/addons' from vendor bundle (only `react` left), no warnings are throw in a browser and my app seems to work fine without `react/addons`.

My question. Do RT utilize any add-on of `react-addons`? If it does, which components do which add-ons utilize? Is it safe to completely remove `react-addons` from vendor bundle?

**Comment by MIGUELWAXX** [comment]
@mping

**Comment by felipeleusin** [comment]
The only addon RT depends upon is react-addons-css-transition-group

**Comment by javivelasco** [comment]
Exactly! Thanks for answering @felipeleusin
