### ISSUE TITLE
Inputs with required indicator

### ISSUE THREAD

**Issue by renato** [react-toolbox/react-toolbox#376]
Far from being a priority, it would be nice to have somethink like the required indicator described in MD spec:

https://www.google.com/design/spec/components/text-fields.html#text-fields-required-fields

Just a suggestion, because it is already possible today using a component instead of a string for the Input label so it is fine to leave this to RT user instead of providing a syntax sugar.

EDIT: Actually, using a component instead of a string raises a warning that expected propType is 'string':
`Warning: Failed propType: Invalid prop ``label`` of type ``object`` supplied to ``Input``, expected ``string``. `

**Comment by KerenChandran** [comment]
Looking at the source code, I notice that a required prop was created, but was never implemented. I'll look into this issue and try to create a PR hopefully within a few days (busy with University stuff).

@javivelasco If you have any input (pun intended :P), please send it across.

**Comment by KerenChandran** [comment]
@renato @javivelasco 

If there are still things to do for this issue please let me know, otherwise can we close it?

**Comment by javivelasco** [comment]
Closed indeed! Thanks @KerenChandran
