### ISSUE TITLE
DatePicker: allow min/max date

### ISSUE THREAD

**Issue by mping** [react-toolbox/react-toolbox#38]
This would be great, since it's one of the most common use cases for datepickers.

**Comment by babygau** [comment]
+1 for that. It would be great if the component support as many methods on [bootstrap-datepicker](https://bootstrap-datepicker.readthedocs.org/en/latest/methods.html) as possible.

**Comment by javivelasco** [comment]
We have to do it! +1

**Comment by soyjavi** [comment]
+1

**Comment by soyjavi** [comment]
Working in the new attributes `minDate` and `maxDate`

**Comment by soyjavi** [comment]
- New properties `minDate` and `maxDate`.
- New UI (Material Design new style)
<img width="362" alt="screen shot 2015-11-17 at 12 34 02 am" src="https://cloud.githubusercontent.com/assets/559654/11189601/865f8184-8cc3-11e5-838e-29702de95efc.png">

**Comment by javivelasco** [comment]
:+1: !!
