### ISSUE TITLE
core-js dependency?

### ISSUE THREAD

**Issue by mgcrea** [react-toolbox/react-toolbox#382]
When trying to use the list from your examples:

```js
import { List, ListItem, ListSubHeader, ListDivider, ListCheckbox } from 'react-toolbox';
```

I'm hit with these errors:
```
ERROR in ./~/react-toolbox/lib/utils/polyfills.js
Module not found: Error: Cannot resolve module 'core-js/fn/array/from' in /Users/olivier/Projects/ng-tools/react-webpack-factory/node_modules/react-toolbox/lib/utils
 @ ./~/react-toolbox/lib/utils/polyfills.js 3:0-32

ERROR in ./~/react-toolbox/lib/utils/polyfills.js
Module not found: Error: Cannot resolve module 'core-js/fn/array/iterator' in /Users/olivier/Projects/ng-tools/react-webpack-factory/node_modules/react-toolbox/lib/utils
 @ ./~/react-toolbox/lib/utils/polyfills.js 5:0-36

ERROR in ./~/react-toolbox/lib/utils/polyfills.js
Module not found: Error: Cannot resolve module 'core-js/fn/map' in /Users/olivier/Projects/ng-tools/react-webpack-factory/node_modules/react-toolbox/lib/utils
 @ ./~/react-toolbox/lib/utils/polyfills.js 7:0-25

ERROR in ./~/react-toolbox/lib/utils/polyfills.js
Module not found: Error: Cannot resolve module 'core-js/fn/string/starts-with' in /Users/olivier/Projects/ng-tools/react-webpack-factory/node_modules/react-toolbox/lib/utils
 @ ./~/react-toolbox/lib/utils/polyfills.js 9:0-40

ERROR in ./~/react-toolbox/lib/utils/polyfills.js
Module not found: Error: Cannot resolve module 'core-js/fn/symbol' in /Users/olivier/Projects/ng-tools/react-webpack-factory/node_modules/react-toolbox/lib/utils
 @ ./~/react-toolbox/lib/utils/polyfills.js 11:0-28
``` 

Stops complaining if I `npm i core-js`. Is it a required dep or is there an issue somewhere?

Thanks!

**Comment by javivelasco** [comment]
Some people are having this issue. Make sure you are running the recommended node and npm version and see if it's still failing. It shoudnt actually!

**Comment by mgcrea** [comment]
Hum, it looks like I'm using supported versions:

```
$ node --version
v5.8.0
$ npm --version
2.14.22
```

Not sure where it does come from, it may work with `npm@v3` since it does flatten the dep tree, but if `core-js` is needed at some point by the production files of `react-toolbox`, I think it should be added to the dependencies, relying on a specific implementation of NPM looks fragile.

**Comment by javivelasco** [comment]
Did you solve it??

**Comment by skylinezum** [comment]
I'm also having this core-js problem with versions
node: v4.4.3
npm: 2.15.1

This is the current supported node stack for AWS elastic beanstalk.

**Comment by felipeleusin** [comment]
I just tested here and indeed with npm@v2 this crashes and imho core-js should be added as a dependency instead of devDependency as it is now

**Comment by javivelasco** [comment]
I'm ok with it, feel free to PR
