### ISSUE TITLE
Set attributes on internal <input> element

### ISSUE THREAD

**Issue by Klathmon** [react-toolbox/react-toolbox#384]
Is there a way to apply attributes to the inner `<input>` element inside a react-toolbox `<Input>`?

I need to apply the attributes `autocomplete="off"`, `autocorrect="off"`, `autocapitalize="off"`, and `spellcheck="false"` to the inner `<input>` element to prevent iOS from doing those things (i'm trying to use an `<Input>` to enter carton identifier strings, and iOS likes to autocorrect carton strings into words...)

**Comment by felipeleusin** [comment]
You can just put them on the Input element that they will get passed on the base <input>. You just have to mind that some of those attributes use camel case in react https://facebook.github.io/react/docs/tags-and-attributes.html (autoCapitalize, autoComplete, autoCorrect, spellCheck)

**Comment by Klathmon** [comment]
Well then that's my problem, thanks!

**Comment by javivelasco** [comment]
Thanks @felipeleusin !
