### ISSUE TITLE
DatePicker doesn't support icon?

### ISSUE THREAD

**Issue by jeffreywescott** [react-toolbox/react-toolbox#392]
It seems like the DatePicker doesn't support the `icon` attribute. Is this intentional? It seems a bit inconsistent from the rest of the inputs.

**Comment by felipeleusin** [comment]
I don't think it's intentional, imho this should be fixed by either adding a inputProps option on the DatePicker or a just an icon attribute directly.

**Comment by javivelasco** [comment]
Yep, exactly. This is not on purpose but shouldn't be difficult to do since the picker uses a normal `Input` component

**Comment by cdroulers** [comment]
[This commit](https://github.com/react-toolbox/react-toolbox/commit/77c74bfb555f0e4bbd8209b1aa788200e107bf4d) seems to add support. It's not integrated into master yet it seems.

PR: https://github.com/react-toolbox/react-toolbox/pull/491

**Comment by javivelasco** [comment]
Closing then. It will be released soon
