### ISSUE TITLE
NPM link workflow

### ISSUE THREAD

**Issue by mgcrea** [react-toolbox/react-toolbox#396]
I'm encountering build issues when trying to use a local linked version of `react-toolbox`:

```
    ERROR in /Users/olivier/Developer/react/react-toolbox/~/css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!/Users/olivier/Developer/react/react-toolbox/~/postcss-loader!/Users/olivier/Developer/react/react-toolbox/~/sass-loader?sourceMap!/Users/olivier/Developer/react/react-toolbox/~/toolbox-loader!/Users/olivier/Developer/react/react-toolbox/lib/avatar/style.scss
    Module build failed: Error: ENOENT: no such file or directory, open '/Users/olivier/Projects/foo/bar/theme.scss'
        at Error (native)
Child extract-text-webpack-plugin:
```

Do you use NPM linking feature while developing other apps built over `react-toolbox`? Any feedback on theses issues?

**Comment by lucaas** [comment]
I receive similar errors related to `eslint-loader` when I try using a locally linked copy of `react-toolbox`.

```
ERROR in ../react-toolbox/lib/app/index.js
Module not found: Error: Cannot resolve module 'eslint-loader' in [...]/react-toolbox/lib/app
 @ ../react-toolbox/lib/app/index.js 8:11-27
```

**Comment by renato** [comment]
I had the theme.css problem (@mgcrea's), then I changed the linked react-toolbox's packages.json to use toolbox-loader 0.0.3 (instead of 0.0.2) and I got the the same problem as @lucaas.

**Comment by javivelasco** [comment]
My experience is using it as a dependency directly from npm. I have to try to tell you something about this but I think there's nothing special. Sometimes webpack can be a little tricky to configure so I always point to the example repository. Leave any progress here in case you figure out something!

**Comment by renato** [comment]
https://webpack.github.io/docs/troubleshooting.html

"When you npm link modules with peer dependencies that are not in your root directory, modules can no longer be found."

Tried applying the workaround but webpack stuck on `webpack: wait until bundle finished: /`.

I gave up on `npm link` and I'm using the `file:../react-toolbox` syntax in packages.json too.

**Comment by mgcrea** [comment]
Had a successful build with the following webpack docs (`fallback`) from @renato, but the build isn't properly working: 

```
invariant.js?568c:38 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

**Comment by mgcrea** [comment]
Ok I've finally got it for good!

I can link to any version of `react-toolbox` and even import components I'm working on, using `import Avatar from 'react-toolbox/components/avatar';`

The working config is:

```js
const modulesPath = path.join(__dirname, 'node_modules');

...

  resolve: {
    extensions: ['', '.js', '.jsx', '.json', '.scss'],
    packageMains: ['browser', 'web', 'browserify', 'main', 'style'], // support `style` main field for normalize.css
    fallback: modulesPath, // support linked modules,
    alias: {
      react: fs.realpathSync(path.join(modulesPath, 'react')) // force components to use a local copy
    },
    root: srcPath
  },
  resolveLoader: {
    fallback: modulesPath // support linked modules
  },
  module: {
    loaders: [{
      test: /\.jsx?$/,
      include: [srcPath, fs.realpathSync(path.join(modulesPath, 'react-toolbox/components'))], // `realpath` is used to support linked modules
      loaders: ['babel']
    }, ...]
  },
```
