### ISSUE TITLE
DatePicker maxDate in past not taken into account when dialog is shown

### ISSUE THREAD

**Issue by jeffreywescott** [react-toolbox/react-toolbox#402]
If I set a `maxDate` that is in the past (e.g., 1995-03-21), when I click on the DatePicker field:

- the date still defaults to _today_, even though that date is not allowed
- it's still possible to move past the `maxDate`
  - the year drop-down still shows years after 1995
  - the year 1995 still shows months 04-12

This forces the user to navigate backwards year-by-year and / or month-by-month, which takes quite a long time.

_At a minimum_, the dialog should open somewhere _before_ `maxDate` (perhaps at the midpoint between `minDate` and `maxDate`?).

While I haven't tested it, I suspect something similar is true for `minDate`.

**Comment by Tudmotu** [comment]
I can confirm similar is true for minDate as well - if minDate is in the future, default date is "today", and you have to scroll through the months till you get to the allowed range.
