### ISSUE TITLE
DatePicker renders date improperly after selected

### ISSUE THREAD

**Issue by jeffreywescott** [react-toolbox/react-toolbox#404]
If I am in, say, the Pacific timezone, and at 3pm in the afternoon select a certain date, it will render as a day earlier. [Everywhere here](https://github.com/react-toolbox/react-toolbox/blob/dev/components/utils/time.js) that you're calling `getFullYear()`, `getMonth()` and `getDate()` on a `Date` object should be `getUTCFullYear()`, `getUTCMonth()`, and `getUTCDate()`.

**Comment by felipeleusin** [comment]
As of #366 you can pass an inputFormat prop that allows you to format how the date is displayed by yourself.

**Comment by jeffreywescott** [comment]
Cool, thanks! Docs need an update. :-)

Also, I think the _default_ behavior is still a bug. Dates (without times) need to be represented as UTC or you get weird offset issues.

**Comment by javivelasco** [comment]
Thanks @felipeleusin !
