### ISSUE TITLE
Update Docs!!!

### ISSUE THREAD

**Issue by KerenChandran** [react-toolbox/react-toolbox#405]
Related Issues: #124 

I noticed some of the docs are outdated and decided its time for an update. Also gonna look into #124 and see what's causing that issue (no guarantees that I'll be able to fix it but I'll do my best!).

@javivelasco Just wanted to know what's the recommended way to import the react-toolbox components. Look at the options below:

Option 1: ` import { Button } from 'react-toolbox'; `
Option 2: ` import {Button, IconButton} from 'react-toolbox/lib/button';`

**Comment by KerenChandran** [comment]
Also can you update the dev branch's version to 0.15.0? Dev is currently set at 0.14.1 and right now we are on 0.15.0

**Comment by felipeleusin** [comment]
For importing, use option 2 since it will make sure you don't bundle the whole toolbox and instead only bundle the components you end up using

**Comment by KerenChandran** [comment]
Alright! I usually go with the first one for simplicity but what you said makes sense.

**Comment by javivelasco** [comment]
@KerenChandran done! About the importing question, @felipeleusin is totally right. If you require directly the component you make sure the bundle includes only what's needed. And yes, the first one is way more elegant, but it's a important issue to grow that size the bundle!
