### ISSUE TITLE
Menu : "TypeError: Cannot read property 'getBoundingClientRect' of undefined"

### ISSUE THREAD

**Issue by mrogelja** [react-toolbox/react-toolbox#407]
Hi !

I notice the same issue than #361 when unmounting the [Menu](https://github.com/react-toolbox/react-toolbox/blob/dev/components/menu/Menu.jsx#L47).

Tks.

**Comment by Blaze34** [comment]
+1

**Comment by javivelasco** [comment]
I've push a fix that checks if the parent node exists before trying to calculate the position. Since the issue is happening when the component is unmounted I think there is no downsides at all
