### ISSUE TITLE
Tooltip doesn't work with IconMenu or Checkbox

### ISSUE THREAD

**Issue by bigticket** [react-toolbox/react-toolbox#409]
Tooltip seems to work fine with IconButton, but not with IconMenu or Checkbox.

**Comment by ngoctranfire** [comment]
Has there been any investigation for this to make it work with Checkbox?

**Comment by javivelasco** [comment]
Whenever you see a tooltip does not work with another component it is because it is not rendering `children` or it's not setting `onMouseEnter` / `onMouseLeave`. Those are properties that the decorator passes down in order to know when the tooltip should be shown and hidden
