### ISSUE TITLE
doesn't work on IE 11

### ISSUE THREAD

**Issue by luisrudge** [react-toolbox/react-toolbox#41]
![image](https://cloud.githubusercontent.com/assets/941075/10916191/5a0f6cf2-8241-11e5-9c70-28233e976a71.png)

![image](https://cloud.githubusercontent.com/assets/941075/10916197/63894794-8241-11e5-9be7-7e138bf52bc6.png)

**Comment by javivelasco** [comment]
Maybe somebody with IE can investigate it?
Thanks!

**Comment by luisrudge** [comment]
the error is pretty clear: you're trying to use object.assign without a polyfill

**Comment by javivelasco** [comment]
But I think the polyfill is added as a dependency so it should be running doesn't it??

**Comment by luisrudge** [comment]
I don't think so.. :(

**Comment by javivelasco** [comment]
So that´s the thing! :dancer: I'll do it as soon as possible

**Comment by buz-zard** [comment]
I'm getting same error on chromium, Version 43.0.2357.130 Ubuntu 14.10 (64-bit)

**Comment by javivelasco** [comment]
That that's more weird :confused:  I'm definitely debugging this with more priority, I'll try to reproduce it and fix it. Thanks!

**Comment by javivelasco** [comment]
It should work now. Can you try @luisrudge?

**Comment by luisrudge** [comment]
Nope.. Same error :(

**Comment by javivelasco** [comment]
Wow, I missed other `Object.assign` usage scenario. I'll let you know as soon as I change it. Hold on!

**Comment by ceram1** [comment]
Fixed, but I don't have a windows device.

**Comment by javivelasco** [comment]
Fixed already. I tested in a Windows OS with Chrome. Please try yourselves too. Finally I removed the usage of `Object.assign` and changed it for a destructuring. Closing!
