### ISSUE TITLE
Dropdown doesn't work with react-router Link

### ISSUE THREAD

**Issue by hamuzek** [react-toolbox/react-toolbox#410]
Hi,

I'm trying to use `react-toolbox`'s dropdown component in my site's header bar to switch between routes, where the value of each `{label, value}` tuple is the link path. I'm also using `redux`, `react-router`, and `react-router-redux`, which brings me to two ways of handling the selection;

1. Hold selection in state, and have the click handler send a `react-router.push` action
1. Hold selection in URL by using `<Link>` in the dropdown

Option 2 makes more sense to me, because it's declarative and avoids a bunch of pitfalls, so I'm using the `template` prop to render like so:

    const renderLink = ({value, label}) => (
        <Link to = {'/' + value}>{label}</Link>
    )
    ...
    <Dropdown template = {renderLink} value = {/* taken from URL */} />

This doesn't work. I had a hunch that the `Link` element expects a `context.router` on its click handling, while `Dropdown` calls the template as a function without passing down the context. So I tried an ugly hack, currying the template function with `context` as an argument and creating a new component to capture the context and pass it down properly to the actual rendering.

This doesn't work either.

Some breakpoints later, it seems that the click event doesn't always bubble up from the `Dropdown` to the `Link` component - if you click on a value in the dropdown list, it doesn't fire, but once it appears as the selected value, it will fire - but only once. Worth noting is that the URL change occurs without the context hack, so my earlier hunch was proven even falsier.

Point is, I don't understand how to make them work together. I looked at both https://github.com/react-toolbox/react-toolbox/issues/144 and https://github.com/react-toolbox/react-toolbox/issues/304, tried using `LinkContainer` as suggested, but still stuck with the same behavior.

I'm at my wit's end.. Why is it not working?

**Comment by bkrall** [comment]
+1

**Comment by javivelasco** [comment]
Well, this is normal because the `Link` is not aware of the `context`. To solve this you can check the code of the original `Link` component in React Router and create a wrapper for the element that understands the context and can manipulate the `history`. Not sure if we should include it in the default `Link` component because it would not be *agnostic* anymore... but it could safely check if context exists. Opinions?
