### ISSUE TITLE
Tabs should have a property to be full width

### ISSUE THREAD

**Issue by gabrielenosso** [react-toolbox/react-toolbox#419]
In Material Design Guidelines about tabs (https://www.google.com/design/spec/components/tabs.html#tabs-usage), the default components are full width: they occupy all the horizontal space available.

It could be good to have a prop to have this kind of tabs.

I tried to apply the CSS and it visually works, but the line that tells you which one is the current Tab is not responsive (it doesn't shrink/enlarge, so as soon as you resize the window, the layout is broken).

**Comment by Reanmachine** [comment]
I just submitted a pull request #706 for this.

**Comment by javivelasco** [comment]
Done!
