### ISSUE TITLE
AppBar?

### ISSUE THREAD

**Issue by luisrudge** [react-toolbox/react-toolbox#42]
Hi. I noticed the AppBar exists inside the repo, but the demo says it's still coming. What's the catch? :D

**Comment by soyjavi** [comment]
Hi Luis,

Yes you can use it AppBar (it's a preliminary version, but works). In the repo https://github.com/react-toolbox/react-toolbox-example you can see a example using this component.

best,

**Comment by luisrudge** [comment]
ok thanks!
