### ISSUE TITLE
Upgrade normalize.css to 4.0.0

### ISSUE THREAD

**Issue by mgcrea** [react-toolbox/react-toolbox#428]
Not sure yet if there is some breaking changes for the project:

https://github.com/necolas/normalize.css/compare/3.0.3...4.0.0

There is at least an issue with webpack due to a change in package.json (`main` => `style`): more info http://stackoverflow.com/questions/32037150/style-field-in-package-json

Related webpack issue: https://github.com/webpack/css-loader/issues/51

**Comment by javivelasco** [comment]
Done
