### ISSUE TITLE
[Request] Table component

### ISSUE THREAD

**Issue by FoxxMD** [react-toolbox/react-toolbox#43]
I love this approach of this project! But it's missing a proper table. Any plans for this?

**Comment by soyjavi** [comment]
Yes!! I'm working now in <Table> component you can see the process in "component.table" branch.

Best

**Comment by soyjavi** [comment]
I already merge the branch Table 

https://github.com/react-toolbox/react-toolbox/commit/5d4c7293d38991ff9b85bcf3b26be97a65121dfb

**Comment by FoxxMD** [comment]
fantastic :) thanks for your hard work!
