### ISSUE TITLE
Dialog rendering in DOM when initial created rather than when active

### ISSUE THREAD

**Issue by ro-savage** [react-toolbox/react-toolbox#432]
I may be way off-base here. But we have 7 `Dialog`s on our page.

When using the react-toolbox `<Dialog>` component, it renders all 7 to the `DOM` immediately, they are just hidden. And when the prop changes to active they animate to visible.

Was this done deliberately? Is there some performance benefit from the `Dialog`s being created initially then animated?

In my code base I have wrapped them in a `HOC` that returns `null` then they aren't active and when they are active render's the `Dialog` to the `DOM` keeping them hidden, then once rendered in the `DOM` it updates to play the animation.

Is there a better way to do this? Should I be doing this? 

If there isn't a reason I could look into creating a PR the will only render when the state changes to active.

(This might be related to issue #264 and [PR279](https://github.com/react-toolbox/react-toolbox/pull/279/) @kagux ?)

**Comment by kagux** [comment]
@ro-savage I've created PR https://github.com/react-toolbox/react-toolbox/pull/279 to solve exactly this scenario by not rendering overlays until they're triggered

**Comment by ro-savage** [comment]
Sweet. I had a quick look at your PR but I wasn't 100% on what was going on. I'll close this, checkout your PR and take a look. Nice work!

**Comment by javivelasco** [comment]
@kagux @ro-savage I've been taking a look into the PR and I have some thoughts. First of all, we should update the implementation according to the current code. Recently we updated the `Overlay` to preserve the context. Apart from that, I'd actually prefer to use internal state and provide the transition via just CSS to avoid the need of specifying transition duration in the component implementing the `Overlay`. I can push a PR tomorrow (I have to do the same for my current company work). Thoughts?

**Comment by kagux** [comment]
@javivelasco obviously, css only is much better, but how do you make a transition for element that wasn't previously in the DOM?

**Comment by ro-savage** [comment]
@javivelasco  Happy to have a review of it if you need. Otherwise I have some time on tuesday when I could look into more.

@kagux thinking outloud. 

Why can't it render as `null` when not active. then when active, render in the DOM with class that is hidden, then once the component has rendered in dom change the class to the visible class with animation? 

I am still new to react, but I assume `ComponentDidMount` will fire even if it's just rendering null?
But what if there was a subcomponent inside the overlay/dialog that fired a callback on `ComponentDidMount` that changed the `className` of it's parent? (in this case the overlay/dialog)?

**Comment by kagux** [comment]
@ro-savage that's pretty much what `ReactCSSTransitionGroup` does, https://facebook.github.io/react/docs/animation.html

**Comment by ro-savage** [comment]
@kagux Well that's the only solution I've got. I guess we'll wait and see what @javivelasco comes up with?

My temporary hack implementation is just a HOC that wraps the dialog with a timeout, renders it on the screen and 200ms later passes active to the dialog. And does the same thing in reverse when it's unmounted. But I would love to see a real solution like your PR implemented.

**Comment by javivelasco** [comment]
I've think struggling with this the whole day... As you said @kagux, it's not possible to add a CSS transition on an element if it's not present in the DOM and then changed. My first guess was to use a state in the middle to first render "empty" and then add state "active", that would trigger the animation. This is possible but wouldn't work in the reverse because the component doesn't know how long it takes.

Then I tried to switch to `ReactTransitionGroup` as you did in the PR but found out that if you want to hide the overlay before the animation is finished, it wouldn't work either because the `transitionAppearTimeout ` cannot be interrupted.

Until this moment I couldn't find a way to have the same behavior as we have now but avoiding rendering the component when it's not active.

BUT I wonder... Is this really wrong? Actually the component is rendered because it is there, but not active. In an application you wouldn't have a huge amount of overlays at the same time. Of course it would be best no to render anything but I am not sure if is a really big deal.

**Comment by javivelasco** [comment]
@ro-savage what do you think?

**Comment by javivelasco** [comment]
I think I've found a way. I'll give you an update later

**Comment by kagux** [comment]
@javivelasco, personally I don't think it's a big deal. It does feel counter to React way of things. I can imagine having some advanced logic in a dialog (say, an image editing pop-up) or a drawer ( a toolbox or something). But then again, realistically for most day to day use cases no one is going to notice a difference.

Just a thought, what if we consider a different approach. Sort of a middle ground. When component not active, render only outer container of a child component and render all children in active state. We'll be limited to only outer container transformations, but that's all we have right now anyway.

**Comment by ro-savage** [comment]
@javivelasco, I haven't had time to read through and understand the docs for `ReactCSSTransitionGroup` and exactly how @Kagux is using it but if this is what it's built for then I don't see what is wrong with using it as Kagux has.

It also appears to be how material-ui is handling [Dialogs](https://github.com/callemall/material-ui/blob/master/src/Dialog/Dialog.js#L300).

For most applications I don't think it's much of a performance hit to render them all to the DOM on page load. However, personally I don't like that the DOM is polluted by a bunch of stuff that doesn't 'exist' to the user yet (it exists to us the developers, but I like the DOM to be what the user is seeing rather than what the dev has coded)

When the problem has been encountered in the past, people often use a single root-level dialog that animates in and out, but the content is changed based on the dialog that is being rendered. This is another (less beautiful) option.

**Comment by ro-savage** [comment]
BTW @javivelasco you've probably heard this already but just encase you haven't. Listen tot he last 10 minutes of the React Podcast: http://reactpodcast.com/2015/12/7-rapid-fire-1-with-special-guest-dan-abramov/

**Comment by javivelasco** [comment]
Yep @ro-savage I heard the podcast, and I was very happy about it! ♥️
The only problem with the transition group is that if you set  a timeout for the appear/leave apparently it cannot be stopped.

**Comment by ro-savage** [comment]
I heard it on the drive home yesterday, that's been epic feedback from the guys :) Very well done!

@javivelasco I haven't looked into it too much yet. But Khan Academy have made their own [transition helper](https://github.com/Khan/react-components/blob/master/js/timeout-transition-group.jsx). It looks like they built it so animations would continue to play when you change tabs. But it might allow us to cancel the timeout.

If you've got something ready by Tuesday, will take a look and give any feedback if you'd like. If nothing is available Tuesday I can have a look at another option.

The main issue with @Kagux implementation in your eyes is the ability to cancel and the `!important` in the stylesheet?

**Comment by javivelasco** [comment]
https://github.com/react-toolbox/react-toolbox/pull/444 solves it with an HOC and keeping all the API styles etc untouched.
