### ISSUE TITLE
Input component shows error even if not touched

### ISSUE THREAD

**Issue by yzaroui** [react-toolbox/react-toolbox#434]
I am trying to use **Input** component within a **redux-form** form. 
The **Input** always shows the error text even if it is untouched. 
Could you please implement this behaviour : When untouched or valid don't show the error and show it otherwise.

**Comment by lucaas** [comment]
I've worked around this issue using the approach below, maybe it will be of help to you as well.

```
    function errorMessage(field) {
        return field.touched && field.error || null;
    }
[...]
    const { fields: { name } } = this.props;
[...]
    <Input
        type="text"
        label="Name"
        name="name"
        {...name}
        error={errorMessage(name)}
    />
```

**Comment by yzaroui** [comment]
Simple and effective.
Would be great if this was integrated in the toolbox.

**Comment by KerenChandran** [comment]
While I was working on the input field, I noticed that the error property accepts a node not a string. It might have been done this way to allow the user to control when the user gets shown and what they want to display in the error. Plus adding a check like this is specific for the redux form controls, which I don't think all users may use. But hey, that's just an opinion.

**Comment by yzaroui** [comment]
It accepts a node but it renders it as if it was just a string : 
`{error ? <span className={style.error}>{error}</span> : null}`

**Comment by KerenChandran** [comment]
@yzaroui Good catch! I mentioned it in the update docs PR that I was working on and changed it from node to string. In other components, error was enforced to be a string and seeing it like this makes sense to me. Lets see what they have to say.

**Comment by javivelasco** [comment]
If there is a fix already I'm closing. If you guys there stuff to do in the `Input` to improve it's integration with redux form feel free to PR it :)
