### ISSUE TITLE
Best way to uglify

### ISSUE THREAD

**Issue by carlitux** [react-toolbox/react-toolbox#435]
Using uglify webpack

            Asset       Size  Chunks             Chunk Names
           app.js    5.53 MB       0  [emitted]  main
    ../styles/app.css  886 bytes       0  [emitted]  main

and dev

            Asset     Size  Chunks             Chunk Names
           app.js   4.1 MB       0  [emitted]  main
    ../styles/app.css  1.14 kB       0  [emitted]  main

Why uglified is bigger?

**Comment by langri-sha** [comment]
UglifyJS's AST only parses ES5 JS. It's probably something related to the style loaders. Can you post your loaders?

**Comment by carlitux** [comment]
I got this working... thanks!
