### ISSUE TITLE
React 15? 

### ISSUE THREAD

**Issue by dlebedynskyi** [react-toolbox/react-toolbox#436]
hi guys, 
any news on React 15? it is now in RC2. would be nice to have 15 release with it

**Comment by javivelasco** [comment]
Maybe somebody already tried to migrate but don't worry. As soon as it's officially released there shouldn't be a problem to update

**Comment by dlebedynskyi** [comment]
@javivelasco  I tried to use current npm version with 15-rc2 and it worked fine. you guys might as well  just put ` "react": "^0.14.0 || ^15.0.0-rc.1",` into peerDependencies for project

**Comment by felipeleusin** [comment]
I think 0.15 is already out, just the docs that aren't updated.
I just tested the toolbox with react 15 and it appears to be working. We should just put that on the peerDependencies

**Comment by dlebedynskyi** [comment]
@felipeleusin @javivelasco  yap. just when out https://github.com/reactjs/core-notes/blob/master/2016-04/april-7.md

**Comment by smazurov** [comment]
There is a PR open that addresses this: #441

**Comment by javivelasco** [comment]
It's merged. Today I'm going to release a new version with all deps updated, some fixes and also to deploy the docs

**Comment by langri-sha** [comment]
💖!!! It's a race to the downloads :dash:
