### ISSUE TITLE
onKey* events on Input and Autosuggest have little/no event data

### ISSUE THREAD

**Issue by oscar-g** [react-toolbox/react-toolbox#440]
First, this library is really great, especially the CSS-modules part...I was immediately turned-off from material-ui because they use the style tag for everything, but I digress. Thank you to all contributors :cake:

My issue is the following:

`<Input onKeyPress={(e) => console.log(e)}`

When I type into this input, the event data that is logged is pretty useless. Specifically, I'm looking for the `keyCode` or `which` or things like that.

It's the same with `onKeyDown`, `onKeyUp`, etc...

Is this how the Input component was designed or is this a bug?

**Comment by oscar-g** [comment]
Wow, it turns out I was being dumb and trying to inspect the event in the console after it had been destroyed by the garbage collector. Nothing to see here...

**Comment by sahas-** [comment]
@oscar-g I'm looking for ways to do autocomplete based on latest input form the user. I tried using onKeyPress and it not working as expected. Meaning
If I've

-  'a' --> onKeyPress function's event doesn't have anything..
- 'ab' --> onKeyPress function's event has 'a' 

It seems to be falling back by 1 character always..
I must be doing something silly, wondering how you got around this..

**Comment by oscar-g** [comment]
@sahas- Make sure you're closely following the example in the documentation.  If I remember correctly, this library worked wonderfully, but I did have to take a closer look at the examples.  If you're still stuck, try posting your question on StackOverflow, complete with a jsfiddle example.
