### ISSUE TITLE
normalize.css v4.0 is broken for webpack

### ISSUE THREAD

**Issue by dlebedynskyi** [react-toolbox/react-toolbox#446]
if you are using 4.0.0 with webpack take a look at 
https://github.com/necolas/normalize.css/issues/567
it seems version 4.0.0 is broken. might roll back to 3.0.3

**Comment by javivelasco** [comment]
It's working in the project. Check [here](https://github.com/react-toolbox/react-toolbox/blob/dev/webpack.config.development.js#L21) is the magic!

**Comment by dlebedynskyi** [comment]
@javivelasco  ty sir. it does need some magic indeed

**Comment by javivelasco** [comment]
😎😬

**Comment by dlebedynskyi** [comment]
normalize.css 4.1 fixes this issue.

**Comment by javivelasco** [comment]
Ok, gonna update it for the release with #448

**Comment by javivelasco** [comment]
Done in `dev`
