### ISSUE TITLE
NavDrawer full height

### ISSUE THREAD

**Issue by renato** [react-toolbox/react-toolbox#450]
I'm migrating from Drawer to NavDrawer (which is awesome with the permanentAt breakpoints and all) and I don't know how is the correct approach to get a 100% height drawer.

Using **exactly** the example in the docs I got this (notice the white area below the overlay):

![image](https://cloud.githubusercontent.com/assets/3530/14471242/fbaec4da-00c3-11e6-9901-0186d5cd09a9.png)

Now testing with the old Drawer:

![image](https://cloud.githubusercontent.com/assets/3530/14471341/81e0de30-00c4-11e6-84fc-b22dbf578688.png)

Shouldn't NavDrawer have a 100% height by default?

I'm sorry for using this space for asking two other questions, but if anyone is using the new Layout components, it'd be nice to get some help and maybe add some tips to the docs:

Is there any way to check if the NavDrawer has the permament() SCSS mixin so I can hide the button that would activate it?

The NavDrawer content scrolls with the Panel content, how can I keep them separate (NavDrawer's content fixed, like the old Drawer)?

Thanks!

**Comment by javivelasco** [comment]
Maybe @patrick-jones can help. If he can't I can look at it tomorrow

**Comment by patrick-jones** [comment]
Unlike the old implementation, the new `NavDrawer` resides within a parent container, the `Layout`.  The drawer will be the full height of the `Layout`.  Back when I originally wrote `Layout`, there was an `App` aka `ToolboxApp` component that made sure that the the application filled the whole screen.  It looks like that has gone away in the mean time.  The solution is to put your `Layout` inside something that fills the entire screen.  For example, the old  `App` used CSS like this:

```css
.root {
  position: absolute;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  overflow-y: auto;
}
```
As for the hamburger button, the best option is to make CSS that uses the same breakpoints that hides the button when you hit your selected permanent width.

**Comment by javivelasco** [comment]
This relates to #448 I'm feeling now like it was a wrong decision. @patrick-jones do you think you can get it working? Check the linked issue to see the discussion please!

**Comment by renato** [comment]
Using the old `App` CSS @patrick-jones provided fixed the issue and now the `NavDrawer` and `AppBar` are fixed while only the content area is scrollable, exactly what I expected. Oh, and using the same media query with the SCSS breakpoint variable worked great too. Thank you.

**Comment by patrick-jones** [comment]
@javivelasco I don't think this relates to #448. The Layout/NavDrawer etc. do not use the overlay component.  The scrim is controlled internally by the Layout.  This avoids the problems of rendering components outside of the React tree. As mentioned in my previous comment, the Layout will fill the height of its parent component.

**Comment by javivelasco** [comment]
Should we add then the former `App` component style to the layout component?

**Comment by patrick-jones** [comment]
I don't think so, at least not automatically. For one thing, that would prevent them from being nested, which could be handy for routing.. For another, I wouldn't want to make assumptions about how someone wants to display their own app. I think a philosophy of "we'll fill the space you give to us" puts the app developer in more control.

That said, full window is the most typical use case. Maybe we could add a `fullScreen` property that would add the `App` css.  Maybe it should even default to `true`.

**Comment by javivelasco** [comment]
Then I guess this shouldn't be considered as a bug and we should close the issue, right? 💃 
Reopen in other case!

**Comment by renato** [comment]
I agree that this isn't a bug, but I think it would be better if demonstrated in the playground.

**Comment by tnikola** [comment]
Is there an example on this that shows this fixed?

**Comment by javivelasco** [comment]
Actually I've just rewrote the layout component. It's not possible to show it in the playground without an iframe.... you just need to set the content to 100vh if it takes the whole viewport :)

**Comment by patrick-jones** [comment]
I wish you wouldn't do that. I have use cases where I don't want the app to take up the whole window.  Ironically, the playground one of those cases.  If you want the layout to fill the whole window, just put it in a container that fills the whole window.

**Comment by javivelasco** [comment]
Well, actually it's possible to customize it and avoid taking the whole window, but the scroll it's an important caveat. It should be possible to refresh the site and keep the scroll where you left it. That's the main issue I had. No worries it will be compatible :)

**Comment by x4080** [comment]
Hi, how to make the navdrawer content scrollable? adding overflow:auto still cannot scroll
