### ISSUE TITLE
[Question] Using react-toolbox on react-native

### ISSUE THREAD

**Issue by saintc0d3r** [react-toolbox/react-toolbox#453]
Hello Developers,

Can we use react-toolbox on both react-native iOS and android apps ? 

Cheers.

**Comment by javivelasco** [comment]
Hi! I have no experience yet with React Native but as long as I know, there is a different handling of styling. You need to use inline styles and create specific stylesheets so the approach of react toolbox which consists of tradicional CSS modules is not valid in this scenario. To be able to use it we should create a conversion tool or something similar to generate valid styles for native from our CSS/SASS files.

So, short answer: sadly it's not possible. 🤕

**Comment by mattferrin** [comment]
It's seems to be in it's infancy, but this is the best I've discovered thus far: https://carbon-ui.com/

**Comment by NawazKhanMd** [comment]
Hi @javivelasco  
Is it still not possible to use React tool box on React native ?
Pls Reply 👍

**Comment by javivelasco** [comment]
It will be possible soon with a new component approach. With the current version it´s not possible
