### ISSUE TITLE
Calendar bug in ie 11

### ISSUE THREAD

**Issue by dlebedynskyi** [react-toolbox/react-toolbox#456]
in IE 11  I'm seeing this 
![image](https://cloud.githubusercontent.com/assets/1182917/14544221/0c1df82e-0266-11e6-95da-7629501bb385.png)

In any other normal browser 
![image](https://cloud.githubusercontent.com/assets/1182917/14544231/1ad0a02e-0266-11e6-9705-50093652c426.png)

IE version 11.162.10586.0  Update Version 11.0.29 Win 10

**Comment by Siern** [comment]
That misalignment is not specific to IE.  I also see it in Chrome Version 49.0.2623.112 m.
In my chrome experience it only sometimes happens and I have not yet spent time to determine what causes it or why it happens.

**Comment by dlebedynskyi** [comment]
I had seen it only in IE so far. but would love a fix anyway)

**Comment by javivelasco** [comment]
I only have Mac so it's difficult for me to debug, help here is appreciated

**Comment by dlebedynskyi** [comment]
try this https://developer.microsoft.com/en-us/microsoft-edge/tools/remote/
work for me on mac

**Comment by ro-savage** [comment]
PR #571 addresses this issue

**Comment by dlebedynskyi** [comment]
@ro-savage - awesome thanks for fix

**Comment by javivelasco** [comment]
Merged! Gonna release 1.0.1 during the next days, I'll try to fix more stuff before releasing
