### ISSUE TITLE
documenting the theming variables

### ISSUE THREAD

**Issue by tonykung06** [react-toolbox/react-toolbox#458]
maybe good to document what variables we could override

**Comment by KerenChandran** [comment]
Hm... I could spend possibly a few days on this, but #498 will make this documentation pointless.

@javivelasco Do you want me to update the documentation or hold off until you're done upgrading RT to use the the react-css-themr?

**Comment by javivelasco** [comment]
I think it makes more sense to include a link to the file in the docs because the documentation would be essentially the same as the config file content. I left in #498 a reference to an example of the new theming approach.

**Comment by KerenChandran** [comment]
Ok I'll create the link to the config.scss file for all the components hopefully this week/weekend. I'm wondering if it should be done on the dev branch without the table that you added for AppBar, or if I should work on the react-themr branch and create the table with some basic info to help lighten your load
