### ISSUE TITLE
Layout Issue

### ISSUE THREAD

**Issue by enyachoke** [react-toolbox/react-toolbox#459]
@javivelasco @patrick-jones 
Am trying out http://react-toolbox.com/#/components/layout. It works fine mostly but if I set the NavDrawer to pinned mode and try to resize the screen see below
![screenshot from 2016-04-16 12-50-18](https://cloud.githubusercontent.com/assets/1908926/14580313/73b9bfc8-03d2-11e6-9f84-09f603970e4b.png)

The drawer disappears but the panel does not resize to fill the screen.

**Comment by mhoffmanniseki** [comment]
+1 I'm having the same problem.

**Comment by javivelasco** [comment]
May you try if it works now?

**Comment by javivelasco** [comment]
This is solved
