### ISSUE TITLE
Provide a Precompiled Package

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [react-toolbox/react-toolbox#460]
As is, SASS is required to use react-toolbox.  Would it be feasible to provide a branch with SASS precompiled?

**Comment by javivelasco** [comment]
The problem with that is that the components would not be customizable anymore. Right now we are providing a way of customization via sass variables that can be loaded with toolbox-loader in webpack. I'm currently experimenting with a different approach to customization and if everything goes well we would be able to get rid of webpack and even toolbox loader but for now I don't think it would be very useful for most cases.
