### ISSUE TITLE
A better way to implement Sass Over-rides?

### ISSUE THREAD

**Issue by Kannaj** [react-toolbox/react-toolbox#464]
Currently, i have a custom toolbox-theme.scss for styling. 

The problem i'm facing is that i would also sometimes require the globals.scss to be imported to gain access to the $unit variable.

if i set up the file like this 
```
@import "~react-toolbox/lib/_globals";


$color-primary-dark: $palette-amber-600 !default;

$navigation-drawer-desktop-width: 3 * $standard-increment-desktop !default;
```

The amber color doesnt apply to the page because of the _globals import. but i need the file to use the $standard-increment-desktop variable

i eventually wound up doing something like this

```
$color-primary-dark: $palette-amber-600 !default;

@import "~react-toolbox/lib/_globals";

$navigation-drawer-desktop-width: 3 * $standard-increment-desktop !default;
```

over-riding global variables need to come before the import statement. I'm now able to get the amber color in my styling.

I would like to know if theres a better way to implement the above as it seems a bit too hacky and the only other way i see is to directly change the _globals.scss file which i dont want to do.

**Comment by langri-sha** [comment]
The [recommended approach](http://react-toolbox.com/#/install) is to use [`toolbox-loader`](https://github.com/react-toolbox/toolbox-loader). This will allow you to replace `$unit` in any of your stylesheets without having to `@import` any partials.

I follow the [guidelines](https://github.com/react-toolbox/react-toolbox/tree/dev/components) from the repository, with regards to how styles and sources are organized.

**Comment by Kannaj** [comment]
I am actually using the toolbox-loader in webpack. The problem i mentioned occurs in the scss file used by the loader (toolbox-theme.scss)

```javascript
toolbox:{
    theme: path.join(__dirname, 'src/client/styles/toolbox-theme.scss')
  }
```

**Comment by javivelasco** [comment]
I'm going to PR a new approach with a small package I've made during this weekend. We are going to get rid of the toolbox-loader and everything will be truly customizable. Hope you guys like it!

**Comment by javivelasco** [comment]
Closing in favor of #498
