### ISSUE TITLE
Input component requires value property if you use a label

### ISSUE THREAD

**Issue by ddeklerk** [react-toolbox/react-toolbox#465]
When I want to use the Input component with a label and I don't set the value using state, the label will not stay in its up position when the element is not in focus anymore. I prefer to use refs instead of state to get the value out of my inputs, but this option would not work properly.

In order to replicate the problem:
- Make an Input with a label, but without a value property
- Try typing in the input, this pushes the label out of the way, as expected
- Now when the input loses focus, the label returns to its original position, in the same place that the input value is

If it makes any difference I am using react-toolbox with Meteor and am using version 0.16.2.

**Comment by javivelasco** [comment]
It should not make any difference. I'm quite busy this week, I'll try it during the weekend

**Comment by KerenChandran** [comment]
I can confirm this bug with the latest version of the code. The class `filled` is only applied if there is a value present, and that only occurs if valuePresent returns true. Below is how value present is calculated:

`const valuePresent = value !== null && value !== undefined && value !== '' && !Number.isNaN(value);`
