### ISSUE TITLE
Table renders incorrect with normalize.css@4.1.1

### ISSUE THREAD

**Issue by farwayer** [react-toolbox/react-toolbox#476]
![2016-04-22-134400_1312x241_scrot](https://cloud.githubusercontent.com/assets/2343101/14739468/5bece0b0-0890-11e6-8699-e0ea4c230433.png)

With normalize.css@3.0.3 all ok:
![2016-04-22-134334_1113x222_scrot](https://cloud.githubusercontent.com/assets/2343101/14739471/5ed6ce26-0890-11e6-9dd0-ce5702647f67.png)

**Comment by langri-sha** [comment]
Maybe this #446 is related to your issue?

**Comment by langri-sha** [comment]
What version did you upgrade from?

**Comment by farwayer** [comment]
`0.16` (and upper) version of `react-toolbox` peer depends on `normalize.css@4` and with it table renders incorrect (no row delimiters and vertical white gaps on selected row).

**Comment by farwayer** [comment]
And something wrong with date input also.
![2016-04-24-060034_726x252_scrot](https://cloud.githubusercontent.com/assets/2343101/14765241/06fc6898-09e2-11e6-9bd1-2dd95f752d82.png)

Tested on firefox and chrome.

**Comment by javivelasco** [comment]
Gonna check it during the weekend!

**Comment by javivelasco** [comment]
Updated dependency!

**Comment by farwayer** [comment]
@javivelasco issue is still exists with `normalize.css@4`. You can see it in project table component example.

**Comment by javivelasco** [comment]
Thanks! Gonna check on it

**Comment by farwayer** [comment]
Fixed by #758. Thanks @rubenmoya!

**Comment by javivelasco** [comment]
Thanks for closing!
