### ISSUE TITLE
How to work with designer 

### ISSUE THREAD

**Issue by cometta** [react-toolbox/react-toolbox#479]
If I want further customization besides changing of colors schema. Since css in react-toolbox is in JS format  `{style.exampleCSS}` . How to work with designer to do customization on the css? What technique that you guys use?

**Comment by javivelasco** [comment]
I'm going to PR a new approach with a small package I've made during this weekend. We are going to get rid of the toolbox-loader and everything will be truly customizable. This will be solved by then!

**Comment by lucaas** [comment]
@javivelasco Do you have any more details on the upcoming change? We use toolbox-loader to change all colors in react-toolbox to a dark theme in an application. The current approach works quite well for us, and it would be good if customization of colors by specifying sass variables continues to be possible.

To make customization easier I would recommend standardizing on which values should be specified as variables and documenting those somehow.

**Comment by javivelasco** [comment]
It will be possible to customize in the same way, by overriding variables, but also you would be able to provide a full stylesheet implementing any styles you want which allows to extend component and to make relationship between styles from different components. For example a button, inside a bigger element can be styled without using `data-react-toolbox` attributes. I will release this small module during the weekend, I'm having a really busy week!

**Comment by lucaas** [comment]
No worries, I was just curious about the direction you are going for. That makes sense, thanks for the response.

CSS Modules is very cool and has a lot of benefits, but it does make it harder to customize and overwrite existing rules, so enabling a custom stylesheet might be a solution for that. 

Would it be an all-or-nothing approach? I imagine certain application developers may want to overwrite rules for just one or two components, while others may customize more or less everything.

**Comment by javivelasco** [comment]
Yes, the only caveat is that components will get styles injected so you need to required them yourself. But that would one only in one place. For example, if you want to use the `Button` you will have to require the styles for the button and customize them if you want. That's the only problem...

But if you want to inject the styles I think there is no other way

**Comment by javivelasco** [comment]
Please check #498
