### ISSUE TITLE
Body text line height is too large 

### ISSUE THREAD

**Issue by lucaas** [react-toolbox/react-toolbox#481]
I thought the line height of body text (paragraph elements) was too large, so I modified it my application code. When doing that, I looked at the [spec](https://www.google.com/design/spec/style/typography.html#typography-styles) and it seems to specify the standard body text leading as 20pt, while react-toolbox specifies it as 24pt (2.4 units).

**Comment by javivelasco** [comment]
Closing as the PR is closed too. If anybody else thinks the line height is too large we can make it smaller but I'd like to get more opinions since for me MDL is the closest implementation to the originals and it's using this same size
