### ISSUE TITLE
Autocomplete unintuitive filter behavior with multiple=false

### ISSUE THREAD

**Issue by lucaas** [react-toolbox/react-toolbox#483]
The Autocomplete component with multiple=false behaves unintuitively after a value has been set (in my opinion, at least).

Once a value has been set, the dropdown will only show the selected item, since that is the only match. To change the value, the user must first manually clear the input field before he can select something else. I think it would be a better user experience to show all values until the query has been changed.

For reference on the desired behaviour, see the [react select](http://jedwatson.github.io/react-select/) examples for single selection. 

An alternative approach is taken by [angular material](https://material.angularjs.org/latest/demo/autocomplete), which includes a clear input icon, and does not show suggestions when a value has been set.

**Comment by farwayer** [comment]
Same issue. And simple fix with `onFocus()`  will not work because `Autocomplete` hooks it :(
