### ISSUE TITLE
maxLength does not work when input type is a number

### ISSUE THREAD

**Issue by hamzapurra** [react-toolbox/react-toolbox#490]

**Comment by KerenChandran** [comment]
After investigating this issue, I realized that maxLength is normally used for strings and displays a counter at the bottom right corner describing the total number of characters entered/total number of characters allowed.

Furthermore, [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) states that maxLength is only applied to text, email, search, password, tel or url. There is a max property for input type='number', but that still allows users to enter numbers greater than the max specified.

If you want to display an error to the user, you can use the error property for the input component. Here's a snippet which you can modify to suit your needs.

```jsx
<Input
  type='number'
  value={this.state.number}
  label='Number'
  hint='Enter Your Favourite Number'
  onChange={(value) => this.setState({number: value})}
  error={this.state.number > 12 ? 'Enter a number less than 12' : ''}
  max={12}
/>
```

If you're still confused, please reply back with a better description of your problem. Otherwise, please close this issue.

**Comment by sitaramyadav** [comment]
Does the issue resolve? maxlength is not working with number.

**Comment by atilkan** [comment]
@sitaramyadav Issue is not related to react. So it doesn't resolved. Maybe we can ask smart :P people at w3 consortium.

**Comment by ruanxianzhi** [comment]
It does not work for me as well. There is no constraint on the input length.
<img width="337" alt="image" src="https://user-images.githubusercontent.com/10456677/41422334-b74ba2a8-6fc6-11e8-99df-2bbf2ce46c85.png">
Any thoughts?

**Comment by orosro** [comment]
This is not related to React. maxLength is an HTML property that applies to input of strings, not of type number: 
https://www.w3schools.com/Tags/att_input_maxlength.asp

read here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

If you want to prevent the user from entering a large number use the "max" property

**Comment by targetcreature** [comment]
For anyone else coming across this, here's a quick solution:
```
handleChange = (e) => {
    const val = e.target.value
    const max = 1000
    const maxLength = max.toString().length-1
    const newVal = val < max ? val : parseInt(val.toString().substring(0, maxLength))
    // setState, etc.     
}
```
The above works for maximum digits. For maximum values, replace `parseInt(val.toString().substring(0, maxLength))` with `max`

**Comment by Pratikshit26** [comment]
I tried the same with Ant design ,it dosn't work for type ="number".I removed type and the maxLength property worked for me .I think it a react issue.
![Screenshot 2020-01-23 at 10 31 33 AM](https://user-images.githubusercontent.com/44422899/72957966-8d823e80-3dcb-11ea-9df9-c3687aa9f43b.png)

**Comment by dinuddin** [comment]
i have simple :<input pattern= “^[0–9]$”  class="form-control" id="xxx" placeholder="xxx" name="xxx" maxlength="16" required>

**Comment by kosumoff** [comment]
> I tried the same with Ant design ,it dosn't work for type ="number".I removed type and the maxLength property worked for me .I think it a react issue.
> ![Screenshot 2020-01-23 at 10 31 33 AM](https://user-images.githubusercontent.com/44422899/72957966-8d823e80-3dcb-11ea-9df9-c3687aa9f43b.png)

It's because default value for type is 'text'.

**Comment by RARANEGARA** [comment]
Simple solution is. If we want to set min length 10 then set min="1000000000" as well as max length, if we want to set max length 20 then add max="99999999999999999999". It's will keep the input length in "number" between 10-20 digit.

**Comment by djeico** [comment]
sample:
`[...]
  handleInputChange = (e) => {
    let val = e.target.value
    let maxLength = 6 // <===
    let newValue = val < maxLength ? val : parseInt(val.toString().substring(0, maxLength));
    this.setState({ myProp: newValue });
  }
[...]

[...]
<input
      type="number"  // <=== number  ; )
      onChange={ e => this.handleInputChange(e) }
      name="MyProp"
      value={this.state.myProp}
      className="form-control" />
[..]`

**Comment by mohitdevelops** [comment]
A simple solution where you can have the maximum length and you can't write any text just numbers:-

<input
      type="number"
      placeholder="Contact no."
      value={phone}
      onChange={(e) => {
	      if(e.target.value.length == 11) return false;
	      setPhone(e?.target.value);
      }}						
/>

**Comment by premkumar96-source** [comment]
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
