### ISSUE TITLE
Problem with event triggering events on elements underneath

### ISSUE THREAD

**Issue by dlebedynskyi** [react-toolbox/react-toolbox#494]
I have a dropbox that populates values above some button 
it looks like if you do click on dropbox item right above the button - it will receive event.
It looks like this 
![image](https://cloud.githubusercontent.com/assets/1182917/14928559/9e09ed26-0e26-11e6-87dd-9c6e37107fb7.png)

so if  you click on 2012 - button below click is triggered as well. 
I have a feeling this has to do with `pointer-events: none` set on the button or somewhere like that.

```
%button {
...
> * {
    pointer-events: none;
  }

...
}
````
In my case this behavior is not desired.
 Is there anyway to disable it?  I tried to remove it from button but result is same. 
Or I'm looking wrong way?

**Comment by dlebedynskyi** [comment]
@javivelasco  any change you can look at this please?

**Comment by Danno040** [comment]
Have you tried stopping the propagation of the onClick event for the `Dropdown`?

I had a similar issue where I had a `ListItem` behind a `Menu`, and it selecting a menu item was also clicking the list item behind it. I "fixed" the issue by adding an `onClick` to the menu that simply called `event.stopPropagation`.

**Comment by suancarloj** [comment]
@dlebedynskyi Hey, could you explain how you implemented this ? Because in my case I had to modify the lib file to change the onMouseDown in the renderValue method to onClick for it to work :( 

if I pass an onClick props to the Dropdown the onClick will be passed to the Input which is not what I want.

Thanks in advance :)

**Comment by dlebedynskyi** [comment]
@suancarloj  actually it was my teammate who fixed this. asking to post here for you.
