### ISSUE TITLE
Snackbar decouple timeout and onTimeout

### ISSUE THREAD

**Issue by omerts** [react-toolbox/react-toolbox#496]
When using the snackbar component, and only using the timeout prop, without setting the onTimeout prop, we get the following error:
```
onTimeout is not a function
```

All we want is to hide the snackbar after x milliseconds. Timeout should not be coupled with onTimeout, and should by default hide the snackbar, without having to implicitly implement it. Especially when the docs state:
```
timeout - Amount of time in milliseconds after the Snackbar will be automatically(<--) hidden.
```

**Comment by javivelasco** [comment]
I think this is fixed already
