### ISSUE TITLE
A new theming approach

### ISSUE THREAD

**Issue by javivelasco** [react-toolbox/react-toolbox#498]
Hi guys, sorry I've been a little disconnected over the last 10 days and couldn't check PRs. I'm going to try to get up to date during this week.

There is nothing written in stone with CSS Modules and customization is still something to figure out. React Toolbox's initial approach is attached to Webpack and probably is not the best option. A lot of people want to do more than just overriding SASS variables and there is no easy way to do so.

Today I've released a [tiny package](https://github.com/javivelasco/react-css-themr) to try to have a better style customization approach by using classnames. I'm currently integrating this into a new version that would allow to use browserify if you want. I would love to gather feedback on this. Please let me know if it makes sense and if you would like to see this on React Toolbox.

**Comment by simofacc** [comment]
I am looking forward because I have a problem styling the react-toolbox components as I don't want to have a global theme file. I don't use sass much yet and I'd rather provide a theme file to override the style injected into the component without generating all the extra css code from the component scss.

It could be useful to add a style parameter to the component to inject the style as a theme and override the style. classes in the component with the ones in the custom theme file.

**Comment by simofacc** [comment]
@javivelasco I was also thinking about extending the components to override the styles but I did not have time to explore that idea yet. Maybe the style could be exposed in the context so it could be extended and overridden.

**Comment by javivelasco** [comment]
@simofacc as I said in the first comment, check github.com/javivelasco/react-css-themr. I'm working on the migration and the plan is to release a new version with this customization for the next weekend. I hope to have time enough! 🙃

**Comment by javivelasco** [comment]
As you know I've started working in a migration to react-css-themr to make React Toolbox easier to customize. The implementation is taking longer than I initially thought because there are some components that have instance methods like, for example, the `Menu` component. This is clearly an anti pattern and it doesn't allow to use HOC so it has to be refactored in order to migrate to themr approach.

This can also be a good moment to add to the documentation of each component a *theming* section with the interface that should be implemented for each component. About the variables, I think it makes more sense to provide a link to the configuration file than listing all the variables right in there.

[Here](https://github.com/react-toolbox/react-toolbox/tree/react-css-themr-migration/components/app_bar) is an example for the `AppBar` component. Let me know any thoughts or improvements!

**Comment by genyded** [comment]
Brilliant! I previously spent days trying to glue React Toolbox and Meteor together with various hacks and extra packages and finally gave up. I could get it to work, but with a butt load of extra stuff and it was a going to be a pain to maintain.  

Using this approach and [build4server](https://github.com/ofzza/react-toolbox-build4server) I was able to get React Toolbox up and running with Meteor application without Webpack or CSS modules in a matter of minutes (about 5 or so) and have complete control over the styling. It also works fine in parallel with other components like React Select that install with pre-compiled CSS modules.

Can't wait to finally start using this in the real world because these components look fantastic and seem to cover most of out needs. Make Cards collapsible like the Material UI ones and the world will be full of butterflies and rainbows - great work and support!!!

**Comment by KerenChandran** [comment]
So far this looks good. I reviewed your commits and left some questions/concerns in c7f8d8357a0cdf73b0e77bd333683606a57c0e1e. They are probably dumb and simple questions that can be easily answered.

**Comment by ofzza** [comment]
Am I right to understand that the idea of separating out themes is that the theme file you're importing here:
```
import theme from '[theme path]/app_bar/style';
```
is a simple JS or JSON declaration/mapping of css class-names and that it's up to the theme (separate module) to decide how it handles the rest?
Something like:
```
module.exports = {  
   appBar: 'appBar',
   fixed: 'fixed',
   flat: 'flat'
};
```

Even, if you were thinking of the imported theme file there to still be a .css or .scss file, handled by loaders etc., it at least could be a JS or JSON file - so it's now up to the theme module (not the core react-toolbox module) to use or not to use any of the potentially problematic stuff, like CSS modules, Webpack requirements, etc.

Really looking forward to seeing how you implement the default theme here - this looks awesome so far. :-)

**Comment by KerenChandran** [comment]
@ofzza To me that sounds about right. You can even centralize all the styles in one object with key matching the identifier specified in the component and wrap the app in a ThemeProvider component, and all your custom styles will be loaded!

And as you mentioned, this should reduce the issues with styling cause you can use whatever style format you like (CSS, LESS, SASS, etc)

**Comment by ofzza** [comment]
If that is the case, a suggestion - eventually, can you have:
1) Each component already contain a style.js file with default mappings
2) The root of the react-toolbox module already contain a pre-built, default, .css style file with class-names matching ones referenced in all the style.js files
3) All the components, if there is no "theme" attribute provided, just use the defaults from that local style.js file

With this, if my understanding of what you're aiming for here is correct, someone who's new to this library and only wanted to try it out as fast as possible could just install it and use it without having to worry about theming, 'cos the module would also be able to act as a default theme for itself ...
I'm thinking this could greatly reduce the barrier for entry for a lot of people.

---

BTW, if this sounds at all interesting to you, I'd be more than happy to write a build process from .scss files into style.js files for each component and a main, common .css style.

It would be very similar to what I have in react-toolbox-build4server, where I tried to do a similar thing to what you're doing here - only in a much more limited way.

**Comment by javivelasco** [comment]
Guys, the migration is ready!! I need to review the new README a little. I'd appreciate feeback with the grammar and also I'd love if you can try it before releasing. Also, this is going to be 1.0.0. I think there is no reason to still be in 0.x

Tomorrow I'm releasing on NPM.

**Comment by saghul** [comment]
The links to react-css-themr in [this section](https://github.com/react-toolbox/react-toolbox/tree/react-css-themr-migration#customization-via-theme-property) are broken.

Also, question: the heading says this integrates with "your webpack workflow". Given these changes, is webpack is the way to use this or can I just no use webpack? If so, an example / mention on the readme would be noteworthy.

At any rate, fantastic work thanks for sharing! :heart:

**Comment by javivelasco** [comment]
Yeah, although it still fits the best with webpack, it's not a requirement anymore. I'd like somebody to PR an example with browserify or a link to an example repository. I don't have experience with it and cannot spend too much time trying it out.

I'm gonna try to clarify a little bit more the examples, thanks for the feedback! :)

**Comment by javivelasco** [comment]
Done!!
