### ISSUE TITLE
Can't run npm test

### ISSUE THREAD

**Issue by NogsMPLS** [react-toolbox/react-toolbox#50]
on Windows 7, npm test gives NODE_ENV issue. This can be resolved by changing the scripts section of package.json to:

```"test": "karma start"```

However, even after that is done, I am getting react-transform-hmr errors:

![react-transform-hmr-error](https://cloud.githubusercontent.com/assets/6899011/10944133/3e5ec754-82dd-11e5-8493-ce3582edd17c.PNG)

**Comment by soyjavi** [comment]
Hi @NogsMPLS , can you send us a PR?

**Comment by NogsMPLS** [comment]
I can make a PR for the ```"test": "karma start"```, but that won't fix the react-transform-hmr error

**Comment by javivelasco** [comment]
Apparently env variables are set differently in Windows. I never considered it and I can't either try since I only own Mac. Maybe somebody can help with windows support

**Comment by javivelasco** [comment]
Related to #1

**Comment by javivelasco** [comment]
@NogsMPLS was this resolved for you with #88 ?

**Comment by NogsMPLS** [comment]
Yes the #88 fixed this for me. Let me check the Pull Request again and see if I can get it to pass travis.
