### ISSUE TITLE
Can't install npm module from GitHub

### ISSUE THREAD

**Issue by jeffreywescott** [react-toolbox/react-toolbox#504]
Thanks again for this great library. :-)

I was hoping to install react-toolbox via npm using `github:react-toolbox/react-toolbox` (because there have been some bug fixes that have been merged but not yet released that are pretty critical). Unfortunately, because you don't commit your `lib` folder, it doesn't work.

It's pretty common practice for people who want to ride the "bleeding edge" to install npm modules from GitHub. However, because you have `npm run build` as a `prepublish`, it won't work. Any chance you could follow the `npm` recommendations here and commit your `lib` folder?

**Comment by lzrski** [comment]
Shameless plug: try https://github.com/lzrski/npm-git-install and let me know if it works for you :)
