### ISSUE TITLE
DatePicker doesn't allow for no `value` to be passed

### ISSUE THREAD

**Issue by jeffreywescott** [react-toolbox/react-toolbox#506]
The fix in #474 broke formatting if no value is passed.

**Comment by ro-savage** [comment]
PR #489 fixes this issue. I submitted the fix just after the merge (when I doubled checked commit doh!).

Unfortunately hasn't been merged yet.

**Comment by javivelasco** [comment]
I've already merge #489, as @ro-savage said it's fixing the same thing so I have to close this PR.
Thanks anyway @jeffreywescott :)

**Comment by jeffreywescott** [comment]
Great. Thanks!
