### ISSUE TITLE
Feature request: paper scroll header panel

### ISSUE THREAD

**Issue by emmanuelbuah** [react-toolbox/react-toolbox#511]
It would be great to add the paper scroll header panel control from polymer - https://elements.polymer-project.org/elements/paper-scroll-header-panel. Great job on the toolbox.

Demo's at:
https://elements.polymer-project.org/elements/paper-scroll-header-panel?view=demo:demo/transform-header-1.html&active=paper-scroll-header-panel
https://elements.polymer-project.org/elements/paper-scroll-header-panel?view=demo:demo/transform-header-2.html&active=paper-scroll-header-panel
https://elements.polymer-project.org/elements/paper-scroll-header-panel?view=demo:demo/transform-header-3.html&active=paper-scroll-header-panel

**Comment by javivelasco** [comment]
Thanks @emmanuelbuah, closing in favor of #626
