### ISSUE TITLE
Button component resulting in undefined after build in the browser.

### ISSUE THREAD

**Issue by steviesama** [react-toolbox/react-toolbox#513]
I got the react-toolbox and dependencies to build after a lot of issues, but once I got it built, when I check the test page in the browser which uses a button I'm getting the error in the console on the following screenshot. Probably have to copy and paste the link, for some reason it always gives a github 404.

http://i.imgur.com/8PR3IRv.png

**Comment by KerenChandran** [comment]
If its possible, can you please post the code for IdeaApp (assuming its not a lot) and where you implemented Button. It's been a while since I was working on React Toolbox, but I'm getting a strong feeling that its implementation issues instead of the framework.

**Comment by steviesama** [comment]
Actually I forgot about this post. The next day I checked it and I'd just done something really stupid. I spent quite a while digging into React and I guess I was too absorbed in that and didn't check the simple stuff. I didn't have a link to the react-toolbox.css that it generated. Yeah I know, real "smaat" lol. I've come a long farther now and I have another problem though. I should probably make a github repo for it and push to it for situations like this. It's all working now generally, but when I did a nested styling, it's not applying the nested styles for an h1 and a small tag nested in the h1. I used this same setup in the react-toolbox-example repo, and it works fine. Not sure what's going on. I have the setup as mirrors as I can get it I think. I'll paste some snippets of the short html and the style, though I'm convinced it must be something else since this works in the other repo.

HTML:
[http://i.imgur.com/V4abzcI.png](url)

SCSS:
[http://i.imgur.com/DJaeday.png](url)

The .appbar > h1 > small series aren't applying, but if I directly use the .title class on the h1, it picks that up, and the smallText on the small element doesn't pick up. Though I'd obviously prefer just style the nested element.

**Comment by KerenChandran** [comment]
I noticed that the same styles are used in the repo and they appear to work (clone repo and run npm start), but I'm really not too sure why its not applying the style correctly. Also you mentioned you imported react-toolbox.css, I'm assuming you set a loader in your webpack config file to handle the .scss files.

Note: If you don't want to apply themes, then remove `!toolbox` from loader section. Also make sure you have style-loader, css-loader, postcss-loader, sass-loader and toolbox-loader installed before using this.

``` js 
{
  test: /(\.scss)$/,
  loader: ExtractTextPlugin.extract('style', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass?sourceMap!toolbox')
}
```

If don't want a stylesheet, then you can probably use this: 

``` js 
{
  test: /(\.scss)$/,
  loader: 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass?sourceMap!toolbox'
}
```

If not then that's cool. I'll create a dummy project and test your snippet later today.

**Comment by steviesama** [comment]
Here is the repo url I just pushed to:
[https://github.com/steviesama/idea-app/tree/master/node](url)

The node folder in the idea-app root has the site. I did this because I'm running apache and tunneled to it so it runs from a different location.

idea.js in that folder is the server. The rest should be normal naming conventions.

**Comment by KerenChandran** [comment]
Ok, so I looked into the project and refactored the parts. As of no, your console is clean and I can see the project without any errors.

@javivelasco Please close this issue as its resolved and was an implementation issue.
