### ISSUE TITLE
Avatar examples not rendering properly on iOS.

### ISSUE THREAD

**Issue by steviesama** [react-toolbox/react-toolbox#514]
I was checking something with my react-toolbox app and happened to run the react-tools spec page, and I noticed that unlike in the desktop browser, the avatars render incorrectly on my iPad. It is fully up-to-date. I took a screen shot linked below.

http://i.imgur.com/4yngWIb.png

**Comment by javivelasco** [comment]
Thanks for reporting!

**Comment by lucasljj** [comment]
Now that #666 has been completed, can we close this?

**Comment by javivelasco** [comment]
This is working with the latest version
