### ISSUE TITLE
Where is the FAB?

### ISSUE THREAD

**Issue by outre99** [react-toolbox/react-toolbox#517]
How is it possible that the second most important control for triggering actions in Material Design is not included?
Fab to the people.
Thank you for a great library.

**Comment by javivelasco** [comment]
The FAB is a floating button. `<Button icon="add" floating accent />`

**Comment by outre99** [comment]
With all due respect  the FAB is not just a floating button.  It has
expansion behavior to other buttons, menus, etc. as described in
Material Design spec.  Hence a different name, Fab vs button.

**Comment by javivelasco** [comment]
Floating Action Button (FAB). The expansion behavior can be variable so you can customize the style and provide your own. At the end is a button as you see.

**Comment by outre99** [comment]
True that but the whole point a library is not to have to build basic
functionality and not spend time on pixel tweaking.  By this logic we
can build menus and navigation bars from more basic components but these
are included in your library. So why not a basic FAB?
At the very least an example of how to do that using your library would
help.

**Comment by javivelasco** [comment]
Opinions?

**Comment by felipeleusin** [comment]
I think eventually creating a more complex Fab would be nice and it would be a nice PR. 

<FloatingActionButton open={true|false} iconClosed={icon} iconOpened={icon}>
     <FloatingActionButtonMenuItem icon={icon} label={label} onClick={} />
     <FloatingActionButtonMenuItem icon={icon} label={label} onClick={} />
</FloatingActionButton>

or something like this?

**Comment by outre99** [comment]
Couldn't agree more.
Especially if it can be easily configured to slide into any direction.
Currently Materialize only allows sliding up or to the left, which is
limiting.

**Comment by javivelasco** [comment]
PR welcome for this!

**Comment by javivelasco** [comment]
Closed in favor of #626
