### ISSUE TITLE
Meteor can't find React-Toolbox since v0.16

### ISSUE THREAD

**Issue by sanderdatema** [react-toolbox/react-toolbox#519]
Since react-toolbox went to version `0.16.0` Meteor complains it can't find the module. And I can't for the life of me find out what's wrong.

Did something change in the imports/exports since `v0.15`?

Meteor gives this error:
```text
Unable to resolve some modules:

  "react-toolbox/lib/app" in /Users/Sander/Documents/meteor/administratie/imports/core/pages/Home.jsx (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save react-toolbox
```
Using something like `import ToolboxApp from 'react-toolbox/lib/app';` will result in that error.

Using `import something from 'react-toolbox'` does not get that error, but `something` will be empty and useless.

**Comment by felipeleusin** [comment]
Actually the ToolboxApp was removed on 0.16 if i'm not mistaken so that's why you're getting this error. You can just yank it from your code.

**Comment by sanderdatema** [comment]
Haha, oh this is silly… I should have tested something else as well… Thanks!
