### ISSUE TITLE
Input label not staying on top when containing input after losing focus...

### ISSUE THREAD

**Issue by steviesama** [react-toolbox/react-toolbox#520]
I was gonna use the multiline input to write in some text input, but when it loses focus, the label which has animated to the top, returns to input area of the element.

Here it is animated up top: 
![working](http://i.imgur.com/FIclFZ0.png)

And here it stacks on top of the user input:
![not-working](http://i.imgur.com/sI83eWm.png)

Is there a way to remove this behavior, or is this not intended?

**EDIT:**
If I set a value as a prop, it stays on top...I noticed in the playground app, the label doesn't have any problems. Doesn't make much sense unless there is extra steps that have to be taken to ensure this behavior.

**Comment by dfischer** [comment]
You need to set state/value

**Comment by steviesama** [comment]
State isn't the problem. The label doesn't need to change. It's the the animated behavior. I added state just to test it anyway, but still nothing. Shown in the shot below.

![tested](http://i.imgur.com/Fr1kkDW.png)

The label still dropped back down and overlaps the input if you remove focus from the input box.

Focus as you can see via the text cursor in the input:
![focus](http://i.imgur.com/Dl2HCju.png)

And overlapping when it loses focus:
![nofocus](http://i.imgur.com/wIQJFsr.png)

**Comment by KerenChandran** [comment]
This is a repeated issue, #465. PR #523 somewhat fixes this issue, but is waiting approval.

As mentioned above, you did not set the value parameter of the input field. Furthermore, the value was supposed to have the state, not the label. Treat the state as something that you can mutate, in this case the user's text in the input field. The label is usually static so it can be hard coded string.

To fix this code, include the following:

```js
constructor() { //Don't think you need to include props, unless you're using it in the constructor.
  this.state = {time: 0};
  this.onTimeChange = this.onTimeChange.bind(this); //Required since events are not autobinded in ES6 react
}

//You can make this generic to handle more input cases, but I'll leave that up to you
onTimeChange(value) {
  this.setState({time: value});
}

render() {
  //Change your input line to be the following
  <Input label="Start Timer" onTimeChange={this.onTimeChange} value={this.state.time} />
}
```

**Comment by KerenChandran** [comment]
Furthermore, #465 had issues cause they wanted to use refs. Here it seems more like an implementation issue, unless you were planning on using refs to access input control.

**Comment by javivelasco** [comment]
I don't agree on this. The less state kept in the components the better. The `Input` component is meant to be used without storing state. This means that you have to provide a value if you want it to be filled. The only issue may come because the html input element has state though but it's just used just for convenience when the markup is generated.

So this is more, in my opinion, a bad usage of the component. I understand that if you are using an Input, you should store the data somewhere.

**Comment by steviesama** [comment]
Actually what they were saying about state and value actually fixed this; it was just ambiguous what they mean given the context and example I gave. The problem was I misunderstood what he meant by state/value. I wasn't thinking about value, the property, I was thinking about value as the r-value assigned to the label property I was referring to in the post.

I think maybe Javi interpreted it the same way I did. I was thinking, why would I want to store the value of the label as state since it will never change. But I'm pretty sure the initial suggestion was for the input value property to be stored as state. I did this and it fixed it. I hadn't moved to set state for the input value because I was trying to figure out the label issue. Lmao...

Though, since setting the input.value to state onChange fixed it, I'm wondering if not setting up input.value as state and the label not behaving correctly was actually intended. Doesn't really matter though since you need state for input.value anyway. Though I imagine if it's checking to see if there is a value in order to determine what to do with the label, without state, I suppose React will just keep the value wiped in the virtual dom and that's probably why the toolbox thinks it's empty.

I set the state here, and to the person that mentioned not needing props, I will later, so I left it in.
![constructor](http://i.imgur.com/j735DE2.png)

And here's the handleTextChange method and the render method that fixed it.
![methods](http://i.imgur.com/ZX2E1bK.png)

**Comment by javivelasco** [comment]
Thanks for your comment :) Yeah, that's the thing. I think if you don't, let's say "need to store" the state, it may be useful to keep it in the input automatically, but this way is up to you. Do you think we should change it and keep state inside as well? I did not find an easy way to keep the label up when the input html element has value but you are not handling yourself...

**Comment by KerenChandran** [comment]
I agree with not having state inside the component. The case in #465 was the user wanted to use refs to access the text in the input field. As a result, the value property was set to null and no state was passed into it. I was confused whether @steviesama was trying to implement refs or was using state with the value property with a onChange handler. Tbh, I do the latter, but I submitted a PR to solve #465

As mentioned in #465, I did not want to add state (and didn't in the PR), I suggested that we could have a forceLabel property for the component which the programmer can specify as true or false so the programmer controls the label controls. It doesn't interfere with the current implementation and only solves the issue in #465.

**Comment by steviesama** [comment]
@javivelasco I don't know if I would want to require state since it could be that you want to access it another way like @KerenChandran was talking about. And to be clear, I wasn't trying to access it via refs, it was just I hit that label issue before I had added much code so you couldn't tell from the code what I was trying to do. My intention was to use state for the value though with the onChange handler, etc; I just hadn't gotten to that point. I didn't expect the label to have that behavior because I wasn't persisting the value with state. It makes sense after thinking about it that it didn't behave correctly thought thinking about how it probably works. I'm for whatever gives the most robust set of options, but I'm also for methodology, so whatever you go with just maintain consistency for the behavior of the toolbox is easier to reason about.

**Comment by adrianmc** [comment]
Shouldn't the input internally have an onChange detection and force the label up to the top if it is non-empty? I don't see why I have to use state in order to use this component.

**Comment by javivelasco** [comment]
The issue is that the native `input` implementation has an internal state. I've found much easier at the time of implementing to make the component fully stateless. Changes from the top were not easy to track and the best solution I've found so far was just to make the `Input` stateless. This approach means that you need to provide always a value. IMO it's not an issue anyway because I think that in most scenarios you'll be storing the value somewhere else.

**Comment by adrianmc** [comment]
After using it for a few days, I feel that this is fine. That being said, it might be a good idea to include this tidbit in the docs so newcomers don't get confused.

**Comment by ShenAdrada** [comment]
https://cloud.githubusercontent.com/assets/26157352/23640441/b515b6ce-0328-11e7-960c-1b99730f04d8.png

"Multiline input not aligned on its textarea (working on single line)"
any solution for this? seems working on firefox, but not in chrome.

**Comment by javivelasco** [comment]
The example in `spec` looks fine. Maybe you missed something? Can you provide a code to reproduce the issue or a playground snippet?
