### ISSUE TITLE
support for bottom sheet

### ISSUE THREAD

**Issue by dsikes** [react-toolbox/react-toolbox#521]
is there any plans to support bottom sheet? 
Angular Material implements it here: https://material.angularjs.org/latest/demo/bottomSheet

Would a PR be welcomed for this feature?

**Comment by felipeleusin** [comment]
It would most definitely be welcomed.

Em sex, 20 de mai de 2016 às 00:05, Dan Sikes <notifications@github.com>
escreveu:

> is there any plans to support bottom sheet?
> Angular Material implements it here:
> https://material.angularjs.org/latest/demo/bottomSheet
>
> Would a PR be welcomed for this feature?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/react-toolbox/react-toolbox/issues/521>
>
-- 

Felipe Amorim

Diretor - SaídaCerta

(21) 98121-0804

**Comment by javivelasco** [comment]
PR welcome! :)

**Comment by javivelasco** [comment]
Closing in favor of #626
