### ISSUE TITLE
Tabs current line in wrong position when using scroll

### ISSUE THREAD

**Issue by gabrielenosso** [react-toolbox/react-toolbox#522]
Hi guys, I'm using the Tabs with a scroll for my mobile layout.
They are part of the Google Material Design:
https://www.google.com/design/spec/components/tabs.html#tabs-types-of-tabs
The second type is the "Scrollable tabs".

The problem is that the position of the line doesn't take care of the left scroll.
You can check it in the image attached.
![tabs probelm](https://cloud.githubusercontent.com/assets/4018887/15428598/9364dc56-1e9c-11e6-9b2f-0ec5257bfaf2.png)

You can easily achieve the same result going on the React Toolbox website:
http://react-toolbox.com/#/components/tabs
and adding the "overlfow-x: scroll" rule to the element with the attribute data-react-toolbox="tabs"

**Comment by javivelasco** [comment]
Thanks for reporting!

**Comment by thovo** [comment]
I encountered the same problem with Tabs when I used a fixed width to contain the navigation part, it looks like the active line will be added before I moved to the full display of active tab.
Image attached:
![scrollabletab](https://cloud.githubusercontent.com/assets/1543066/17480246/433a5caa-5d77-11e6-9358-8e4f8659e728.png)

Could we have some options to let the tab horizontal scrollable and customization? Currently, I just add the `overflow-x: auto` to enable the default scrollbar of browser, can we use other React component for this scrollbar like `[react-custom-scrollbars](https://github.com/malte-wessel/react-custom-scrollbars)`

**Comment by thovo** [comment]
Can we have some update of this bug?

**Comment by javivelasco** [comment]
Can you try the updates made with https://github.com/react-toolbox/react-toolbox/pull/706? I'll try to give a look soon. That project looks very nice!

**Comment by therealparmesh** [comment]
I am attempted to push tab pagination through here: https://github.com/react-toolbox/react-toolbox/pull/975

**Comment by javivelasco** [comment]
This can be closed I guess :)
