### ISSUE TITLE
don't use refs for firing actions

### ISSUE THREAD

**Issue by luisrudge** [react-toolbox/react-toolbox#53]
I'm seeing a few components (snackbar, dialog and drawer) that are using `refs.show` or `refs.hide` to do toggle visualization.

What do you think about changing that to use props instead? Using refs means that anyone using any flux implementation will have to change the mindset around the component state :(

**Comment by javivelasco** [comment]
Check PR #34 
We are moving to pure functional components. This is one of the things I wanted to change before the first release but also I wanted to publish the components before Reactive Conference 2015. Will be done so closing!

Thanks!

**Comment by luisrudge** [comment]
Ohhh, thanks! :)
