### ISSUE TITLE
Add some features to Table

### ISSUE THREAD

**Issue by wolfoO** [react-toolbox/react-toolbox#531]
Can you add 3 things to table?

1. Ability to select a row when you click on whole row.

2. Ability to hide checkboxes but can still select rows.

3. Ability to add onClick handler to each rows.

**Comment by javivelasco** [comment]
PR welcome

**Comment by kenjiru** [comment]
These are really useful features, but I think they would require a pretty big refactoring.
@javivelasco Do have any changes in the pipeline for the table component?

**Comment by q3452** [comment]
I think your three items are really just "add onClick handler to table rows" which should be a pretty easy enhancement.
@wolfoO Have a look at components/table/Table.js and add a prop to receive a function like 'onRowClick' and pass it to the rows as an 'onClick'.  That should do what you want.

**Comment by javivelasco** [comment]
All of this can be done with the new implementation. Please leave feedback
