### ISSUE TITLE
Dialog brokes the <body> (also in the online Demo)

### ISSUE THREAD

**Issue by gabrielenosso** [react-toolbox/react-toolbox#532]
If you go there, http://react-toolbox.com/#/components/dialog , then show the dialog and close it, you notice that at the border of the window some scrollbars appear.

I don't know why, but in some way it adds the CSS rule "overflow: scroll" to the <body> element.

It seems crazy :)

**Comment by javivelasco** [comment]
Fixed in the new release!

**Comment by gerhardsletten** [comment]
@javivelasco In which release is this issue fixed?

**Comment by gerhardsletten** [comment]
My problem was that I did not render the Dialog component when it was not active, so it did not get a chance to clean up the body-tag. Mayby there should be a not in the docs about that?

**Comment by javivelasco** [comment]
A full example would be helpful. Anyway the `Dialog` is not rendered if it's not active so you can delegate that piece of code to react-toolbox :)
