### ISSUE TITLE
could we get a new release on npm?

### ISSUE THREAD

**Issue by acornejo** [react-toolbox/react-toolbox#534]
A few bugfixes have gone in, and it would be nice to have them (I am looking at you ListItemLayout).

I know this would make #504 happy too.

**Comment by javivelasco** [comment]
Soon. I'm finishing a [new version](https://github.com/react-toolbox/react-toolbox/tree/react-css-themr-migration)

**Comment by kodermax** [comment]
It's great!

**Comment by acornejo** [comment]
ooohhh, shiny! I'll keep my eyes on it.

**Comment by ab712** [comment]
Eta on this? We evaluated this today but are going to hold off on going all in because of a few issues we've hit that seem to be fixed on dev.

**Comment by javivelasco** [comment]
I have it almost ready. Just need to write some documentation about how customization is done now and about themr. Apart from that theres is not a lot of stuff todo so I'll be able to dedicate time today and tomorrow. 

Sorry for the delay, but this is not the project that feeds me you know... priorities 😬

**Comment by ab712** [comment]
I get that. Would be nice to have seen the maintenance releases for some of the existing fixes pushed out separate from the larger themr refactoring. That being said, I'll wait patiently for the new release :)

**Comment by javivelasco** [comment]
[Ready!!!](https://github.com/react-toolbox/react-toolbox/releases/tag/1.0.0)
