### ISSUE TITLE
Add ability to use node as label for radio button

### ISSUE THREAD

**Issue by AleksandrZhukov** [react-toolbox/react-toolbox#536]
Hey guys what do you think about adding ability to use node as label for radio button (for checkbox label as well) or maybe use children as label.
For example when you need to add custom styles for label, like on this img
![Radio Button](http://pix.toile-libre.org/upload/original/1464716883.png)

**Comment by kodermax** [comment]
I think, this is not interesting idea, it's not material design.
Can you give real examples?

**Comment by AleksandrZhukov** [comment]
Real example from my project
![Example](http://image.prntscr.com/image/45595622aa1b43c88cb817d23ac7c97b.png)

**Comment by kodermax** [comment]
Так это надо св-во label сделать универсальным, чтобы помимо текста, можно было вставить html какой угодно.

**Comment by AleksandrZhukov** [comment]
Да, именно это я и предлагаю. Просто сейчас `label` может быть только строкой, а если сделать возможность получать его из `props.children`, либо как `node` - все будет отлично. Могу сделать ПР на добавление подобной возможности.

**Comment by kodermax** [comment]
Да нужен PR

**Comment by javivelasco** [comment]
If we are talking about styles here, you will be able to customize it with the new version. In case you want to do something like in your example the only way would be to use a node as label property. I think it's something very easy to do and it does not have any drawbacks so it can be added. Feel free to submit a PR!
