### ISSUE TITLE
Unable to write tests

### ISSUE THREAD

**Issue by ab712** [react-toolbox/react-toolbox#539]
I would like to start contributing to this project, but I'm not sure how to contribute code that is thoroughly tested. There isn't a mention of this on the contribution section so I thought I'd bring it up.

The project is using a set up I'm not familiar with, having mostly seen BDD style describes and its used to define a unit of code and how it is expected to behave. I've tried both commenting out test code and production code and can't get failures to occur from the test suite. I've also tried adding a new spec file to include describe()'s and it()'s that have obviously failing expectations (like false === true).

I would love to help out switching to a more BDD approach if the project maintainers are on board. The benefit is that the project will be more regression proof as individual component behaviors are tested vs just their ability to be mounted or compiled by Babel. Also, new features can be added safely and rapidly without fear of breaking existing features because of the backlog of tests that verify existing capabilities.

Does anyone have any opinions or objections to this being an actionable item I can pick up? Would love to start contributing since I plan on using this project for a long-term project.

**Comment by javivelasco** [comment]
I've forgot about this issue @ab712 ! Of course it would be great to have a better testing support and coverage. When I've started the project I wanted to write tests for every component but testing this kind of UI components is not easy. I've wrote some examples with the `Button` that has a more complex logic to figure out classNames and the `Slider` that wasn't easy at all. You can start checking them if you didn't already.

When I finished every component that is present today I wanted to write tests for them but as you know, it's not always easy to find time and motivation to do so once the components are generally working. I think tests should tested like:

- Nodes responds to events properly.
- Components with internal state change as expected with interaction.
- Components with behavior in instance methods has an appropriated input/output (see the slider).
- Classname composition is the expected one for each combination of props.

It could be great to see a component with a proper testing done and is it as a template to write tests for the rest of components.
