### ISSUE TITLE
card's shadow

### ISSUE THREAD

**Issue by luisrudge** [react-toolbox/react-toolbox#54]
![image](https://cloud.githubusercontent.com/assets/941075/10945660/a0a92530-8305-11e5-98d4-400026bfd219.png)

* Left: [react-toolbox's card](http://react-toolbox.com/#/components/card)
* Right: [google's card](https://www.google.com/design/spec/components/cards.html#cards-usage)

I'm noticing that toolbox's card shadows are slightly different than google's and it's pretty hard to notice the shadows at all with a white background:

![image](https://cloud.githubusercontent.com/assets/941075/10945743/f04fc79c-8305-11e5-9eb8-8bc334deb14f.png)

**Comment by javivelasco** [comment]
Yes, the shadows are quite smooth. If anybody can get a closer approach to MD I'll be happy to check and merge :) I think the current proposal is taken from MDL which should be very close considering that the project comes from Google.

Closing to reduce noise in the issues, thanks @luisrudge !
