### ISSUE TITLE
button component not rendering properly in safari

### ISSUE THREAD

**Issue by Pyrolistical** [react-toolbox/react-toolbox#542]
<img width="616" alt="screen shot 2016-06-05 at 9 11 53 pm" src="https://cloud.githubusercontent.com/assets/463642/15811816/2e7a03e8-2b62-11e6-83fa-bacfa992de00.png">
<img width="284" alt="screen shot 2016-06-05 at 9 12 31 pm" src="https://cloud.githubusercontent.com/assets/463642/15811821/3a263806-2b62-11e6-89c1-c3a08eecfdbd.png">

**Comment by javivelasco** [comment]
This probably has to do with the `inline-flex` thing. Gonna take a look this afternoon

**Comment by Danno040** [comment]
@javivelasco: It seems that there are issues both ways. #529 said `inline-flex` fixed an issue, and now you've reverted it here.

What I have noticed is that `<button>` elements are display properly now, but `Buttons` that become `<a>` tags are not. See screenshot:

![Text buttons not displaying properly](https://cloud.githubusercontent.com/assets/81397/16505370/de1ff7dc-3ed9-11e6-98b0-faa1cc4679f7.png)

I believe anchor tags need to be `display: inline-flex`, and buttons can stay as is.

**Comment by smazurov** [comment]
@javivelasco any update on this issue?

**Comment by javivelasco** [comment]
I couldn't reproduce it. For me it looks well in Safari and I have no iPad right now to check on it. My iPhone is rendering nicely too..

**Comment by Danno040** [comment]
Did you change the code to not have an icon? Like this?

```html
<Button href='http://github.com/javivelasco' target='_blank' raised>
  Github
</Button>
```

The above code is broken for me on Chrome and Safari on Mac (only browsers tested).
