### ISSUE TITLE
Table allows react elements as cell values but that is not clear from the documentation

### ISSUE THREAD

**Issue by shishircc** [react-toolbox/react-toolbox#543]
Allowing table cell values to be react elements is great flexibility. However this is not clear in documentation. 

I suggest updating the documentation to include this important information.

**Comment by felipeleusin** [comment]
I actually think the current Table implementation should be switched to something like DataTable and the basic Table with TableHeader, TableBody and others should be made avaiable a fully customizable. Would this PR be welcomed @javivelasco ?

**Comment by javivelasco** [comment]
Yeah, I think you're right. We should have ha simpler one with just CSS

**Comment by felipeleusin** [comment]
I'll get on it, was waiting for the theme refactor.

**Comment by javivelasco** [comment]
Great! 💃

**Comment by coljung** [comment]
Any updates on this @felipeleusin ?
Thx

**Comment by javivelasco** [comment]
Please check the PR!
