### ISSUE TITLE
Tooltip not usable in div with overflow hidden

### ISSUE THREAD

**Issue by gabrielenosso** [react-toolbox/react-toolbox#544]
I think this is an enhancement that I am requesting:
right now the <Tooltip> doesn't work if you have containers with overflow hidden.

Could it be possible to solve this?
Practically the Tooltip should be rendered at root level, so that user can adjust its z-index with CSS.

**Comment by javivelasco** [comment]
Yes, we can use a similar approach to Dialogs using Portal, it shouldn´t be difficult

**Comment by gabrielenosso** [comment]
Will it be done?
As it is, it is quite a limitation...

**Comment by javivelasco** [comment]
Sadly I don't have to much time now, PRs are welcome for this :)

**Comment by javivelasco** [comment]
Done in #694
