### ISSUE TITLE
IconMenu positioning not working since 1.0.0? 

### ISSUE THREAD

**Issue by mgcrea** [react-toolbox/react-toolbox#550]
Not sure if I've missed something but the `IconMenu` demo (http://react-toolbox.com/#/components/menu) seems broken, the menu does impact the flow of DOM elements when closed (eg. hidden but still there in the DOM), shouldn't the position be absolute-like?

Also tried to play with the `position` attr/prop, and nothing changes.

Is it a regression or has it always behaved like this? Is this open for a PR?

**Comment by Danno040** [comment]
I believe it's because they [renamed all the position constants](https://github.com/react-toolbox/react-toolbox/blob/dev/components/menu/Menu.js#L9) in 1.0.0, and don't validate against them.

Essentially, if you're using `top-left`, you should be using `topLeft`.

**Comment by Danno040** [comment]
Submitted a PR, so we can be the last to be affected by this issue. :)
