### ISSUE TITLE
Passing through id attribute for use with media selectors (etc.)

### ISSUE THREAD

**Issue by jasonm23** [react-toolbox/react-toolbox#563]
It would be useful if the components would accept and pass on an `id` attribute, so that CSS defined media selectors would be able to semantically target specific component root elements.

For the moment we appear to have to use CSS selectors such as:

```
@media (min-width: 600px) {
  [data-react-toolbox=navigation][class*='vertical'] {
    display: none;
  }
}
```

**Comment by awatson1978** [comment]
YES!  This!  

Adding ``id`` attributes to elements is a best-practice for acceptance, end-to-end, and validation testing.  The automated browsers (generally driven by webdriver, selenium, etc) need the ``id`` attributes to 'grab onto'.  

Currently running into trouble with ``IconMenu`` and ``ListItem``, but I'm sure there will be others.

**Comment by javivelasco** [comment]
I would have no problem about moving the layers identifiers to ids. At first we chose to use data attributes just in case you want to use the prop spreading to assign and id yourself. More opinions??

**Comment by javivelasco** [comment]
You can achieve this behavior using theme objects
