### ISSUE TITLE
Autocomplete suggestions should use .includes()

### ISSUE THREAD

**Issue by thearrow** [react-toolbox/react-toolbox#566]
Using `.startsWith()` on this line:

https://github.com/react-toolbox/react-toolbox/blob/afde8b1aa21122aabac1145346ad74f2c4a1782e/components/autocomplete/Autocomplete.js#L154

...is of extremely limited usefulness because it will only suggest matches that start with the query. 

Can this just be switched to use `.includes()` instead (to match the query anywhere in the string)? 

Would you want a prop added to the Autocomplete component to control this behavior? 

Am willing to do a PR if needed, just wanted to see if this has been discussed before and which approach would be favored.

**Comment by ro-savage** [comment]
I'd like to see a prop to control the behaviour.

1) Starts with
2) Anywhere inside the string
3) Starts with, each word (e.g. 'Ro Savage' would match on 'R' and 'Sa')

**Comment by thearrow** [comment]
👍 I'll start work on a PR

**Comment by thearrow** [comment]
PR #572 adds the `suggestionMatch` prop to the Autocomplete component with the three options `start`, `anywhere`, `word` like @ro-savage mentioned.
