### ISSUE TITLE
How to write tests with Karma

### ISSUE THREAD

**Issue by mistre83** [react-toolbox/react-toolbox#574]
I've setup my project with react-toolbox and works fine.
Now i would like to use Karma to test it (Karma use for example Chrome) as browser so i think i have to include react-toolbox in karma.conf.js

Right now my karma.conf.js is this, how i can "complete" it to use React Toolbox and write test ?

```
var webpackConfig = require('./webpack.config.js');

module.exports = function(config) {
    config.set({
        browsers: ['Chrome'],
        singleRun: true,
        frameworks: ['mocha'],
        files: [
            'app/tests/**/*.test.js'
        ],
        preprocessors: {
            'app/tests/**/*.test.jsx': ['webpack', 'sourcemap']
        },
        reporters: ['mocha'],
        client: {
            mocha: {
                timeout: '5000'
            }
        },
        webpack: webpackConfig,
        webpackServer: {
            noInfo: true
        }
    });
};
```

**Comment by javivelasco** [comment]
Take as a reference the tests configuration in react-toolbox. I think it should be the same, the only thing to take into account is that you should still have a loader for css. If you don't want to actually import the css you can use something like `null-loader`

**Comment by mistre83** [comment]
Thanks for the reply. I close this
