### ISSUE TITLE
FontIcon with children is missing classname 'material-icons'

### ISSUE THREAD

**Issue by BaoDelta** [react-toolbox/react-toolbox#575]
Hi,

The example in http://react-toolbox.com/#/components/font_icon is not working. The last item shows the text 'star' instead of the icon.

Viewing the code, I can see this line:

```
className={classnames({'material-icons': typeof value === 'string'}, className)}
```

Should it also have classname 'material-icons' when children are a string?

Otherwise, I must use:
```
<FontIcon className='material-icons'>star</FontIcon>
```

**Comment by javivelasco** [comment]
Yes, you are right. Wanna PR??
