### ISSUE TITLE
How react-toolbox load custom SCSS?

### ISSUE THREAD

**Issue by mistre83** [react-toolbox/react-toolbox#578]
Since yesterday i'm try to find out what was wrong in my application with this errors:

Warning: Failed propType: Invalid prop `component` supplied to `Route`.
Warning: [react-router] Invalid undefined `component` supplied to `Route`.
Uncaught Invariant Violation: The root route must render a single element

after many and many hours i've figure out that if i simply have a file called App.scss and App.js, i got this error. I dont load this file anywhere, i simply create it.

If i delete the file, the application works again.

My router is this:

```
import React from 'react';
import { Route, IndexRoute } from 'react-router';

import App from './containers/App';
import Dashboard from './containers/Dashboard';

export default (
  <Route path="/" component={App}>
      <IndexRoute component={Dashboard} />
  </Route>
);

```

I think is a standard routing... so.... how react-toolbox load .scss files that have the same name to another .js ? (fo example, App.scss and App.js)

**Comment by javivelasco** [comment]
You have to tell webpack which file are you loading if they are named the same. It cannot figure out the extension because both can be imported with `import Whatever from './Whatever'` if they are `Whatever.scss` and `Whatever.js`.

I think this is not related to react-toolbox so I'm closing!
