### ISSUE TITLE
theme not working as expected

### ISSUE THREAD

**Issue by riorulzz** [react-toolbox/react-toolbox#580]
I am trying to apply theme on ListItem but it is not working as expected.
Below is the code :-

`<ListItem theme={AlertBoxTheme} leftIcon={alertIcon} caption="ALERT TYPE"
                    legend="This is the defination of alert"
                    rightActions={rightActions}>
                    </ListItem>
`

`AlertBoxTheme:-
.left{
background-red
}`

.listItem appears to work but not .left, .item ..

Am i doing something wrong ?

**Comment by javivelasco** [comment]
May you provide more information? Take into account that:
- By default the classnames resulting from your theme are *added* to the default unless you specify so via props.
- Your css should be located *after* the original if the priority on your rules is the same as the default theme.

Try adding a className to the customized component and nest your theme into it. This way you will see if it's a priority issue or something else.

**Comment by randycoulman** [comment]
I ran into this issue as well and submitted #618 to fix it.  The problem is that `ListItem` is not passing the `theme` prop down to its internal `ListItemLayout` component, so nothing rendered by `ListItemLayout` is able to apply the theme.

**Comment by javivelasco** [comment]
Great! Thanks!!
