### ISSUE TITLE
can not resolve the module postcss in react-toolbox button

### ISSUE THREAD

**Issue by Dhaval8087** [react-toolbox/react-toolbox#581]
below is my webpack config

`var path = require('path');
var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');

var autoprefixer = require('autoprefixer');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  devtool: 'inline-source-map',
  entry: [
      'webpack-hot-middleware/client',
      './src/main.js'
  ],
  output: {
    path: path.join(__dirname, '/dist/'),
    filename: 'bundle.js',
    publicPath: '/'
  },
  resolve: {
    extensions: ['', '.scss', '.css', '.js', '.json'],
      modulesDirectories: [
        'node_modules',
        path.resolve(__dirname, './node_modules')
  ]
 },
  plugins: [
    new webpack.optimize.OccurenceOrderPlugin(),
    new ExtractTextPlugin('react-toolbox.css', { allChunks: true }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('development')
    })
  ],
  module: {
    loaders: [{
      test: /\.js?$/,
      exclude: /(node_modules|bower_components)/,
      loader: 'babel'
    }, {
      test: /\.json?$/,
      loader: 'json'
    },
    { test: /\.css$/, loader: 'style!css' },
    {
        test: /(\.scss|\.css)$/,
        loader: ExtractTextPlugin.extract('style', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass')
    }
    ]
  },
  postcss: [autoprefixer],
   sassLoader: {
     data: '@import "' + path.resolve(__dirname, 'app/theme/_config.scss') + '";'
  },
};
`

**Comment by javivelasco** [comment]
This doesn't look like an issue of the package. Please refer to the [example](http://github.com/react-toolbox/react-toolbox-example). There are also some closed issues referring to configuration that may help you.
