### ISSUE TITLE
Best way to customize global attributes

### ISSUE THREAD

**Issue by iampeter** [react-toolbox/react-toolbox#587]
I'd like to make global customizations that are not covered by the variables, for example I'd like `text-transform: none;`

What is the best way to do it?

**Comment by javivelasco** [comment]
I think that those globals can be easily configured overriding with traditional CSS. Also, importing `common.scss` is optional, but you'd need to set a root font size according to what components expect (10px). Also we can extract it to a variable in case it's defined directly in components, or also you can give that override via theming
