### ISSUE TITLE
min Height on dropdown

### ISSUE THREAD

**Issue by kennyw12** [react-toolbox/react-toolbox#589]
There is a min height on `.theme__templateValue___3if5o`. This makes rendering plain text in dropdowns not as straight forward. Is there a reason for the min height being set?

**Comment by javivelasco** [comment]
Can't tell right now... you can try to remove it and if everything works fine we can merge it :)

**Comment by neekey** [comment]
I remove it to make it work. Anyway, according to Google Material Design's principle, if the menu can scroll, it should have a scroll bar:

![image](https://cloud.githubusercontent.com/assets/499870/18298530/8ea73ebe-74fc-11e6-97dc-96ce3d1e80cd.png)

**Comment by javivelasco** [comment]
Closing in favor of #1029
