### ISSUE TITLE
.babelrc incompatible with Babel 6

### ISSUE THREAD

**Issue by joshuaegclark** [react-toolbox/react-toolbox#59]
the current .babelrc uses the "stage: 2" option which is no longer supported in the latest Babel, which causes it to throw an error if you are using Babel >= 6.0.0.

**Comment by javivelasco** [comment]
Ok! Updating config to babel 6. Thanks for reporting!

**Comment by javivelasco** [comment]
I will be happy to accept any PR with a HMR configuration using Babel 6!

**Comment by hasyee** [comment]
What's about Babel 6 updating? Thanks!

**Comment by javivelasco** [comment]
Yep, as I said in the previous comment, contribution here is very welcome. BTW, I don't know yet about babel 6 support in HMR which is very useful for development...

**Comment by nathanmarks** [comment]
Waiting on this, https://github.com/gaearon/babel-plugin-react-transform/issues/46

**Comment by javivelasco** [comment]
Perfect, so as soon as we get support we can update! 
Thanks @nathanmarks !

**Comment by Bernardstanislas** [comment]
@javivelasco I think you can use [react-hot-loader](https://github.com/gaearon/react-hot-loader) to achieve HMR with Babel 6, we did this in [our projects](https://github.com/KleeGroup/focus-comments/blob/develop/webpack.config.js#L34) and it works like a charm :)

**Comment by javivelasco** [comment]
Awesome! Gonna work on it during the afternoon. Thanks @Bernardstanislas :)

**Comment by carloscuatin** [comment]
@javivelasco create a roadmap for upgrade to babel 6

**Comment by javivelasco** [comment]
Yeah we should. I was waiting for HMR to be updated and it seems it's coming. I'll have some time to work on toolbox during the weekend and I'll try to release some changes and set up next priorities. This should be one of them

**Comment by carloscuatin** [comment]
@javivelasco create a roadmap, i create pull request for upgrade

**Comment by guerrero** [comment]
@javivelasco It seems that this issue can be closed without further actions

**Comment by javivelasco** [comment]
Yep! thanks @guerrero !
