### ISSUE TITLE
Poor support in typescript

### ISSUE THREAD

**Issue by ixrock** [react-toolbox/react-toolbox#591]
1) Bundled root `index.d.ts` exports not all components, for example `IconButton` not available.
2) If I export something from package bundle, e.g `import { AppBar } from 'react-toolbox'` typescript compiler throws errors:

> ERROR in [default] /Users/ixrock/Desktop/Projects/account-ui/node_modules/react-toolbox/lib/navigation/index.d.ts:41:17 
Cannot find name 'ButtonProps'.

> ERROR in [default] /Users/ixrock/Desktop/Projects/account-ui/node_modules/react-toolbox/lib/navigation/index.d.ts:45:16 
Cannot find name 'LinkProps'.

3) Missed typings for `components/lib/ripple` and `components/lib/layout` (no `index.d.ts` at all)
4) Import for most of the components with only single export default class, e.g `Avatar`, `Input`, etc. works only if it imports as default, e.g `import Input from 'react-toolbox/lib/input'` and it's not working with curly braces, e.g `import { AppBar } from ...`.
I use WebStorm and code complete works only inside `{}` for import statements. 
Plus it would be nice to have consistency along other components with no default export, e.g `import {Tab, Tabs} ...`. Otherwise I need to guess does some component have default export or not to proper import it.

**Comment by javivelasco** [comment]
I can't help too much with this, I've never used TS. The bindings we provide are PRs from the community so from my side I can't do a lot...

**Comment by galvesribeiro** [comment]
@javivelasco maybe you should use something like `autodts` to generate the bindings for it... Every component we've seen today if isn't made in TypeScript at least offer the the definition files... I'm missing the `Layout` definition... IMHO, if you can't do anything about it, you should at least state on your page that you * DON'T*  support typescript otherwise, after a big amount of time invested on your component will be waste like I did. I'm now looking to something more modern and open to use...

**Comment by ixrock** [comment]
I came up with temporary solution by providing re-export of everything from react-toolbox:

**components/react-toolbox/index.ts**
```
export const { Layout, Panel, NavDrawer, Sidebar } = require('react-toolbox/lib/layout');
export const Navigation = require('react-toolbox/lib/navigation').default;
export const Ripple = require('react-toolbox/lib/ripple').default;

export { default as AppBar } from 'react-toolbox/lib/app_bar'
export { default as Autocomplete } from 'react-toolbox/lib/autocomplete'
export { default as Avatar } from 'react-toolbox/lib/avatar'
export { Button, IconButton } from 'react-toolbox/lib/button'
export { Card, CardTitle, CardMedia, CardText, CardActions } from 'react-toolbox/lib/card'
export { default as Checkbox } from 'react-toolbox/lib/checkbox'
export { default as Chip } from 'react-toolbox/lib/chip'
export { default as DatePicker } from 'react-toolbox/lib/date_picker'
export { default as Dialog } from 'react-toolbox/lib/dialog'
export { default as Drawer } from 'react-toolbox/lib/drawer'
export { default as Dropdown } from 'react-toolbox/lib/dropdown'
export { default as FontIcon } from 'react-toolbox/lib/font_icon'
export { default as Input } from 'react-toolbox/lib/input'
export { default as Link } from 'react-toolbox/lib/link'
export { List, ListCheckbox, ListItem, ListDivider, ListSubHeader } from 'react-toolbox/lib/list'
export { Menu, MenuDivider, MenuItem, IconMenu } from 'react-toolbox/lib/menu'
export { default as ProgressBar } from 'react-toolbox/lib/progress_bar'
export { RadioButton, RadioGroup } from 'react-toolbox/lib/radio'
export { default as Slider } from 'react-toolbox/lib/slider'
export { default as Snackbar } from 'react-toolbox/lib/snackbar'
export { default as Switch } from 'react-toolbox/lib/switch'
export { Tabs, Tab } from 'react-toolbox/lib/tabs'
export { default as TimePicker } from 'react-toolbox/lib/time_picker'
export { default as Tooltip } from 'react-toolbox/lib/tooltip
```

So for now I'm able to do `import {Layout, IconButton} from 'components/react-toolbox'`

**Comment by galvesribeiro** [comment]
@ixrock thanks. But I refuse to make something like this to get something to work... We changed to meterial-ui since it has full support to TypeScript and is simples to theming along with more components implemented from Google Materia design.

**Comment by JeroenNelen** [comment]
hello @ixrock , @galvesribeiro,

It seems I have more or less the same setup as you (mine is typescript + react/redux +  webpack + sass).
Next to the issues mentioned here (with the typings and the imports) I am having a hard time overwriting styles for the components, except from general theming. 
I explained the issue more thoroughly in this issue: https://github.com/react-toolbox/react-toolbox/issues/121#issuecomment-228440473
@galvesribeiro I am also considering switching to material-ui, however I read quite some things about performance issues and it also requires you to (over)write styling inline inside of the components, while I would have preferred to keep the styling in external .scss files. How are you tackling this, are you just doing all your styling inline ?
@ixrock have you tried overwriting styling set in react-toolbox components (fictive example: if on one page you want the height of a button to be 30px, on another one you want it to be 50px), I'm currently not able to get this to work (see the other issue for a more detailed explanation).

Any input is welcome, thanks!

**Comment by ixrock** [comment]
@javivelasco  I've created PR #599  related to the topic, please have a look.

@JeroenNelen First what comes to my mind, you can use `className` to the button and assign any styles you want, e.g.
```
// buttons.scss
[class^="theme-button"].big {
  height: 100px;
}

// some-page.tsx
<Button label="Hello there" className="big" raised/>
```

**Comment by JeroenNelen** [comment]
@ixrock that doesn't seem to be sufficient, as I explain in the other topic, this can be used to set styles that are not yet set by the react-toolbox css, not for over-writing them, as .theme__raised___1CNoR will over-rule the styling I set in my own .css files.
Or am I misunderstanding your explanation?

**Comment by ixrock** [comment]
@JeroenNelen Yeah, that's true. In some cases it's not possible to overwrite styles.
To override styles from the theme you need specify more detailed selector which override the existing.
For example try to use this:

```
// mixins.scss
@mixin themed($selector) {
  [class^="theme-"]:not([disabled])#{$selector} {
    &[class*="-flat"],
    &[class*="-raised"] {
      @content;
    }
  }
}

// my-component.scss
@include themed(".big-btn") {
  height: 100px;
  background: red;
  color: black;
}
```

**Comment by JeroenNelen** [comment]
@ixrock are you in that case working with CSS modules for your own styling as well?
I have some form of the overwrite working by using the "naked" components and than in my own  CSS module I import the base styling: 
`@import '~react-toolbox/components/button/theme';
.raised {
    height: 100px;
}`

And then in my TSX I include the naked component together with my scss module:
`let buttonStyles = require('../common/buttonStyle');
import { Button } from 'react-toolbox/lib/button/Button.js'`

and then I define the component as follows:
`<Button
    label="test"
    raised
    primary
    theme={secondButtonStyles}
/>`

Issues here are:
- a lot of work for a small style change like changing the height
- if I want to have two buttons with different heights, I would have to repeat this proces but this will make the resulting .css file very big as the original styles exist multiple times (for every time I make an adjusted theme for a component)

Have you tested your suggestion? Because as far as I am aware it will not work as it will just not overwrite the already existing original styling, at it will have a different hash at the end of the class? 
And in your example, you're not working with css modules for the custom css but with normal css and using className = ? How do you make sure your custom css is loader after the default react-toolbox css modules? as the order will depict which selector wins?

Kind regards and thanks for your info!

**Comment by ixrock** [comment]
@JeroenNelen I don't use css modules for my project `.scss` files.
Yes, I tested my solution above for the button.

> How do you make sure your custom css is loader after the default react-toolbox css modules? as the order will depict which selector wins?

```
// main.scss
@import "~react-toolbox/lib/commons";
@import '~gridlex/src/gridlex';
@import "./utils";
```

All styles from your components will be defined below since you render the app below :
```
// main.tsx
import 'main.scss';
// other imports
render(<App/>, document.getElementById('app'));
```

**Comment by ixrock** [comment]
@JeroenNelen here is updated version for mixin cause it provides better support for code completion in IDE:

```
// mixins.scss
@mixin themed() {
  &[class^="theme-"]:not([disabled]) {
    &[class*="-flat"],
    &[class*="-raised"] {
      @content;
    }
  }
}

// my-component.scss
.big-btn {
  @include themed {
    height: 100px;
    background: red;
    color: black;
  }
}
```

**Comment by JeroenNelen** [comment]
Thanks for the swift replies @ixrock, really appreciate it!
I'm currently not at home but I'll test your suggestion when I get home (this evening or tomorrow). 
How have you configured your webpack? I had the module and hash loading done for only the node_modules/react-toolbox and another loader for my project specific css and sass. In what order have you placed your loaders?

Kind regards,

**Comment by ixrock** [comment]
@JeroenNelen I guess the order of loaders doesn't matter cause they are mutually exclusive.
I have this in my `webpack.config.js`:
```
{
  test: /\.scss$/,
  exclude: /react-toolbox/,
  loader: ExtractTextPlugin.extract('style', [
    'css?sourceMap',
    'postcss?sourceMap',
    'sass?sourceMap'
  ].join('!'))
},
{
  test: /\.scss$/,
  include: /react-toolbox/,
  loader: ExtractTextPlugin.extract('style', [
    'css?sourceMap&modules&importLoaders=1&localIdentName=[name]-[local]-[hash:base64:5]',
    'postcss?sourceMap',
    'sass?sourceMap'
  ].join('!'))
}
```

**Comment by JeroenNelen** [comment]
Hm, I still seem to be missing something.
If you use the extratextplugin, I suppose you set the style in your index.html?  
I use the extracttextplugin to generate 1 css bundle and it is imported in the index.html: 
`<html>
  <head>
    <title>Poort parkeren</title>
    <link rel="stylesheet" type="text/css" href="/assets/app.css" />
  </head>`

I use the Button with the styling included: 
`import { Button } from 'react-toolbox/lib/button';`

Then I have a own .scss file where I define a btn-big class in login.scss:
`.btn-big {
    height: 100px;
}`

In the component I then import the style:
`import '../login';`

And attach the class to the Button via className property:
`<Button
      label="test"
      raised
      primary
      className="btn-big"
/>`

But the styling is not applied and as I inspect the element it shows the default height being set in:
`.theme-raised-1CNoR`

And I also see my own selecter: `btn-big` in which the height is striked through, as both are selectors without nesting etc (as far as I can see), this would mean that the last one wins... so I get the idea the order is off? 

Thanks again for your reply, do you happen to have an example somewhere? It seems I'm still missing something...

Kind regards,

**Comment by ixrock** [comment]
@JeroenNelen you didn't use my mixin from above in your example. In that case of course `.btn-big { height: 100px; }` has lower priority. 
Or have you tried actually like this:
```
.big-btn {
  @include themed {
    height: 100px;
  }
}
```

**Comment by JeroenNelen** [comment]
@ixrock, I totally forgot to include your mixin, the selector is idd more specific now! I suppose this is the best way to overwrite the components without impacting anything else. Only issue might arise if they decide to change the react-toolbox classnames, I could add a class to the wrapping container for a nested btn-big selector and to prevent being influenced by classname changes but that's not very maintainable either I think... what do you think?
Thank you again for the expanation and suggestion!

**Comment by ixrock** [comment]
If react-toolbox class names will be changed at some point you can easily correct the mixin in one place and all the things become available again, IMO.

**Comment by javivelasco** [comment]
I have no clue about how TS works. May go check the PR and give a "seal of approval"? If I merge directly I'd have no idea what I'm doing... Use reactions in this same comment please!!

![1-sntxfelfuqlsfdnvzkj6ia](https://cloud.githubusercontent.com/assets/1634922/16533313/1afba030-3fd8-11e6-8061-de3201c9987d.png)

**Comment by JeroenNelen** [comment]
@javivelasco I've left a comment on the PRQ.
Furthermore, all the d.ts files just define the signatures of the functions and the types of the parameters (for auto completion and warnings/errors etc when using them in Typescript, but I suppose you already know that).

Kind regards,

**Comment by javivelasco** [comment]
Yep, I but don't know how to test it or whatever it gets to make sure it would work and to be backwards compatible as you said. I'm going to merge the PR, it should come with the next patch :)

**Comment by JeroenNelen** [comment]
@ixrock how are you currently getting the items from the library? As I'm getting quite some errors since the update, I'm trying to do:
import {Button} from 'react-toolbox';
It seem to throw errors for all lines in the index.d.ts:
Cannot find module 'react-toolbox/lib/list'. (for all components).

Kind regards,

**Comment by ixrock** [comment]
@JeroenNelen I don't know what happened after PR was merged, but now there is no component files `*.d.ts` in `lib/some_component/component.d.ts`
I don't use react-toolbox for my project, so didn't notice it before..

**Comment by javivelasco** [comment]
Maybe it was erased at build time? Is it actually included in the build workflow?

**Comment by JeroenNelen** [comment]
@javivelasco was there, initially, a specific reason you know of to include the d.ts files here in the repo instead of pushing them to the typings repo (https://github.com/DefinitelyTyped/DefinitelyTyped)? It might be more interesting to move them there? I got the idea that most big libraries work that way. (react, react-redux,...).

If I, somehow, find some spare time this week I can try and look at the current issue (but I have a busy schedule for work as well so I can't promise anything).

**Comment by ixrock** [comment]
@JeroenNelen I guess the only reason when you put the definitions inside extra repo like `dt` it needs more time to maintain declarations and keep it in sync with your code. To end user of this lib it gives better user experience of course.
@javivelasco have a look at typescript, it's cool stuff! You can start using it even on existing project.

**Comment by javivelasco** [comment]
@ixrock I have to take a look at it but sadly I don't have too much do so :( Meanwhile I need you guys to find out the best way to integrate with Typescript and trust your criteria :)

**Comment by normano64** [comment]
Hi. I started working on a up to date typings file, it's a round 1000 lines right now.
I hope to finish it tomorrow, but may take a bit longer. Will make a pull request then.

I hope it's okay with you @ixrock, felt it would take longer to edit the current one as I would have to check if everything was there so I started from scratch. The index.d.ts is now more like something from dt than separate modules for every part.

**Comment by javivelasco** [comment]
If you're all agree I'll merge with no trouble!

**Comment by JeroenNelen** [comment]
@javivelasco currently the typings are quite broken so it's great that @normano64 already took the time to write new ones, thanks!

**Comment by normano64** [comment]
@JeroenNelen: About putting them in `dt` seems to me like a good idea. I'm having problems when I don't import the components directly but instead from "react-toolbox". It gives me an error (`TS2656`) when the file is in the `node_modules/react-toolbox` directory, but not when in `typings/globals/react-toolbox`. Been trying to find an answer to why without success.

**Comment by JeroenNelen** [comment]
@normano64 hmm, your webpack or other task runner/bundler is picking up the .ts files from the react-toolbox when placing the typings there?

**Comment by normano64** [comment]
I made a pull request (#650). I still not done with all the comments and will continue another day.

**Comment by javivelasco** [comment]
Let me know when it's ready!

**Comment by normano64** [comment]
I think it's ready now @javivelasco.
Maybe you can test it @JeroenNelen and see if it works correctly? :)

**Comment by ojosdegris** [comment]
@normano64 do you have example of webpack.config.js for react-toolbox + typescript setup?

**Comment by normano64** [comment]
@ojosdegris: Here you go, but you will probably have to change the webpack-dev-server part.
```javascript
const path = require("path");
const webpack = require("webpack");
const autoprefixer = require("autoprefixer");
const ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
    entry: [
        path.join(__dirname, "src", "App")
    ],
    output: {
        path: path.join(__dirname, "build"),
        filename: "build.js",
        publicPath: "/"
    },
    resolve: {
        extensions: ["", ".css", ".scss", ".js", ".jsx", ".ts", ".tsx", ".json"],
        modulesDirectories: [
            path.join(__dirname, "node_modules"),
            path.join(__dirname, "src")
        ]
    },
    module: {
        loaders: [
            {
                test: /(\.tsx?)$/,
                loaders: ["ts"],
                exclude: /(node_modules)/
            }, {
                test: /(\.scss|\.css)$/,
                loader: ExtractTextPlugin.extract("style", [
                    "css?sourceMap&modules&importLoaders=1&localIdentName=[name]_[local]_[hash:base64:5]",
                    "postcss",
                    "sass"
                ])
            }
        ]
    },
    postcss: [
        autoprefixer({ browsers: ["last 2 versions"] })
    ],
    sassLoader: {
        data: "@import '" + path.join(__dirname, "src", "styles", "config") + "';",
        includePaths: [
            path.join(__dirname, "node_modules")
        ]
    },
    plugins: [
        new ExtractTextPlugin("bundle.css", {
            allChunks: true
        })
    ],
    stats: {
        children: false
    }
};

if (process.env.NODE_ENV === "production") {
    module.exports.plugins.push(
        new webpack.DefinePlugin({
            "process.env": {
                NODE_ENV: JSON.stringify("production")
            }
        }),
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false,
                drop_console: true
            }
        }),
        new webpack.optimize.OccurenceOrderPlugin()
    );
} else {
    module.exports.entry.push(
        "webpack-dev-server/client?http://localhost:3000"
    );
    module.exports.plugins.push(
        new webpack.DefinePlugin({
            "process.env": {
                NODE_ENV: JSON.stringify("development")
            }
        }),
        new webpack.HotModuleReplacementPlugin()
    );
    module.exports.devtool = "#source-map"
}
```

**Comment by ojosdegris** [comment]
@normano64 thank you!

**Comment by javivelasco** [comment]
Closing since apparently it's solved!
