### ISSUE TITLE
Dialog - Invariant violation

### ISSUE THREAD

**Issue by mistre83** [react-toolbox/react-toolbox#600]
I have created a simple class like this:

```
class DisplaySystem extends Component {
    constructor(props) {
        super(props);
        this.state = {
            dialogActive: false
        };
        this.handleToggleDialog = this.handleToggleDialog.bind(this);
    }

    handleToggleDialog() {
        this.setState({dialogActive: !this.state.dialogActive});
    }

    render() {
        const actions = [
            { label: "Cancel", onClick: this.handleToggleDialog},
            { label: "Save", onClick: this.handleToggleDialog}
        ];

        return (
            <span>
                <Dialog
                    actions={actions}
                    active={this.state.dialogActive}
                    onEscKeyDown={this.handleToggleDialog}
                    onOverlayClock={this.handleToggleDialog}
                    title="Change System">
                    <p>Dummy content</p>
                </Dialog>
            </span>
        );
    }
}

const mapStateToProps = state => ({
    userLoggedIn: userIsLoggedIn(state),
    customerName: getSelectedCustomerName(state)
});

export default connect(mapStateToProps)(DisplaySystem);
```

But Chrome console say:

> Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `DisplaySystem`.
> 
> Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `DisplaySystem`.

I have checked this component removing Dialog and it works. I have miss something... ?

**Comment by mistre83** [comment]
Got the same error with <ProgressBar />

**Comment by mistre83** [comment]
Problem solved. I was using react-toolbox version 0.16.2.

Updated to 1.0.1 and now all works.

**Comment by banomaster** [comment]
I think the issue is back in version 1.2.x. Thank you for the update.
