### ISSUE TITLE
Menu not responding to theme

### ISSUE THREAD

**Issue by michaelsharpe** [react-toolbox/react-toolbox#603]
I am currently trying to style the menu utilizing themr to override the default stylings.  All of my other styles have taken fine, but the RTMenu styles are not taking.  

I think it may be because there is no constant defined for MENU in identifiers.js that is passed to the default themr export (default themr(MENU)(Menu)).

**Comment by javivelasco** [comment]
This is already fixed by https://github.com/react-toolbox/react-toolbox/pull/602 !!
Sorry for the late fix, I'm releasing a patch today
