### ISSUE TITLE
react-toolbox and Metor

### ISSUE THREAD

**Issue by sun2rise** [react-toolbox/react-toolbox#604]
Hi!
i am trying to make a new project with meteor but i cannot make sass work: what should i install? how should i configure it?

**Comment by abigtoe** [comment]
See: https://github.com/nathantreid/meteor-react-toolbox-example

**Comment by javivelasco** [comment]
Remember that using sass is now *optional*. Of course you'd need to compile the styles yourself into plain CSS and provide a module with mappings using `ThemeProvider` but still, you can avoid it.

I have no experience with meteor, hopefully the link would help you. I'm gonna close :)

**Comment by Captain-GaDo** [comment]
The link https://github.com/nathantreid/meteor-react-toolbox-example don't work with Meteor 1.3.4.1- How i can install this excellent resource in Meteor?

**Comment by javivelasco** [comment]
Not sure, I have no idea how Meteor works.. but if you have the theming concepts clear enough you should be able to configure it with just any project

**Comment by Captain-GaDo** [comment]
No. I tried but with no success.

Sadly

**Comment by javivelasco** [comment]
What's the issue?

**Comment by cranesandcaff** [comment]
After following the instructions from the example @hmontes posted, you need to modify the instructed `package.json` additions.

Here is how to make react-toolbox play nice with Meteor.

`meteor npm install --save-dev node-sass@3.4.2`
`meteor add nathantreid:css-modules@2.0.2`

Add this to your `package.json`:
 
	"cssModules": {
		"extensions": ["scss", "css"],
		"enableSassCompilation": ["scss"],
	 "globalVariables": [
	    "node_modules/react-toolbox/lib/_colors.scss",
		    {
		      "theme-building": true
		    },
		    "client/toolbox-theme.scss"
		  ]
		}

You need to include both `scss` and `css` in your extensions option.
