### ISSUE TITLE
Unknown prop `composeTheme` on <button> tag

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [react-toolbox/react-toolbox#606]
In development, `IconButton` is throwing this warning.  I believe `composeTheme` is being inculded [when props are spread](https://github.com/react-toolbox/react-toolbox/blob/dev/components/button/IconButton.js#L57).

**Comment by javivelasco** [comment]
Yes, this is happening because themr is passing down that prop but I think it´s not needed. I've opened an issue to fix it in react-css-themr.

**Comment by kodermax** [comment]
when will be fixed?

**Comment by javivelasco** [comment]
Sorry, already fixed!
