### ISSUE TITLE
Tabs component is not responsive

### ISSUE THREAD

**Issue by nastiatikk** [react-toolbox/react-toolbox#608]
Hi guys!

Our team started to use react-toolbox and we find it a fantastic alternative to other Material-UI based react libraries, thank you!

I am currently working on implementing tab component and found that it's not responsive on smaller viewports:
![image](https://cloud.githubusercontent.com/assets/4110509/16536010/a72f0a2e-3fba-11e6-89f0-3fe125306c6d.png)

As you can see on the provided screenshot - if tabs' labels are a little wider it cuts underline line and adds scroll to the page.

Let me know if I can help solving this using CSS (adding a horizontal scroll for example)

**Comment by nastiatikk** [comment]
The other problem that I noticed with tab component on the smaller viewports - if user is on the tab that doesn't fit the viewport and located somewhere on the right, user doesn't see what is the current tab until the page is scrolled.

**Comment by javivelasco** [comment]
Hi @nastiatikk !! Truth is I've never tried out hardly on smaller viewports every single component. I was planning to review each one and make the needed corrections to make them responsive but I don't have too much time to do so and I gave priority to stuff like theming.

Contributions on this side are really appreciated, I'm gonna label as an enhancement and try it out :)
Thanks for reporting!

**Comment by cdroulers** [comment]
@javivelasco I think it'd be decently easy with a bit of CSS (I already got it to wrap with `flex-wrap: wrap`. I wanted to modify the code to put the blue bar under each tab label, but I can't get the project to compile / run. I'm on the master branch, clean checkout. Ran `npm install && npm run build && npm run test` and get the following output.

```
ERROR in ./~/css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./~/sass-loader!./components/ripple/style.scss
Module build failed:
  @import "./colors";
 ^
      Import directives may not be used within control directives or mixins.
      in C:\dev\external\react-toolbox\components\_base.scss (line 4, column 3)
 @ ./components/ripple/style.scss 4:14-240
07 07 2016 12:31:48.801:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
07 07 2016 12:31:48.809:INFO [launcher]: Starting browser PhantomJS
07 07 2016 12:31:50.603:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket /#sgG12Gj7Jns7ziMvAAAA with id 2867635
PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  Error: Cannot find module "!!./../../node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:C:/dev/external/react-toolbox64:5]!./../../node_modules/postcss-loader/index.js!./../../node_modules/sass-loader/index.js!./style.scss"
  at C:/dev/external/react-toolbox/tests.webpack.js:4152
PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 0 of 0 ERROR (0.115 secs / 0 secs)
```

I think it's related to node-sass maybe? Any ideas? I'd love to contribute!

**Comment by javivelasco** [comment]
Wow, master is totally outdated!!! :| Gonna update it and it should work

**Comment by MorrisGallego** [comment]
Hi. Any update on this?

**Comment by therealparmesh** [comment]
I think this may help alleviate your issues.

https://github.com/react-toolbox/react-toolbox/pull/975

**Comment by MorrisGallego** [comment]
Thanks a lot, @therealparmesh! Do you know if there is a published version with your changes?

**Comment by therealparmesh** [comment]
There's no published version with those changes currently.

However, I'm optimistic that it will be merged in soon.

**Comment by javivelasco** [comment]
I'm publishing today :)

**Comment by MorrisGallego** [comment]
Sorry for my insistence... Any plan on including this in the css-next branch? I just ported my project today to that version...

**Comment by javivelasco** [comment]
I have to merge the main branch. It's going to happen during this week

**Comment by vikramjit575** [comment]
you can try this
 {
                 test: /(\.css|\.scss)$/,
                loader: 'style-loader!css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!sass-loader?sourceMap'
            }

**Comment by lantanios** [comment]
any solution so far?
