### ISSUE TITLE
Difference between lib and components?

### ISSUE THREAD

**Issue by kossel** [react-toolbox/react-toolbox#610]
Hi
What is the difference of lib and components? 
Is there any difference these 2 imports? (beside named vs no named import, es6 vs transpiled)
`import {Button} from 'react-toolbox';`
and
`'import Button from 'react-toolbox/lib/Button';`

Which should I use?

**Comment by wtgtybhertgeghgtwtg** [comment]
`import {Button} from 'react-toolbox';` and `import Button from 'react-toolbox/lib/button';` will give you the same component.  [The button `react-toolbox` imports is imported from `react-toolbox/lib/button`.](https://github.com/react-toolbox/react-toolbox/blob/dev/lib/index.js#L10-L18)  `react-toolbox` will also import every other component, whether or not you use them.
It's a little verbose, but using `react-toolbox/lib/button` will save you some space on the final bundle.

**Comment by javivelasco** [comment]
Yes, thanks for answering @wtgtybhertgeghgtwtg 
You should always import from lib, otherwise every component will be included in the final bundled as he said :)
