### ISSUE TITLE
In <IconMenu /> can not theme the <FontIcon />

### ISSUE THREAD

**Issue by kossel** [react-toolbox/react-toolbox#611]
Hi

When using` <IconMenu> `component, is there anyway to customize the `<FontIcon>`? (for example change the icon size and color)

The issue is in `<IconButton >` it's passing the theme object to `<FontIcon>` [https://github.com/react-toolbox/react-toolbox/blob/dev/components/button/IconButton.js#L68](url),  but when you are using `<IconMenu>` component the `theme` props is always empty. 

My temporal workaround is o pass the `theme` through props from `IconMenu` to `IconButton`(from the source code), is there a better way to do this?

```
<IconMenu>   
<IconButton > 
 <FontIcon/>
</ IconButton > 
</IconMenu>  
```

**Comment by rrgarciach** [comment]
+1

**Comment by javivelasco** [comment]
Yeah, this is because the `FontIcon` component has no styles, so it's not implementing a theme. It is just an `span` element:

```jsx
const FontIcon = ({ children, className, value, ...other}) => (
  <span
    data-react-toolbox='font-icon'
    className={classnames({'material-icons': typeof value === 'string' || typeof children === 'string'}, className)}
    {...other}
  >
    {value}
    {children}
  </span>
);
```

To customize it you can just give a `className` and refer to that `className` prop from your theme property in the container component.

**Comment by kossel** [comment]
Sorry, maybe I'm not good explaining  or I'm not clear with your solution, what I want to achieve is to change the Icon size of `<IconMenu/>` component.

In menuIcon.js:
```
...
<div className={classnames(this.props.theme.iconMenu, this.props.className)}>
          <IconButton
            className={this.props.theme.icon}
            icon={this.props.icon}
            onClick={this.handleButtonClick}
            ripple={this.props.iconRipple}
          />
...
```
theme.iconMenu = style for the menu
theme.icon = style for the IconButton (contains the <font-icon />

However, in lib/button/_config.scss there is a default button font size for the span element:
`$button-toggle-font-size: $unit * 2 !default;`
```
.toggle {
  @extend %button;
  width: $button-height;
  background: transparent;
  border-radius: 50%;
  > .icon, svg {
    font-size: $button-toggle-font-size;
    line-height: $button-height;
    vertical-align: middle;
  }
  > .rippleWrapper {
    border-radius: 50%;
  }
}
```

therefore even I put a different font-size using  `theme.icon` it will get overwritted. I obviouslly can not nested style like the .toggle because they have same name
```
.icon{
      color: #ffffff !important;
    .icon {
      font-size: 3rem !important;
    }
}
```

![image](https://cloud.githubusercontent.com/assets/1760498/16718204/7f044c28-46e3-11e6-8371-e637aa64b76a.png)

**Comment by kossel** [comment]
I just come up with
```
.icon{
  color: #ffffff !important;
    span {
      font-size: 3rem !important;
    }
}
```
and it worked 😃  not sure if it's the best way...
however I found that I have alway to put  `!important;` in order to be able to overwrite styles of the components

**Comment by javivelasco** [comment]
@kossel ! Pass to the `IconButton`a custom `theme` object. You can create it in CSS using the API given in the docs. For example you can create your css:

```scss
.toggle {
  > .icon, svg {
    font-size: 3rem;
    color: #fff;
  }
}
```

Then require that theme object and pass it to `IconButton`. It will *add your custom* `toggle` class along with the default. Since your are writing selectors with the same priority as the defaults it's going to be overriden if your styles are included *after* the default in the final bundle. If you want to still boost priority pass a `className` as well and use it concatenated with your `.toggle`. That will work without using that ugly `!important`.

Let me know if it works!

**Comment by jasan-s** [comment]
I still can't get the icons to change color always remain black.  is there a working example? or can it be added to the react-toolxox-example

**Comment by javivelasco** [comment]
Hi @jasan-s! Soon there will be a way to provide live examples. Make sure you review the theming section with detail, all you need is there. What you need to add to do with the later example is to import that module in an object and pass it as a theme property to the IconButton
