### ISSUE TITLE
serviceworker

### ISSUE THREAD

**Issue by joeblew99** [react-toolbox/react-toolbox#612]
I was wondering if anyone can point me to some code to allow service worker.
I want to be able to bundle my app, so that part of it load only when needed, and that the routing is encapsulated.

Angular2 and polymer have this, but i am looking for the React way.

thank in advacne

**Comment by javivelasco** [comment]
Is this directly related to react-toolbox? I have no experience with service workers and I don't know if the project has anything to do with this...

**Comment by wtgtybhertgeghgtwtg** [comment]
No, this is not directly `react-toolbox` related.
