### ISSUE TITLE
redux and button

### ISSUE THREAD

**Issue by kodermax** [react-toolbox/react-toolbox#614]
I have an error, when i use button and redux
```
  handleCancel = (e) => {
    e.preventDefault();
    this.context.store.dispatch(push('/'));
  };
```
![image](https://cloud.githubusercontent.com/assets/590985/16632895/2becbb72-43cf-11e6-802d-7a96931409db.png)

**Comment by javivelasco** [comment]
Can you provide more info to identify if it's a RT related issue? Maybe you can solve it from your side?

**Comment by javivelasco** [comment]
Closing to reduce noise meanwhile. I suspect it's not a RT issue :/
