### ISSUE TITLE
AppBar examples.

### ISSUE THREAD

**Issue by Stalso** [react-toolbox/react-toolbox#615]
Hello. Can you provide some more detailed information about AppBar? I do not understand how can I place elements there and make it responsive. How can I make something like [this](https://canopy.co/) . Or how can I make beautifull links like [here](http://www.google.com/inbox/) or something like [this](http://materialwp.com/), or [this](https://design.google.com/events/) cool tab links in app bar with hover? And by the way, if I add navigation with links in AppBar, they are dark, not white.

**Comment by javivelasco** [comment]
I've never composed a complex example with the `AppBar`... If somebody created something complex please share!

**Comment by vmsoftware** [comment]
12-columns based grid system proposed here #596 would be useful to make mor complex layout's
