### ISSUE TITLE
localisation / i18n support

### ISSUE THREAD

**Issue by joeblew99** [react-toolbox/react-toolbox#623]
These components are very high quality and very reusable, but i frankly need the ability to do i18n on them to use this in real world projects.  
So, i am asking for some support on this.

Generally you need to project a way to do:
- text translation
- datetime, currency and number formatting
- RTL and LTR layout even

Its a difficult task and big, but others have done it for React.
SO far i have found this, and it looks well supported.
https://github.com/yahoo/react-intl
- tackles the hard aspects
- lots of committers
- looks good to me so far
- considers the workflow. This is very important
- backed by format.js (http://formatjs.io/integrations/)

But how to integrate it with react toolbox in a sustainable way is really important.
There seems to be utter confusion about how best do this. Use Props, Context or Mixins.

I would very much appreciate feedback on this.

Also i am curious if others feel this is an important thing to them ? 

There has been a hack done in the past. Its does not really do datetime formatting 
https://github.com/react-toolbox/react-toolbox/issues/229

**Comment by javivelasco** [comment]
I think there are components like the `DatePicker` where localisation should be definitively taken into account. #680 does a great work and it's being published today with a new release. I think the best we can do to avoid messing up too much with this is to move any hardcoded message to a property. For example, dialogs for pickers should have the message coming from properties. We should identify all components where this happens and extract messages to props.

For other components like the DatePicker it's more complicated but it's done anyway.

**Comment by javivelasco** [comment]
I think this can be closed. Every component should be flexible enough to allow to pass custom translated text and the most problematic (which was `DatePicker`) is already localised. If you find a component that cannot be changed please open a new issue with the details about the specific case.
