### ISSUE TITLE
Tooltip decorator not passing theme to composed component

### ISSUE THREAD

**Issue by emdfonseca** [react-toolbox/react-toolbox#627]
Hi guys. Great work you've been doing with this project! Thanks!

While using the tooltip decorator I found out that the css module theme is not being applied to the composed component. While analysing the issue I've looked into [components/tooltip/Tooltip.js:55](https://github.com/react-toolbox/react-toolbox/blob/672429f806287f9aa1423f631890487a0257ccee/components/tooltip/Tooltip.js#L55) source and noticed that the theme prop is being extracted from the props that are passed to ComposedComponent. 

Is there any reason why theme prop is being extracted or can we simply leave theme attribute as part of the props being passed into the composed component?

**Comment by javivelasco** [comment]
Hi! Not actually, it's an issue. Fixing it right now

**Comment by javivelasco** [comment]
We were not passing the theme down in case you use the Tooltip for JSX that does not accept that prop and throws warnings from the latest React version. It should be passed down and in case you want to avoid it you should delete it.
