### ISSUE TITLE
Website components not synchronized with current NPM version

### ISSUE THREAD

**Issue by janesconference** [react-toolbox/react-toolbox#63]
hi, I see that the latest components added (ie Tooltip) are still not available on the [main site](http://react-toolbox.com/#/)?

**Comment by soyjavi** [comment]
Tooltip will be available in the next release ;)

**Comment by janesconference** [comment]
mmmh so, I'm a bit confused :)
react-toolbox on npm seems to be @ v0.11.3, while here on Github the only tag I see is 0.10.20. What is the main site referring to?

**Comment by javivelasco** [comment]
Yes, sorry about that. The thing is we just released a first approach to be able to show the site while presenting it @ Reactive 2015 but we are not into semantic versioning either tagging releases in Github. We have an open PR to use a command line tool to make versioning easy and stop messing up everything.

I didn't expected the project to get that popular so we need discipline with versioning and releasing. This weekend I'll have time to get everything straight. Sorry about that!

**Comment by janesconference** [comment]
No problem! Just wanted to raise the issue for you to be able to pick it up when you could :)
Thank you for your answer!

**Comment by soyjavi** [comment]
So sorry @janesconference we will fix that ASAP.

**Comment by javivelasco** [comment]
It should be everything ok now!
