### ISSUE TITLE
RadioGroup renders only RadioButton ignoring any other possible child

### ISSUE THREAD

**Issue by dlebedynskyi** [react-toolbox/react-toolbox#630]
this one almost got my hair grey. 
if you create any custom 'radio' component such as, for example, Radio Button with input and pass it to  RadioGroup, your custom component will be ignored completely an instead RadioButton will be rendered with your props mapped (sic!). 

this is due to this  line
https://github.com/react-toolbox/react-toolbox/blob/dev/components/radio/RadioGroup.js#L27

Expected behavior is that you actually render components passed to RadioGroup as children

On a side note, you might want to try to avoid things like 
```javascript 
handleChange = (value) => {
      if (this.props.onChange) this.props.onChange(value);
    };
...
render () {
...
onChange={this.handleChange.bind(this, radio.props.value)}/>
...
}
```
 cause it creates a new function each time component is rendered. 
Optionally you can use stuff like [recompose](https://github.com/acdlite/recompose) withHandlers

**Comment by javivelasco** [comment]
The bind thing is for a next iteration and reflected in another issue!

**Comment by alexhisen** [comment]
The fix for this issue broke the ability to use raw/unthemed RadioButton components as children and have the radio group automatically manage their onChange, checked and disabled props.

**Comment by dlebedynskyi** [comment]
@alexhisen  can you give an example of this?

**Comment by alexhisen** [comment]
For how to use a raw RadioButton component? You import RadioButton.js directly.
 !isComponentOfType(RadioButton, child) is what fails btw, because in that component RadioButton is  expected to actually be the themr-wrapped RadioButton as opposed to the one from RadioButton.js
