### ISSUE TITLE
How do I override button font size

### ISSUE THREAD

**Issue by shineli1984** [react-toolbox/react-toolbox#634]
I was trying to change the overall sizes by changing $unit, but I noticed that raised button has fixed `font-size: 1.4rem` which is hardcoded in typo-button mixin in the global mixin.scss

Is there a way to override this?

**Comment by kossel** [comment]
you may want to create a scss selector which match the element
```
<Button className={styles.parent} />
```

```
.parent{
    button {
      font-size: $larger-font;  //or whatever the new size
  }
}
```

**Comment by javivelasco** [comment]
PR is merged and it makes sense!
