### ISSUE TITLE
Should NavBar provide callback for when it goes permanent?

### ISSUE THREAD

**Issue by InfernoZeus** [react-toolbox/react-toolbox#639]
I'd like the ability to remove the burger from my AppBar when the NavBar goes permanent due to the window size. Looking at the way [baloob/react-sidebar achieves this](https://github.com/balloob/react-sidebar/blob/1db3960ce8a9c9975a0197c630152e3f529f18ed/example/src/responsive_example.js#L23), I think it should be possible for us to achieve in a similar manner. If I were to provide a PR for this, would it be appreciated?

**Comment by javivelasco** [comment]
Of course! We can just add a prop to the `Layout` to achieve this. Feel free to do it

**Comment by InfernoZeus** [comment]
Ok, I'll try and find time to make a PR.

**Comment by javivelasco** [comment]
I think this makes more sense if anybody implements it outside the component. Take into account that to achieve this we need to add a resize listener that most people may not need. Also the current implementation is flexible enough to tell from outside when it should go permanent so it means it can be controlled easily. If more people think this is needed, please reopen
