### ISSUE TITLE
Where do this warning coming from?

### ISSUE THREAD

**Issue by kossel** [react-toolbox/react-toolbox#640]
When I type something in the input demo (type='email')
I can see this warning, is this from react toolbox, react or chrome?
is there a way to catch this warning so I can display a more friendly version?

![image](https://cloud.githubusercontent.com/assets/1760498/16817753/ec6f8912-4909-11e6-95f1-a36ebe54803b.png)

**Comment by stevebest** [comment]
It comes from Chrome when React tries to set the value of `<input type="email">` to a non-email.

Test case: http://jsbin.com/nokenadesu/1/edit?html,js,output

Open console and click the button to see the same warning message.

**Comment by shukerullah** [comment]
what is solution for this?
