### ISSUE TITLE
Can't apply style on RadioButtons

### ISSUE THREAD

**Issue by fabiozaffani** [react-toolbox/react-toolbox#642]
Using the same configuration that work for input and checkbox fields, it won't work on radiobuttons or radiogroups.

Obs.: This issue is hapening when trying to set it through the "theme" property

**Comment by javivelasco** [comment]
Can you be more specific or provide some code to reproduce the issue? Make sure that you're using the latest version or try directly from the `dev` branch. I can't see anything wrong right now
