### ISSUE TITLE
Buttons with hrefs render offset with text at top

### ISSUE THREAD

**Issue by fastfedora** [react-toolbox/react-toolbox#643]
Buttons render incorrectly when an `href` is present, but no icon is present. 

In the [Button](http://react-toolbox.com/#/components/button) documentation, this renders fine:

```
    <Button href='http://github.com/javivelasco' target='_blank' raised accent>
      <GithubIcon /> Github
    </Button>
```

But this renders incorrectly:

```
    <Button href='http://github.com/javivelasco' target='_blank' raised accent>
       Github
    </Button>
```

Note that I added the `accent` attribute so the background of the button would be colored to better highlight the issue. The text is being rendered in the same location, but the button is offset so that the top of the button is aligned with the top of the text. It appears to be a conflict with the link styles that are wrapped around the button when an `href` is provided.

I confirmed the bug in the most recent versions of both Chrome and Firefox.

**Comment by javivelasco** [comment]
It's fixed in dev!
