### ISSUE TITLE
Autocomplete issue on shouldComponentUpdate

### ISSUE THREAD

**Issue by carlitux** [react-toolbox/react-toolbox#649]
I am trying to use Autocomplete but for some reason on shouldComponentUpdate not working well. The component is about two levels from root component. But if I set the direction different than 'auto'... it works as should be.

On this line https://github.com/react-toolbox/react-toolbox/blob/dev/components/autocomplete/Autocomplete.js#L70 I added a log:

```js
console.log(this.state.focus, nextState.focus, this.props.direction, POSITION.AUTO)
```

logs
```js
false true "auto" "auto"
```

and this line https://github.com/react-toolbox/react-toolbox/blob/dev/components/autocomplete/Autocomplete.js#L74 looks like doesn't fire the lifecycle **sometimes**, I did a quick test with this code and works (I don't feel is the best approach):

```js
 shouldComponentUpdate (nextProps, nextState) {
   if (!this.state.focus && nextState.focus && this.props.direction === POSITION.AUTO) {
    const direction = this.calculateDirection();
     if (this.state.direction !== direction) {
       // not calling setState
       this.state.direction = direction;
     }
   }
   return true;
 }
```

Reading https://facebook.github.io/react/docs/component-specs.html

docs from shouldComponentUpdate doesn't have a suggest if we can use setState or not...

**Comment by farwayer** [comment]
https://github.com/react-toolbox/react-toolbox/pull/646

**Comment by javivelasco** [comment]
Fixed
