### ISSUE TITLE
Arrow functions in server.js

### ISSUE THREAD

**Issue by NogsMPLS** [react-toolbox/react-toolbox#65]
When running ```npm run start``` the process errors out because of arrow functions in server.js:

![npm-run-start-arrow-functions](https://cloud.githubusercontent.com/assets/6899011/11001821/fcfa2d1a-846e-11e5-81dd-ce8c4d7d4c86.PNG)

Maybe it's not getting polyfilled correctly? Either way, changing to use the function keyword fixes this. Will have a PR soon.

**Comment by NogsMPLS** [comment]
PR fixes this specific error, but a new error pops up in events.js. I will open a separate issue for that.

**Comment by soyjavi** [comment]
what version of NodeJS are you using?

<img width="397" alt="screen shot 2015-11-07 at 3 35 40 pm" src="https://cloud.githubusercontent.com/assets/559654/11014361/5f892b92-8565-11e5-9f94-a6f545dc75ae.png">

**Comment by javivelasco** [comment]
Hi! We've tested the package using node 4.2.1 that already supports ES6 syntax. If you have other projects with a setup in a previous node version, I recommend you to use [n](https://github.com/tj/n) or [nvm](https://github.com/creationix/nvm).

We would like to keep ES6 syntax for now :)
