### ISSUE TITLE
Documentation w.r.t. Theming and Raw Components

### ISSUE THREAD

**Issue by landabaso** [react-toolbox/react-toolbox#654]
From the docs [here](http://react-toolbox.com/#/install), section theming:

> Then, when you use a button you can inject the appropriated theme:

```
import { Button } from 'react-toolbox/lib/button/Button';
import buttonTheme from './theme/button.scss';

const ThemedButton = (props) => (
  <Button theme={buttonTheme}  {...props} />
);

export default ThemedButton;
```

> With this technique you have to create wrappers for every component and this is not cool at all... but don't worry, we can provide the theme via context to avoid this.

Perhaps it should be:

`import Button from 'react-toolbox/lib/button/Button';`
(without the Brackets - {  } -)

Otherwise the themes passed through the context are not applied ([see the code here](https://github.com/react-toolbox/react-toolbox/blob/dev/components/button/Button.js)).
 
Is that correct?

**Comment by javivelasco** [comment]
Totally! Wanna PR?

**Comment by landabaso** [comment]
Should I close it or wait until [http://react-toolbox.com/#/install](http://react-toolbox.com/#/install) is compiled with the changes?

**Comment by javivelasco** [comment]
Better close, I'm releasing between today and tomorrow!
