### ISSUE TITLE
Using with redux-form

### ISSUE THREAD

**Issue by msenevir** [react-toolbox/react-toolbox#657]
How would you go about using an `<Input />` component with a package like `redux-form`?

`import Input from 'react-toolbox/lib/input`
`<form onSubmit={handleSubmit(this.props.onSubmit)}>`
`   <Field name="firstName" component={Input} type="text" placeholder="Frist Name"/> `
 `   <Field name="lastName" component="input" type="text" placeholder="Last Name"/> `
 `   <button type="submit">Submit</button>`
`</form>`

I get this error: `Unknown props 'active', 'asyncValidating', 'dirty', 'invalid', 'input', 'pristine', 'touched', 'valid', 'visited' on <input> tag. Remove these props from the element.`

When I try something like `<Input {...this.props.fields.firstName} />`, then no error is thrown, but `onSubmit` is no longer receiving the data.

**Comment by igorbarbashin** [comment]
redux-form 6.0.0-rc3 got it covered. You'll have to use `props.input` to pass to `Input`.
redux-form 5.x is not compatible with React 15.2

**Comment by msenevir** [comment]
Thanks! That tip, along with this [thread](https://github.com/erikras/redux-form/issues/1249), helped me solve the issue. Here's the code I used to get it working:

    const renderField = field => (
        <div>
            <Input {...field.input} />
        </div>
    );

    // the render method of MyComponent
    render() {
        const { fields: { firstName }, handleSubmit, onSubmit } = this.props;
        return (
            <form onSubmit={handleSubmit(onSubmit)}>
                <Field component={renderField} name="firstName} {...firstName} />
                <button type="submit">Submit</button>
            </form>
        );
    }

    export default reduxForm({
        form: 'theForm',
        fields: ['firstName']
    })(MyComponent);

**Comment by alexanderharm** [comment]
For me this does not work. I'm using `redux-form@6.0.0-rc4` and the latest version of `react-toolbox`. My input field just stays emtpy and there seems to be no `onChange` passed between `Form` and `Input`.

**Comment by javivelasco** [comment]
@alexanderharm Can you report an more detailed example of a gist to reproduce it? I have no experience with `redux-form` so I'd need guidance to focus on the fix

**Comment by alexanderharm** [comment]
Seems to be my fault. Didn't import from `redux-form/immutable`. Sorry to bother.

**Comment by javivelasco** [comment]
No problem!

**Comment by euanmillar** [comment]
Anyone experienced this?  When I am using toolbox v2.0.0-beta.12 with redux-form v6.8.0 the redux form's very first redux-form/CHANGE event causes the input to lose focus.  The next time you focus in the Input, the problem goes away?  Most strange but quite annoying to lose focus on the Input.

**Comment by euanmillar** [comment]
Found my problem.  I had my renderFunctions inside my render function.  Solution explained here in case anyone else has this problem:  [https://github.com/erikras/redux-form/issues/1094#issuecomment-229820291 ](url)
