### ISSUE TITLE
TimePicker theme not getting applied to children

### ISSUE THREAD

**Issue by conroywhitney** [react-toolbox/react-toolbox#660]
It seems like the `TimePicker` component is not correctly passing down its `theme` to its children.

It looks like the destructuring of `theme` in [line 62 of `TimePicker`](https://github.com/react-toolbox/react-toolbox/blob/dev/components/time_picker/TimePicker.js#L62) means it does not get splatted down in [line 67](https://github.com/react-toolbox/react-toolbox/blob/dev/components/time_picker/TimePicker.js#L67).

If you compare with `DatePicker`, it does *not* get destructured in [line 71](https://github.com/react-toolbox/react-toolbox/blob/dev/components/date_picker/DatePicker.js#L71) so it *does* get splatted in [line 79](https://github.com/react-toolbox/react-toolbox/blob/dev/components/date_picker/DatePicker.js#L79).

**Comment by conroywhitney** [comment]
Created PR #661 to address this issue. Thanks for all your work on this project!

**Comment by javivelasco** [comment]
Merged! Thanks @conroywhitney :)
