### ISSUE TITLE
Menu component should unsubscribe events on componentWillUnmount

### ISSUE THREAD

**Issue by azrahel** [react-toolbox/react-toolbox#672]
Hey, 

I use Menu component to handle navigation. Sign out is one of the navigational features. 
After clicking signOut I unmount Menu component from my TopAppHeader (the usual bar at the top of the app. Menu component is or is not there based on user permissions). 
I unmount it as it obviously shouldnt be there after logout. 
Even as Menu component is unmounted its function - handleDocumentClick tries to fire findDOMNode on it. 

I added componentWillUnmount with removing subscribed method and it works now: )

Lacking piece of code in Menu.js: 

 {
    key: 'componentWillUnmount',
    value: function componentWillUnmount() {
      _utils.events.removeEventsFromDocument({ click: this.handleDocumentClick });
    }
  },

**Comment by javivelasco** [comment]
I think this is fixed in the `dev` branch. Not sure about the latest release. Thanks!! :)

**Comment by azrahel** [comment]
np. Best mate!
