### ISSUE TITLE
Broken identifier import for TimePicker

### ISSUE THREAD

**Issue by Varnius** [react-toolbox/react-toolbox#678]
The content of identifiers.js:

```js
export const TIMEPICKER = 'RTTimePicker';
```

and here is what /timepicker/index.js and timepicker/TimePicker.js imports

```js
import { TIME_PICKER } from '../identifiers.js';
```

Missing underscore and broken import :)

**Comment by javivelasco** [comment]
🙉 Thanks!! 💃
