### ISSUE TITLE
Menu display issue inside CardTitle

### ISSUE THREAD

**Issue by ssb402** [react-toolbox/react-toolbox#683]
If I have a Menu inside a CardTitle, it only partly shows up (and the menu items get "hidden"). I tried changing the z-index for the divs inside the Menu from Firebug but it does not seem to affect the display at all.

Here's what I am trying to do:
```
<Card>
   <CardTitle>
     <IconMenu icon='more_vert' position='topLeft' menuRipple>
       <MenuItem value='download' icon='get_app' caption='Download' />
       <MenuItem value='help' icon='favorite' caption='Favorite' />
       <MenuItem value='settings' icon='open_in_browser' caption='Open in app' />
       <MenuDivider />
       <MenuItem value='signout' icon='delete' caption='Delete' disabled />
     </IconMenu>
   </CardTitle>
</Card>
```

and what it looks like
<img width="711" alt="screen shot 2016-08-02 at 1 39 44 pm" src="https://cloud.githubusercontent.com/assets/1744097/17344517/3d4a4ef0-58b7-11e6-840a-5b0677674188.png">

How do I make it so that the Menu shows "on top" of the CardTitle and not hide like that?

Thanks!

**Comment by vmsoftware** [comment]
You need check overflow property of card and cardtitle wrappers.  By default has hidden. Override with visible for you specific component.

**Comment by ssb402** [comment]
Oh! I didn't realize Card was overflow:hidden by default.

Thanks. I changed my card style to overflow:visible and it works now. Thank you @vmsoftware
