### ISSUE TITLE
[Multiline Input Field]: Inconsistency between the character counter and the browser-enforced limit

### ISSUE THREAD

**Issue by SimonSelg** [react-toolbox/react-toolbox#685]
### The problem

when using the input element with `maxLength` specified, the input field will display the entered amount of characters:

![image](https://cloud.githubusercontent.com/assets/9430680/17385907/0faa9b96-59e6-11e6-8327-25f41bbb094e.png)

The component uses simply the `length` function of the string to determine the amount of entered characters. The limit is enforced using the [`maxlength`](http://www.w3schools.com/tags/att_input_maxlength.asp) attribute of the input. 

However, the maxlength attribute counts newlines (in browsers that implement the specs correct, such as the current version of chrome) as **two characters** (`\r\n`). [Chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=252613), [SO discussion #1](https://stackoverflow.com/questions/10030921/chrome-counts-characters-wrong-in-textarea-with-maxlength-attribute), [SO discussion #2](https://stackoverflow.com/questions/22016511/different-maxlength-validation-of-textarea-with-newlines-in-chrome-and-firefox).

To check that out yourself, enter a bunch of newlines [here](https://jsfiddle.net/bxFbL/). For explanations why that's the case, check the [this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=252613#c6) in the chrome issue or the [html specs](https://html.spec.whatwg.org/multipage/forms.html#maximum-allowed-value-length).

The `length` function (that is used to display the amount of entered characters, as discussed below) however counts newlines as *one* characters (because in the value string they are just `\n`, the browser just counts them internally as `\r\n` because when the form is submitted that how they are going to be encoded).

That is inconsistent behavior and confuses the users, as the counter displays something like 5/10 but the textarea won't allow you to enter any more characters (this would be the case if you'd enter 5 linebreaks).

### Possible solutions

We should should either adjust the behavior of the textarea limit or the behavior of the counter.

This is a non trival choice - one one hand you want to stick to the specs (and they have a valid point, because if you submit that textarea using a form a newline is submitted as two characters) - but on the other hand that's something the user does not expect - he'd expect that a line break is just one character.

Anyways, to adjust the behavior of the limit, we'd have 

- either to enforce the limit using javascript (which is easy because the input is a *controlled* input, meaning we can just block any input after the `length` function determines that the string reached it maximum length, or better: prevent insertion of characters in the onKeyPress handler)

- or have to let the counter count a newline as two characters, which is trival too. 

I'd prefer the first approach (counting a newline as one character). I could create a PR for this if that'd help.

Cheers,
Simon

**Comment by javivelasco** [comment]
Great PR and great report! Thanks @SimonSelg !
