### ISSUE TITLE
Holding down the delete key on some input fields makes the cursor jump back to the beginning of the line

### ISSUE THREAD

**Issue by ashokfernandez** [react-toolbox/react-toolbox#689]
When using some input fields, the cursor will jump back to the beginning of the line. Here is an example of this behaviour in the email input field from the docs:

![example](http://i.giphy.com/3o7TKRc4Vvb7XmzV3W.gif)

It doesn't seem to happen in all input fields and only seems to happen when there are spaces (i.e more than one word)

Example was taken from Chrome 51.0.2704.106 on OSX 10.11.5

**Comment by javivelasco** [comment]
This is happening because it's an email type and there is a [reported bug](https://github.com/facebook/react/issues/6368) in React repository about it. Closing since it's not actually related to the library.
