### ISSUE TITLE
 Error: Cannot resolve module 'react-addons-update'

### ISSUE THREAD

**Issue by miserylee** [react-toolbox/react-toolbox#695]
```
ERROR in ./~/react-toolbox/lib/ripple/Ripple.js
Module not found: Error: Cannot resolve module 'react-addons-update' in /Users/miserylee/Documents/projects/plugit/node_modules/react-toolbox/lib/rippl
e
 @ ./~/react-toolbox/lib/ripple/Ripple.js 25:25-55
```

Is there any update duration the past few days? It works fine the day before yesterday.
I have resolved the issue by `npm install --save-dev react-addons-update`, but I think it's not a good way to use a framework so complicated.

**Comment by javivelasco** [comment]
Just released a new version including the dependency as a `peerDependency`. Please update to `1.1.1`!

**Comment by Klathmon** [comment]
Can you mention this in the release notes of 1.1.0 (or 1.1.1 if you want)?

I generally check those before updating and not seeing that I'd need a new dependency threw a (admittedly small) wrench into my morning (especially when I missed the unmet peer dependency warning).

**Comment by javivelasco** [comment]
Done!

**Comment by ben-foxmoore** [comment]
@javivelasco Should `react-addons-update` be replaced by [`immutability-helper`](https://www.npmjs.com/package/immutability-helper)? Apparently Facebook [are deprecating](https://github.com/facebook/react/issues/2909) `react-addons-update`.

**Comment by javivelasco** [comment]
Yeah I think so @ben-foxmoore Do you want to PR?

**Comment by ben-foxmoore** [comment]
@javivelasco Will do (using my personal account @InfernoZeus )

**Comment by stereobooster** [comment]
```
Error in ./~/react-toolbox/lib/ripple/Ripple.js
Module not found: 'immutability-helper' in /Users/**/my/test-custom-react-scripts/node_modules/react-toolbox/lib/ripple

 @ ./~/react-toolbox/lib/ripple/Ripple.js 23:26-56
```

node -v: v6.1.0
npm -v: 3.8.6
"react-toolbox": "^1.2.1"

**Comment by futzco** [comment]
@stereobooster same thing here. Just wanted to check react-toolbox, but I guess I'll stick with muicss for the time being.

`
Ripple.js:23 Uncaught (in promise) Error: Cannot find module "immutability-helper"(…)
`

react-toolbox": "^2.0.0-beta.0
node -v: v6.5.0
npm -v: 3.10.8

**Comment by InfernoZeus** [comment]
What does `npm list immutability-helper` say?

**Comment by tumetus** [comment]
Same here.

`ERROR in ./~/react-toolbox/lib/ripple/Ripple.js
Module not found: Error: Cannot resolve module 'immutability-helper' in s:\git\**\src\react\node_modules\react-toolbox\lib\ripple
 @ ./~/react-toolbox/lib/ripple/Ripple.js 23:26-56`

react-toolbox: 1.2.3
node: 5.6.0
npm: 3.6.0

@InfernoZeus got the following when running npm list immutabliity-helper:

> +-- UNMET PEER DEPENDENCY immutability-helper@~2.0.0
+-- UNMET PEER DEPENDENCY react@15.1.0
+-- UNMET PEER DEPENDENCY react-addons-css-transition-group@15.1.0
`-- UNMET PEER DEPENDENCY react-dom@15.1.0
npm ERR! peer dep missing: react@^0.14.8, required by react-addons-test-utils@0.14.8
npm ERR! peer dep missing: react@~0.14 || ~15.3.0, required by react-toolbox@1.2.3
npm ERR! peer dep missing: react-addons-css-transition-group@~0.14.0 || ~15.3.0, required by react-toolbox@1.2.3
npm ERR! peer dep missing: react-dom@~0.14.0 || ~15.3.0, required by react-toolbox@1.2.3
npm ERR! peer dep missing: immutability-helper@~2.0.0, required by react-toolbox@1.2.3
npm ERR! code 1

**Comment by jonocairns** [comment]
I was able to resolve this by doing the following 

Firstly, I ran `npm list immutability-helper` as suggested by @InfernoZeus this gave me the following result:

+-- UNMET PEER DEPENDENCY babel-core@^6.0.0
+-- UNMET PEER DEPENDENCY immutability-helper@~2.0.0
`-- UNMET PEER DEPENDENCY react-addons-css-transition-group@~0.14.0 || ~15.3.0

So then I just ran through the unmet deps and npm installed them with --save-dev. The ordering is important as react-addons-css-transition-group depends on immutability-helper.

`npm install babel-core --save-dev`

Then

`npm install immutability-helper --save-dev`

Then

`npm install react-addons-css-transition-group --save-dev`
