### ISSUE TITLE
IE: copy pasting text into input using mouse does not trigger input on change

### ISSUE THREAD

**Issue by dlebedynskyi** [react-toolbox/react-toolbox#698]
Look like a minor bug. Sadly we still need to use IE 11

IE only. possibly only IE 11
1. Copy any text.
2. type something in input field. 
3. Clear input field using IE x button on right on input
4. right click inside of input and do paste

Current - on change does not trigger 

Expected - value of input is changed and onChange is triggered.

note - ctrl+c/ ctrl+v works fine. Only on mouse paste issue

latest react-toolbox 1.1,1. react 15.

similar issue found with google https://github.com/olahol/react-tagsinput/issues/84

**Comment by jcullen** [comment]
Seems like a core react issue that may already be fixed for the next release, see https://github.com/facebook/react/issues/7211 (and https://github.com/facebook/react/issues/7475)

**Comment by javivelasco** [comment]
Interesting, thanks both!
