### ISSUE TITLE
FR: expandable input with icon button

### ISSUE THREAD

**Issue by ceram1** [react-toolbox/react-toolbox#71]
mdl: http://www.getmdl.io/components/index.html#textfields-section
See "Expanding"

**Comment by soyjavi** [comment]
Hi @ceram1 

Now we are moving all our components to *stateless mode*. When we have completed this process I will create this property for `<Input>`.

**Comment by javivelasco** [comment]
Thanks for reporting @ceram1 We will include it soon!

**Comment by javivelasco** [comment]
Since it's out of the spec we are not implementing if for now. If you feel like it's very important add +1 so we can reconsider it.

**Comment by ceram1** [comment]
As it's common in "Do" in material design spec, I searched for it and found https://www.google.com/design/spec/patterns/search.html#search-in-app-search
See Expandable Search

**Comment by javivelasco** [comment]
Well, this is actually from Patterns and it looks more like the autocomplete...

**Comment by ceram1** [comment]
I meant
https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsYkJBc2RpNFI0SU0/patterns_search_expandable1.png and https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsUENaeGRvVks0Tms/patterns_search_expandable2.png

Spec refered this images from "Expandable search"
