### ISSUE TITLE
ENTER in Autocomplete selection causes e.stopPropagation is not a function

### ISSUE THREAD

**Issue by mglonnro** [react-toolbox/react-toolbox#714]
Cheers, 

Sorry if this is a misplaced newbie question but I got this error in my own project and get it in the playground (http://react-toolbox.com/#/components/autocomplete) as well: 

- Click into the first autocomplete component
- Navigate to either selection (England, USA) with keyboard and press ENTER

=>

`Uncaught TypeError: e.stopPropagation is not a functionpause
Event @ docs.js:6
n.select @ docs.js:29
n.handleQueryKeyUp @ docs.js:29
r @ docs.js:9
s @ docs.js:9
o @ docs.js:9
p @ docs.js:7
f @ docs.js:7
n @ docs.js:29
processEventQueue @ docs.js:7
r @ docs.js:92
handleTopLevel @ docs.js:92
a @ docs.js:92
perform @ docs.js:7
batchedUpdates @ docs.js:92
a @ docs.js:6
dispatchEvent @ docs.js:92`

**Comment by mglonnro** [comment]
Ok, the fix seems to be here: 
https://github.com/react-toolbox/react-toolbox/issues/697

**Comment by javivelasco** [comment]
Fixed! Thanks for reporting!
