### ISSUE TITLE
Allow "name" property on input elements

### ISSUE THREAD

**Issue by DarkoKukovec** [react-toolbox/react-toolbox#722]
The `name` property is required in order to submit the form if the client-side JS is disabled.

**Comment by javivelasco** [comment]
+1 PR??

**Comment by acornejo** [comment]
I am confused, the `name` property is already supported on the input component, did you try it and it didn't work for you @DarkoKukovec?? I agree that the documentation needs to be updated, but that is a different issue.

**Comment by javivelasco** [comment]
It's true. Actually it's supported but implicit. I did not noticed. Thank you @acornejo !
