### ISSUE TITLE
How pass theme via context?

### ISSUE THREAD

**Issue by tselishev-semen** [react-toolbox/react-toolbox#723]
Hi, I want customize  theme in **Autocomplete** component but I don't understand how I can do it.
I can pass some themes, which was described in http://react-toolbox.com/#/components/autocomplete
(active,autocomplete,focus,input,label)
```javascript
<Autocomplete theme={{active: 'active-class'...}}/>
```
This works perfectly.

But **Autocomplete** component is using **Chip** component.
How I can customize theme in such Chip component?

There ( http://react-toolbox.com/#/components/chip ) is a phrase:
>  If you want to provide a theme via context, the component key is RTChip.

Could you give example for this functionality?

**Comment by gavriguy** [comment]
in http://react-toolbox.com/#/install there is a section about theming describing how you should do it. I would also recommend passing to theme attribute an imported `scss` file and way it's written in the link I mentioned.

**Comment by tselishev-semen** [comment]
@gavriguy, thanks a lot

**Comment by javivelasco** [comment]
Great to see you figured it out! I wanted to add that in case you need to inject a customized component into another that needs it as dependency, the factory functions are exposed and can be imported as well: https://github.com/react-toolbox/react-toolbox/blob/dev/components/autocomplete/Autocomplete.js#L16

This way you can even create a custom Chip from a raw component and generate a style Autocomplete that uses that chip you've just created. 👌

**Comment by tselishev-semen** [comment]
@javivelasco, Did I understand correctly that this feature already in master and I can use it?
Your link to the dev branch, but i see similar code already in master:
https://github.com/react-toolbox/react-toolbox/blob/master/components/autocomplete/Autocomplete.js#L16

**Comment by javivelasco** [comment]
Yes, this is usable from the latest release but it's not documented because it's not easy to explain and most people don't need it :)

**Comment by tselishev-semen** [comment]
@javivelasco, it's very good, thanks

**Comment by javivelasco** [comment]
Great!! Happy you like it 😄
