### ISSUE TITLE
Typescript typings problem - ReactJS dependency

### ISSUE THREAD

**Issue by giacomorebonato** [react-toolbox/react-toolbox#727]
I have a problem that I am not sure it is not related to this repo, but I am looking for advices.
Running the `tsc` command everything works... so the Typescript validations pass...  
I have written my tests in Typescript and I would like to just use `ts-node` without converting them.  
This is the command I use  
```
NODE_ENV=test $(npm bin)/mocha -r jsdom-global/register --compilers ts:ts-node/register --compilers tsx:ts-node/register --require ignore-styles ./src/**/__tests__/**.spec.ts*
```  
I get the following error and it looks like it is not resolving ReactJS typings for react-toolbox.

```
/Users/grebonato/Code/JavaScript/mino_material/node_modules/ts-node/src/index.ts:253
          throw new TSError(diagnosticList)
                ^
TSError: ⨯ Unable to compile TypeScript
src/views/Root.tsx (24,12): Property 'className' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Menu> & MenuProps & { children?: ReactNode; }'. (2339)
src/views/Root.tsx (33,8): Property 'className' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<IconButton> & IconButtonProps & { children?: React...'. (2339)
src/views/Root.tsx (36,8): Property 'onClick' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<IconButton> & IconButtonProps & { children?: React...'. (2339)
```

Do you have any idea?

**Comment by javivelasco** [comment]
Maybe somebody from #591  could help?

**Comment by giacomorebonato** [comment]
Sorry... I have resolved it. It is a problem with Typescript@next and I have reported it.
Using the stable version everything works.

**Comment by javivelasco** [comment]
Great!

**Comment by adrian-moisa** [comment]
@giacomorebonato Can you give some details?
