### ISSUE TITLE
Using Tooltip with a common <div>

### ISSUE THREAD

**Issue by gabrielenosso** [react-toolbox/react-toolbox#728]
How do I use the tooltip component with a normal div?

**Comment by javivelasco** [comment]
I'm afraid that since it's an HOC you need a component to decorate. Fortunately it's as easy as a simple function. Try this in the playground:

```jsx
const TooltippedDiv = Tooltip(props => <div {...props} />)

const TooltipTest = () => (
  <TooltippedDiv 
  	style={{ display: 'inline-block' }} 
    tooltip="I am the tooltip!!"
    label="I'm a div with a tooltip"
  />
);

return <TooltipTest />;
```

I don't know if there is a better way thought! :)

**Comment by neekey** [comment]
@javivelasco this snap actually works, but with a tiny problem: when I try to do some theming for the `TooltippedDiv` using `theme`, React will give me a warning for giving `theme` to div.

Anyway, for anyone who may find this useful, I made a wrapper for easier usage of tooltip:

```js
/**
 * This is just a wrapper for easy use of tooltip.
 */
import React from 'react';
import tooltip from 'react-toolbox/lib/tooltip';
import omit from 'lodash/omit';
import theme from './theme.Tooltip.scss';

function Div(props) {
  const rest = omit(props,
    ['theme', 'tooltip', 'tooltipDelay', 'tooltipHideOnClick']);
  return (<div {...rest} />);
}

const Tooltip = tooltip(Div);

/**
 * This wrapper add theme style and default delay, and disable tooltip when `tooltip` is empty.
 * @param props
 * @constructor
 */
export default function TooltipWrapper(props) {
  if (props.tooltip) {
    return (<Tooltip
      tooltipDelay={400}
      {...props}
      theme={Object.assign({}, theme, props.theme || {})} />);
  }
  return <Div {...props} />;
}

TooltipWrapper.propTypes = {
  tooltip: React.PropTypes.any,
  theme: React.PropTypes.object,
};
```

You could use it:

```html
< TooltipWrapper tooltip="my tooltip" >Hover me</TooltipWrapper>
```

And if the `tooltip` is empty, the tooltip will not appear.

**Comment by javivelasco** [comment]
Yeah @neekey I can't think about a workaround from the library right now since the tooltip can't just swallow the theme property. Your approach looks good! 👍

**Comment by dwojtyca** [comment]
@javivelasco is Your approach still working? I don't have any errors but the tooltip is not showing in my case. Here is my code:
`import React from 'react';
import Tooltip from 'react-toolbox/lib/tooltip';

const TooltippedDiv = Tooltip(props => <div>{props.value}</div>),
    TooltipDecorator = props => {
        return <TooltippedDiv tooltip="test tooltip" {...props} />;
    };

export default TooltipDecorator;`

**Comment by javivelasco** [comment]
The tooltip is injected on mouse enter for the decorated component. In your example you're not passing the onMouseEnter, that's why it's not shown :) You have to spread the props to the `div` too

**Comment by dwojtyca** [comment]
Thanks for Your response, but unfortunately this not take effect. My tooltip is still not working even when I've added {...props} to div inside my component function. 

I've also tested it on React-toolbox website (http://react-toolbox.com/#/components/tooltip) in playground section and it is also not working. @javivelasco  did You tested it? Could You share Your working example?

**Comment by osala-netquest** [comment]
I couldn't make it work too

**Comment by javivelasco** [comment]
@dwojtyca @osala-netquest In the playground:

```jsx
const Other = (props) => (
	<div {...props} />
);

const TooltippedDiv = Tooltip('div');
const TooltippedOther = Tooltip(Other);

const TooltipTest = () => (
  <div>
  	<TooltippedDiv tooltip="Hello raw div">Raw div</TooltippedDiv>
    <TooltippedOther tooltip="Hello other">Other component</TooltippedOther>
  </div>
);

return <TooltipTest />;
```

**Comment by osala-netquest** [comment]
Thanks @javivelasco

Even your answer solved my specific problem, same example but not using a self closing tag isn't working. Maybe I'm not taking in account something obvious... anyway thanks!

```javascript
const Other = (props) => (
	<div {...props}>Other component</div>
);

const TooltippedOther = Tooltip(Other);

const TooltipTest = () => (
  <div>
    <TooltippedOther tooltip="Hello other">Other component</TooltippedOther>
  </div>
);

return <TooltipTest />;
```

**Comment by javivelasco** [comment]
Here:

```jsx
const Other = (props) => (
  <div {...props}>Other component</div>
);
```

You are hardcoding `children` to `"Other component"`. The tooltip is injected as a child so if you don't pass children to that div you'll never see the tooltip. change it to:

```jsx
const Other = (props) => (
	<div {...props}>{props.children}</div>
);
```

And it will work :)

**Comment by fallanic** [comment]
this worked for me (using `props.onMouseEnter`, `props.onMouseLeave` and `props.children`)

```
const StatusIcon = Tooltip(props => (
	<div onMouseEnter={props.onMouseEnter} onMouseLeave={props.onMouseLeave} className="my-custom-class">
		<img src={myIcon} alt={myAlt} />
		{props.children}
	</div>
));
return <StatusIcon tooltip={`${myToolTip}`} />;
```
