### ISSUE TITLE
Out of date documentation? Install error and Button import error with react-hot-boilerplate.

### ISSUE THREAD

**Issue by alltom** [react-toolbox/react-toolbox#73]
http://react-toolbox.com/#/install and the README seem to recommend using react-hot-boilerplate and seem to say I can use Button out of the box.

But I run into two problems:
* `npm install --save react-toolbox` complains about missing react-addons-css-transition-group and normalize.css.
* The `react-toolbox/button` module can't be found. Installing react-addons-css-transition-group and normalize.css doesn't fix this error.

---

Full transcript:

    $ git clone https://github.com/gaearon/react-hot-boilerplate.git
    ...
    $ cd react-hot-boilerplate/
    $ npm install
    ...
    $ npm install --save react-toolbox
    ...
    npm WARN EPEERINVALID react-toolbox@0.11.3 requires a peer of react-addons-css-transition-group@^0.14.0 but none was installed.
    npm WARN EPEERINVALID react-toolbox@0.11.3 requires a peer of normalize.css@^3.0.3 but none was installed.
    ...
    $ npm start

At this point, accessing http://localhost:3000/ shows "Hello, world."

So I add this line to `App.js`:

    import Button from 'react-toolbox/button';

Hot recompilation fails:

    Module not found: Error: Cannot resolve module 'react-toolbox/button' in /Users/tom/src/react-hot-boilerplate/src

**Comment by javivelasco** [comment]
Yes, the docs are outdated. I'm going to update now, you have to import from 'react-toolbox/lib/button'. 

Check the organization account. There is a working example there. 
Thanks!!

**Comment by alltom** [comment]
I'm up and running. Thanks a ton.

**Comment by javivelasco** [comment]
I'm happy to read it, great! :)
