### ISSUE TITLE
DatePicker not displaying first day of month

### ISSUE THREAD

**Issue by wvetter22** [react-toolbox/react-toolbox#731]
If the first day of the month is on a Sunday and the sundayFirstDayOfWeek == false, the first day is not being displayed.

![image](https://cloud.githubusercontent.com/assets/11875617/17909090/fa0b2e7a-6950-11e6-9023-bcf751bd264f.png)

**Comment by javivelasco** [comment]
Thanks for reporting!

**Comment by rubenmoya** [comment]
I found the error in CalendarDay.js line 24, when `time.getFirstWeekDay(this.props.viewDate) - e` is negative produces an incorrect margin.

**Comment by javivelasco** [comment]
It's fixed now

**Comment by kodemi** [comment]
I have the same error in the last version.

**Comment by javivelasco** [comment]
I'm releasing today. If it still happens please reopen!
