### ISSUE TITLE
Compiled CSS Organization

### ISSUE THREAD

**Issue by coljung** [react-toolbox/react-toolbox#741]
I've noticed that the way the compiled CSS works is from bottom to top. Meaning that any custom styles I add on my app are compiled first, thus appear first on my final CSS, where as if I include commons.scss at the root of my document, the final CSS version has those styles right at the end of my CSS.

I think the compiled CSS should have the inverse order for this. We are basically having ~normalize be the last section of our compiled CSS, which doesnt make any sense.

Is there a way to modify this behaviour ?

I noticed this issue because I was trying to create some kind of overwrites file, with a few minor resets of my own. But I was unable to make it work normally because normalize is the last part of my CSS and it trumps whichever styles I created ( unless i used specificity ).

**Comment by javivelasco** [comment]
Hi @coljung! 

I guess it all depends on your build tool. You can always boost a little of priority just assigning a class on top of your customized component.

Also I think there is no way to control this from the library but normalize being added at the bottom is definitively an issue. I've tried some different configurations in webpack and what you require first gets bundled first but probably there is no guarantee on that.

Let's keep this open a bit in case somebody figured out a way to set up the order :)

**Comment by coljung** [comment]
Thanks for the reply.

What i did in order to have a global overwrites file was:

On my entry point to the App, where we import react-toolbox/lib/commons.scss i added:

```javascript
import 'react-toolbox/lib/commons.scss';
require('./styles/overwrites.scss');
```

This then fixes my problem with having a global overwrites rewritten by normalize.

Now, the problem persists where common.scss ( and my overwrites file ) are compiled AFTER the rest of the CSS of my application.

**Comment by javivelasco** [comment]
Yeah exactly, that makes sense. I guess that you are doing both imports at the top of your app and then requiring `App.js` later? If that's the case if should work the same

**Comment by javivelasco** [comment]
Please @coljung try out this:

https://twitter.com/javivelasco/status/810763888690163712

This plus react-toolbox@2.0.0-beta.4 should solve the issues

**Comment by coljung** [comment]
Great, thanks again!
