### ISSUE TITLE
Ripple effect over the outer container, become very ugly，Unable to fit border-radius 

### ISSUE THREAD

**Issue by yiluxin** [react-toolbox/react-toolbox#748]
![2016-08-29 06 43 38](https://cloud.githubusercontent.com/assets/10407739/18037361/3e3b3efc-6db4-11e6-901c-d7a815f0c70f.png)
Ripple effect over the outer container, become very ugly，Unable to fit border-radius

**Comment by javivelasco** [comment]
You have to customize the ripple using the theme properties. For example, the `Button` component needs to customize the ripple to hide overflow and round corners as you want to do in your example. Checking [here](https://github.com/react-toolbox/react-toolbox/blob/dev/components/button/theme.scss#L48) and [here](https://github.com/react-toolbox/react-toolbox/blob/dev/components/button/theme.scss#L109) might be helpful :)

**Comment by yiluxin** [comment]
$button-border-radius: 2 * $unit;
.rippleWrapper {
  border-radius: 2 * $unit;
}

Thanks for the help, I solve this problem

**Comment by javivelasco** [comment]
Great, glad to read!!
