### ISSUE TITLE
Input floating label collides with browser place holders

### ISSUE THREAD

**Issue by PhantomPayne** [react-toolbox/react-toolbox#75]
It looks like the floating label on input fields doesn't work right when there are placeholders automatically added by the browser (eg date, time, color, week)

Example input
```javascript
import Input from 'react-toolbox/lib/input';
<Input type='time' label='Duration' icon='phone'/>
<Input type='date' label='Date' icon='phone' />
```
Example output
![image](https://cloud.githubusercontent.com/assets/6565044/11018179/77271e42-858a-11e5-95d0-5d2ef85f0a1e.png)

I encountered this issue by cloning down react-toolbox-example and adding the above javascript.

I observed this in Chrome 46 on Windows 10.

**Comment by soyjavi** [comment]
Thanks @PhantomPayne for report this bug, I will fix ASAP

**Comment by soyjavi** [comment]
Fixed in the next release 
https://github.com/react-toolbox/react-toolbox/commit/34cef32038874df956af61fd03a4c58386577e3a
