### ISSUE TITLE
Unable to make it work with react-boilerplate

### ISSUE THREAD

**Issue by tusharkhatiwada** [react-toolbox/react-toolbox#753]
Hi,
I'm trying to use this library with `react-boilerplate`. I even followed this issue. #527 . But I'm still getting this error :

`Uncaught (in promise) Error: Cannot find module "./theme.scss"`

These are my settings:

```
{
      test: /\.scss$/,
      include: /node_modules\/react-toolbox/,
      loader: options.sassLoaders,
    }
```

`sassLoaders: 'style-loader!css-loader?localIdentName=[local]__[path][name]__[hash:base64:5]&modules&importLoaders=1&sourceMap!postcss-loader!sass-loader',`

```
resolve: {
    modules: ['app', 'node_modules'],
    extensions: [
      '',
      '.js',
      '.jsx',
      '.react.js',
      '.scss',
    ],
```

There's no error on the terminal `npm run start`. The above error shows on Chrome's console though.

Am I missing anything? 
Thanks.

**Comment by douglasjunior** [comment]
Please, check my sample project, maybe help you https://github.com/douglasjunior/learning-react/tree/master/ReactWebpackCssModulesReactToolbox

**Comment by tusharkhatiwada** [comment]
@douglasjunior Thanks for the link. But I want it to work with [react-boilerplate](https://github.com/mxstbr/react-boilerplate)

**Comment by douglasjunior** [comment]
I dont know [react-boilerplate](https://github.com/mxstbr/react-boilerplate), but you need to configure the [css-modules](https://github.com/css-modules/css-modules) before [react-toolbox](http://github.com/react-toolbox/react-toolbox/). So, I choose to start with the [webpack-demo](https://github.com/css-modules/webpack-demo) provided by @css-modules. Of all the ways that I've tried, this was the easiest to get.

So, first of all, you need to check if `react-boilerplate` is ready for work with `css-modules` (and SASS loader), then it's easy to configure `react-toolbox`.

**Comment by javivelasco** [comment]
Yeah @tusharkhatiwada The only thing you'd need is to customize the webpack config given by the boilerplate to allow having `css-modules` enabled by default at least for `react-toolbox` imports. There are some issues about configuration that can give you more insights about how to configure. Since react-boilerplate uses webpack, it should work for you with those examples so I'm going to close here to avoid duplication!
