### ISSUE TITLE
Autocomplete allowCreate not working

### ISSUE THREAD

**Issue by be4code** [react-toolbox/react-toolbox#755]
While using `allowCreate={true}` an error is thrown after pressing 'Enter' .

**Comment by nicomfe** [comment]
hey @javivelasco Im having this issue, and the fix doesnt seem to help, 

Im using a multiple value autocomplete, when I insert a new value and press enter the chip doesnt get added. Im not seeing any error on the console either.

**Comment by be4code** [comment]
I figured out it is necessary to add manually entered value to the `source`.

26 wrz 2016 23:46 "Nicolas" <notifications@github.com> napisał(a):

**Comment by nicomfe** [comment]
but whats the point of the allowCreate then? if you have to add manually new values.

**Comment by be4code** [comment]
Imho none :) but that's how it works currently

2016-09-27 0:05 GMT+02:00 Nicolas <notifications@github.com>:

**Comment by javivelasco** [comment]
Ha! Maybe it was not released yet? If allowCreate it's not useful it should be removed 😕

**Comment by matthax** [comment]
Perhaps the Autocomplete should actually have a callback for when a new item is created? That way we can easily implement adding the new value to the source, and avoid altering the input source property...
