### ISSUE TITLE
Should mention commons.scss in Installation guide

### ISSUE THREAD

**Issue by jasson15** [react-toolbox/react-toolbox#756]
It costs me hours to figure out the styling goes wrong without importing `commons.scss` . Take  [react-toolbox-example](https://github.com/react-toolbox/react-toolbox-example) for example. If we comment out the line importing `commons.scss`:

``` javascript
import React from 'react';
// import 'react-toolbox/lib/commons.scss';           // Import common styles
```

The style will become

<img width="463" alt="screen shot 2016-08-31 at 12 58 29 pm" src="https://cloud.githubusercontent.com/assets/8468853/18144271/a8867cc8-6f7a-11e6-9b2f-5549bbaa9c1d.png">

_(font family not applied, way too big buttons and so forth)_

It seems trivial to those developers familiar with this project. But for those beginners like me, having this in the [documentation](http://react-toolbox.com/#/install) saves their lives.

**Comment by javivelasco** [comment]
Yeah, definitively agree. It will be included with #666 so I'm closing in favor of that
