### ISSUE TITLE
Organizational Question ?

### ISSUE THREAD

**Issue by rwatts3** [react-toolbox/react-toolbox#765]
Greetings, 

Would it be possible to create an index.js file as a rollup export of all components. 
This way we can use syntax in es6 like so : 

`import { Button , Layout } from 'react-toolbox';

It's not a huge problem, but when doing rapid development. it's a lot easier than trying to remember which components are in which directory.

**Comment by javivelasco** [comment]
Isn't it [this](https://github.com/react-toolbox/react-toolbox/blob/dev/components/index.js) one? The problem with that kind of import is that you will be bundling all components even though you're not actually using them

**Comment by acornejo** [comment]
yup, this already works.

try ```import { Button, Layout } from 'react-toolbox/lib'```

The lib is an artifact of the way react-toolbox handles npm releases, but that is a separate issue.
