### ISSUE TITLE
minTime, maxTime

### ISSUE THREAD

**Issue by JWo1F** [react-toolbox/react-toolbox#767]
Hi there! Do you want to add some properties: minTime & maxTime (for timepicker)?

I mean:
`<TimePicker minTime="12:30" maxTime="14:50" />`

**Comment by javivelasco** [comment]
No sure how does it fit with the spec. I mean, there should be a way to provide feedback to tell the valid range to the user. I never saw it before in Android so I wonder it it should be controller from outside the component

**Comment by javivelasco** [comment]
Closed since I got no feedback. I think it would make sense but showing disabled dates is pretty straightforward for the `DatePicker`. For `TimePicker` I am not sure.
