### ISSUE TITLE
Autocomplete on search

### ISSUE THREAD

**Issue by kencana-voilaah** [react-toolbox/react-toolbox#770]
After updating my react lib + react toolbox, the search query doesn't seems to work anymore. 

`<Autocomplete
          label={props.label}
          onChange={props.onChange}
          source={props.data}
          value={props.value}
          disabled={props.disabled}
          multiple={false}
        />`

it doesn't seems to work on sandbox either, http://react-toolbox.com/#/components/autocomplete

seems like `const rawQuery = this.state.query || this.props.multiple ? '' : this.props.value;` in suggestion method line 166 is causing the issue. it's always returning an empty string

does this make sense `const rawQuery = this.state.query || (this.props.multiple ? '' : this.props.value);` > this will work. do correct me if i am wrong. thank you

**Comment by kencana-voilaah** [comment]
and one more thing, not sure if it make sense to include in name props for the Autocomplete component. seems like it's not being passed on to the input component

**Comment by javivelasco** [comment]
Fixed and released, thanks! Btw, I think the `name` prop should be passed down. Maybe I'm missing something but a `name` prop is unknown to the `Autocomplete` so it takes it in a rest operation along with other unknown props and spread them to the input.
