### ISSUE TITLE
Closing a Dropdown from outside

### ISSUE THREAD

**Issue by pablonete** [react-toolbox/react-toolbox#774]
Hola,

We need to close a dropdown when something happens in another component of the page. I've seen that Dropdown has a public method called close(), but actually I'd like to be able to close the Dropdown through props, and I'm missing something like `isDroppedDown`. Is `close` the supported way of achieving this, or am I missing something?

-Pablo

**Comment by javivelasco** [comment]
Hi! Well, this is not actually possible at the moment. It's true that there is an instance method to close the Dropdown but it is there for convenience and just internal usage. If you want to use it anyway you can access the decorated component instance or to use `findDOMNode` and call the method but the best is to create a new property. So here is the thing:

The Dropdown is a component that most people would use without the need of keeping the active state out of it. For this reason I think it's convenient to keep the behavior in an internal state but it should be possible to keep it out as well. The most immediate solution coming to my mind is to add an `active` property synchronizing the state. Still you need to know out of the component when the state changes so also we should add a function property like `onActiveChange`. This way it would be possible to choose between delegating state control or implement it outside.

What do you think? Should be just extract the state?

**Comment by javivelasco** [comment]
Closed in favor of #1169. We are going to sync an active prop with the internal state so you can pass your custom and close the dropdown from outside
