### ISSUE TITLE
Make Dropdown look the same as input/autocomplete

### ISSUE THREAD

**Issue by rowanG077** [react-toolbox/react-toolbox#776]
Hey guys!

thank you for your hard work on this.

I have some layout issues though. For one I really like the input and autocomplete component.
The problem I am having is that the dropdown doesn't really fit in with either input or autocomplete. 

If you directly compare the autocomplete and the dropdown they are very similiar in function. Both allow you to pick a value from a range of values. However the autocomplete is nicely style to look like an input and the panel starts exactly below the input. The dropdown however has a slight different style where the dropdown panel overlays the input.

I hope you agree and can correct this!

**Comment by acornejo** [comment]
Not against this. However, react-toolbox is juat following the spec.

Dropdown are here (look for dropdown) https://material.google.com/components/menus.html#menus-usage

And auto complete here https://material.google.com/components/text-fields.html#text-fields-auto-complete-text-field.

**Comment by rowanG077** [comment]
I see, you are correct.

However then I would suggest at least aligning the options with the current selected option like the spec suggests.

**Comment by acornejo** [comment]
Yes. And another idea would be to add a new select field component (ideally internally just a wrapper around dropdown). A select field would only be capable of rendering text options, but it would look very similar to a text field or autocomplete to provide a consistent UI in forms.

What do you think? (I may try to so this in a PR).

**Comment by rowanG077** [comment]
Maybe it would be better to make dropdown into a higher order component so you could also make menus with it. 

then you could make the select from the autocomplete since you basically allready have most of the functionality. What would also be possible is make the standard select a special case of the autocomplete with a prop or something. But that wouldn't be as clean.
