### ISSUE TITLE
Tooltip TypeError when quickly hovering between multiple tooltips

### ISSUE THREAD

**Issue by gregegan** [react-toolbox/react-toolbox#780]
When you move the cursor really quick between the tooltip elements an error is thrown in console.
`Uncaught TypeError: Cannot read property 'style' of undefined`

![untitled](https://cloud.githubusercontent.com/assets/6665100/18331737/133aa83c-7516-11e6-9d95-1779dd25c224.gif)

https://github.com/react-toolbox/react-toolbox/blob/dev/components/tooltip/Tooltip.js#L84 

![image](https://cloud.githubusercontent.com/assets/6665100/18331799/7e112e38-7516-11e6-80a8-6465b7d0c6b6.png)

**Comment by gregegan** [comment]
Can anyone else validate this bug?

**Comment by vitalis** [comment]
Same here!!

**Comment by juneidysoo** [comment]
same thing happened, if the Tooltip-ed button throws an error, the button's onClick wouldn't work

**Comment by javivelasco** [comment]
Fixed!
