### ISSUE TITLE
Should allow `tooltip` prop for Tooltip to be element not only string

### ISSUE THREAD

**Issue by neekey** [react-toolbox/react-toolbox#787]
Hi, as the title, I think the property of `tooltip` should be able to take any valid element, not only string, this allows further customized format for tooltip.

My user case( just make it two paragraphs ):

![image](https://cloud.githubusercontent.com/assets/499870/18427531/134a1200-790c-11e6-985b-42c68ef33744.png)

**Comment by javivelasco** [comment]
Done. Remember you can now pass custom classnames to set the proper styles since if you use, for example paragraphs, some attributes like the font size might not get applied.

**Comment by neekey** [comment]
👍  Great work!
