### ISSUE TITLE
Table component: Multi select is broken

### ISSUE THREAD

**Issue by shidhincr** [react-toolbox/react-toolbox#79]
The table component multi select checkbox is kind of broken. It works when no rows are selected, but will not work for the selected rows.

See the screencast

![](https://dl.dropboxusercontent.com/u/32430642/react-toolkit-issue.gif)

**Comment by javivelasco** [comment]
Great, thanks for reporting! @soyjavi can you take a look on it?

**Comment by soyjavi** [comment]
When we release the new version of checkbox stateless it will be fixed ;)

**Comment by shidhincr** [comment]
:+1:  Thanks @soyjavi
