### ISSUE TITLE
How to add custom field to Table component

### ISSUE THREAD

**Issue by coljung** [react-toolbox/react-toolbox#796]
It seems you can add custom ( React components ) to the Table one.

For example, I have my source which is 5 fields, and i would like to add a custom one at the end with a button/link to edit such row.

So far i havent been able to achieve this, but i think its possible to have this minor customization.

thanks!

**Comment by q3452** [comment]
Just add an extra column with the controls, there are PRs for adding controls via the data model but they can already be added as data, see: #825.  Adding edit icons inside existing cells would be harder though.

**Comment by javivelasco** [comment]
Since there are too many issues with Table customization and it started looking like a monster, I've made a new implementation that it's going to be merged to #666 if there is no negative feedback. Please check and leave your opinion!
