### ISSUE TITLE
Decentered radio button

### ISSUE THREAD

**Issue by waj** [react-toolbox/react-toolbox#797]
Depending on the zoom level of the browser, I can see the center of the checked radio button misaligned:
<img width="182" alt="radio-buttons" src="https://cloud.githubusercontent.com/assets/22697/18537428/c4283b1c-7adb-11e6-91d9-d0948debbaa0.png">

I tried on different browsers (Chrome, Safari, Firefox) all with the same problem.

Is there any reason not to use the Material icons for this purpose?
  * https://design.google.com/icons/#ic_radio_button_checked
  * https://design.google.com/icons/#ic_radio_button_unchecked

**Comment by yhbrandon** [comment]
I like the idea of using icons. Will work out a PR to use these instead

**Comment by javivelasco** [comment]
We are not using icons in components like the Checkbox because we want to support an smooth animation and that's just not possible when you switch content if it's based on an icon. I'm fixing it since I just realized that it was not working either.
