### ISSUE TITLE
FR: Time picker fields should be editable

### ISSUE THREAD

**Issue by shidhincr** [react-toolbox/react-toolbox#80]
I feel it easy to use the time picker ( especially the minutes field ) by typing the numbers. Can you please add the option to manually add the time?

**Comment by javivelasco** [comment]
I don't know it's in the Material Design Spec. If so, I didn't notice. Can you provide an example on how do you expect it to look? If it's out of the spec, although it may be convenient, I think it shouldn't be implemented... just to keep as close as possible to the specs.

Thanks!

**Comment by soyjavi** [comment]
Hi @shidhincr I think it's out of the Material Design Spec. We have to respect the spec ;)

best,

**Comment by shidhincr** [comment]
Thanks @soyjavi @javivelasco

**Comment by javivelasco** [comment]
Thank you @shidhincr :)
