### ISSUE TITLE
How do i launch a icon menu from App Bar left Icon? 

### ISSUE THREAD

**Issue by jasan-s** [react-toolbox/react-toolbox#802]
This may be very obvious but i cant seem to figure it out.  I can successfully use the icon menu in the app bar but it places it to the far right (i want it before the title), might be due to the theme. so I thought using leftIcon would do the trick , but the left icon just takes a string , so just unclear how to launch pop up menu using theleftIcon clicked.

**Comment by acornejo** [comment]
leftIcon can take a string OR an element. this is an error in the documentation on my part. I have a PR that fixes that (amongst other appbar improvements).

**Comment by jasan-s** [comment]
Thanks. adding the entire element worked. @acornejo . is there a guide to overwrite theme styles using local css style sheets? the pop-up menu size is acceptable for large screens but for mobile the menu size is undesirable.

**Comment by acornejo** [comment]
Don't use inline styles, the docs describe the css class names used, and using the theme prop you can override all 
Css classes with your own. Detailed examples are on the installation section of the website.

As an aside, menu sizes look fine on my cellphone, and
It looks like it is following the spec for mobile menus, see here https://material.google.com/components/menus.html#menus-simple-menus.

If it looks very diferentes from that then you may have a problem with your webpack config.

**Comment by gala132** [comment]
Now with the new version, how can we open a `IconMenu` from the `rightIcon` for example? We define the `rightIcon={'more_vert'}` and then the handler for the `onclick` event `onRightIconClick={this.toggleActive}` but how can I open the `IconMenu`? I am struggling to understand that.
