### ISSUE TITLE
The library components are not responsive

### ISSUE THREAD

**Issue by jasan-s** [react-toolbox/react-toolbox#804]
ie: The input fields and input field text remains the same on mobile. 
menu: the text and container size is too large and doesnt auto-scale down as per screen size.

**Comment by javivelasco** [comment]
Yeah, it's a step that must be taken and it's reflected [here](https://github.com/react-toolbox/react-toolbox/issues/626). There are some things to do first like finishing the PostCSS release. Media breakpoints already exists in both SASS and future version so they would be easy checks. I'm closing in favor of #626
