### ISSUE TITLE
Layout issue : missing style for "lg-tablet" layout breakpoint

### ISSUE THREAD

**Issue by david-cho-lerat-HL2** [react-toolbox/react-toolbox#806]
Hi! Thanks again for react-toolbox!

If you look here :

https://github.com/react-toolbox/react-toolbox/blob/dev/components/layout/theme.scss#L117-L127

you'll see there's no style for `$layout-breakpoint-lg-tablet` :

https://github.com/react-toolbox/react-toolbox/blob/dev/components/_globals.scss#L77

So setting this:

`<NavDrawer permanentAt="lg-tablet">`

doesn't work. Could you please add the relevant style for this layout breakpoint ?

Thanks!

**Comment by javivelasco** [comment]
Yeah, never noticed. PR for this?

**Comment by david-cho-lerat-HL2** [comment]
Thanks!
