### ISSUE TITLE
Scrolling in Table

### ISSUE THREAD

**Issue by alwinn1977** [react-toolbox/react-toolbox#808]
Hello,
It is possible to fix table height and add scrolling to tbody with fixed thead?

**Comment by msaron** [comment]
Yes, but you will need to customize the Table component. The best solution I have found is from the following link and it works beautifully [http://stackoverflow.com/questions/17450861/add-scroll-bar-to-table-body](url)

**Comment by javivelasco** [comment]
Great!

**Comment by NarasimhaReddyY** [comment]
Accepted answer for the SO question you shared saying that, we need to wrap tbody inside a scrolable div, 
But as per documentation ``` TableRow should be place as a direct descendant of Table and it should has TableCells children.``` Then where should i insert div to make tbody scrolable ? @javivelasco @msaron

**Comment by javivelasco** [comment]
You can still write CSS for it right??
