### ISSUE TITLE
Table : having header labels

### ISSUE THREAD

**Issue by Nanane** [react-toolbox/react-toolbox#809]
Hi,

I've been confronted to a simple problem while using the Table component.
This works  fine : 
```
const model = {name:{type: String}};
const source = [
  {name:'Alan'}
];
...
<Table model={model} source={source} />
```

But if I want "name" to be displayed as "first name", I have to have this : 
```
const model = {"first name":{type: String}};
const source = [
  {"first name":'Alan'}
];
...
<Table model={model} source={source} />
```

I find this very hard to implement, as I must translate each and every keys in each row of my source.
But I didn't find any other solution for this.

What do you think about using a "label" property in the model description like this : 

```
const model = {name:{label:"name", type: String}};
const source = [
  {name:'Alan'}
];
...
<Table model={model} source={source} />
```

 ?

If a solution has already been implemented, please tell me !

Thanks for this great lib !

**Comment by chiester** [comment]
```const model = {name:{title:"name", type: String}};```

**Comment by Nanane** [comment]
Nice ! Thanks !

Is there any doc about this ?

**Comment by chiester** [comment]
There will be if they merge my pull request ;-)

https://github.com/react-toolbox/react-toolbox/pull/812

**Comment by chiester** [comment]
https://github.com/chiester/react-toolbox/tree/add-table-model-header-details-to-docs/components/table

**Comment by javivelasco** [comment]
Done!
