### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by mydearxym** [react-toolbox/react-toolbox#81]
hi @javivelasco 

i npm install the latest version and can not import it right 

```js
import Btn from 'react-toolbox/button'
```
```bash
Module not found: Error: Cannot resolve module 'react-toolbox/button'
.....
```

Or :
```js
import Btn from 'react-toolbox/lib/button'
```

```bash
Module not found: Error: Cannot resolve 'file' or 'directory' ./style 
....
```

**Comment by javivelasco** [comment]
Hi @mydearxym!

Sorry, the docs are wrong. I'm working on a ton on issues and couldn't change it yet. You should import components individually from `react-toolbox/lib`.

Thanks!

**Comment by pewh** [comment]
Hi @javivelasco 

Can you give some example how to import components individually from `react-toolbox/lib`?

**Comment by javivelasco** [comment]
Yes, documentation is already updated with the proper imports. [Here](https://github.com/react-toolbox/react-toolbox-example) you have a working example.
Hope you find it useful! :)

**Comment by Josenzo** [comment]
https://github.com/react-toolbox/react-toolbox-example/blob/master/server.js Must be written in ES5. Otherwise the example does not work.

**Comment by javivelasco** [comment]
You just have to start the server with a supported node version. Toolbox is tested with `4.2.1`, may you give a try?

**Comment by Josenzo** [comment]
Yes, working now. Thank you.
But do you know the webpack configuration to build a minified/deploy version? Because using `npm run deploy` is not working. With `npm run build` the JS and CSS is not minified and is about 1.93mb only the JS.

**Comment by javivelasco** [comment]
You can check an example on how can you configure webpack for production inside `docs` folder. Basically the process consists of putting all JS and CSS together, minifying and moving everything to a `build` folder. Then we use `gh-pages` package to deploy to a github pages branch and publish automatically the site. Remember to set a `production` flag on build to avoid transpiling with dev configuration!

**Comment by austinmao** [comment]
@javivelasco I am seeing this problem with node v5.0.0. Is it not compatible with this version?
