### ISSUE TITLE
Input multiline height

### ISSUE THREAD

**Issue by diondirza** [react-toolbox/react-toolbox#811]
Hi, how do you set input with multiline `true` (textarea) height?
I'm using `rows` attribute but didn't works.

**Comment by javivelasco** [comment]
At the moment it's not possible. The height adjusts depending on the content always in case it's a multiline Input. Maybe this behavior can be optional but I can't see the benefit. Do you want to set it fixed or just a minimum?

**Comment by diondirza** [comment]
I see. I want to set it as minimum height, because I have requirement to put a long message in `hint` attribute therefore if textarea doesn't have minimum height the hint message will be broken.

**Comment by javivelasco** [comment]
Oh! Yeah that's definitively an issue. I'm trying out with some different style implementations that allows the hint element to be placed differently with CSS making the component more flexible. The textarea should auto adjust to the hint content so this is an issue. I'll try to take a look during the weekend, I'm having busy days
