### ISSUE TITLE
ListItemContent exports are wrong/inconsistent

### ISSUE THREAD

**Issue by javaguru-ch** [react-toolbox/react-toolbox#813]
There seems to be a problem with ListItemContent. If we're trying to use the plain (non-themed) component as follows:

`import {ListItem} from 'react-toolbox/lib/list/ListItem';`

We get the following error in the browser console: 

> Warning: Unknown props \`caption\`, \`legend\` on \<span\> tag. Remove these props from the element.

In my opinion, there is something wrong with the exports in the file "components/list/ListItemContent.js".
The following code:
```
const ListItemContent = themr(LIST)(InjectListItemText);
export default ListItemContent;
export { factory as listItemContentFactory };
export { ListItemContent };
```

should look as follows:
```
const ListItemContent = factory(InjectListItemText);
export default themr(LIST)(ListItemContent);
export { factory as listItemContentFactory };
export { ListItemContent };
```
(which would then be consistent with what is done in "components/list/ListItemLayout.js".)

**Comment by javivelasco** [comment]
Thanks!!
