### ISSUE TITLE
Tabs: handleResize should also be called in no fixed mode. 

### ISSUE THREAD

**Issue by fraenku** [react-toolbox/react-toolbox#814]
I've added some tabs inside an appbar

```
<AppBar .../>
  <Tabs index={this.state.index} theme={theme} f>
</AppBar>
```

Through adaption of the theme, I have positioned the tabs to be in the center. If I make the screen smaller, the tabs adapt accordingly (moving to the left), the position of the pointer is not adapted, indeed. The reason for that is that the pointer adapts only if the Tabs are in fixed mode, but I do not want them to be fixed. 

```
handleResize = () => {
      if (!this.props.fixed) {
        return;
      }
```

**Comment by javivelasco** [comment]
Thanks for reporting!
