### ISSUE TITLE
handleDocumentClick not being fired in Menu on Safari Mobile

### ISSUE THREAD

**Issue by Findiglay** [react-toolbox/react-toolbox#816]
As title states, the callback is not being fired on iOS9/Safari Mobile when clicking off the an open menu item. This prevents the menu from closing without clicking on another button/menu item.

Is this a known issue?

**Comment by Findiglay** [comment]
Note that this can be reproduced the example here - from http://react-toolbox.com/#/components/menu

**Comment by Findiglay** [comment]
Adding the touchstart listener resolves this issue:

`events.addEventsToDocument({
    click: this.handleDocumentClick,    
    touchstart: this.handleDocumentClick 
})`

Also adding touchstart to the relevant removeEventsFromDocument calls.

Should I make a PR for this (provided this is fine with some more testing) or is there a preferred way to approach this?

**Comment by javivelasco** [comment]
Thanks!
