### ISSUE TITLE
Snackbar.label should be either a string or a React.Element

### ISSUE THREAD

**Issue by mikeplus64** [react-toolbox/react-toolbox#819]
Would make Snackbar labels much nicer to work with. My use case is simply to add some syntax highlighting to Snackbar labels

All that needs to be done is make label's proptypes: 

```javascript
PropTypes.oneOfType([
  PropTypes.string,
  PropTypes.element
]),
```

Alternatively Snackbar could use `children` as the same thing [but that would be a breaking change], or have both.

Not sure if making tiny PRs like that is shunned here or not.

**Comment by javivelasco** [comment]
Done!
