### ISSUE TITLE
NavDrawer customizing theme, width, etc

### ISSUE THREAD

**Issue by aislanmaia** [react-toolbox/react-toolbox#824]
I'm trying hard to work with NavDrawer, but I can't to modify the default width unless I hack into the "$navigation-drawer-mobile-width" variable. I can't find the doc for this component too.

My code is trying to customize like below: 

```
<Layout>
    <NavDrawer
        active={this.state.drawerActive}
        pinned={this.state.drawerPinned} permanentAt='xxxl'
        onOverlayClick={ this.toggleDrawerPinned }
        theme={theme}
    >
        <p>
            Navigation, account switcher, etc. go here.
        </p>
     </NavDrawer>
</Layout>
```

and the theme.scss : 

```
.navDrawer {
  width: 16rem;

  .pinned {
     width: 16rem;
  }
}

@media screen and (min-width: 600px) {
  .navDrawer {
    width: 16rem;

     .pinned {
        width: 16rem;
     }
  }
}
```

How can I do to customize this component just easy?

Thanks in advance.

**Comment by rubenmoya** [comment]
I'm pretty sure you have to change the with using `drawerContent`:

```
.navDrawer {
  & .drawerContent {
    width: 16rem;
  }
}
```

**Comment by aislanmaia** [comment]
I've tried, but this way doesn't work as well. : (

**Comment by javivelasco** [comment]
If the problem is that your custom CSS has no enough priority so it's not being applied what you need to do is to use a class to boost priority. For example, try adding a custom class `.myCustomDrawer` and then nest the styles within that selector.

**Comment by rubenmoya** [comment]
I just tried it in a small project and this is the way to do it:

```
.navDrawer {
  & .drawerContent {
    width: 12rem;
  }

  &.pinned {
    max-width: 12rem;
    width: 12rem;
  }
}
```

<img width="795" alt="screen shot 2016-10-03 at 20 45 31" src="https://cloud.githubusercontent.com/assets/905225/19049378/7a5b354c-89aa-11e6-8ed3-4341f6084656.png">
<img width="688" alt="screen shot 2016-10-03 at 20 45 41" src="https://cloud.githubusercontent.com/assets/905225/19049379/7a624f94-89aa-11e6-8a4c-22e43e7dc999.png">

**Comment by aislanmaia** [comment]
Thanks guys, for helping me and sorry for my delay. I can't get it to working until right now. @rubenmoya what the toolbox version you're using? Trying to import the media.css file and getting a not found error. And seems my css is not applying and it get overridden by the default css.

![navdrawer](https://cloud.githubusercontent.com/assets/2199137/20278686/6be1d0b6-aa84-11e6-974f-fccdb3fc363e.png)

**Comment by sai-prasanna** [comment]
@aislanmaia  Did you find how to override this? 

And how is this being done by the themer?, Why is it repeating class names if the overide fails?

**Comment by burakuluu** [comment]
@rubenmoya could you please explain more to customize navbar like you did? I mean, I added the styles you wrote into the theme.scss file and called it like;

```
        <NavDrawer active={this.state.drawerActive}
          pinned={this.state.drawerPinned} permanentAt='xxxl'
          onOverlayClick={this.toggleDrawerPinned}
          theme={theme}>
          <p>
            Navigation, account switcher, etc. go here.
          </p>
        </NavDrawer>
```

But my navbar still looks like this;

![image](https://cloud.githubusercontent.com/assets/25999821/25804504/c2d2eaae-3404-11e7-831d-f7811deeb49b.png)

I want to add columns like you did.

Thanks a lot!

**Comment by javivelasco** [comment]
ping @rubenmoya

**Comment by rubenmoya** [comment]
Uhm... not sure what it could be, can you inspect the element to see which classes/rules are applied?

**Comment by aislanmaia** [comment]
@sai-prasanna Sorry for the huge delay bro. Yeah, the classes are applied, but somehow my custom styles (size, padding, etc) don't. Actually I've give up on this and just used the Drawer not pinned. I'm using the Toolbox 1.3.3 version.

**Comment by KeizerDev** [comment]
You can overwrite it the way you want. Just use `.navDrawerDrawer` instead of `.navDrawer` like this:
```
.sidebarDrawer,
.navDrawerDrawer {
  background-color: red;
}
```
