### ISSUE TITLE
Contributing, Autocomplete Input on Change and DatePicker Dialog label

### ISSUE THREAD

**Issue by donnanicolas** [react-toolbox/react-toolbox#828]
First, thanks for such a great project. 

I was going to make a PR, but when running `npm install` on the repo (I made a fork) a lot of files are deleted, some edited and a double  `export default` error stops the processs (Issue #820).

So I open this issue, add some code here and if you give me hand setting up the repo I can make a PR.

The things I need are two:
- A way to interact with the Autocomplete Input onChange. I need to catch the onChange events to make queries to a server for a dynamic autocomplete
- A way to set up a label in the DatePicker dialog, I'm make a range filter and the end date picker pops up automatically, and it's a little confusing without a title.
- Also there is an issue when selecting years prior to 2016 in the datepicker.

I'll make additional comment with the code for each issue

PS: My english is a little rough, sorry 🙏

**Comment by donnanicolas** [comment]
Autocomplete Input onChange:


```
// components/autocomplete/Autocomplete.js
class Autocomplete extends Component {
   static propTypes = {
     // ...
     inputOnChange: PropTypes.func,
     // ...
  }

   // ...
   // Line #99
   handleQueryChange = (value) => {
     this.setState({query: value, showAllSuggestions: false}, () => {
       if (this.props.inputOnChange) {
          this.props.inputOnChange(value)
       }
     });
   };
```

The if can be removed by using *defaultProps*

**Comment by donnanicolas** [comment]
DatePicker Dialog Title

```
// components/date_picker/DatePickerDialog.js
class CalendarDialog extends Component {
   static propTypes = {
     // ...
     dialogTitle: PropTypes.string,
     // ...
  }

   // ...
   // Line #89
   render () {
      const { theme, dialogTitle } = this.props;
      // ...
      return (
        <Dialog
          // ...
        >
          <header className={headerClassName}>

            <!-- this line -->
            {dialogTitle && <h1 className={theme.dialogTitle}>{{dialogTitle}}</h1>}
            <!-- this line -->

            <span id='years' className={theme.year} onClick={this.handleSwitchDisplay}>
              {this.state.date.getFullYear()}
            </span>
            <h3 id='months' className={theme.date} onClick={this.handleSwitchDisplay}>
              {shortDayOfWeek}, {shortMonth} {date}
            </h3>
          </header>
```

I can't say for styling, since I play a lot with the repo, but maybe reduce the size of year and date in the header when it's present, or rearrange the parts

**Comment by donnanicolas** [comment]
When I get the repo up and running I can check the issue with the years

**Comment by javivelasco** [comment]
Hi @donnanicolas sorry it took me a while to answer, I had a lot of pending work.

What's the exact issue you're having setting up the project? Cloning, npm install and npm start should work. Maybe some dependency is screwing it up?
