### ISSUE TITLE
[docs] npm start hangs forever in webpack build [Windows]

### ISSUE THREAD

**Issue by NogsMPLS** [react-toolbox/react-toolbox#83]
Repo has some issues with wepack alias + sass loader on Windows machines at least.

See following sass-loader issues:

https://github.com/jtangelder/sass-loader/issues/149

https://github.com/jtangelder/sass-loader/issues/173

When running npm run build, I get file unreadable errors because of the alias not working correctly in sass-loader.

When running npm run start, the bundler never finishes. I can only get npm run start to work, if I remove alias in webpack. But then, obviously, the alias imports in sass don't work.

Just bringing awareness that There is a broken dependency currently in the project.

**Comment by javivelasco** [comment]
Great, thanks @NogsMPLS! Let's keep this open while the bug is resolved in sass loader. I think it's ok to keep it here so people can be aware of it, thanks for your help! :)

**Comment by NogsMPLS** [comment]
updating title of the issue to better reflect exact behavior happening

**Comment by javivelasco** [comment]
Nice! Thanks!

**Comment by NogsMPLS** [comment]
For reference, screenshot of webpack hanging:

![webpack-hangs](https://cloud.githubusercontent.com/assets/6899011/11158623/1b6f8186-8a1f-11e5-9f67-566e32a68138.PNG)

Hangs forever. I can leave and come back hours later and it will give me the ```webpack: wait until bundle finished: /``` warning anytime i try and go to localhost address.

Very frustrating bug as I can not get anything to throw an error or give any other messages.

I believe this is a Windows only thing, but I have not confirmed.

I'm assuming when someone does ```npm run start``` on OSX/Linux in docs, they are able to actually use the dev server that is created? Can someone confirm this?
