### ISSUE TITLE
Table column widths

### ISSUE THREAD

**Issue by mikeplus64** [react-toolbox/react-toolbox#830]
It'd be nice to be able to specify the widths of table columns. Maybe just allowing a `children` prop to Table that's just added before the table head and body, where you could have e.g. `<colgroup> ... </colgroup>`.

**Comment by mikeplus64** [comment]
For now a combination of className and hacky looking CSS using nth-child works

**Comment by q3452** [comment]
I introduced this in #832  which is awaiting approval from a Javi. #

**Comment by coljung** [comment]
I started to play with the table component and after trying unsuccessfully to tweak it to my needs, i ended up adding a 'fake' grid using http://roylee0704.github.io/react-flexbox-grid/

Then i simply imported the styles from the Table component and applied them to my custom grid.

**Comment by javivelasco** [comment]
Since there are too many issues with Table customization and it started looking like a monster, I've made a new implementation that it's going to be merged to #666 if there is no negative feedback. Please check and leave your opinion!

**Comment by mikeplus64** [comment]
Thanks! Great work @javivelasco
