### ISSUE TITLE
Checkbox: size of checkmark

### ISSUE THREAD

**Issue by mg** [react-toolbox/react-toolbox#833]
Hi,

attempting to change the size of the checkmark in the checkbox, but whatever I do (even changing height and width properties on the :after element in devtools) the size remains stubbornly at 11.1875px X 19.1875px

![image](https://cloud.githubusercontent.com/assets/1972/19020514/586cb55c-889a-11e6-92f2-ca58634ef09c.png)
Set the height to 5px, still is 19px

Any ideas how to change this?

cheers,
mg

**Comment by mg** [comment]
Managed to fix it with the following sledgehammer:

```
// theme.scss

.checked:after {
  transform: scale(0.6) rotate(45deg) !important;
  margin-left: -0.2rem;
  margin-top: -0.1rem;
}
```

Terrible, but works

**Comment by javivelasco** [comment]
You should never need to use important!. If you need to boost priority you can do it with just one level adding a className to the parent node and nesting one level in your theme. That should work too. Of course the size implementation is done with scale so it's not enough with changing just width. It happens the same with `Radio`
