### ISSUE TITLE
Dropdown changes incorrectly when jumping over the form inputs via pressing Tab key

### ISSUE THREAD

**Issue by ktaras** [react-toolbox/react-toolbox#836]
When you have a form with dropdown and you're tabbing through it the value of dropdown gets changed and returns a label-attribute, but not a value-attribute of source item.

Also mentioned here: https://github.com/react-toolbox/react-toolbox/issues/297#issuecomment-208665520

**Comment by L-u-k-e** [comment]
This is probably the result of this line: 

https://github.com/react-toolbox/react-toolbox/blob/dev/lib/dropdown/Dropdown.js#L214

What I'm doing now is just using my own template `template={(item) => <div>{item.label}</div>}`

Basically, this renders the component inaccessible, which is obv very bad, but it stops you from being able to tab through it at all.

**Comment by javivelasco** [comment]
This is fixed now. The `onChange` was spread to the internal `Input` element causing a call when it was focused. Now the `Dropdown` has its own focus and call onChange only when selection really changes. Still we pass the `value` to `Input` cause that's what we want to display. It's not semantic though but changing it takes some time and I plan to improve Dropdown very soon. Still more important work to do!

**Comment by javivelasco** [comment]
Check [276e891ac14e00b09c9fa844c63d27881f8cde14](https://github.com/react-toolbox/react-toolbox/commit/276e891ac14e00b09c9fa844c63d27881f8cde14)
