### ISSUE TITLE
MenuItem React Warning "Unknown prop `composeTheme`"

### ISSUE THREAD

**Issue by icd2k3** [react-toolbox/react-toolbox#841]
Just started using react-toolbox and so far loving it as an alternative to react-bootstrap which I was using previously.

I did just run into an issue, though, with a prop warning from React.

Seems like it could be related to https://github.com/react-toolbox/react-toolbox/issues/607 or https://github.com/react-toolbox/react-toolbox/issues/606. I'm getting this same error with MenuItem.

```
warning.js:36 Warning: Unknown prop `composeTheme` on <li> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in li (created by MenuItem)
    in MenuItem (created by RippledComponent)
    in RippledComponent (created by ThemedRippledComponent)
```

react: 15.3.1
react-toolbox: 1.2.1

Let me know if posting my source would be helpful. Any ideas for workarounds in the meantime?

**Comment by fgiroud** [comment]
I have the same warning here, 
The react-toolbox-example repository give the same warning.
Unfortunately I am a beginner so I can not really help.

node: v6.6.0
react: 15.3.0
toolbox: 1.2.1

**Comment by icd2k3** [comment]
Thanks @javivelasco 👍

**Comment by javivelasco** [comment]
No problem!!
