### ISSUE TITLE
CSS error in List component (css-next)

### ISSUE THREAD

**Issue by marcuscarrigan** [react-toolbox/react-toolbox#842]
There's a typo on line 11 in lib/list/config.css causing errors.

**Comment by rubenmoya** [comment]
I fixed it, as I had another pull request open (#837) it went into it :/

**Comment by javivelasco** [comment]
I think this is solved already!

**Comment by javivelasco** [comment]
Btw, there is a beta `2.0.0-beta.0` release :)
