### ISSUE TITLE
"support paypal" link on react-toolbox.com doesn't work

### ISSUE THREAD

**Issue by alltom** [react-toolbox/react-toolbox#85]
I get redirected to my account home.

**Comment by soyjavi** [comment]
hahaha.. funny.. for that reason maybe our account is 0 ;)

**Comment by javivelasco** [comment]
In Bratislava is not enabled and I couldn't verify :( 
Now it's fixed, many thanks for reporting it!!

**Comment by alltom** [comment]
Hopefully your account balance is fixed now, too. :)

**Comment by javivelasco** [comment]
Hahaha **hopefully** :dancer: 
Thanks @alltom :)
