### ISSUE TITLE
Link component usage

### ISSUE THREAD

**Issue by coljung** [react-toolbox/react-toolbox#858]
So i have a couple of questions regarding the Link component.

First, how do i set an active state for the current page. I know i can simply add 'active' as a property, but how can i change it when i switch pages ? Which brings me to my next question.

Should Link work as the Link component from react-router ? I noticed that while using react-toolbox Link comp, when i click on my navigation, a full page reload is made, even though im using child routes. I was wondering what i was doing wrong, and in one of my tests i simply switched the Link component for the one from react-router. Then my app began behaving like a  SPA.

Is there a setting for the Link component to treat links as a SPA ?

**Comment by javivelasco** [comment]
Yeah. In react-router a `Link` component has a `to` property that internally makes a push into the history. It's not a real redirect. Our `Link` implementation is nothing but a wrapper around an anchor. To behave the same as react-router you need to make the `Link` aware of context so it can access its API. In #851 you can find some helpful links.

The purpose of the `Link` component is to give a minimum style but it's actually a really really simple component. You can even get rid of it and use your own but the most important thing is the ability to make it composable. If its not we have to change its API

**Comment by borela** [comment]
Might be useful, I created a [package](https://github.com/borela/react-toolbox-plus-router) to interface with the v4 router.

**Comment by javivelasco** [comment]
Check [here](https://github.com/react-toolbox/react-toolbox/issues/984)
