### ISSUE TITLE
Create own css-module -less build

### ISSUE THREAD

**Issue by anri-asaturov** [react-toolbox/react-toolbox#861]
HI, I've never used css modules and, well, in current project I can't use webpack and therefore css-loader(but can use electron's native require). Is there any painless way to use awesome react-toolbox in my project? Like maybe fork it and compile all styles to final prefixed classes? Where should I look for answers to this?

**Comment by javivelasco** [comment]
Hi! I'm working on an approach where the only thing you need is to customize variables using future css custom properties. You will be able to provide styles using the context with a pre-defined css modules object. Still WIP, keep track of #666, I hope to have a approach ready in the next three days.

Meanwhile, it is still possible but you will need to compile the style some way. There is no example but it is hypothetically possible. Recall from the docs you can import components with/without style so you can either require a component that requires the CSS Module vs require a component that receives its CSS Module via `theme` property / context. You will have to setup your own theme object. The docs and [react-css-themr](http://github.com/javivelasco/react-css-themr) should give you enough info to set it up while I get done an example with 2.0.0 beta.

Please give some feedback through this issue!

**Comment by anri-asaturov** [comment]
I managed to compile scss to css with prefixed class names. Now figuring out how to provide them to react-toolbox.

**Comment by anri-asaturov** [comment]
This way, basically:
```npm install --save-dev postcss-cli postcss-modules
 ./node_modules/.bin/postcss -u postcss-modules ./node_modules/react-toolbox/components/button/theme.scss ```

**Comment by anri-asaturov** [comment]
Yeah, no this is too much :) I'll have to make some temporary webpack configuration.

**Comment by javivelasco** [comment]
Actually I have this working locally now 😂 Everything works fine, the only problem is that you need to include manually the CSS for each dependency but I guess it's a feature not a bug. Apart from that, we are going to ship from now on every CSS processed with everything but custom properties and color function plugins in #666. Wondering now what's the most painless way for consumers to process with css-next from their projects.

**Comment by anri-asaturov** [comment]
Ok, so i can just use css-next branch? Tell me if i can help with smth in there, it looks like we (Peerio) will use RT for our new desktop app, so I can officially spend some time contributing towards it ;)

**Comment by anri-asaturov** [comment]
TBH in my venture yesterday i did manage to make it work like this:
```
const postcss = require('postcss');
const modules = require('postcss-modules');
const path = require('path');
const fs = require('fs');
const cp = require('child_process');

function getJSONFromCssModules(cssFileName, json) {
    const cssName = path.basename(cssFileName, '.css');
    const jsonFileName = path.resolve('./build/', `${cssName}.json`);
    fs.writeFileSync(jsonFileName, JSON.stringify(json));
}

cp.spawnSync('./node_modules/.bin/node-sass ./node_modules/react-toolbox/components/button/theme.scss button.css');
const css = fs.readFileSync('button.css');
postcss([modules({ getJSON: getJSONFromCssModules })])
        .process(css, { from: 'button', to: 'build/button.css' })
        .then((result) => {
            fs.writeFileSync('build/button.css', result.css);
        });
```
then i included css and `require(.json)` passed it as `theme` property to button and verything works except ripple.

**Comment by javivelasco** [comment]
That sounds great, happy to hear!! I would suggest to jump into css-next branch since sass is definitively going to be deprecated. I'm going to push asap a new build step with `gulp` where I generate the theme modules for each component so they can be used to feed components from a `ThemeProvider` component at the top of the tree.

The only caveat (can't find a solution) is customization. It's not possible to remove every build step for consumers without killing theming. The best way to customize is obviously with the future css custom properties so we can build up everything but that. If you use react-toolbox in a recent browser it's going to work but still we need a build step to process custom variables into final css. The huge question is what's the most painless way to do so.

css-in-js doesn't look like an alternative unless we change the approach and forget about extracting CSS. This is not possible either because most people choose react-toolbox because of the styling technique (or that's what I believe...)

As I said, I'll try to push stuff asap to both css-next branch and the example repository. Feel free to ping through discord too

**Comment by anri-asaturov** [comment]
Well, I like react-toolbox because it's very well written, clean and clear code and it's not scary to fork it. And components look good visually and are performant, especially when you compare to alternatives.

As for customization, this is for developers, so I think it's totally fine to have a tool/script for that, a lot of the UI kits do that.

**Comment by anri-asaturov** [comment]
Do you have any idea why this might be happening: https://monosnap.com/file/Xdknr3qE9nte8goPoGq0zNQhIZocRo
?

**Comment by javivelasco** [comment]
Yeah, that's the ripple component but you need to include the styles for it too!
The size is happening because you need to import the commons.css stylesheet too

**Comment by anri-asaturov** [comment]
Thanks, works like a charm. There is a one detail though, for some reason, `icon` class from input theme conflicts and messes up button icons, if you remove it - buttons look good.

**Comment by anri-asaturov** [comment]
Btw, in case you're interested, I made it work with electron without webpack or css-modules.
1. Aggregate stylesheet `react-toolbox.css`
```
@import '../../node_modules/react-toolbox/lib/commons.css';
@import '../../node_modules/react-toolbox/lib/animations/slide-left.css';
@import '../../node_modules/react-toolbox/lib/animations/slide-right.css';
@import '../../node_modules/react-toolbox/lib/animations/zoom-in.css';
@import '../../node_modules/react-toolbox/lib/animations/zoom-out.css';
@import '../../node_modules/react-toolbox/lib/app_bar/theme.css';
@import '../../node_modules/react-toolbox/lib/autocomplete/theme.css';
@import '../../node_modules/react-toolbox/lib/avatar/theme.css';
and so on, all the other themes
```
2. compilation script
```
const postcss = require('postcss');
const modules = require('postcss-modules');
const path = require('path');
const fs = require('fs');
const cp = require('child_process');

function getJSONFromCssModules(cssFileName, json) {
    const cssName = path.basename(cssFileName, '.css');
    const jsonFileName = path.resolve('./build/', `${cssName}.json`);
    fs.writeFileSync(jsonFileName, JSON.stringify(json));
}

const css = fs.readFileSync('./src/styles/react-toolbox.css');
postcss([
    require('postcss-import')(),
    require('postcss-mixins')(),
    require('postcss-each')(),
    require('postcss-cssnext')(),
    modules({getJSON: getJSONFromCssModules}),
    require('precss')(),
    require('postcss-reporter')()
]).process(css, {
    from: './src/styles/react-toolbox.css',
    to: 'build/react-toolbox.css'
}).then((result) => {
    fs.writeFileSync('build/react-toolbox.css', result.css);
});
```
3. electron `require` hook (set in renderer thread before any `requires`): 
```
require.extensions['.css'] = function(m, f) { m.exports = require('./react-toolbox.json'); };
```
4. voila!

**Comment by javivelasco** [comment]
This is really nice and quite similar to what I'm doing in a separate branch. I'll update an example asap

**Comment by anri-asaturov** [comment]
I think i figured out why do i have style conflicts, since postcss-modules processes my aggregate file - hash is the same. I gotta process separate files and then join them.

**Comment by anri-asaturov** [comment]
Yup, that was it, now it's all amazing, thank you!

**Comment by javivelasco** [comment]
Great! Good work!

**Comment by anri-asaturov** [comment]
Will post my final script:

```
/* eslint-disable */
const postcss = require('postcss');
const modules = require('postcss-modules');
const path = require('path');
const fs = require('fs');
const cp = require('child_process');
var writeFile = require('writefile')

const src = './node_modules/react-toolbox/lib/';
const dst = './build/react-toolbox/';
function getJSONFromCssModules(cssFileName, json) {
    writeFile(`${cssFileName.substring(0, cssFileName.length - 4)}.json`, JSON.stringify(json));
}

function generateScopedName(name, fileName, css) {
    let file = path.basename(fileName, '.css');
    if(file === 'theme') file = ''; else file = '-'+file;
    let folder = path.basename(path.dirname(fileName));
    if(folder === 'lib') folder = ''; else folder = '-'+ folder;
    return 'rt'+folder+file+'-'+name;
}

function compile(file) {
    const css = fs.readFileSync(src + file);
    postcss([
        require('postcss-import')(),
        require('postcss-mixins')(),
        require('postcss-each')(),
        require('postcss-cssnext')({
            features: {
                customProperties: {
                    variables: {
                        'color-primary': 'var(--palette-indigo-500)',
                        'color-primary-dark': 'var(--palette-indigo-700)',
                        'color-primary-light': 'var(--palette-indigo-500)',
                        'color-accent': 'var(--palette-pink-a200)',
                        'color-accent-dark': 'var(--palette-pink-700)',
                        'color-primary-contrast': 'var(--color-dark-contrast)',
                        'color-accent-contrast': 'var(--color-dark-contrast)',
                        'animation-duration': '0.3s'
                    }
                }
            }
        }),
        modules({
            getJSON: getJSONFromCssModules,
            generateScopedName: generateScopedName, 
            scopeBehaviour : 'local'
        }), 
        require('precss')(), 
        require('postcss-reporter')()
]).process(css, {
    from: src + file,
    to: dst + file
}).then((result) => {
    return writeFile(dst + file, result.css);
});
}[
'commons.css',
'animations/slide-left.css',
'animations/slide-right.css',
'animations/zoom-in.css',
'animations/zoom-out.css',
'app_bar/theme.css',
'autocomplete/theme.css',
'avatar/theme.css',
'input/theme.css',
'button/theme.css',
'card/theme.css',
'checkbox/theme.css',
'chip/theme.css',
'date_picker/theme.css',
'dialog/theme.css',
'drawer/theme.css',
'dropdown/theme.css',
'layout/theme.css',
'link/theme.css',
'list/theme.css',
'menu/theme.css',
'navigation/theme.css',
'overlay/theme.css',
'progress_bar/theme.css',
'radio/theme.css',
'ripple/theme.css',
'slider/theme.css',
'snackbar/theme.css',
'switch/theme.css',
'table/theme.css',
'tabs/theme.css',
'time_picker/theme.css',
'tooltip/theme.css'
].forEach(f => compile(f));
```

In the end I generate scoped names without hashes, and use them to override css properties.

**Comment by javivelasco** [comment]
Thank you!
