### ISSUE TITLE
Error dropdown theme.required prop

### ISSUE THREAD

**Issue by diondirza** [react-toolbox/react-toolbox#867]
Just update my dep to version 1.2.3 and got this error when testing some of my component which using Dropdown component

`warning.js:36 Warning: Failed prop type: Invalid prop 'theme.required' of type 'string' supplied to 'Dropdown', expected 'boolean'`.
    `in Dropdown (created by ThemedDropdown)`

and my Markup almost same like in example page
`<Dropdown auto onChange={this.handleChange} source={countries} value={this.state.value} />`

how do i fix this issue?

**Comment by ferenc-radius** [comment]
I saw this issue to and I believe the change at this line 
https://github.com/react-toolbox/react-toolbox/blob/dev/components/dropdown/Dropdown.js#L34
should not be a boolean but a string (I tested version 1.2.2 and 1.2.3) and the bug introduced in version 1.2.3

I will create a pullrequest

**Comment by ashleyyang0610** [comment]
@javivelasco I met the same issue in my project. Whether this solution published in latest version? Thanks.

**Comment by javivelasco** [comment]
I'm releasing a patch just today or tomorrow, I need to check some other prs!

**Comment by bmatto** [comment]
@javivelasco any word on this? Thanks!

**Comment by fgiroud** [comment]
Release 1.2.4 solved this issue for me. Thank you

**Comment by zverev** [comment]
Still having this issue on 1.2.4 (Chrome 54.0.2840.71 (64-bit), react 15.3.2)

**Comment by mitalcoi** [comment]
Same error, 1.2.4 (React 15.3.2)

**Comment by javivelasco** [comment]
Just released a patch. Should work now!
