### ISSUE TITLE
sassLoader options to set theme do not work with webpack V2

### ISSUE THREAD

**Issue by nagarajay** [react-toolbox/react-toolbox#872]
In webpack V2 having sassLoader in the configuration webpack file is not allowed but it is allowed as a plugin webpack.LoaderOptionsPlugin. 

Not sure but even though the _theme.scss file is included in the bundle but the default _globals.scss file values take precedence.

I do have a working example where in webpack V1 things were working.

Any help is much appreciated.

**Comment by ne-spal** [comment]
That's how it works for us.
```
new webpack.LoaderOptionsPlugin({
    options: {
      context: __dirname,
      sassLoader: {
        data: '@import "theme/_config.scss";',
        includePaths: [__dirname + '/src'],
      },
    },
  })
```
But keep in mind the paths to your folders.

**Comment by nagarajay** [comment]
Thanks for sharing the same. I got it to work with Webpack2. Had created a repo to test it out also. 
Closing the Issue.
