### ISSUE TITLE
A new approach for Table

### ISSUE THREAD

**Issue by javivelasco** [react-toolbox/react-toolbox#880]
The `Table` component is not flexible enough. Some people might find useful to set a model to inline edit fields but the reality is that's really limited. It should be reimplemented following a different approach.

EDIT: Please check the PR or leave your feedback here!

**Comment by vmsoftware** [comment]
I was trying this before merge and I can say it's really nice implementation. Great work! @javivelasco

However I have some small questions/suggestions:

What's about responsive table? Maybe easy wrap the Table component into a div(for example), set horizontal scroll and define columns widths

What's the best way to handle múltiple sorted columns?

What do you think about a HOC called DATATABLE with págination, rows per page and header actions like MD spec?

What's happend with the old table implementation? I think it is very usefull too when we only need to show simple data.

**Comment by javivelasco** [comment]
Thank you @vmsoftware!! Finally I merged because there is nothing you cannot do with the new implementation although I agree the old one is useful for some cases.

1. I totally missed it. It's a good opportunity to do it so I'm going to add it. I'm going to implement it or if you want to PR it would be great. 
2. Not sure. I'd need to think about it but since the source it's outside the component and you control sorting it's out of the scope. Probably a solution could be to sort by one criteria as in the example and identify repeated elements. Then you can sort those groups by the second criteria and so on.
3. I think it could be cool and useful. I don't have too much time to keep digging on this because there are other priorities but rather than an HOC I'd follow the same implementation of a wrapper component. It could be interesting. Since the `Table` structure is fixed and predictable, you can actually navigate the components from a wrapper to figure out children. Then you can render only what corresponds to the pagination parameters. Maybe it's too obscure but I can't think on a better approach keeping the same customization level.
4. Removed. The editing is definitively not a good idea because it breaks the guidelines. Generating data is really easy just by mapping rows and cells. It's a breaking change but with an straightforward migration if you're not editing anything.

**Comment by vmsoftware** [comment]
@javivelasco, 

Of course I would like to contribute... Do you have any release date for 2.0.0?

I'm waiting for it and ready to work.
