### ISSUE TITLE
Autocomplete: Error selecting value

### ISSUE THREAD

**Issue by IGZangelsanchez** [react-toolbox/react-toolbox#883]
You can reply this error in the components page:
1 - Go to http://react-toolbox.com/#/components/autocomplete
2 - Click in the "Choose countries" Autocomplete
3 - Mouse over "Spain" option
4 - Write something like "italy" 
(Then the suggestion list dissapears)
5 - Press enter

The "Spain" option is added but the Autocomplete text input had a different value.

**Comment by igorbarbashin** [comment]
I experienced same bug. I thought that it was just not working with redux-form.
My temporary fix was to pass a no-op onBlur function to Autocomplete:
```jsx
<Autocomplete
  onBlur={() => {}}
/>
```

But yeah, looks like it's a bug introduced in latest releases

**Comment by igorbarbashin** [comment]
Should single Autocomplete have a clear button as in the Material Specification?

<img width="416" alt="screenshot 2016-10-20 11 25 18" src="https://cloud.githubusercontent.com/assets/1911427/19572662/1a3f36ca-96b8-11e6-946a-cc9f2a0b790c.png">
