### ISSUE TITLE
Default styling theme is not applying

### ISSUE THREAD

**Issue by iiitmanikanta** [react-toolbox/react-toolbox#884]
hi ..
i'm new to react toolbox..but i am unable to see any styling applied for the components.
$ npm install --save react-toolbox

here is my code
`import { Button } from "react-toolbox/lib/button/Button" `
`render () {`
` <Button label='Inbox' />`
`}`
config: 
     react 15.3.2
     webpack

am i need to add any extra configuration in webpack or something ??

**Comment by rubenmoya** [comment]
Try using `import Button from "react-toolbox/lib/button/Button"` or `import { Button } from "react-toolbox/lib/button"`

**Comment by javivelasco** [comment]
Take also into account that you need to configure in webpack css modules in case you are using styled components. An styled component requires a CSS module so your bundler should be able to do so. Check the [example repository](http://github.com/react-toolbox/react-toolbox-example) to see a working demo!
