### ISSUE TITLE
Multi-level menus (submenus)

### ISSUE THREAD

**Issue by Feex-s** [react-toolbox/react-toolbox#886]
How to create a multi-level menu (submenu)? Is there a ready-made solution?

![image](https://cloud.githubusercontent.com/assets/6947598/19601547/fbcc274e-97d3-11e6-8b4a-cace87a5207d.png)

**Comment by javivelasco** [comment]
I have this solved in a different project and I'm planning to refactor the menu so this is going to be really easy. It's planned, but not worthy to be done at the current dev branch.

**Comment by FranBacoSoft** [comment]
Hello, I wanted to know if this feature is currently possible. Thank you!

**Comment by javivelasco** [comment]
It's not possible yet but it will be. It's blocked until the postcss version is released

**Comment by javivelasco** [comment]
Closed in favor of #1169
