### ISSUE TITLE
FontItems with spaces in names do not appear

### ISSUE THREAD

**Issue by WellRedPandit** [react-toolbox/react-toolbox#89]
I am using [the font item corner of the playground](http://react-toolbox.com/#/components/font_icon). When I replace the sample values with, for example, `backspace` or `block`, the preview area below reflects them correctly, but when I use multi-word material icons (e.g. `add circle outline` or `font download` etc.) either as is with spaces or with underscores instead (`add_circle_outline` or `font_download`), they are missing from the preview area. I've also tried Unicode (`&#20;`), url (`%20`), slash space (`\ `) and other crazy ideas :-)

**Comment by javivelasco** [comment]
Oh! sorry, to keep consistency with the rest of the CSS we named spaces with dashes so instead of `add_circle_outline` you should use `add-circle-outline`. I'm going to add an example with a multi-word!

Do you think it might be better to use low dashes?

**Comment by WellRedPandit** [comment]
Many thanks!! 

Btw, purely FYI, I used underscores only because that's what [the material design site](https://www.google.com/design/icons/) uses, e.g.
![selection_044](https://cloud.githubusercontent.com/assets/3659381/11097752/0beea752-886f-11e5-9caa-0ae5beab2f8c.png)

**Comment by WellRedPandit** [comment]
Another btw :-) Excellent work! Learning a lot from your code.

**Comment by lycon2014** [comment]
can you shoot me an email regarding the font

**Comment by javivelasco** [comment]
Thanks @WellRedPandit, I'm very happy to read it!
@lycon2014 what do you mean??
