### ISSUE TITLE
Use squash to merge PRs

### ISSUE THREAD

**Issue by neerfri** [react-toolbox/react-toolbox#895]
Hi,

I was wondering if there's any reason why this repository is not using [github's new squash and merge](https://github.com/blog/2141-squash-your-commits) in the PRs.

I think this has a great advantage in the history it creates and makes it much easier for react-toolbox's users to track recent changes without the need to create a manual changelog.

Right now [toolbox's history](https://github.com/react-toolbox/react-toolbox/commits/dev) looks like this:
![image](https://cloud.githubusercontent.com/assets/21379/19637874/c2d5d48c-99d9-11e6-8fc3-b6bad9206679.png)
Which makes it hard to understand which commit belongs to which PR and to understand the single changes themselves (especially with the addition of the merge commits)

See for example [react's history](https://github.com/facebook/react/commits/master) (they switched recently)
![image](https://cloud.githubusercontent.com/assets/21379/19638406/7a7333b2-99dc-11e6-9b06-1d65152791ba.png)

P.S.
You can disable the normal merge behavior in [the repo settings](https://github.com/react-toolbox/react-toolbox/settings) to make it easier to not forget ;-)

**Comment by neerfri** [comment]
I forgot to mention that the normal argument of "but I want to know the full history of commits" is easily solved here since you can always go to the PR's page and see the original commits and restore the original branch if needed.

**Comment by javivelasco** [comment]
I definitively need to improve my git skills! I'd take a look at the link and try to make it cleaner, sometimes I forget how important is to keep a clean history for people using the project. Thanks for telling :)

**Comment by jagged3dge** [comment]
Well, IMO, it's either that, or keep the CHANGELOG.md file manually updated on every release. Probably both.

**Comment by javivelasco** [comment]
I'm doing this now, and also I plan to write detailed Changelogs with each release!
