### ISSUE TITLE
Table does not render checkbox and number picker

### ISSUE THREAD

**Issue by thomasthiebaud** [react-toolbox/react-toolbox#897]
I have this component 

```
import { Table } from 'react-toolbox'

export class RecordTable extends React.Component {
  componentWillMount () {
    this.props.getRecords()
  }

  render () {
    return (
      <Table
        model={this.props.model}
        source={this.props.records}
        selectable={false}
      />
    )
  }
}
```

With this model 

```
{ 
  date: { type: Date }, 
  test: { type: String },
  number: { type: Number },
  boolean: { type: Boolean}
}
```

the output table looks like 

![table](https://cloud.githubusercontent.com/assets/3715715/19717107/59ac7010-9b5f-11e6-8e03-92c9c0a4f660.png)

As you can see the number picker is not rendered in the Number column and the checkbox is not rendered in the Boolean column.

**Comment by rubenmoya** [comment]
Seems like you have to use the `onChange` prop in the table to make it editable so they can render. Documentation about `onChange`:

> Callback function that is fired when an item in a row changes. If set, rows are editable.

**Comment by thomasthiebaud** [comment]
👍
