### ISSUE TITLE
Don't publish generated sources to the repository

### ISSUE THREAD

**Issue by okonet** [react-toolbox/react-toolbox#898]
You have `.npmignore` in place that will `/lib` into the `tar.gz` when publishing. Is there another reason you publish `/lib` on github?

**Comment by javivelasco** [comment]
Yeah, somebody asked for it because there is no pre-defined release cycle. This way people can add the repository in the package and use the dev branch if they want. If theres another way that allows leaving the `lib` folder outside the repo, I'm in!

**Comment by okonet** [comment]
You could add a `postinstall` script that would build a dust if it doesn't exist I think. But i believe that if people install from GitHub it should be their responsibility to make a build. But it's your call of course.

**Comment by javivelasco** [comment]
Yeah actually it's making the project more difficult to maintain. I'm removing it because probably there is not that many people using it anyway.
