### ISSUE TITLE
Icon common deconstructions

### ISSUE THREAD

**Issue by javivelasco** [react-toolbox/react-toolbox#91]
It could be cool to create some components for common icon transformations. An example can be the hamburger icon used to open a drawer in mobile. Here is a resource about the topic:

http://cloudcannon.com/deconstructions/2014/12/05/material-design-delightful-details.html

With enough people interested we can plan it to do it soon.

**Comment by vmsoftware** [comment]
@javivelasco Finally was discarded?

**Comment by javivelasco** [comment]
I'm was going to add it to the Issue as a future component but forgot to do so!! :S

**Comment by javivelasco** [comment]
I'm closing because this is something that can be done in another lib/module...
