### ISSUE TITLE
No class names in elements with react-redux-starter-kit

### ISSUE THREAD

**Issue by apaatsio** [react-toolbox/react-toolbox#911]
I'm trying to get react-toolbox to work with the react-redux-starter-kit. The CSS is loaded in the browser but the elements don't have any class names. What am I missing?

Here are the changes I have made to react-redux-starter-kit: https://github.com/apaatsio/react-redux-starter-kit/commit/0b172cf8511812030f11f7bb6dba8b50cd72ed4c

I see in web inspector that the styles are loaded:
![react-toolbox - css loaded](https://cloud.githubusercontent.com/assets/195210/19838275/5d76bb92-9ed4-11e6-98d1-a2dc427be46a.png)

The elements don't have class names:
![react-toolbox - no class names](https://cloud.githubusercontent.com/assets/195210/19838277/6abfda54-9ed4-11e6-82e9-bb37c54858c8.png)

How elements look in browser:
![react-toolbox - no styles](https://cloud.githubusercontent.com/assets/195210/19838280/77b7ecec-9ed4-11e6-840f-a37d7bb6e008.png)

**Comment by rubenmoya** [comment]
Hi! I had a look at the project and found a few things:

If you load `{ Button }` from button directly it will be unstyled, so better use this import:

`import { Button, Chip } from 'react-toolbox'`

Then, the second problem I found was with the loaders for sass, you have to use css-modules, changing it to this works, but maybe you want to play around and make it work with the `BASE_CSS_LOADER` constant.

```
webpackConfig.module.loaders.push({
  test    : /\.scss$/,
  exclude : null,
  loaders : [
    'style',
    'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass'
  ]
})
```

After that, you have to add `import 'react-toolbox/lib/commons.scss'` somewhere in the project, I recommend you to do it in the main component so it applies to the entire application.

I hope this solves your problem!

**Comment by apaatsio** [comment]
Thank you very much @rubenmoya!

It's working now. Here's the updated working version https://github.com/apaatsio/react-redux-starter-kit/commit/414f9827ea431698c93211596881aa17d22ec98b

BTW, I can't find this `import { Button } from 'react-toolbox'` documented anywhere. Not in the docs or the example project. What's the difference to `import { Button } from 'react-toolbox/lib/button'`?

**Comment by rubenmoya** [comment]
If you import from the index.js it doesn't matter if you import from default `import Button from 'react-toolbox/lib/button'` or the named `import { Button } from 'react-toolbox/lib/button'` because both export the ThemedButton, you can check it [here](https://github.com/react-toolbox/react-toolbox/blob/dev/components/button/index.js)

In the other hand, if you import from `react-toolbox/lib/button/button` with the named `{ Button }` you will load the button without theme, with the default, it goes through Themr, but as far as I know right now it doesn't do anything (in the future it will apply a default theme I think).

I hope I made myself clear!

**Comment by apaatsio** [comment]
Thank you, I understood. But that wasn't actually what I asked. I asked what's the difference between `import { Button } from 'react-toolbox'` and `import { Button } from 'react-toolbox/lib/button'`.

But I already checked and it seems that there is no difference, since https://github.com/react-toolbox/react-toolbox/blob/dev/index.d.ts is just a thin wrapper for the components.

It seems odd to me that all code examples use the "long format", e.g.

```javascript
import Navigation from 'react-toolbox/lib/navigation';
import Link from 'react-toolbox/lib/link';
```

when it would be simpler to just say

```javascript
import { Navigation, Link } from 'react-toolbox';
```

**Comment by javivelasco** [comment]
@apaatsio The difference is that if you import directly from 'react-toolbox' your module bundler will require every file imported by the `index.js`. In node apps it's not that important but for frontend this means your bundler will output in your final JS every component even if it's not used so it will increment the bundle size.

**Comment by apaatsio** [comment]
Thanks @javivelasco! That was really helpful and makes sense :)

**Comment by junibrosas** [comment]
@apaatsio @rubenmoya Thanks guys! I spent 4 hours trying to figure out what went wrong. I also noticed that the button tag has no class. I basically followed @apaatsio change commit then applied @javivelasco advice to load needed components only. Glad I found this.

`import Navigation from 'react-toolbox/lib/navigation';`
