### ISSUE TITLE
Error: Please check the code for the ActivableRenderer component.

### ISSUE THREAD

**Issue by chiester** [react-toolbox/react-toolbox#915]
Error: 

Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ActivableRenderer component.

How do I track this down?

**Comment by rubenmoya** [comment]
It's hard to know what's going on without more information, but this happens when you call a function that changes the state in the render method, for example, doing `onClick={this.handleClick()}` instead of `onClick={this.handleClick}`. Not sure if it's react-toolbox related to be honest.
