### ISSUE TITLE
Snackbar icon

### ISSUE THREAD

**Issue by MarcoWorms** [react-toolbox/react-toolbox#918]
According to Material Design guidelines snackbars can't have icons https://material.google.com/components/snackbars-toasts.html#snackbars-toasts-usage

`Snackbars should contain a single line of text directly related to the operation performed. They may contain a text action. They cannot contain icons.`

The main example of snackbar usage has an icon http://react-toolbox.com/#/components/snackbar

I could PR this but maybe you guys don't wanna change that :)

**Comment by anri-asaturov** [comment]
Wow, aren't you a purist.

**Comment by rubenmoya** [comment]
Well, the spec is the spec, I'll open a PR soon :)

**Comment by MarcoWorms** [comment]
Thanks man!
