### ISSUE TITLE
Expired Domain

### ISSUE THREAD

**Issue by hassa** [react-toolbox/react-toolbox#921]
Looks like http://www.react-toolbox.com/ has expired?

I see a generic expired domain page when I try to go there.

![screenshot](https://cloud.githubusercontent.com/assets/425229/19885607/733fb746-a017-11e6-9724-7f3375512f1e.png)

**Comment by asifalikhokhar** [comment]
+1
It's troubling for more than 1 hour :-(

**Comment by mosaice** [comment]
anyone find out ip address?

**Comment by rubenmoya** [comment]
Nop, but one alternative is cloning the project,  `cd docs`, `npm install` and `npm start`.

**Comment by Raathigesh** [comment]
Tried to build the docs but there were few webpack errors. Just cone the **gh-pages** branch and serve it through [http-server](https://www.npmjs.com/package/http-server).

**Comment by david-cho-lerat-HL2** [comment]
About the webpack errors : I had to `npm install immutability-helper`, and then it worked for me.

**Comment by javivelasco** [comment]
I need to reach @soyjavi who owns is at the moment. Meanwhile you can use the http-server cloning gh-pages branch.

**Comment by Mythli** [comment]
You can use http://rt.mythli.net if you want.

**Comment by javivelasco** [comment]
You can use https://react-toolbox.github.io/react-toolbox/ meanwhile

**Comment by javivelasco** [comment]
Now it's up again!

**Comment by david-cho-lerat-HL2** [comment]
seems like it's gone again ?

**Comment by rubenmoya** [comment]
It's working for me

**Comment by david-cho-lerat-HL2** [comment]
The site no longer says the domain name has expired, but it still shows the "generic" page for me (I've emptied my cache, though). It might not be ready for everybody yet depending on the geographic location ?

**Comment by david-cho-lerat-HL2** [comment]
![image](https://cloud.githubusercontent.com/assets/19814268/19921937/8bb83518-a0e0-11e6-83cb-e12f72b138d2.png)

**Comment by rubenmoya** [comment]
Have you tried a dns flush?

**Comment by david-cho-lerat-HL2** [comment]
It's working now, thanks.
