### ISSUE TITLE
The http://react-toolbox.com/ is not working

### ISSUE THREAD

**Issue by pravin-d** [react-toolbox/react-toolbox#923]
This seems like a very good lib for developers especially coming from a bootstrap background. Could you please host the components maybe as gh page with a different URL?? The home page given above in the title has been deleted I guess

**Comment by faergeek** [comment]
Domain is expired :-(

**Comment by pravin-d** [comment]
Yup.. is it not possible to host github.com ? (I'm not realy sure how gh pages work)

**Comment by faergeek** [comment]
It's actually hosted on http://react-toolbox.github.io/react-toolbox/

Sadly it redirects from there to expired domain. One way to see it is to clone the repo and checkout `gh-pages` branch

**Comment by pravin-d** [comment]
ok will give it a go.. thanks man.. but this needs to be fixed I guess.. doesn't look good given that it is a lib for building websites :)

**Comment by faergeek** [comment]
@pravin-d after you clone this repo, you can install `serve` package from npm and just run `serve`, then open http://localhost:3000/

**Comment by faergeek** [comment]
@pravin-d 
>but this needs to be fixed I guess

I am not from react-toolbox team, so I can't fix it, sorry :-(

**Comment by pravin-d** [comment]
Oh.. sorry dude.. 
Anyways tried your suggestion. I'm able to see the components.. Thanks

**Comment by javivelasco** [comment]
You can use https://react-toolbox.github.io/react-toolbox/#/components meanwhile
