### ISSUE TITLE
Domain was not renewed

### ISSUE THREAD

**Issue by DevAlien** [react-toolbox/react-toolbox#924]
Hey, I pinged @javivelasco on twitter for this, but better open an issue with this.

http://react-toolbox.com domain name was not renewed.

**Comment by DevAlien** [comment]
Ok, apparently the docs are here: http://react-toolbox.github.io/react-toolbox/

**Comment by gregegan** [comment]
I tried to buy it back for you guys! but not available

**Comment by Bandit** [comment]
Uh oh spaghetti-oh

**Comment by ngoctranfire** [comment]
hmmm... weird...

**Comment by javivelasco** [comment]
Up

**Comment by miguel-orange** [comment]
@javivelasco,
Both links aren't working for me today.

**Comment by miguel-orange** [comment]
@javivelasco,
This was working for me again this morning, however is not now.

**Comment by javivelasco** [comment]
It should be a local issue. It's working for me!
