### ISSUE TITLE
What is happening to react-toolbox.com ?

### ISSUE THREAD

**Issue by antoinejaussoin** [react-toolbox/react-toolbox#927]
Seems your website was either hijacked, or you forgot to renew your domain?

[http://react-toolbox.com/](http://react-toolbox.com/) returns a grey page with keywords such as "cash advance debt consolidation insurance react-toolbox.com"...

**Comment by rubenmoya** [comment]
A dns flush should fix it

**Comment by antoinejaussoin** [comment]
Cool thanks.
I did a dns flush on my machine, but it doesn't work, probably because I'm on a corporate network that has its own cache.

I tried accessing the website at home, and it's working ok, so the issue is indeed caused by my crappy corporate network.

We might want to leave this issue open for a few days though, as I'm surely not the only one facing this issue within a corporate environment.

Thanks!
