### ISSUE TITLE
Is there a Grid component ?

### ISSUE THREAD

**Issue by thomasthiebaud** [react-toolbox/react-toolbox#928]
Is there a Grid component like the one from [mdl](https://react-mdl.github.io/react-mdl/components/grid/) or [materialize](https://react-materialize.github.io/grid.html) ? 

Is it planned to add it for version 2 ?

**Comment by javivelasco** [comment]
It is planned to work on more components as soon as we release a new version with a better approach regarding styling. It's also detailed here: #626 so I'm closing this issue
