### ISSUE TITLE
Problems with webpack workflow

### ISSUE THREAD

**Issue by borillo** [react-toolbox/react-toolbox#93]
Hi guys,

First of all, thanks a lot for such a great work!!

Let me describe the process that i have followed. I'm sure that i'm missing something important :(

    $ node -v
    v5.0.0
    
    $ git clone https://github.com/gaearon/react-hot-boilerplate.git
    $ cd react-hot-boilerplate
    $ npm install
    $ npm install --save react-toolbox
    $ webpack

At this point. All is fine!!

Then, i have modified the App.js file that is available in de "src" directory. This is the result:

    import React, { Component } from 'react';
    import Button from 'react-toolbox/lib/button';
    
    export default class App extends Component {
      render() {
        return (
          <div>
            <h1>Hello, world.</h1>
            <Button label="Hello world" kind="raised" accent />
          </div>
        );
      }
    }

Let's pack again!!:

    $ webpack
    Hash: d98a5668fea2ed782153
    Version: webpack 1.12.4
    Time: 908ms
        Asset     Size  Chunks             Chunk Names
    bundle.js  1.02 MB       0  [emitted]  main
       [0] multi main 52 bytes {0} [built]
        + 238 hidden modules
    
    ERROR in ./~/react-toolbox/lib/button/index.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ./style in /tmp/react-hot-boilerplate/node_modules/react-toolbox/lib/button
     @ ./~/react-toolbox/lib/button/index.js 37:13-31
    
    ERROR in ./~/react-toolbox/lib/font_icon/index.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ./style in /tmp/react-hot-boilerplate/node_modules/react-toolbox/lib/font_icon
     @ ./~/react-toolbox/lib/font_icon/index.js 15:13-31
    
    ERROR in ./~/react-toolbox/lib/ripple/index.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ./style in /tmp/react-hot-boilerplate/node_modules/react-toolbox/lib/ripple
     @ ./~/react-toolbox/lib/ripple/index.js 25:13-31
    
    ERROR in ./~/react-toolbox/lib/tooltip/index.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ./style in /tmp/react-hot-boilerplate/node_modules/react-toolbox/lib/tooltip
     @ ./~/react-toolbox/lib/tooltip/index.js 25:13-31

I also tried to import the Button with the following definition with the same result:

    import { Button } from 'react-toolbox';

My package.json is:

    {
      "name": "react-hot-boilerplate",
      "version": "1.0.0",
      "description": "Boilerplate for ReactJS project with hot code reloading",
      "scripts": {
        "start": "node server.js",
        "lint": "eslint src"
      },
      "repository": {
        "type": "git",
        "url": "https://github.com/gaearon/react-hot-boilerplate.git"
      },
      "keywords": [
        "react",
        "reactjs",
        "boilerplate",
        "hot",
        "reload",
        "hmr",
        "live",
        "edit",
        "webpack"
      ],
      "author": "Dan Abramov <dan.abramov@me.com> (http://github.com/gaearon)",
      "license": "MIT",
      "bugs": {
        "url": "https://github.com/gaearon/react-hot-boilerplate/issues"
      },
      "homepage": "https://github.com/gaearon/react-hot-boilerplate",
      "devDependencies": {
        "babel-core": "^6.0.20",
        "babel-eslint": "^4.1.3",
        "babel-loader": "^6.0.1",
        "babel-preset-es2015": "^6.0.15",
        "babel-preset-react": "^6.0.15",
        "babel-preset-stage-0": "^6.0.15",
        "eslint-plugin-react": "^3.6.2",
        "react-hot-loader": "^1.3.0",
        "webpack": "^1.12.2",
        "webpack-dev-server": "^1.12.1"
      },
      "dependencies": {
        "react": "^0.14.0",
        "react-dom": "^0.14.0",
        "react-toolbox": "^0.11.4"
      }
    }

Thanks a lot for your help!!

**Comment by danmartinez101** [comment]
Here is a diff of the minimal changes that I had to make in order to get this working.

The dev-deps might look slightly different if you are using npm v2 or prior but the major thing is the webpack config.

I really thing that this should be prebuilt by default because putting this burden of knowledge on adopters makes it kind of hard to get started and sets a high barrier to entry when someone is just initially trying to evaluate the library initially. (but I'll create a separate issue about that.)
```
Daniels-MacBook-Pro:miser maverick$ git diff 
diff --git a/package.json b/package.json
index b0599e3..64ebf69 100644
--- a/package.json
+++ b/package.json
@@ -21,5 +21,17 @@
     "webpack": "^1.12.2",
     "webpack-dev-middleware": "^1.2.0",
     "webpack-hot-middleware": "^2.4.1"
+  },
+  "devDependencies": {
+    "css-loader": "^0.22.0",
+    "node-sass": "^3.4.1",
+    "normalize.css": "^3.0.3",
+    "react": "^0.14.2",
+    "react-addons-css-transition-group": "^0.14.2",
+    "react-addons-test-utils": "^0.14.2",
+    "react-dom": "^0.14.2",
+    "react-toolbox": "^0.11.4",
+    "sass-loader": "^3.1.1",
+    "style-loader": "^0.13.0"
   }
 }
diff --git a/webpack.development.js b/webpack.development.js
index 294433a..82c8d56 100644
--- a/webpack.development.js
+++ b/webpack.development.js
@@ -29,9 +29,20 @@ module.exports = {
     new Webpack.HotModuleReplacementPlugin(),
     new Webpack.NoErrorsPlugin()
   ],
+  resolve: {
+    extensions: ['', '.jsx', '.scss', '.js', '.json']
+  },
   module: {
     loaders: [
       {
+        test: /(\.scss|\.css)$/,
+        loaders: [
+          require.resolve('style-loader'),
+          require.resolve('css-loader') + '?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]',
+          require.resolve('sass-loader') + '?sourceMap'
+        ]
+      },
+      {
         test: /\.js$/,
         loader: require.resolve('babel-loader'),
         exclude: /node_modules/,
Daniels-MacBook-Pro:miser maverick$ 
```

**Comment by borillo** [comment]
Thx a lot!! I was missing all the SCSS processing :(
Grrrrr

**Comment by vinz243** [comment]
@danmartinez101 Where is `webpack.development.js` please? Can't find it anywhere.

**Comment by javivelasco** [comment]
@vinz243 Try https://github.com/react-toolbox/react-toolbox-example!

**Comment by danmartinez101** [comment]
@vinz243 I created https://github.com/danmartinez101/miser for my react/webpack flow.

The example provided by @javivelasco might be better as an example though since miser is pretty hardcoded to my conventions

**Comment by vinz243** [comment]
@javivelasco  Awesome thanks dude !!

**Comment by javivelasco** [comment]
No problem!! :)
