### ISSUE TITLE
Custom theme not working for NavDrawer

### ISSUE THREAD

**Issue by thomasthiebaud** [react-toolbox/react-toolbox#931]
I'm trying to create a custom theme for a `NavDrawer` (inside a `Layout`).

Here is my theme 

**NavDrawer.scss**

```
.drawerContent {
    background-color: #38474F !important;
    box-shadow: none !important;
    border: none !important;
}
```

and I'm trying to apply it using 

```
import theme from './NavDrawer.scss'

<Layout>
    <NavDrawer theme={theme} pinned >
    </NavDrawer>
</Layout>
```

But nothing happened. Is it normal ? I'm using css modules into my app also, so I was thinking about a conflict.

**Comment by rubenmoya** [comment]
Hi! Check #914 it was the same problem

**Comment by thomasthiebaud** [comment]
Awsome ;) thanks a lot. Maybe it can be put into the [doc](https://github.com/react-toolbox/react-toolbox/tree/dev/components/layout)
