### ISSUE TITLE
Move to airbnb-eslint-config

### ISSUE THREAD

**Issue by javivelasco** [react-toolbox/react-toolbox#932]
I would like to drop the custom eslint config in favor of [airbnb eslint config](https://www.npmjs.com/package/eslint-config-airbnb). It should only take JS changes and it's going to be easy to merge with #666. Also it would remove discouraged bind syntax so I'm closing #652 in favor of this. Other goodies would come with this migration like, for example, the `ref` syntax.

**Comment by carlitux** [comment]
@javivelasco I can help this one, on which branch?

**Comment by wtgtybhertgeghgtwtg** [comment]
Are you going to include `react/jsx-filename-extension` or overwrite it?

**Comment by javivelasco** [comment]
@wtgtybhertgeghgtwtg I'd rather keep JS files. @carlitux we can do it in dev and then merge to PostCSS. The JS code is the same, it only generates conflicts with styles and a couple of components that are changed.

**Comment by carlitux** [comment]
@javivelasco cool, do we follow all rules as airbnb or do you prefer change something?

**Comment by carlitux** [comment]
import/extension force us remove extension on imports.

Also here if you want to keep space before ( we need to change the rule

`js
componentDidMount () {  // space-before-function-paren
      if (this.props.scrollHide) {
        this.initializeScroll();
      }
    }

`

**Comment by rubenmoya** [comment]
@carlitux check this out, because maybe we're both doing the same changes https://github.com/rubenmoya/react-toolbox/commit/9c54525c8c3a6c6bb5ff687879776faa9422e5c0

I've already removed most of the errors with the .js extensions, trailing commas and space before function parenthesis

**Comment by wtgtybhertgeghgtwtg** [comment]
On the subject of proptypes, would this be a good time to consider moving to flow?

**Comment by javivelasco** [comment]
It would be perfect, but I have no experience at all. Good moment to start with it :)

**Comment by therealparmesh** [comment]
Big fan!

**Comment by kjg531** [comment]
+1 on Flow!! Thank you for all the work you guys put in. If the ball ever gets rolling on flow, I would be glad to contribute.

**Comment by rubenmoya** [comment]
This has been done in #1180 right? Maybe we should close it and open a new issue for the Flow integration
