### ISSUE TITLE
Add "export" to Props interface definition in all component index.d.ts files

### ISSUE THREAD

**Issue by uds** [react-toolbox/react-toolbox#935]
Having standard Props interface defined as private makes it impossible to reuse the Props definition when creating your own custom version of the component.

**Comment by javivelasco** [comment]
Anybody helping with this?

**Comment by nidu** [comment]
Is anybody doing it? I'd like to slightly extend some components in my app and reusing existing props would be very convenient.

This sounds quite simple. Just exporting props won't break anything and actually we're not exposing more than already exposed because Props are a part of API

**Comment by javivelasco** [comment]
Not that I know @nidu!
