### ISSUE TITLE
Optgroup feature

### ISSUE THREAD

**Issue by mitalcoi** [react-toolbox/react-toolbox#938]
Is it possible to realize <optgroup> feature in Dropdown or Autocomplete component with react-toolbox?

**Comment by javivelasco** [comment]
It will come with a future version. I have another `Dropdown` implementation when this is done but it's blocked until the PostCSS version is officially out.

**Comment by liokm** [comment]
Would be great to have this one. Currently we are extending unthemed `Autocomplete`, kicking in groups in `renderSuggestions()` and wrapping theme.

**Comment by javivelasco** [comment]
Closed in favor of #1030

**Comment by liokm** [comment]
I might be wrong but seems #1030 is a different one?

**Comment by javivelasco** [comment]
I meant #1169 😅
