### ISSUE TITLE
Tabs: index.d.ts -> TabsProps interface missing members

### ISSUE THREAD

**Issue by sjroe** [react-toolbox/react-toolbox#939]
Requires the following to allow use of `inverse` and `fixed` with Typescript:

```
interface TabsProps extends ReactToolbox.Props {
...
    inverse?: boolean;
    fixed?: boolean;
...
}
```

**Comment by anotherpit** [comment]
#952 adds `inverse`. Still misses `fixed`, though.

**Comment by anotherpit** [comment]
@sjroe, FYI, I used to cheat TS compilation using spread operator: `<Tabs {...{inverse: true, fixed: true}}>...</Tabs>`. Yeah, ugly, but works.

**Comment by sjroe** [comment]
@anotherpit Thanks for the idea of using the spread operator...yeah it's not pretty but it's a good interim solution.

**Comment by anotherpit** [comment]
@javivelasco How do you close the issue, when the `fixed` prop is still missing in TS declarations?

**Comment by javivelasco** [comment]
Sorry, forgot to push
