### ISSUE TITLE
Slider with step over 1 does not increment correctly

### ISSUE THREAD

**Issue by samhagan** [react-toolbox/react-toolbox#942]
When using the slider, step values over 1 do not change the amount that the slider increments -- it remains at 1. This issue can be reproduced in the playground (http://react-toolbox.com/#/components/slider) by changing the step for slider3.

**Comment by rubenmoya** [comment]
I've been having a look into the code, and it seems that the steps are only used when using the keyboard by adding/subtracting the step to the value.

Basically it's not implemented, or I didn't find it in the code.

**Comment by samhagan** [comment]
@rubenmoya: thanks for taking a look.  I will work to implement.
