### ISSUE TITLE
Ripple effect only occurs on circle part of RadioButton

### ISSUE THREAD

**Issue by alexhisen** [react-toolbox/react-toolbox#945]
Although the entire RadioButton component (i.e. the circle and the label text) can be clicked/tapped, only taps on the circle part result in the ripple effect.

**Comment by javivelasco** [comment]
Thanks for reporting but this is expected behavior :)

**Comment by alexhisen** [comment]
It's not a particularly good UX. The ripple is meant to indicate to the user that their tap has been recognized, that they didn't miss the tap area. As implemented currently, tapping outside the radio circle still has the same effect as tapping the circle, but is not indicated as such to the user.  It's equivalent to only showing a different cursor on hover over just the circle instead of the whole clickable label.

**Comment by javivelasco** [comment]
I know, but every implementation from Google works like that. Check [here](https://elements.polymer-project.org/elements/paper-radio-button?view=demo:demo/index.html) and [here](https://material.google.com/components/selection-controls.html#selection-controls-radio-button). Anyway if you want to change it's possible. There is an exposed ripple decorator you can use to create a custom `radio` where the label is covered by the ripple too!
