### ISSUE TITLE
Card versatility and customization

### ISSUE THREAD

**Issue by nathanmarks** [react-toolbox/react-toolbox#95]
According to examples in the official spec, cards are actually much more flexible and versatile than this library currently allows.

Is this an area you would like to improve? And if so, do you have any opinions on how you would like to organize the separate card components (needed for flexibility). It's something I may want to contribute to depending on your thoughts here.

**Edit:** Leaving this here for reference: https://www.google.com/design/spec/components/cards.html

**Comment by javivelasco** [comment]
Of course. This is a first release with a lot of stuff to improve, specially moving state out of components (something in progress), adding more callback props, etc. Cards are one of the components with more improvements coming. We should go through the spec and create separate subcomponents with their own style to create a card by aggregating them. The idea is to do something similar to the `List`.

A lot of work to do without being my main project, be patient :smile: 
Thanks!

**Comment by nathanmarks** [comment]
@javivelasco TOTALLY understand.

Are you accepting contributions currently?

**Comment by javivelasco** [comment]
Sure, I still have to write the contribution guide but following a similar style to components already developed there would be no problem to accept any contribution. There are already linter configuration for sass and javascript files. Also it's important for me to style giving classes and keeping the markup at a minimum being semantic where possible, etc.

And if there are stuff that I don't agree we can always speak about it and learn all together. That's the best part of open source :smile: !!

**Comment by nathanmarks** [comment]
Cool! What branch should people work off? Master?

**Comment by javivelasco** [comment]
For now I'm try to keep all progress in master since the package is not fully released yet. So yes, master! :)

**Comment by EnzoMartin** [comment]
This would be great, I'm also finding myself needing to use cards as a container element to get a nice box with dropshadow, etc. around my content, though I'm wanting something more along the lines of http://material-ui.com/#/components/paper

**Comment by nathanmarks** [comment]
@EnzoMartin I'm thinking that maybe cards could be built on top of a component called `<Whiteframe>` https://www.google.com/design/spec/layout/structure.html#structure-whiteframes

Then the `Whiteframe` component can be used by anyone for anything

**Comment by EnzoMartin** [comment]
Sounds good, that's essentially what I'm wanting to use it for, a container box that can be any combination of width/height

**Comment by nathanmarks** [comment]
@EnzoMartin Even if something like a whiteframe isn't added, you can always use the new card coming up as a "blank" card. OR you can just use one of the SCSS mixins in the library:

```
background-color: #fff;
border-radius: 2px;
@include shadow-2dp();
```

Is a card basically

**Comment by sloria** [comment]
It would be great to see `Card` support subcomponents. I think material-ui handles it quite nicely:

From their docs:  http://material-ui.com/#/components/cards

```jsx
<Card>
  <CardHeader
    title="Title"
    subtitle="Subtitle"
    avatar={<Avatar>A</Avatar>}/>
  <CardHeader
    title="Demo Url Based Avatar"
    subtitle="Subtitle"
    avatar="http://lorempixel.com/100/100/nature/"/>
  <CardMedia overlay={<CardTitle title="Title" subtitle="Subtitle"/>}>
    <img src="http://lorempixel.com/600/337/nature/"/>
  </CardMedia>
  <CardTitle title="Title" subtitle="Subtitle"/>
  <CardActions>
    <FlatButton label="Action1"/>
    <FlatButton label="Action2"/>
  </CardActions>
  <CardText>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    Donec mattis pretium massa. Aliquam erat volutpat. Nulla facilisi.
    Donec vulputate interdum sollicitudin. Nunc lacinia auctor quam sed pellentesque.
    Aliquam dui mauris, mattis quis lacus id, pellentesque lobortis odio.
  </CardText>
</Card>
```

In particular, the actions API for react-toolbox's cards is rather inflexible at the moment. I think it makes sense to define these as subcomponents rather than a list of objects that automatically get rendered as buttons.

**Comment by nathanmarks** [comment]
Coming at the end of this weekend!

**Comment by javivelasco** [comment]
:dancer:

**Comment by nathanmarks** [comment]
@javivelasco I need to clean up and write docs but what's the overall plan here?

**Comment by EnzoMartin** [comment]
Any updates on this?
