### ISSUE TITLE
input error on css-next branch

### ISSUE THREAD

**Issue by claudiuapetrei** [react-toolbox/react-toolbox#950]
Input fields when adding error has a small glitch. It moves the elements below it a few pixels down. 

Is this the expected behavior or should the input field allocate the height needed to incorporate the error message without changing it's height ?

**Comment by javivelasco** [comment]
It's indeed expected as long as you are referring to the small height increase. The top should stay the same but if we reserve space for errors the Input would take too much space while pristine.
