### ISSUE TITLE
Second Button or IconButton fires submit event

### ISSUE THREAD

**Issue by carlitux** [react-toolbox/react-toolbox#953]
I have one Button with type submit and I created another Button/IconButton (I tested both) clicking on this fires the submit event on form.

EDIT: And if I add the onClick on the second button all input fields call this callback

**Comment by carlitux** [comment]
Changing onClick to onMouseUp fix the second error, now callback is only called when click on button.

But still on clicking this fires the on submit form event. 

BTW.- Maybe a bad reference on event delegation?

**Comment by javivelasco** [comment]
I guess it was happening because by default if the button has no type it seems like it submits the form if it's contained in it. I've added a default `type="button"` by default to `Button` when it has no `href` and therefore it's a `button` element.

**Comment by carlitux** [comment]
Thank you

**Comment by drager** [comment]
@javivelasco: This broke our application since all our buttons in a form is no longer of type submit. I do not get why this wasn't a major release.

**Comment by javivelasco** [comment]
Sorry about it @drager I never thought it would create an issue since having a submit button usually means adding the `type=submit`. I will try to get clean changelogs from the next release.

**Comment by drager** [comment]
@javivelasco: Great! Thanks for a great project.
