### ISSUE TITLE
Snackbar "icon" props does not effect

### ISSUE THREAD

**Issue by mitalcoi** [react-toolbox/react-toolbox#954]
```
<Snackbar
                active={true}
                icon="question_answer"
                label="Test"
            />
```
<img width="1173" alt="2016-11-11 10 58 46" src="https://cloud.githubusercontent.com/assets/3224226/20208237/dc8f2a36-a7fd-11e6-9902-eaf7b4ff4308.png">

**Comment by javivelasco** [comment]
It was removed because actually is out of the spec. You still can do it customizing content, see #925 and the related issue.
