### ISSUE TITLE
Example of rightActions/leftActions

### ISSUE THREAD

**Issue by TestKitt** [react-toolbox/react-toolbox#959]
What type of node should we use in the rightActions array prop for ListItems? Maybe we should put an example for this prop in the docs?

**Comment by rubenmoya** [comment]
As far as I know, you can use any type of node, I just tried a bunch of components (FontIcon, Button, IconButton, Avatar, List with ListItems, etc, and they worked...

**Comment by TestKitt** [comment]
Ok cool, I was just wondering if perhaps there was a node we should use. My use case was creating a menu using a the more-vert icon

**Comment by jacargentina** [comment]
The buttons look ugly (no right/left padding). copy paste this on the playground.

```
class ListTest extends React.Component {
  state = {
    checkbox: false
  };

  handleCheckboxChange = () => {
    this.setState({checkbox: !this.state.checkbox});
  };

  render () {
    return (
      <List selectable ripple>
        <ListSubHeader caption='Explore characters' />
        <ListItem
          avatar='https://dl.dropboxusercontent.com/u/2247264/assets/m.jpg'
          caption='Dr. Manhattan'
          legend="Jonathan 'Jon' Osterman"
          rightIcon='star'
        />
        <ListItem
          avatar='https://dl.dropboxusercontent.com/u/2247264/assets/o.jpg'
          caption='Ozymandias'
          legend='Adrian Veidt'
          rightIcon='star'
        />
        <ListItem
          avatar='https://dl.dropboxusercontent.com/u/2247264/assets/r.jpg'
          caption='Rorschach'
          legend='Walter Joseph Kovacs'
          rightIcon='star'
        />
        <ListSubHeader caption='Configuration' />
        <ListCheckbox
          caption='Notify new comics'
          checked={this.state.checkbox}
          legend='You will receive a notification when a new one is published'
          onChange={this.handleCheckboxChange}
        />
        <ListDivider />
        <ListItem caption='Contact the publisher' leftIcon='send' rightActions={[<Button primary raised icon='mail' label='Write E-mail'/>]} />
        <ListItem caption='Remove this publication' leftIcon='delete' />
      </List>
    );
  }

}

return <ListTest />;
```
![rightactions-bug](https://user-images.githubusercontent.com/517228/26978713-e5905812-4d02-11e7-8287-1bcb6b839402.png)

Look at the **"Contact the publisher"** below, the "Write E-Mail" button has no padding and looks ugly.

**Comment by matthewberkompas** [comment]
@jacargentina Just a note that if you have less text in the button on the list item, the padding works (see below).
<img width="125" alt="screen shot 2017-06-28 at 11 45 58 am" src="https://user-images.githubusercontent.com/7084294/27654609-718c72f8-5bf7-11e7-864c-36503a84cdea.png">
