### ISSUE TITLE
example of react-toolbox + webpack + babel 6 failing 

### ISSUE THREAD

**Issue by WellRedPandit** [react-toolbox/react-toolbox#96]
This has transpired during my attempt to introduce react-toolbox into a working app, but I have reduced the issue to bare minimum. Please take a look at [this repository](https://github.com/WellRedPandit/rtbx) that has a full example and a README with the steps to reproduce the error (a positive path is noted in the Comment section). Any help will be much appreciated!

**Comment by nathanmarks** [comment]
I submitted a pull request to your repo with a fix.

Webpack runs successfully now -- I haven't checked the finished product though.

**Comment by WellRedPandit** [comment]
@nathanmarks Webpack does totally run now! THANK YOU!!!

But I am totally flummoxed on two counts :-)

1. why must theme.scss be present? (though not used anywhere in my code; I did try to remove it, and of course, webpack failed)

2. to make the "product" :-) (it's just a react-toolbox hello world button on an empty page, nothing else), I run `cp app/scripts/index.html target/sandbox/` after webpack finishes and then I open index.html in Chrome. The app does show the button, but react complains:
![selection_050](https://cloud.githubusercontent.com/assets/3659381/11111535/ff41a536-88d7-11e5-8f7d-b83c61ddfc28.png)
and I've read the doc they refer to three times, but can't see a problem with my tiny little nothing of an app; if you could kindly take a look and set me on the right path, I would be GREATLY appreciate that!

**Comment by WellRedPandit** [comment]
Btw, there are no multiple copies of react:
```
> npm ls | grep react
UnifiedSearch@1.0.0 /bks/PROJECTS/reactjs_all/wellredpandit--rtbx_git
├─┬ babel-preset-react@6.1.4
│ ├── babel-plugin-transform-react-display-name@6.1.4
│ ├─┬ babel-plugin-transform-react-jsx@6.1.4
│ │ └── babel-helper-builder-react-jsx@6.0.15
│ └── babel-plugin-transform-react-jsx-source@6.1.4
├─┬ react@0.14.2
├── react-addons-css-transition-group@0.14.2
├── react-dom@0.14.2
├─┬ react-hot-loader@1.3.0
│ ├── react-hot-api@0.4.7
├── react-toolbox@0.11.5
```

**Comment by javivelasco** [comment]
@WellRedPandit about 1, it shouldn't fail. If you remove your theme, remember to remove also the `toolbox-loader` from your webpack config. We the second one happened to me it was actually loading two copies of React. Toolbox is configured with React as a `peerDependency` and the error shouldn't be happening because of it.... I would have to take a look in your repository to check and I need some time to do it.

I'll let you know if I figure out what's happening

**Comment by nathanmarks** [comment]
@WellRedPandit This fixes it, your external react was causing the issue.

https://github.com/WellRedPandit/rtbx/pull/2

**Comment by javivelasco** [comment]
Thanks @nathanmarks!
Closing

**Comment by WellRedPandit** [comment]
@nathanmarks 
@javivelasco 
I have accepted the PR with much gratitude! Learning a lot from you, guys, but decided to think a couple days before actually doing a merge (still a mystery to me though why external react is a problem; too deep for my current state of knowledge). 

My question is (sort of to myself): can I really go back to my team and say that in order to introduce react-toolbox they'd have to get rid of webpack externals? (and possibly refactor some code and build infrastructure - unlikely to be met with regard :-) or is there a way to keep the separation? - Any and all suggestions will be most appreciated.

**Comment by WellRedPandit** [comment]
Just wanted to let you know that the issue with external react seems to have nothing to do with react-toolbox - just bumped into it on another project (was getting "Only a ReactOwner can have refs." that disappeared as soon as I got rid of external react). Ok. Time to debug webpack :-)

Once again - thank you guys for your help! You are AWESOME!

**Comment by lycon2014** [comment]
Moving faward
