### ISSUE TITLE
Problem with button in Table component

### ISSUE THREAD

**Issue by kolacpav** [react-toolbox/react-toolbox#963]
Hi, I´am a newbie in React-toolbox and i have a simple question how can i insert Button inside the table component? I just found some topics about this but noone solved my problem. 

This solutions looks great ...
```
const users = [
  {name: 'Javi Jimenez', twitter: <Button label="@soyjavi" raised accent />, birthdate: new Date(1980, 3, 11), cats: 1},
  {name: 'Javi Velasco', twitter: <Button label="@javivelasco" raised accent />, birthdate: new Date(1987, 1, 1), dogs: 1, active: true}
];
```
... but there is one problem. I have a table with N elements and i need this button inside of each row, so the solution should be insert this <Button /> inside of predefined model. But how?

I just tried somethink like this:

```
const UserModel = {
  name: { type: String },
  twitter: { type: String },
  birthdate: { type: Date,
    title: 'Date of Birth' },
  cats: { type: Number },
  dogs: { type: Number },
  active: { type: Boolean },
  editButton: {
    header: 'Fav repo',
    render: () => (<Button label='@soyjavi' raised accent />), 
  },
  deleteButton: { title: ' ' },
};
```

But it doesnt work. Please help.

**Comment by javivelasco** [comment]
The `Table` implementation is not very flexible in the current release. We have a better implementation in the #666 thought. I'm updating and releasing a new version for it during the next days so I'd recommend to switch to 2.0 beta. Consider it hasn't a lot of changes, it's mostly in sync with dev apart from Table and Layout components so it's kinda bug free.

Please try it out and leave your feedback!
