### ISSUE TITLE
Docs Theme section proposal

### ISSUE THREAD

**Issue by xgarrett** [react-toolbox/react-toolbox#964]
Hello,

--- ORIGINAL QUESTION
I've noticed that [DatePicker](http://react-toolbox.com/#/components/date_picker) theme table is missing `label` property.

--- EDIT
Sorry if it's non issue, I've just found that `Feel free to take a look into the original themes or just check the selectors you want to override in DevTools.`

Could you please add this kind of information at the bottom of docs (under `theme`)?
It would be nice to see this if someone's just reading any component doc, not just a theming section.

Something like `If any property is missing you can check the selectors you want to override in DevTools.`.

P.S. Thank you for your hard work. This project is really great.

**Comment by borela** [comment]
@javivelasco It would be interesting to open source the website to enable people to fix the documentation faster.

**Comment by rubenmoya** [comment]
@borela It's already open sourced, you just have to edit the README.md of the component

**Comment by borela** [comment]
@rubenmoya Nice, didn't notice that, my bad.

**Comment by javivelasco** [comment]
Thank you @xgarrett !
