### ISSUE TITLE
css-next Layout Panel width ignores vertical scrollbar

### ISSUE THREAD

**Issue by patrick-jones** [react-toolbox/react-toolbox#965]
The css-next layout uses `right` on the `Panel` when the right `Sidebar` is open. But if the content in the panel is long enough to make the vertical scrollbar appear, then the sidebar extends on top of the panel by the width of the scrollbar. It also makes a spurious horizontal scrollbar appear (see bottom right of screenshot).

![right-sidebar](https://cloud.githubusercontent.com/assets/10633578/20312774/571660a2-ab1a-11e6-8fb7-042127416031.png)

**Comment by patrick-jones** [comment]
Upon further investigation I realized that the `Panel` is always too wide if the content is long enough to make the vertical scrollbar show. Note the unnecessary horizontal scrollbar in the attached screenshot.

This is because absolute positioning ignores the width of the scrollbar when calculating right; it starts at the right edge of the window whether there is a scrollbar or not. Just one of the things that makes CSS awesome.

![layout-ignores-scrollbar](https://cloud.githubusercontent.com/assets/10633578/20314386/ad826972-ab1f-11e6-945c-e9b0f4bbb6d6.png)

**Comment by javivelasco** [comment]
Please verify it works as intended!

**Comment by patrick-jones** [comment]
Changing min-width from 100vw to 100% did the trick
