### ISSUE TITLE
css-next Layout Panel does not support right Sidebar percentage-based widths

### ISSUE THREAD

**Issue by patrick-jones** [react-toolbox/react-toolbox#966]
In the new layout the `Panel` does not accommodate a right `Sidebar` that uses a percentage-based width. The right spacing is done in `rem`s rather than percentages, so the amount of overlap varies with how wide the window is.

![layout-sidebar-25pct](https://cloud.githubusercontent.com/assets/10633578/20313626/1dabcdea-ab1d-11e6-96f1-ed2e2017b854.png)

**Comment by javivelasco** [comment]
Please @patrick-jones verify it works now! You exactly know how it should work :)
