### ISSUE TITLE
How to expand cards with react-toolbox

### ISSUE THREAD

**Issue by sahas-** [react-toolbox/react-toolbox#967]
Sorry, this is not an issue. More of a feature request.

Does react-toolbox card component (http://react-toolbox.com/#/components/card) offer any expandable option similar to material-ui cards? (http://www.material-ui.com/#/components/card).

**Comment by javivelasco** [comment]
Not natively but I think it's not necessary to implement. The card can be considered as a mere container. You can place inside whatever you want making it collapsible. The only thing you might need is to add a transition to the card container so changing the animation would be smooth. But again, it does not require any work from react-toolbox side!
