### ISSUE TITLE
Bump `react` peerDependency.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [react-toolbox/react-toolbox#970]
`react@15.4.0` is out, but `react-toolbox` [does not accept it as a peerDependency](https://github.com/react-toolbox/react-toolbox/blob/dev/package.json#L120).

**Comment by ToniIltanen** [comment]
I just noticed the same thing.

**Comment by eskimoblood** [comment]
Is there any reason to lock it to a minor version at all. I think we can trust the react team to follow semver, so why not just lock it to the major version.

**Comment by larsts** [comment]
Same goes for react-addons-css-transition-group
