### ISSUE TITLE
Stop using rems for sizing

### ISSUE THREAD

**Issue by rohannair** [react-toolbox/react-toolbox#971]
Using rems forces everyone who is using this library to set their root font size to 10px. This seems like unnecessarily opinionated behaviour. For instance, if my root font size was 16px (the default root  font size):

```javascript
<body style={fontSize:'16px'}>
  <section style={fontSize:'10px'}>
    <Input />
  </section>
</body>
```
The computed font-size in my `Input` (1.6rem) would be 25.6px;

If react-toolbox used ems for everything, sizing would be relative to the parent component that last set font-size. The same `Input` above would then have a `10*1.6` = 16px font size.

The primary reason for this change would be to allow flexible interoperability with other UI libraries, because there are others that do not assume a default 10px root size.

**Comment by samsch** [comment]
You can configure the unit used in the [_globals.scss](https://github.com/react-toolbox/react-toolbox/blob/dev/components/_globals.scss#L15) file.

**Comment by rohannair** [comment]
It's not quite a drop-in library if I need to configure the globals. Especially if then I need to change my dev environment for (which, I ended up having to do because I'm using PostCSS).

**Comment by samsch** [comment]
I wonder if the impending styles migration #666 might end up being the solution that you want.

As far as drop in solutions though, I generally expect them to be opinionated in some ways. For example, Bootstrap (3) sets the <html> font size to 14px, and Bootstrap 4 sets it to 16px.

I think another thing to note is that the Material Design strictly specifies the sizes for fonts and other things, so I would expect that a library/framework implementing the spec would probably set those sizes.

**Comment by rohannair** [comment]
> I generally expect them to be opinionated in some ways
I totally agree with that. It's just that by using a `rem`, it's my root font-size. If react-toolbox's base font-size was `10px`, that would achieve the same intended effect (in terms of size ratios), but wouldn't be affected by how a user sets their roots.

Using your example, if I was to have Bootstrap 4 and react-toolbox, it would conform to the root size of 16px, and the react-toolbox sizing would be 1.6x the expected.

With that said, Bootstrap does set that root with a [static pixel size](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L234)

**Comment by samsch** [comment]
Well, I think #666 will probably be your answer. Until that is merged though, react-toolbox is just designed to be used in a sass modules dev environment, where it's easy enough to configure what you need to.

For what it's worth, I prefer using rems for sizing over ems.

**Comment by borela** [comment]
The #666 is the css-next branch, it stil uses `rem` [units.](https://github.com/react-toolbox/react-toolbox/blob/css-next/components/variables.css#L14)

**Comment by borela** [comment]
[You can import a file to every scss](https://github.com/react-toolbox/react-toolbox#using-sass-loader) using the loader and replacing the value of the [$unit](https://github.com/react-toolbox/react-toolbox/blob/dev/components/_globals.scss#L15) variable.

**Comment by javivelasco** [comment]
It's perfectly possible to configure unit to 10px and everything will work with one exception: the font sizes of generic selectors in `commons.scss`. This should be fixed so I'm going to label this as a bug and solve it for the next release.

**Comment by javivelasco** [comment]
Done already!
