### ISSUE TITLE
Tabs.js:118 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined

### ISSUE THREAD

**Issue by Triyugi** [react-toolbox/react-toolbox#978]
I want to use `react-toolbox` tabs and then make them to slide. For this, I have first created tabs which is working. But now, I want to make them scrollable. For this I am using `react-slick` plugin from https://github.com/akiran/react-slick but getting following error:

`Tabs.js:118 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined`

Current code is:

`import React, {Component} from 'react';`
`import ReactDOM from 'react-dom';`
`import {Tab, Tabs} from 'react-toolbox/lib/tabs';`
`import Slider from 'react-slick/lib/slider'`
`import 'slick-carousel/slick/slick.css'`
`import 'slick-carousel/slick/slick-theme.css'`

`class Labeltab extends React.Component {`
	`constructor() {`
    	`super();`
	   `this.state = {
			index: 0,
			fixedIndex: 0,
			inverseIndex: 0
	    };`
		`this.handleTabChange = this.handleTabChange.bind(this);`
		`this.handleFixedTabChange = this.handleFixedTabChange.bind(this);`
		`this.handleInverseTabChange = this.handleInverseTabChange.bind(this);`
		`this.handleActive = this.handleActive.bind(this);`
	`}`

  `handleTabChange (index) {
    this.setState({index});
  };`

 `handleFixedTabChange (index) {
    this.setState({fixedIndex: index});
  };`

  `handleInverseTabChange (index) {
    this.setState({inverseIndex: index});
  };`

  `handleActive () {
    console.log('Special one activated');
  };`

  `render () {`
	  `const settings = {`
		  `focusOnSelect: true,`
		  `infinite: true,`
		  `slidesToShow: 3,`
		  `slidesToScroll: 1,`
		  `speed: 500`
		`};`

 `return (`
      `<section>`
        `<Tabs index={this.state.index} onChange={this.handleTabChange}>`
		`<Slider {...settings}>`
          `<Tab label='Primary'><small>Primary content</small></Tab>`
          `<Tab label='Secondary' onActive={this.handleActive}><small>Secondary content</small></Tab>`
          `<Tab label='Third' disabled><small>Disabled content</small></Tab>`
          `<Tab label='Fourth' hidden><small>Fourth content hidden</small></Tab>`
          `<Tab label='Fifth'><small>Fifth content</small></Tab>`
		`</Slider>`
        `</Tabs>`
      `</section>`
   ` );`
  `}`
`}`
`module.exports = Labeltab;`

**Comment by borela** [comment]
Please create a repository with the code demonstrating the problem.

**Comment by javivelasco** [comment]
Shouldn't happen anymore and if it does it's probable not RT responsibility!
