### ISSUE TITLE
Component file naming conventions

### ISSUE THREAD

**Issue by nathanmarks** [react-toolbox/react-toolbox#98]
I'm not sure that naming every component `index.jsx` is the best idea, curious to hear your rationale.

In some parts of the React community, the generally accepted naming convention for component files is `ComponentName.jsx`.

This also means you can keep different components that are composed to create a specific "element" in the same folder, while keeping a consistent naming convention (for example, you may put all the form controls in the form folder).

Tying into an issue I created about making the cards more flexible, this is how I would set up the component folders were this my own project:

#### Folder structure

```
react-toolbox
--components
----card
------Card.jsx
------CardActions.jsx
------CardHeader.jsx
------CardMedia.jsx
------CardText.jsx
------CardTitle.jsx
------index.js
```

#### `index.js` contents

```javascript
export Card from './Card.jsx';
export CardActions from './CardActions.jsx';
export CardHeader from './CardHeader.jsx';
export CardMedia from './CardMedia.jsx';
export CardText from './CardText.jsx';
export CardTitle from './CardTitle.jsx';
```

#### Usage

```javascript
import React, { PropTypes } from 'react';
import {
  Card,
  CardActions,
  CardHeader,
  CardText
} from 'react-toolbox/components/card';

// your component class
```

Is this a file naming style that you dislike for any reason? I feel like it is much clearer than having **every** component in the library called `index.jsx`.

**Comment by javivelasco** [comment]
Make a lot of sense. I started creating the most basic components and they were composed by just one component file. In that first approach I've included the component directly in the `index.jsx` file. Then, when I get some bigger components I wasn't really following a convention and maybe I should.

Your proposal makes a lot of sense and it's going to be included in the next release.
Thanks for proposing it!! :smile:

**Comment by nathanmarks** [comment]
@javivelasco awesome! 

I've found with larger react projects, if you keep components in a flat structure it can become pretty unwieldy. 

For example, it's nice to be able to look for all form controls in a form folder rather than a components folder with 100 other components.

### Small problem

The only issue is providing backwards compatibility. You'll have to wait until the next major release as it is a breaking change. Thoughts?

**Comment by javivelasco** [comment]
Yes, in fact I'm going to create a major release next weekend with tons of changes :smile: I'm putting as much state as I can out of components to avoid methods (check `pure-components` branch). Maybe this would be a good opportunity to change the naming convention. What do you think?

**Comment by nathanmarks** [comment]
@javivelasco Definitely like that approach!

**Comment by javivelasco** [comment]
Great, we'll go for it!

**Comment by nathanmarks** [comment]
@javivelasco One thing, I'm 95% certain that the export style I used above requires the http://babeljs.io/docs/plugins/transform-export-extensions/ plugin. (It is also in the stage 1 presets).

**Comment by javivelasco** [comment]
Thanks for the advice! I guess that as soon as I start migrating I will figure that out :smile:

**Comment by nathanmarks** [comment]
@javivelasco Is it best to wait to contribute new/changed components until after the first major release given the potential restructuring?

**Comment by javivelasco** [comment]
Yes,  we are releasing it during the weekend. For now changes are happening in `pure-components`  branch.  Any feedback or contribution there is appreciated!

**Comment by wrench7** [comment]
I'd like to see the index.scss file renamed to match the name of the component as well. eg.
```index.scss -> ComponentName.scss```
This will ensure that when the classes are applied to the DOM, that the classname that appears in the DOM will actually match the Component it's being applied to. As it stands, "style__" is littered all over the DOM which is not very useful.

Great work with the library BTW, after looking at Material-UI for the last couple of weeks I can safely say I'm very impressed with the work you guys have all done :-)

**Comment by wrench7** [comment]
Curious whether you'd be open to a PR on my suggestion on renaming the style.scss files to match their components?

It would be far more readable having ```Button-icon___34ags``` in the DOM compared to ```style-icon___34ags``` as it stands at the moment. Happy to open another issue if that helps?

**Comment by javivelasco** [comment]
Sorry @wrench7 !! I forgot to answer. Here is the thing: when we have a complex component with multiple subcomponents it doesn't make sense to have different style files for each one because they usually depends one on another and the imports can be made with composition purposes.

I think it is possible to use the component name which would be enought for most cases. In such scenario we would need to import the file specifying the extension too because otherwise there would be conflicts between `Button.jsx`, `Button.scss`.

I'm going to do some tests to have more semantic classes in the DOM. Feel free to open an issue to track the progress.

**Comment by nathanmarks** [comment]
@javivelasco it could just be the name of the main component. A lot of people **do** do `Button.scss`. Having `scss` as an auto resolve module extension is strange -- most people i've seen using CSS modules don't do that as it's not as obvious at a glance.

**Comment by javivelasco** [comment]
Ok, I'll do some tests by naming the scss as the components and check how does it look like!

**Comment by wrench7** [comment]
Thanks for clarifying some more @javivelasco.

I like @nathanmarks also explicitly declare that the styles files are .scss ones, which makes it easier at a glance to see amongst the other js/jsx ones (which don't use a suffix).

I'm still forming some thoughts on the structure of components like List and Card which have "sub-components" that rely on the base components stylesheet. I'm coming from a BEM/SUITs terminology and still see some benefit in adhering to those naming conventions when possible.

**Comment by nathanmarks** [comment]
@wrench7 Which stylesheet are you referring to?

**Comment by wrench7** [comment]
Sorry, I'm referring to the ```styles.scss``` that all of the Toolbox components import. If they were named in a similar fashion to the components they're styling, then the classes generated by CSS modules in the DOM would be eminently more readable.

**Comment by javivelasco** [comment]
Yeah, as long as the imports are added with the extension I think there would be on problem with it. But still, for subcomponents we shouldn't split the styles because we cannot import them to target the clases from one subcomponent style file to another. That's the only thing to take into account IMO

**Comment by wrench7** [comment]
:+1:

**Comment by Rillus** [comment]
This appears to have been fixed by https://github.com/react-toolbox/react-toolbox/commit/26d7b8a6e8260ff80df7825815be9a7911b61718
