### ISSUE TITLE
"Autocomplete" page's playground will get 'TypeError' using IE 11

### ISSUE THREAD

**Issue by queryxl** [react-toolbox/react-toolbox#99]
[Autocomplete page](http://react-toolbox.com/#/components/autocomplete)
Click on "Load in playground", it will show 
```
TypeError: Object doesn't support property or method 'from'
```
Using IE 11, win10. Edge and Chrome works.

**Comment by javivelasco** [comment]
Ok! Thanks for reporting!

**Comment by nathanmarks** [comment]
@javivelasco FYI you can always use virtualbox + images from http://modern.ie

**Comment by javivelasco** [comment]
Very nice, I'll give it a try. Thanks @nathanmarks !

**Comment by nathanmarks** [comment]
@javivelasco If you have vmfusion or parallels, they tend to perform a bit better than virtualbox for these.
