### ISSUE TITLE
Components rendering very big

### ISSUE THREAD

**Issue by Tiwaz89** [react-toolbox/react-toolbox#998]
For some reason the components are rendering extremely big my side. This could be the intention of the author but looking at the 'react-toolbox-example' project there's no styling that overwrites the base styling making the components render smaller. I also can't find anyone else complaining that the components their side looks very big. 

![screen](https://cloud.githubusercontent.com/assets/12480236/20641421/18818c60-b400-11e6-8446-470caf21a39c.jpeg)

**Comment by rubenmoya** [comment]
Hi! I think you have to `import 'react-toolbox/lib/commons.scss';`
