### ISSUE TITLE
Checkbox onChange returns proxy, not value

### ISSUE THREAD

**Issue by DarkoKukovec** [react-toolbox/react-toolbox#999]
According to the documentation, the onChange function should get the value, but it gets a Proxy object instead.

Tested on 1.3.0, also happening in [the playground](http://react-toolbox.com/#/components/checkbox) (since the proxy object is truthy, the checkbox will always be checked)

I rolled back to 1.2.5 and everything works as expected.

**Comment by dryboy** [comment]
I am having a same issue. Seems like onChange is getting fired twice, and returns the proxy on the second run.

**Comment by Varnius** [comment]
Same
